### ISSUE TITLE
Text w/ % renders badly when formatted into eBook on Kindle

### ISSUE THREAD

**Issue by robogeek** [markdown-it/markdown-it#100]
I'm at Markdown-it 4.1.1 on AkashaCMS .. and recently created AkashaEPUB, a toolchain for building EPUB eBooks.  I wrote a guidebook on using AkashaEPUB, then put the guidebook on the Kindle market, and I just checked the book and it's properly formatted except for instances of `<%= title %>` and the like.

I can take the EPUB, view it in other EPUB readers and it's fine.  On the Kindle - Amazon converts the EPUB to their own MOBI format - the % is rendered on the page, but shifted to the right by about 15em's worth of distance.

The sequence is rendered by the system as this HTML

```
<pre><code>    &lt;h1&gt;&lt;%= title %&gt;&lt;/h1&gt;
</code></pre>
```

That's perfectly reasonable HTML for the input.

There are several variants of this as I included many different EJS sequences in the book.  The % character is always rendered quite a distance to the right of where it should be.

Any ideas on where to start?  I'm gonna take the same question over to a Kindle publishers forum ...

**Comment by puzrin** [comment]
No ideas. I an help only if `markdown-it` output is wrong. Not familiar with kindle and related things.

**Comment by puzrin** [comment]
Make sure you don't rely on tabs. All CM implementations convert those to 1-4 spases, depending on position.

**Comment by puzrin** [comment]
Closing - not related to this package, IMHO.
