### ISSUE TITLE
Convenient way to use markdown-it via cdn?

### ISSUE THREAD

**Issue by elibarzilay** [markdown-it/markdown-it#1001]
(Not sure whether this fits a bug, a feature request, or a question.)

I have my own system to convert md files dynamically to html, based on commonmark for years.  Markdown-it looks tempting to get some of the obvious extensions, but looks like neither CDNs have all of the plugins from the org.

Even better would be a common case for such a thing to get a package with all of these (all plugins under the markdown-it org) in a single bigger file.

---

Slightly less related: while digging into it, I also noticed that there's a whole bunch of duplicated code, like -ins and -mark being pretty much identical, and -sub + -sup too.  I'm sure that this doesn't help the benchmarking when these things are enabled, but more damagingly than that, there's some weird differences -- like the fact that `~~*x*~~` and `*~~x~~*` both work nicely, but only `*~x~*` works as expected.  

It could be nice to have a single customizable step where you could map open/close tokens to html tags, which could knock out all of `~~`, `++`, `==`, `~`, `^` (maybe also `*` etc) into one thing, which would behave the same, and probably be faster than doing each separately.

**Comment by rlidwka** [comment]
> but looks like neither CDNs have all of the plugins from the org

first one does:
https://www.jsdelivr.com/package/npm/markdown-it-ins

in addition, you can also try https://www.unpkg.com/
