### ISSUE TITLE
Improve code in `state_inline.mjs`

### ISSUE THREAD

**Issue by elibarzilay** [markdown-it/markdown-it#1003]
The code that decides on `can_open` and `can_close` could be simplified to the following:

```javascript
  const left_flanking =
    !isNextWhiteSpace && (!isNextPunctChar || isLastWhiteSpace || isLastPunctChar)
  const right_flanking =
    !isLastWhiteSpace && (!isLastPunctChar || isNextWhiteSpace || isNextPunctChar)

  const can_open  = left_flanking  && (canSplitWord || !right_flanking || isLastPunctChar)
  const can_close = right_flanking && (canSplitWord || !left_flanking  || isNextPunctChar)
```

IMO this is better because it shouldn't make a big impression on performance (other than reducing it), because the flanking part is the same as the commonmark origin, and because it is easier to read and follow the logic.

Making this an issue since I'm too lazy to make a PR that might be rejected if you prefer the current style.

**Comment by rlidwka** [comment]
okay, changed, thanks for the suggestion
