### ISSUE TITLE
Is it possible to get col number and row number of each token?

### ISSUE THREAD

**Issue by Jinjiang** [markdown-it/markdown-it#1006]
What I only have found about positions of tokens is `map`. However, I understand this just includes 2 line numbers, not exact the position (start col and row + end col and row) of every token.

So is it possible to do that or similar in markdown-it? I'm migrating a project from `remark-parse` + `unist` for some reasons. In `unist` it has a position object in each node https://github.com/syntax-tree/unist?tab=readme-ov-file#node

Thanks.

**Comment by puzrin** [comment]
That's not possible without full rewrite, see previous issues.
