### ISSUE TITLE
isString is not a function

### ISSUE THREAD

**Issue by JoeyBuddy27** [markdown-it/markdown-it#1007]
Hi,

All of a suddent yesterday we are getting errors everywhere we are using the library react-native-markdown-display. 

The error seems to be related to the dependency **markdown-it.**

Any ideas on a cause/fix?

Thanks.

![image](https://github.com/markdown-it/markdown-it/assets/63646507/61c517be-6520-4e2f-8ce2-f6046c035d48)

**Comment by puzrin** [comment]
There were no changes in this package and deps this time. Probably, may be other deps of your project.
