### ISSUE TITLE
Possible to strip markdown syntax from a string?

### ISSUE THREAD

**Issue by chrismbarr** [markdown-it/markdown-it#101]
I see that there is a `renderInlineAsText` renderer, but [the docs say not use use it](https://markdown-it.github.io/markdown-it/#Renderer.renderInlineAsText) since it's for internal use in `alt` tags.

However... if I were to ignore the warning, would it be possible to use this to strip markdown syntax out of a string?

Can
`This is some **bold** and _italics_ text`
be converted to
`This is some bold and italics text`
with this library?

**Comment by puzrin** [comment]
It was designed for another things and never tested/supported in this mode.

**Comment by puzrin** [comment]
Closing. Rendered to text was not investigated and implemented (out of this project goals). Probably, that should be a separate package.

**Comment by dessalines** [comment]
One method I'm using here, is to `renderInline`, then use  https://www.npmjs.com/package/html-to-text to strip out the html tags.
