### ISSUE TITLE
inline html transform error

### ISSUE THREAD

**Issue by yonecdeng** [markdown-it/markdown-it#1012]
The original md document：

```
   hello <picture>
     <source type="image/avif" srcset="https://picbed-1306720359.cos.ap-guangzhou.myqcloud.com/upic/2024-02-07-17-37-OUE54Z.webp?imageMogr2/format/avif">
     <img src="https://picbed-1306720359.cos.ap-guangzhou.myqcloud.com/upic/2024-02-07-17-37-OUE54Z.webp" alt="https://picbed-1306720359.cos.ap-guangzhou.myqcloud.com/upic/2024-02-07-17-37-OUE54Z.webp" loading="lazy"/>
   </picture>
```

The above will be converted to

```
   <p>hello <picture></p>
     <source type="image/avif" srcset="https://picbed-1306720359.cos.ap-guangzhou.myqcloud.com/upic/2024-02-07-17-37-OUE54Z.webp?imageMogr2/format/avif">
306720359.cos.ap-guangzhou.myqcloud.com/upic/2024-02-07-17-37-OUE54Z.webp" alt="https://picbed-1306720359.cos.ap-guangzhou.myqcloud.com/upic/2024-02-07-17-37-OUE54Z.webp" loading="lazy"/>
   </picture>
```

The correct one should be：

```
   <p>你好</p><picture>
     <source type="image/avif" srcset="https://picbed-1306720359.cos.ap-guangzhou.myqcloud.com/upic/2024-02-07-17-37-OUE54Z.webp?imageMogr2/format/avif">
306720359.cos.ap-guangzhou.myqcloud.com/upic/2024-02-07-17-37-OUE54Z.webp" alt="https://picbed-1306720359.cos.ap-guangzhou.myqcloud.com/upic/2024-02-07-17-37-OUE54Z.webp" loading="lazy"/>
   </picture>
```

**Comment by puzrin** [comment]
[seems to work](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%20%20%20hello%20%3Cpicture%3E%5Cn%20%20%20%20%20%3Csource%20type%3D%5C%22image%2Favif%5C%22%20srcset%3D%5C%22https%3A%2F%2Fpicbed-1306720359.cos.ap-guangzhou.myqcloud.com%2Fupic%2F2024-02-07-17-37-OUE54Z.webp%3FimageMogr2%2Fformat%2Favif%5C%22%3E%5Cn%20%20%20%20%20%3Cimg%20src%3D%5C%22https%3A%2F%2Fpicbed-1306720359.cos.ap-guangzhou.myqcloud.com%2Fupic%2F2024-02-07-17-37-OUE54Z.webp%5C%22%20alt%3D%5C%22https%3A%2F%2Fpicbed-1306720359.cos.ap-guangzhou.myqcloud.com%2Fupic%2F2024-02-07-17-37-OUE54Z.webp%5C%22%20loading%3D%5C%22lazy%5C%22%2F%3E%5Cn%20%20%20%3C%2Fpicture%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D)

[the same in reference commonmark parser](https://spec.commonmark.org/dingus/?text=%20%20%20hello%20%3Cpicture%3E%0A%20%20%20%20%20%3Csource%20type%3D%22image%2Favif%22%20srcset%3D%22https%3A%2F%2Fpicbed-1306720359.cos.ap-guangzhou.myqcloud.com%2Fupic%2F2024-02-07-17-37-OUE54Z.webp%3FimageMogr2%2Fformat%2Favif%22%3E%0A%20%20%20%20%20%3Cimg%20src%3D%22https%3A%2F%2Fpicbed-1306720359.cos.ap-guangzhou.myqcloud.com%2Fupic%2F2024-02-07-17-37-OUE54Z.webp%22%20alt%3D%22https%3A%2F%2Fpicbed-1306720359.cos.ap-guangzhou.myqcloud.com%2Fupic%2F2024-02-07-17-37-OUE54Z.webp%22%20loading%3D%22lazy%22%2F%3E%0A%20%20%20%3C%2Fpicture%3E)

**Comment by yonecdeng** [comment]
> [seems to work](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%20%20%20hello%20%3Cpicture%3E%5Cn%20%20%20%20%20%3Csource%20type%3D%5C%22image%2Favif%5C%22%20srcset%3D%5C%22https%3A%2F%2Fpicbed-1306720359.cos.ap-guangzhou.myqcloud.com%2Fupic%2F2024-02-07-17-37-OUE54Z.webp%3FimageMogr2%2Fformat%2Favif%5C%22%3E%5Cn%20%20%20%20%20%3Cimg%20src%3D%5C%22https%3A%2F%2Fpicbed-1306720359.cos.ap-guangzhou.myqcloud.com%2Fupic%2F2024-02-07-17-37-OUE54Z.webp%5C%22%20alt%3D%5C%22https%3A%2F%2Fpicbed-1306720359.cos.ap-guangzhou.myqcloud.com%2Fupic%2F2024-02-07-17-37-OUE54Z.webp%5C%22%20loading%3D%5C%22lazy%5C%22%2F%3E%5Cn%20%20%20%3C%2Fpicture%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D)
> 
> [the same in reference commonmark parser](https://spec.commonmark.org/dingus/?text=%20%20%20hello%20%3Cpicture%3E%0A%20%20%20%20%20%3Csource%20type%3D%22image%2Favif%22%20srcset%3D%22https%3A%2F%2Fpicbed-1306720359.cos.ap-guangzhou.myqcloud.com%2Fupic%2F2024-02-07-17-37-OUE54Z.webp%3FimageMogr2%2Fformat%2Favif%22%3E%0A%20%20%20%20%20%3Cimg%20src%3D%22https%3A%2F%2Fpicbed-1306720359.cos.ap-guangzhou.myqcloud.com%2Fupic%2F2024-02-07-17-37-OUE54Z.webp%22%20alt%3D%22https%3A%2F%2Fpicbed-1306720359.cos.ap-guangzhou.myqcloud.com%2Fupic%2F2024-02-07-17-37-OUE54Z.webp%22%20loading%3D%22lazy%22%2F%3E%0A%20%20%20%3C%2Fpicture%3E)
> 
> Make sure to enable html, it's disabled by default

![image](https://github.com/markdown-it/markdown-it/assets/73653404/b1e95473-a152-4c16-b3ad-c0799ef12e8e)

**Comment by yonecdeng** [comment]
> [seems to work](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%20%20%20hello%20%3Cpicture%3E%5Cn%20%20%20%20%20%3Csource%20type%3D%5C%22image%2Favif%5C%22%20srcset%3D%5C%22https%3A%2F%2Fpicbed-1306720359.cos.ap-guangzhou.myqcloud.com%2Fupic%2F2024-02-07-17-37-OUE54Z.webp%3FimageMogr2%2Fformat%2Favif%5C%22%3E%5Cn%20%20%20%20%20%3Cimg%20src%3D%5C%22https%3A%2F%2Fpicbed-1306720359.cos.ap-guangzhou.myqcloud.com%2Fupic%2F2024-02-07-17-37-OUE54Z.webp%5C%22%20alt%3D%5C%22https%3A%2F%2Fpicbed-1306720359.cos.ap-guangzhou.myqcloud.com%2Fupic%2F2024-02-07-17-37-OUE54Z.webp%5C%22%20loading%3D%5C%22lazy%5C%22%2F%3E%5Cn%20%20%20%3C%2Fpicture%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D)
> 
> [the same in reference commonmark parser](https://spec.commonmark.org/dingus/?text=%20%20%20hello%20%3Cpicture%3E%0A%20%20%20%20%20%3Csource%20type%3D%22image%2Favif%22%20srcset%3D%22https%3A%2F%2Fpicbed-1306720359.cos.ap-guangzhou.myqcloud.com%2Fupic%2F2024-02-07-17-37-OUE54Z.webp%3FimageMogr2%2Fformat%2Favif%22%3E%0A%20%20%20%20%20%3Cimg%20src%3D%22https%3A%2F%2Fpicbed-1306720359.cos.ap-guangzhou.myqcloud.com%2Fupic%2F2024-02-07-17-37-OUE54Z.webp%22%20alt%3D%22https%3A%2F%2Fpicbed-1306720359.cos.ap-guangzhou.myqcloud.com%2Fupic%2F2024-02-07-17-37-OUE54Z.webp%22%20loading%3D%22lazy%22%2F%3E%0A%20%20%20%3C%2Fpicture%3E)
> 
> Make sure to enable html, it's disabled by default

![image](https://github.com/markdown-it/markdown-it/assets/73653404/16c82bbe-d9ba-421e-91b9-1c11925bd9f9)
enable html definitely.But the result after compilation as shown above is wrong.

**Comment by puzrin** [comment]
1. Please use online demos to provide examples. As I did. And make it as minimal as possible. There are no `<p>` inside.
2. Please, check result in reference parser first. If behaviour is the same, it should not be posted here as bug - dig spec why this happens.
