### ISSUE TITLE
Bold can not be rendered with punctuation marks

### ISSUE THREAD

**Issue by yongman** [markdown-it/markdown-it#1013]
Markdown bold format can not be rendered. If we add a blank to the end bold mark (line 5) or remove the punctuation mark (line 6), the bold text can be rendered successfully.
```
* **开源：**代码是公开的，任何人可以查看、修改和贡献代码。
* **免费：**不需要付费使用，但可能需要付费获得商业支持。
* **安全性：**Linux 在安全方面是比较可靠，因为其内核是一个安全代码，不易被攻击。
* **稳定性：**Linux 是一个稳定可靠的操作系统，不会经常出现问题。
* **可扩展性：** Linux 是一个可扩展的操作系统，可以适应各种各样的设备。
* **自由度**Linux 是一个自由度高的操作系统，可以根据用户需求进行调整。
```
<img width="1179" alt="image" src="https://github.com/markdown-it/markdown-it/assets/3875656/3895e48a-6c14-49e2-8434-e0d4363e9f57">

**Comment by puzrin** [comment]
We follow CommonMark spec, and don't accept custom requests. Please read spec and address your proposals there. This package implements spec and don't discuss markup itself.

**Comment by tats-u** [comment]
Tentative solution: https://www.npmjs.com/package/markdown-it-cjk-friendly
