### ISSUE TITLE
Nested numbering not working as expected

### ISSUE THREAD

**Issue by srbhaski** [markdown-it/markdown-it#1016]
The markdown result for this markdown content should be as per screenshot below, but if we use the `markdown-it`, the numbering format and the indentation is lost and we get numbering from 1 to 9.

```
1. First item
    1. Sub-item
        1. Another sub-item
2. Second item
    1. Sub-item
        1. Sub-sub-item
        2. Another sub-item
    2. Sub-sub-item
3. Third item
```
<img width="642" alt="image" src="https://github.com/markdown-it/markdown-it/assets/54976344/e3600e87-f2b4-4c22-ac4d-1c600951f6fb">

**Comment by puzrin** [comment]
It works exactly as [reference parser](https://spec.commonmark.org/dingus/?text=1.%20First%20item%0A%20%20%20%201.%20Sub-item%0A%20%20%20%20%20%20%20%201.%20Another%20sub-item%0A2.%20Second%20item%0A%20%20%20%201.%20Sub-item%0A%20%20%20%20%20%20%20%201.%20Sub-sub-item%0A%20%20%20%20%20%20%20%202.%20Another%20sub-item%0A%20%20%20%202.%20Sub-sub-item%0A3.%20Third%20item). Please read CM spec and address all markup questions to commonmark forum. This package implements spec and not discuss desired markup behaviour.
