### ISSUE TITLE
How can I custom renderer tag?

### ISSUE THREAD

**Issue by dribble-njr** [markdown-it/markdown-it#1017]
I am trying to implement a blog with `chakra-ui` and `markdown-it`. 

Now I can parse markdown file to HTML with `markdown-it`, and I renderer as normal HTML tag like `<h1>` without any style. But I want to custom style with `chakra-ui` instead of write CSS code. 

How can I costom HTML tag to `chakra-ui` components. It seems like:

```markdown
## h2
```

```html
<Heading as={"h2"}>{...}</Heading>
```

I am trying to  change `md.renderer.rules` but I doesn't work. So does any other way to impletment it.

Thanks in advance.

**Comment by mikelecunio** [comment]
hey ill @dribble-njr have you found a fix to the issue, if not let me know, I am interest in helping you out.

**Comment by dribble-njr** [comment]
> hey I am interested in taking this issue on @dribble-njr , I know something about rendering issues in chakra-ui through a friend.

I solved this problem by [ChakraUIRenderer](https://github.com/mustaphaturhan/chakra-ui-markdown-renderer). Actually, it use `react-markdown` other than `markdown-it`.

Do you have some idea for rendering custom component with `markdown-it`?

**Comment by dribble-njr** [comment]
So it is also using another lib to render markdown. It seems that `markdown-it` does not provide similar capabilities?

**Comment by puzrin** [comment]
See this code https://github.com/markdown-it/markdown-it/blob/0fe7ccb4b7f30236fb05f623be6924961d296d3d/lib/renderer.mjs#L312-L316

Rendered check if the rule exists, and use default one if not. Just add your custom rules for `heading_open` and `heading_close`. Use [online demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%23%23%20heading%5Cn%5Cntext%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22debug%22%7D%7D) to investigate token names.

**Comment by druskus20** [comment]
This only works with some rules. 

for example, the rule for code fences hardcodes `<code>` 

https://github.com/markdown-it/markdown-it/blob/0fe7ccb4b7f30236fb05f623be6924961d296d3d/lib/renderer.mjs#L71
