### ISSUE TITLE
Does markdown-it depend on es5-shim for IE8 support? if so is there an independent version that works in IE8 without the es5-shim?

### ISSUE THREAD

**Issue by smoothlikejazz** [markdown-it/markdown-it#102]
Currently Integrating into our application, and running into IE8 issues when including the shim. I viewed the Demo and noticed that the es5-shim was included there, So I also included the es5-shim and markdown-it is working in our application in IE8, yet shim inclusion now breaks other aspects of our app. 

So i was wondering if there was a version of markdown-it that worked in IE 8, that doesn't depend on the es5-shim? If not could we update the readme to include information about the es5-shim dependency for IE support.

Thanks guys

**Comment by puzrin** [comment]
Yes, it uses es5. No plans to waste time for es3 support.

es5-shim is well known acceptable solution. Problems can be with es5-shAm but we don't use those features.
