### ISSUE TITLE
Is this a markdown-it thing or a commonmark thing?

### ISSUE THREAD

**Issue by abalter** [markdown-it/markdown-it#1020]
I have the following code:

```js
const regular = `
# Title  
text below  
`;

const with_htag = `
<h1>Title</h1>  
text below  
`;

const with_htag_and_newline = `
<h1>Title</h1>  

text below  
`;

const md_html = markdownit({html: true});
const md_no_html = markdownit({html: false});

const output = document.getElementById('output');
output.innerText = ""
  + "regular with html true: \n" + md_html.render(regular) + "\n"
  + "regular with html false: \n" + md_no_html.render(regular) + "\n"
  + "htag with html true: \n" + md_html.render(with_htag) + "\n"
  + "htag with html false: \n" + md_no_html.render(with_htag) + "\n"
  + "htag+nl with html true: \n" + md_html.render(with_htag_and_newline) + "\n"
  + "htag+nl with html false: \n" + md_no_html.render(with_htag_and_newline);
```

and output

```html
regular with html true: 
<h1>Title</h1>
<p>text below</p>

regular with html false: 
<h1>Title</h1>
<p>text below</p>

htag with html true: 
<h1>Title</h1>  
text below  

htag with html false: 
<p>&lt;h1&gt;Title&lt;/h1&gt;<br>
text below</p>

htag+nl with html true: 
<h1>Title</h1>  
<p>text below</p>

htag+nl with html false: 
<p>&lt;h1&gt;Title&lt;/h1&gt;</p>
<p>text below</p>
```

See [this codepen](https://codepen.io/abalter/pen/KKYBmZQ?editors=1111).

I don't understand why the text under the heading (closed h1 tag) does not get wrapped in a p tag. I tried adding extra spaces at the end of the first line.

However, if I add an extra line after the h1 tag, then the p tags seem to get wrapped properly.

I don't see why the behavior of `# Title` should be any different than `<h1>Title</h1>` if I am allowing HTML tags.

**Comment by rlidwka** [comment]
> Is this a markdown-it thing or a commonmark thing?

looks to me like a commonmark thing:
https://spec.commonmark.org/dingus/?text=%3Ch1%3ETitle%3C%2Fh1%3E%0Atext%20below

**Comment by abalter** [comment]
Or a bug in their code as well.

**Comment by abalter** [comment]
So I decided to ask: https://github.com/commonmark/commonmark-spec/issues/767
