### ISSUE TITLE
Increase maxNestsing or make it public

### ISSUE THREAD

**Issue by Guck1311** [markdown-it/markdown-it#1025]
Correct me if I'm wrong, but using the CommonMark preset allows you to use a `maxNesting` of 20, which allows me to use up to 19 blockquotes and up to 9 nested lists. Only 9 nested lists as lists use `ul` and `li` tokens. I implemented a custom written details summary plugin, which also allows me to use up to 9 (as my details contains a summary and a details_content token). When using those collapsibles together with e.g. lists, the `maxNesting` of 20 is reached pretty fast, but I can't increase it as, since it is internally protected. Would it be possible to increase it in the CommonMark preset or make it accessible when creating a MarkdownIt instance?

Best regards,
Marcel Burgstaller

**Comment by rlidwka** [comment]
> or make it accessible when creating a MarkdownIt instance?

It is accessible when creating a markdown-it instance:

https://github.com/markdown-it/markdown-it/blob/0fe7ccb4b7f30236fb05f623be6924961d296d3d/test/misc.mjs#L336

**Comment by puzrin** [comment]
You were provided a concrete test for this option. If something doesn't work - please be more descriptive instead of simple statement.
