### ISSUE TITLE
Escaping "#" at the end of heading

### ISSUE THREAD

**Issue by Djordjenp** [markdown-it/markdown-it#1029]
Hello I looked into your library and I found if we pass string like "# Hello World \\#" we get back header with text token "Hello World" so escaping hash is skipped because of this line in "heading" tokenizer:
```
  const tmp = state.skipCharsBack(max, 0x23, pos) // #
```
Is this how it's suppose to work because when I passed same string to "commonmark" demo, it got rendered like "Hello World #"

**Comment by rlidwka** [comment]
the output looks the same to me:

```
$ echo -e '# Hello World \#' | deno run -A npm:commonmark@0.31.0
<h1>Hello World #</h1>
$ echo -e '# Hello World \#' | deno run -A npm:markdown-it@14.1.0
<h1>Hello World #</h1>
```
