### ISSUE TITLE
Replacing renderer for image does not give href property

### ISSUE THREAD

**Issue by spank79** [markdown-it/markdown-it#103]
Hi, I tried to follow the example to replace vimeo links with the iframe code. But it doesn't work. tokens[idx].href is always undefined. 

I can see the url under tokens[idx].atrrs['src'].[2] but there is no href attribute...

How can I get it to work.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/token.js#L121

Attrs are array, not hash. Use token.attrIdx('href') to search.

**Comment by spank79** [comment]
thank you. Can you update the info here: https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer 

the code listed for vimeo doesn't work

**Comment by puzrin** [comment]
Ah, got it. Thank you for info! Take a look at updated code. Feel free to send PR with clarifications.

**Comment by spank79** [comment]
The updated code still contains an error:

aIndex = token.attrIndex('src'); should be used, am I right? There seems to be no href attribute and the function is attrIndex not attrIdx

**Comment by puzrin** [comment]
Yes. I had no time to test it.

**Comment by spank79** [comment]
created a PR :D
