### ISSUE TITLE
Renderer config in comment that applies only to part of a file

### ISSUE THREAD

**Issue by sghuang19** [markdown-it/markdown-it#1030]
This feature may be possible to be implemented with a plugin, but I haven't found one so far.

```markdown
<!-- markdown-it:breaks=true -->
Some text here
<!-- markdown-it:breaks=false -->
```

So that the line breaks are respected for this particular block of text.

**Comment by puzrin** [comment]
Macro directives are a higher abstraction layer and out of the project scope. I'd suggest splitting text before parsing, rendering each separate, and gluing back.
