### ISSUE TITLE
Ampersands being used as delimiters in query strings in links are getting URL encoded, they shouldn’t be

### ISSUE THREAD

**Issue by aral** [markdown-it/markdown-it#1031]
Markdown like the following:

```md
[a `<div>` inside a `<p>` tag](https://caninclude.glitch.me/caninclude?child=div&parent=p)
```

Gets rendered as:

```html
<p><a href="https://caninclude.glitch.me/caninclude?child=div&amp;parent=p">a <code>&lt;div&gt;</code> inside a <code>&lt;p&gt;</code> tag</a></p>
```

When it should be rendered as:

```html
<p><a href="https://caninclude.glitch.me/caninclude?child=div&parent=p">a <code>&lt;div&gt;</code> inside a <code>&lt;p&gt;</code> tag</a></p>
```

In other words, the ampersand being used as a delimiter in the query string should not be escaped as `&amp;` as this will break parameter parsing in the URL you’re hitting.

In this case, this is the incorrect link that’s being rendered (you can hit it to see the error):

- https://caninclude.glitch.me/caninclude?child=div&amp;parent=p

And this is the correct URL and its behaviour:

- https://caninclude.glitch.me/caninclude?child=div&parent=p

The following code reproduces the issue with the latest version on Markdown-it as installed from npm (14.1.0):

```js
import markdownIt from 'markdown-it'

const md = markdownIt()
const result = md.render('[a `<div>` inside a `<p>` tag](https://caninclude.glitch.me/caninclude?child=div&parent=p)')
console.log(result)
```
## Notes

- Related: https://github.com/markdown-it/markdown-it/issues/627
- Note that escaping the ampersand in Markdown (`\&`) does not disable this behaviour.
- It looks like the CommonMark spec doesn’t actually have a test for this use case (https://spec.commonmark.org/0.31.2/#link-reference-definitions) although there was discussion about it around nine years ago (https://talk.commonmark.org/t/need-clarification-for-links-escaping-unescaping/998).

    In this case CommonMark should implement URL escaping as per RFC 3986, which includes `&` in the set of reserved characters:

    > Percent-encoding a reserved character, or decoding a percent-encoded octet
   that corresponds to a reserved character, will change how the URI is
   interpreted by most applications.  Thus, characters in the reserved
   set are protected from normalization and are therefore safe to be
   used by scheme-specific and producer-specific algorithms for
   delimiting data subcomponents within a URI.
    >
    >  https://www.rfc-editor.org/rfc/rfc3986#section-2.2

## Workaround

Until this is fixed, in your own code, you can work around the issue (at the expense of performance) by replacing all ampersands in links with a token, carrying out the markdown rendering, and then replacing the tokens back with ampersands.

e.g., 

```js
import markdownIt from 'markdown-it'

let text = '# An example\n\nSome other stuff.\n\n[a `<div>` inside a `<p>` tag](https://caninclude.glitch.me/caninclude?child=div&parent=p)'

const linkRegExp = /(?:\[.*?\]\()(.*?)(?:\))/g
const ampersandToken

text = text.replace(linkRegExp, (_, $1) => {
  return $1.replace(/&/g, '\ue060')
})

const md = markdownIt()

let result = md.render(text)
result = result.replace(/\ue060/g, '&')

console.log(result)
```

Note that including some plugins may exhibit behaviour where your token also gets encoded. In that case, make sure you replace the encoded token.

e.g., From the version of the workaround I’m currently implementing for [Kitten](kitten.small-web.org):

```js
const linkRegExp = /\[(.*?)\]\((.*?)\)/g

/**
  Renders Markdown using given renderFunction while maintaining ampersands in links.

  @param {string} markdown
  @param { typeof markdownIt.render | typeof markdownIt.renderInline } renderFunction
*/
function render (markdown, renderFunction) {
  const result = renderFunction(markdown.replace(linkRegExp, (_, $1, $2) =>
    `[${$1}](${$2.replace(/&/g, '\ue0060')})`
  ))
  // One of the plugins we’re using is also encoding the token (this doesn’t happen in
  // plain Markdown-it) so, after the render, we replace the encoded version of the token.
  return(result.replace(/%EE%80%860/g, '&'))
}

const md = {}
md.render = (/** @type {string} */ markdown) =>
  render(markdown, markdownIt.render.bind(markdownIt))

md.renderInline = (/** @type {string} */ markdown) =>
  render(markdown, markdownIt.renderInline.bind(markdownIt))
```

**Comment by aral** [comment]
Related: https://github.com/markdown-it/markdown-it/issues/627

**Comment by aral** [comment]
It looks like the CommonMark spec doesn’t actually have a test for this use case (https://spec.commonmark.org/0.31.2/#link-reference-definitions) although there was discussion about it around nine years ago (https://talk.commonmark.org/t/need-clarification-for-links-escaping-unescaping/998).

In this case CommonMark should implement URL escaping as per RFC 3986, which includes `&` in the set of reserved characters:

> Percent-encoding a reserved character, or decoding a percent-encoded octet
   that corresponds to a reserved character, will change how the URI is
   interpreted by most applications.  Thus, characters in the reserved
   set are protected from normalization and are therefore safe to be
   used by scheme-specific and producer-specific algorithms for
   delimiting data subcomponents within a URI.


https://www.rfc-editor.org/rfc/rfc3986#section-2.2

**Comment by puzrin** [comment]
https://spec.commonmark.org/dingus/?text=%5Ba%20%60%3Cdiv%3E%60%20inside%20a%20%60%3Cp%3E%60%20tag%5D(https%3A%2F%2Fcaninclude.glitch.me%2Fcaninclude%3Fchild%3Ddiv%26parent%3Dp)

Isn't the result of the reference parser the same? If yes, it's better to create a ticket in the CM repo because here, we only implement the spec, not develop it.

**Comment by aral** [comment]
> it's better to create a ticket in the CM repo because here, we only implement the spec, not develop it.

Thanks, @puzrin, I’ll do that. Yes, this is a spec issue.

**Comment by aral** [comment]
This is an issue in my server not the CommonMark spec:

https://github.com/commonmark/commonmark-spec/issues/771

Closing. Sorry for the noise.
