### ISSUE TITLE
Punctuation affects bold parsing

### ISSUE THREAD

**Issue by luckymore** [markdown-it/markdown-it#1032]
`bold` is not resolved with zero, but I don't know which rule is affecting it

```js
var md = markdownit()
md.renderInline('**country:**Scotland')
// '**country:**Scotland'
```

**Comment by tats-u** [comment]
Commonmark, which markdown-it is based on, does not support this case.
This case is not covered by https://www.npmjs.com/package/markdown-it-cjk-friendly, but it may help you because it looks like you live in China.
