### ISSUE TITLE
Extract title (h1), and do not render it

### ISSUE THREAD

**Issue by mrleblanc101** [markdown-it/markdown-it#1036]
Hi,
I found markdown-it-title to extract the first h1. I use this metadata to render the title somewhere in my application.

Now, the problem is that when I render the markdown document, it results in my page having two h1.

How would I prevent the rendering of the first h1 (there should only be one, but just in case) of the document ?

**Comment by mrleblanc101** [comment]
I know I have to make a plugin and use the headings_open and headings_close, like in howhttps://github.com/markdown-it/markdown-it/issues/871 but I haven't figured out

**Comment by mrleblanc101** [comment]
My current solution that remove the `<h1>`, `</h1>`, `textcontent` and the wrapping anchor added by `markdown-it-anchor`:
```
    const proxy = (tokens, idx, options, env, self) => self.renderToken(tokens, idx, options);
    const defaultHeadingOpenRenderer = md.renderer.rules['heading_open'] || proxy;
    const defaultHeadingCloseRenderer = md.renderer.rules['heading_close'] || proxy;
    md.renderer.rules['heading_open'] = function (tokens, idx, options, env, self) {
        if (tokens[idx].tag === 'h1') {
            tokens[idx].map.forEach((item) => {
                tokens[item].hidden = true;
                tokens[item].children = [];
            });
        }
        return defaultHeadingOpenRenderer(tokens, idx, options, env, self);
    };
    md.renderer.rules['heading_close'] = function (tokens, idx, options, env, self) {
        if (tokens[idx].tag === 'h1') {
            tokens[idx].hidden = true;
        }
        return defaultHeadingCloseRenderer(tokens, idx, options, env, self);
    };
    console.log(md.render('# h1 \n ## h2 \n ### h3 \n #### h4 \n ##### h5 \n ###### h6'));
    ```

**Comment by puzrin** [comment]
You could add a plugin to the core chain after the block parser (https://github.com/markdown-it/markdown-it/blob/master/lib/parser_core.mjs#L21), scan tokens, and remove the first range from `heading_open` to `heading_close.` In parallel, you can store the removed data in `env` for future needs or continue using the plugin you have now for this task.

As you can see, the core chain now has some rules for tweaking content after generic parsers (block + inline). Your plugin can be something like this.
