### ISSUE TITLE
[xx]:xx   This format cannot be parsed

### ISSUE THREAD

**Issue by zjw1253527299** [markdown-it/markdown-it#1038]
https://github.com/user-attachments/assets/03404b2c-8208-450f-8e24-843e974d38ee

**Comment by zjw1253527299** [comment]
Is this a bug or is it by design?

**Comment by puzrin** [comment]
https://spec.commonmark.org/dingus/?text=%5Bxx%5D%3Axx%0A%0A123

I think, by design, looks like reference
