### ISSUE TITLE
Disable line numbers in code blocks?

### ISSUE THREAD

**Issue by Trippnology** [markdown-it/markdown-it#1042]
Is it possible to disable line numbers in code blocks? I'm using markdown-it in the terminal (via [cli-markdown](https://github.com/grigorii-horos/cli-markdown)) and copying code means that the line numbers get copied too.

Apologies if this is a noob question, I did scour the docs, but couldn't find anything.

**Comment by puzrin** [comment]
Probably worth contact authors of that package. Markdown-it does not add any line numbers in code block. Probably, that's a result of customized code highlighter (not about this library)
