### ISSUE TITLE
How do i load markdown-it as ESM module in a browser without CDN?

### ISSUE THREAD

**Issue by markg85** [markdown-it/markdown-it#1044]
Hi,

I hear that ESM is the way to go in JS these days.
So i thought, lets try it in a new pet project.

Hours later i'm just freaking stuck loading damned javascript file. Yes, this is frustrating.

Let me be explicit and super clear that i'm trying this as a **static** page in plain simple html/js in a browser. There is no nodejs involved in this at all! I like to keep it that way.

Now i'm gonna be a "little" stuborn because this works:
```js
import markdownIt from 'https://cdn.jsdelivr.net/npm/markdown-it@14.1.0/+esm'
```

But i'm not gonna use that because i want to be able to build the ESM myself. I don't want to use a CDN.

But the distribution files of markdown-it (build using `npm run build`, and yes, this is the **only** nodejs i did, only to build it because this project doesn't provide the dist files sadly .. why?). The files it generates seem to be anything but ESM (honestly, i lost the plethora of module-like-3-letter-abbreviations, CJS, AMD, UMD, ESM... sjees).

Sorry for the snarky comment but i'm sure it's somewhat understandable after a couple hours of trying with no progress of something that seems so simple. Heck, i even had to - yes had to - use a webserver because imports apparently must obey the cross origin policy, a local html file in your browser (so just opening index.html and go with it) isn't enough for that anymore.

Best regards,
Mark

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/package.json#L40 dist files are provided in published versions. Just install published version. Content looks something like this https://unpkg.com/browse/markdown-it@14.0.0/, with `dist/` and so on.
