### ISSUE TITLE
Seems Like HTML <br/> Isn't Respected 100%

### ISSUE THREAD

**Issue by johnnyshankman** [markdown-it/markdown-it#1046]
```js
import markdownIt from 'https://cdn.jsdelivr.net/npm/markdown-it@14.1.0/+esm'
const md = markdownIt({
  html: true,
  linkify: true,
  typographer: true
});
const result = md.render(`# The Title <br/> the body`);
```

The result does not contain a new line and skips over the BR then renders everything as one big header.

Is this spec?

![Screenshot 2024-08-29 at 2 52 13 PM](https://github.com/user-attachments/assets/dccf1ee4-07d5-4e3c-aa6f-55af09d5b7eb)

**Comment by johnnyshankman** [comment]
For the record it will respect <br/> in other later spots:

```
import markdownIt from 'https://cdn.jsdelivr.net/npm/markdown-it@14.1.0/+esm'
const md = markdownIt({
  html: true,
  linkify: true,
  typographer: true
});
const result = md.render(`# The Title \n the body <br /> a new line`);
```

produces what i would expect

![Screenshot 2024-08-29 at 2 53 35 PM](https://github.com/user-attachments/assets/d3129f03-c782-4e0f-8b61-e7f5c89ee81d)

**Comment by johnnyshankman** [comment]
Identical behavior in commonmark mode. This seems odd bc to me this should be reasonably unambiguous syntax and yet none of the parsers understand it.

**Comment by rlidwka** [comment]
It is indeed unambiguous syntax. Header starts with `#` and ends with newline (\r or \n).

So this: `# The Title <br/> the body`

Produces this: `<h1>The Title <br/> the body</h1>`

Markdown treats `<br>` as any inline tag, and copies it to output as is (so it becomes part of the header).

**Comment by mask2012** [comment]
same problem, coud it be solved anyway?

**Comment by johnnyshankman** [comment]
@mask2012 not worth it, outside of the Markdown standard, you'll run into headaches unless you're only supporting a subset of markdown (like just paragraph tags).
