### ISSUE TITLE
Zero-indexed numbered list not recognized without a leading empty line

### ISSUE THREAD

**Issue by mik-jozef** [markdown-it/markdown-it#1047]
The following two render correctly as lists of two items

```markdown
This is text

0. zeroth item
1. first item
```

```markdown
This is text
1. first item
2. second item
```

while this one does not

```markdown
This is text
0. zeroth item
1. first item
```

Screenshot from [the live editor](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22This%20is%20text%5Cn0.%20zeroth%20item%5Cn1.%20first%20item%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D):
![image](https://github.com/user-attachments/assets/89b8bec0-6df4-4843-acb5-b2f8072076f7)

I believe this is a bug

**Comment by rlidwka** [comment]
Working exactly as intended, see https://spec.commonmark.org/0.31.2/#list for details

*In order to solve the problem of unwanted lists in paragraphs with hard-wrapped numerals, we allow only lists starting with 1 to interrupt paragraphs.*

See also examples 304 and 305.
