### ISSUE TITLE
Can we differentiate inline and block <code> rendering

### ISSUE THREAD

**Issue by cawoodm** [markdown-it/markdown-it#1048]
We are using markdown-it followed by highlight-js to render code. For block code this works as desired but we do not want inline code handled this way. Unfortunately highlight-js targets all `<code>` entities.

Is there a way to tell markdown-it to render `inline code` with a different tag?

![image](https://github.com/user-attachments/assets/984b2644-c546-4578-b686-c5ca62714929)

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.mjs#L13 just override approproate rule.
