### ISSUE TITLE
`parse` failing to tokenize "[a]: a"

### ISSUE THREAD

**Issue by celestine-stripe** [markdown-it/markdown-it#1050]
Hello! I'm using `markdown-it` version 14.1.0 and ran into a few edge cases where `parse` is failing to produce any tokens. Here's a script to reproduce the bug:

```ts
import markdownit from 'markdown-it';

const md = markdownit();

const cases = [
  '[aaa]: aa aaa.',
  '[aaa]: aa aaa',
  '[aaa]:',
  '[aaa]: ',
  'aaa: aa',
  '[aaa: aa',
  '[aaa] a.',
  '[]:',
  '[]: \n',
  '[]: .',
  '[[aaa]: a',
  '[]: a',
  '[ ]: a',
  'a [a]: a',
  // Cases below fail
  '[aaa]: aa',
  '[aaa]: a.',
  '[a]: a',
  '[.]: a',
];

cases.forEach((text) => {
  if (md.parse(text, {}).length === 0) {
    console.log(`Failed to sucessfully parse "${text}"`);
  }
});
```

The output is:
```
Failed to sucessfully parse "[aaa]: aa"
Failed to sucessfully parse "[aaa]: a."
Failed to sucessfully parse "[a]: a"
Failed to sucessfully parse "[.]: a"
```

I can repro the behavior using https://markdown-it.github.io/ as well!

**Comment by rlidwka** [comment]
What tokens did you expect to get?

----

It's a [link reference definition](https://spec.commonmark.org/0.31.2/#link-reference-definition). It's not supposed to produce any tokens itself, instead it affects how other links are parsed (no links = no output).

You can see results in env instead:

```js
import markdownit from 'npm:markdown-it';

const md = markdownit();

let env = {};

console.log(md.parse("[a]: a", env));
// []
console.log(env);
// { references: { A: { title: "", href: "a" } } }
```

I think there was a discussion to make it a token anyway (for roundtripping and such), but that's not a bug, and rather lack of feature.

**Comment by celestine-stripe** [comment]
Oh interesting! Hm, so I was expecting:
```ts
md.parse('[aaa]: aa aaa', {})
```
to produce:
```ts
[
  {
    "type": "paragraph_open",
    "tag": "p",
    "attrs": null,
    "map": [
      0,
      1
    ],
    "nesting": 1,
    "level": 0,
    "children": null,
    "content": "",
    "markup": "",
    "info": "",
    "meta": null,
    "block": true,
    "hidden": false
  },
  {
    "type": "inline",
    "tag": "",
    "attrs": null,
    "map": [
      0,
      1
    ],
    "nesting": 0,
    "level": 1,
    "children": [
      {
        "type": "text",
        "tag": "",
        "attrs": null,
        "map": null,
        "nesting": 0,
        "level": 0,
        "children": null,
        "content": "[aaa]: aa aaa",
        "markup": "",
        "info": "",
        "meta": null,
        "block": false,
        "hidden": false
      }
    ],
    "content": "[aaa]: aa",
    "markup": "",
    "info": "",
    "meta": null,
    "block": true,
    "hidden": false
  },
  {
    "type": "paragraph_close",
    "tag": "p",
    "attrs": null,
    "map": null,
    "nesting": -1,
    "level": 0,
    "children": null,
    "content": "",
    "markup": "",
    "info": "",
    "meta": null,
    "block": true,
    "hidden": false
  }
]
```

For additional context, we figured this was a "bug" when `parse` failed to produce tokens for the Japanese string `'[プロダクトのご紹介]: ユーザー体験がどのようなものかを貴社とサポートチームが把握できるように、プロダクトの主要な機能の概要を紹介します。'`.  But looking at it more now, I think we just have a malformed string, so I'm going to close this issue! Thank you!

**Comment by h7kanna** [comment]
> I think there was a discussion to make it a token anyway (for roundtripping and such), but that's not a bug, and rather lack of feature.

Hi, Is there a reference to this discussion. and if it is still planned to be added as a feature.
I am interested in contributing a PR for the same. I need [link reference definition](https://spec.commonmark.org/0.31.2/#link-reference-definition) in the token stream.
