### ISSUE TITLE
Image is wrapped in paragraph, how to disable that?

### ISSUE THREAD

**Issue by markg85** [markdown-it/markdown-it#1052]
Hi,

I'm working on a static markdown renderer. It's the HedgeDoc render style but static.
You can find my rendering result here: https://static-hedgedoc.sc2.nl/ and the code for it lives here https://github.com/markg85/static-hedgedoc/blob/main/js/static-hedgedoc.js

To spare you going over all of it, the important bits:
```js
const md = markdownIt({
  html: true,
  breaks: true,
  langPrefix: '',
  linkify: true,
  typographer: true,
  highlight: highlightRender
})...
```

This renders:
```md
![Minion](https://octodex.github.com/images/minion.png)
```
as:
```html
<p>
    <img src="https://octodex.github.com/images/minion.png" alt="Minion">
</p>
```

I want to render it as:
```html
<img src="https://octodex.github.com/images/minion.png" alt="Minion">
```

For a bit of context as it might be worth it to get an understanding of what i'm trying to do.
I am trying to make a markdown component of the bootstrap [cards](https://getbootstrap.com/docs/4.1/components/card/). For reference, it's html looks like:
```html
  <div class="card">
    <img class="card-img-top" src=".../100px180/" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
```
Note the `img` element in there. I can't have it wrapped in a paragraph yet that's what markdown-it does by default. Thus i'm looking for a way to remove that behavior. I'm fine if that would have to be done in code for that component i'm making but how?

**Comment by puzrin** [comment]
In general, there are no way to "just disable paragraph wrap in some part of text", because this does not fit into "markdown spirit".

- You can manually call an inline parser/renderer if you need to proceed with inline content.
- You can post-process on the HTML level after the markdown call.
