### ISSUE TITLE
Please consider adding async support!

### ISSUE THREAD

**Issue by markg85** [markdown-it/markdown-it#1053]
Hi,

Please consider giving us async/await support!

Currently this is impossible:
```js
md.renderer.rules.fence = async (tokens, idx, options, env, self) => {
}
```

But if you change the `Renderer.prototype.render`: method to
```js
Renderer.prototype.render = async function (tokens, options, env) {
  let result = ''
  const rules = this.rules

  for (let i = 0, len = tokens.length; i < len; i++) {
    const type = tokens[i].type

    if (type === 'inline') {
      result += this.renderInline(tokens[i].children, options, env)
    } else if (typeof rules[type] !== 'undefined') {
      result += await rules[type](tokens, i, options, env, this)
    } else {
      result += await this.renderToken(tokens, i, options, env)
    }
  }

  return result
}
```

Then it already works and is already so much more helpful.

With this minor change you **maintain** the sync nature of the parser but **allow** async code to be used.
For example, i want on-the-fly loading of syntax highlighting files. The best way is to do this while rendering as it literally is a render step. But that is impossible as loading a file and and importing it as a js module at some point in the chain is going to be async. So the solution, as you also described on your FAQ and what i am currently doing too, is having a post rendering function. Yeah sure that works... But it adds a lot of bookkeeping to have that post rendering work as intended.

So please. Consider giving us async support! You lose nothing (sync rendering stays as-is) but we - your users! - win a lot. It's not like i'm the first to request it.

**Comment by puzrin** [comment]
Sorry, no plans to change sync API to async. You still can do [ manual parser call + async ops + manual render call ]. Or even completely replace renderer with your custom anync version.

**Comment by markg85** [comment]
You might want to reconsider your, perhaps overly, conservative to changes in this project. I get being conservative if it means changing API calls.

But this request isn't doing that. It allows it, yes, but it's essentially still sync. You could even go for it and just not document it making it an undocumented (experimental) feature.

The value in this project is it adhering to the commonmark spec and the project being stable. But not progressing along with how js is progressing (async support is a must these days) will put you at risk of getting forked at some point by a dev who is annoyed enough by it to go that path. I already have a few patches on top of markdown-it which already make me think: "if i add any more patches i might as well fork". I agree with your stance of preferring plugins over API changes but you need to provide a minimal set of features. Async/await support qualifies as minimal which should be handled by markdown-it itself, not a plugin.

It would be awesome if you could reconsider this.

**Comment by DanteCoder** [comment]
> Sorry, no plans to change sync API to async. You still can do [ manual parser call + async ops + manual render call ]. Or even completely replace renderer with your custom anync version.

Hi @puzrin , I'm trying something similar to Mark with a fence rule:
```javascript
const plugin: PluginSimple = (markdownIt) => {
  const defaultRender =
    markdownIt.renderer.rules.fence ?? ((tokens, idx, options, _env, self) => self.renderToken(tokens, idx, options));

  markdownIt.renderer.rules.fence = (tokens, idx, options, env, self) => {
    const token = tokens[idx];

    if (token.info !== 'bible') {
      return defaultRender(tokens, idx, options, env, self);
    }

    // Some async logic that returns HTML
    // that I want to render

    return 'Loading Bible quote...';
  };
};
```
This is for another plugin for the Joplin app, which in turn injects this markdown plugin.
The async logic is very fast but needs to be done in the main Joplin plugin. I have written a small script to send and receive messages through the Joplin and Markdown-it plugins.

How would you suggest that I implement the manual render call when I already have the HTML? or do you have any suggestions for my implementation?
I don't see an obvious way to do a manual render of HTML in the docs.

**Comment by puzrin** [comment]
See https://github.com/markdown-it/markdown-it/blob/master/docs/development.md#faq

https://github.com/markdown-it/markdown-it/blob/0fe7ccb4b7f30236fb05f623be6924961d296d3d/lib/index.mjs#L527-L531

Default `.render()` calls parser + renderer. You and do that manually, and insert some async ops between. That's a documented approach. Not ideal, but useable enougth.

**Comment by DanteCoder** [comment]
I see what you mean, this would be great if I had access to the renderer to manually trigger it after the async work is done, but that is handled internally by Joplin.
Joplin only [exposes the MarkdownIt instance to the plugins](https://github.com/laurent22/joplin/blob/dev/packages/app-cli/tests/support/plugins/content_script/src/markdownItTestPlugin.ts#L5) to add or modify rules. I've also tried replacing the renderer `render` method as Mark suggests, but this messes up with Joplin because it doesn't expect a promise.

Perhaps I need to take this issue with Joplin? Or maybe I'm missing something that could be done just from the md plugin.

**Comment by markg85** [comment]
@DanteCoder There's a simple fix for it (it's getting more complex for each fix though).

Just test if the callback you pass in it a function. If it is just call it, if it's not then assume it's a promise and await it. That gives you backwards compatibility. You can be strict and test more explicitly for the promise.

**Comment by DanteCoder** [comment]
@markg85 I ended up doing a post-render replacement, as [suggested](https://discourse.joplinapp.org/t/async-markdown-it-plugin/41155/2?u=dantecoder) by a Joplin contributor and by the [FAQs](https://github.com/markdown-it/markdown-it/blob/master/docs/development.md#i-need-async-rule-how-to-do-it). My problem as that I couldn't figure out how to do that in a Joplin plugin.

**Comment by s-light** [comment]
i found a more complete example of the FAQ suggestion at
https://github.com/markdown-it/markdown-it/issues/256#issuecomment-224700130
