### ISSUE TITLE
Fence extraction into new rules + helper callback

### ISSUE THREAD

**Issue by markg85** [markdown-it/markdown-it#1054]
Hi,

I couldn't find this so i'm assuming it's not possible yet.
And i couldn't find much discussion besides potentially [this](https://github.com/markdown-it/markdown-it/issues/46) (from nearly 10 years ago by now)

For syntax highlighting i'm overriding the fence rule and specify a highlight function.
That seems to be how things are supposed to be done so i'm just following by example.

However, i like a little more control. My fence override is beginning to have some if/else and switches to do special things for some specific fences. This makes me curious why we don't have a more fine-grained fence rule. Here's an example of what i mean, say with these markdowns fence blocks:

~~~plain
```js
// .. js code
```

```mermaid
// mermaid syntax
```
~~~

If i would have fences like:
```js
md.renderer.rules.fence.js = async (tokens, idx, options, env, self) => {
}

md.renderer.rules.fence.mermaid = async (tokens, idx, options, env, self) => {
}
```

Or even as optional blocks (note the `?.` notation):
```js
md.renderer.rules.fence?.js = async (tokens, idx, options, env, self) => {
}

md.renderer.rules.fence?.mermaid = async (tokens, idx, options, env, self) => {
}
```

Either of those options would be quite a bit cleaner.

But it can be even cleaner. Clearly this is intended for syntax highlighting. Now when you highlight you will have a list of syntax definitions you support (not loaded yet, just a list). And for that you might want to have another nice helper functions. A function that is being called as callback _before_ a fence handler is going to be called. I'd propose a function like this in the markdown-it configuration:

```js
const md = markdownIt({
  html: true,
  breaks: true,
  langPrefix: '',
  linkify: true,
  typographer: true,
  highlight: highlightRender,
  fenceNameCallback: async (fenceName) => {
    if (['js', 'mermaid', 'cpp'].includes(fenceName)) {
      // syntax load check, etc...
      md.renderer.rules.fence[fenceName] = (tokens, idx, options, env, self) => {
        // highlight
      }
    }
  }
}).use(...)
```

**Obviously** this is just some mockup to show the intent. You need a little more to make this work properly but that's on the users of this library, not for the library itself.

What you end up with is a very clean neat mechanism to support syntax highlighting. It's just a "make it easier and better" suggestion, it's not vitally important though it would be very nice to have.

What do you think?

**Comment by puzrin** [comment]
I think creating plugins instead of inventing new api-s is preferred and recommended way for this project. You can create a plugin for advanced fences rendering, if you wish. It can check info string and select any custom render. By default, everything doable via plugins is rejected from core, to keep API simple and clear.

**Comment by puzrin** [comment]
Bro, your posting in this tracker looks like you used this library for a very short period and ask for new features before understanding concepts. Please be patient and constructive. Investigate how to use existing possibilities before sharing your ideas about API changes.

> But it appears that child tokens are not being send through the rules mechanism.

Fences are one of the minimal markdown markup units. They are not splittable and can not have children (other markdown elements). Children are parts of markdown containers—paragraphs, lists, and so on. Fences are NOT containers; they are "blob wrappers."

**Comment by markg85** [comment]
I've been using it for just a couple of weeks but rather intensely. Mostly to rebuild the style of HedgeDoc to create a [static parser](https://github.com/markg85/static-hedgedoc). That works and now i try to enrich it's features for my own purposes. In my opinion, and in the spirit of markdown, it's intended to be a fast developer friendly way to write neat documents. You [might disagree](https://github.com/markdown-it/markdown-it/issues/1052) on what i try to do with it and that's perfectly fine. I however intent to support writing quite rich formatted documents while preserving the ease of the markdown syntax. One of the first things i did is [writing and implementing a progressbar extension](https://static-hedgedoc.sc2.nl/?mdfile=specs/progress_bar.md) because i hate using images for that, which sadly is common in markdown as it simply lacks that feature.

I admit my patience is lacking a little ;) But hey, you yourself point to a FAQ which essentially says "not possible, use a post-parser to get what you want". Not the exact quote but that's what it boils down to. If i'm hitting that issue, which i do with syntax highlighting, then i think i'm deep enough into the tech already to ask for an API change. I did my research and know you've rejected it multiple times already. I disagree strongly on that and am therefore putting in the time and effort to try and convince you with constructive arguments (i think i did that, what wasn't constructive in your view?) to sway you to support this on an API level.

I agree that my understanding of your API is on the fresh side and i don't fully know all of it yet so i'm sorry if some of it (like the above children thing) is a silly rookie mistake in hindsight. I hope that we can constructively work on API changes where needed.

This very post (and https://github.com/markdown-it/markdown-it/issues/1053) are both constructive. Especially the linked post is a feature many people in the past asked from you too. Being constructive goes both ways. If you just close it because you think post-processing is the way then the argument of being constructive kinda rapidly loses it's value. I think I've been constructive here and [there](https://github.com/markdown-it/markdown-it/issues/1053), I hope you can be too. I can totally imagine the request i made here is too specific and you'd close it for that, but i can't see that for https://github.com/markdown-it/markdown-it/issues/1053.
