### ISSUE TITLE
Markdown-it is gone from npm registry, breaking the installations

### ISSUE THREAD

**Issue by piotr-tomczyk-appfire** [markdown-it/markdown-it#1069]
Installation of our application have started to fail today, I noticed that npmjs page for the library https://www.npmjs.com/package/markdown-it shows 404.
Can this be resolved urgently?

**Comment by piotr-tomczyk-appfire** [comment]
Nevermind we managed to solve the issue, the installation was possible when used higher version of the package(14.1.0), although we couldn't get 13.0.2 version to install.

**Comment by puzrin** [comment]
npm registry issue, seems to work now.

**Comment by piotr-tomczyk-appfire** [comment]
Thanks!

**Comment by Baki51249** [comment]
ola
