### ISSUE TITLE
alt text not rendered for images

### ISSUE THREAD

**Issue by spank79** [markdown-it/markdown-it#107]
When I use an image with code 

`![Alt text](/path/to/img.jpg "Optional title")` 

the HTML output is 

`<img src="/path/to/img.jpg" alt="" title="Optional title">`

**Comment by puzrin** [comment]
[Can't reproduce](https://markdown-it.github.io/#md3={%22source%22%3A%22![Alt%20text]%28%2Fpath%2Fto%2Fimg.jpg%20\%22Optional%20title\%22%29%22%2C%22defaults%22%3A{%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22}})

Please, create a minimalistic code example.

**Comment by spank79** [comment]
I use it in the browser and I am overwriting the image function for youtube videos. Just saw that it only doesn't work if you overwrite the image function and then pass it to the parent function.

```javascript
var md = window.markdownit();
    
var youtubeUrl       = /^https?:\/\/(\w+\.)?youtube.com\/embed\/(\w+)($|\/)/;
md.renderer.rules.image = function (tokens, idx, options, env, self) {
    var token = tokens[idx],
         aIndexSrc = token.attrIndex('src'),
         aIndexTitle = token.attrIndex('title');
        
    // youtube video
    if (youtubeUrl.test(token.attrs[aIndexSrc][1])) {
         var id = token.attrs[aIndexSrc][1].match(youtubeUrl)[2];
            
         return '<div class="videoWrapper">' + 
                  '   <iframe src="https://www.youtube.com/embed/' + id + '" frameborder="0" allowfullscreen></iframe>' +
                 '</div>';
    }
      
    return self.renderToken(tokens, idx, options, env, self);
};
    
var result = md.render('![Alt text](http://i.stack.imgur.com/RESL1.jpg?s=128 "Optional title")');
console.log(result);
```

**Comment by puzrin** [comment]
http://jsfiddle.net/chLqcdvg/

@rlidwka , take a look please.

**Comment by rlidwka** [comment]
`self.renderToken()` is a generic renderer, and we override it for images.

So the code should call old `md.renderer.rules.image`, not `self.renderToken`. See an example [here](https://github.com/nodeca/nodeca.core/blob/ee667dfcd56333c30d02d191f2d7df832663f5f4/lib/parser/plugins/attachments.js#L19-L34).

And yes, this is not a very good part of the api.

**Comment by puzrin** [comment]
Seems we have buggy example https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer, not properly updeted after version change

**Comment by puzrin** [comment]
@spank79  i've fixed example, sorry for confusion.

**Comment by spank79** [comment]
thank you. Works like a charm :dancers:
