### ISSUE TITLE
Allow file:/// protocol in links

### ISSUE THREAD

**Issue by mtmacdonald** [markdown-it/markdown-it#108]
In plain HTML, I can link to a local file using the `file:///` protocol, like so:

     <a href="file:///C:/test.docx">Link</a>

I would expect the equivalent CommonMark link to be expressed like this:

     [Link](file:///C:/test.docx)

I can't see anything in the [CommonMark spec](http://spec.commonmark.org/0.19/) that prohibits the `file:///` protocol from being used in links, and indeed the [reference implementation](http://spec.commonmark.org/dingus/?text=[Link]%28file%3A%2F%2F%2FC%3A%2Ftest.docx%29) parses this as expected:

![bug1](https://cloud.githubusercontent.com/assets/2428859/7881682/d62e5612-0605-11e5-8fa4-498544a3e20e.png)

However the [markdown-it implementation](https://markdown-it.github.io) does not:

![bug2](https://cloud.githubusercontent.com/assets/2428859/7881685/f2ab8bc0-0605-11e5-9b3d-14a50bfb7026.png)

Is this a bug?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/index.js#L285

That's a security restriction to be safe by defaul. Override it if needed.

**Comment by johnmapeson** [comment]
@puzrin `md.validateLink = function () { return true; }` works fine, but is there an easy way to allow spaces, as long as a `file:///` hyperlink is enclosed in angle brackets, e.g. </foo/bar/aaa bbb/baz>?
