### ISSUE TITLE
Grabbing all image links in markdown text?

### ISSUE THREAD

**Issue by canebat** [markdown-it/markdown-it#109]
Does `markdown-it` provide a way to extract all image links from a body of markdown text?

I would like to verify them with `MarkdownIt#validateLink(url)`, but need a list of the urls to begin with.

**Comment by puzrin** [comment]
See src of https://github.com/markdown-it/markdown-it-for-inline or use it directly. It has tokens iterator.

**Comment by canebat** [comment]
@puzrin  Is there a list of token types I can see? I'm not sure what they are or which one I should use?

**Comment by puzrin** [comment]
In src only. I'd recommend to read dev docs first https://github.com/markdown-it/markdown-it/tree/master/docs
