### ISSUE TITLE
markdown-it-for-inline throws cannot read property 'referenes' of undefined on malformed link.

### ISSUE THREAD

**Issue by canebat** [markdown-it/markdown-it#110]
Here is an example:
```
var iterator = require('markdown-it-for-inline');
md.use(iterator, 'test', 'link_open', function(tokens, idx) {
    console.log(tokens[idx]);
});

md.parse(markdown_text);
```

Tried to parse this:
```
**Hello** This is a test!

[alink]http://example.com)
```

Notice the link is missing a beginning `(`.

This results in:

    TypeError: Cannot read property 'references' of undefined

**Comment by rlidwka** [comment]
`md.parse(src, env)` is an internal method, which requires you to supply an environment as a second argument. That is a bit different from a `md.render()` function.

So please use `md.parse(markdown_text, {})` instead if you want to get a token list.
