### ISSUE TITLE
Code block should terminate block quote

### ISSUE THREAD

**Issue by opennota** [markdown-it/markdown-it#112]
[Snippet.](http://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3E%20block%20quote%5Cn%20%20%20%20should%20be%20code%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

According to the CommonMark 0.19 spec,

> Laziness only applies to lines that are continuations of paragraphs. Lines containing characters or indentation that indicate block structure cannot be lazy.

**Comment by puzrin** [comment]
http://spec.commonmark.org/dingus/?text=%3E%20block%20quote%0A%20%20%20%20should%20be%20code

Invalid. See http://spec.commonmark.org/0.19/#example-65 . "An indented code block cannot interrupt a paragraph."

**Comment by puzrin** [comment]
If you wish - report clarification request to https://github.com/jgm/CommonMark/issues
