### ISSUE TITLE
Make a menu from the #, ##, ###.

### ISSUE THREAD

**Issue by AlexisTM** [markdown-it/markdown-it#113]
Dear,

I would like to generate a menu from the headings and the underline properties. The desired code would be like this, where `IDMenu` refers to `<div id="IDMenu"> </div>`

```
var md = window.markdownit()
    .use(window.markdownitMenu, 'IDMenu');
```

How should I write the module? Does one already exist?

**Comment by vyp** [comment]
#28

**Comment by AlexisTM** [comment]
Thanks!

**Comment by vyp** [comment]
There are some plugins you can use that are linked near the botttom. If that is what you are after, you should close this.
