### ISSUE TITLE
Incorrectly parsed fragment

### ISSUE THREAD

**Issue by opennota** [markdown-it/markdown-it#116]
[Snippet.](http://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3E%20%20%20%20%20foo%5Cn%20%20%20%3Ebar%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

Text:
```
>     foo
   >bar
```

**Comment by rlidwka** [comment]
Fixed, thanks!
