### ISSUE TITLE
Add some css to the table tag

### ISSUE THREAD

**Issue by AlexisTM** [markdown-it/markdown-it#117]
Dear, 

I am using bootstrap and render a table correctly, I would have to add the table class to table DOM, like :

``` js
<table class="table">
</table>
```

How should I do? I searched the the table rule, but it seems not to be directly editable : `block.ruler.__rules__[9].fn`

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.js#L288-L294

If no specific rule defined, default renderer used. You can define renderer for `table_open` token, OR iterate tokens and push class attr.

**Comment by AlexisTM** [comment]
Thanks! I will try it!

**Comment by AlexisTM** [comment]
This is awsome! So moddable! 

(solution in case of someone got this or similar problem)

``` javascript
var md = window.markdownit();
md.renderer.rules.table_open = function() {
      return '<table class="table">';
};
```

**Comment by antgel** [comment]
I'm a bit late here but let's see. I'd like to override the blockquote implementation to add a class name as per https://github.com/holger1411/11straps/issues/138 but I don't see any `renderer.rules` function relating to blockquote. I guess I may have missed some implementation detail. Is this possible, and if so, how?

**Comment by AlexisTM** [comment]
This was kind of a while ago (2015) so I do not remember what I did then.

**Comment by antgel** [comment]
Thank you, I understand ("I'm a bit late here..."). Perhaps someone else can advise.

**Comment by rlidwka** [comment]
@antgel `md.renderer.rules.blockquote_open` and `blockquote_close`

you don't see them, but they still exist (and they have default implementation)

**Comment by jyang81** [comment]
I'd like to do the same thing as @antgel, but I'm more curious as to whether it's possible to render the blockquote **without** the nested <p> tag. It's causing unwanted bottom margin within the blockquote, and I have no way of adding a class to the <p> tag to override it. If anyone can help, I'd really appreciate it!
