### ISSUE TITLE
Domains with < or > after them aren't linkified

### ISSUE THREAD

**Issue by opennota** [markdown-it/markdown-it#118]
`>google.com<` will not be linkified.

If this is an intended behaviour, just close this issue.

**Comment by puzrin** [comment]
Yes, it's ~ invalid domain name (can't end with `<`).

Also, it's better to report such problems to https://github.com/markdown-it/linkify-it directly.

**Comment by opennota** [comment]
> invalid domain name (can't end with <).

Of course, but markdown-it could still linkify google.com

**Comment by puzrin** [comment]
Yes, it can. Because second case can't give false positives. It's not a problem to generate broken artificial sequence, but that make no sence in real life.
