### ISSUE TITLE
How to disable all rules, and then enable only couple?

### ISSUE THREAD

**Issue by rpominov** [markdown-it/markdown-it#12]
Hi,

First of all, thanks for the great library!

I have a little question on configuration. I am trying to use the library to do only a couple of things (`**bold**`, `[link](...)`, and auto insertion of `<p>` and `<br/>`). Could you please give me some direction of how to do that? For now I even fail to find a way of disabling rules via config hash, and don't know where to find a list of all available rules.

**Comment by intijk** [comment]
Can I ask a question here that how to only disable `italic`?

Tried with 
```javascript
md.disable('italic')
```
but reported error.

**Comment by puzrin** [comment]
@intijk name is [emphasis](https://github.com/markdown-it/markdown-it/blob/master/lib/parser_inline.js#L21), it can be disabled in pair with bold only. Or you should replace emphasis rule with your own

**Comment by intijk** [comment]
Thank you for your reply :) @puzrin 

I tried below code and found bold also turned off. So the logic here is to enable both bold and italic or disable both of them, right?

```javascript
'use strict'
var MarkdownIt=require('markdown-it')
var md=new MarkdownIt()

md.disable("emphasis")

var result=md.render("_italic_ **bold**")
console.log(result)
```

**Comment by intijk** [comment]
Let me see if I could make some `strong` rule here to separate these two logic.

**Comment by puzrin** [comment]
yes
