### ISSUE TITLE
Code block instead of table

### ISSUE THREAD

**Issue by opennota** [markdown-it/markdown-it#120]
GitHub renders this
```
    column1 | column2
  --------- | --------
    abc     | def
```

as a table:

    column1 | column2
  --------- | --------
    abc     | def

whereas markdown-it fails to recognize the table.

Note that the indent of the second line is 2, not 4.

[Snippet.](http://markdown-it.github.io/#md3=%7B%22source%22%3A%22%20%20%20%20column1%20%7C%20column2%5Cn%20%20---------%20%7C%20--------%5Cn%20%20%20%20abc%20%20%20%20%20%7C%20def%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

**Comment by puzrin** [comment]
I tend to postpone it until tables spec done. Issue seems not critical. At least, nobody reported problems in npm registry.

If it's critical for you - let me know.

**Comment by bmordan** [comment]
do a table in markdown-it like this
```
|header|other header|
|:--------|:-----------------|
this is | all good
```

**Comment by puzrin** [comment]
Fixed by https://github.com/markdown-it/markdown-it/commit/0318337a3df8867570372727d57ba303533c150e
