### ISSUE TITLE
Audio / Video / WebM support

### ISSUE THREAD

**Issue by v3ss0n** [markdown-it/markdown-it#122]
We are discussing about it at http://talk.commonmark.org/t/embedded-audio-and-video/441/9 . Many of us agrees to use ![](filename.ext) format to determine what media to be served.

I think it will be good to have inside markdown-it .

**Comment by vyp** [comment]
plugin?

**Comment by puzrin** [comment]
@v3ss0n i don't see reasons why this extension should be in core instead of plugin.

**Comment by v3ss0n** [comment]
ok plugin it is.

**Comment by eloquence** [comment]
Plugins are neat (!), but I would argue for making HTML5 video/audio a first class content citizen in markdown-it. There's no reason why a WebM, Ogg or MP4 file should be rendered as an <img> tag by default -- that plainly never makes sense, as modern, standards-compliant browsers can render such content without plugins just as they would a PNG, SVG or JPG.

**Comment by puzrin** [comment]
@eloquence you should address your request to https://talk.commonmark.org/. This package accepts only things from CM spec to not deviate from standard. Everything else is left for plugins.

**Comment by eloquence** [comment]
That's fair, thanks for the quick response. I'll comment there and see how it goes :)

**Comment by puzrin** [comment]
https://talk.commonmark.org/t/embedded-audio-and-video/441/72?u=vitaly :)
