### ISSUE TITLE
Images in divs don't render with HTML enabled

### ISSUE THREAD

**Issue by grit96** [markdown-it/markdown-it#123]
```markdown
<div>![Screenshot of Pebble Info](images/pebble.png)</div>
```
converts to
```html
<div>![Screenshot of Pebble Info](images/pebble.png)</div>
```

**Comment by svbergerem** [comment]
This is exactly what the [CommonMark spec](http://spec.commonmark.org/0.20/#html-blocks) says:

> An HTML block begins with an HTML block tag, HTML comment, processing instruction, declaration, or CDATA section. It ends when a blank line or the end of the input is encountered. The initial line may be indented up to three spaces, and subsequent lines may have any indentation. The contents of the HTML block are interpreted as raw HTML, and will not be escaped in HTML output.

**Comment by grit96** [comment]
Oh, so no markdown within HTML blocks?
Is there a way to allow that within markdown-it?

**Comment by digitalmoksha** [comment]
Yes it's allowed, it just needs to be formatted properly:  http://spec.commonmark.org/0.20/#example-110

**Comment by grit96** [comment]
OK thanks. This seems a strange requirement and is not consistent with other parsers/markdown specs.

**Comment by digitalmoksha** [comment]
only slightly different, and that section explains it in pretty good detail.

**Comment by puzrin** [comment]
Not a bug
