### ISSUE TITLE
Cannot load lib with jspm

### ISSUE THREAD

**Issue by grofit** [markdown-it/markdown-it#127]
This may just be me being an idiot but if I include this lib via JSPM (doing some work with aurelia) then it includes it all fine, but when I go to import it, it blows up saying:

`jspm_packages/github/markdown-it/markdown-it@4.3.0/lib/lib.js net::ERR_FILE_NOT_FOUND`

Now I *THINK* it may be down to the line in your `index.js` file which does:

`module.exports = require('./lib/');`

but not too sure, so has anyone else had this working with jspm?

**Comment by puzrin** [comment]
I suspect, this problem should be reported to jspm, not here.
