### ISSUE TITLE
class injection in fence renderer

### ISSUE THREAD

**Issue by rlidwka** [markdown-it/markdown-it#128]
Similar issue as in https://github.com/jgm/commonmark.js/issues/54, but not quite the same:

    ```foo&#x20;bar
    code
    ```

Current code decodes entities *after* split, so this will be rendered to:

```html
<pre><code style="language-foo bar">
code
</code></pre>
```

Therefore, user can attach arbitrary classes to the `code` tag.

**Comment by v3ss0n** [comment]
:+1:
