### ISSUE TITLE
Can't start a numbered list with a 0

### ISSUE THREAD

**Issue by Leonya** [markdown-it/markdown-it#129]
CommonMark supports it, but not Markdown-it.

**Comment by vyp** [comment]
Are you sure, [this](https://markdown-it.github.io/#md3=%7B%22source%22%3A%220.%20first%20item%5Cn1.%20second%20item%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D) seems to work?

**Comment by Leonya** [comment]
It works but the rendered list starts with 1, unlike in CommonMark:

http://spec.commonmark.org/dingus/?text=0.%20item%20zero%0A1.%20item%20one%0A2.%20item%20two%0A%20%20%20-%20sublist%0A%20%20%20-%20sublist%0A%0A

**Comment by vyp** [comment]
@markdown-it Here are the possibly relevant sections from the spec: Just above [example 178](http://spec.commonmark.org/0.20/#example-178) is this:

> If the list item is ordered, then it is also assigned a start number, based on the ordered list marker.

Also see example 179 (version 0.20).

**Comment by vyp** [comment]
Okay I got the actually relevant section: http://spec.commonmark.org/0.20/#lists:

> The start number of an ordered list is determined by the list number of its initial list item. The numbers of subsequent list items are disregarded.

http://spec.commonmark.org/0.20/#example-207

**Comment by vyp** [comment]
Btw, this is not strictly just stylistic because commonmark implements the above rule with the `start` attribute (as can be seen in @Leonya's example link).

**Comment by Leonya** [comment]
No, it's not stylistic, I believe it's a genuine bug.

**Comment by rlidwka** [comment]
I agree, it is a bug. Fixed in 954e156.

**Comment by Leonya** [comment]
Cool, thanks.
