### ISSUE TITLE
Highlight function not called for all code blocks

### ISSUE THREAD

**Issue by danielgtaylor** [markdown-it/markdown-it#130]
It seems that any code blocks defined without the fence characters do not get highlighted. Is this on purpose?

[Example in the interactive editor](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22Some%20code%3A%5Cn%5Cn%60%60%60coffee%5Cnclass%20Foo%5Cn%20%20constructor%3A%20%28%40id%29%20-%3E%5Cn%60%60%60%5Cn%5CnSome%20other%20code%3A%5Cn%5Cn%20%20%20%20var%20x%20%3D%201%3B%5Cn%20%20%20%20console.log%28x%20%2A%20x%29%3B%5Cn%5CnYet%20more%20code%3A%5Cn%5Cn%60%60%60%5Cnvar%20y%20%3D%202%3B%5Cnconsole.log%28y%20%2A%20y%29%3B%5Cn%60%60%60%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

<img width="712" alt="screen shot 2015-06-04 at 11 53 46" src="https://cloud.githubusercontent.com/assets/106826/8616529/559efafc-26fc-11e5-85b6-dbc4cbf963a9.png">

The second code block should still go through the highlighter. Reported through danielgtaylor/aglio#119.

**Comment by puzrin** [comment]
Yes, is configured such way, because indented blocks do on allow to define language explicit, can contain lyrics and so on. If you wish highlighter there - override `code_block` renderer ~ as `fence` https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.js#L26.

PS. It seems aglio uses very old parser version, you'd better to upgrade.

**Comment by danielgtaylor** [comment]
@puzrin thanks, setting it to the `fence` rule makes this work as expected. Closing this issue as it's not really a bug!

**Comment by KristerV** [comment]
sorry, how does this fix work? The link seems to be a bit off.
