### ISSUE TITLE
Extract plain text?

### ISSUE THREAD

**Issue by kajmagnus** [markdown-it/markdown-it#131]
Hi, is there some way to extract the plain text contents of a markdown-it text? For example, this:

```
**The sun** is <bold>shining</bold> unless it's cloudy or it's night or it's gone.

- Diamond field ahead.
```

would result in: "The sun is shining unless it's cloudy or it's night or it's gone. Diamond field ahead."

If there is currently no way to do this, perhaps I should just use something like JSoup http://jsoup.org/cookbook/extracting-data/attributes-text-html and call `.text()` on the resulting HTML.

**Comment by puzrin** [comment]
You could to use `cheerio` to parse markup and extract text tokens. This task is not related directly to markdown parser.

**Comment by kajmagnus** [comment]
Didn't know about https://github.com/cheeriojs/cheerio. Seems like a great project (well lots of stars anyway) — I'm using Scala though on the JVM so for me JSoup feels like the thing I'll test first. Thanks
