### ISSUE TITLE
<iframe>s

### ISSUE THREAD

**Issue by bevacqua** [markdown-it/markdown-it#133]
Version `4.4.0` breaks expectation to be able to include `<iframe>` declarations anywhere in a markdown document. This should be a task for a sanitizer such as https://github.com/bevacqua/insane, not the markdown parser

**Comment by puzrin** [comment]
http://spec.commonmark.org/

Are you vamiliar with 0.21 spec changes? Is this report related to this pachage or to spec?

**Comment by bevacqua** [comment]
That's gibberish to me, I can't make sense of the spec, I just see that it doesn't reference `<iframe>` elements anymore. Markdown historically allowed to mix-in HTML. Removing support for that seems like a major change *(and even with a major version change I would be strongly against it)*

**Comment by puzrin** [comment]
@bevacqua , both this project and reference implementation have demos, allowing to create examples.

- https://markdown-it.github.io/
- http://spec.commonmark.org/dingus/

Please, create examples what is wrong and give links to those.

**Comment by puzrin** [comment]
[example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22before%20iframe%5Cn%5Cn%3Ciframe%20width%3D%5C%22560%5C%22%20height%3D%5C%22315%5C%22%20src%3D%5C%22https%3A%2F%2Fwww.youtube.com%2Fembed%2FpfBTXZWRPQ4%5C%22%20frameborder%3D%5C%220%5C%22%20allowfullscreen%3E%3C%2Fiframe%3E%5Cn%5Cnafter%20iframe%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D)

I see no problem with iframe, except the fact it's been wrapped with paragraph.

**Comment by bevacqua** [comment]
If I upgrade to `4.4.0` [in this library](https://github.com/bevacqua/megamark) the `<iframe>` test fails

**Comment by puzrin** [comment]
I can't test your library. If you need help here - please, prepare examples.

**Comment by bevacqua** [comment]
Nevermind, it was an issue in my end _(didn't realize that it got wrapped in a paragraph now.)_

**Comment by puzrin** [comment]
Wrapping to paragraph seems to be a bug.

Reported here https://github.com/jgm/CommonMark/issues/352

**Comment by bevacqua** [comment]
Yeah I agree, I was just content to be able to upgrade to `@latest` with tests passing
