### ISSUE TITLE
XML tag inside fenced code block

### ISSUE THREAD

**Issue by felixSchl** [markdown-it/markdown-it#134]
XML tags get swallowed if they are inside a fenced code block:

```
    ```
    <foo>
    ```
```

renders as:

```
```

As you can see, it *should* work:

```
<foo>
```

**Comment by puzrin** [comment]
[Example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%20%20%20%20%60%60%60%5Cn%20%20%20%20%3Cfoo%3E%5Cn%20%20%20%20%60%60%60%5Cn%5Cn%60%60%60%5Cn%3Cfoo%3E%5Cn%60%60%60%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

Can not reproduce.

**Comment by felixSchl** [comment]
Touche, must be something I am doing wrong. Sorry for the noise and thank you!
