### ISSUE TITLE
Render markdown inside an HTML tag

### ISSUE THREAD

**Issue by davidmerfield** [markdown-it/markdown-it#136]
```
<div>
   ![Alt](http://example.com/image.jpg)
</div>
```

does not become

```
<div>
  <img src="http://example.com/image.jpg" alt="Alt" />
</div>
```

Is this is an intentional decision on your part? If so, please could you point me to the section of the library which I can alter to get this functionality?

**Comment by puzrin** [comment]
That's a commonmark parser, and it follows specification.

http://spec.commonmark.org/0.21/#html-blocks

There are no good ways to mix inline content with html blocks. Your inline markdown will be wrapped to paragraphs.

**Comment by davidmerfield** [comment]
Thanks for the prompt response. 

When you say 'that's a commonmark parser,' do you mean I should be looking for a commonmark parser to accomplish this?

The reason I ask is that running that mixture of HTML and markdown through [chjj/marked](https://github.com/chjj/marked) produces that output. However, marked lacks other features I'd like, notably footnotes...

**Comment by puzrin** [comment]
I gave you link to specification, that describes this parser behaviour. Read it to investigate if your requirement can be satisfied or not. Markup-related questions should be asked at commonmark forum.

**Comment by davidmerfield** [comment]
Ah I see – I misunderstood your response. Thank you.

**Comment by m93a** [comment]
Am I mad or has this behavior changed in the latest CommonMark spec?
https://spec.commonmark.org/0.28/#raw-html
