### ISSUE TITLE
Unresponsive script

### ISSUE THREAD

**Issue by itay-grudev** [markdown-it/markdown-it#137]
I think the image below is descriptive enough.

<img width="485" alt="screen shot 2015-08-16 at 22 23 25" src="https://cloud.githubusercontent.com/assets/2123767/9294980/d0b225e8-4466-11e5-80a3-740dbac59cc3.png">

P.S. This occured on Firefox 40.0 on both Mac OS X and Linux Mint.

**Comment by puzrin** [comment]
Hm, it hangs with muild from master. Rebuilded from 4.4.0 tag

@rlidwka take a look, what's up. `make demo` also hangs locally.

**Comment by puzrin** [comment]
Solved. Thanks for report.
