### ISSUE TITLE
Output is not markdown compliant

### ISSUE THREAD

**Issue by toddself** [markdown-it/markdown-it#139]
Hi!

I'm the author of an HTML->Markdown converter ([Dr SAX](/toddself/dr-sax)) and I have a few tests that check for round-trip compliance with several Markdown->HTML converters.

I just added this and notice that when handling `<iframe>` tags the output is wrapped in a `<p>` tag.  This is not compliant with Gruber's original implementation (which leaves the `<iframe>` unwrapped).

CommonMark seems to be split on this. Originally flagged as a bug that was resolved (jgm/commonmark#88) but is open again in the latest version of the module (jgm/commonmark#352).

I'm not sure if compliance with Gruber is an aim of the non-commonmark output for this library, but wrapping `<iframes>` in `<p>` tags does make styling them a little more difficult!

**Comment by puzrin** [comment]
#352 was created by me :) . Please, use commonmark-related resources to discuss spec issues. This is alternate commonmark implementation, and it follows spec.
