### ISSUE TITLE
Links with target="_blank"

### ISSUE THREAD

**Issue by nickmkk** [markdown-it/markdown-it#140]
Is there an easy way to make all links use target="_blank" so they open in a new tab?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer

**Comment by nickmkk** [comment]
Thank you sir =)

**Comment by smaimon** [comment]
Thank you @puzrin for the link  👍
I think I miss something because I can't found the way to declare the attribute target="_blank" in the `.md` file {:target="_blank"}, [target=blank],... ?
😅

**Comment by SaulSilver** [comment]
@sebu `.md` files accept HTML too so you can add the `target` attribute to the HTML anchor tag `<a>`. 
See this Stackoverflow answer: https://stackoverflow.com/a/4425223
