### ISSUE TITLE
Tabs aren't preserved within fenced in blocks

### ISSUE THREAD

**Issue by reggi** [markdown-it/markdown-it#143]
If I have the code below in a markdown file, and parse it, it looks as if the tabs are converted to spaces. 

```js
var x = '		'
```

    ```js
    var x = '		'
    ```

Even github's markdown parser here does it too.

**Comment by puzrin** [comment]
Tabs preserve appeared only in latest CM spec, and is available in master. See commints history.

**Comment by reggi** [comment]
This is great? Any idea when this release is going to hit NPM?

**Comment by puzrin** [comment]
In couple of week, when complete other spec issue. Busy with other things now.

**Comment by reggi** [comment]
Thanks a bunch @puzrin!!

**Comment by reggi** [comment]
I'm using markdown-it as a dep https://github.com/reggi/evalmd `^4.4.0` and I need to preserve tabs. How can I pick the current master branch as my dep? I'd really love it if you could add a tag. Thoughts?

**Comment by puzrin** [comment]
https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by reggi** [comment]
@puzrin Totally forgot about setting commit hash, thanks!
