### ISSUE TITLE
Links with spaces in href don't get parsed as links?

### ISSUE THREAD

**Issue by reggi** [markdown-it/markdown-it#147]
The following is a anchor containing a space,

```
[](#hello world)
```

This gets parsed without `link_open` and `link_closed` braces, and just as raw text.

**Comment by vyp** [comment]
Pretty sure this is just [spec](http://spec.commonmark.org/0.21/#link-destination):

> A nonempty sequence of characters that **does not include ASCII space** or control characters [...]

**Comment by puzrin** [comment]
@reggi, we have a bit limited resources for support. Prefer to use this tracker for cases which can not be solved without authors - bug reports and so on. Please, avoid create a lot of tickets in "talk/educational" mode. Read the docs, spec, and study src of project & plugins first.

**Comment by reggi** [comment]
@puzrin agreed, sorry for opening too many tickets.

**Comment by phaseOne** [comment]
Could we please reopen this ticket?

The following inline link with spaces in the link destination is failing, but is [valid in the CommonMark spec](https://spec.commonmark.org/0.29/#example-486) (passing [commonmark.js dingus permalink](https://spec.commonmark.org/dingus/?text=[Broken%20inline%20link%20with%20space.md](%3C./Broken%20inline%20link%20with%20space.md%3E)), failing [markdown-it demo permalink](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%5BBroken%20inline%20link%20with%20space.md%5D%28%3C.%2FBroken%20inline%20link%20with%20space.md%3E%29%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)):
```
[Broken inline link with space.md](<./Broken inline link with space.md>)
```

**Comment by puzrin** [comment]
@phaseOne just create a new issue and copy your message there. That may be not related to this one (spec changed, for example)

**Comment by phaseOne** [comment]
@puzrin done: #567. Thanks!
