### ISSUE TITLE
Support ReactJS components

### ISSUE THREAD

**Issue by funkjunky** [markdown-it/markdown-it#150]
Perhaps this is a far reach. I've been looking into this for the last hour.

I don't understand the internals well enough yet.
Also someone may understand how to do this: https://github.com/alexkuz/markdown-react-js/

Essentially the plugin needs to return a react component, which may be very straight forward if written in a JSX way.

If no one picks this up after a few days perhaps remove it. I'm putting it here, because right now I think this may be very very simple with how JSX works.

**Comment by puzrin** [comment]
Sorry, this tracker is not right place for such request.

**Comment by funkjunky** [comment]
I understand your reasoning, however I've solved my own issue, however I could use some assistance with proceeding further.

See if you use the map function on the tokens array and return that in render and renderInline, then ReactJS elements can be rendered through JSX.
The downside is that the markdown-it tool needs to normally output a string, not an array.

Obviously I could fork the repository, but I don't want to miss out on all the awesome updates you guys are making.

Would it be unreasonable to provide a renderToTokens method?

While you consider it I'll write this out, then make a pull request. Worst case you reject it and I fork.
If you don't understand, perhaps you'll understand better with the code from the pull request.

**Comment by puzrin** [comment]
I think architecture is flexible enougth to be extended via plugins & monkeypatching. This is core project, it can't accept custom features to mainstream.

**Comment by funkjunky** [comment]
ok, I understand. Thinking about it, I'm using Array Maps, which is slower than string concatenation, so I'll just fork.
Thanks for the suggestions. Keep up the good work with Markdown-it!
