### ISSUE TITLE
Expose all loaded plugins.

### ISSUE THREAD

**Issue by leipert** [markdown-it/markdown-it#153]
I want to write a markdown-it wrapper that can take several options whether a plugin should be enabled or disabled. So for example:

```javascript 
var wrapper = require('wrapper');
wrapper.render(markdown, {math: true}); // Renders markdown with markdown-it-math
wrapper.render(markdown, {math: false}); // Renders markdown with markdown-it-math
```

Now the trick is:
In the background the wrapper disables or enables the markdown-it-math plugin. I can do that easily with `enable` or `disable`. But I do not want to load all markdown-it plugins, upon initialization, I'd rather lazyload them:

```javascript
if (options.math){
	//This part is missing as far as I can see from the spec:
	if(!markdownIt.hasRegistered(['math_inline', 'math_block'])){
		//This part works again.		
		markdownItMath.use(require('markdown-it-math'))
	}
	markdownIt.enable(['math_inline', 'math_block'], true);
}else{
	markdownIt.disable(['math_inline', 'math_block'], true);
}
```

**Comment by puzrin** [comment]
It's recommended to create & memoise several instances (per each options combination) instead. That's by design. If you need lazy load - do lazy create on first use.

**Comment by leipert** [comment]
If my wrapper wraps only 6 plugins and I want to save an option for each combination, then I will have 720 combinations. Okay. But as I am not expecting changing options too much, I will simply create a new instance each time the options change. Thanks for your quick answer (and this package).

Just fyi, we are using markdown-it in the [markdown-preview-plus](https://atom.io/packages/markdown-preview-plus) package for the atom editor, exposing it to circa 14000 people. 

It is awesome thank you.

**Comment by puzrin** [comment]
In real world very few combinations needed and instance cache works very well. We used this approach (configure once, use many) to reach max possible speed (see benchmarks).

It seems to me, that i mentioned principle "create new instance for each new config" somewhere in docs. But if that's missed or not evident - feel free to clarify.
