### ISSUE TITLE
Is it possible to utilize this parser for single line input?

### ISSUE THREAD

**Issue by oliverjanik** [markdown-it/markdown-it#154]
I have a need for a single line subset of Markdown. I.e. one that doesn't generate paragraphs and only supports inline constructs.

The use case are standalone single lines of content e.g. coming from input[type="text"] not a textarea.

Minimum support would be bold, underline...

**Comment by puzrin** [comment]
https://markdown-it.github.io/markdown-it/#MarkdownIt.renderInline

**Comment by oliverjanik** [comment]
Thanks, missed that.
