### ISSUE TITLE
Auto linking breaks if markdown is in the URL.

### ISSUE THREAD

**Issue by 3rd-Eden** [markdown-it/markdown-it#156]
For example an URL like: http://example.com/this_is_broken will render the `_is_` as italic instead of considering it as part of the URL, causing the autolinking to only link the `http://example.com`. Copy and pasting the URL will also no longer world as it will be rendered as `http://example.com/thisisbroken` instead of `http://example.com/this_is_broken`

**Comment by puzrin** [comment]
Please, use demo permalinks for live examples.

[Here](https://markdown-it.github.io/#md3={%22source%22%3A%22aaa%20http%3A%2F%2Fexample.com%2Fthis_is_broken%20bbb%22%2C%22defaults%22%3A{%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22}}) i don't see any problems with italic. The only known issues were described in #38.

**Comment by 3rd-Eden** [comment]
It's indeed the issue described in #38 closing this as duplicate
