### ISSUE TITLE
Image rendering fails

### ISSUE THREAD

**Issue by cakebake** [markdown-it/markdown-it#162]
The rendering for images with whitespace fails. I tried escaping the URL, but did not succeed. 
Parsing is canceled before I can [modify the image src](https://github.com/cakebake/markdown-themeable-pdf/blob/master/lib/markdown-themeable-pdf.js#L281) with `md.renderer.rules.image`.

I use the module for generating PDFs on github atom with [markdown-themeable-pdf](https://atom.io/packages/markdown-themeable-pdf) package. A user has reportet the initial Issue at cakebake/markdown-themeable-pdf#9

#### Example markdown:

```
![local image](rattlesnake image.jpg)
```

- [Source](https://raw.githubusercontent.com/cakebake/markdown-themeable-pdf/master/tests/images.md)
- [Output](https://github.com/cakebake/markdown-themeable-pdf/blob/master/tests/images.pdf)

**Thank´s for your support :)**

**Comment by rlidwka** [comment]
Url-escaping the url works just fine:

```md
![local image](rattlesnake%20image.jpg)
```

Alternatively, you can enclose url in angular brackets, which will allow wider range of characters in it including spaces:

```md
![local image](<rattlesnake image.jpg>)
```

So, it's not a bug. You can also check [commonmark spec](http://spec.commonmark.org/0.22/#link-destination) for more details on which characters are accepted in the link destination.

**Comment by cakebake** [comment]
Thank you for your note! So my problem is no longer a problem :+1:
