### ISSUE TITLE
Import markdown files rather than inputting as a string?

### ISSUE THREAD

**Issue by cassidoo** [markdown-it/markdown-it#163]
Does the library support importing markdown files, for example something like this?  If not, how would one try that?

```
var MarkdownIt = require('markdown-it'),
    md = new MarkdownIt();
var result = md.render(someMarkdownFile.md);```

**Comment by puzrin** [comment]
https://nodejs.org/api/fs.html#fs_fs_readfilesync_filename_options

This library works with strings. If you need to read text file, probably node tutorials should have examples.
