### ISSUE TITLE
Is it possible to inlcude another file from markdown file via plugin?

### ISSUE THREAD

**Issue by hh9527** [markdown-it/markdown-it#164]
Something like this:

file a.md:

```markdown
this is a.md
#include "b.md"
```

file b.md:

```markdown
this is b.md
```

And produce:
```markdown
this is a.md
this is b.md
```

**Comment by vyp** [comment]
No.

I don't know why you would want this, but chances are using some templating system (at the html level) will solve your issue here.

**Comment by puzrin** [comment]
If you need async file load, here is generic advice https://github.com/markdown-it/markdown-it/blob/master/docs/development.md#i-need-async-rule-how-to-do-it.

In general - yes, it's possible, but nobody yet did it and we have no plans to write such plugin ourself.

**Comment by camelaissani** [comment]
@hh9527 I think my plugin can be what you are looking for https://github.com/camelaissani/markdown-it-include

**Comment by gogy27** [comment]
@camelaissani unfortunately your plugin doesn't work in browser environment.
