### ISSUE TITLE
Task lists?

### ISSUE THREAD

**Issue by dvcrn** [markdown-it/markdown-it#166]
Hi!

Any chance we can see task lists in markdown-it? 
```
- [x] text
- [ ] text
- [x] text
```

- [x] text
- [ ] text
- [x] text

**Comment by vyp** [comment]
What about the https://github.com/mcecot/markdown-it-checkbox plugin?

**Comment by dvcrn** [comment]
Oh I didn't see that one. Hard to search when these things are sometimes called 'task lists', sometimes 'todo lists', sometimes 'checkboxes'. I'll give that a try.

**Comment by puzrin** [comment]
No plans in core team, because CM spec is not complete and some plugins available.
