### ISSUE TITLE
Can't render HTML in code block

### ISSUE THREAD

**Issue by aarondufall** [markdown-it/markdown-it#167]
Rendering HTML or any < or > in code blocks with `html: true ` isn't working. This works fine when I try it out with the demo site though. Maybe I'm missing a setting or require a plugin to do this.

I'm using version 5.0.1 from the cdn with this tag

```
<script src="https://cdn.jsdelivr.net/markdown-it/5.0.1/markdown-it.min.js"></script>
```

With HTML:

```javascript
window.markdownit({html: true}).render("```<h1>Hello World</h1>```")
"<p><code>&lt;h1&gt;Hello World&lt;/h1&gt;</code></p>"
```

With < and >:

```javascript
window.markdownit({html: true}).render("```1 < 1```")
"<p><code>1 &lt; 1</code></p>"
```

**Comment by puzrin** [comment]
Could you explain what's wrong? Html tags are not available in code blocks, by spec.

[Demo](https://markdown-it.github.io/#md3={%22source%22%3A%22%60%60%60%3Ch1%3EHello%20World%3C%2Fh1%3E%60%60%60%22%2C%22defaults%22%3A{%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22}}) shows the same result as in your post.

**Comment by aarondufall** [comment]
Thank you for your speedy response. In the source tab it does show the < and > as &lt and &gt, but in the html tab it shows the HTML tags in the code block correctly. When inspecting the elements it contains  `<code><h1>Hello World</h1></code>`  . The problem I am getting is that I have been unable to get < and > to display in code blocks like shows in the attached screenshot and would like to be able to.  I have tried enabling this behaviour with `window.markdownit({html: true})` but get the results mentioned previously.

<img width="1440" alt="markdown-it" src="https://cloud.githubusercontent.com/assets/1779992/11111046/442250f2-88b9-11e5-8bba-6919704c9e0e.png">

**Comment by vyp** [comment]
I don't understand, are you saying that your browser does not render `;&gt;` as `>` (and vice versa)? Because the html that markdown-it generates:

```
<p><code>&lt;h1&gt;Hello World&lt;/h1&gt;</code></p>
```

is correct right?

**Comment by aarondufall** [comment]
I'm trying to render markdown that has code that containing < and >.

The code block I'm trying to render would look something like this:

Markdown (ignore the " just trying to show the MD):
```markdown
"```
if( 1 < 2) { 
   console.log('success') 
}
```"
```
desired output:
```javascript
if( 1 < 2) { 
   console.log('success') 
}
```

What I end up getting when I render the markdown is this

```javascript
if( 1 &lt; 2){
  console.log('success')
}
```

I only get this problem with code blocks between the back-ticks, < and > work fine in regular content areas


The code I'm using for markdown is something like the following:

```javascript
let _md = window.markdownit({html: true});

let renderMarkdown = (input) => {
  return _md.render(input)
}

let showEl = document.querySelector('#markdown')
if(showEl) {
  let renderedMarkdown = window.markdownit().render(showEl.innerHTML)

  showEl.innerHTML = renderedMarkdown
}
```

**Comment by puzrin** [comment]
Your question is not related to this project. It works as needed. Generic questions about markdown should be discussed at appropriate places http://commonmark.org/. There are links to spec & forum.

**Comment by vyp** [comment]
@aarondufall

> desired output:

> ```
if( 1 < 2) { 
   console.log('success')
}
```

Isn't this the problem? Isn't it the case that in html, any `<` or `>` not used as part of html tags always have to be escaped (to `&lt;` / `&gt;`)?

**Comment by mightyiam** [comment]
The reference implementation actually seems to convert those `<` and `>` to the entities when they are in code blocks. And I find that very convenient. Does this make is a valid bug? Try here:
http://spec.commonmark.org/dingus/

**Comment by autotel** [comment]
Just for reference of others; I ran into the same problem, but later I realized it was because I was using the .innerHTML of the node as contents to parse instead of the .textContent

```
var showdown=require('showdown');
// var commonmark=require('commonmark');
module.exports=function(source,dest){
  var nodes = document.getElementsByClassName(source);
  var destNode=document.getElementsByClassName(dest);
  for(var n in nodes){
    var node=nodes[n];
    if(destNode[n]){
      htmlContent = node.innerHTML;
      textContent = node.textContent;
      var converter = new showdown.Converter();
      console.log(showdown.getOptions());
      showdown.setFlavor('github');
//here: feeding htmlContent or textContent, both work; but htmlContent will render <'s into &lt; when they are inside `'s
      html = converter.makeHtml(textContent);
      destNode[n].innerHTML=(html);
    }
  }
}

```
