### ISSUE TITLE
MultiMarkdown Cross References

### ISSUE THREAD

**Issue by ToniWonKanobi** [markdown-it/markdown-it#168]
CommonMark has yet to implement the popular MultiMarkdown v2+ feature, "[Cross References](http://fletcher.github.io/MultiMarkdown-5/syntax.html#cross-references "Fletcher Penney's page on Cross References in MultiMarkdown v2+")."

One of the things I've struggled with is creating unique `id`'s on elements, and incorporating them into Tables of Contents. I know `markdown-it-anchor` and `markdown-it-table-of-contents` exist, but I'd prefer to have the Markdown source file be a little more platform-independent.

So, when I want to create a TOC, I have to use HTML. I'm not opposed to that, but it really doesn't look as nice as Markdown.

Consider the following Markdown: 

```
## Table of Contents

* [This Is a Header][]
* [This Is a Subhead][subhead]

# This Is a Header

This is a paragraph.

## This Is a Subhead [subhead]

This is another paragraph.

This is a [link][This Is a Header] to the header.

This is a [link][subhead] to the subhead, using an alternate reference link instead of \_the\_actual\_header\_title\_.
```

The resultant HTML would be:

```
<h2>Table of Contents</h2>

<ul>
<li><a href="#thisisaheader">This Is a Header</a></li>
<li><a href="#subhead">This Is a Subhead</a></li>
</ul>

<h1>This Is a Header</h1>

<p>This is a paragraph.</p>

<h2 id="subhead">This Is a Subhead</h2>

<p>This is another paragraph.</p>

<p>This is a <a href="#thisisaheader">link</a> to the header.</p>

<p>This is a <a href="#subhead">link</a> to the subhead, using an alternate reference link instead of _the_actual_header_title_.</p>
```

So instead of reverting to the HTML parlance of `<h1 id="...`, you can just use slightly modified Markdown link syntax. You can see how MultiMarkdown makes it easy to link to headers in the document---without having to insert icky HTML into the source document.

Just something I've been thinking about suggesting for a while :)

**Comment by puzrin** [comment]
I think you need to write your suggestions at commonmark forum. This repo is for one of implemantation, not about spec.

**Comment by ToniWonKanobi** [comment]
I'm not so concerned with what CommonMark is doing---I was suggesting that `markdown-it` incorporate this directly.

Didn't you say in a CommonMark forum post that you're kind of doing your own thing anyways? Or did I misunderstand?

**Comment by puzrin** [comment]
This project implements commonmark spec + allows extentions.

All suggestions about markup change should be discussed at commonmark forum & accepted to spec first. http://commonmark.org/
