### ISSUE TITLE
MultiMarkdown Reference Link and Reference Image Attributes

### ISSUE THREAD

**Issue by ToniWonKanobi** [markdown-it/markdown-it#169]
CommonMark has yet to implement the popular MultiMarkdown v2+ feature, "[Link and Image Attributes](http://fletcher.github.io/MultiMarkdown-5/syntax.html#linkandimageattributes)."

Consider the following Markdown:

```
This is an ![image][] link and a regular hypertext [link][].

[image]: http://path.to/image "Image title" 
[link]:  http://path.to/link.html "Some Link"
```

We're all pretty familiar with this (it's part of the original John Gruber [spec](http://daringfireball.net/projects/markdown/syntax#img)).

But what if I wanted to apply attributes to the image, like `width="100%"`, or `class="big"`, I would have to use an `<img>` tag instead. 

MultiMarkdown allows this:

```
This is an ![image][] link and a regular hypertext [link][], with attributes.

[image]: http://path.to/image "Image title" width=100% class=big style="border: solid black 1px;"
[link]:  http://path.to/link.html "Some Link" class=external
```

So we could use basically the same syntax that we're used to for reference image links and hypertext links :)

**Comment by puzrin** [comment]
@ToniWonKanobi , please don't create spec suggestions in this repo. It's a wrong place for such things.

**Comment by ToniWonKanobi** [comment]
See my previous response. I don't care about the spec! That's why I am asking you directly to incorporate it into `markdown-it`.

Is that something you're interested in doing or no?

**Comment by puzrin** [comment]
@ToniWonKanobi , i understant, but we DO care about specs. So, direct changes can not be accepted. Right place for such suggestions is commonmark forum.

**Comment by ToniWonKanobi** [comment]
Apologies—I was under the impression that `markdown-it` was based on CommonMark, but could also be modified for some things that CommonMark does not contain, such as URL autolinking, etc.

Again, apologies :)
