### ISSUE TITLE
no effect? set highlight after instance

### ISSUE THREAD

**Issue by XGHeaven** [markdown-it/markdown-it#170]
I set `highlight` opts after instance, like this
```javascript
var md = require('markdown-it')();

md.set({
    highight: function() {
        // code in here
    }
})
```
no effect. But i move it in constructor's opts, it works. code follows
```javascript
var md = require('markdown-it')({
    highlight: function(){
        // code
    }
})
```

why?

**Comment by puzrin** [comment]
Hm... No idea. It should work. Could you provide minimal executable examples to investigate?

**Comment by XGHeaven** [comment]
I solve it, it really work.
But I find a other problem.

it can't highlight code with tab indent
such as
```
    code here start with four space
    can't highlight
```

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.js#L26-L51

That's intendend, because tabbed blocks have no language, and guessing is not acceptable for all. Just override code block renderer in similar way as fenced one works.

**Comment by XGHeaven** [comment]
Oh, thanks~~~
