### ISSUE TITLE
Simple tables vs Complex tables

### ISSUE THREAD

**Issue by Martii** [markdown-it/markdown-it#171]
This package doesn't seem to handle complex tables in GFM such as:

 | [![Mozilla Firefox][imgfx]][urlfx] | [![Mozilla SeaMonkey][imgsm]][urlsm] | [![Apple Safari][imgsi]][urlsi] | [![Opera Software Opera][imgoa]][urloa] | [![Microsoft Internet Explorer][imgie]][urlie] | [![Chromium Projects Chromium][imgcm]][urlcm][![Google Chrome][imgce]][urlce] | &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
:-----: | :-----: | :-----: | :-----: | :-----: | :-----: | :-----: | :-----: | :-----:
![Linux][imgtux]     | [![Greasemonkey][imggmao]][urlgmao] [![Greasemonkey prc][imggmsf]][urlgmsf]&#10;[![uso - installWith][imgiwi]][urliwi] [![GM_config][imggmc]][urlgmc] | [![Greasemonkey Port][imggpsf]][urlgpsf] [![uso - installWith][imgiwi]][urliwi] [![GM_config][imggmc]][urlgmc] | &ndash; | &ndash; | &ndash; | &ndash;
![Macintosh][imgmac] | [![Greasemonkey][imggmao]][urlgmao] [![Greasemonkey prc][imggmsf]][urlgmsf]&#10;[![uso - installWith][imgiwi]][urliwi] [![GM_config][imggmc]][urlgmc] | [![Greasemonkey Port][imggpsf]][urlgpsf] [![uso - installWith][imgiwi]][urliwi] [![GM_config][imggmc]][urlgmc] | &ndash; | &ndash; | &ndash; | &ndash;
![Windows][imgwin]   | [![Greasemonkey][imggmao]][urlgmao] [![Greasemonkey prc][imggmsf]][urlgmsf]&#10;[![uso - installWith][imgiwi]][urliwi] [![GM_config][imggmc]][urlgmc] | [![Greasemonkey Port][imggpsf]][urlgpsf] [![uso - installWith][imgiwi]][urliwi] [![GM_config][imggmc]][urlgmc]| &ndash; | &ndash; | &ndash; | &ndash;

[c]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/clear16.png
[ch]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/clearhalf16.png
[imgwin]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/windows16.png "Windows"
[imgtux]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/linux16.png "Linux"
[imgmac]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/macintosh16.png "Macintosh"
[imgfx]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/firefox16.png "Mozilla Firefox"
[imgsm]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/seamonkey16.png "Mozilla SeaMonkey"
[imgsi]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/safari16.png "Apple Safari"
[imgoa]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/opera16.png "Opera Software Opera"
[imgie]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/iexplorer16.png "Microsoft Internet Explorer"
[imgcm]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/chromium16.png "Chromium Projects Chromium"
[imgce]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/chrome16.png "Google Chrome"
[imggmao]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/amogreasemonkey16.png "Greasemonkey on Moz"
[imggmsf]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/sfgreasemonkey16.png "Greasemonkey on SF"
[imggpsf]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/gmport16.png "Greasemonkey Port"
[imgtmgo]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/tampermonkey16.png "TamperMonkey"
[imgvmoa]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/violentmonkey16.png "Violent monkey"
[imgiwi]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/iw16.png "uso - installWith"
[imggmc]: https://raw.githubusercontent.com/sizzlemctwizzle/GM_config/master/gm_config_icon.png "GM_config"
[urlfx]: https://www.getfirefox.com/
[urlsm]: http://www.seamonkey-project.org/
[urlsi]: http://www.apple.com/safari/
[urloa]: http://www.opera.com/
[urlie]: http://www.microsoft.com/windows/internet-explorer/
[urlcm]: http://dev.chromium.org/chromium-projects
[urlce]: http://www.google.com/chrome/
[urlgmao]: https://addons.mozilla.org/firefox/addon/748
[urlgmsf]: https://sf.net/projects/greasemonkey/files/
[urlgpsf]: https://sf.net/projects/gmport/files/
[urltmgo]: http://chrome.google.com/webstore/detail/dhdgffkkebhmkfjojejmpbldmpobfkfo
[urlvmop]: http://addons.opera.com/extensions/details/violent-monkey/?hidemessage=1
[urliwi]: https://openuserjs.org/scripts/marti/httpuserscripts.orgusers37004/uso_-_installWith
[urlgmc]: https://github.com/sizzlemctwizzle/GM_config/wiki/

... which renders,  using *markdown-it*, as:

![markdownitsimplevscomplexfailing](https://cloud.githubusercontent.com/assets/114709/11371520/2c2360e6-9286-11e5-8764-0c44b70b33aa.png)

... but should be rendered, using *marked*, as:

![markedsimplevscomplexworking](https://cloud.githubusercontent.com/assets/114709/11362997/5becdf46-9254-11e5-961a-ca44e3466ad8.png)

This is probably the only reason our project hasn't utilized this package with GFM table support appearing to be incomplete. *(although I haven't tested out our HTML sanitizer with this since we need direct calls to the block rendering but that is the next step after this issue may be resolved)*

Plain text tables appear to work but start doing non-text *(e.g. complex md with tables)* and it appears to fail. This project looks super since I first investigated it a few months back but this one little thing is enough not to use it in our project... I really like the modular *(plugin)* design though.

Is there a reason why complex tables aren't working? *(with markdown-it)* TIA

**Comment by puzrin** [comment]
> Is there a reason why complex tables aren't working?

The lack of clear specs & tests.

**Comment by Martii** [comment]
I can write some tests for tables but the specs are buried on GH somewhere in code most likely... I can ask support but they may or may not share that info *(possibly telling me to go hunt for it)*... IDK yet.

If I were to guess at this... without fully knowing this project here... I would possibly assume that a precedence issue is present on parsing and **might** be the issue... again IDK yet.

Thanks for the reply.

**Comment by puzrin** [comment]
Could you simplify your example (reduce size to minimal possible)?

**Comment by vyp** [comment]
@Martii Do you know what GitHub uses for GFM parser?

**Comment by Martii** [comment]
@vyp 
That's what I would need to go hunting for... GH uses codenames for each of their components *(gollum for example is their wiki)* and I'd have to find out what it is, go find it, then see if it's a language I know, and see if I can decipher the GFM table standards.

@puzrin 
I'll see if I can simplify where  it first starts to fail but the code itself is in the [first post above](/markdown-it/markdown-it/issues/171#issue-118567752)... the original HTML I posted back in the day is [here](https://gist.github.com/Martii/504114) but that's just the markup.

**Comment by vyp** [comment]
@Martii I looked for this before and was pointed to https://github.com/vmg/redcarpet, but then later I was told that's not what GitHub uses anymore, but I don't think I was ever told what it *does* use now. Hence why I asked, good luck.

**Comment by Martii** [comment]
@puzrin 
Looks like this is what is busting tables in *markdown-it*:

With...

``` md
| [![Mozilla Seamonkey][imgsm]][urlsm] |
 :-----:
| [![Greasemonkey Port][imggpsf]][urlgpsf] [![uso - installWith][imgiwi]][urliwi] [![GM_config][imggmc]][urlgmc] |
```
... notice that the pipes aren't matched intentionally. GH itself doesn't seem to care in my first post above... e.g. it inherits the outer pipes is a guess.

This also busts it:

``` md
| [![Mozilla Seamonkey][imgsm]][urlsm] | something else |
| :-----: |  :-----: |  :-----: |
| [![Greasemonkey Port][imggpsf]][urlgpsf] [![uso - installWith][imgiwi]][urliwi] [![GM_config][imggmc]][urlgmc]

```
... where the "th" count is **two** and the next line down count is **three**... again GH doesn't seem to care.

| [![Mozilla Seamonkey][imgsm]][urlsm] | something else |
| :-----: |  :-----: |  :-----: |
| [![Greasemonkey Port][imggpsf]][urlgpsf] [![uso - installWith][imgiwi]][urliwi] [![GM_config][imggmc]][urlgmc]

[c]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/clear16.png
[ch]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/clearhalf16.png
[imgwin]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/windows16.png "Windows"
[imgtux]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/linux16.png "Linux"
[imgmac]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/macintosh16.png "Macintosh"
[imgfx]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/firefox16.png "Mozilla Firefox"
[imgsm]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/seamonkey16.png "Mozilla Seamonkey"
[imgsi]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/safari16.png "Apple Safari"
[imgoa]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/opera16.png "Opera Software Opera"
[imgie]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/iexplorer16.png "Microsoft Internet Explorer"
[imgcm]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/chromium16.png "Chromium Projects Chromium"
[imgce]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/chrome16.png "Google Chrome"
[imggmao]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/amogreasemonkey16.png "Greasemonkey on Moz"
[imggmsf]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/sfgreasemonkey16.png "Greasemonkey on SF"
[imggpsf]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/gmport16.png "Greasemonkey Port"
[imgtmgo]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/tampermonkey16.png "TamperMonkey"
[imgvmoa]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/violentmonkey16.png "Violent monkey"
[imgiwi]: https://raw.githubusercontent.com/Martii/UserScripts/master/res/compatibilityMatrix/iw16.png "uso - installWith"
[imggmc]: https://raw.githubusercontent.com/sizzlemctwizzle/GM_config/master/gm_config_icon.png "GM_config"
[urlfx]: https://www.getfirefox.com/
[urlsm]: http://www.seamonkey-project.org/
[urlsi]: http://www.apple.com/safari/
[urloa]: http://www.opera.com/
[urlie]: http://www.microsoft.com/windows/internet-explorer/
[urlcm]: http://dev.chromium.org/chromium-projects
[urlce]: http://www.google.com/chrome/
[urlgmao]: https://addons.mozilla.org/firefox/addon/748
[urlgmsf]: https://sf.net/projects/greasemonkey/files/
[urlgpsf]: https://sf.net/projects/gmport/files/
[urltmgo]: http://chrome.google.com/webstore/detail/dhdgffkkebhmkfjojejmpbldmpobfkfo
[urlvmop]: http://addons.opera.com/extensions/details/violent-monkey/?hidemessage=1
[urliwi]: https://openuserjs.org/scripts/marti/httpuserscripts.orgusers37004/uso_-_installWith
[urlgmc]: https://github.com/sizzlemctwizzle/GM_config/wiki/

**Comment by rlidwka** [comment]
Fixed, now all examples you posted above should work like they do on github.

There are still no guarantees that the output will always match 'cause there is no specification for tables.
