### ISSUE TITLE
Modularity of core

### ISSUE THREAD

**Issue by Martii** [markdown-it/markdown-it#172]
So I was investigating flowdock/markdown-it-flowdock#3 and it would appear that *markdown-it* *(and so is marked package with a false "hit")* is handling `_emphasis_ markdown syntax` first then that package is failing with a "miss" since it is a post operation.

Hopefully not presuming too much... I can possibly see some logic alternatives to fix this:

1. Add a priority parameter somewhere that says "do this plugin before the core" ... I'm only a few days into in-depth checking this project out so thanks for your patience if this already exists. Still may present as an issue with `a`nchor tags with `textContent`.
2. Refactor with a breaking change the core of this project to have all core markdown parsing handled as individual plugins... so that we can `use` them in whatever priority we choose. Still may present as an issue with `a`nchor tags with `textContent`.
3. As a last resort we can blacklist `_` and we already blacklist `*` ... this may break other sites if adopted and definitely going to confuse all users including ours when I go around and renaming their account with an announcement.

Any thoughts on this from this upstream here and downstream there?

**Comment by puzrin** [comment]
https://markdown-it.github.io/markdown-it/#Ruler

You already can inject your plugin rules before/after some. Anything wrong with that?

**Comment by Martii** [comment]
> Anything wrong with that?

Maybe... the core, which is this project, processes `@_foo_` first and converts it to `@<em>foo</em>` which renders as @_foo_ ... then the mentioned plugin incorrectly handles it and does `<a class="mention"><em>foo</em></a>` which renders as *(simulated on GH as they have the same issue)* <a class="mention" href="/"><em>foo</em></a>... e.g. if we could get the plugins to be able to execute first then have the core of this project it **might** handle it a little better with keeping the underscores intact with the issued username.

I guess better questions:

* Can a plugin developer tell *markdown-it* to postpone handling its own built-in plugins until the third-party finishes first?
* Does the core *markdown-it* name every "process" *(say emphasis, strong, tables, etc)*?

I appreciate your feedback as I'm still learning how to assist others with their plugins and perhaps writing one myself. :)

**Comment by puzrin** [comment]
> Can a plugin developer tell markdown-it to postpone handling its own built-in plugins until the third-party finishes first?

No. You need to inject your plugin with more high proirity than existing one to consume such content.

> Does the core markdown-it name every "process" (say emphasis, strong, tables, etc)?

Yes.

**Comment by Martii** [comment]
> > Does the core markdown-it name every "process" (say emphasis, strong, tables, etc)?
> Yes

So I might be able to change the priority of the core to be later then... e.g. postponing? *(getting my terminology in sync with yours here)*

Alright... I'll do some twiddling after the holiday here and see if I can get that plugins issue fixed as it's nearly exactly what we're looking for. I'd rather not blacklist `_` from our usernames on our production site is the main reason. It seems that referenced plugins development just stopped a while back. I don't like using CSS `content` to modify things not to mention that plugin doesn't actually set the `href` yet.

If it's alright with you can I keep this issue open? I'll scour over the API very soon and see if my objective, and the reporters too, can be achieved.

**Comment by puzrin** [comment]
I'd prefer to close it, because such common issues without clear resolution have tendency to be "endless". It's better to create a new one when needed. I think, after digging code, docs & existing plugins in npm, the number of your question will decrease significantly.

**Comment by Martii** [comment]
One trick of the trade is to use HTML entities too... so the flowdock plugin might be able to set the `href` `textContent` to an entity.

**Comment by puzrin** [comment]
It's better to create a new token with separate renderer.

**Comment by Martii** [comment]
Alright.... plenty to "chew" on here... closing... Thanks for your assistance. :)
