### ISSUE TITLE
Questions regarding AST

### ISSUE THREAD

**Issue by IngwiePhoenix** [markdown-it/markdown-it#176]
I am currently trying to wrap my head around MarkdownIt's generated AST. Mainly because I want to adapt it into: https://github.com/kueblc/LDT

So far, I actually can identify elements to some degree. But I am lacking a way to actually make newlines.

In LDT's default, RegEx based parser, the `\n` character is actually still present from the input - so that is used. But within MarkdownIt's AST these are gone.

Here is the code that I currently have. Its still hacky, but I am getting there.

```javascript
/**
 * Transforms a markdown-it AST into a simplified array.
 * That array should only contain objects of format:
 *
 * {
 *     type: "Name of the token",
 *     content: "...",
 * }
 */
var transform = function(AST, tokens, parentStack) {
    tokens = tokens || [];
    parentStack = parentStack || [];
    var previous = null;
    for(var node_id=0; node_id<AST.length; node_id++) {
        var ASTNode = AST[node_id];
        previous = (previous==null ? ASTNode : AST[node_id-1]);
        if(ASTNode.markup != '' && ASTNode.nesting != -1) {
            tokens.push(new mdASTNode({
                type: ASTNode.tag,
                content: ASTNode.markup+" "
            }));
        }
        if(ASTNode.children != null) {
            transform(ASTNode.children, tokens, previous);
        } else {
            if(ASTNode.type == "text") {
                // Text! Let's find the proper name for it.
                var parent = previous;
                while(parent.tag == '' && parentStack.length > 0) {
                    // Either, parent being the previous token will
                    // already result in a valid, tag'ed token.
                    // Alternatively, we pop the parent stack till it can pop no' mo'.
                    parent = parentStack.pop();
                }
                if(parent.tag == '' && parentStack.length == 0) {
                    throw new Error("The parentStack has ran out and no matching node was found.");
                }
                tokens.push(new mdASTNode({
                    type: parent.tag,
                    content: ASTNode.content
                }));
            }
        }
    }
    return tokens;
}

var mdASTNode = function(node) {
    this.node = node;
}
mdASTNode.prototype.toString = function() {
    return this.node.content;
}
mdASTNode.prototype.identify = function() {
    return "ldt-"+this.node.type;
}

module.exports = transform;
module.exports.mdASTNode = mdASTNode;
```

`mdASTNode` needs a `toString()` method since the original parser within LDT would return a string array, and will treat the returned tokens as such. The latter `identify` method is used to return a class-name.

What would be the best way to figure out newlines - and, do you maybe have suggestions what to add here?

The `transform` function is sued as a substitute for LDT's default `tokenize` function. It receives a MarkdownIt AST:

```javascript
        var parser = {
            add: function(){
                throw new Error("Can't add dynamic rules. Yet.");
            },
            tokenize: function(input){
                return transform(markdownIt.parse(input));
            },
            identify: function(token){
                return token.identify();
            },
        };
        var ta_l = new LDT($ta[0], parser);
```

The `token` argument to `identify` is just one of those returned by `tokenize`.

Any help/idea would be much appreciated :)

**Comment by puzrin** [comment]
@IngwiePhoenix i'm not familiar with that project. Could you reduce your question, leaving only markdown-it related things?

Line breaks are generated in [newline](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/newline.js) rule as `softbreak` / `hardbreak` tokens.

**Comment by IngwiePhoenix** [comment]
@puzrin Alright, I'll try my best. :)

I am trying to parse the AST returned by `MarkdownIt.parse(String $input)`. For my purpose, I want to extract just the text sequences, and the tag name. That way, I'd end up with something like this:

Input: 
```markdown
# Story

Foo goes to Baz' bar. 
He spends a **lot** of money.
```

This is what i'd like to turn that into:
```javascript
var nodes = [
    { type: "h1",   content: "# Story\n\n" },
    { type: "p",    content: "Foo goes to Baz' bar.\n\n" },
    { type: "p".    content: "He spends a" },
    { type: "b",    content: "lot" },
    { type: "p",    content: "of money.\n" }
]
```

I wouldn't mind if I would add empty `{type: "break", content:null}` tokens to the list - but what I really need is to be able to get the line breaks-

As you say `newline`, would I simply do: `MarkdownIt.enable("newline")` to enable them?

**Comment by puzrin** [comment]
> As you say newline, would I simply do: MarkdownIt.enable("newline") to enable them?

I think, that should work. It's normal to use 'zero' preset and enable only those plugins you need.

**Comment by puzrin** [comment]
See https://github.com/markdown-it/markdown-it/blob/master/lib/presets/zero.js it enables only minimal possible set of rules. Others can be switched according to your requirements.

**Comment by IngwiePhoenix** [comment]
I see - thanks for that.

I have been busy for a while and just came back. While I talked to another guy, they reminded me of something I had totally forgotten: Tokens.

So basically, he explained to me that normally a parser tokenizes the input first, and only then builds an AST.

Is there a way to get these tokens from `markdown-it`? I am just trying to find a way to make this as best as I can, since the AST is going to be very nested - and all I want is just a list of simple objects with a name and value.

**Comment by puzrin** [comment]
- https://github.com/markdown-it/markdown-it/blob/master/lib/index.js#L520
- https://markdown-it.github.io/markdown-it/#MarkdownIt.parse

Call `.parse()` and then play with toens as you wish.
