### ISSUE TITLE
some nested unordered list items get parsed as code blocks

### ISSUE THREAD

**Issue by erusev** [markdown-it/markdown-it#179]
```
  1. li
    - li
```

**Comment by rlidwka** [comment]
It's not a *nested* unordered list item. If you want to make it nested, you need to indent "-" so it'll be below "1" like this:

```md
  1. li
     - li
```

As it's written, "-" is on the same level as "1.", so it's either a list+list (not nested) or list+code block. I'm not sure which one is it.

**Comment by puzrin** [comment]
- [ref](http://spec.commonmark.org/dingus/?text=%20%201.%20li%0A%20%20%20%20-%20li)
- [our](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%20%201.%20li%5Cn%20%20%20%20-%20li%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

ref dingus works differently

**Comment by puzrin** [comment]
Since issue is forwarded to spec https://github.com/jgm/CommonMark/issues/385, closing this. Because:

1. It's not critical, and not related to this parser directly.
2. We will fix it anyway after spec update, because new tests will be added.
