### ISSUE TITLE
typographer: true should not touch quotes inside code elements

### ISSUE THREAD

**Issue by ivan-kleshnin** [markdown-it/markdown-it#182]
```js
import Markdown from "markdown-it";

let markdown = Markdown({
  html: true,
  typographer: true,
});

console.log(
  markdown.render('"test" <code>console.log("test");</code>')
);
```

#### Result

```html
<p>“test” <code>console.log(“test”);</code></p>
```

#### Expected

```html
<p>“test” <code>console.log("test");</code></p>
```

This breaks potential code highlighting, copy-paste is invalid, etc. etc.
Of course, all possible breaks **typographer** can introduce need to be reviewed.
Verified in **v4.01** and **v5.02**.

**Comment by rlidwka** [comment]
What's the reason to use html code tags instead of markdown ones in your case?

This works correctly and will produce exactly the expected output:

```md
"test" `console.log("test");`
```

**Comment by ivan-kleshnin** [comment]
> What's the reason to use html code tags instead of markdown ones in your case?

Markdown does not support any syntax for inline fenced blocks. I want to highlight inline code as well as block.

**Comment by puzrin** [comment]
There are many way how smartquater can be exended. For example, it can analyze language to select proper quotes automatically. But i think, all those extentions should not be included in basic package.

Analyzing HTML tags nesting will do things much more complicated, and is a bit out of this project goals. Currently parser does not do anything with HTML tags, just forward it as raw output. So, i tend to decline this request. IMHO, if you wish to use HTML tags, you could write your own smartquoter.

**Comment by ivan-kleshnin** [comment]
If tag structure is not considered currently, it surely does not worth the complexity. 
I'll just disable typographer for now.
