### ISSUE TITLE
Article preview, separator line and metadata

### ISSUE THREAD

**Issue by deni35** [markdown-it/markdown-it#185]
In wordpress I could add separator line in article. And in preview of article will be shown only text before this line.
And I want to use metadata, like: data, author.
In general, I want:
```
data: 04.01.2015
author: Den

First paragraph.
--- 
Rest text.
```

I was looking for plugin, but nothing is found.
Is there way to do it?

**Comment by rlidwka** [comment]
It's called "yaml header", and I'm pretty sure there are plugins to do it.

I wrote my own plugin for this, you can copy that code if you want:
https://github.com/rlidwka/render-readme/blob/master/lib/rules/meta.js

**Comment by deni35** [comment]
I found nothing https://www.npmjs.com/search?q=markdown-it+yaml
Why do you still not add your plugin to npm?

**Comment by puzrin** [comment]
1. Metadata should be processed & shrinked before markdown parse. For example with https://www.npmjs.com/package/yaml-front-matter. That's not related to markdown-it directly.
2. I don't know plugin for `cut`. Probably, you will need to write your own.

**Comment by deni35** [comment]
Thank you.
I like this package https://www.npmjs.com/package/front-matter
