### ISSUE TITLE
Pre > Code tags with markup create unexpected results

### ISSUE THREAD

**Issue by apipkin** [markdown-it/markdown-it#187]
I am processing a code fence with another plugin and replacing it with a live code example and documentation about the code example (think embedded codepen). 

However, the processing after this within markdown-it is modifying the code within the CODE tag. For instance, it's extra escaping the code and printing portions of the formatted HTML already on the page. 

I have HTML set to true, but this still happens. Any help would be appreciated.

**Comment by puzrin** [comment]
http://spec.commonmark.org/0.23/#html-blocks i guess, problem is caused by empty lines in html blocks.

I'd suggest to do additional processing after markdown-it (or before render).

**Comment by SofianHn** [comment]
I am hitting similar issues here, here is an example: 
```
<p>remove this and it should work fine</p>
<pre> 

       <span>this should not be escaped</span>
</pre>
```
This code block will render correctly if you do one of the following things: 
1- remove the p tag at the beginning
2- remove the extra space after pre

According to http://spec.commonmark.org/0.23/#html-blocks, this fits condition number 1 of having a a line begins with pre. Anything inside should be escaped and rendered as is.

**Comment by puzrin** [comment]
You are right, pre is one of special cases and can contain white lines, but has to go itself after white line.

Anyway, that spec related and not markdown-it issue.

Closing?

**Comment by SofianHn** [comment]
> but has to go itself after white line.

Where is that in the spec? If I am reading it correctly it defines a block as any number of lines that starts with <pre> and ends with </pre>. I did not find a reference on not containing white lines?

**Comment by puzrin** [comment]
http://spec.commonmark.org/0.23/#html-blocks

see (6). In your example block starts with `<p>`, and miss `<pre>` because goes until white line.

**Comment by SofianHn** [comment]
in that case 
```
<p>remove this and it should work fine</p>

<pre> 

       <span>this should not be escaped</span>
</pre>
```

should render correctly and it does not. This can be a good workaround to insure that `<pre>` is wrapped with whitelines. Otherwise how would you suggest working around this?

**Comment by puzrin** [comment]
[demo](http://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Cp%3Eremove%20this%20and%20it%20should%20work%20fine%3C%2Fp%3E%5Cn%5Cn%3Cpre%3E%20%5Cn%5Cn%20%20%20%20%20%20%20%3Cspan%3Ethis%20should%20not%20be%20escaped%3C%2Fspan%3E%5Cn%3C%2Fpre%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D)

I see no problem with your "fixed" example. It renders as needed. Adding white line before opening pre helps.

**Comment by SofianHn** [comment]
my bad, it works fine. thanks!

**Comment by puzrin** [comment]
No problem. Just note that markdown-it and commonmark have online demos, that can help to quickly check everything about spec and provide examples for issues.

**Comment by apipkin** [comment]
I padded the plugin output with two `\n` at the beginning and the end (just to be on the safe side). Works like a charm!  I spent a good part of the day last week trying to track this down and go no where close to a line-break fix. Thank you so much for the help!
