### ISSUE TITLE
highlight.js. code block mush have hljs class.

### ISSUE THREAD

**Issue by deni35** [markdown-it/markdown-it#188]
To use style of code background, ```<code>``` mush have the "hljs" class.
Now I've done it the next way:
```js
    var fenceFn = md.renderer.rules.fence;
    md.renderer.rules.fence = function(tokens, idx, options, env, slf) {
        var token = tokens[idx];
        token.attrPush([ 'class', 'hljs' ]);
        return fenceFn.apply(this, arguments);
    }
```
It looks like it works, but it return such html: ```<code class="hljs" class="language-js">```. 
I'm afraid this will work incorrectly. Chrome dev tool shows only first class.

**Comment by puzrin** [comment]
do like this https://github.com/markdown-it/markdown-it/commit/88c6e0f8e6fd567c70ffabbc1e9ce7b980d2e3a9

**Comment by deni35** [comment]
I see you add this class:
```js
return  '<pre **class="hljs"**><code' + slf.renderAttrs(token) + '>'
 +          + highlighted
 +          + '</code></pre>\n';
```
Cool) Only 6 hours as you have fixed it yet.

**Comment by deni35** [comment]
I think it will be better if you will combine all the classes in one attribute. It will be more versatile.

**Comment by puzrin** [comment]
There are 2 problems:

1. We work with attributes, not with classes. So, we can not know in advance, if attribute allow join content or not.
2. Hightlighter can not change `<pre>`.

I could add method `.join(attr, data)`, but that will not help with (2).

**Comment by puzrin** [comment]
Created #189 to discuss.

**Comment by deni35** [comment]
Не пойму что Вы имеете в виду.
```class="hljs" class="language-js"```
```class="hljs language-js"```
Второй вариант всегда будет работать. Что может не позволить соединить все class-ы в один атрибут?
Просто записать все классы в отдельный массив(или даже Set из ES6), а потом отрендерить их отдельно от остальных атрибутов.

**Comment by puzrin** [comment]
Please, speak english, that's international repo. Setting .hljs to `code` will conflict with twitter bootstrap, you can check it in demo with devtools.

**Comment by deni35** [comment]
I understood. You add class hljs to ```<pre>```, and attrs render to ```<code>```.
Maybe render attrs to ```<pre>```? All the same language-js class in not used.
Bootstrap 4 has "pre code" selector, but page looks normal.

Yeah, You need more flexible html wrapper generation. it's difficult to do it.
Or if this attrs render system is using only for such simply cases, remove it.
This looks good.
```
`<pre class="hljs"><code class="${options.langPrefix + langName}"> ${highlighted}</code></pre>\n`
```
