### ISSUE TITLE
minor version update `5.1.0` has breaking changes

### ISSUE THREAD

**Issue by ashleygwilliams** [markdown-it/markdown-it#190]
may be related/dupe of #189 

you just released `5.1.0`, a minor version update. but your highlighting changes are breaking, and broke my package [`npm/marky-markdown`](https://github.com/npm/marky-markdown), see https://github.com/npm/marky-markdown/pull/90

valid semver suggests that breaking changes should be a major version bump. given that, most people use `^` so npm doesn't match a new major version (because it would have potentially breaking changes). your only using a minor version bump will likely cause breaks in other packages, as it did mine.

perhaps you didn't know you had a breaking change on your hands! it happens. i'd recommend removing this `5.1.0` version and re-publishing a major version release. 

happy to help with that if you need it. open source is hard and takes lots of work. thanks for contributing!

**Comment by puzrin** [comment]
Please, provide clear example. 5.1.0 should be backward compatible.

**Comment by ashleygwilliams** [comment]
it specifically breaks these tests on my package:

```js
  it('converts github flavored fencing to code blocks', function () {
    assert(~fixtures.basic.indexOf('```js'))
    assert($('code').length)
  })

  it('adds js class to javascript blocks', function () {
    assert(~fixtures.basic.indexOf('```js'))
    assert($('code.js').length)
  })

  it('adds sh class to shell blocks', function () {
    assert(~fixtures.basic.indexOf('```sh'))
    assert($('code.sh').length)
  })

  it('adds coffeescript class to coffee blocks', function () {
    assert(~fixtures.basic.indexOf('```coffee'))
    assert($('code.coffeescript').length)
  })

  it('adds diff class to diff blocks', function () {
    assert(~fixtures.basic.indexOf('```diff'))
    assert($('code.diff').length)
  })

  it('allows classnames on code tags', function () {
    assert($('code.highlight').length)
  })
```

**Comment by ashleygwilliams** [comment]
you can reproduce this by cloning the package and running the tests:

- `markdown-it@5.0.2`: 90pass 0fail
- `markdown-it@5.1.0`: 84pass 6fail

**Comment by puzrin** [comment]
@ashleygwilliams i can not debug your package. Sorry, but to accept this issue i need more clear and short example what is wrong with api.

**Comment by ashleygwilliams** [comment]
ok i'll make you one, once i'm done patching my package.

**Comment by puzrin** [comment]
FYI https://github.com/markdown-it/markdown-it/commit/87ece24ff997502418e74fffc3ad78173af4a1d1#diff-de043c47b7a14d2d383d220efbaa9c2eR48 this is the only change about highlighter, and i have no idea how could it break your code if you escaped things properly.

**Comment by revin** [comment]
@puzrin I admit I don't know what "properly" means in this context, and I apologize for not having a clear example for you to run; but what's happening is, the [highlighter](https://github.com/atom/highlights) @ashleygwilliams' package is using is rendering code blocks as, e.g. (straight from the highlighter's [README](https://github.com/atom/highlights/blob/master/README.md)):

```html
<pre class="editor editor-colors">
  <div class="line">
    <span class="source js">
      <span class="storage modifier js"><span>var</span></span>
      <span>&nbsp;hello&nbsp;</span>
      <span class="keyword operator js"><span>=</span></span>
      <span>&nbsp;</span>
      <span class="string quoted double js">
        <span class="punctuation definition string begin js"><span>&quot;</span></span>
        <span>world</span>
        <span class="punctuation definition string end js"><span>&quot;</span></span>
      </span>
      <span class="punctuation terminator statement js"><span>;</span></span>
    </span>
  </div>
</pre>
```

Since the commit you reference skips the `<pre><code>...</code></pre>` wrapper if the first rendered element is `<pre>`, the highlighted code blocks now lack the wrapper, whereas with 5.0.x we ended up with:

```html
<pre>
   <code class="highlight js">
      <pre class="editor editor-colors">
        <div class="line">
          <span class="source js">
          <!-- snip -->
      </pre>
   </code>
</pre>
```

i.e., the output above, but wrapped.

The tests she refers to all hinge on that `<code>` element appearing in the rendered output, so that's why they're failing now.

**Comment by puzrin** [comment]
@revin, i think nested `pre`, when second one is not escaped, are very special case. Probably, it's better to fix your test & code you generate. Or if such use is common, could you explane me why?

**Comment by puzrin** [comment]
I mean, if highlighter function returns <pre>..., it does not need to be wrapped again.

**Comment by revin** [comment]
@puzrin I couldn't guess one way or another how common nested `<pre>` elements are, and I definitely see where you're coming from. However, I think the bottom line for this issue is that per semver, this is a breaking change now, right? 5.0.x supported nested `<pre>` (even if such support was an accident) and 5.1 drops support for it.

**Comment by aredridel** [comment]
Aw, geez. This breaks npm's web site's tests. It's definitely a breaking change.

**Comment by puzrin** [comment]
> this is a breaking change now, right?

I consider it as a bug on npm site due improper use. I use markdown-it too, and had no breaks in this place.

> 5.0.x supported nested <pre> (even if such support was an accident) and 5.1 drops support for it.

NO. It does NOT drop support. Only removes double wrapper, if highlighter already returned it. If you take example from previus version, it will work without problems.

**Comment by revin** [comment]
I understand. My wording could have been clearer, for sure.

The basic point I'm trying to make is this: removing the double wrapper isn't backwards compatible. The question of *whether anyone should have been relying on it* is immaterial for the purpose of SemVer numbering, that's all I'm trying to say.

**Comment by jefflembeck** [comment]
> I couldn't guess one way or another how common nested <pre> elements are

```html
<pre>
  <code>
   ...
  </code>
</pre>
```
is, unfortunately for this issue - pretty dang common for anybody showing code blocks (as far as I've seen)

**Comment by aredridel** [comment]
Yeah. Does leave the semantic meaning there, though mostly it just affects styling of downstream users.

**Comment by puzrin** [comment]
@is, unfortunately for this issue - pretty dang common for anybody showing code blocks (as far as I've seen)

Content of your example (html code in fenced block) MUST be escaped, and will NOT fall under used condition.

**Comment by puzrin** [comment]
> The basic point I'm trying to make is this: removing the double wrapper isn't backwards compatible. The question of whether anyone should have been relying on it is immaterial for the purpose of SemVer numbering, that's all I'm trying to say.

@revin let's leave politics aside. I understand your point, but consider cirrent case very specific to be covered by semver (at least, until i see correct example). I can invent dosen cases to intentionally break even on patch number change.

IMHO the best solution is to apply patch for npm website and move forward. You would have to do it after major version too.

**Comment by revin** [comment]
@puzrin No politics intended on my end, for sure. I'm happy to agree to disagree on this and move forward accordingly. Thanks for the consideration!

**Comment by puzrin** [comment]
@ashleygwilliams @aredridel @jefflembeck

Since source of error is clear, my suggestion is to provide _correct_ example how nested `<pre>` can happen, or consider this issue as very specific and close it.

**Comment by aredridel** [comment]
I think on our end, we'll have to lock marky-markdown@6 to the old version (or replicate the old behavior post facto), then upgrade, release marky-markdown@7 with the breaking changes, and adjust the website for marky-markdown@7.

**Comment by ashleygwilliams** [comment]
yarp. closing.

**Comment by aredridel** [comment]
I think once we have HTML-emitting libraries, we end up with an unfortunately definite large API surface to support. Very easy to make breaking changes.

**Comment by puzrin** [comment]
Thanks for understanding. Feel free to create issues with questions, if you need help about modifying markdown-it.
