### ISSUE TITLE
How to iterate over the list of tokens without side effects with ability to replace contents of certain tokens

### ISSUE THREAD

**Issue by gajus** [markdown-it/markdown-it#195]
I am breaking my head trying to write/ use one of the existing markdown parsers to *find and replace* every text paragraph in a markdown document and leave everything else untouched.

Example Input:

```markdown
# A First Level Header

## Second Level Header

Now is the time for all good men to come to the aid of their country. This is just a regular paragraph.

The quick brown fox jumped over the lazy dog's back.

### Header 3

> This is a blockquote.
> 
> This is the second paragraph in the blockquote.
>
> ## This is an H2 in a blockquote
```

Desired effect is to identify paragraphs and replace them, e.g.

```markdown
# A First Level Header

## Second Level Header

[replaced]

[replaced]

### Header 3

> This is a blockquote.
> 
> This is the second paragraph in the blockquote.
>
> ## This is an H2 in a blockquote
```

Existing libraries such as [`marked`][1] or [`markdown-it`][2] appear to be incapable of parsing and re-creating markdown document without side-effects.

What is the best approach to find and replace a text paragraph in a markdown document?

Original question: http://stackoverflow.com/q/34914559/368691

  [1]: https://www.npmjs.com/package/marked
  [2]: https://www.npmjs.com/package/markdown-it

**Comment by gajus** [comment]
I have tried using `markdown-it` [`zero`](https://github.com/markdown-it/markdown-it/blob/master/lib/presets/zero.js) preset and writing a custom plugin that would replace the `md.block` `paragraph` rule. But this approach nevertheless produce side effects.

**Comment by puzrin** [comment]
Technically, source manipulations via output analysis require sourcemap info. I don't know markdown parsers with full and correct souremap support.

But... line numbers are available. That's not much, but could help for paragraphs. Dig into demo source - we use line numbers there to sync panes scroll.

**Comment by gajus** [comment]
> But... line numbers are available. That's not much, but could help for paragraphs. Dig into demo source - we use line numbers there to sync panes scroll.

Please provide a link to the referenced demo. I have looked through quite a few code examples and plugin source codes already.

**Comment by puzrin** [comment]
https://markdown-it.github.io/ :)

And here is init we use to inject line numbers https://github.com/markdown-it/markdown-it/blob/master/support/demo_template/index.js#L178. Sorry, for messy code - it was written for demo only.

**Comment by gajus** [comment]
> And here is init we use to inject line numbers https://github.com/markdown-it/markdown-it/blob/master/support/demo_template/index.js#L178. Sorry, for messy code - it was written for demo only.

Just a tip, but avoid using master branch when linking to the source code. Use a specific commit or a tag, e.g. https://github.com/markdown-it/markdown-it/blob/5.1.0/support/demo_template/index.js#L116. I have seen you do the former on some other GitHub issues. The links become useless as soon as the source code on the master changes.

Thank you. I will have look.

**Comment by gajus** [comment]
An interesting observation (and my oversight) http://stackoverflow.com/questions/34914559/detect-and-replace-text-paragraph-in-a-markdown-document?noredirect=1#comment57586910_34914559.

**Comment by puzrin** [comment]
Thanks for advice. For root-level blocks, existing lines info should be enougth (because columns value is always zero).

**Comment by puzrin** [comment]
closing?
