### ISSUE TITLE
RangeError Maximum call stack size exceeded

### ISSUE THREAD

**Issue by akhoury** [markdown-it/markdown-it#197]
I know this is ridiculous, why does this huge ~2MB text cause a rangeError, but when trying a simpler text with the same length doesn't. I have yet to find the needle, I figured I could ask for help.

Warning, large file, 1.9MB

https://gist.githubusercontent.com/akhoury/6a9849ec25fcf0a57963/raw/67737bc9324dbcecb6a4dee36113b4416f6125e6/wtf

I know this doesn't look like Markdown either, but just humor me :) trying to find why does that fail.

Thanks.

**Comment by puzrin** [comment]
Please, clarify parse options. Default? Just `md.render(bigfile)`?

**Comment by puzrin** [comment]
Hm... if i copy-paste text to demo, i see "too much recursion" in console. That's strange, because we did some tricks to limit nesting.

Thanks for report!

**Comment by akhoury** [comment]
default, sorry, yea, in Chrome, I get the RangeError on the [demo](https://markdown-it.github.io/) page

**Comment by puzrin** [comment]
Fixed in 6.0.0. It no longer crash on patterns exceeding nesting calls limit (it will not parse some bad pattern, but without crash).
