### ISSUE TITLE
"<div>3</div> ~~3~~" ,   result in "~~3~~" ,not "<s>3</s>"

### ISSUE THREAD

**Issue by scil** [markdown-it/markdown-it#198]
~~~
            var md = markdownit({
                html: true,
            });
~~~

"<span>3</span> ~~3~~" , result in "<span>3</span> <s>3</s>"
but "<div>3</div> ~~3~~“， result in "<div>3</div> ~~3~~"

**Comment by puzrin** [comment]
Please use demo to post example https://markdown-it.github.io/

**Comment by puzrin** [comment]
See spec http://spec.commonmark.org/0.24/#html-blocks html block ends with empty line, not with closing tag.
