### ISSUE TITLE
Replace `autolink` dependency with better implementation 

### ISSUE THREAD

**Issue by puzrin** [markdown-it/markdown-it#2]
1. It does not supports IDLs and non english letters in URL paths.
2. It supports only http/https schemas.
3. It contains HTML parser, not needed in our case (size, security).
4. It has some unpleasant not fixed bugs in tracker.

Probably, it worth to make a new package - could not find good alternate implementations.

Things to read about good autolinking:

- http://daringfireball.net/2009/11/liberal_regex_for_matching_urls
- http://stackoverflow.com/a/21925491/1031804

Design draft:

- https://gist.github.com/puzrin/ce95a25581a4d069e173

Other things to check:

- https://github.com/kevva/url-regex
- https://github.com/ljosa/urlize.js
- https://github.com/webmodules/urlregexp

URI schemas:

- http://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml
- http://en.wikipedia.org/wiki/URI_scheme

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/issues/38#issuecomment-70957738

Needs partial implementation in inline parser to avoid conflicts.

**Comment by puzrin** [comment]
Partially done https://github.com/markdown-it/linkexp

**Comment by Kagami** [comment]
:+1:
