### ISSUE TITLE
Rule only at beginning of string

### ISSUE THREAD

**Issue by ferllings** [markdown-it/markdown-it#201]
Hello,

I would like to write a plugin that handle metadata at the beginning of the file, with this format:

```
---
title: Report
category: main
tags: desktop, mobile
---
```

How can I detect the beginning of the string (file), and ignore the rule on other lines?

Thanks,

**Comment by puzrin** [comment]
IMHO that should be done before passing data to markdown. By regexp for example.

**Comment by ferllings** [comment]
But still you need to parse it, in order to ignore it

**Comment by puzrin** [comment]
No, for regex it's enougth to detected heading/tailing `---`. Anyway, such header can be followed by any content. You question is not specific to markdown.

**Comment by ferllings** [comment]
Ok, so if I understand correctly, you suggest to extract the meta, using regex, then only pass the content to markdown-it?

That sounds easier, indeed.

**Comment by puzrin** [comment]
Yes. I suggest to keep thing simple and process meta separately, before passing data to markdown

**Comment by ferllings** [comment]
That make sense. Thanks.

**Comment by renatocassino** [comment]
I made this simple function

```js
const parseContent = (content) => {
  const data = content.split('---');
  data.shift();

  return {
    metadata: data[0],
    content: data[1],
  };
};
```
