### ISSUE TITLE
Could this support two spaces for list indentation?

### ISSUE THREAD

**Issue by jackycute** [markdown-it/markdown-it#202]
Example:

1. Test 1.
  - Blah.
  - Blah.
2. Test 2.

```
1. Test 1.
  - Blah.
  - Blah.
2. Test 2.
```

Because GitHub support two spaces indentation list.
Could markdown-it also support two spaces for list indentation?
Or how can I customize the indentation rules?

Thank you very much!

**Comment by puzrin** [comment]
> Could markdown-it also support two spaces for list indentation?

http://spec.commonmark.org/0.24/#list-items. Your question should be asked at commonmark forum. This project implements CM spec without deviations.

> Or how can I customize the indentation rules?

You can rewrite "list" component of this parser, it's possible to override it with external implementation.

**Comment by jackycute** [comment]
Thanks for such a quick response!
Sure, http://talk.commonmark.org/t/could-also-support-two-spaces-for-list-indentation/2022

I've checked the "list" component of the parser.
I must say it's kinda hard to overwrite a block-level rule because there is too much need to know.
I will try, still not sure where exactly the list indentation size variable is.

**Comment by jackycute** [comment]
OK, I get it now.
CommonMark have strong and reasonable reason why they chose 4-spaces rule instead of others.
http://spec.commonmark.org/0.24/#motivation
