### ISSUE TITLE
bullet list and pre code

### ISSUE THREAD

**Issue by diversen** [markdown-it/markdown-it#203]
When doing this the code part will not be formatted with `<pre><code></code></pre>`. 

    * A test
    * Another test

        Code Block

But if it like this (with double newline) it will work. I guess this is a bug?

    * A test
    * Another test

        Code Block

**Comment by puzrin** [comment]
There are no bugs :) . See loose/tight lists http://spec.commonmark.org/0.24/#loose i think it worh to discuss spec-related questions at commonmark forum.

PS. use demo to provide permalinks for samples.

**Comment by diversen** [comment]
Thanks. I will remember your advice :)
