### ISSUE TITLE
Best approach for new 'block'?

### ISSUE THREAD

**Issue by benfrain** [markdown-it/markdown-it#207]
Thanks for this, looks incredibly powerful and well documented. So much so I feel I'm a little overwhelmed. Could someone point me in the right direction?

I'm parsing markdown (via Node) and want to replace certain strings. Specifically, given this markdown:

````markdown
I> Info box
````

I want to produce this HTML:

````html
<aside class="info">Info box</aside>
````

They key thing here being the `I>` combo and the end of the line being the end point.

What is the correct approach of adding this functionality for my setup? Some sort of override or do I need to create a plugin. I've looked at the source code for a few plugins but they all seem a little verbose (although that may be by necessity)

Any help appreciated, thanks again.

**Comment by puzrin** [comment]
If you need exactly `I>` markup, you need to create plugin, based on rewritten blockquote rule.

I'd recommend another plugin instead https://github.com/markdown-it/markdown-it-container, with fenced-style markup. It's ready to use.

**Comment by benfrain** [comment]
Wow - thanks for the super quick response and I'm glad I asked - that looks like EXACLY what I'm after. Thanks for this great project and the help :+1:
