### ISSUE TITLE
Turn markdown-it into a highlighter

### ISSUE THREAD

**Issue by IngwiePhoenix** [markdown-it/markdown-it#208]
Hey.

Is it possible to actually use markdown-it as a syntax highlighter itself?

My question comes from this background: I only seem to find Highlightjs being able to do syntax highlighting for basic Markdown. But I'd like to develop a flavor of markdown using markdown-it. It would be nice to use the same grammar for parsing, compiling and highlighting.

Any idea if this is possible?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/pull/204

Markdown-it doesn't track exact source positions. So, you can't know where to highlight source. That's the only one requested task, not implemented here (and not implemented in any other markdown parsers i know). You can dig closed issues, this question was asked several times in different forms.

**Comment by IngwiePhoenix** [comment]
Interesting PR. I'll definitively watch out for that one to be merged, since it does indeed contain features that would make the usage of markdown-it as a syntax highlighter possible.

Thanks for the info!
