### ISSUE TITLE
Render Markdown AST to Markdown

### ISSUE THREAD

**Issue by ericandrewlewis** [markdown-it/markdown-it#209]
It would be great to be able to build a Markdown AST and serialize it to Markdown.

**Comment by puzrin** [comment]
ripped in #125

**Comment by ericandrewlewis** [comment]
Sorry, what does ripped mean?

**Comment by puzrin** [comment]
https://www.google.ru/search?q=rip&tbm=isch :)

**Comment by puzrin** [comment]
That requires significant reqrite and we have no resources for that. You can try to write your own transformer from tokens stream to AST. There should be enougth info for that (except columns mapping).

**Comment by ericandrewlewis** [comment]
Okay, thanks for the feedback!
