### ISSUE TITLE
Can't set options for constructor, after defined preset

### ISSUE THREAD

**Issue by artemT82** [markdown-it/markdown-it#210]
I need your help, guys. I'm trying to enable linkify-it while using 'zero' preset. Here is how I do this:
`this.md = new Markdown('zero', { linkify: true })`
But it doesn't work for my app. The page doesn't even load.
I've also tried to write my own preset (which particularly is a 'zero' preset, but with enabled linkify-it) and then set it this way 
`this.md = new MarkdownIt();
 this.md.configure(myZero)`
This time page is uploading, and zero preset is enabled, but linkify-it still disabled. 
Also I tried 
`this.md = new MarkdownIt('zero').set({ linkify: true })`
Doesn't work either.
Can you advise me something?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/parser_core.js#L17

I guess you need something like

```js
require('mardown-it')('zero', { linkify: true }).enable('linkify')
```
because zero presed disabled almost all plugins.

**Comment by artemT82** [comment]
Thanks a lot. Though this exact method didn't worked for my app (infinite loading occured), but creating my own preset similar to zero but with 'linkify: true' and then writing
`this.md = new MarkdownIt(); 
this.md.configure(myZero).enable('linkify')`
did the job.
Thank you
