### ISSUE TITLE
Way to preserve empty newlines?

### ISSUE THREAD

**Issue by jay-hodgson** [markdown-it/markdown-it#211]
I realize that it's counter to the commonmark spec, but do you have any ideas on how I might go about modifying the processor to preserve empty newlines in the output html (rather than skipping)?

Restated, if you were going to convert internal line endings into `<br />` tags, where would you start?

Thank you for all of your work on this project!

**Comment by puzrin** [comment]
https://markdown-it.github.io/markdown-it/#MarkdownIt.new

`{ breaks: true }` ?

**Comment by jay-hodgson** [comment]
I wish!  Using the [nifty demo](https://markdown-it.github.io/) you can verify that these options have no impact.  For example, paste this into the input with 'breaks' turned on:
```






Test








```

**Comment by puzrin** [comment]
[example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22first%20line%5Cnsecond%20line%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Atrue%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

If you need __multiple__ consequent breaks, that's impossible in markdown, because 2 breaks = paragraph.

If you can allow yourself to not have block elements at all (quotes, lists, paragraphs), you can try to use `.renderInline()` and hack [newline](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/newline.js) if needed.

I don't understand your full task. It's very difficult to give advices by small part.

**Comment by MrHen** [comment]
I solved this problem by just breaking up the input by `\n` and parsing each line separately:

```
            return _.map(input.split('\n'), function(line) {
                return markdown.render(line).trim();
            }).join('\n');
```

**Comment by giuseppeg** [comment]
@jay-hodgson got a solution for this?

**Comment by giuseppeg** [comment]
@puzrin is there any way to implement this? maybe via plugins? If so can you give me some hint and point me to the right docs?

**Comment by thibautcornolti** [comment]
This seems to work on my side, didn't test a lot so be careful.

```js
this.md = new MarkdownIt();
const defaultParagraphRenderer = this.md.renderer.rules.paragraph_open || ((tokens, idx, options, env, self) => self.renderToken(tokens, idx, options));
    this.md.renderer.rules.paragraph_open = function (tokens, idx, options, env, self) {
      let result = '';
      if (idx > 1) {
        const inline = tokens[idx - 2];
        const paragraph = tokens[idx];
        if (inline.type === 'inline' && inline.map && inline.map[1] && paragraph.map && paragraph.map[0]) {
          const diff = paragraph.map[0] - inline.map[1];
          if (diff > 0) {
            result = '<br>'.repeat(diff);
          }
        }
      }
      return result + defaultParagraphRenderer(tokens, idx, options, env, self);
    };
```

**Comment by xueyongg** [comment]
Facing same issue as well. Whats the proper resolution?

**Comment by douglasg14b** [comment]
2023,  whole 7 years into this, still no support for multiple new lines? Or if there is (There has to be, right?) how does this work?

**Comment by TheDogHusky** [comment]
Yeah, I need that too as I'm not using Markdown It for a conventional markdown system, but for a chat app.
I mean, not a chat app but it's for a friend's website (that I make) with a ticket system. As most users that uses his website won't know conventions, and would just like to be able to type just like in discord, I'd like a working and easy implementation of multi breaks.

**Comment by be-here-meow** [comment]
Another option, that preserves new lines between all types of elements, including lists, and headings (not only paragraph returns) is to use the html option, and preprocess the markdown and insert BRs between; 

```js
const md = markdownit({ html: true })

md.render(insertBrForExtraBlankLines(content))

function insertBrForExtraBlankLines(mdText) {
	return mdText.replace(/\n{2,}/g, (match) => {
		const lineCount = match.split('\n').length - 1
		return '\n\n' + '<br>'.repeat(lineCount - 1) + '\n'
	})
}
```
