### ISSUE TITLE
How to truncate links

### ISSUE THREAD

**Issue by artemT82** [markdown-it/markdown-it#212]
I don't ask you to explain me how to perform truncation itself, I'm just wondering in which place in data flow I could get all info about link I need (href, content inside <a>...</a>).  I'm trying to do this in md.renderer.rules.link_open, but in renderer I can only work with token, which doesn't have props I need (it has 'href' in attrs, but how do I get content inside <a>...</a>?). And I'm not quite sure how can I do this in ruler. Can you advise me something?

**Comment by puzrin** [comment]
The most simple way is to call parser separate, then mutate tokens and then call renderer. Or add such mutator to the end of `core` chain.

Also, you probably need to shorten only autogenerated links, and not touch links where user defined text manually (`[manually defiled text](link)`). I this case you can scan for `link_open` tokens with attr [{ info: "auto" }](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Chttp%3A%2F%2Fexample.com%3E%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Atrue%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Afalse%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22debug%22%7D%7D), and replace following text token with shortened content.

Also see example with plugin https://github.com/markdown-it/markdown-it-for-inline#use.

**Comment by artemT82** [comment]
Thanks a lot
