### ISSUE TITLE
Odd heading behavior in one case (when hr follows)

### ISSUE THREAD

**Issue by jay-hodgson** [markdown-it/markdown-it#213]
Could you explain [why the second line is interpreted as a h2](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%23%23%23%23%20Heading%204%5CnWhy%20is%20this%20interpreted%20as%20Heading%202%5Cn---%5CnThis%20text%20is%20fine.%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Afalse%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)?

**Comment by puzrin** [comment]
http://spec.commonmark.org/0.24/#setext-headings

because spec says to do so :) ?

**Comment by jay-hodgson** [comment]
That's a good reason :)
