### ISSUE TITLE
Nested ordered lists parsed incorrectly.

### ISSUE THREAD

**Issue by ta2edchimp** [markdown-it/markdown-it#215]
Contrary to ordered lists, unordered lists are, when nested, not parsed correctly.

### Nested Unordered List

**Input:**

```Markdown
* a
* b
* c
* d
* e
  * f
  * g
  * h
    * i
    * j
```

**Output:** Correct

```html
<ul>
  <li>a</li>
  <li>b</li>
  <li>c</li>
  <li>d</li>
  <li>e
    <ul>
      <li>f</li>
      <li>g</li>
      <li>h
        <ul>
          <li>i</li>
          <li>j</li>
        </ul>
      </li>
    </ul>
  </li>
</ul>
```

### Nested Ordered List

**Input:**

```Markdown
1. a
2. b
3. c
4. d
5. e
  1. f
  2. g
  3. h
    1. i
    2. j
```

**Output:** Incorrect

```html
<ol>
  <li>a</li>
  <li>b</li>
  <li>c</li>
  <li>d</li>
  <li>e</li>
  <li>f</li>
  <li>g</li>
  <li>h</li>
  <li>i</li>
  <li>j</li>
</ol>
```

**Edit:**  
I narrowed it down being an issue with the indentation of (un)ordered lists: unordered/bullet lists work on indentations of 2 and 4 spaces, while ordered/numbered lists only work when its Markdown is entered using 4 spaces indentation.

**Comment by ta2edchimp** [comment]
Addition:
After a brief investigation, I think it has sth. to do with [how the indentation is calculated on lists](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_block/list.js#L205-L209).

On unordered/bullet lists, the marker has a length of `1` (`-`, `+`, `*`), but on ordered/numbered lists it has a length of `2` (because the number itself is suffixed by `.` or `)`).

The calculated indentation is later on passed als `blkState` property of `state` to `ParserBlock.prototype.tokenize`, [which tests for a "termination condition for nested calls"](https://github.com/markdown-it/markdown-it/blob/master/lib/parser_block.js#L59-L63).
From my point of view, this leads to a false positive for the tested nested-calls-condition. The indentation (using 2 space) of a subsidiary / nested list *will* be less than the `blkState`, thus not correctly detecting the nested list.
In a quick test, omitting the addition of `indentAfterMarker` to `initial` in order to receive the final `indent`, even nested ordered/numbered are parsed correctly — I assume anything important is done, that requires the addition of `indentAfterMarker` that I just don't see (yet).

**Comment by puzrin** [comment]
That's all according to CM spec: [proof](http://spec.commonmark.org/dingus/?text=1.%20a%0A2.%20b%0A3.%20c%0A4.%20d%0A5.%20e%0A%20%201.%20f%0A%20%202.%20g%0A%20%203.%20h%0A%20%20%20%201.%20i%0A%20%20%20%202.%20j%0A%0ARight%3A%0A%0A1.%20a%0A2.%20b%0A3.%20c%0A4.%20d%0A5.%20e%0A%20%20%201.%20f%0A%20%20%202.%20g%0A%20%20%203.%20h%0A%20%20%20%20%20%201.%20i%0A%20%20%20%20%20%202.%20j)

If you wish to change minimal indent for nested numbered lists - write to http://talk.commonmark.org

**Comment by puzrin** [comment]
Of cause you can change list rule as you wish in your project, if you need another behaviour. But that's not a bug here.

**Comment by ta2edchimp** [comment]
Thanks for clearing this up!
