### ISSUE TITLE
Breaks and \n not working

### ISSUE THREAD

**Issue by cga-F4** [markdown-it/markdown-it#216]
Tested with the 6.0.0 version (and also on you test page https://markdown-it.github.io/ ).

When I set the `breaks` options to `true` (only this one) and I test the following text "line1\nline2", there is no break included and the \n is still displayed.

**Comment by puzrin** [comment]
[sample](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22first%20line%5Cnsecond%20line%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Atrue%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Afalse%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

Everything works as needed. I don't understand your problem.

**Comment by cga-F4** [comment]
You're right, I just thought you needed to include the 2 characters "\n" in order to insert an line break (but you just need to use the "enter" key).
Sorry.

**Comment by puzrin** [comment]
To force multiple `\n` you can use [`\` at the end of string](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22first%20line%5Cnsecond%20line%5Cn%5C%5C%5Cn%5C%5C%5Cn%5C%5C%5Cn%5C%5C%5Cntada%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Atrue%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Afalse%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

In any case, i'd recommend to revisit commonmark spec - this package just implements it as is, probability of bugs is very low,
