### ISSUE TITLE
A renderer that renders md: emit markdown

### ISSUE THREAD

**Issue by prasannavl** [markdown-it/markdown-it#217]
Currently, there's only one renderer which emits html. It would great if there's a renderer that also emits markdown again. 

**Use case:** I tokenize the markdown, and do some processing on it. I'd like to emit this back into markdown. 

I assume there's no other way to do this currently, without another custom renderer?

**Comment by puzrin** [comment]
1. That's a markdown reader, not writer
2. This task requires sourcemapping for proper implementation. Such question was asked/answered many times before.

Sorry, that's out of project scope.
