### ISSUE TITLE
Custom `list` rule replaced via `ruler.at('list', ...)` failing

### ISSUE THREAD

**Issue by revin** [markdown-it/markdown-it#218]
Hello,

For my project, I need to modify the way list parsing works for compatibility with some older (non-standard) markdown docs, so I'm taking a look at forking the `list.js` block parsing rule and making my changes from there. To get started, I made a copy of `lib/rules_block/list.js` in my own project, pasted in the `isSpace()` function from `common/utils`, and did

```js
var myList = require('./list'); // the copied file, unchanged except for adding isSpace()
var parser = require('markdown-it')();
parser.block.ruler.at('list', myList);
```

This allows me to run without errors, but the markdown lists all render as

```html
<ul>
<li>- raw
- markdown
- appears
-here</li>
</ul>
```

...as though it isn't doing the nested tokenization like it should. Do you know why this would happen? Am I missing a step somewhere? Thanks!

**Comment by rlidwka** [comment]
It should be:

```js
parser.block.ruler.at('list', myList, { alt: [ 'paragraph', 'reference', 'blockquote' ] });
```

... where "alt" is the last argument [here](https://github.com/markdown-it/markdown-it/blob/0e51825a5cd912121d733938ef2603833378888a/lib/parser_block.js#L20)

Roughly speaking, this argument says "whenever paragraph rule finds valid list inside (e.g. '- markdown' above), it should stop its own execution. So without it paragraph gets as much data as it can without stopping at "-" like it should.

**Comment by revin** [comment]
Oh, perfect! I'd even tried using that array, but I'd done it as the third argument directly and neglected to put it in an object's `.alt` property; this gets me going again. Thanks so much @rlidwka!
