### ISSUE TITLE
Suggestion: Include more languages in highlight.js

### ISSUE THREAD

**Issue by Choonster** [markdown-it/markdown-it#219]
The build of highlight.js used in the current version of this plugin only includes the default languages (minus Device Tree).

I'd like to suggest including more languages, possibly all of them. The two I'd most like to see are Lua and Go.

**Comment by puzrin** [comment]
`highlight.js` is used for demo only, and is not included into build. That's an external package and you can configure it as you wish.

If your question is about demo - let me know.

**Comment by Choonster** [comment]
Sorry, it seems I reported this in the wrong repo.

**Comment by puzrin** [comment]
no problem :)
