### ISSUE TITLE
Buggy behaviour for inline.ruler.before/after

### ISSUE THREAD

**Issue by aleemb** [markdown-it/markdown-it#22]
I am trying to build a bunch of image renders which would look at the image URL and based on that, render an iframe for YouTube, Vimeo, Twitter, etc or just fallback to a default image. Since I want to keep each of these as separate plugins, I am trying to do it with `inline.ruler.before` as:

```
md.inline.ruler.before('emphasis', 'foobar', function() { alert('before emphasis'; }
md.render('![foo](http://foo)'); // shows alert
```

**Comment by puzrin** [comment]
Fixed example in the `next` branch, thanks for clarification.
