### ISSUE TITLE
implementing a task-list plugin

### ISSUE THREAD

**Issue by episodeyang** [markdown-it/markdown-it#221]
Hi @puzrin 

Thanks for this great project. The full list of markdown-it plugins is very impressive!

I am trying to parse and generate GitHub style task-lists. Currently both `markdown-in-checkbox` and `markdown-in-task-lists` plugin only handle the list items, but not the list container. According to GitHub markdown's behavior, I believe GitHub intended the task-list to be a forth type of list besides `ul`, `ol`, and `dl`. 

The problem I am encountering is I'm not sure how to get the parent node (list container) from the child node (list item). Would you mind pointing me to the right direction?

Thanks!

----------

expected behavior:

```
.
- [ ] unchecked
- [_] unchecked
- [x] checked
- [X] checked
.
<ul class="task-list">
<li class="task-list-item"><input type="checkbox">unchecked</li>
<li class="task-list-item"><input type="checkbox">unchecked</li>
<li class="task-list-item"><input type="checkbox" checked="true">checked</li>
<li class="task-list-item"><input type="checkbox" checked="true">checked</li>
</ul>
.
```

note to self: I might want to change the text to label. But will stay faithful to gfm for now.
```
.
- [ ] unchecked
- [_] unchecked
- [x] checked
- [X] checked
.
<ul class="task-list">
<li class="task-list-item"><input type="checkbox" id="checkbox1"><label for="checkbox1">unchecked</label></li>
<li class="task-list-item"><input type="checkbox" id="checkbox2"><label for="checkbox2">unchecked</label></li>
<li class="task-list-item"><input type="checkbox" id="checkbox3" checked="true"><label for="checkbox3">checked</label></li>
<li class="task-list-item"><input type="checkbox" id="checkbox4" checked="true"><label for="checkbox4">checked</label></li>
</ul>
.
```

**Comment by puzrin** [comment]
All list magic happens here https://github.com/markdown-it/markdown-it/blob/master/lib/rules_block/list.js. You could close it and add your rule before list.

I would do the ~ same things, + add new `input_checkbox` , `label_open` + `label_close` tags. Probably with renderer for checkbox (not sure default one understands self-closed tags)

**Comment by episodeyang** [comment]
Thanks @puzrin ! This is really helpful!

also the `markdown-it-check-lists` implementation is correct. I don't know what happened last night, seems two plugins where conflicting with each other (can't reproduce this morning).
