### ISSUE TITLE
list output

### ISSUE THREAD

**Issue by episodeyang** [markdown-it/markdown-it#222]
Hi @puzrin 

I was running the following simple list markdown, and found that the result is different between github and markdown-it.

So it looks like with markdown-it, as long as one list item in a list uses paragraph, the whole list has all of its list items contain paragraph. On github however, it looks like the only one affected is that particular list item itself.

Is this intentional?

```markdown
tentative todo list:
- [ ] connect with github?

    and this is a new paragraph inside the list
    
    and we ca just keep adding 
    
    and this is awesome the math is fantastic.
- [ ] note model.
- [ ] list of notes?
- [ ] note to the server?
- [ ] subscribe to server update?
```

**Comment by puzrin** [comment]
See commonmark spec for tight lists http://spec.commonmark.org/0.25/#example-271

**Comment by episodeyang** [comment]
Thanks just found it:)
