### ISSUE TITLE
[Question] Language support in demo is broken?

### ISSUE THREAD

**Issue by johncja** [markdown-it/markdown-it#225]
For example, if I set the language to `language-js`:

> ![github1](https://cloud.githubusercontent.com/assets/18004961/14223288/ac6a083a-f885-11e5-9b68-732c4a8f000e.PNG)

... and also remove `js` from this part of code:

> ![github5](https://cloud.githubusercontent.com/assets/18004961/14223381/7277811e-f887-11e5-8839-2504c43cadfb.PNG)

... then, the code highlight will be disabled:

> ![github4](https://cloud.githubusercontent.com/assets/18004961/14223366/18105778-f887-11e5-8858-f8541d76109b.PNG)

Is it broken or by design (and I just don't understand something)?

**Comment by puzrin** [comment]
In demo autohightlight is disabled intentionally. You can use "auto" instead https://github.com/markdown-it/markdown-it/blob/6.0.0/support/demo_template/index.js#L89

HIghlighter is attached as external module, and you can do it in any way you wish. https://github.com/markdown-it/markdown-it/blob/6.0.0/lib/renderer.js#L31-L55
