### ISSUE TITLE
How can I find a good static site generator based on markdown-it?

### ISSUE THREAD

**Issue by Klortho** [markdown-it/markdown-it#226]
Sorry to open this as a GH issue, but I've searched around for a while without having much luck. I think partly because, unfortunately, the name "markdown-it" yields too many false positives.

Is there a registry or a category or a list somewhere of static site generators that use this? Or, if you have a recommendation, that would be great. I want something I can get working very fast. 

[FWIW: I started trying to use assemble, but those projects seem to be all a shambles. Then I came across this thread, [remarkable vs. markdown-it](http://talk.commonmark.org/t/remarkable-vs-markdown-it/1956/11) -- lots of drama!]

**Comment by puzrin** [comment]
IMHO it worth to search in npm dependents https://www.npmjs.com/browse/depended/markdown-it.

**Comment by puzrin** [comment]
+

There are several static site generators (in dependents), but i don't know are they good or bad (not familiar with this area). Also, i guess, the most of stati site generators can use `marked` due historic reasons. If you like any of those, you can suggest authors migrate to markdown-it.

**Comment by cliss** [comment]
@Klortho Shameless self-promotion: [Camel](https://github.com/cliss/camel) is a Node.js semi-static blogging engine I wrote that uses `markdown-it`. It is not listed in NPM.

**Comment by Klortho** [comment]
Thanks, both! Camel looks nice, but it looks specialized for blogs -- I need something more general purpose. I also really want a solution that includes a web-based editor included. Since writing this, I found Stackedit, which looks pretty good.

**Comment by puzrin** [comment]
@Klortho i'm not sure StackEdit uses markdown-it. See [Dillinger](https://github.com/joemccann/dillinger) instead.

**Comment by Klortho** [comment]
Damn, you're right. I was looking at so many, I guess the wires in my brain got crossed. Yes, Dillinger is very nice, indeed.

**Comment by egoist** [comment]
https://hexo.io/ also supports markdown-it via plugin
