### ISSUE TITLE
it there a option makes image to be able to click?

### ISSUE THREAD

**Issue by alsotang** [markdown-it/markdown-it#229]
I wanna images within rendered html can wrap in a `a` tag, then it can be click to see the details.

But after search the docs, I dont find any options related to this.

It there a option for it? Or I should hack the rules parser?

**Comment by puzrin** [comment]
https://raw.githubusercontent.com/markdown-it/markdown-it/master/README.md

See first lines of readme, how to format clickable images

**Comment by alsotang** [comment]
I know I can achieve it by markdown format. But my product users always just post a image without a tag.

In github, it would make a image clickable by default, so I think it's common demand.

![image](https://cloud.githubusercontent.com/assets/1147375/14247608/d13b39d6-faa1-11e5-9750-0b7cc7efb1b0.png)

**Comment by puzrin** [comment]
Got it. This task is not specific to markdown markup. You need additional processing to replace images with previews, convert links to videos & quotes, and so on.

We have such things at our site https://dev.rcopen.com/forum/f91/topic444506, but that's done via post-processing after markdown.
