### ISSUE TITLE
Library requires punycode but not in package.json

### ISSUE THREAD

**Issue by ubald** [markdown-it/markdown-it#230]
Please add punycode to package.json

Thanks

**Comment by puzrin** [comment]
This package is not used here.

**Comment by ubald** [comment]
markdown-it/lib/index.js line 14

**Comment by puzrin** [comment]
Ah, really. Sorry for confusion. But this is node's built-in library https://nodejs.org/api/punycode.html, it's not needed in package.json.

Why do you request to add it?

**Comment by ubald** [comment]
I'm using it client-side in a meteor app and it was not finding punycode unless I added it manually.

**Comment by puzrin** [comment]
IMHO that's a problem of your assets manager (report in their tracker). For example `browserify` resolves such dependencies right. Or you can try to use browserified files from `/dist` folder. Adding punicode to dependencies can cause warnings from npm on install.

I think, that's not a bug of this package.

**Comment by ubald** [comment]
I agree with you. I reacted a bit quickly when I saw that punycode was available on npm, I didn't realize it was built-in node.

Thanks again!

**Comment by adrianheine** [comment]
The [bundled `punycode` is deprecated](https://nodejs.org/api/punycode.html) since nodejs 7.0. It would make sense to add a dependency on the standalone library.

**Comment by puzrin** [comment]
@adrianheine thank for info. At first glance, punicode from npm uses es6, while markdown-it uses es5. Need to investigate, how browserify handle this. Anyway, module is not yet removed from node 8.x, and it's possible to postpone any changes.

**Comment by adrianheine** [comment]
The version used by `browserify` is [not ES5](https://github.com/alexgorbatchev/node-browser-builtins) either.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/dist/markdown-it.js#L7480 code is es5 in browserified file (without `const`, `let` etc)

**Comment by adrianheine** [comment]
You're right, `browserify` doesn't use the package I linked to. `punycode` switched to ES6 in `2.0.0`, so if you require `^1`, you're safe in ES5 land.

**Comment by benjycui** [comment]
`punycode` had been deprecated in newer Node.js, so could you add it to dependencies @puzrin ?

**Comment by abirchall** [comment]
It's worth noting that react native libraries that depend on `markdown-it` will encounter this issue. There, neither `nodejs` nor `browserify` are a dependency. See https://github.com/iamacup/react-native-markdown-display/issues/97

**Comment by kethan1** [comment]
It seems like `yarn install punycode`, or `npm install punycode`, or `expo install punycode`(recommended for expo) should work

**Comment by compulim** [comment]
Dependencies should be properly defined in `package.json` without assuming anyone got the polyfill correctly. 😞

**Comment by tomwanzek** [comment]
Agree with the above statement, we are using this library in a React Native context. The build started failing, as soon as we upgraded a completely unrelated 3rd party library. That library used to have a dependency on `punycode`, but no longer does. So `punycode` was wiped from our `yarn.lock`.

Et voila, `markdown-it` started creating build errors, as it does not declare what clearly is a dependency for the package.
With such a wonderful package, why not simply keep its dependencies explicit? 🙇

**Comment by anomiex** [comment]
> It seems like after punycode is installed with: `yarn install punycode`, or `npm install punycode`, or `expo install punycode`(recommended for expo) it should work

That won't work in all cases. When using workspaces along with yarn's PnP or pnpm with hoisting disabled, for example, it doesn't work very well.

**Comment by jerone** [comment]
I think commit [737c95a](https://github.com/markdown-it/markdown-it/commit/737c95a12976357df99652e4b51d831cac4a75aa) fixes the punycode issue in version [14.0.0](https://github.com/markdown-it/markdown-it/releases/tag/14.0.0).
