### ISSUE TITLE
Support for tables without headers

### ISSUE THREAD

**Issue by patricktokeeffe** [markdown-it/markdown-it#231]
I've been using this style to omit header rows on tables: 

```
|
|----------|-----------|
| cell 1   | cell 2    |
| another  | a fourth  |
```

It works in Bitbucket's render, but is not widely supported (at least not Github, Dillenger.io, Stackedit.io). That's a real shame because a header row *should* be optional for tables.

From what I gather, this project tracks the CommonMark spec so I've also posted a comment on [their discussion page](http://talk.commonmark.org/t/tables-in-pure-markdown/81).

**Comment by puzrin** [comment]
Thanks for posting on CM forum. I close issue here, because we stay aside from spec - that's intentional. Of cause you can write your own plugin to replace default tables, if you disagree with spec or don't wish to wait.

**Comment by patricktokeeffe** [comment]
OK thanks. Hopefully people find this issue and click-through to the discussion page to voice their support.
