### ISSUE TITLE
[enhancement] (browser) JS markdown-it + plugins embedding

### ISSUE THREAD

**Issue by Netsaver** [markdown-it/markdown-it#232]
Hi, not wanting to rely on nodeJS installation, I tried to use a local JS as suggested:
// browser without AMD, added to "window" on script load
// Note, there is no dash in "markdownit".
var md = window.markdownit();
var result = md.render('# markdown-it rulezz!');

It was fine, anyway this way I couldn't link together all plugins.
Can you please make available a set of linked JS library to use in browser installation?
Or Have I to do it via NodeJS - browserify?
Thanks a lot
Netsaver, Rome - IT

**Comment by puzrin** [comment]
Combining multiple JS together should be done by assets manager (external program). Therte are some grunt taska for that. And of cause, you can do it yourself with `browserify`.
