### ISSUE TITLE
Rendering bug?

### ISSUE THREAD

**Issue by eoftedal** [markdown-it/markdown-it#237]
Input

    render("![text\"'\](http://hello)")

Expected output:

    <p><img src="http://hello" alt="text&quot;'`"></p>\n

Actual output output:

    <p><img src="http://hello" alt="text&amp;quot;\'`"></p>\n

As you can see the `"` is double encoded and the `'` is prepended with a slash

**Comment by cbreeden** [comment]
Markdown-it is escaping alt tags in images twice.  Here is a minimal example:

```
![&](#)
```
is rendered as:
```
<p><img src="#" alt="&amp;amp;"></p>
```

The problem stems from [here](https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.js#L250).  Markdown-it is trying adhere to commonmark's recommendation that the alt tag is stripped of all other markdown as described [here](http://spec.commonmark.org/0.25/#example-538).

What happens is the `alt` tag is processed through `rules.text`which calls `escapeHtml`, and then again while rendering the attribute, `renderAttrs`.  A possible alternative is to perhaps give render.text and option `escape` parameter.  But considering that `rules.text` does nothing other than call `escapeHtml`, and that no other entity uses `rendinerInlineAsText` we may be able to simply replace [this line](https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.js#L266):

```javascript
    result += rules.text(tokens, i, options, env, this);
```

with:

```javascript
    result += tokens[i].content;
```

I can try it out later tonight and run it through some tests and convert it to a pull-request.

**Comment by puzrin** [comment]
You escaped closing scope: `\].

[Works as needed](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22!%5Btext%5C%5C%5C%22%27%5C%5C%5D%28http%3A%2F%2Fhello%29%5Cn%5Cn!%5Btext%5C%5C%5C%22%27%5D%28http%3A%2F%2Fhello%29%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D).
