### ISSUE TITLE
Pre wrapped in div has extra paragraph inserted

### ISSUE THREAD

**Issue by runemadsen** [markdown-it/markdown-it#238]
Take a look at [this example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%23%20This%20example%20works%5Cn%5Cn%3Cpre%3E%5Cnbackground%28255%29%5Cn%5Cn%3C%2Fpre%3E%5Cn%5Cn%23%20This%20example%20has%20an%20extra%20paragraph%5Cn%20%20%5Cn%3Cdiv%3E%3Cpre%3E%3Ccode%3E%5Cnbackground%28255%29%3B%5Cn%5Cn%3C%2Fcode%3E%3C%2Fpre%3E%3C%2Fdiv%3E%20%20%20%20%5Cn%5Cn%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Afalse%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D)

Is this expected behavior? It seems that when a `<pre>` is not a direct child of root, markdown-it doesn't treat the code inside of it as pre text. Instead, it gets an empty paragraph.

**Comment by puzrin** [comment]
[commonmark dingus](http://spec.commonmark.org/dingus/?text=%23%20This%20example%20works%0A%0A%3Cpre%3E%0Abackground%28255%29%0A%0A%3C%2Fpre%3E%0A%0A%23%20This%20example%20has%20an%20extra%20paragraph%0A%20%20%0A%3Cdiv%3E%3Cpre%3E%3Ccode%3E%0Abackground%28255%29%3B%0A%0A%3C%2Fcode%3E%3C%2Fpre%3E%3C%2Fdiv%3E) At least, reference implemantation has the same problem. May be worth to ask here https://github.com/jgm/CommonMark/issues.

But keep in mind, that commonmark is not very friendly about empty lines in html blocks. See [spec](http://spec.commonmark.org/0.25/#html-blocks). Even if you fix somehow this example, you will not fix all such problems.

**Comment by runemadsen** [comment]
Good point. I fixed my example by moving my `<pre>` on a separate line, and that worked. I was just surprised because Commonmark describe the `<pre>` as *special* which made me think that it's actually parsing the HTML to figure out where to allow empty lines. But I guess it's only if the pre is first on a line.

**Comment by puzrin** [comment]
Yeah, [div on separate lines is ok](https://markdown-it.github.io/#md3={%22source%22%3A%22%23%20This%20example%20has%20an%20extra%20paragraph\n%20%20\n%3Cdiv%3E\n\n%3Cpre%3E%3Ccode%3E\nbackground%28255%29%3B\n\n%3C%2Fcode%3E%3C%2Fpre%3E\n\n%3C%2Fdiv%3E\n%22%2C%22defaults%22%3A{%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Afalse%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22}})

Anyway, i'd suggest to close issue here as spec-related. You can rise this question in spec repo (if needed), and if spec will be updated, `markdown-it` will follow very soon.

Also, i'd suggest to override fenced block renderer, to have custom look for special names. That will eliminate the need to use html at all. Of cause, i don't know your goals and can not guarantee it will be good for you. But if you describe your needs, i'll try to help.

**Comment by runemadsen** [comment]
Thx!
