### ISSUE TITLE
Allow omitting a space in headers (GFM-style)

### ISSUE THREAD

**Issue by Leonya** [markdown-it/markdown-it#240]
GitHub-flavored Markdown allows the following markup for headers:

```
#header
```

While markdown-it only allows

```
# header
```

I understand that CommonMark requires a space between the `#` and the text, but I would still like to allow both syntaxes in my app. Please guide me in this regard.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/rules_block/heading.js copy this rule, change it as you need and replace original one after instance init https://markdown-it.github.io/markdown-it/#Ruler.at

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/parser_block.js#L22

```js
var md = require('markdown-it')();
md.block.ruler.at('heading', your_handler, { alt: [ 'paragraph', 'reference', 'blockquote' ] });
```

**Comment by Leonya** [comment]
Thanks, figured it out!

**Comment by coryschires** [comment]
For future readers... You can also achieve this behavior (a little more cleanly IMO) by installing this plugin: https://www.npmjs.com/package/markdown-it-lazy-headers.
