### ISSUE TITLE
Escape Templating Tags

### ISSUE THREAD

**Issue by tawe141** [markdown-it/markdown-it#241]
I'd like to be able to do something like this:

```
{% extend "base.html" %}

# This is a Title
```

and not format the `extend` tag so that the result is like this:

```
{% extend "base.html" %}

<h1>This is a Title</h1>
```

Is this possible? I understand there are ways to create custom rules, but I'm not sure how to use those either.

**Comment by puzrin** [comment]
http://spec.commonmark.org/0.25/#processing-instruction. CommonMark supports only `<? ..... ?>` skip (when html enabled).

Other markup should be added via plugins. Good place to start is to read [dev docs](https://github.com/markdown-it/markdown-it/tree/master/docs).
