### ISSUE TITLE
Autorender on web page?

### ISSUE THREAD

**Issue by erhnsn** [markdown-it/markdown-it#242]
It occurred to me that it is not that easy to use on a web page. The naive way would be to call this when the document loads. Is there a function to render all text-nodes in the document?

``` js
document.body.innerHTML = window.markdownit(opts).render(document.body.innerHTML);
```

**Comment by puzrin** [comment]
No, this library works with strings and not related to DOM anyhow. It's in your responsibility to scan text nodes and provide correct input.

**Comment by ixti** [comment]
https://jsfiddle.net/ye68cgjo/3/
