### ISSUE TITLE
Async operations

### ISSUE THREAD

**Issue by heruan** [markdown-it/markdown-it#248]
I'd like to build a plugin to let a user able to reference an external resource and having the current status of that resource rendered, e.g.
```markdown
See this ticket #456.
```
being rendered as:
```html
See this ticket <a href="/tickets/456">456</a><span class="status-working">WORKING</span>.
```
where the `span` depends on an async call to an API.

Would it be possible with the current renderer?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/docs/development.md#i-need-async-rule-how-to-do-it
