### ISSUE TITLE
markdown-it.github.io throws TypeError due to hljs

### ISSUE THREAD

**Issue by arve0** [markdown-it/markdown-it#250]
![skjermbilde 2016-05-30 kl 17 22 59](https://cloud.githubusercontent.com/assets/4810521/15653129/4c81f21e-268b-11e6-98fd-be0a95bd1f84.png)

**Comment by puzrin** [comment]
Fixed by https://github.com/markdown-it/markdown-it/commit/564bfa8e7d7c5bc89fb807753f1b57a9fae4e67d, thank for report!
