### ISSUE TITLE
Multiline tables

### ISSUE THREAD

**Issue by GrahamHannington** [markdown-it/markdown-it#253]
I am writing Markdown in files (IBM z/OS MVS data sets) with fixed 80-byte record (line) length. Typically, following platform-specific conventions (I can be more specific, if asked), I try to keep lines even shorter, to a maximum of 72 characters.

Given these constraints, Pandoc-style [multiline tables](http://pandoc.org/README.html#tables) that "allow headers and table rows to span multiple lines of text" would be very useful. (Grid tables, too, but multiline tables are a better fit for my immediate use cases.)

I know: I'm welcome to develop a plugin to do this, right? However, that would involve a steep learning curve for me. While I'm pondering that, I thought I'd create this issue. I'm sure you (markdown-it developers) would do a better job, quicker.

Related reference: [my post](https://talk.commonmark.org/t/tables-in-pure-markdown/81/99?u=grahamhannington) to the CommonMark discussion forum topic "Tables in pure Markdown" (I notice you guys have been there, too).

**Comment by puzrin** [comment]
Sorry, we will change tables only after those will appear in CM spec. Current ones are minimal implementation of "something like github". Everything not in spec and not on github should stay in external plugins for now.

**Comment by GrahamHannington** [comment]
Thanks for the quick response. I understand your position, and I agree: such functionality belongs in external plugins for now.

Thank you for markdown-it. I love your work.
