### ISSUE TITLE
Linkify doesn't work on valid link

### ISSUE THREAD

**Issue by garrynewman** [markdown-it/markdown-it#254]
This link only turns into a link up until the first period.

http://ecx.images-amazon.com/images/I/810ZEQfvXAL._SL1449_.jpg

**Comment by puzrin** [comment]
Use `<...>` to mark such links explicit. See https://github.com/markdown-it/markdown-it/issues/38

**Comment by garrynewman** [comment]
Sorry, I wasn't looking for a workaround, I was reporting a bug

**Comment by puzrin** [comment]
That's not a big, but known collision. If you disable emphasis rule, link will be detected properly.
