### ISSUE TITLE
Option to use blocks only when needed

### ISSUE THREAD

**Issue by davidgilbertson** [markdown-it/markdown-it#255]
I am writing a type of CMS where a text record could be a few words (e.g. the text for a button) or a whole page. So I don't want everything wrapped in a `<p>` but if a user writes a list I need it to produce the `<ul>` (which `renderInline` doesn't).

Is there an option to do this? I don't see a plugin [here](https://www.npmjs.com/browse/keyword/markdown-it-plugin). Right now I'm doing a check like so, it feels like there must be a better way.

```js
let html = md.render(myMarkdownString);

const testDom = document.createElement('div');
testDom.innerHTML = html;

if (testDom.childElementCount === 1 && testDom.children[0].nodeName.toLowerCase() === 'p') {
  html = testDom.children[0].innerHTML;
}
```

**Comment by puzrin** [comment]
You can use https://markdown-it.github.io/markdown-it/#MarkdownIt.parse and check if list token exist. If not - then call renderInline.

**Comment by davidgilbertson** [comment]
Thanks for the quick reply! 

It's not so much that I'm looking for a list. I also want blocks if the user entered, say, three paragraphs. Only if the user enters an inline string of text do I want to _not_ have a block level element as a wrapper (it would be incorrect for me to assume they want a 'paragraph').

I'll have a look at the parse method, if it returns a hierarchical list then I can just check that for a single top-level p. But I'm doing a live preview so I guess that means I be parsing everything twice per keystroke.

**Comment by puzrin** [comment]
Detecting of content is a post-parse task anyway. That does not depend on method you prefer. And that's not related to parser itself.
