### ISSUE TITLE
Example for Async plugin?

### ISSUE THREAD

**Issue by alinex** [markdown-it/markdown-it#256]
I want to make a new plugin but need to call async code. I already red https://github.com/markdown-it/markdown-it/blob/master/docs/development.md but would like to have an easy example.

What I want to make is a block plugin which wil parse:

    $$$ mermaid
    < some code like described on https://github.com/knsv/mermaid >
    $$$

The content should be send through the mermaid processing asynchroneous and be replaced by the resulting html (inline svg image).

As example for the plugin I looked into the code syntax highliting base plugin.

Can anybody show how to call a simple method like the following (maybe from the renderer):

``` javascript
getHtml = function (code, callback) {
  // make some process calls
  callback(null, '<svg>...</svg>');
}
```

I plan to add more visualizations beside mermaid like table2chart conversion...

**Comment by puzrin** [comment]
You should manually call parser/render and insert async call between. Something like this:

```js
const md = require('markdown-it')();

let env = {}
let tokens = md.parse(input, env);

your_async_fn(tokens, env, err => {
  // here you will have modified tokens (and may be env) as you need
  output = md.renderer.render(tokens, md.options, env);
});
```

**Comment by alinex** [comment]
Thanks I wiill try to do this that way the next days. Only downside thing is that such plugins are not easily addable through only an use call.

**Comment by manastalukdar** [comment]
@alinex , were you able to make this work? I am trying to accomplish the same thing using mermaid.

**Comment by s-light** [comment]
@puzrin for me it had helped if there was a short example in the FAQ.

what about just putting something like this in there?
```js
import MarkdownIt from "markdown-it";
const mdOptions= {};
const md = new MarkdownIt(mdOptions);

let env = {}
let tokens = md.parse(input, env);
const env = {
    filePath: "get current file path somehow",
};

let tokens = md.parse(your_source_md, env);

export const runYourAsyncFunction = async (tokens, options, env, self) => {
    for (let idx = 0; idx < tokens.length; idx++) {
        const token = tokens[idx];
        if (token.type == "fence") {
            await doYourWorkOnTheFenceBlock(tokens, idx, options, env, self);
        }
    }
};

// this does only side effects on the tokens array:
await runYourAsyncFunction(tokens, {}, env, md.value);

const contentHTML = md.renderer.render(tokens, md.value.options, env);

```
