### ISSUE TITLE
Is there a way to specify the starting heading level?

### ISSUE THREAD

**Issue by kruncher** [markdown-it/markdown-it#257]
For instance, given the following markdown:
```markdown
# First Heading
## Second Heading
### Third Heading
```
Some sort of markdown-it option `rootHeadingLevel: 3`; such that the output HTML is along the lines of:
```html
<h3>First Heading</h3>
<h4>Second Heading</h4>
<h5>Third Heading</h5>
```
Many thanks!

**Comment by puzrin** [comment]
Override default renderers for `heading_open` & `heading_close` tokens.

**Comment by kruncher** [comment]
Thanks for the fast response!
