### ISSUE TITLE
Allow for 'scoped' rendering

### ISSUE THREAD

**Issue by cbreeden** [markdown-it/markdown-it#258]
This is essentially a feature request, but I feel that it is a far-fetched feature request.  I would like to have an API that would instruct markdown-it to cache the parsing of the previous input.  Then upon a request to render the input with additional modifications, it would be nice that if we told markdown-it where modifications took place it could render only what is necessary in a smart way as opposed to re-rendering the entire document.

Here is an example of something that I have been playing with:

``` javascript
_mdCache = [];
function renderMdChange(src, line) {
    if (_mdCache === [] || !line) {
        _mdCache = md.parse(src, {});
        return md.renderer.render(_mdCache, md.options, {});
    }
    
    const length = _mdCache.length;
    for (let n = 0; n < length; n++) {
        const token = _mdCache[n];
        if (token.map && token.map[0] > line) { break; }    
        if (token.type === "paragraph_open" &&
            token.map && token.map[0] <= line && token.map[1] > line) {
                const newSrc = getLines(src, token.map[0], token.map[1]);
                console.log("Re-parsing: " + _mdCache[n+1].content);
                _mdCache = Array.prototype.concat(
                    _mdCache.slice(0,n),
                    md.parse(newSrc, {}),
                    _mdCache.slice(n+3));
                return md.renderer.render(_mdCache, md.options, {});
        }
    }

    _mdCache = md.parse(src, {});
    return md.renderer.render(_mdCache, md.options, {});    
}
```

What happens here is that I tell markdown-it that there has been a 'small' addition on line number `line`.  Then I scan through the token list seeing if that line change occurs inside a paragraph block.  If that change occurs in a paragraph block, I will just re-render the scope of that paragraph block and place it in our tokenlist cache.  I then send it to the renderer to be processed.

I took the example markdown from <https://markdown-it.github.io/> and added a new paragraph to the end.  When I used this technique and added to the paragraph at the end the rendering time reduced from an average of 6 ms to 1 ms.  I believe that there is more room for improvement as well if you consider using a virtual DOM for an out-put as well, where this will allow rendering to be in place too.

I know there are several issues to consider if attempting to implement something like this:

- Some changes will break blocks, this may not work well with this model
- How to determine large changes like deleting or adding lots of new lines from pasting
- Recalculating 'source maps'
- Rendering can not modify token list (see #259)

I think we could very likely dramatically increase the speed to rendering small changes in markdown as long as we know where these changes occur.  Perhaps this could be an avenue worth considering?

**Comment by puzrin** [comment]
I'd like to categorize this issue somehow, because as feature request it's a bit specific and can not be implemented in core.

Right now you can track top-level blocks only, and replace changed ones. That will be correct. It's not necessary to keep changes as minimal as possible, if minimal unit is "1 top level block" - that will be good enougth for the speed. Demo uses the same principle for sync scroll. Recalculating source maps is not a problem too, if you need top level blocks only.

> How to determine large changes like deleting or adding lots of new lines from pasting

- I would scan from the head and from the tail, until lines are equal, and would consider the rest as single modified range. Or would use some `diff` library.
- Then i would scan top level blocks to mark changed everything in range found.

**Comment by cbreeden** [comment]
Good ideas.  VSCode gives you a good deal of information, on edit you get the range of code of the original text that is modified and the replacement text for that range.  So you essentially have something like this:

__Additions__: Starting with "123456789", by pasting in abc after 5 you get: Range from 5 to 5 is modified (an empty range at cursor point 5) with replacement text "abc".
__Deletion__: Starting with "123456789", by deleting 56 you get: Range from 5 to 6 is modified with replacement text "".
__Replaement__: Starting with "123456789", by selecting 56 and pasting abc you get: Range from 5 to 6 is modified with replacement text abc.

I only had the intention of using top level blocks.  It's funny that you mention it:

> I would scan from the head and from the tail, until lines are equal, and would consider the rest as single modified range. 

This is exactly what I did when I tried my second attempt.  Of course it broke the footnotes extension though.  But I think this is certainly doable, I'll play around with it some more later this week and let you know how it goes.

**Comment by cbreeden** [comment]
Good ideas, vscode gives us this on modifications: the r

**Comment by puzrin** [comment]
> This is exactly what I did when I tried my second attempt. Of course it broke the footnotes extension though. But I think this is certainly doable, I'll play around with it some more later this week and let you know how it goes.

Yeah, footnotes & abbreviation will break linear flow between input and output. I think, stupid condition "disable fast render if footnote/abbr exists" should help :). Because those features are rarely used in real world. Of cause, that can be done better, but i think, that "cache 99% use-cases right now" is a good result to start with.

**Comment by puzrin** [comment]
Let's close it? Seems no reasons to keep it open. But i will continue answer your questions if you have any.

**Comment by cbreeden** [comment]
I agree.  I do plan to continue with implementing this, and maybe later on if you consider a new AST (#125) I can show you what I did and perhaps these modifications could be considered defining a new AST.  Not with the intention of being implemented in core, of course.

**Comment by puzrin** [comment]
FYI, AST is a good thing, but we had a reason to postpone it:

- CM spec is not stabilized AST format (they try, but result is very intermadiate). And it's expensive to make big changes on every spec update.
- That needs a big rewrite anyway. I still need to finish Nodeca. Humor is, that markdown-it is already used in Diaspora, NodeBB and so on. And I still did not deployed it for my own :)
- AST still does not add principal difference. It worth to combine big rewrite with sourcemap support. And that's really non-trivial task.

---

Also found one more edge case for you. Opening \`\`\` (fenced block) without close can propagate down to the end of document. That should invalidate cached tail.

Probably it worth to check if user did not added \`\`\` at line start. Then block edges can be detected by empty line above and below (if you don't find \`\`\` during scan up and down)
