### ISSUE TITLE
Parse table error

### ISSUE THREAD

**Issue by afc163** [markdown-it/markdown-it#26]
Expected: https://github.com/IonDen/ion.rangeSlider/blob/master/readme.md#settings
Actually: http://spmjs.io/package/ion-rangeslider

![](https://t.alipayobjects.com/images/T1rh4eXipfXXXXXXXX.png)

Happened in markdown 2.x & 3.x

**Comment by puzrin** [comment]
Could you use permalink from [demo](https://markdown-it.github.io/) to show exacty input and output, and put correct output to gist ?

**Comment by puzrin** [comment]
Also, please, reduce example to minimal possible.

**Comment by afc163** [comment]
Ok, I will do it later.

**Comment by afc163** [comment]
Good: https://markdown-it.github.io/#md64=eyJzb3VyY2UiOiI8dGFibGU+XG5cbiAgPHRyPlxuICAgIDx0ZD4xMjM8L3RkPlxuICAgIDx0ZD4xMjM8L3RkPlxuICA8L3RyPlxuPC90YWJsZT4iLCJkZWZhdWx0cyI6eyJodG1sIjp0cnVlLCJ4aHRtbE91dCI6ZmFsc2UsImJyZWFrcyI6ZmFsc2UsImxhbmdQcmVmaXgiOiJsYW5ndWFnZS0iLCJsaW5raWZ5Ijp0cnVlLCJ0eXBvZ3JhcGhlciI6dHJ1ZSwiX2hpZ2hsaWdodCI6dHJ1ZSwiX3N0cmljdCI6ZmFsc2UsIl92aWV3IjoiaHRtbCJ9fQ==

Bad: https://markdown-it.github.io/#md64=eyJzb3VyY2UiOiI8dGFibGU+XG5cbiAgICA8dHI+XG4gICAgPHRkPjEyMzwvdGQ+XG4gICAgPHRkPjEyMzwvdGQ+XG4gIDwvdHI+XG48L3RhYmxlPiIsImRlZmF1bHRzIjp7Imh0bWwiOnRydWUsInhodG1sT3V0IjpmYWxzZSwiYnJlYWtzIjpmYWxzZSwibGFuZ1ByZWZpeCI6Imxhbmd1YWdlLSIsImxpbmtpZnkiOnRydWUsInR5cG9ncmFwaGVyIjp0cnVlLCJfaGlnaGxpZ2h0Ijp0cnVlLCJfc3RyaWN0IjpmYWxzZSwiX3ZpZXciOiJodG1sIn19

**Comment by puzrin** [comment]
See http://spec.commonmark.org/0.15/#html-blocks

and http://spec.commonmark.org/dingus.html?text=%3Ctable%3E%0A%0A%20%20%20%20%3Ctr%3E%0A%20%20%20%20%3Ctd%3E123%3C%2Ftd%3E%0A%20%20%20%20%3Ctd%3E123%3C%2Ftd%3E%0A%20%20%3C%2Ftr%3E%0A%3C%2Ftable%3E

We follow commonmark spec, and result is exactly as required by spec.

**Comment by puzrin** [comment]
I see 2 possible solutions:

1. Write your own rule to replace existing html_block
2. Just fix your markup to be CommonMark-compatible

I understand, that result can be not as you expect, but this it NOT a bug.

**Comment by afc163** [comment]
Understood. 

Github do too much in Makedown's compatibility, that is sad.

**Comment by puzrin** [comment]
Closing? Or need advices how to rewrite [html_block](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_block/html_block.js) rule ?

**Comment by afc163** [comment]
That would be another issue. Close first

**Comment by puzrin** [comment]
FYI http://talk.commonmark.org/t/raw-html-blocks-proposals-comments-wanted/983?u=vitaly HTML blocks are now discussed. Not sure about this case, but general improvments are expected soon.
