### ISSUE TITLE
A Reactive Renderer

### ISSUE THREAD

**Issue by episodeyang** [markdown-it/markdown-it#262]
Hi Vitaly, 

I am working with React and would love to build a renderer for markdown-it that renders the AST into a react component tree.

Where shall I start if I want to do this? 

Thanks,
Ge

**Comment by puzrin** [comment]
No ideas, i'm still not familiar with react. Docs aboout markdown-it are here https://github.com/markdown-it/markdown-it/tree/master/docs. Also plugins can be searched via npm.

**Comment by episodeyang** [comment]
Thanks Vitaly.

I'm thinking about using the markdown-it parse function instead of the
render function. That way I am effectively making a customer renderer.

Best,
Ge
