### ISSUE TITLE
Disable everything, except inline + autolink

### ISSUE THREAD

**Issue by ile** [markdown-it/markdown-it#263]
Hi,

I try to first disable everything and then enable just paragraphs and autolinking (if possible):

```
> md = require('markdown-it')('zero', { linkify: true }).enable([ 'inline' ])
> md.render('123456 http://qwerty.com 567890\n\n1234567')
'<p>123456 http://qwerty.com 567890</p>\n<p>1234567</p>\n'

 ```
As you can see, the `http://qwerty.com` doesn't get turned into a link. Paragraphs seem work though.

**Comment by puzrin** [comment]
Zero preset switch off almost everything - when linkifier rule is disabled, options flag does not change anything.

- actual rule https://github.com/markdown-it/markdown-it/blob/7.0.0/lib/parser_core.js#L17
- what is left in zero preset https://github.com/markdown-it/markdown-it/blob/7.0.0/lib/presets/zero.js#L40-L42

Add `.enable('linkify')` to be happy :)

That can be a bit confusing, but i don't like to enable linkifier in zero preset by default.

**Comment by ile** [comment]
Thanks, that makes sense. But I don't seem to be able to get it turn into a link yet:

```
> md = require('markdown-it')('zero').enable(['inline', 'linkify'])
> md.render('123456 http://qwerty.com 567890\n\n1234567 **hello**')
'<p>123456 http://qwerty.com 567890</p>\n<p>1234567 **hello**</p>\n'
```

Maybe I'm still doing something wrong?

**Comment by puzrin** [comment]
Seems you missed option `{ linkify: true }`, it's still needed.

**Comment by puzrin** [comment]
Also, `inline` is already enabled in zero preset https://github.com/markdown-it/markdown-it/blob/7.0.0/lib/presets/zero.js#L42, there are no need to enable it again.
