### ISSUE TITLE
Feature request: adding link attributes

### ISSUE THREAD

**Issue by ile** [markdown-it/markdown-it#264]
How about customizing the links a bit, like:

https://github.com/markdown-it/markdown-it/blob/master/lib/rules_core/linkify.js#L102

->

```
 token.attrs = [ [ 'href', fullUrl ], [ 'target', '_blank' ] ];
```

How to do this? You could do this in the configuration object:

```
require('markdown-it')({ links: { target: "_blank" } })
```

Or if you want only configure linkify links:

```
require('markdown-it')({ linkify: { target: "_blank" } })
```

If there is a way to do this in a plugin, that would be welcome as well, but is there? I couldn't figure out a way.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it-for-inline

Place it in core chain (after linkifier or later), go via `link_open` tokens and push additional attrs.

**Comment by puzrin** [comment]
Ah, it already push itself to proper place https://github.com/markdown-it/markdown-it-for-inline/blob/master/index.js#L26

Just see example in readme for the links.

**Comment by ile** [comment]
Great! Thanks!
