### ISSUE TITLE
Consider converting tabs to spaces in code blocks

### ISSUE THREAD

**Issue by ediweissmann** [markdown-it/markdown-it#265]
Consider converting tabs to spaces in code blocks.
Reason being tab size cannot be properly controlled and configured via the browser.  

There is [some CSS support](http://caniuse.com/#feat=css3-tabsize) but not all browsers support it (eg: IE)  so changing the default tab size from 8 to something else in a browser is currently not ideal.

**Comment by puzrin** [comment]
You can do it yourself by overriding code tags renderer as you need. I don't see reason to include this to core. May be i don't understand something, then more descriptive examples needed.

**Comment by ediweissmann** [comment]
I agree, one could attempt to handle this with a plugin. 

Since tabs in code blocks cannot really be configured across all major browsers, I think one could always prefer to do the tabs to spaces conversion as part of the markdown conversion to HTML, and have the output without tabs in code blocks when it reaches a browser.

A plugin that's always good to have enabled might be considered a good candidate for a core feature? Of course OK to say pass and interested parties can always try to go the plugin way.

FWIW, it seems to me that's also how the GitHub readme markdown renderer behaves.
