### ISSUE TITLE
support Markdown Extra syntax 

### ISSUE THREAD

**Issue by MovGP0** [markdown-it/markdown-it#266]
[Markdown Extra](https://michelf.ca/projects/php-markdown/extra/) provides some very useful extensions to markdown, especially with tables: 

```
| Left align | Right align | Center align |
|:-----------|------------:|:------------:|
| This       |        This |     This     
| column     |      column |    column    
| will       |        will |     will     
| be         |          be |      be      
| left       |       right |    center    
| aligned    |     aligned |   aligned
```

**Comment by svbergerem** [comment]
markdown-it already supports tables: [demo](https://markdown-it.github.io/#md3={%22source%22%3A%22|%20Left%20align%20|%20Right%20align%20|%20Center%20align%20|\n|%3A-----------|------------%3A|%3A------------%3A|\n|%20This%20%20%20%20%20%20%20|%20%20%20%20%20%20%20%20This%20|%20%20%20%20%20This%20%20%20%20%20\n|%20column%20%20%20%20%20|%20%20%20%20%20%20column%20|%20%20%20%20column%20%20%20%20\n|%20will%20%20%20%20%20%20%20|%20%20%20%20%20%20%20%20will%20|%20%20%20%20%20will%20%20%20%20%20\n|%20be%20%20%20%20%20%20%20%20%20|%20%20%20%20%20%20%20%20%20%20be%20|%20%20%20%20%20%20be%20%20%20%20%20%20\n|%20left%20%20%20%20%20%20%20|%20%20%20%20%20%20%20right%20|%20%20%20%20center%20%20%20%20\n|%20aligned%20%20%20%20|%20%20%20%20%20aligned%20|%20%20%20aligned%22%2C%22defaults%22%3A{%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22}})
