### ISSUE TITLE
is this a bug? the rendered `&emsp;` character gets trimmed 

### ISSUE THREAD

**Issue by akhoury** [markdown-it/markdown-it#268]
I dont think this is a bug, but just wanted to make sure. I find it weird they these chars get trimmed from the ends of a line but in the middle of it.

1) visit https://markdown-it.github.io/
2) paste the following on the left side

```markdown
----

    4 Regular-spaces, cause a code in Md

----

&emsp;&emsp;&emsp;&emsp;Entity(`emsp`)-space gets rendered correctly as a space character in Md

----

    Entity(`emsp`-rendered-character)-however if you use that same rendered character at the beginning of a line or at the end, it gets trimmed out, but not in the middle of t h e line.

----
```

3) you should see this
![screen shot 2016-07-22 at 12 30 43 am](https://cloud.githubusercontent.com/assets/1398375/17046647/9a047ba6-4fa3-11e6-8226-817c66d63cea.png)

(it is also the case with `&nbsp;` as well

**Comment by puzrin** [comment]
Dupe
