### ISSUE TITLE
Syntax highlighting and remove <pre> tag

### ISSUE THREAD

**Issue by egoist** [markdown-it/markdown-it#269]
I need to use https://github.com/knsv/mermaid and markdown-it together

eg:

    ```mermaid
    code
    ```
into:

```html
'<div class="mermaid">'+code+'</div>'
```

and it should not have `<pre><code>` wrapped around.

The current solution won't work https://github.com/markdown-it/markdown-it#syntax-highlighting

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.js#L41 You should override default fenced block renderer to format your specific type differently.

https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer

**Comment by GARENFEATHER** [comment]
@egoist did you get it?

**Comment by sustained** [comment]
Can you elaborate? I don't really get it. Can't we have some option to override it adding the `<pre>` stuff? Seems like a fairly common use-case. In my case, I want it to render a custom Vue component and inside the Vue component it has pre/code etc. stuff.

Seems kind of hackish for us to have to dive into the lib and override rendering code just to say "don't wrap"?

**Comment by sustained** [comment]
The way that it is now it means I have to copy-paste the `fence` function into my code and I also need to include some of your utils (`unescapeAll`, `escapeHtml`) and whenever you update any of that code I also need to sync all of those changes to my version... all of this just to say "don't wrap `pre`.

That is not a good situation at all.

**Comment by puzrin** [comment]
NO.

**Comment by sustained** [comment]
I see?

**Comment by sustained** [comment]
This is what I went with anyway, since it's the only solution as things stand:

```
import { unescapeAll, escapeHtml } from "markdown-it/lib/common/utils";

mdInstance.renderer.rules.fence = function(tokens, idx, options, env, slf) {
  const token = tokens[idx];
  const info = token.info ? unescapeAll(token.info).trim() : "";
  let langName = "";
  let highlighted;

  if (info) {
    langName = info.split(/\s+/g)[0];
  }

  if (options.highlight) {
    highlighted =
      options.highlight(token.content, langName) || escapeHtml(token.content);
  } else {
    highlighted = escapeHtml(token.content);
  }

  return highlighted + "\n";
};
```

Seems to work for my needs. In case anyone else is wondering how to do it.

**Comment by olets** [comment]
@puzrin are you open to reconsidering? Currently, markdown-it syntax highlighting plugin authors who support rendering HTML where the outermost element isn't a &lt;pre> have to tell their users to copy, paste, modify, and then maintain a customized version of the default fence rule. That's a lot to ask of a plugin user.

Here's a refactor idea which

- IMO preserves the certainty of the out-of-the-box behavior (see https://github.com/markdown-it/markdown-it/pull/927#issuecomment-1817525222);

- provides an simple way to opt out of code wrapping (`markdownit({ wrapHighlighted: false })`) (https://github.com/markdown-it/markdown-it/issues/269#issuecomment-235486115, https://github.com/markdown-it/markdown-it/pull/927, https://github.com/shikijs/shiki/issues/792)

- makes it easy for users to provide their own wrapper for highlighted code (this issue's original request) without touching the highlighter

The emoji reactions quite a few people have wanted this over the years. Lmk if I can work on a PR

&nbsp;

-
	```js
	// lib/helpers/wrap_highlighted.js
	
	export default function(tokens, idx, options, env, slf, highlighted) {
	  // https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.mjs#L48-L74 goes here
	}
	```

- Add `wrap_highlighted` to `lib/helpers/index.mjs`

-
	```js
	// lib/presets/default.mjs

	// import wrap_highlighted

	export default {
	  // …
	  wrapHighlighted: wrap_highlighted,
	  // …
	}
	```

-
	```js
	// lib/renderer.mjs
	
	// …
	
	default_rules.fence = function (tokens, idx, options, env, slf) {
	  // https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.mjs#L30-L46 goes here
	
	  if (options.highlightCodeWrap) {
	    return options.wrapHighlighted(tokens, idx, options, env, slf, highlighted)
	  }
	
	  // https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.mjs#L49 goes here
	}
	
	// …
	```

**Comment by olets** [comment]
Would still like my suggestion above, but in the meantime I packaged up the wrapperless fence rule as a plugin:

https://github.com/olets/markdown-it-wrapperless-fence-rule

The README has some Stackblitz links
