### ISSUE TITLE
Dashes in URLs with typographer option enabled

### ISSUE THREAD

**Issue by freshlogic** [markdown-it/markdown-it#272]
```
var md = require('markdown-it')({ linkify: true, typographer: true });
var html = md.render('https://www.youtube.com/watch?v=ex--O-cJcZA');
console.log(html);
```

Expected:
```
<p><a href="https://www.youtube.com/watch?v=ex--O-cJcZA">https://www.youtube.com/watch?v=ex--O-cJcZA</a></p>
```

Actual:
```
<p><a href="https://www.youtube.com/watch?v=ex--O-cJcZA">https://www.youtube.com/watch?v=ex–O-cJcZA</a></p>
```

**Comment by puzrin** [comment]
`.disable('replacements')` could be a quick fix, if you don't need those at all.

I think it's possible to improve those:

- skip links with "auto" attr
- ? skip links starting with `http://`, `https://` & `ftp://`

**Comment by rlidwka** [comment]
Thanks for reporting. Fixed in master, so now replacements won't be applied to anything inside autolinks.
