### ISSUE TITLE
Cannot escape typographer replacements

### ISSUE THREAD

**Issue by nielsAD** [markdown-it/markdown-it#274]
It would be nice to be able to escape typographic replacements (e.g. using `\(c\)` would not turn into a copyright symbol).

**Comment by puzrin** [comment]
That's not possible with current implementation. You can only disable replacements or change it to other fn.

**Comment by puzrin** [comment]
Close as "wontfix" for now.

**Comment by RedBug312** [comment]
HTML encoding is one way to escape, `&#40;c)` for this case.

**Comment by coryschires** [comment]
If, like me, you want all typographic replacements (e.g. quotes, m-dash, n-dash, etc) except copyright, I recommend using [markdown-it-replacements](https://github.com/edemaine/markdown-it-replacements). 

The trick is to set `typographer: true` _and_  use markdown-it-replacements. For me, this achieves the desired result.

---

Separately, a recommendation for @puzrin... I think the `typographer` option should not convert `(c)` to ` ©`. In my experience, it's pretty common for authors to do something like:

> I would like to make the following three points: (a) foo, (b) bar, (c) baz.

Whereas the need for copyright replacement is much less common in my experience. So, in short, the current behavior causes more problems than it solves. 

But that's just my two cents. Thanks for making a great library!

**Comment by puzrin** [comment]
[workaround](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%28c%5C%5C%29%20baz.%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

> Whereas the need for copyright replacement is much less common in my experience.

I have different opinion. Need to collect stat somehow.

**Comment by LeaVerou** [comment]
> If, like me, you want all typographic replacements (e.g. quotes, m-dash, n-dash, etc) except copyright, I recommend using [markdown-it-replacements](https://github.com/edemaine/markdown-it-replacements).
> 
> The trick is to set `typographer: true` _and_ use markdown-it-replacements. For me, this achieves the desired result.
> 
> Separately, a recommendation for @puzrin... I think the `typographer` option should not convert `(c)` to ` ©`. In my experience, it's pretty common for authors to do something like:
> 
> > I would like to make the following three points: (a) foo, (b) bar, (c) baz.
> 
> Whereas the need for copyright replacement is much less common in my experience. So, in short, the current behavior causes more problems than it solves.
> 
> But that's just my two cents. Thanks for making a great library!

Coming here 8 years later to say, this is spot on. I have never, ever needed to have a copyright replaced — in the few occurrences where I need a copyright sign, I can just use the unicode character.
But I have used inline lists like (a) foo, (b) bar, (c) baz, _numerous_ times.
