### ISSUE TITLE
How to theme? any way to add custom classes?

### ISSUE THREAD

**Issue by v3ss0n** [markdown-it/markdown-it#277]
I am trying to theme but i think i use to remember there is option to set a custom class prefix somewhere

**Comment by alinex** [comment]
Why not make the theme css only. I did so and am loading different stylesheets in the html head to change the overall look.

It's all possible with the current tags and classes.

**Comment by v3ss0n** [comment]
putting a wrapper Div and nested selection works but not sure it is optimal if many?

```
.markdownit > p > img {
    width: 100%;
    height: auto;
}
.markdownit > p{
  word-break: break-all;
}
```

**Comment by alinex** [comment]
That looks fine. You can put everything also in multiple div tags. I did just that for the documentation at https://alinex.github.io/node-codedoc/README.md.html the page content is completely done by markdown-it, styled using css and the outer html comes from a gandlebars template.

**Comment by v3ss0n** [comment]
very good one , didn't even realize it is done in Markdown-it  rendering.
