### ISSUE TITLE
Embedded HTML parsing error

### ISSUE THREAD

**Issue by SynCap** [markdown-it/markdown-it#279]
Try render this live example with `markdown-it`:

```markdown
<p align="right">
English description | <a href="README_RU.md">Описание на русском</a>
</p>

# ![Tars](https://raw.githubusercontent.com/artem-malko/artwork/master/tars/logo.png)

[![Mac/Linux Build Status](https://img.shields.io/travis/tars/tars/master.svg?label=Mac%20OSX%20%26%20Linux&style=flat-square)](https://travis-ci.org/tars/tars) [![Windows Build status](https://img.shields.io/appveyor/ci/artem-malko/tars/master.svg?label=Windows&style=flat-square)](https://ci.appveyor.com/project/artem-malko/tars/branch/master) [![Gitter](https://img.shields.io/badge/gitter-join%20chat%20%E2%86%92-brightgreen.svg?style=flat-square)](https://gitter.im/tars/tars?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

TARS is a builder for modern frontend of any complexity, which is based on [Gulp.js](http://gulpjs.com/). It facilitates and accelerates process of web-development. TARS will be suitable for teams and individual developer. It solves the most routine cases associated with a web-development and it brings you more pleasure from work.
```
H1 - covers all text.

**Comment by puzrin** [comment]
[I don't see problem with it](http://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Cp%20align%3D%5C%22right%5C%22%3E%5CnEnglish%20description%20%7C%20%3Ca%20href%3D%5C%22README_RU.md%5C%22%3E%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%BD%D0%B0%20%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%BE%D0%BC%3C%2Fa%3E%5Cn%3C%2Fp%3E%5Cn%5Cn%23%20!%5BTars%5D%28https%3A%2F%2Fraw.githubusercontent.com%2Fartem-malko%2Fartwork%2Fmaster%2Ftars%2Flogo.png%29%5Cn%5Cn%5B!%5BMac%2FLinux%20Build%20Status%5D%28https%3A%2F%2Fimg.shields.io%2Ftravis%2Ftars%2Ftars%2Fmaster.svg%3Flabel%3DMac%2520OSX%2520%2526%2520Linux%26style%3Dflat-square%29%5D%28https%3A%2F%2Ftravis-ci.org%2Ftars%2Ftars%29%20%5B!%5BWindows%20Build%20status%5D%28https%3A%2F%2Fimg.shields.io%2Fappveyor%2Fci%2Fartem-malko%2Ftars%2Fmaster.svg%3Flabel%3DWindows%26style%3Dflat-square%29%5D%28https%3A%2F%2Fci.appveyor.com%2Fproject%2Fartem-malko%2Ftars%2Fbranch%2Fmaster%29%20%5B!%5BGitter%5D%28https%3A%2F%2Fimg.shields.io%2Fbadge%2Fgitter-join%2520chat%2520%25E2%2586%2592-brightgreen.svg%3Fstyle%3Dflat-square%29%5D%28https%3A%2F%2Fgitter.im%2Ftars%2Ftars%3Futm_source%3Dbadge%26utm_medium%3Dbadge%26utm_campaign%3Dpr-badge%29%5Cn%5CnTARS%20is%20a%20builder%20for%20modern%20frontend%20of%20any%20complexity%2C%20which%20is%20based%20on%20%5BGulp.js%5D%28http%3A%2F%2Fgulpjs.com%2F%29.%20It%20facilitates%20and%20accelerates%20process%20of%20web-development.%20TARS%20will%20be%20suitable%20for%20teams%20and%20individual%20developer.%20It%20solves%20the%20most%20routine%20cases%20associated%20with%20a%20web-development%20and%20it%20brings%20you%20more%20pleasure%20from%20work.%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

What is wrong?

**Comment by SynCap** [comment]
Embedded HTML stays as is, but ALL following text encloses by H1 tag.
For example, [GFMR](https://github.com/SynCap/GFMR) (with latest markdown-it) renders like that:

![image](https://cloud.githubusercontent.com/assets/1856986/17835664/5e6c7814-67a9-11e6-88d7-123ff15035de.png)

When embedded  text converted to markdown, rendering looks no problem: 

![image](https://cloud.githubusercontent.com/assets/1856986/17835677/db840164-67a9-11e6-8c2a-d420d8c70aca.png)

Also, not so rarely i've meets markdown inside embedded HTML.
For example:
```
<p align="right" style="width:50%;folat:right">![](this_is_awesome.jpg)</p>
```

**Comment by puzrin** [comment]
I'm closing issue until example of wrong header provided. Sample from the first post is ok. If you suspect something is wrong - just give a link to example in live demo as i did.

Also read CM spec about html markup and other things, it's not strictly equal to GFM. For close to GFM behaviour - try https://github.com/npm/marky-markdown
