### ISSUE TITLE
Enable GFM-style triple backticks

### ISSUE THREAD

**Issue by brentonstrine** [markdown-it/markdown-it#280]
Currently, code blocked off with triple backticks is just rendered with `<code>`. Would be nice if it was wrapped with `<pre><code>content</code></pre>` to distinguish blocks of code with **\`\`\`** and inline code with **\`**.

**Comment by puzrin** [comment]
Just override appropriate renderers as you wish.

**Comment by brentonstrine** [comment]
Maybe it would be helpful to explain this in the readme file or documentation somewhere if it isn't already. I'll go fishing. :D
