### ISSUE TITLE
Create a GitHub Flavored Markdown preset

### ISSUE THREAD

**Issue by brentonstrine** [markdown-it/markdown-it#281]
Would be great to make a preset available to match GFM, especially since the default is already similar to GFM

```
var md = require('markdown-it')('GFM');
```
or
```
var md = require('markdown-it')('github');
```

**Comment by puzrin** [comment]
Please, don't create requests to modify core. This parser follows CommonMark spec. Everything else is left for external configuration and plugins.

**Comment by borekb** [comment]
GFM also follows CommonMark spec so I think it's quite reasonable to consider providing this popular format out of the box. I've just tried to find a combination of settings and/or extensions that would render Markdown exactly as on GitHub and failed :(

**Comment by puzrin** [comment]
1. GFM has no specification
2. No, it does not follow CM spec.

You probably need this package https://github.com/npm/marky-markdown

**Comment by krixano** [comment]
https://githubengineering.com/a-formal-spec-for-github-markdown/

**Comment by puzrin** [comment]
@krixano thank for the links. That's better than nothing, but not more :) . You can see all extensions doc is very primitive (compare with other elements).

Anyway, if someone wish "something similar to GFM" - just use defaults and tune [options](https://github.com/markdown-it/markdown-it#init-with-presets-and-options) only. If more close behaviour needed - use `marky-markdown`.

**Comment by borekb** [comment]
Thanks for the pointer to marky-markdown, that seems exactly like what I was looking for. I was probably just bad a googling :)
