### ISSUE TITLE
Could embedded  plugin  Strikethrough  output<del> instead of <s>?

### ISSUE THREAD

**Issue by scil** [markdown-it/markdown-it#282]
Now Github parse `~~This was mistaken text~~ ` to `<del>This was mistaken text</del>`(https://help.github.com/enterprise/2.7/user/articles/basic-writing-and-formatting-syntax/)

And,
> The s element represents contents that are no longer accurate or no longer relevant.
> 
> The del element represents a removal from the document.
>
> http://html5doctor.com/ins-del-s/

**Comment by puzrin** [comment]
I'm familiar with difference. For now i'd suggest to override renderer instead. `<del>` was expected to use in something like diff, coupled with `<ins>`.

Leaving this open if someone has more to say.

**Comment by puzrin** [comment]
Closing - seems nobody care.

We can reopen after CM spec says something certain. Now it's better to customise markup via renderer as usual.

**Comment by thom4parisot** [comment]
`<s>` is a *styling* tag (like `<b>` and `<i>`). Which implies accessibility warnings (invalidates a [G115 WCAG rule](https://www.w3.org/WAI/WCAG21/Techniques/general/G115)) `<del>` is a semantic one (like the output of `**` and `*`, which are `<strong>` and `<em>`).

It would make sense to align on GFM and accessibility, allowing to customize the tag but only for a period of time, eventually.
