### ISSUE TITLE
zero + breaks + typographer = possible?

### ISSUE THREAD

**Issue by ile** [markdown-it/markdown-it#283]
Hi again,

I'm trying to do this:

```js
md = new Markdown('zero', { breaks: true, typographer: true, linkify: true })
md.render('hello
there'); 
```

outputs:
```html
<p>hello
there</p>
```

Should output?
```html
<p>hello<br>there</p>
```

Linkify works, but breaks / typography don't seem to work. Is there a way to use zero with breaks and typographer?

I tracked this into some inline rules (`text` maybe), but then I got lost.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/tree/master/lib see `rules_*`, you need to .`enable()` back appropriate rules, because zero preset disables almost everything
