### ISSUE TITLE
Extra paragraphs in output

### ISSUE THREAD

**Issue by ivan-kleshnin** [markdown-it/markdown-it#284]
```js
let Markdown = require("markdown-it")

let md = Markdown({
  html: true,      
  breaks: false,      
})

console.log(md.render(`
  foo
  
  <h4 class="custom">test</h4>
  
  bar
`))
```

outputs

```
<p>foo</p>
<p><h4 class="custom">test</h4></p>
<p>bar</p>
```

**H4 inside P is invalid HTML** and is rendered in browsers as 

```
<p>foo</p>
<p></p>
<h4 class="custom">test</h4>
<p></p>
<p>bar</p>
```

leading to extra whitespace above and below headers.

---
Checked in 7.0.0 and 7.0.1

**Comment by puzrin** [comment]
Works as expected (non-single html tag considered as paragraph with inline html). See commonmark spec.

[This works as you need](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22foo%5Cn%5Cn%3Ch4%20class%3D%5C%22custom%5C%22%3E%5Cntest%5Cn%3C%2Fh4%3E%5Cn%5Cnbar%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D)
