### ISSUE TITLE
renderToken() call with extraneous argument

### ISSUE THREAD

**Issue by kjk** [markdown-it/markdown-it#286]
It's harmless, but still: In https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.js#L328, a call to renderToken() passes `env` argument but renderToken() function doesn't take 4 arguments, only 3.

**Comment by puzrin** [comment]
Someone could wish to override that function. I don't think anyone ever need it, but think it's better to leave function call as is. It's more convenient when renderer is called with the same signature everywhere.
