### ISSUE TITLE
TypeScript Definitions don't support highlighting?

### ISSUE THREAD

**Issue by georgeedwards** [markdown-it/markdown-it#288]
If you take the following example, which (correct me if I'm wrong) is the TypeScript implementation of the example given in the README for highlighting:

```
var hljs = require('highlight.js');
import * as MarkdownIt from 'markdown-it';
var md = new MarkdownIt({
  highlight: function (str, lang) {
    if (lang && hljs.getLanguage(lang)) {
      try {
        return hljs.highlight(lang, str).value;
      } catch (__) {}
    }

    return ''; // use external default escaping
  }
});
```
The typescript compiler throw the error:

>Argument of type '{ [x: number]: undefined; highlight: (str: any, lang: any) => any; }' is not assignable to parameter of type 'string'

Is this correct and if so, can we modify the typescript definition to support this?

**Comment by puzrin** [comment]
Project is written in pure es5 and all samples are in es5. I'm not familiar with typescript and here are no any typescript definitions. Not sure here is right place for such questions.

**Comment by georgeedwards** [comment]
@puzrin There is a `highlightjs` definition on typings. Is this unofficial then?

**Comment by georgeedwards** [comment]
@puzrin There is a TS Definition file on Typings for [`Markdown-IT`](https://www.npmjs.com/package/markdown-it) with that link. Is this unofficial then?

**Comment by puzrin** [comment]
I think it's done by someone else and i don't know anything about it, sorry. All "official" (supported by us) packages are located https://github.com/markdown-it only.

**Comment by puzrin** [comment]
https://github.com/typings/registry/blob/master/npm/markdown-it.json that's a file in typings registry. Anyone can update it to more actual.
