### ISSUE TITLE
No documentation listing rules?

### ISSUE THREAD

**Issue by MikeRatcliffe** [markdown-it/markdown-it#289]
I have been trying to gather together all of the rules that can be used with markdown.it. Can you have a look over them and let me know which I have right and which I have wrong?

```
'autolink',      // Automatically convert link text surrounded by angle brackets to <a> tags
'backticks',     // Allow inline code blocks using backticks
'blockquote',    // > I am a blockquote becomes <blockquote>I am a blockquote</blockquote>
'code',          // Code block (4 spaces padded)
'emphasis',      // *Emphasize* _emphasize_ **Strong** __Strong__
'entity',        // Parse HTML entities e.g. &amp;
'escape',        // Automatically escape special characters.
'fence',         // Fenced code blocks
'heading',       // # Foo becomes <h1>Foo</h1>. ###### becomes <h6>Foo</h6>
'hr',            // ***, --- and ___ produce a <hr> tag.
'html_block',    // Enable / disable HTML blocks.
'html_inline',   // Enable / disable inline HTML.
'image'          // Enable / disable inline images.
'lheading',      // Use === or --- underneath text for h1 and h2 blocks.
'link',          // Process [link](<to> "stuff")
'linkify',       // Replace link-like texts with link nodes.
'list',          // Ordered and unordered lists.
'newline',       // '  \n' -> <br>
'normalize',     // Replace newlines with \n, null characters and convert tabs to spaces.
'paragraph'      // Use blank lines to indicate a paragraph.
'reference',     // Reference style links e.g. [an example][id] reference-style link... further down in the document [id]: http://example.com/  "Optional Title Here"
'strikethrough', // ~~strike through~~
'table',         // GFM style tables
'text_collapse', // Merge adjacent text nodes into one, and re-calculate all token levels
```

**Comment by rlidwka** [comment]
All of it seems correct.

> 'heading',       // Same as lheading

Almost, but not quite. Heading is `# something`, lheading is `something\n=======`, both are rendered into `<hX>` tags however.

> 'text'           // Can't work out what the heck this does.

It's a hack to speed up parsing walls of text. It shouldn't affect output I don't think, and should usually be enabled (I can't think of a reason to disable it).

**Comment by MikeRatcliffe** [comment]
Great, I have updated my list... should this not be documented somewhere?

**Comment by puzrin** [comment]
> should this not be documented somewhere?

Not sure. User still needs to read spec & sources to understand right what happens. And after it's done, such comments are not needed too much IMHO.

I'd suggest to close issue now and reopen after couple of month if you are still sure this can be useful.

**Comment by CNSKnight** [comment]
...and what are the de-faults?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/tree/8.2.2/lib/presets

**Comment by MartinMuzatko** [comment]
I would also have needed that list.. Nowhere this is stated on the documentation or the main readme :/

**Comment by titaniumbones** [comment]
I know this is closed, but a more comprehensive list in the docs somewhere would certainly help me as well.

**Comment by simonprovost** [comment]
Agree with the others. A List could be helpful to view what are the options that we could enable disable and so on. It's not intuitive today. Btw, thanks to this post guys.

**Comment by hadleygarrett** [comment]
This is super useful. I had to do a lot of manual work to figure out the various rules and what they meant. I would appreciate this list somewhere on the readme! Thank you for putting this together, Mike.
