### ISSUE TITLE
Blockquotes not rendering

### ISSUE THREAD

**Issue by wurde** [markdown-it/markdown-it#290]
I can't see block quotes rendered via ">" characters.

Could this be due to most recent commit changes?
7a053ef "Fix tab behavior inside blockquotes"

**Comment by puzrin** [comment]
All tests are ok. Please, provide example via online demo.

**Comment by wurde** [comment]
Solved within my implementation. I needed to set content passed in as html_safe within the Rails app. 

Closing as a 'non-issue'.
