### ISSUE TITLE
Help formatting Free Software Magazine

### ISSUE THREAD

**Issue by mercmobily** [markdown-it/markdown-it#291]
I am the owner of Free Software Magazine. We had a huge server crash. I am 99.9% finished eradicating the article database from the ancient Drupal system, and have converted everything to a static file. (http://www.freesoftwaremagazine.com -- it's not styled yet... the priority right now is getting the data back up!)

The problem I have is that I have Markdown like this:

    What about Android?
    
    <div class="textbox">
    <h2>But Tony, didn't you love Ubuntu?</h2>
    <div class="textbox-contents">
    Yes, I still **absolutely** love Ubuntu; 
    * One
    * Two
    * Three
    </div>
    </div>
    Blah blah

I need `remark` to:

* Leave the HTML as it is (this is already happening)
* Actually *format* the contents of the DIV (this is not happening)

 At the moment, I am doing:

    var MarkdownIt = require('markdown-it');
    md = new MarkdownIt({
       html: true
    });
    fileData.contents = md.render( fileData.contents );

With the PHP version of Markdown, I could add something the the HTML:

    <div class="textbox-contents" markdown=1>

And the contents would be interpreted. Is there any way I could do that here?

Thank you!

**Comment by puzrin** [comment]
http://spec.commonmark.org/0.26/#html-blocks you need whiteline before and after html blocks. Just follow commonmark spec.
