### ISSUE TITLE
Link formatting failure with file://...

### ISSUE THREAD

**Issue by noahleigh** [markdown-it/markdown-it#294]
See [example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%5BWorking%20Link%5D%28http%3A%2F%2Fhello%29%5Cn%5Cn%5BStill%20Working%20Link%5D%28garbage%3A%2F%2Fhello%29%5Cn%5Cn%5BWhy%20don%27t%20I%20work%3F%5D%28file%3A%2F%2Fhello%29%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

**Comment by noahleigh** [comment]
Works in CommonMark: http://spec.commonmark.org/dingus/?text=%5BI%20work!%5D(file%3A%2F%2Fhello)

**Comment by puzrin** [comment]
That's intended, for security reasons.

https://github.com/markdown-it/markdown-it/blob/8.0.0/lib/index.js#L32-L85

See sources of additional methods, you can override those with custom implementations for your needs.
