### ISSUE TITLE
Tables and tabs characters problem

### ISSUE THREAD

**Issue by TeknoBebel** [markdown-it/markdown-it#295]
I have a problem with tables not being detected.

While editing documents with a text editor, [elastic tab stops](http://nickgravgaard.com/elastic-tabstops/) can be used to keep things neat and aligned. But when markdown-it is used to render, it doesn't detect the text as a table due to the tabs characters in the _"header separator"_ line.

So while the following table renders nicely:
````
| Just | Testing |
| --- | --- |
| Only | using spaces |
````
If i use tabs to keep the cell width constant in text mode, it isn't recognized as a table:
````
| Just[TAB]| Testing[TAB]|
| --- [TAB]| ---    [TAB]|
| with[TAB]| tabs   [TAB]|
````
But this one will be ok:
````
| Just[TAB]| Testing[TAB]|
| --- | --- |
| No tabs[TAB]| in "header separator" line[TAB]|
````
So it _looks like_ it's not detecting the table because of tabs characters in the "header separator" line. 

```` javascript
var md = MarkdownIt();
console.log(md.render('| Just | Testing |\n| --- | --- |\n| Only | using spaces |\n'));
console.log(md.render('| Just \t| Testing \t|\n| --- \t| ---\t|\n| with\n| tabs \t|\n'));
console.log(md.render('| Just \t| Testing \t|\n| --- | --- |\n| No tabs\t| in "header separator" line\t|\n'));
````

**Comment by puzrin** [comment]
Fixed by https://github.com/markdown-it/markdown-it/commit/1bb254b879cff95c67f7ae452b2ba8cdefd87da3

**Comment by puzrin** [comment]
Thank you for report and good examples!

**Comment by TeknoBebel** [comment]
And thank you for markdown-it, and for fixing this so quickly :)
