### ISSUE TITLE
Disabling `paragraph` causes an infinite loop

### ISSUE THREAD

**Issue by ChiperSoft** [markdown-it/markdown-it#296]
I wanted to create a routine that would strip all markdown formatting and spit out the input as plain text, so I created the following:

```js
var md = require('markdown-it');
var MarkdownStrip  = md('zero', {}).disable('paragraph');
exports.strip = (input) => MarkdownStrip.render(input);
```

Every time this gets called the code goes into an infinite loop that I can't even control-c out of, I have to force kill the process.  Removing the `.disable('paragraph')` allows the code to run, but naturally this gives me paragraph wraps around the text.

In the mean time I'm using `striptags` to remove those paragraphs, but this is probably a bug worth looking in to since it kills the event loop.

**Comment by ChiperSoft** [comment]
Upon further investigation, the zero config doesn't do what I wanted anyway, since it leaves all the markdown formatting in place. Oh well.

**Comment by puzrin** [comment]
Works as expected. Don't disable paragraphs :). Also, if you don't wish blocks processing, you can use `.renderIncline()`

**Comment by ChiperSoft** [comment]
If it's working as expected then perhaps it could throw an error when you try to disable paragraphs instead of just looping forever?

**Comment by puzrin** [comment]
I think that's possible, but not necessary. At least, you are the first for 2 years who tried to do that :)

**Comment by viharm** [comment]
Thanks for all the hard work.

I'm using this through _11ty_.

I've got the same issue. I'm trying to render multiple variables to form a sentence, and the `<p>` tag is really coming in the way.

Was this ever resolved?

**Comment by jean343** [comment]
Yes, see https://github.com/markdown-it/markdown-it/issues/811#issuecomment-905272202

**Comment by rlidwka** [comment]
> If it's working as expected then perhaps it could throw an error when you try to disable paragraphs instead of just looping forever?

Just for the record, this now should throw an error on the latest version:

https://github.com/markdown-it/markdown-it/blob/e476f78bc3ea3576beb61bdc94322d0a6b2d85cc/lib/parser_block.js#L89-L90
