### ISSUE TITLE
fence#attrs treated different than code_block#attrs

### ISSUE THREAD

**Issue by envygeeks** [markdown-it/markdown-it#297]
```
Token {
  type: 'fence',
  tag: 'code',
  attrs: [ [ 'data-md-type', 'gfm' ] ],
  map: [ 0, 3 ],
  nesting: 0,
  level: 0,
  children: null,
  content: 'code\n',
  markup: '```',
  info: '',
  meta: null,
  block: true,
  hidden: false }
```

Results in:
```html
<pre>
  <code data-md-type="gfm">
code
  </code>
</pre>
```

---

```
Token {
  type: 'code_block',
  tag: 'code',
  attrs: [ [ 'data-md-type', 'spec' ] ],
  map: [ 0, 1 ],
  nesting: 0,
  level: 0,
  children: null,
  content: 'code',
  markup: '',
  info: '',
  meta: null,
  block: true,
  hidden: false }
```

Results in:

```html
<pre data-md-type="gfm">
  <code>
code
  </code>
</pre>
```

**Comment by puzrin** [comment]
Those tags are really different by nature. I'd recommend to override default renderers if you don't like such behaviour. That's very simple.

**Comment by envygeeks** [comment]
No, you make them different by nature, but they are not actually different by nature.  That's okay though, we already accounted for this locally expecting this response.  Thanks for the response at least.

**Comment by puzrin** [comment]
Fences are different, because CM spec has requirement to add lang attributes to `pre` tag instead of `code`. Also different people has different opinions about proper location of pre+code attributes.

Since we can't select "best for all" solution, it's better to not break anything and let users to decide. If they can modify attributes - they already have enougth skills to modify renderer too when required.

**Comment by envygeeks** [comment]
Where you choose to add the language has ***nothing*** to do with the difference in attribute behavior... that's a logic choice in ***your*** source, not a logical choice to somebody using your API.

**Comment by puzrin** [comment]
It's not logical only if you consider fenced and padded code blocks the same. if not - then it can be more convenient to have custom attrs on pre for different styling.

Anyway, if somebody considers existing choice not logical, that's not the reason to change things for all. I think, package solve it's main task - provides good api to customize features for user needs, without dependency on my personal opinion.
