### ISSUE TITLE
Options not passed to plugins

### ISSUE THREAD

**Issue by iamso** [markdown-it/markdown-it#298]
The options object is not passed to the plugins. I don't know if this has been changed at some point, but some plugins rely on that options object being passed as the second argument.

This, of course, breaks/prevents configuration of the plugins.

To see what I mean, you can do the following:
```javascript
const md = require('markdown-it')({
  html: true,
  xhtmlOut: false,
  breaks: true
}).use(function() {
  console.log(arguments);
});
```
And you will see, that there is no second argument.

Am I doing something wrong here?

**Comment by puzrin** [comment]
See `.use()` src https://github.com/markdown-it/markdown-it/blob/8.0.1/lib/index.js#L494-L498

```
.use(function (md) {
  console.log(md.options);
});
```

Plugin options != parser options. Second and next params appears only if those exists in `.use()` call. This signature was not changed since v3.+.

**Comment by iamso** [comment]
@puzrin Thanks. I didn't know, that I could pass options to the `.use()` function.
