### ISSUE TITLE
Some characters unexpectedly need escaping...

### ISSUE THREAD

**Issue by Lord-Kamina** [markdown-it/markdown-it#300]
First, I'll say my use case is very specific. I'm using the markdown-it chiefly as a means to produce a decent "changelog" for my Firefox add-on. This means I'm using it from inside JPM; so I'm not entirely sure whether the problem lies with markdown-it (or perhaps uc.micro), with JPM or with the interaction of both.

I have noticed that, whenever I have a list (ordered or unordered seems to make no difference; only other thing I've found that works is code blocks) that contains either a _ (also true for * but that's more to be expected I guess) inside one of the items (even mid-word), I get a throw originating in ```isPunctChar (markdown-it/lib/common/utils.js:190:10)```. After much trial and error I've noticed that escaping the offending characters fixes the issue. I have not been able to reproduce this in the live test, so it might be something in jpm; but I'll be damned if I know what.

EDIT: Whoops, forgot the actual error message. It's ```[error]   Message: TypeError: "lastIndex" is read-only```

**Comment by puzrin** [comment]
Search shows this is the only place where lastIndex is rewritten https://github.com/markdown-it/markdown-it/blob/8.0.1/lib/rules_core/smartquotes.js#L45

Try to disable smartquotes rule. Also make sure you don't use buggy uglifier and so on...

**Comment by Lord-Kamina** [comment]
I tried but that didn't work. However, I have found the proper solution. I'm not gonna make a PR or anything because it'd be incredibly overkilll, but this fixes it.

```
--- /Users/Koji/keybinder/node_modules/markdown-it/lib/common/utils.js	2016-10-29 19:27:41.000000000 -0300
+++ /Users/Koji/Desktop/utils.js	2016-10-29 19:29:05.000000000 -0300
@@ -183,7 +183,7 @@
 ////////////////////////////////////////////////////////////////////////////////
 
 /*eslint-disable max-len*/
-var UNICODE_PUNCT_RE = require('uc.micro/categories/P/regex');
+var UNICODE_PUNCT_RE = new RegExp(require('uc.micro/categories/P/regex'));
 
 // Currently without astral characters support.
 function isPunctChar(ch) {
```

**Comment by puzrin** [comment]
That looks really strange, may be a packager bug in your project. How do you call the module in your sources? As node's commonjs or as browser bundle from `dist/` folder?

**Comment by Lord-Kamina** [comment]
```
var md = require('markdown-it')({
  html: false,
  linkify: true,
  typographer: true,
  xhtmlOut:     true
  });
```
Basically, syntax straight out of the readme. I suspect the problem might actually be related to uc.micro's export syntax. I first got the idea when I realized if I copy-pasted the regex pattern inline in utils.js, the error disappeared. Wasn't too big a stretch from there to assuming it was a Type issue. Perhaps at some step it was being implicitly being turned into a string or something like that.

**Comment by puzrin** [comment]
Try `require('markdown-it/dist/marjdown-it.js')`, may be `require` is broken and bundled package with internal wrapper will be better.

There is nothing bad with regex export, IMHO. Those files are just repackaged peaces from https://github.com/mathiasbynens/unicode-9.0.0, even without src change.

**Comment by Lord-Kamina** [comment]
Indeed that also works. I'll use your solution if only to make it simpler to update markdown-it in the future, I guess.

Thanks.

**Comment by puzrin** [comment]
Can we close this issue then as solved/outer?

**Comment by Lord-Kamina** [comment]
Yeah.
