### ISSUE TITLE
Incorrect Rendering of Table With Inline Code Cells

### ISSUE THREAD

**Issue by mjbvz** [markdown-it/markdown-it#303]
Reported From: https://github.com/Microsoft/vscode/issues/16134

**Bug**
The following markdown table:

```md
# | 1 | 2
--|--|--
x | `\` | `x`
```

is currently rendered as:

<img width="551" alt="screen shot 2016-11-28 at 11 03 37 am" src="https://cloud.githubusercontent.com/assets/12821956/20681821/25b42be4-b55a-11e6-9cc7-3ef765e68278.png">

with html:

```html
<table>
<thead>
<tr>
<th>#</th>
<th>1</th>
<th>2</th>
</tr>
</thead>
<tbody>
<tr>
<td>x</td>
<td><code>\</code> | <code>x</code></td>
<td></td>
</tr>
</tbody>
</table>
```

**Expected**
I believe the correct rendering is:

<img width="552" alt="screen shot 2016-11-28 at 11 05 12 am" src="https://cloud.githubusercontent.com/assets/12821956/20681867/5de740a0-b55a-11e6-9237-ab8f7eb3bd8b.png">

with html:

```html
<table>
<thead>
<tr>
<th>#</th>
<th>1</th>
<th>2</th>
</tr>
</thead>
<tbody>
<tr>
<td>x</td>
<td><code>\</code></td>
<td><code>x</code></td>
</tr>
</tbody>
</table>
```

**Comment by rlidwka** [comment]
Fixed, thanks!
