### ISSUE TITLE
Incorrect rendering of blockquotes

### ISSUE THREAD

**Issue by alinex** [markdown-it/markdown-it#304]
I have the markdown:

    > Stefan said:
    > > I would like to visit a castle in north scotland, next year.
    > But my home is my castle

But the fird line will added directly to the second line with depth=2 instead of being in the same depth as the first line. Look at it in the live Demo.

**Comment by puzrin** [comment]
[Reference implementation works the same way](http://spec.commonmark.org/dingus/?text=%3E%20Stefan%20said%3A%0A%3E%20%3E%20I%20would%20like%20to%20visit%20a%20castle%20in%20north%20scotland%2C%20next%20year.%0A%3E%20But%20my%20home%20is%20my%20castle).

I don't remember details, but i think you can find those in commonmark spec. Or you can suggest improbment on commonmark dorum.

**Comment by rlidwka** [comment]
Third line is a paragraph continuation.

```md
> This is rendered as
a single blockquote
```

```md
>
> > This is rendered
> as a single blockquote
```

See the idea behind this?

If you want to place third line inside 1st level blockquote, you need to add empty line just before it:

```md
> Stefan said:
>
> > I would like to visit a castle in north scotland, next year.
>
> But my home is my castle
```
