### ISSUE TITLE
Having problems disabling the paragraph rule for MarkdownIt.render()

### ISSUE THREAD

**Issue by jhyland87** [markdown-it/markdown-it#307]
Hello! I'm using a [Metalsmith](http://www.metalsmith.io/) plugin which is basically a fancy wrapper around *markdown-it* - [metalsmith-markdownit](https://github.com/mayo/metalsmith-markdownit). In addition to the *metalsmith-markdownit* plugin, I'm using a template parsing plugin. How it works is any content defined in the `.md` markdown file will get included in the template. So basically, the majority of the HTML is done somewhere *other* than the markdown-it parsing.

Obviously you don't support either of those metalsmith plugins, and I don't expect you to. I'm just giving you the reason behind why I want to disable the *paragraph* rule. By looking at the source for  *metalsmith-markdownit* I can [see that it utilizes](https://github.com/mayo/metalsmith-markdownit/blob/master/lib/index.js#L41) the `MarkdownIt.render` method to process the markdown content, as opposed to the `MarkdownIt.renderInline` method. And after reading through some of the markdown-it documentation, I found that the difference between the two is:

> ### [`MarkdownIt. renderInline`](https://markdown-it.github.io/markdown-it/#MarkdownIt.renderInline)
> Similar to [`MarkdownIt.render`](https://markdown-it.github.io/markdown-it/#MarkdownIt.render) but for single paragraph content. Result will NOT be wrapped into `<p>` tags.

I [can access the *markdown-it* instance](https://www.npmjs.com/package/metalsmith-markdownit#javascript-usage) thats initiated by *metalsmith-markdownit* plugin, and I can see that markdown-it has a [method for disabling rules](https://markdown-it.github.io/markdown-it/#MarkdownIt.disable), so theoretically, it looks like I should be able to disable the [**paragraph**](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_block/paragraph.js) rule, and the `<p>` tags should stop showing up.. right?

Here's a test, executing the `MarkdownIt.render` and `MarkdownIt.renderInline` methods through the `metalsmith-markdownit` plugin:
```javascript
const Metalsmith  = require( 'metalsmith' )
const markdown    = require( 'metalsmith-markdownit' )

const md = markdown({
  html: true,
  xhtmlOut: true,
  typographer: true,
  linkify: true
})

//md.parser.disable('paragraph')

const str = "Hello World!"

console.log( 'Original String:', str )
console.log( 'MarkdownIt.render:', md.parser.render( str ) )
console.log( 'MarkdownIt.renderInline:', md.parser.renderInline( str ) )
```
Result:
> $ DEBUG=* node metalsmith_markdown_test.js
> Original String: Hello World!
> MarkdownIt.render: <p>Hello World!</p>
> 
> MarkdownIt.renderInline: Hello World!

But then when I uncomment the line where I execute the `Ruler.disable` method, it outputs the following:
Result:
> $ DEBUG=* node metalsmith_markdown_test.js
> Original String: Hello World!
> 
And just hangs there...

Am I doing something wrong? Or is it not possible to disable the *paragraph* rule for `MarkdownIt.render`? And if so, do you have any suggestions?

Thanks!

**Comment by puzrin** [comment]
> Or is it not possible to disable the paragraph rule for `MarkdownIt.render`? 

Yes, that's technically impossible to make `.render()` work without `paragraph`. And this can't be changed. You can only use  .render() with pharagraphs, or .renderInline() without paragraphs.

**Comment by jhyland87** [comment]
Hey, back to this question.. I thought the only difference between `render` and `renderInline`, was that `render` would add `<p></p>` tags everywhere?

I'm also noticing that `renderInline` doesnt seem to render the headers.

EG: This (markdown format):
```markdown
### Welcome to my website!

This is a test
```
Using `render` is rendered as:
```html
<h3>Welcome to my website!</h3>
<p>This is a test</p>
```
But using `renderInline` is rendered as:
```html
### Welcome to my website!

This is a test
```
What I'm trying to accomplish is:
```html
<h3>Welcome to my website!</h3>
This is a test
```
Is that possible at all?

**Comment by puzrin** [comment]
> Is that possible at all?

You can try to override paragraph's renderer to write text without wrapping tags. But that's not the same as "disable paragraph". That's just output change with the same internal data.
