### ISSUE TITLE
Breakline in Table-Cell

### ISSUE THREAD

**Issue by murieletrentini** [markdown-it/markdown-it#308]
Hi there. I'm loving markdown-it so far! 
However i have run into a problem: I was under the assumption, that you use Github markdown for your table rendering. But i cant seem to be able to insert a linebreak in my tables. Its does however work on github with `<br>` (see table below).
Does anyone know how i can achieve a linebreak in my table using markdown-it?

| test | table |
|-----|------|
|a long table cell <br> with two lines | a short cell |

**Comment by puzrin** [comment]
[enable html](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%7C%20test%20%7C%20table%20%7C%5Cn%7C-----%7C------%7C%5Cn%7Ca%20long%20table%20cell%20%3Cbr%3E%20with%20two%20lines%20%7C%20a%20short%20cell%20%7C%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D), it's disabled bu default.

Dont forget to use sanitizer then, if needed.
