### ISSUE TITLE
markdown rendered inside of html element

### ISSUE THREAD

**Issue by goessner** [markdown-it/markdown-it#310]
Having a Html element with some latex content inside ...

`<eq>{e}_x = a{e}_\alpha</eq> `

will be rendered by `md.render(str)` as

`<p><eq>{e}<em>x = a{e}</em>\alpha</eq></p>`

If you remove the `}` before the first `_` or the backslash after the second  `_` everything is fine.

btw. ... CommonMark does the same thing, so I'm not sure, if it is a bug or a feature.

thanx for your great parser ... !

**Comment by puzrin** [comment]
http://spec.commonmark.org/0.27/ - there are all details about html tags.

Those tags are not paired (with content inside), but passwe as raw result: [ raw html tag ] + [ markdown text ] + [ raw html tag ]. In you case [you need aditional escaping](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Ceq%3E%7Be%7D%5C%5C_x%20%3D%20a%7Be%7D%5C%5C_%5C%5C%5C%5Calpha%3C%2Feq%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D)

**Comment by goessner** [comment]
Thanks for enlightening me ... I think I should have read the spec more carefully.
