### ISSUE TITLE
Thanks for the Debian package

### ISSUE THREAD

**Issue by valerio-bozzolan** [markdown-it/markdown-it#313]
I've found this project from the `libjs-markdown-it` Debian package. Great!

Please add somewhere in the README a ref to the existing Debian package: someone will really appreciate it! :) Only to be known:

https://packages.debian.org/libjs-markdown-it

    # For Debian testing (stretch) -- if you are in stable (jessie) RTFM
    apt-get install libjs-markdown-it

So useful in production  to don't have to update a thing installed multiple time everywhere, using the pre-configured Apache `/javascript/markdown-it/markdown-it.js` alias.

Have a nice day, and thanks again!

**Comment by puzrin** [comment]
I don't like this idea.

1. Such packages usually have old version.
2. Those are mostly useful as CLI tools, but our CLI support is very limited and has low priority.

**Comment by valerio-bozzolan** [comment]
(It's OK to don't like Debian cycles, but why to do not like to show even the existence of the Debian package?)

**Comment by puzrin** [comment]
This info can add more confusion than value, for ordinary users. That package is maintained by 3rd party (not at our side), and i don't like to recommend old versions.

I think, people who like to install deb packages instead of npm already know how to find those.
