### ISSUE TITLE
Embeded <!--HTML comments--> == *bonk!*

### ISSUE THREAD

**Issue by CNSKnight** [markdown-it/markdown-it#314]
I wrote an extension to Mark'd down markup which will apply attributes after the fact. eg:
```
<span class="purple-text">Yes!</span> You can use [Markdown](http://commonmark.org/help/) here! <!--[class:right]--->
```
but the comment shown stubbornly renders thusly.

![markdon-bonk](https://cloud.githubusercontent.com/assets/220025/21411546/47c75e9e-c7b7-11e6-92d9-e15c1b0268a6.png)

the init currently looks like this `md: new MarkdownIt({html: true, linkify: false, html_inline: true, escape: false})`

**Comment by puzrin** [comment]
1. [Seem to be a bug](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22123%20%3C!--%5Bclass%3Aright%5D---%3E%5Cn%5Cn456%20%3C!--%5Bclass%3Aright%5D--%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D) in inline comments.
2. You have wrong init code to enable/disable tules. See readme https://github.com/markdown-it/markdown-it#manage-rules

**Comment by puzrin** [comment]
Ups. Not a bug.

http://spec.commonmark.org/0.27/#raw-html

Comment content should not end with minus.

**Comment by CNSKnight** [comment]
Excellent! Cross-eyed here missing that extraneous '-'.
