### ISSUE TITLE
Paragraph not indented properly in ordered list with additional blank lines

### ISSUE THREAD

**Issue by schnerd** [markdown-it/markdown-it#315]
Similar to #287 but the issue is with ordered lists instead of unordered lists:

[Example in markdown-it demo page](https://markdown-it.github.io/#md3=%7B%22source%22%3A%221.%20Doesn%27t%20work%20with%20ordered%20list%5Cn%5Cn%20%20This%20is%20a%20second%20paragraph%5Cn%5Cn-%20Works%20with%20unordered%20list%5Cn%5Cn%20%20This%20is%20a%20second%20paragraph%5Cn%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)
![screen shot 2016-12-27 at 10 28 41 am](https://cloud.githubusercontent.com/assets/875591/21505771/44a6037a-cc1f-11e6-8d89-3fb0ca9c1824.png)

```
1. Doesn't work with ordered list

  This is a second paragraph

- Works with unordered list

  This is a second paragraph
```

**Comment by schnerd** [comment]
Btw–if anyone needs a workaround, you can use a \&nbsp; character with carefully placed spaces:

```
1. foo
  &nbsp;  
  bar
```

**Comment by puzrin** [comment]
[Reference implementation is the same](http://spec.commonmark.org/dingus/?text=1.%20Doesn%27t%20work%20with%20ordered%20list%0A%0A%20%20This%20is%20a%20second%20paragraph%0A%0A-%20Works%20with%20unordered%20list%0A%0A%20%20This%20is%20a%20second%20paragraph)

I think you need to read spec, why ordered list requires more spaces in indent. Or you can dig commonmark forum, why such behaviour was done.

If you mean something else - please add more details. Or close issue.

**Comment by puzrin** [comment]
Here is [fixed example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%221.%20Doesn%27t%20work%20with%20ordered%20list%5Cn%5Cn%20%20%20This%20is%20a%20second%20paragraph%5Cn%5Cn-%20Works%20with%20unordered%20list%5Cn%5Cn%20%20This%20is%20a%20second%20paragraph%5Cn%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D), with one more space added.

And reference dingus works the same way.

**Comment by schnerd** [comment]
Makes sense, sorry for the false alarm. Thanks!
