### ISSUE TITLE
supported browser versions

### ISSUE THREAD

**Issue by hyperknot** [markdown-it/markdown-it#316]
I tried figuring out what browser versions are supported by markdown-it, but I couldn't find any information either on the website nor in the Github repository.

Can you clarify what are the exact supported versions, especially Internet Explorer?

**Comment by puzrin** [comment]
Should support all. Very ancient ones - with es5-shim https://github.com/es-shims/es5-shim

**Comment by hyperknot** [comment]
Then please write this somewhere, at least in the README.md. I really took me some time and I still couldn't find this information.

**Comment by puzrin** [comment]
I don't like this idea. Code just works with standard polyfills, but there are no plans to "officially" test old browsers. Also, since code is es5, i see no reasons to write obvious things about polyfills.

**Comment by hyperknot** [comment]
You don't need to test in old ones, just state which ones should work out of the box, without any shims needed. For example IE9+ would be a useful information.

**Comment by puzrin** [comment]
IMHO that's de-facto standard to provide es5 builds for browsers. I don't remember that anyone else asked such things, but if some people will ask again, i'll consider adding this info. Ok?

**Comment by hyperknot** [comment]
Many js libs moved to IE10+ or IE11+ these days and I wanted to know if markdown-it did something similar.
