### ISSUE TITLE
How does html_block `silent` mode work?

### ISSUE THREAD

**Issue by revin** [markdown-it/markdown-it#323]
Hello, I've run into a bit of a puzzle and am hoping someone can clarify how the `html_block` rule is intended to work. I have a case where running the rule with `silent` == `true` is returning `false`, yet running the rule normally it returns `true`.

A simplified case of the markdown I'm getting is:

```markdown
### My Heading
<img src="path/to/some/image.png"/>
- item 1
- item 2
- item 3
```

Running the `html_block` rule normally, it returns `true` and considers everything from `<img` to the end of the snippet to be a single HTML block. This makes perfect sense to me.

However, if I run it with `silent` set to `true`, the rule returns `false` because of [`html_block.js#L42`](https://github.com/markdown-it/markdown-it/blob/79244d11483013126ab1eca277e527d2b4f69183/lib/rules_block/html_block.js#L42). This `false` is explicitly specified on [line 19](https://github.com/markdown-it/markdown-it/blob/79244d11483013126ab1eca277e527d2b4f69183/lib/rules_block/html_block.js#L19), so it's got me thinking that 1) maybe I don't understand validation mode properly, or 2) it's simply a bug.

My understanding is that parser rules should return the same value for the same input, regardless of the `silent` parameter, and that `silent` only determines whether the rule modifies the token list in `state`.

Am I missing a bit of context/nuance here? Can someone help me understand what's going on? Thanks!

**Comment by puzrin** [comment]
AFAIK, silent (validation) mode used to check if markup can terminate previous block without empty line. That's used as look-ahead, to detect block end.

See for example https://github.com/markdown-it/markdown-it/blob/8.2.2/lib/rules_block/paragraph.js#L26-L32

**Comment by puzrin** [comment]
Here is [example in online demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22paragraph%20can%20not%20be%20terminated%20by%20image%20tag%5Cn%3Cimg%20src%3D%5C%22path%2Fto%2Fsome%2Fimage.png%5C%22%2F%3E%5Cn%5Cnbut%20can%20be%20terminated%20with%5Cn%3C!--%20comment%20--%3E%5Cnyes%5Cn%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

That's exactly as described in spec.

**Comment by revin** [comment]
Aaaahhhhh, got it, thanks for the clarification! 👍
