### ISSUE TITLE
Table inside of list is rendered incorrectly

### ISSUE THREAD

**Issue by astoilkov** [markdown-it/markdown-it#325]
[Example from markdown-it page](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22-%20list%20item%5Cn%20%20%20%20%5Cn%20%20%20%20%7C%20Col1%20%20%7C%20Col2%20%7C%5Cn%20%20%20%20%7C%20-----%20%7C%20----%20%7C%5Cn%20%20%20%20%7C%20Col1%20%20%7C%20Col2%20%7C%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

```markdown
- list item
    
    | Col1  | Col2 |
    | ----- | ---- |
    | Col1  | Col2 |
```

![image](https://cloud.githubusercontent.com/assets/884810/22014640/51c51bf2-dca7-11e6-91d7-ed25a961e3c7.png)

**Comment by puzrin** [comment]
Good catch. Probably a bug.

Works with [2-space indent](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22-%20list%20item%5Cn%20%20%20%20%5Cn%20%20%7C%20Col1%20%20%7C%20Col2%20%7C%5Cn%20%20%7C%20-----%20%7C%20----%20%7C%5Cn%20%20%7C%20Col1%20%20%7C%20Col2%20%7C%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D), but doesn't work with 3 & 4.

@rlidwka what do you think?

**Comment by puzrin** [comment]
Also table [overrides indented code block](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%7C%20Col1%20%20%7C%20Col2%20%7C%5Cn%20%20%20%20%20%20%20%20%20%20%20%7C%20-----%20%7C%20----%20%7C%5Cn%20%20%20%20%20%20%20%20%20%20%20%7C%20Col1%20%20%7C%20Col2%20%7C%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D) by unknown reasons

**Comment by puzrin** [comment]
Ah, that's a result of attempt to support ["unbordered" tables](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22Col1%20%20%7C%20Col2%20%5Cn-----%20%7C%20----%20%5CnCol1%20%20%7C%20Col2%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D):

```
Col1  | Col2 
----- | ---- 
Col1  | Col2
```

I think:

1. Broken indented code blocks should be fixed
2. Starting table cell without `|` pipe should not be empty (seems gihtub behave the same way).

**Comment by rlidwka** [comment]
Fixed, thanks for reporting.
