### ISSUE TITLE
Difference to commonmark with tight list and fence

### ISSUE THREAD

**Issue by alinex** [markdown-it/markdown-it#329]
I found that the following code is interpreted differently in common mark and markdown-it:

~~~
   - a
     > b
     ```
     c
     ```
   - d
~~~
While common mark will interpret it as tight list with a fenced code block markdown-it will issue an inline code element instead. Is this a bug or intended this way?

[markdown-it demo](http://markdown-it.github.io/#md3=%7B%22source%22%3A%22%20%20%20-%20a%5Cn%20%20%20%20%20%3E%20b%5Cn%20%20%20%20%20%60%60%60%5Cn%20%20%20%20%20c%5Cn%20%20%20%20%20%60%60%60%5Cn%20%20%20-%20d%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D)
[commonmark demo](http://spec.commonmark.org/dingus/?text=%20%20%20-%20a%0A%20%20%20%20%20%3E%20b%0A%20%20%20%20%20%60%60%60%0A%20%20%20%20%20c%0A%20%20%20%20%20%60%60%60%0A%20%20%20-%20d%0A)

**Comment by puzrin** [comment]
That's not indended, markdown-it pass all 0.27 spec tests and we resync with latest spec from time to time.

Need to check what'up. Thanks for report.

**Comment by rlidwka** [comment]
> Is this a bug or intended this way?

Definitely a bug (blockquotes inside indented lists hadn't been terminated correctly).

Thanks for reporting!
