### ISSUE TITLE
Docs don't mention how to turn off HTMLEntity replacement

### ISSUE THREAD

**Issue by Pomax** [markdown-it/markdown-it#330]
I cannot seem to find any information that lets me turn off HTMLentity replacement. I have some MD that needs to be rendered to HTML but with `&` kep the way it is, not replaced with `&amp;, and `"` kept the way it is, not replaced with `&quot;`, etc.

Which option is used for this, and can this be added to the README.md in the section that covers most of the common config options?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it#manage-rules

Do you need `.disable('entity')` or something else?

**Comment by Pomax** [comment]
A `.disable('entity')` in line with link, image, etc. would be perfect.

**Comment by puzrin** [comment]
`.disable([ 'entity', 'link', 'image' ])` ?

https://github.com/markdown-it/markdown-it/tree/master/lib/rules_inline you can disable any rules you wish, wish some exceptions like paragraph. Or use `zero` preset (`let md = require('markdown-it')('zero')`) and enable rules you need.

For advanced use i'd recommend to read `./doc` folder and inspect src directories. Readme is already big enougth, and contains info about basic use and what to read next.

**Comment by Pomax** [comment]
That is not how I experience a readme. The README.md contains all the information that I as developer need to get my job done, and anything not in the README.md is not intended for reading. That's kind of in the name.  A whole bunch of the "API documentation" is just the README.md  repeated, and makes it really hard to find the information I'm looking for, so in thise case I would absolutely recommend putting this in the README.md : it's basic information, and deserves mention alongside link and image.

**Comment by puzrin** [comment]
@Pomax i don't like floating issues about docs, and discuss theories about miking ideal readme. Such changes should be suggested via PR and discussed there. If your technical issues are solved - let's close this issue. If not - clarify technical details.

**Comment by Pomax** [comment]
It's your repo - I won't be filing a PR because I have no idea how you run the docs side of things - issues as far as I'm used to are where discussions happen until a PR can be written, so since you don't feel the same about issues, and since I have no idea what PR to write, I'll just close this issue as probably unresolved until someone else finds it.

**Comment by puzrin** [comment]
Ok. I know exactly, that have no resources to rework docs in near and far future, so prefer to avoid endless issues. But if someone decides to spend time for docs improve - i'm ready to answer any technical questions.
