### ISSUE TITLE
Missing paragraph tag inside nested lists

### ISSUE THREAD

**Issue by johncja** [markdown-it/markdown-it#331]
Typically, I use empty lines in lists. This allows me to have multiple paragraphs in each list item:

```
foo

- Item 1

  Item 1 cont

- Item 2

  Item 2 cont

bar
```

Sometimes I create nested lists. And I faced with, probably, a bug. If nested list include only one item, and this item have only one paragraph, rendering would be incorrect. Here are examples.

**Example 1.** It's all OK

```
Foo

- Item 1

  - Item 1.1

  - Item 1.2

- Item 3

Bar

--------

Foo

1. Item 1

   1. Item 1.1

   2. Item 1.2

2. Item 2

Bar
```

Each paragraph of text placed inside `<p>` tag:

![li2](https://cloud.githubusercontent.com/assets/18004961/23030832/021bf1e8-f480-11e6-8bd1-c5cf2e912641.png)

**Example 2.** Here is incorrect rendering :

```
Foo

- Item 1

  - Item 1.1

- Item 2

Bar

--------

Foo

1. Item 1

   1. Item 1.1

2. Item 2

Bar
```

In nested lists, paragraphs placed directly inside `<li>` tag. In other words, `<p>` tag is missing :

![li](https://cloud.githubusercontent.com/assets/18004961/23030513/14293bb2-f47f-11e6-8091-8cbe1762701b.png)

**Example 3.** It's all OK again, since nested list item include multiple paragraphs:

```
Foo

- Item 1

  - Item 1.1

    Item 1.1 cont

- Item 2

Bar

--------

Foo

1. Item 1

   1. Item 1.1

      Item 1.1 cont

2. Item 2

Bar
```

![li3](https://cloud.githubusercontent.com/assets/18004961/23031278/735475a0-f481-11e6-9db5-3f1d855c9e60.png)

I also tested these examples in [Commonmark.js dingus](http://spec.commonmark.org/dingus/) and the results are the same. So, I don't sure if it a bug or not.

**Comment by puzrin** [comment]
IMHO everything works as expected (according to commonmark spec, and exactly as reference implementation). At least, that's not bug of this package. I think it worth ask at https://talk.commonmark.org/.

**Comment by puzrin** [comment]
You can force paragraph wrap in list with single item via [fake ref](http://markdown-it.github.io/#md3=%7B%22source%22%3A%22-%20single%20line%5Cn%5Cn%20%20%5Bfake%20ref%5D%3A%20example.com%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D)

```
- single line

  [fake ref]: example.com
```

PS. I know, that's ugly :), just an idea.

**Comment by johncja** [comment]
OK, thank you for answer :-) I think, it really should be asked at Commonmark forum :-)

**Comment by alinex** [comment]
This is based on the possibility to usr two ways of lists in common mark. The loose lists contains additional paragraphs within and so has visually more separation between each. But the tight lists won't have this.

Problem here is that the decission of type us done for each list independly while you want the sublists of the identical type.

As statet above this is based in common mark and has to be duscussed there. But you may fix the visual output through your style sheet.

**Comment by windmaomao** [comment]
What seems strange to me is that `<p>` tag is generated based on different cases. Ex.

```
  - ABC [abc](http://abc)
```

The above generated a paragraph inside `<li>` for me, I don't know if this is the core or any plugin which caused it.
