### ISSUE TITLE
The way for simple local use

### ISSUE THREAD

**Issue by johncja** [markdown-it/markdown-it#332]
I know Vitaly doesn't have enough time to answer such questions, but I still hope someone could help with it.

Also, to avoid ambiguity, I should make a note, that markdown-it really cool (the best parser from my point of view). All problems, described below, are consequence of *my own lack of skills*.

---

I want to use markdown-it for my local text files. That's how I use it:

*(It is slightly modified version. In real life, I just have Chrome extension, then open any md-file, and all additional markup, CSS and scripts added automatically).*

    <xmp id="markdown" style="display: none;">
    # Heading 1

    ::: warning
    **Lorem ipsum** dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
    et dolore magna aliqua.
    :::

    > Blockquote goes here

    ```
    <div>
      Fenced code block goes here
    </div>
    ```

    End of document
    </xmp>
    <div id="result"></div>

    <script src="markdown-it.js"></script>
    <script src="markdown-it-container.js"></script>
    <script src="markdown-it-footnote.js"></script>

    <script>
    var xmp = document.querySelector('xmp#markdown');
    var mdText = xmp.innerHTML; // Take the content in xmp#markdown as input

    var md = window.markdownit({
        html:         true,
        breaks:       true,
        linkify:      true
    })
        .use(markdownitContainer, 'warning')
        .use(markdownitFootnote);

    // Render the xmp#markdown content as HTML
    document.querySelector('#result').innerHTML = md.render(mdText);
    </script>

    <style>
    .warning { background-color: gold; }
    </style>

But, there is a problem: I cannot add `xmp` code block in document. This will broke it:

    ```
    <xmp>
    foo
    </xmp>
    ```

Yes, `xmp` tag is deprecated, and also it cannot contain another `xmp` tag. I tried to use `textarea` and `div` as top-level container (see below), but it still doesn't work properly - sometimes html/xml code blocks rendered incorrectly, and in other cases, I get incorrectly rendered blockquotes.

    <div id="markdown" style="display: none;">
    # Heading 1

    ``` html
    <div>
      Sometimes fail is here
    </div>
    ```

    > And sometimes here

    End of document
    </div>

And `textarea` could not contain `textarea`:

    <textarea id="markdown" style="display: none;">
    # Heading 1

    ```
    <textarea>
    fail
    </textarea>
    ```

    End of document
    </textarea>

I'm not a pro at JavaScript, just a novice, If someone could help me to improve my first snippet, I would be very thankful. Also, I think it would be very useful for a lot of newcomers, who like markdown-it, but failing to "cook it" for simple home use.

**Comment by ucev** [comment]
Maybe you can you `<script type="text/html" id="markdown"></script>` tag to replace `<xmp></xml>` tag, and put your MD contents in the `script` tag. Others goes the same as your original code.

**Comment by puzrin** [comment]
@johncja please avoid using tracker for generic programming questions. Also, use https://markdown-it.github.io/ for examples.

The most common error is that people miss empty line before/after raw html blocks
