### ISSUE TITLE
Softbreak rendering in CJK languanges

### ISSUE THREAD

**Issue by episodeyang** [markdown-it/markdown-it#334]
Hey Puzrin!

I finally managed to find the time to write a `markdown-it` token to `react` renderer! Using react made the rendering much much faster b/c it doesn't refresh the DOM, and it allows me to extend it on top of the solid foundation provided by your work :D So first of all, thanks a bunch for this fantastic project! You can take a look at the work here: www.episodeyang.com/gittor/

My question is: what is a proper way to handle the softbreaks in a mixed-languange environment? 

similar problem and discussions can be found here: 
1. [on Atom editor](https://github.com/atom/atom/issues/9447), 
2. [discussion from commonmark spec](https://talk.commonmark.org/t/soft-line-breaks-should-not-introduce-spaces/285/5) 

and

3. [wikipedia page for language-specifics on softbreak handling](https://en.wikipedia.org/wiki/Line_wrap_and_word_wrap#Word_wrapping_in_text_containing_Chinese.2C_Japanese.2C_and_Korean)

4. [line breaking rules in East Asian Languages](
https://en.wikipedia.org/wiki/Line_breaking_rules_in_East_Asian_languages)

Should this be done on the parser level or the renderer level?

A proper heuristics is: 

- if both the last character of a line and the first character of the next line is CJK then softbreak should be rendered as nothing. 
- if either is not CJK, then softbreak should be rendered as space.

Here is relevant discussion in pandoc. This heuristics corresponds to the `linebreak smart` option. [Linebreak handling control](https://github.com/jgm/pandoc/pull/534)

**Comment by puzrin** [comment]
Hi @episodeyang . Thanks for info. I think this topic is better for CM forum, because i'm not experienced with languages and try to be focused on implementation here.

But... if been close to real world... nobody can prohibit you to implement this via plugin for markdown-it, until people decide if this can be a part of spec or not :). You can put your plugin on the end of `core` chain, scan inlines and cleanup softbreak tokens when your condition found.

Also, there is similar CJK-related issue in `linkify-it` https://github.com/markdown-it/linkify-it/issues/15. If you have a time - add your thoughts please.

**Comment by episodeyang** [comment]
I just took a look at #15 and my head exploded. In Chinese quora, there were a few quite heated discussion on the correct Chinese typographic rules with sophisticated explainations and reasoning. I will learn more when it is more relavant to this propblem. 

> But... if been close to real world... nobody can prohibit you to implement this via plugin for markdown-it, until people decide if this can be a part of spec or not :). 

Yes!! I just became familiar with the parsing mechanisms! I will come back to visit this again at some point and bug you with questions :)

In fact, my math parsing logic is quite interesting (closing deliminator depends on the open deliminator and bose uses regex)

I have a question for you in terms of end of line handling for inline deliminators. I will post it tomorrow maybe.

**Comment by puzrin** [comment]
No problem. Feel free to create new issues. Take a look at last arrays in https://github.com/markdown-it/markdown-it/blob/8.3.0/lib/parser_block.js#L15-L25. Those are called in "verify" mode to detect if existing block should be terminated.

Can we close this issue? I agree that situation with CJK should be improved, but there are no enougth info right now for "official" update here.

**Comment by episodeyang** [comment]
Yes thanks! Let's close this one for now. I will comment for reopen if new information arises.

**Comment by puzrin** [comment]
Closing:

1. Need more "official" and formal spec before implementation.
2. Good links for discussions available in first post (we avoid spec discussions here).

Until more formal logic available, this can be implemented via plugins.

**Comment by episodeyang** [comment]
John Farlane came back with some details. Just like you said, they implemented the logic as a parser extention: https://github.com/jgm/pandoc/commit/44120ea7165546152af88fd442c52ab0f201052e

CMD discussion: https://talk.commonmark.org/t/soft-line-breaks-should-not-introduce-spaces/285/8?u=episodeyang

CJK typesetting rules: https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.en.md#place-one-space-before--after-english-words

I will add these to the top of the issue. This can be kept closed.

**Comment by h404bi** [comment]
Looks like there is no further progress, is there any workaround or implemented plugin till now?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it-cjk-breaks

@episodeyang thanks for summary.
