### ISSUE TITLE
Replacing the content within a block

### ISSUE THREAD

**Issue by donbader** [markdown-it/markdown-it#335]
Hello,
I'm writing a calendar plugin with my self-designed syntax.

And what I want to do is to replace the content between open and close tokens.
for example:
```html
<div class="calendar">
.....
</div>
```

I have extracted the information from user's markdown.
and all I want to do is to re-render the html to a whole new one from the information.

I've figured out a way to do this, but I think it's not pretty good:
#### while rendering `calendar_open`
```javascript
return self.renderToken(tokens, idx, _options, env, self) + '<!-- '
```
#### while rendering `calendar_close`
```javascript
return '-->' + self.renderToken(tokens, idx, _options, env, self)
```

What I've done is just commenting out the content between it.
Is there any better solution ?
Thanks a lot!

**Comment by puzrin** [comment]
I don't think it's a good idea to use HTML in such way. I would use fenced block with special name (calendar), or https://github.com/markdown-it/markdown-it-container if nested content required.

Then you can extend fenced block renderer to do what you need (see [examples](https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer)).

**Comment by donbader** [comment]
Oh.. 
```html
<div class="calendar">
.....
</div>
```
This one I mentioned is already rendered. 

The syntax I designed is:
```
@[calendar]
(1):
-(2:00, Sleep) I have to sleep
(15):
...
@[/calendar]
```

And I'm asking that if there is a way to replace the content between open and close tokens.
The following code is what I thought now:
```javascript
  function renderDefault(tokens, idx, _options, env, self) {
    if (tokens[idx].nesting === 1) {
      // return: <div class="calendar"> <!--
      tokens[idx].attrPush(['class', name]);
      var token_html = self.renderToken(tokens, idx, _options, env, self);
      return token_html + '<!-- '
    }
    else if (tokens[idx].nesting === -1){
      // return: --> xxx(Calendar's new content)xxx  <div>
      newHTML = new Calendar(tokens[idx].info).html()
      var token_html = self.renderToken(tokens, idx, _options, env, self);
      return ' --> ' + newHTML + token_html
    }
  }
```

**Comment by puzrin** [comment]
If calendar content has no markdown, i would create a single new token type for it (see what fenced code block does), and would add a separate named renderer method for it.

But, in general, everything that wortks for you is ok and secure enougth, until you avoid html tags use (those are disabled by default).

**Comment by donbader** [comment]
I think I'll create a new token type for it.

Thank you very much for helping!
