### ISSUE TITLE
source index in token array (sourcemapping?)

### ISSUE THREAD

**Issue by episodeyang** [markdown-it/markdown-it#336]
Hi Puzrin, 

I want to be able to keep track of which segment of source text is responsible for a particular piece of token. Would it be possible to contain such information in the token array?

I'm not sure if this is the same as source map #73. 

from my read of the library source, it looks like if I just save a field `sourceIndex: [state.pos, state.pos + count]` then it would allow me to do so. This has to be done for all tokens.

Best, 
Ge

**Comment by puzrin** [comment]
Currently only line numbers are tracked (you can implement sync scroll as in demo, but can not implement copy-paste from generated html back to markdown). Adding columns track requires serious internal data rework, and there are no plans for nearest future.

This repo was created to collect info in background: https://github.com/markdown-it/markdown-ast-spec

**Comment by puzrin** [comment]
Close - added more direct mentioning to dev memo #125 (common place to bury such things).

PS. There are no markdown parser with full sourcemap support.

PPS. I need this feature for my forum, and will implement it... sometime... when have no more important things to do...

**Comment by digitalmoksha** [comment]
@episodeyang, the [remark](https://github.com/wooorm/remark) parser by @wooorm provides enough source information to enable syntax highlighting.  I currently use it specifically for this, and markdown-it for the final rendering.  Both are great projects.

**Comment by puzrin** [comment]
Wow, did @wooorm really solved that non trival source mapping problem? That sounds very impressing.
@digitalmoksha could you comment why you still use both?

**Comment by digitalmoksha** [comment]
Full commonmark compliance is important to me for rendering, and I already used several plugins for markdown-it.  I just haven't had the time to verify that remark is fully compliant and replace all the plugins.  However being able to syntax highlight the source was incredibly important, and remark allowed me to accomplish it.  When I have time, I will probably do the work to try to shift everything over to remark, because I find it wasteful to be using two different libraries.

That said, I still think it would be a great addition to have source mapping in  markdown-it, though I know it's a hard problem.  And it would keep me from shifting...

I've been impressed with the functionality and support of both libraries.

**Comment by wooorm** [comment]
It’s an interesting question! I wasn’t asked for my thoughts, but I couldn’t resist voicing them anyway! :)

>  I just haven't had the time to verify that remark is fully compliant

remark is not, unfortunately, commonmark compliant.

> replace all the plugins

There’s a lot of markdown-it plugins, and quite some remark plugins too. But I think the main reason to use markdown-it and its plugins is that the plugins add support for many markdown extensions. remark’s plugins focus more on inspecting markdown (e.g., linting) and transforming markdown (e.g., `[foo](bar)` > `[foo][1]\n[1]: bar`).

I think, aside from commonmark, that that’s the main difference between markdown-it and remark.

**Comment by puzrin** [comment]
@wooorm you are always welcome here. Designing good markdown parser that can "do everything" is too complex thing to be done with one person. Me and @rlidwka were focused on speed / extensions / cm spec, and had to drop source maps for a while. Now markdown-it reached limits of rurrent architecture and needs rework.

The most difficult thing for me is to design lossless AST and a convenient API to iterate and apply transforms.

**Comment by digitalmoksha** [comment]
> remark is not, unfortunately, commonmark compliant

Well you do have the `commonmark` configuration option, which I use, but I got the impression it wasn't 100%.  But it works well enough for my syntax highlighting

Then I guess for now I'm doing the right thing.

> remark’s plugins focus more on inspecting markdown (e.g., linting) and transforming markdown (e.g., [foo](bar) > [foo][1]\n[1]: bar)

Hmm, I wonder if applying the syntax highlight codes could be made into a remark plugin...

**Comment by wooorm** [comment]
> @wooorm you are always welcome here. Designing good markdown parser that can "do everything" is too complex thing to be done by one person. Me and @rlidwka were focused on speed / extensions / cm spec, and had to drop source maps for a while. Now markdown-it reached limits of current architecture and needs rework.

Cheers, thanks! Yeah, it’s lots of work... My focus was on the syntax tree, positional info, inspecting and mutating those trees — ignoring complete commonmark support. I’m also now noticing that I need a rewrite of the parser to enable complete commonmark support... 

> The most difficult thing for me is to design lossless AST

Could you expand on that? What do you see as a lossless AST? Why is that needed?

@digitalmoksha

> Well you do have the commonmark configuration option, which I use, but I got the impression it wasn't 100%. But it works well enough for my syntax highlighting

Correct, it’s unfortunately not perfect, but it’s okay!

> Hmm, I wonder if applying the syntax highlight codes could be made into a remark plugin...

Maybe? Let’s talk about that on [Gitter](https://gitter.im/wooorm/remark).

**Comment by puzrin** [comment]
> Could you expand on that? What do you see as a lossless AST? Why is that needed?

Something, created after source parse, that allows to generate back _exactly the same_ source.

> I’m also now noticing that I need a rewrite of the parser to enable complete commonmark support...

I think we go to the same result via different ways (because we had different initial priorities). I don't know are you interested to write code together. But at least we could collaborate to create a good data design/flow.

I've created https://github.com/markdown-it/markdown-ast-spec to collect info and describe goals. Join if you wish. Or, if you have better ideas - let me know.

**Comment by episodeyang** [comment]
It would be really great if we can have source map support with  markdownit. Common mark spec has caveats, but it is a good spec and a common denominator. 

I'm also really invested in markdownit already.

**Comment by puzrin** [comment]
@episodeyang i've filled most of edge cases (from my point of view) in spec repo. Those may seems too technical or difficult to understand, because expect that you understand parser's background in details. But you can ask your questions anytime if you decide to participate.

**Comment by episodeyang** [comment]
I have taken a quick look at the edge cases (apologies if I had written too much and was off-topic sometimes. If I had more time I would have written less!)

In general I think:
1. incremental parse is not a requirement. 
    1. A depth-limiter with limit-tokens is good enough.
    2. diff-patch should be done in the renderer or by the user of the AST
    3. html update (repaint) is always going to be the bottleneck, parsing is not. Unless you talk directly to the DOM instead of generate a HTML string. If a user (or your renderer) is advanced enough to care about performance at all, it should care about repaint time, and it **should** use a differential DOM rendering step. Most likely the user should be using either 
          1. a home-brew diff renderer, in which case it should use established 3rd party algo
          2. **or** use a modern framework with shadow-dom like react or angular2. 
    in both cases markdonw-it doesn't need to do these things.

2. You might want to incrementally add the source info inside the 2-level array instead of drastically change the AST syntax. As an end user current AST and good and capable enough that I don't really need a full-rewrite just for that.
    - lot of the plug-ins don't and won't take advantage of these new features. 
    - Do you want to allow existing plug-ins to work?
    - if you want them to continue to work, how to make sure the authors comply with the new source-map features? 
       - I think a warning is good enough.
    - if you don't want existing plugins to work, why so?

3. fast definition list look up might warrant a tree-like AST, but again, looping through the AST to get these info is not that slow, and much faster than `repaint` already. This is not currently a bottle neck.
    - you probably do want to make sure the error is informative when conflicting definitions are found.

**Comment by episodeyang** [comment]
A potential solution is just:
```
AST:
<bullet-list-open toke-content="-   ">
<inline>list content blah blah blah</inline>
<bullet-list-close token-content="↩">
```

**Comment by tejasvi** [comment]
[commonmark.js](https://github.com/commonmark/commonmark.js/) now provides character level `Node.sourcepos`. Alas tables aren't yet "official".

**Comment by puzrin** [comment]
@tejasvi 

> commonmark.js now provides character level Node.sourcepos.

Could you provide proof of useable column info?

**Comment by tejasvi** [comment]
@puzrin I am building a WYSIWYG markdown editor where character level source mapping is useful. The alternative is regex with missed edge cases. On top of that I wish for incremental parsing which can handle editing _huge_ markdown files. [This article](https://ui.toast.com/weekly-pick/en_20200402) expresses the use case in detail though the proposed ToastMark is very much alpha right now.

**Comment by puzrin** [comment]
1. Full source mapping (with columns) requires AST design. That's non trivial task.
2. Huge files still can be operated with partial re-parse, if you split those by blocks. That's not easy, but possible (more realistic than AST design without bugs).
