### ISSUE TITLE
list item renders as quote

### ISSUE THREAD

**Issue by erusev** [markdown-it/markdown-it#338]
```
1. First item
    > Nested quote
2. Second item
```

renders as:

![image](https://cloud.githubusercontent.com/assets/184170/23590106/b2ee00a0-01e2-11e7-8f86-d919830e2f8d.png)

"second item" should render as a list item

**Comment by puzrin** [comment]
[Works as expected](http://spec.commonmark.org/dingus/?text=1.%20First%20item%0A%20%20%20%20%3E%20Nested%20quote%0A2.%20Second%20item). See commonmark spec.

**Comment by puzrin** [comment]
Ups, sorry, misunderstood. That's a bug.

**Comment by rlidwka** [comment]
Fixed, thanks!
