### ISSUE TITLE
It shall not interprete the angle brackets inside coding block

### ISSUE THREAD

**Issue by greenlaw110** [markdown-it/markdown-it#342]
The raw source:

![image](https://cloud.githubusercontent.com/assets/216930/23886020/a4d3958a-08cb-11e7-9a4a-ae179f0cb1a0.png)

The presentation on GitHub
![image](https://cloud.githubusercontent.com/assets/216930/23886061/e593e4a8-08cb-11e7-94ad-e937e65fdd16.png)

The presentation interpretated by markdown-it.js

![image](https://cloud.githubusercontent.com/assets/216930/23886042/cc443ad4-08cb-11e7-8104-cfc53302b579.png)

**Comment by puzrin** [comment]
Can not reproduce. Please, show example in demo https://markdown-it.github.io/

**Comment by greenlaw110** [comment]
Sorry it was my problem. If I remove `highlight` part from the configuration shown below it will be all good.
![image](https://cloud.githubusercontent.com/assets/216930/23896315/102775d2-08fd-11e7-8777-404b22f14680.png)

However I need it to hightlight the syntax. Still wondering where I am wrong ...

**Comment by greenlaw110** [comment]
Okay I endup with replacing prism with hilight js and the issue is gone
