### ISSUE TITLE
Howto disable fuzzyLink in linkify

### ISSUE THREAD

**Issue by alinex** [markdown-it/markdown-it#344]
The linkify-it package has the ability to deactivate such things like the fuzzyLink but use the rest. Is it possible to setup markdown.it with fuzzyLink disabled?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/8.3.1/lib/index.js#L290

```js
const md = require('markdown-it');
md.linkify.set(...)
```
