### ISSUE TITLE
HTML Comment Tags

### ISSUE THREAD

**Issue by Ratstail91** [markdown-it/markdown-it#345]
Hi, I'm using markdown-toc, which produces comments like this:

    
    

I've noticed that markdown-it doesn't ignore these or convert them into HTML comments when embedded into markdown. Is there a way this feature could be added? Thanks in advance.

**Comment by johncja** [comment]
I doesn't tested, but here is an extension for it: https://github.com/jay-hodgson/markdown-it-inline-comments

**Comment by Ratstail91** [comment]
Thank you for the fast response. I'll test this tonight.
