### ISSUE TITLE
Question: How to properly insert rules.

### ISSUE THREAD

**Issue by goessner** [markdown-it/markdown-it#346]
When properly inserting custom inline or block rules using `after` or `before` in list of existing rules, won't I need to know the list of current rules ?

Are there some general rules von doing this?

thanks

**Comment by ucev** [comment]
see here: [api](https://markdown-it.github.io/markdown-it/#Ruler)
and read source files under [lib/rules_block](https://github.com/markdown-it/markdown-it/tree/master/lib/rules_block)  etc.
I know where it is but i don't have enough to read it through though.

**Comment by puzrin** [comment]
@goessner you may rely on default rule names (from this repo), that's usually enougth to insert your modifications with desired priority. Or just add to the end if you have no preferences.

**Comment by goessner** [comment]
yes, thanks. I pragmatically start to work with `ruler.push`.

**Comment by puzrin** [comment]
Ahh... seems block rules should go before last one (paragraph). Anyway, there are no universal answer.

**Comment by goessner** [comment]
ok .. setting block rule before `paragraph` for now .. thanks.

**Comment by jdalrymple** [comment]
This is closed, but it seemed silly to open a new issue if i just wanted some clarification. @puzrin Is there a reason why block rules should go before the paragraph rule? I did try adding one after and it didnt get run. Is this a limitation in the code, or was it on purpose?

Thanks!

**Comment by puzrin** [comment]
That's by design. paragraph = everything not matched. So it should go after all other checks.

**Comment by jdalrymple** [comment]
Alrighty, Ill make a PR to add that to the docs!
