### ISSUE TITLE
Interesting comparison with syntax high-light parsing in Atom

### ISSUE THREAD

**Issue by episodeyang** [markdown-it/markdown-it#347]
Hey @puzrin 

I was doing some research on Atom when I saw this script. Is it possible to have all of the grammer captured this way, and what do you think of their approach in parsing/source map making?

https://github.com/atom/language-gfm/blob/master/grammars/gfm.cson

**Comment by puzrin** [comment]
This question is better for comminmark forum.

Markdown is a collection of assorted kludges by design. AFAIK, it's not describable by BNF notation. Your example has no major difference.
