### ISSUE TITLE
Cant use Markdown-it

### ISSUE THREAD

**Issue by reyesrico** [markdown-it/markdown-it#348]
I just have installed markdown-it using:
npm install --save markdown-it

Then inside the .tsx I have:
import * as MarkdownIt from 'markdown-it';
const result = MarkdownIt().render(src);

Can't build the code:
ERROR in ./-/entities/maps/entities.json
Module parse failed: C:\...\node_modules\entities\maps\entities.json Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:9)
@ ./-/markdown-it/lib/common/entities.js 6:17-55

**Comment by puzrin** [comment]
This question doesn't seems to be related to this repo. Code works as needed and all commits are tested on travis.
