### ISSUE TITLE
Trailing "new line" character

### ISSUE THREAD

**Issue by danielcobo** [markdown-it/markdown-it#349]
```node
var md = require('markdown-it')();
var result = md.render('# markdown-it rulezz!'); //"<h1>markdown-it rulezz!</h1>\n"
```
(see working sample above: https://runkit.com/58db86c6eae8b80014630525/58ed4d8b84abae0014060150)

Why is there a trailing `\n` in the result?
The documentation does not seem to specify this.

**Comment by puzrin** [comment]
It's common practice for multiline texts. For example, if you commit text without newline to github, you will see red warning marker at the end in diff. Eslint report missed tailing newline as bug. And so on. You can `.trim()` result if you don't like this.
