### ISSUE TITLE
Emphasis fails if followed by html tag without space

### ISSUE THREAD

**Issue by puzrin** [markdown-it/markdown-it#35]
__Bad:__

https://markdown-it.github.io/#md64=eyJzb3VyY2UiOiJhbiAqKig6Kio8YnI+IiwiZGVmYXVsdHMiOnsiaHRtbCI6ZmFsc2UsInhodG1sT3V0IjpmYWxzZSwiYnJlYWtzIjpmYWxzZSwibGFuZ1ByZWZpeCI6Imxhbmd1YWdlLSIsImxpbmtpZnkiOnRydWUsInR5cG9ncmFwaGVyIjp0cnVlLCJfaGlnaGxpZ2h0Ijp0cnVlLCJfc3RyaWN0Ijp0cnVlLCJfdmlldyI6InNyYyJ9fQ==

__Reference__

http://spec.commonmark.org/dingus.html?text=an%20**%28:**%3Cbr%3E

Probably, spec error, because <> are not punctuation chars.

**Comment by svbergerem** [comment]
`<` and `>` are punctuation chars according to the spec: http://spec.commonmark.org/0.15/#ascii-punctuation-character

**Comment by puzrin** [comment]
Yea, i've missed, that markdown punctuation includes some chars, not existing in unicode punctuation.

https://github.com/markdown-it/markdown-it/commit/c2312d971fb7a65b4d9ffa8d8edf48271ab6876f

**Comment by puzrin** [comment]
Fixed in 3.0.3
