### ISSUE TITLE
Empty line in script tag parsed like code block

### ISSUE THREAD

**Issue by Akurganow** [markdown-it/markdown-it#350]
This will work if script tag placed inside another tag like `div`

Source:
```html
<div>
  <script type="text/javascript">
    var someVar = 0;

    function someFunc(variable) {
      return variable
    };
  </script>
</div>
```

Result:
```html
<div>
  <script type="text/javascript">
    var someVar = 0;
<pre><code>function someFunc(variable) {
  return variable
};
</code></pre>
  </script>
</div>
```

**Comment by puzrin** [comment]
Works as described in spec. http://spec.commonmark.org/0.27/#html-blocks

Remove empty line to fix.

**Comment by puzrin** [comment]
[example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Cdiv%3E%5Cn%20%20%3Cscript%20type%3D%5C%22text%2Fjavascript%5C%22%3E%5Cn%20%20%20%20var%20someVar%20%3D%200%3B%5Cn%20%20%20%20function%20someFunc%28variable%29%20%7B%5Cn%20%20%20%20%20%20return%20variable%5Cn%20%20%20%20%7D%3B%5Cn%20%20%3C%2Fscript%3E%5Cn%3C%2Fdiv%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D)

**Comment by Akurganow** [comment]
But in [this example](http://spec.commonmark.org/0.27/#example-136) empty line inside script tag stay empty line

HTML tags inside script tag looks like a bug, there are no situations where it might be the right behavior

**Comment by puzrin** [comment]
There are special cases for `script` & `style` tags. You question is not related to markdown-it anyhow. All those things are described in commonmark spec.
