### ISSUE TITLE
Why are references required?

### ISSUE THREAD

**Issue by martinheidegger** [markdown-it/markdown-it#351]
I just used `.parse` like this:

```javascript
const md = new MarkdownIt()
const tokens = md.parse('# Hi!\n\n Fully test [hello], [hosy](http://google.com) ')
```

and it showed this nice error:

```
not ok Cannot read property 'references' of undefined
    stack: |
      Array.link (node_modules/markdown-it/lib/rules_inline/link.js:101:25)
      ParserInline.tokenize (node_modules/markdown-it/lib/parser_inline.js:135:22)
      ParserInline.parse (node_modules/markdown-it/lib/parser_inline.js:163:8)
      Array.inline (node_modules/markdown-it/lib/rules_core/inline.js:10:23)
      Core.process (node_modules/markdown-it/lib/parser_core.js:51:13)
      MarkdownIt.parse (node_modules/markdown-it/lib/index.js:523:13)
      index.js:43:23
      module.exports (index.js:41:10)
      Test.<anonymous> (test/index.js:5:10)
    at:
      line: 101
      column: 25
      file: node_modules/markdown-it/lib/rules_inline/link.js
      function: Array.link
    type: TypeError
    test: simple
    source: |
      if (typeof state.env.references === 'undefined') { return false; }
```

which kindly disappears if you pass in `references: {}` 

```javascript
const md = new MarkdownIt()
const tokens = md.parse('# Hi!\n\n Fully test [hello], [hosy](http://google.com) ', {references: {}})
```

Why is this necessary? Couldn't an error be shown more clearly? Should there be a document that explains that? _Couldn't find one ... :blush:_

**Comment by puzrin** [comment]
https://markdown-it.github.io/markdown-it/#MarkdownIt.parse

See API docs. IMHO it has enougth details. Could you explain the sequence, how you found `.parse()` method and decided that second param is optional?

**Comment by martinheidegger** [comment]
@puzrin I have used many parsers (and markdown-it) in the past and remembered the `parse` function but simply didn't remember that `env` is required _(my mistake, totally! :sweat_smile: )_. But it does work with env being `null` or `undefined` until you run into a case like the one mentioned above where it tries to lookup a link.

**Comment by puzrin** [comment]
In 99% users need `.render()`. If someone decide to use low level api, he is expected to understend well what he does (read docs, surf sources and so on). Of cause, mistakes are possible but i think, there are no needs now to add more checks into `.parse()`.

Can we close this or do you have objections?

**Comment by martinheidegger** [comment]
Thanks for taking the time considering my reqyest

**Comment by puzrin** [comment]
I've created label `no consensus` for such issues, to be able revisit potential ideas sometime in future.
