### ISSUE TITLE
render output as json

### ISSUE THREAD

**Issue by jmls** [markdown-it/markdown-it#355]
I'm trying to parse the api markdown of gitlab as get a json representation. From all that I have read about markdown-it, I think it should be more than possible to render jsom, but I can only find examples of how to render html

I have got the token list using `parse` but that is very obviously low-level.  Is there any documentation on what the `map`, `nesting` and `level` properties are on a token ?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/token.js

There are comments in source.

**Comment by lukasoppermann** [comment]
@jmls did you get it to render json? I am looking for a json with just the tags and content. Did you do something like this?

**Comment by simonh1000** [comment]
I need to be able to render as json as well
