### ISSUE TITLE
Highlighted HTML from pygmentize-bundled is not output

### ISSUE THREAD

**Issue by euclio** [markdown-it/markdown-it#36]
Code that reproduces the problem:

```javascript
var MarkdownIt = require('markdown-it');
var pygmentize = require('pygmentize-bundled');

var md = new MarkdownIt({
  html: true,
  linkify: true,
  highlight: function(str, lang) {
    pygmentize({ lang: lang, format: 'html' }, str, function(err, result) {
      return !err ? result.toString() : '';
    });
  }
});

console.log(md.render('```python\n' +
'print("Hello world!")\n' +
'```'));
```

Expected output: HTML with pygmentize spans and classes inside a code block.
Actual output: Plain text inside a code block.

Pygmentize itself returns escaped HTML. Am I missing something here?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it#syntax-highlighting

Hightlighter MUST be sync. For async processing you need to chain manually `parse` + `highlight` + `render`.

**Comment by euclio** [comment]
D'oh! That would make sense. Thanks.
