### ISSUE TITLE
List of Rules for Enabling/Disabling

### ISSUE THREAD

**Issue by cmagnollay** [markdown-it/markdown-it#361]
This is not an issue with the code so much as a question about enabling/disabling rules as explained in the documentation. It shows an example with "link" and "image" rules being enabled, but there does not seem to be a comprehensive list of what rules are available for enabling/disabling nor what they do.

Looking in the source I can find references to the rules, but it is unclear to me how I can tell what some of them do. For example, what does the "text" rule do?

In addition, in the code there are comments discussing enabling "bold" or "italic", but those does not seem to be actual rule names. It seems that "emphasis" is the rule name that enables the bold and italic markdown rules.

I was able to figure out what I needed after some trial and error and by looking through the source, but I was wondering if I missed something and there is indeed somewhere in the documentation that explains the rules.

Thanks!

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/presets/zero.js - here is the minimal rules set that can't be reduced. Everything else can be switched.

Full list of rules can be inspected via [sources](https://github.com/markdown-it/markdown-it/blob/8.3.1/lib/parser_block.js#L15-L25) of `parcer_block.js` / `parcer_inline.js` / `parcer_core.js`

Commonmark has a bit different names for html markup. You can see in difference in spec http://spec.commonmark.org/

**Comment by shi-yan** [comment]
the list should be provided in the document, or at lease the above comment should be in the document.

**Comment by karlitos** [comment]
I would also appreciate better documentation to applicable rules if possible

**Comment by puzrin** [comment]
PR welcome
