### ISSUE TITLE
Symbol with underscores on either side in url breaks linkify

### ISSUE THREAD

**Issue by mattchue** [markdown-it/markdown-it#362]
With this set of sample URLs:
```
https://en.wikipedia.org/wiki/Jesse_Hughes_(musician)#/media/File:Eagles_of_Death_Metal_$_Steel_Blue_Oval_(1_3_2010)_(4416148631).jpg

https://en.wikipedia.org/wiki/Jesse_Hughes_(musician)#/media/File:Eagles_of_Death_Metal_%_Steel_Blue_Oval_(1_3_2010)_(4416148631).jpg

https://en.wikipedia.org/wiki/Jesse_Hughes_(musician)#/media/File:Eagles_of_Death_Metal_@_Steel_Blue_Oval_(1_3_2010)_(4416148631).jpg

https://en.wikipedia.org/wiki/Jesse_Hughes_(musician)#/media/File:Eagles_of_Death_Metal_A_Steel_Blue_Oval_(1_3_2010)_(4416148631).jpg

https://en.wikipedia.org/wiki/Jesse_Hughes_(musician)#/media/File:Eagles_of_Death_Metal_a_Steel_Blue_Oval_(1_3_2010)_(4416148631).jpg

https://en.wikipedia.org/wiki/Jesse_Hughes_(musician)#/media/File:Eagles_of_Death_Metal_1_Steel_Blue_Oval_(1_3_2010)_(4416148631).jpg

https://en.wikipedia.org/wiki/Jesse_Hughes_(musician)#/media/File:Eagles_of_Death_Metal_-_Steel_Blue_Oval_(1_3_2010)_(4416148631).jpg
```
Paste this source into the [markdown-it](https://markdown-it.github.io/) and [linkify-it](http://markdown-it.github.io/linkify-it/) demos. The link breaks when it encounters a symbol in the `markdown-it` demo between two underscores, but does not for the `linkify-it` demo. 

I believe this has something to do with `em` being applied before linkify. I've tried to write a rule to circumvent this behavior, but modifying tokens after they've already been parsed to the needed degree gets pretty messy. Any insight is appreciated.

**Comment by puzrin** [comment]
That's s known issue that can't be fixed. You markup link directly with `<...>` to avoid collision
