### ISSUE TITLE
Fix issues with commonmark spec adherance

### ISSUE THREAD

**Issue by Neaox** [markdown-it/markdown-it#363]
markdown-it fails to meet the following cases in the markdown spec
* [441](http://spec.commonmark.org/0.26/#example-441), [442](http://spec.commonmark.org/0.26/#example-442) - markdown-it switches the em/strong order than that in the spec.
* [465](http://spec.commonmark.org/0.26/#example-465) - markdown-it does not support unescaped `(` and `)` within links.

I will continue to update this issue if I find any more.

**Comment by puzrin** [comment]
You pointed to old spec version (0.26), actual one is 0.27.

Spec tests are included into test pack https://github.com/markdown-it/markdown-it/blob/master/test/commonmark.js

**Comment by Neaox** [comment]
My bad, I did link to the wrong version of the spec. I was running the tests against the latest version of the spec, it was an accident to link to the older spec.

Can I ask why you have your own test suite that is de-synced from the spec? Why not reference the spec package directly (https://www.npmjs.com/package/commonmark-spec) to ensure that you have up to date tests. When a new commonmark spec version is released all you need to do is update the package reference.

The above package is the spec, the tests within it are the standard of spec compliance, so by definition shouldn't markdown-it, when in commonmark mode, pass these tests, no customisation needed?

**Comment by puzrin** [comment]
AFAIK we are in synk with spec https://github.com/markdown-it/markdown-it/tree/master/test/fixtures/commonmark. I don't understand your question. We use files in the way that is convenient for us.

**Comment by Neaox** [comment]
My apologies. I made a massive error, I had accidentally used the github dependency for commonmark-spec (https://github.com/jgm/CommonMark) instead of the `0.72` version on npm, essentially pointing it at master, which has edge changes from 9 days ago which you can't be expected to comply with.

When I created a bare bones project, testing markdown-it against the `0.72` test project, it all seems good.

Sorry for pointing the figure without a thorough investigation first. I will, in future create the bare bones project first to replicate the issue.

Thanks!
