### ISSUE TITLE
Table default style doesn't looks like GFM style.

### ISSUE THREAD

**Issue by jjljyn** [markdown-it/markdown-it#364]
Well, here is the [demo](https://jsfiddle.net/julianjia/6mun7z4p/9/).

This is my table
<img width="739" alt="screenshot" src="https://cloud.githubusercontent.com/assets/16191775/26715289/b9a8436e-47a7-11e7-972f-bb31827986af.png">

This is what I expect

| Left-aligned | Center-aligned | Right-aligned |
| :---         |     :---:      |          ---: |
| git status   | git status     | git status    |
| git diff     | git diff       | git diff      |
| git status   | git status     | git status    |
| git diff     | git diff       | git diff      |

What should I do to configure it and make it looks like GFM?
Did I miss something?

**Comment by svbergerem** [comment]
@jjljyn Use some CSS to change the table style.

**Comment by jjljyn** [comment]
@svbergerem Yeah, thanks. It works. But is there any configuration to control the table style?

**Comment by puzrin** [comment]
@jjljyn there are no any special configuration. Just add CSS styles you need. See [online demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%7C%20Left-aligned%20%7C%20Center-aligned%20%7C%20Right-aligned%20%7C%5Cn%7C%20%3A---%20%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%3A---%3A%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%20%20%20---%3A%20%7C%5Cn%7C%20git%20status%20%20%20%7C%20git%20status%20%20%20%20%20%7C%20git%20status%20%20%20%20%7C%5Cn%7C%20git%20diff%20%20%20%20%20%7C%20git%20diff%20%20%20%20%20%20%20%7C%20git%20diff%20%20%20%20%20%20%7C%5Cn%7C%20git%20status%20%20%20%7C%20git%20status%20%20%20%20%20%7C%20git%20status%20%20%20%20%7C%5Cn%7C%20git%20diff%20%20%20%20%20%7C%20git%20diff%20%20%20%20%20%20%20%7C%20git%20diff%20%20%20%20%20%20%7C%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

**Comment by jjljyn** [comment]
My table works fine and looks nice now.Thank you.
