### ISSUE TITLE
brackets as terminator char .. ?

### ISSUE THREAD

**Issue by goessner** [markdown-it/markdown-it#366]
I understand, that you are only supporting a small set of chars, which can be tokens for performance reasons.

In [text.js](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/text.js) you have them in the comment list, 
```
// !, ", #, $, %, &, ', (, ), *, +, ,, -, ., /, :, ;, <, =, >, ?, @, [, \, ], ^, _, `, {, |, }, or ~
```
but not in the following switch statement.

Latex math uses `\[...\]`  escaped square brackets for block math (works fine) and `\(...\)` escaped brackets for inline math (not recognized). Question: Is it possible to get brackets `(,)` as tokens ?

Thanks

**Comment by puzrin** [comment]
Seems no by default, but it's not difficult to change - you can replace existing `text` rule with your custom one and add `()` skip there.

I don't remember why `()` were not added in the past. But we can do it later, if you succeed with your plugin.

**Comment by puzrin** [comment]
BTW, if you need to work with `\(...\)`, i guess you should stop text scan not on `()` but on `\`. So, you should not have problems at all.

Can we close this?

**Comment by goessner** [comment]
Thanks for your hint. 

Yes, I thought so also .. but it does not work. I patched `md.inline.ruler.at('text', ...)` as you suggested and added 
```
    case 0x28/* ( */:
    case 0x29/* ) */:
```
in the switch statement. This magically doesn't work either. I will add some tests here .. and come back to you then.

I will close this now by myself.

Thanks

**Comment by puzrin** [comment]
> but it does not work

Make sure your rule is inserted BEFORE [escape](https://github.com/markdown-it/markdown-it/blob/8.3.1/lib/parser_inline.js). If it does not work - probably you do something wrong.

**Comment by goessner** [comment]
YES .. exactly this was the golden hint ... works like a charme now :)

**Comment by laygir** [comment]
@goessner do you still have the solution around, would you mind sharing it?
