### ISSUE TITLE
code block to table is right?

### ISSUE THREAD

**Issue by dwatow** [markdown-it/markdown-it#368]
# markdown
    ## Code

    Inline `code`

    Indented code

        // Some comments
        line 1 of code
        line 2 of code
        line 3 of code

    Block code "fences"

    ```
    Sample text here...
    ```

    Syntax highlighting

    ``` js
    var foo = function (bar) {
      return bar++;
    };

    console.log(foo(5));
    ```

# myHTML

    <h2>Code</h2>
    <p>Inline <code>code</code></p>
    <p>Indented code</p>
    <pre><code>// Some comments
    line 1 of code
    line 2 of code
    line 3 of code
    </code></pre>
    <p>Block code &quot;fences&quot;</p>
    <p>
      <figure class="highlight plain">
        <table>
          <tr>
            <td class="gutter"><pre><div class="line">1</div></pre></td>
            <td class="code"><pre><div class="line">Sample text here...</div></pre></td>
          </tr>
        </table>
      </figure>
    </p>
    <p>Syntax highlighting</p>
    <p>
      <figure class="highlight js">
        <table>
          <tr>
            <td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div></pre></td>
            <td class="code"><pre><div class="line"><span class="keyword">var</span> foo = <span class="function"><span class="keyword">function</span> (<span class="params">bar</span>) </span>&#123;</div><div class="line">  <span class="keyword">return</span> bar++;</div><div class="line">&#125;;</div><div class="line"></div><div class="line"><span class="built_in">console</span>.log(foo(<span class="number">5</span>));</div></pre></td>
          </tr>
        </table>
      </figure>
    </p>

# but [demo web](https://markdown-it.github.io/) without table

    <h2>Code</h2>
    <p>Inline <code>code</code></p>
    <p>Indented code</p>
    <pre><code>// Some comments
    line 1 of code
    line 2 of code
    line 3 of code
    </code></pre>
    <p>Block code “fences”</p>
    <pre class="hljs"><code>Sample text here...
    </code></pre>
    <p>Syntax highlighting</p>
    <pre class="hljs language-js"><code><span class="hljs-keyword">var</span> foo = <span class="hljs-function"><span class="hljs-keyword">function</span> (<span class="hljs-params">bar</span>) </span>{
    <span class="hljs-keyword">return</span> bar++;
    };

    <span class="hljs-built_in">console</span>.log(foo(<span class="hljs-number">5</span>));
    </code></pre>

**Comment by dwatow** [comment]
this question become from "hexo util"

**Comment by dimaslanjaka** [comment]
hmm [https://github.com/hexojs/hexo-util](https://github.com/hexojs/hexo-util)

**Comment by dimaslanjaka** [comment]
```yaml
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: false # <--- problem
  hljs: false
```

DONE
