### ISSUE TITLE
integrating in ng2

### ISSUE THREAD

**Issue by VinzentE** [markdown-it/markdown-it#373]
Any idea if that is "an easy thing" or if it is somehow not possible? Are there any showstoppers?
So far we are running into several issues...

We'd love to use the rich framework of markdown-it with several already created markdown-it plugins in our own editor, which we want to build with ng2.

Any ideas / thought highly appreciated.

Thanks

**Comment by puzrin** [comment]
I'm not familiar with ng2. Please avoid too abstract issues without clear solve criterias.
