### ISSUE TITLE
An elipsis should always be rendered as three dots

### ISSUE THREAD

**Issue by tophee** [markdown-it/markdown-it#376]
If I'm not mistaken,

`test?..... test!....` 

is currently rendered as 

test?.. test!..

I suggest that it should be rendered with three instead of two dots (and, ideally with a space between the punctuation mark and the ellipsis.

For further reference, see here:

https://en.wikipedia.org/wiki/Ellipsis
https://english.stackexchange.com/questions/115022/spaces-for-ellipses 
http://thewritepractice.com/how-to-use-an-ellipsis-correctly/

**Comment by puzrin** [comment]
https://en.wikipedia.org/wiki/Ellipsis#In_Russian

Works as expected.

**Comment by tophee** [comment]
So markdown-it is following Russian Typography?

**Comment by puzrin** [comment]
It tries to do some well known things, when possible. I did not found another examples for this case. Also, you can disable replacer and add your own if you don't like existing one.
