### ISSUE TITLE
How to disable starting ordered list from any number?

### ISSUE THREAD

**Issue by luminarious** [markdown-it/markdown-it#377]
I ran into an issue today where our user copy-pasted a text that included a sentence starting with "2017. aastal..." and reported an issue when formatting was weird. Basically, it was unexpected behaviour for them.

Since it may be a common use-case for our platform, is there a way to limit ordered list parsing to those starting with "1. "?

**Comment by puzrin** [comment]
No. Only if you replace `list` rule with your custom patched one.
