### ISSUE TITLE
Linkify is unencoding spaces

### ISSUE THREAD

**Issue by SamSaffron** [markdown-it/markdown-it#378]
https://meta.discourse.org/search?q=visits%20%23hosting

Is rendered as [https://meta.discourse.org/search?q=visit&amp; %23hosting]()

This looks a bit strange, I am not sure it makes sense to unencode there, thoughts?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/8.3.1/lib/index.js#L23-L85

Таке a look at code above (and usage). Markdown-it has some default beautification/safety logic about links. IMHO that works well, but you can override with your own if you don't like defaults.

**Comment by puzrin** [comment]
https://github.com/markdown-it/linkify-it/blob/master/index.js#L615 linkifier has some normalisation logic, but it's not related to described effect. All magic about autogenerated links is located in markdown-it.

**Comment by SamSaffron** [comment]
Isn't that around hostname normalization? It does not appear to be dealing with query strings. is mdurl.decode responsible here for the `%20` replacement here?

**Comment by puzrin** [comment]
It normalize everything (in link's text), to behave like browser's url field.

Yes, `mdurl.decode` is responsible for that. It does ~ the same as `decodeURI`, but with guarantee that no exception will be thrown on bad data.

**Comment by puzrin** [comment]
[example why that's good](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22https%3A%2F%2Fru.wikipedia.org%2Fwiki%2F%25D0%259F%25D1%258E%25D0%25BF%25D0%25B8%25D1%2582%25D1%2580%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

**Comment by SamSaffron** [comment]
I see, decodeUri is notoriously annoying when it comes to dealing with spaces, totally get the reasoning here. I kind of want a `decodeUri` but don't decode `%20` here (or maybe just gsub %20 with +) ... I guess I can just amend some of our app urls so we generate: 

`https://meta.discourse.org/search?q=testing+testing+test`

instead of 

`https://meta.discourse.org/search?q=testing%20testing%20test`

**Comment by puzrin** [comment]
`+` will not be properly encoded back if you copypaste text to browser.

Anyway, [decode](https://github.com/markdown-it/mdurl#decodestr--exclude---string) is configurable. You can make it work as you wish.

I have no near plans to change defaults, because that requires to analyze a lot of data for better solution. I have both no data and no time. But if someone decides to pass this quest - result is discussable. For now i'm ok with existing API - it's flexible enougth to allow others be independent on my opinion.

**Comment by SamSaffron** [comment]
just to circle back, I applied this to Discourse:

https://github.com/discourse/discourse/commit/d2ba543ed3c1f6ca4ab5d378249a3051acf6e207

**Comment by puzrin** [comment]
https://github.com/discourse/discourse/commit/d2ba543ed3c1f6ca4ab5d378249a3051acf6e207#diff-d60804b6ffb637de5947111dab7c1b14R95 it's e bit dirty to modify "global" constant. You may affect other places. It's better to override https://github.com/markdown-it/markdown-it/blob/8.3.1/lib/index.js#L322 with your custom implementation:

```js
...

md.normalizeLinkText = function(url) {
  var parsed = mdurl.parse(url, true);

  if (parsed.hostname) {
    if (!parsed.protocol || RECODE_HOSTNAME_FOR.indexOf(parsed.protocol) >= 0) {
      try {
        parsed.hostname = punycode.toUnicode(parsed.hostname);
      } catch (__) { /**/ }
    }
  }

  return mdurl.decode(mdurl.format(parsed), ';/?:@&=+$,# ');
}

**Comment by SamSaffron** [comment]
Thanks will give that a shot
