### ISSUE TITLE
You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by JianmingXia** [markdown-it/markdown-it#379]
I use markdown-it have a problem.
when i want import this to my app, webpack error.
![image](https://user-images.githubusercontent.com/9691577/27941549-a5ca1fc6-6303-11e7-9385-e0d626bf00c1.png)
And I use in a new app, that's ok, It's also by webpack bundle.
Can help me?

**Comment by puzrin** [comment]
https://github.com/webpack/webpack/issues/965

You need to configure webpack to properly `require("XXX.json")` files. I don't know why they dont have this in defaults. Anyway, it's better to search details in google/webpack. This question is not related to this package.

**Comment by JianmingXia** [comment]
oh, thank you.
I know the reason, because my App use old version webpack, is 1.13.1.
But my new demo use the new webpack, so is ok.
I'm sorry.
