### ISSUE TITLE
linkify doesn't accept urls with underscores

### ISSUE THREAD

**Issue by svbergerem** [markdown-it/markdown-it#38]
[Example](https://markdown-it.github.io/#md64=eyJzb3VyY2UiOiJodHRwOi8vbWVkaWEuY2NjLmRlL2Jyb3dzZS9jb25ncmVzcy8yMDE0LzMxYzNfLV82MzczXy1fZW5fLV9zYWFsXzZfLV8yMDE0MTIyOTE2MDBfLV90aGVfb25seV90aGluZ193ZV9rbm93X2Fib3V0X2N5YmVyc3BhY2VfaXNfdGhhdF9pdHNfNjQweDQ4MF8tX29saWFfbGlhbGluYS5odG1sIiwiZGVmYXVsdHMiOnsiaHRtbCI6ZmFsc2UsInhodG1sT3V0IjpmYWxzZSwiYnJlYWtzIjpmYWxzZSwibGFuZ1ByZWZpeCI6Imxhbmd1YWdlLSIsImxpbmtpZnkiOnRydWUsInR5cG9ncmFwaGVyIjp0cnVlLCJfaGlnaGxpZ2h0Ijp0cnVlLCJfc3RyaWN0IjpmYWxzZSwiX3ZpZXciOiJodG1sIn19)
One has to escape the underscores in the url but I don't think that this is the expected behavior.

**Comment by puzrin** [comment]
http://spec.commonmark.org/dingus.html?text=http%3A%2F%2Fmedia.ccc.de%2Fbrowse%2Fcongress%2F2014%2F31c3_-_6373_-_en_-_saal_6_-_201412291600_-_the_only_thing_we_know_about_cyberspace_is_that_its_640x480_-_olia_lialina.html

That's not linkify issue, that's collision with italic. Not sure it can be resolved with ease. Ideas?

**Comment by vyp** [comment]
Links can't have whitespace right? So what about any Word (surrounded by whitespace) that starts with a valid protocol (`http://`/`https://`) ignores the italics until the end of the Word? Do you guys do the list of suggested protocols things suggested in commonmark spec? (Or is that part still there?)

I'm assuming it's might be more complicated than this though, but just the first thing I thought of.

**Comment by puzrin** [comment]
That with require inline parser to stop at `h` letter - technically possible, but bad in general.

@svbergerem what do you think about direct marking link via `<url_with_underscores>`?

**Comment by puzrin** [comment]
[this](https://markdown-it.github.io/#md64=eyJzb3VyY2UiOiI8aHR0cDovL21lZGlhLmNjYy5kZS9icm93c2UvY29uZ3Jlc3MvMjAxNC8zMWMzXy1fNjM3M18tX2VuXy1fc2FhbF82Xy1fMjAxNDEyMjkxNjAwXy1fdGhlX29ubHlfdGhpbmdfd2Vfa25vd19hYm91dF9jeWJlcnNwYWNlX2lzX3RoYXRfaXRzXzY0MHg0ODBfLV9vbGlhX2xpYWxpbmEuaHRtbD4iLCJkZWZhdWx0cyI6eyJodG1sIjpmYWxzZSwieGh0bWxPdXQiOmZhbHNlLCJicmVha3MiOmZhbHNlLCJsYW5nUHJlZml4IjoibGFuZ3VhZ2UtIiwibGlua2lmeSI6dHJ1ZSwidHlwb2dyYXBoZXIiOnRydWUsIl9oaWdobGlnaHQiOnRydWUsIl9zdHJpY3QiOmZhbHNlLCJfdmlldyI6Imh0bWwifX0=) works as expected.

**Comment by puzrin** [comment]
http://talk.commonmark.org/t/markup-collision-with-underscores-in-link-texts/1016

Created discussion @ CM forum. May be @jgm can suggest better resolution with markup.

**Comment by vyp** [comment]
Ah I see then, agreed.

**Comment by svbergerem** [comment]
@puzrin `<url_with_underscores>` should work because of the commonmark spec. URLs without surrounding `<` and `>` are afaik not part of the commonmark spec so this might be a specific issue for markdown-it.

I am not sure why linkify has to be a core rule. A possible solution might be making it an inline rule and calling it between 'backticks' and 'strikethrough'. (I haven't tried that yet)

**Comment by vyp** [comment]
> URLs without surrounding `<` and `>` are afaik not part of the commonmark spec so this might be a specific issue for markdown-it.

Yes I believe you are correct. They left that problem to 'autolinkers'.

**Comment by puzrin** [comment]
@svbergerem such inline rule will require text terminator chars enchancement with `h` char. That's not good for defaults, because will reduce speed (increase of false positives for ordinary text).

If it's very critical for you, i can include appropriate api in next rewrite milestone https://github.com/markdown-it/markdown-it/issues/34#issuecomment-70401084 . Then it will be possible to extend terminators as you wish.

Let me know about priority of this problem for your project (how critical is it, how much can it wait).

**Comment by puzrin** [comment]
> Yes I believe you are correct. They left that problem to 'autolinkers'.

Autolinkers are magic by nature. Question is, how much of such magic should be in core, and how much in plugins.

**Comment by svbergerem** [comment]
@puzrin You are right, I didn't think about the text terminator char problem. For a proper link recognition you would also have to stop at other chars (Ftp, Xmpp, Mailto, ...) and that wouldn't even be good for non-defaults (imo). 

So the basic problem is that linkify is called after the markup for emphasis has been applied. On the other hand one has to make sure that links inside of code blocks are disregarded.

**Comment by puzrin** [comment]
There are can't be collisions with code blocks. There is collision with emphasis only. Correct resolution for all protocols will be expensive for speed. If you remove `text` rule, to imitate stop on each char, speed will decrease 5x times.

**Comment by puzrin** [comment]
Compromiss solution:

1. Check only http(s) in inlline rule. That's enougth to avoid collisions in most cases.
2. Algorythm:
    - on `:`, if next is `/`+`/` -> check `/https?$/` in state.pending
    - check the rest, cut state.pending & write link tokens

That should work.

**Comment by svbergerem** [comment]
sounds good

**Comment by puzrin** [comment]
@svbergerem is it urgent to have fix in upstream? I'd like to postpone it until linkifier rewrite.

Tend to leave in core something more simple (or drop at all to plugin)

**Comment by unindented** [comment]
+1 for dropping to plugin

**Comment by svbergerem** [comment]
@puzrin Moving it to a plugin sounds good to me because this is an addition to the commonmark specs. We still need some time for the next diaspora* release and use markdown-it only in the development version so stable versions aren't affected.

**Comment by puzrin** [comment]
@svbergerem I've started linkifier rewrite. Could you give me examples of NOT links, linkified at diaspora*? Hashtags and so on. Examples + validation rules (or link to implementation).

I'd like to verify, that new linkifier will be flexible enougth.

**Comment by svbergerem** [comment]
@puzrin We have two plugins for diaspora* that are related to links: [markdown-it-hashtag](https://github.com/svbergerem/markdown-it-hashtag) ([tests](https://github.com/svbergerem/markdown-it-hashtag/blob/master/test/fixtures/hashtag/default.txt)) and [markdown-it-diaspora-mention](https://github.com/diaspora/markdown-it-diaspora-mention) ([tests](https://github.com/diaspora/markdown-it-diaspora-mention/blob/master/test/fixtures/mention/default.txt)).

In the linkify implementation for diaspora* we accept http://, https://, ftp://, mailto: and xmpp:

**Comment by puzrin** [comment]
https://github.com/markdown-it/linkexp

I'm still alive :) . That library needs some fixes and rewriting charcode classes generator. API seems to be enougth for adding typical extentions (mentions, hashtags).

**Comment by puzrin** [comment]
http://markdown-it.github.io/linkify-it/

Test it please. Feedback welcome.

**Comment by vyp** [comment]
[Link](http://markdown-it.github.io/linkify-it/#md64=eyJzb3VyY2UiOiJodHRwOi8vbWVkaWEuY2NjLmRlL2Jyb3dzZS9jb25ncmVzcy8yMDE0LzMxYzNfLV82MzczXy1fZW5fLV9zYWFsXzZfLV8yMDE0MTIyOTE2MDBfLV90aGVfb25seV90aGluZ193ZV9rbm93X2Fib3V0X2N5YmVyc3BhY2VfaXNfdGhhdF9pdHNfNjQweDQ4MF8tX29saWFfbGlhbGluYS5odG1sIn0=).

**Comment by puzrin** [comment]
@vyp what's wrong with it?

**Comment by vyp** [comment]
@puzrin nothing of course. I just linked OP's example for convenience. You have similar examples, but not the exact same one in the demo by default. No problems, it works.

**Comment by svbergerem** [comment]
@puzrin I found a similar problem we had for diaspora before:
`antifaschistisch-feministische ://test.com`
That crashes firefox and in chromium the tab freezes. The problem was that we were using [url-regex](https://github.com/kevva/url-regex) which is based on https://gist.github.com/dperini/729294. That regex somehow has a problem with the string I mentioned. We solved the problem by using a less precise and less complex regex which has some false positives but at least doesn't freeze your browser.

**Comment by puzrin** [comment]
Nice catch. Will take a look. Thanks!

**Comment by vyp** [comment]
If it helps, I'm on firefox 35.0.1, and with @svbergerem's example, firefox seems to complain about [line 489 in linkify-it.js](https://github.com/markdown-it/linkify-it/blob/gh-pages/linkify-it.js#L489).

**Comment by jhass** [comment]
The problem seems to be that a full URL regex easily involves too many alternatives and optional things, so the regex engine has to do too much backtracking and generally too many possibilities to consider, as they grow exponentially here. I think it should help to use something less precise to get the parts of an URL and then to validate the parts against stricter patterns and/or to use a series of patterns that are stricter and have less alternatives instead of trying to incorporate the whole job into a single pattern.

**Comment by puzrin** [comment]
I don't know how, but it will be fixed :). That demo is on very early beta stage. I only finished to clarify api and recognition logic. There are still pending questions with normalizers, speed and so on.

**Comment by puzrin** [comment]
Let's continue! I've updated `linkify-it` demo, it doesn't hang anymore. Speed also increased significantly. Need more broken examples :)

**Comment by puzrin** [comment]
Got a collision. If i change link detection as described in https://github.com/markdown-it/markdown-it/issues/38#issuecomment-70957738, then this patterns become broken:

- `*http://example.com/test*`
- `_http://example.com/test_`

Tailing `*` & `_` will be considered as part of link. But users need to mark autolinked text with italic & bold. The same for other extensions like strikethrough, mark, insert and so on.

Any ideas how to resolve? Without resolution we can get more problems than profit.

**Comment by puzrin** [comment]
@svbergerem , i released 3.1 with new linkifier but without priority hack. Need to decide something about https://github.com/markdown-it/markdown-it/issues/38#issuecomment-75434351.

Can we say, that links never finish with `*` and `_` or not? I could cut `/[*_]+$/` from detected pattern, but not shure if it's correct. And that will not help with other plugins like strike, ins, mark (when text is marked with ~~, ++, ==).

**Comment by svbergerem** [comment]
@puzrin I'm not an expert either. Maybe @jhass can help here.

**Comment by puzrin** [comment]
You could replace emphasis with custom one, which disables both `_` and `_-_` inside words. That requires a small change in [scanDelims](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/emphasis.js#L13), and easy to do.

I've asked @jgm in http://talk.commonmark.org/t/markup-collision-with-underscores-in-link-texts/1016/8?u=vitaly, but doubt that such exclusion will be accepted officially.

Can we agree, that this problem has solution via custom extension and no longer critical for Diaspora (can be solved without me and without dependency on mainstream)?

**Comment by jhass** [comment]
I think it's rare someone would do `_some sentence http://example.org/path_bar_`, `_some sentence http://example.com/path_bar more words_` and `_http://example.org/path_bar_` seem much more likely to me. Therefore I think a good heuristic would be to match the formatter (`_`, `*`, `~~` and so on) preceding a scheme, so cases like `_http://`, `*ftp://`, `~~mailto:` and so on, and in that case look for the matching marker before the next whitespace (including newline and end of string), or in other words at the end of the next "word", and apply them only if one is found, otherwise consider the trailing characters part of the URL.

Whether, how and where such a heuristic would fit into markdown-it, I'm not sure.

**Comment by puzrin** [comment]
@jhass , "this problem should be magically solved" contains too few technical details :)

There are 2 realistic (technically) choices:

1. make emphasis rule not break lincs of this kind.
2. add linkifier to inline rules and restrict link end.

I don't like second choice because it's not safe (see examples above). Add `_-_` to emphasis restrictions looks more safe. At least, i can't imagine false negatives. I don't like to include it into mainstream right now, but nobody can prohibit you to implement it as plugin.

**Comment by puzrin** [comment]
@svbergerem , @jhass what people says about new markdown? may be we can close this ticket as unresolvable and re commend to use `<...>` for rare complex cases?

**Comment by svbergerem** [comment]
@puzrin I acknowledge that there is no easy solution for this issue. I heard no further complains so it seems like this is a rare case.
