### ISSUE TITLE
Underscore in URL is handled differently than commonmark 0.27.0

### ISSUE THREAD

**Issue by SamSaffron** [markdown-it/markdown-it#380]
see:  https://johnmacfarlane.net/babelmark2/?text=https%3A%2F%2Fderp.com%3F_test_%3D1 

```
https://derp.com?_test_=1
```

commonmark 0.27.0 

```
<p>https://derp.com?_test_=1</p>
```

markdown.it

```
<p>https://derp.com?<em>test</em>=1</p>
```

Is this unspecified per spec?

**Comment by puzrin** [comment]
Seems something new... Will check tomorrow.

Also, search "underscore" in closed issues. There is a known collision between linkifier and emphasis, with my explanations. It can not be resolved without very big rewrite. Workaround is add `<...>` to links with problems. May be it's possible to do something with your example in this issue, but that will not change the situation in general.

**Comment by rlidwka** [comment]
> Is this unspecified per spec?

It is very well specified in the spec which commonmark.js ain't following correctly.
Check this example: `?_test_=`.

Punctuation characters are defined in the spec here:
 - [CommonMark/spec.txt](https://github.com/jgm/CommonMark/blob/c94efe8d3adbfbe6418c7ea59ab3802472c7e4b2/spec.txt#L329-L332)

Those are implementations:
 - [commonmark.js/lib/inlines.js](https://github.com/jgm/commonmark.js/blob/277b0d71e7494d5e38666c00c281372ae9799b59/lib/inlines.js#L39)
 - [cmark/src/cmark_ctype.c](https://github.com/jgm/cmark/blob/53ef343a65e3da19d605cfb7e8909004cfac954e/src/cmark_ctype.c#L7-L24)
 - [markdown-it/lib/common/utils.js](https://github.com/markdown-it/markdown-it/blob/a1b64e6f5779d7d28ab2387ede10e78fdfb8db7f/lib/common/utils.js#L201-L239)

Spec defines this character set as punctuation:
```
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
```

But commonmark uses this one instead:

```
!"#%&'()*,-./:;?@[\]_{}
```

As you can see, 8 characters are missing there. Which creates this inconsistency:

```
$ echo '^_test_' | ./cmark/build/src/cmark 
<p>^<em>test</em></p>
$ echo '^_test_' | ./markdown-it/bin/markdown-it.js 
<p>^<em>test</em></p>
$ echo '^_test_' | ./commonmark.js/bin/commonmark 
<p>^_test_</p>
```

Imho, it's a bug in commonmark.js.

**Comment by puzrin** [comment]
@sam, so this issue consists of 2 parts:

1. Bug in `commonmark.js` (not here, reported)
2. Known bug/collision with linkifier/emphasis

I know that (2) can be fixed, but don't like to spend a lot of time for it, since it's not very critical IMHO and has easy workaround with `<...>`. If anyone decide to improve, i can explain principle.

Can i close this issue?

**Comment by SamSaffron** [comment]
sure, we can close, the implementation is good, I think the spec needs love but this is nothing to do with the particular implementation here.
