### ISSUE TITLE
@ sign in url is not being rendered as a link

### ISSUE THREAD

**Issue by oblakeerickson** [markdown-it/markdown-it#381]
It appears that when you post a link that contains an @ sign the whole url doesn't being a link.

A lot of [Medium](https://medium.com/) urls contain '@' signs. I personally don't understand why they chose to do this, but considering how popular Medium is I think it might be a good thing to support.

Here is an example link that is currently not being generated correctly:

https://medium.com/@garyvee

You can see a current demo if it not working on [Discourse Meta](https://meta.discourse.org/t/commonmark-testing-started-here/65121/103?u=oblakeerickson)

According to [RFC 2396 - 3.3](https://tools.ietf.org/html/rfc2396#page-14) the @ sign is valid in urls. You can read a little bit more about this [here](https://medium.engineering/it-takes-a-village-to-read-an-rss-feed-84e63a3c9094) which states:

> What this is basically saying is that “@” is OK in some parts but not in other parts. The URL “https://medium.com/@nicksantos” is valid, but “https://medium@/” is not.

**Comment by puzrin** [comment]
[Can not reproduce](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22https%3A%2F%2Fmedium.com%2F%40garyvee%2C%20foo%20bar.%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

Seems problem is not here. Any other samples?

**Comment by SamSaffron** [comment]
This may be a clash with our @mention support, will update this on Monday and close if that is th case

**Comment by SamSaffron** [comment]
Feel free to close, this is a bit of a nightmare to fix though. 

At the moment @mention is implemented as an inline rule and linkify happens in a core rule after, so I am stuck moving @mention into a core rule

**Comment by puzrin** [comment]
OK.

I think, in theory, you can even extend linkifier with `@` schema. Anyway, now see no problem to implement mentions both at inline or at core (may be i miss some knowledge). Logic itself is simple and should not produce serious collisions.
