### ISSUE TITLE
Is it possible to use markdown-it with multiline text and / or template literals?

### ISSUE THREAD

**Issue by manovotny** [markdown-it/markdown-it#384]
More than likely, I am probably being dumb. I am trying to do something like this.

```js
import Markdown from 'markdown-it';

const md = new Markdown();

const markdown = `
    # This is a heading

    And here's the content.

    *This is italic text.*

    **This is bold text.**

    ***This is bold italic text.***

    ~~This is strikeout text.~~
`;

const renderedMarkdown = md.render(markdown);

console.log(renderedMarkdown);
```

Which produces...

```html
<pre><code># This is a heading

And here's the content.

*This is italic text.*

**This is bold text.**

***This is bold italic text.***

~~This is strikeout text.~~
</code></pre>
```

I assume this is the case be cause markdown-it is processing the template literal backticks as markdown code ticks, thus the `<pre>` around the whole block.

Is there a way to get markdown-it to render template literals or to somehow render multiline text? Or is markdown-it only meant to process a line at a time or single line text with `\n`'s in them?

Thanks for the insight!

**Comment by puzrin** [comment]
1. Your should remove leading spaces at start of text lines :). 4 spaces -> code block
2. https://markdown-it.github.io/ - that should help to experiment.

**Comment by manovotny** [comment]
Ugh... Indentation. See! I said I was probably being dumb!

Thanks for the help!
