### ISSUE TITLE
indented list incorrectly parsed as blockquote continuation

### ISSUE THREAD

**Issue by dwelle** [markdown-it/markdown-it#386]
```
- list
    > blockquote
blockquote
    - SHOULD BE LIST, NOT BLOCKQUOTE
```

- [cm perma](http://spec.commonmark.org/dingus/?text=-%20list%0A%20%20%20%20%3E%20blockquote%0Ablockquote%0A%20%20%20%20-%20SHOULD%20BE%20LIST)
- [markdown-it perma](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22-%20list%5Cn%20%20%20%20%3E%20blockquote%5Cnblockquote%5Cn%20%20%20%20-%20SHOULD%20BE%20LIST%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D) (incorrect)

would appear it incorrectly parses curr list indentation, since this works:

```
- list
    > blockquote
blockquote
  - 2-column-indented list (parsed correctly as 2nd level list)
```

**Comment by rlidwka** [comment]
Fixed, thanks!
