### ISSUE TITLE
closing fence should allow trailing *spaces* only 

### ISSUE THREAD

**Issue by dwelle** [markdown-it/markdown-it#388]
As per spec (which I think is kinda stupid in this case, but...), closing fence should only allow trailing spaces, not tabs.

- [CommonMark dingus](http://spec.commonmark.org/dingus/?text=%60%60%60%0Acode%0A%60%60%60%09%0Astill%20code)
- [MarkdownIt Dingus](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%60%60%60%5Cncode%5Cn%60%60%60%5Ct%5Cnstill%20code%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

Caused by [utils/isSpace](https://github.com/markdown-it/markdown-it/blob/e6f19eab4204122e85e4a342e0c1c8486ff40c2d/lib/common/utils.js#L154) allowing tabs

**Comment by rlidwka** [comment]
As per spec, tabs can be expanded to spaces "in contexts where whitespace helps to define block structure" (quote from [here](http://spec.commonmark.org/0.28/#tabs)).

See the [example 11](http://spec.commonmark.org/0.28/#example-11) in particular where trailing tabs after thematic break are treated as spaces, even though thematic breaks allow spaces only (see definition [here](http://spec.commonmark.org/0.28/#thematic-breaks)).

I think I'm going to open an issue against commonmark.js about this one.

**Comment by rlidwka** [comment]
The behavior of reference parsers (`commonmark.js` and `cmark`) is different, and I believe it works correctly here. So I'm closing this issue, please re-open if it gets fixed in `commonmark.js` or `cmark` in any way that's different from markdown-it implementation.
