### ISSUE TITLE
Failed to parse file:// in image markup

### ISSUE THREAD

**Issue by lambdalisue** [markdown-it/markdown-it#389]
<img width="980" alt="screen shot 2017-08-04 at 13 32 28" src="https://user-images.githubusercontent.com/546312/28954328-79f3b5ac-7919-11e7-952b-d1d6aa22b1b9.png">

The following markup fail

```
![AAA](file://aaaaa)
```

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/8.3.2/lib/index.js#L23-L40

That's indended for defaults. You should override validator:

```js
var md = require('markdown-it')();
// example only, you may wish to keep `javascript://` etc links disabled
md.validateLink = function () { return true; };
```

**Comment by lambdalisue** [comment]
I see thanks 👍
