### ISSUE TITLE
nested ordered lists not rendering

### ISSUE THREAD

**Issue by ngoldman** [markdown-it/markdown-it#39]
Reproducible in the demo at https://markdown-it.github.io/:

![screen shot 2015-01-25 at 9 42 51 pm](https://cloud.githubusercontent.com/assets/427322/5895687/49520616-a4db-11e4-920f-ddcb86572708.png)

![screen shot 2015-01-25 at 9 42 55 pm](https://cloud.githubusercontent.com/assets/427322/5895688/4a391ed4-a4db-11e4-95b0-9e7cda5889df.png)

It appears rendering for ordered lists is also ignoring line breaks (visible above).

**Comment by rlidwka** [comment]
Elements of the nested lists should be aligned to the first non-space character of the parent list item.

For example, this is nested list:

```
1. Parent item
   1. Nested list item
```

But this one is not:

```
1. First item
  1. Second item (not a nested list)
```

**Comment by ngoldman** [comment]
Because the first has three spaces and the second has two? I don't understand how that doesn't qualify.

The nested unordered list directly above it is using two spaces:

```
Unordered

+ Create a list by starting a line with `+`, `-`, or `*`
+ Sub-lists are made by indenting 2 spaces:
  - Marker character change forces new list start:
    * Ac tristique libero volutpat at
    + Facilisis in pretium nisl aliquet
    - Nulla volutpat aliquam velit
+ Very easy!
```

**Comment by ngoldman** [comment]
Just as an example here is how github is rendering the same list above when ordered:

1. Create a list by starting a line with `+`, `-`, or `*`
1. Sub-lists are made by indenting 2 spaces:
  1. Marker character change forces new list start:
    1. Ac tristique libero volutpat at
    1. Facilisis in pretium nisl aliquet
    1. Nulla volutpat aliquam velit
1. Very easy!

and here is how markdown-it is rendering it:

![screen shot 2015-01-26 at 1 22 37 am](https://cloud.githubusercontent.com/assets/427322/5897540/ddb7bdaa-a4f9-11e4-852c-eacfb6ee260f.png)

**Comment by vyp** [comment]
@ngoldman have you read the [commonmark spec](http://spec.commonmark.org/0.17/#motivation)? It has more of the reasoning I believe.

**Comment by ngoldman** [comment]
Ah, I see. Thanks @vyp. This was a stylistic variation of CommonMark I was not familiar with. Since markdown-it is 100% CommonMark I guess my argument is invalid. The second thing I noticed is also invalid -- the ordered lists are rendering correctly, it's just the style of the site that makes them look like they're part of the same list. Thanks for the lesson.

**Comment by vyp** [comment]
> The second thing I noticed is also invalid -- the ordered lists are rendering correctly, it's just the style of the site that makes them look like they're part of the same list.

Sorry for being annoying, but I don't see this? Perhaps I've inputted the wrong example? https://markdown-it.github.io actually has a 'permalink' button you can click on after you have inputted your text (so you didn't have to take screenshots), could you do that because I'm a bit curious? Thanks in advance!

**Comment by puzrin** [comment]
Closed - works as needed (according to CM spec)

**Comment by ngoldman** [comment]
@vyp https://markdown-it.github.io/#md64=eyJzb3VyY2UiOiJPcmRlcmVkXG5cbjEuIExvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0XG4yLiBDb25zZWN0ZXR1ciBhZGlwaXNjaW5nIGVsaXRcbjMuIEludGVnZXIgbW9sZXN0aWUgbG9yZW0gYXQgbWFzc2FcblxuXG4xLiBZb3UgY2FuIHVzZSBzZXF1ZW50aWFsIG51bWJlcnMuLi5cbjEuIC4uLm9yIGtlZXAgYWxsIHRoZSBudW1iZXJzIGFzIGAxLmBcblxuXG4xLiB0aGlzIGxpc3QgbG9va3Mgd2VpcmRcbjEuIGJ1dCBpdCdzIGp1c3QgYSBDU1MgdGhpbmcgbm90IGEgbWFya3VwIHRoaW5nIHNvIGl0J3Mgbm90IGFuIGlzc3VlXG5cbjEuIGhvd2V2ZXIgdGhpcyBzZWVtcyBsaWtlIGFuIGlzc3VlIGFzIGl0IHNob3VsZCBiZSB0aGUgc3RhcnQgb2YgYSBuZXcgbGlzdCAtLSB1bmxlc3MgdGhhdCdzIGFub3RoZXIgQ29tbW9uTWFyayB0aGluZyBJJ20gdW5hd2FyZSBvZlxuXG4xLiBzZWUgd2hhdCBJIG1lYW4gLS0gYWZhaWsgdGhpcyBzaG91bGQgYmUgIzEgbm90ICM0XG5cblN0YXJ0IG51bWJlcmluZyB3aXRoIG9mZnNldDpcblxuNTcuIGZvb1xuMS4gYmFyXG4iLCJkZWZhdWx0cyI6eyJodG1sIjpmYWxzZSwieGh0bWxPdXQiOmZhbHNlLCJicmVha3MiOmZhbHNlLCJsYW5nUHJlZml4IjoibGFuZ3VhZ2UtIiwibGlua2lmeSI6dHJ1ZSwidHlwb2dyYXBoZXIiOnRydWUsIl9oaWdobGlnaHQiOnRydWUsIl9zdHJpY3QiOmZhbHNlLCJfdmlldyI6Imh0bWwifX0=

**Comment by vyp** [comment]
@ngoldman Ah okay I see. I think the "this list looks weird" is due to being wrapped in `<p>` tags, but not sure.

> unless that's another CommonMark thing I'm unaware of

Indeed, I believe you're using ['loose'](http://spec.commonmark.org/0.17/#loose) lists here. I think [example 203](http://spec.commonmark.org/0.17/#example-203) (and so on) might help clear things.

**Comment by ngoldman** [comment]
:+1: `CommonMark !== GFM`
