### ISSUE TITLE
Html code with blank lines render differently

### ISSUE THREAD

**Issue by RoDash** [markdown-it/markdown-it#390]
**Doesn't work** (notice the blank line between divs)
<ul>
  <li>
    <div>
      <div>
        foo
      </div>

      <div>
        blah
      </div>
    </div>
  </li>
</ul>

![image](https://user-images.githubusercontent.com/15942907/28964780-dccdf13a-792b-11e7-931d-d7d1aa26dfc3.png)

**Works fine**
<ul>
  <li>
    <div>
      <div>
        foo
      </div>
      <div>
        blah
      </div>
    </div>
  </li>
</ul>

![image](https://user-images.githubusercontent.com/15942907/28964748-ba659fc6-792b-11e7-9af3-a32a24238443.png)

**Comment by puzrin** [comment]
Please read CM spec and check in reference demo prior to report here. That's not a bug and not related to this package.
