### ISSUE TITLE
Can i customize the markdown syntax instead of CommonMark syntax ?

### ISSUE THREAD

**Issue by tikkichan4** [markdown-it/markdown-it#392]
Since i am developing an user-generated content project, i would like to display some content with markdown. But i dont want the user to use those markdown.

However, the user content may contains the syntax like **

**Solution 1:**
I would like to customize the markdown syntax to avoid user using the markdown syntax, such as :
** to [bold][bold]

**Solution 2:**
 Add a specific character such as \ to skip the markdown syntax checking.

Is it possible ? Thanks a lot.

**Comment by puzrin** [comment]
I'd suggest to read docs about customization principles https://github.com/markdown-it/markdown-it/tree/master/docs

The general question is out of this project scope.
