### ISSUE TITLE
Block rule does not capture last element

### ISSUE THREAD

**Issue by dsbudiac** [markdown-it/markdown-it#393]
I added the following block rule to replace any `<p>` wrapped `<img>` tags with `<figure>`:

```javascript
md.block.ruler.before('paragraph', 'figure', state => {
  for (let i = 0; i < state.tokens.length; i++) {

    let open = state.tokens[i];
    let inline = state.tokens[i + 1];
    let close = state.tokens[i + 2];

    // Find token sequence <p><img /></p>
    if (open.type !== 'paragraph_open') continue;
    if (close.type !== 'paragraph_close') continue;
    if (!/^!\[[^\]]*\]\([^)]+\)$/.test(inline.content)) continue;

    // Swap out the paragraphs for figures
    open.type = 'figure_open';
    open.tag = 'figure';

    close.type = 'figure_close';
    close.tag = 'figure';
    }
});
```

I'm betting I'm doing something wrong, but:

1. Is there a better way to do this?
2. If the last line in markdown is an image, this rule will not capture. (example below)

```markdown
![kittens](kittens.jpg)

![puppies](puppies.jpg)

![turtles](turtles.jpg)
```

Will render:

```html
<figure><img src="kittens.jpg" alt="kittens"></figure>
<figure><img src="puppies.jpg" alt="puppies"></figure>
<p><img src="turtles.jpg" alt="turtles"></p>
```

Why wouldn't the last one get captured?

**Comment by puzrin** [comment]
I would not recommend to override paragraph on this (tokenizer) level to avoid collisions with other rules.

It would be more safe to to add rule to `core` chain after everything, scan paragraphs and make replacements if content has only one image.

**Comment by dsbudiac** [comment]
Thank you. This works as needed if I replace...

```javascript
md.block.ruler.before('paragraph', 'figure', state => {
```

with...

```javascript
md.core.ruler.after('inline', 'figure', state => {
```

*Aside*: Now instead of using regex, I now examine the inline property's children for the single image token.
