### ISSUE TITLE
CommonMark 0.28 support

### ISSUE THREAD

**Issue by noirbizarre** [markdown-it/markdown-it#395]
Hi !

[CommonMark 0.28](http://spec.commonmark.org/0.28/) is out. Is it possible to sync CommonMark support to this version ?

I noticed that @kivikakk started some works on #356 but I don't know if this is still working with the final 0.28 release.

**Comment by puzrin** [comment]
Thanks for memo. Will be done in the nearest time.

**Comment by noirbizarre** [comment]
You're welcome :+1: 

Thanks for the fast response ;)
