### ISSUE TITLE
Only have linkify enabled

### ISSUE THREAD

**Issue by ridewn** [markdown-it/markdown-it#396]
I'm not sure exactly how to only enable linkify, which makes me think this is be an issue, but I could be wrong or missing something.

I have 

```javascript
const mdConversation = new MarkdownIt('zero', {
  linkify: true
})

return mdConversation.render(message)
```

Yet for some reason, `linkify` is still not working; say the message variable is 'http://www.example.com/', the output is not linkified.

Can this be done?

Thanks.

**Comment by puzrin** [comment]
If you used `zero`, then you have add back plugin too: `.enable('linkify')`

**Comment by ridewn** [comment]
I should have put this in my initial issue, but I had tried that as well, but it didn't work, these are the only two things I've tried though.

Using still produces no autolink:

https://jsfiddle.net/f2c2214q/

**Comment by puzrin** [comment]
https://jsfiddle.net/f2c2214q/3/

```js
var md = new markdownit('zero', { linkify: true }).enable('linkify');
```

**Comment by ridewn** [comment]
Ah, okay. Didn't realize I had to specify it in the options then enable. thank you!
