### ISSUE TITLE
Relative picture paths not interpreted

### ISSUE THREAD

**Issue by FoxP** [markdown-it/markdown-it#397]
From an html file located at :

`C:\Users\Test\SHEETS\Test.html`

And a picture located at :

`C:\Users\Test\SHEETS\FILES\Test\Picture 1.png`

The following markdown picture code is not interpreted :

`![PictureTitle](FILES\Test\Picture 1.png)`

I'm migrating from marked.js to this awesome parser but this is a blocker for me.
I'm working on a local HTML catalog used on a Windows OS.

**Comment by puzrin** [comment]
Spaces are not allowed in URL you should escape or encode those:

[example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22!%5BPictureTitle%5D%28FILES%5C%5CTest%5C%5CPicture%5C%5C%201.png%29%5Cn%5Cn!%5BPictureTitle%5D%28FILES%5C%5CTest%5C%5CPicture%25201.png%29%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D)

**Comment by FoxP** [comment]
Oops. My example is not that good.
It does not work with an url without spaces, but if i replace "\" by "/" in it, it's ok.
I think the problem is related to my Windows local paths.

**Comment by puzrin** [comment]
I think it's better to read commonmark spec about all edge cases http://spec.commonmark.org/0.28/#links.

PS. marked does not follow CM spec, but migration should not be too difficult.

**Comment by FoxP** [comment]
Thanks for this spec, i'll update my Mardown code so.
