### ISSUE TITLE
bug of mardown list style

### ISSUE THREAD

**Issue by laoqiren** [markdown-it/markdown-it#398]
When I use `markdown-it` to generate a markdown file with a list like this:
```
* itme1
* item2
```
I found that in the result html, the list's style is strange, it's out fo the container while other contents perfoms normal. Here is a screenshot.
![http://7xsi10.com1.z0.glb.clouddn.com/mdissue.png](http://7xsi10.com1.z0.glb.clouddn.com/mdissue.png)

The black spot on the left of the list is out of the container.

Or you can have a more clear look at [http://luoxia.me/yohe_site/2017/09/07/RabbitMQ/index.html](http://luoxia.me/yohe_site/2017/09/07/RabbitMQ/index.html)

**Comment by puzrin** [comment]
I'm not sure i understand the problem.

1. Please, use https://markdown-it.github.io/ to provide minimal sample.
2. Check the reference http://spec.commonmark.org/dingus/ implementation and make sure problem is markdown-it specific.

**Comment by puzrin** [comment]
Close - no feedback, timed out.
