### ISSUE TITLE
Dynamically load markdown-it-katex if math block is encountered in the html.

### ISSUE THREAD

**Issue by prabhatmuroor** [markdown-it/markdown-it#399]
We have requirement to use markdown-it-katex with markdown-it.
markdown-it-katex with its dependencies is around 200kb, so we dont want to load markdown-it-katex in every page, we want to load only in the pages that include a math block.
Is it possible to provide a callback similar to highlight, so that we can parse the page and load it dynamically?

If I need to send patch for it, can someone please suggest right approach to implement this?

Thanks,
Prasad

**Comment by puzrin** [comment]
Markdown-it is sync, and can not control async operations (like module loads) directly. Possible workarounds are described in https://github.com/markdown-it/markdown-it/blob/master/docs/development.md#i-need-async-rule-how-to-do-it.

You should render katex parts to special token (or html block in renderer). Then, if such element exist - load additional dependency, rend apply changes (or reconfigure parser and rerun).

I think, this should be addresses to `markdown-it-katex` author as improvement suggestion. There is nothing to change here.

**Comment by jimmywarting** [comment]
Is there still no possibility to have a async function? i also wish to be able to dynamically load the highlight js language as needed only.

```js
window.markdownit({
      html: true,
      async highlight (code, lang) {
        const parser = await import(lang)
        hljs.set(...)
      }
    })
```

**Comment by puzrin** [comment]
See previous reply. Async stuff can be called manually between parser & renderer. Or you can do post-processing after html generated.

**Comment by jimmywarting** [comment]
Switching to `marked` as it has more modern codebase and [async support](https://marked.js.org/using_advanced#highlight) for highlights, even comes with esm, so sry, but i will say good bye to markdown-it
