### ISSUE TITLE
Asynchronous usage?

### ISSUE THREAD

**Issue by zeke** [markdown-it/markdown-it#40]
We want to replace `marked` with `markdown-it` in our project, but we're using an asynchronous syntax highlighting function:

https://github.com/npm/marky-markdown/blob/7317bc933c4c999c7f52b9f638a174d10b2a076e/lib/render.js#L5-L26

Is there a way to do this with `markdown-it`?

// @fengmk2 @puzrin

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/docs/development.md#i-need-async-rule-how-to-do-it

marked does not really support async highlight, it does ugly hack. You should understand, that all such parsers are sync by nature. You can do manually:

- parse
- async highlight each fenced token
- render (and override fenced rendered to not escape)

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/index.js#L399-L403

See what happens when you call markdown-it. Just cann those functions manually, and do async job between.
