### ISSUE TITLE
Why every input was wrap with <pre> and <code>

### ISSUE THREAD

**Issue by DanielWLam** [markdown-it/markdown-it#400]
https://jsfiddle.net/lwd931227/uwywnxj8/

Here is a jsfiddler. It looks normal to me. However, markdown-it just doesn't render correctly, which spend a whole day for me to find out why...

Is there anything i did wrong?

**Comment by puzrin** [comment]
> Is there anything i did wrong?

In your source text every line has 4 spaces at start. That's a code block according to CM spec. Remove those spaces.
