### ISSUE TITLE
markdown-it takes two render() calls to render markdown-it-katex

### ISSUE THREAD

**Issue by prabhatmuroor** [markdown-it/markdown-it#401]
We are using markdown-it-katex to display mathematical symbols with markdown-it. We have modified markdown-it-katex to support the AMD.

We are noticing that after we make the call  markdown-it's use("<path to>/markdown-it-katex"), we need to call render(content) twice for markdown-it to render the math symbols. 

Can somebody suggest reason why this might be happening, or please point me to right direction to debug this?

Thanks.

**Comment by puzrin** [comment]
No ideas. That looks like too general question, "how to debug my code".
