### ISSUE TITLE
Option to disable underscore as a italic marker

### ISSUE THREAD

**Issue by neilsustc** [markdown-it/markdown-it#404]
When use markdown with LaTeX, `_` used for LaTeX subscript is often parsed to italic block.

Can markdown-it be configured to ignore `_` when rendering?

**Comment by puzrin** [comment]
only in pair with bold: `.disable('emphasis')`

**Comment by neilsustc** [comment]
Thanks for your response!

But `.disable('emphasis')` will disable all emphasis blocks (both `_` and `*`), right? Can we disable `_` but enable `*`?

**Comment by puzrin** [comment]
You can create custom emphasis, based on  default one, and crop underlines support there.

**Comment by neilsustc** [comment]
Could you please point out where should I start? Do I need to write a plugin for it? (because I have no idea about how a parser works)

Of course I can start by reading through all the code... but some simple tips from you will save me a lot of time. Thanks!

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/tree/master/docs

**Comment by neilsustc** [comment]
Thanks

**Comment by neilsustc** [comment]
Another solution: wrapping your math equation with `<p>` or `<div>` to avoid parsing of markdown-it

*Comment here in case there are other users have the same problem*

**Comment by zwcloud** [comment]
markdown-it will still translate `<span>123_</span>456<span>_789</span>` to `<span>123</span><em>456</em><span>789</span>`. This is actually a bug since embedded html tag's contents are translated.

**Comment by puzrin** [comment]
That's not a bug of this package, because it does exactly as commonmark spec says. Use escapes (`\`) to keep `_` intact (or don't mix markdown markup with html).

**Comment by zwcloud** [comment]
Emm.. I have to say, you ARE right, sir.

But I hope markdown-it will become practically useful instead of sticking to the so-called spec. See [how markdown.js approach this issue](https://github.com/evilstreak/markdown-js/issues/129)?

**Comment by yzhang-gh** [comment]
I agree with @puzrin because sticking to spec makes it pure.

---

BTW @zwcloud, the markdown-it online demo seems to work as you wish. You might not use the latest version?

![image](https://user-images.githubusercontent.com/7588612/52060721-b54a1800-2564-11e9-97dd-bd777a64a781.png)

**Comment by puzrin** [comment]
@zwcloud 

I understand your desire to have "something working immediately", but we should follow some rules to not invent "yet another one incompatible standard". Very often question appears hear not because package is bad, but becouse people don't know how to use existing features of markdown and what is the optimal place to address such issues.

If your question is about markup, the best way is to ask it at commonmark forum. In worst case, you can ask here "how can i do this?", and i'll try to help. Trying to address here "global problems" will not help, because we can not diverge from spec. We intentionally stay aside from any spec-related discussions. Don't consider this as "sending to hell" :).

**Comment by zwcloud** [comment]
@yzhang-gh 
![image](https://user-images.githubusercontent.com/6965758/52061330-02e87400-25a9-11e9-9003-05300b8529e9.png)

```
<span>$f_{\text{r}}(\omega_{\text{i}},\omega_{\text{r}})$</span><span>$L_{\text{r}}(\omega _{\text{r}})$</span>However<span>$\operatorname {d} L_{\text{r}}(\omega _{\text{r}})$</span>ABC<span>$\operatorname {d} E_{\text{i}}(\omega _{\text{i}})$</span>
```

**Comment by zwcloud** [comment]
> @zwcloud
> 
> I understand your desire to have "something working immediately", but we should follow some rules to not invent "yet another one incompatible standard". Very often question appears hear not because package is bad, but becouse people don't know how to use existing features of markdown and what is the optimal place to address such issues.
> 
> If your question is about markup, the best way is to ask it at commonmark forum. In worst case, you can ask here "how can i do this?", and i'll try to help. Trying to address here "global problems" will not help, because we can not diverge from spec. We intentionally stay aside from any spec-related discussions. Don't consider this as "sending to hell" :).

Thanks for your well-considered response. I can understand the idea.
I think it's better to spending some time in digging into the source code and docs, to solve the issue myself.

**Comment by yzhang-gh** [comment]
> ```
> <span>$f_{\text{r}}(\omega_{\text{i}},\omega_{\text{r}})$</span><span>$L_{\text{r}}(\omega _{\text{r}})$</span>However<span>$\operatorname {d} L_{\text{r}}(\omega _{\text{r}})$</span>ABC<span>$\operatorname {d} E_{\text{i}}(\omega _{\text{i}})$</span>
> ```

You have two `\omega _` there 😑

**Comment by zwcloud** [comment]
@yzhang-gh 

```<span>$f_{\text{r}}(\omega_{\text{i}},\omega_{\text{r}})$</span>```
result with MathJax:

![image](https://user-images.githubusercontent.com/6965758/52063033-ae46f800-25ac-11e9-92d9-91f2b1a33185.png)

**Comment by zwcloud** [comment]
@yzhang-gh  Yes. That's it. Thank you! That fixes my issue temporarily.

**Comment by puzrin** [comment]
I'm ok about any discusstions in closed issues. The only problem is new issues because i should invent polite reasons how to close those :)

**Comment by yzhang-gh** [comment]
Lol 🤣

Here is a perfect candidate

![standards](https://imgs.xkcd.com/comics/standards.png)

**Comment by zwcloud** [comment]
@yzhang-gh 
Remove `_` check from this line disables underscore as a italic marker:
https://github.com/markdown-it/markdown-it/blob/bda94b0521f206a02427ec58cb9a848d9c993ccb/lib/rules_inline/emphasis.js#L15

```diff
@@ -4880,7 +4880,7 @@ module.exports.postProcess = function emphasis(state) {
   for (i = max - 1; i >= 0; i--) {
     startDelim = delimiters[i];

-    if (startDelim.marker !== 0x5F/* _ */ && startDelim.marker !== 0x2A/* * */) {
+    if (startDelim.marker !== 0x2A/* * */) {
       continue;
     }
```

I don't know if it will introduce some side effects but I works for me, for now. I never use underscore as a italic marker myself because it often cause syntax highlighting error in other editors when used aside  Unicode characters such as VSCode.

**Comment by yzhang-gh** [comment]
Ah, nice finding. Would you like to make it a markdown-it plugin 😏 (so we can use it in vscode)

**Comment by jennifer-shehane** [comment]
Ah, I would have really liked this feature. I need some places to interpret markdown for italic and bold and some for only bold, so I can't even patch it easily like shown above.

**Comment by puzrin** [comment]
> Ah, I would have really liked this feature. I need some places to interpret markdown for italic and bold and some for only bold, so I can't even patch it easily like shown above.

You can create your bold-only plugin. See the strikethrough rule and https://github.com/markdown-it/markdown-it-mark. That should give you an idea of how to clean existing emphasis code for your custom needs,
