### ISSUE TITLE
images not rendered between <center> tags in html mode

### ISSUE THREAD

**Issue by alexpmorris** [markdown-it/markdown-it#405]
When rendering in html mode, if I have the following construct the image is not rendered:

```
<center>![cuteCat](https://i.redd.it/qh713wbo4r8y.jpg)</center> 
```
My current workaround is to replace `<center>` with `<c!>` before the render, then restoring by converting `&lt;c!&gt;` back to `<center>` afterwards.  However, this seems more of a "hacky" work-around rather than the "expected" functionality.

**Comment by alexpmorris** [comment]
I found one more quirk.  If someone places html header code in html mode, the links are no longer rendered either.  For example:

```
<h1>test:</h1>
![cuteCat](https://i.redd.it/qh713wbo4r8y.jpg)
```
remove the line `<h1>test:</h1>` and it renders the image correctly again.

**Comment by puzrin** [comment]
Add empty line after html block tags. That's specified in CommonMark spec. Not a bug.

**Comment by alexpmorris** [comment]
It does seem to solve it, though it still requires an extra pre-processing step.  Shouldn't that perhaps only be enforced in "CommonMark strict" mode?  I'm processing a more generic html/markdown combo from a public blog site, so "strict"-type processing is not really in the cards for this data set.  

Regardless, this definitely helps a lot for now, so thanks for that! :)

**Comment by puzrin** [comment]
IMHO that's not right place for such suggestions. We implement spec and don't discuss format itself. You can ask such questions at commonmark forum or try customized alternatives like https://github.com/npm/marky-markdown (search in npm for plugins).

**Comment by asterism612** [comment]
I have same issue . 
How to solve it?
