### ISSUE TITLE
Support for multi-line rows in tables

### ISSUE THREAD

**Issue by KantarBruceAdams** [markdown-it/markdown-it#406]
This implementation (as used by VSTS) doesn't seem to support multi-row cells in tables (a github flavour markdown extension). As below:

| Fruit         | Price                   | Advantages              |
| ------------- | ----------------------- | ----------------------- |
| Bananas       | first line<br>next line | first line<br>next line |
| Bananas       | first line<br>next line | first line<br>next line |

If this is deliberate it might help to clarify in the documentation.
(i.e. this page https://help.github.com/articles/organizing-information-with-tables/)

See also:
https://stackoverflow.com/questions/47324785/how-can-i-add-a-table-with-multi-row-cells-to-a-readme-in-vsts/47335483#47335483

**Comment by puzrin** [comment]
Seems to [work as expected](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%7C%20Fruit%20%20%20%20%20%20%20%20%20%7C%20Price%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Advantages%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%5Cn%7C%20-------------%20%7C%20-----------------------%20%7C%20-----------------------%20%7C%5Cn%7C%20Bananas%20%20%20%20%20%20%20%7C%20first%20line%3Cbr%3Enext%20line%20%7C%20first%20line%3Cbr%3Enext%20line%20%7C%5Cn%7C%20Bananas%20%20%20%20%20%20%20%7C%20first%20line%3Cbr%3Enext%20line%20%7C%20first%20line%3Cbr%3Enext%20line%20%7C%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

Could you provide example with error via demo?

**Comment by KantarBruceAdams** [comment]
I'll take that as sufficient evidence the problem is not markdown-it.

I can't provide an example. Microsoft claim to use your implementation [here|https://code.visualstudio.com/docs/languages/markdown] but they don't state which version or configuration. I suspect they have disabled html completely in VSTS for fear of real or imaginary html injection attack vectors.

**Comment by Lucas-C** [comment]
Note that if you don't want to use `<br>` and have a very long row line in Markdown,
you can use this plugin:
https://github.com/RedBug312/markdown-it-multimd-table#multiple-lines-of-row

**Comment by mahdyaslami** [comment]
if it was possitble to have a table like following table it was more flexible

| column1 | column 2 |
|----------|-----------|
| value      | * value 1  |
|               | * value 2  |
|----------|-----------|
| value      | * value 1  |
|               | * value 2  |

is there any way to do this? because this structure help to have readable document with notepad and other editor too.

**Comment by puzrin** [comment]
All extensions should be done via plugins. Default implementation works like github's one and modification requests are not accepted.

**Comment by Riverlance** [comment]
> if it was possitble to have a table like following table it was more flexible
> 
> ```
> | column 1 | column 2 |
> |----------|----------|
> | value    | * value 1|
> |          | * value 2|
> |----------|----------|
> | value    | * value 1|
> |          | * value 2|
> ```
> 
> is there any way to do this? because this structure help to have readable document with notepad and other editor too.

Yes.

| column 1 | column 2 |
|------------|----------|
| value | <ul><li>value 1</li><li>value 2</li></ul> |
| value | <ul><li>value 1</li><li>value 2</li></ul> |

| column 1 | column 2 |
|------------|----------|
| value | <p>value 1<br>value 2</p> |
| value | <p>value 1<br>value 2</p> |

**Comment by 8tm** [comment]
Mode 3: HTML (for me best one)

<table>
 <thead>
  <tr align="center"><th colspan="3">Collumns</th></tr>
  <tr align="center"><th>First</th><th>Second</th><th>Third</th></tr>
 </thead>
 <tbody>
  <tr>
   <td>First 1</td>
   <td>Second 2<br>Second 2</td>
   <td>Third 1<br>Third 2<br>Third 3</td>
  </tr>
  <tr>
   <td>
    <ul>
     <li>List 1 element</li>
    </ul>
   </td>
   <td>
    <ul>
     <li>List 2 elements (1)</li>
     <li>List 2 elements (2)</li>
    </ul>
   </td>
   <td>
    <ul>
     <li>List 3 elements (1)</li>
     <li>List 3 elements (2)</li>
     <li>List 3 elements (3)</li>
    </ul>
   </td>
  </tr>
 </tbody>
</table>

**Comment by JimLewis** [comment]
> 
> 
> if it was possitble to have a table like following table it was more flexible
> 
> ```
> | column 1 | column 2 |
> |----------|----------|
> | value    | * value 1|
> |          | * value 2|
> |----------|----------|
> | value    | * value 1|
> |          | * value 2|
> ```
> 
> is there any way to do this? because this structure help to have readable document with notepad and other editor too.

I need this too.  Maybe I need to switch to .rst as without this, md will not be practical to use.  Looking for a replacement for word for general purpose open source documentation.

**Comment by eyalroz** [comment]
@Riverlance : That's not what's been asked.

@8tm : You haven't posted the markdown source of your table.

**Comment by nilahnair** [comment]
> Mode 3: HTML (this is the best option in my opinion)
> 
> Collumns
> First	Second	Third
> First 1	Second 2
> Second 2	Third 1
> Third 2
> Third 3
> * List 1 element
> 
> * List 2 elements (1)
> * List 2 elements (2)
> 
> * List 3 elements (1)
> * List 3 elements (2)
> * List 3 elements (3)

How do we do this?

**Comment by damies13** [comment]
@Riverlance & @8tm 

Putting html in the markdown defeats the point of using markdown in the first place, if people need to learn html to use markdown then they may as well just write the whole document in html.

These are suitable as temporary work arounds not solutions.

I'm surprised this issue is closed as I don't see any resolution?

**Comment by Driftr95** [comment]
This does not work for me - 

```markdown
|index|headingType|preStr|headingText|paragraphs|
|---|---|---|---|---|
|0|h3|"\t\t"|Product||
|1|h3|"\t\t"|Features|Explore our product features|
|2|h3|"\t\t"|What we offer|Explore our product features|
|3|h3|"\t\t"|For teams|Explore our product features|
|4|h3|"\t\t"|Executive Leadership|Explore our product features\<br\>Lead with style|
|5|h3|"\t\t"|Marketing|Explore our product features\<br\>Lead with style\<br\>Create better materials|
|6|h3|"\t\t"|Human Resources|Explore our product features\<br\>Lead with style\<br\>Create better materials\<br\>Communicate more efficiently|
|7|h3|"\t\t"|Training & Development|Explore our product features\<br\>Lead with style\<br\>Create better materials\<br\>Communicate more efficiently\<br\>Deliver effective training|
|8|h3|"\t\t"|Operations|Explore our product features\<br\>Lead with style\<br\>Create better materials\<br\>Communicate more efficiently\<br\>Deliver effective training\<br\>Manage systems better|
|9|h3|"\t\t"|Product Development|Explore our product features\<br\>Lead with style\<br\>Create better materials\<br\>Communicate more efficiently\<br\>Deliver effective training\<br\>Manage systems better\<br\>Go to market with visuals|
```
<hr>

produces 

|index|headingType|preStr|headingText|paragraphs|
|---|---|---|---|---|
|0|h3|"\t\t"|Product||
|1|h3|"\t\t"|Features|Explore our product features|
|2|h3|"\t\t"|What we offer|Explore our product features|
|3|h3|"\t\t"|For teams|Explore our product features|
|4|h3|"\t\t"|Executive Leadership|Explore our product features\<br\>Lead with style|
|5|h3|"\t\t"|Marketing|Explore our product features\<br\>Lead with style\<br\>Create better materials|
|6|h3|"\t\t"|Human Resources|Explore our product features\<br\>Lead with style\<br\>Create better materials\<br\>Communicate more efficiently|
|7|h3|"\t\t"|Training & Development|Explore our product features\<br\>Lead with style\<br\>Create better materials\<br\>Communicate more efficiently\<br\>Deliver effective training|
|8|h3|"\t\t"|Operations|Explore our product features\<br\>Lead with style\<br\>Create better materials\<br\>Communicate more efficiently\<br\>Deliver effective training\<br\>Manage systems better|
|9|h3|"\t\t"|Product Development|Explore our product features\<br\>Lead with style\<br\>Create better materials\<br\>Communicate more efficiently\<br\>Deliver effective training\<br\>Manage systems better\<br\>Go to market with visuals|

<hr>

Screenshot [in case it looks different to others: ]
![image](https://user-images.githubusercontent.com/116537600/198764751-c9ec9baa-4174-4a80-86ea-d8efee6aeb2c.png)

**Comment by 8tm** [comment]
> @Riverlance : That's not what's been asked.
> 
> @8tm : You haven't posted the markdown source of your table.

Mode 3: instead of < br > use < p >

```text
| Collumns |||
| --- | --- | --- |
| First | Second | Third |
| First 1 | <p> Second 2 <p> Second 2 | <p> Third 1 <p> Third 2 <p> Third 3 |
| * List 1 element | <p>* List 2 elements (1) <p>* List 2 elements (2) | <p>* List 3 elements (1) <p>* List 3 elements (2) <p>* List 3 elements (3) |
```

| Collumns |||
| --- | --- | --- |
| First | Second | Third |
| First 1 | <p> Second 2 <p> Second 2 | <p> Third 1 <p> Third 2 <p> Third 3 |
| * List 1 element | <p>* List 2 elements (1) <p>* List 2 elements (2) | <p>* List 3 elements (1) <p>* List 3 elements (2) <p>* List 3 elements (3) |

**Comment by sushantsp** [comment]
Why cant we have simple Identifier that this is a text blob that needs to come in one cell only. 
more like put it in triple quote or quadruple quote or something else. <p>, <br> arent the solutions and genuinely defeats the purpose of the markdown like someone said above.
