### ISSUE TITLE
Support for preventing HTTP (unencrypted) embeds

### ISSUE THREAD

**Issue by eloquence** [markdown-it/markdown-it#407]
Embedding unencrypted media on HTTPS sites leads to mixed content warnings. HTTPS sites that accept user-created content may wish to prevent such embeds, since it's an instant way for users to cause breakage across the site.

I believe this should be core functionality, since it's an increasingly important security feature. It may make the most sense to do this at the tokenization stage, preventing tokenization of invalid embeds if this setting is enabled. Thoughts?

**Comment by eloquence** [comment]
After considering it some more: This may be best accomplished via a site-wide CSP and is perhaps out of scope for the parsing stage, especially since Upgrade-Insecure-Requests handles potentially successful requests more gracefully than just preventing them entirely. Self-closing.

**Comment by puzrin** [comment]
See also [validateLink](https://github.com/markdown-it/markdown-it/blob/3353462142d519dfe5b613e4d9e79fa29601ff98/lib/index.js#L307)
