### ISSUE TITLE
Embedding HTML in the Markdown Browser.

### ISSUE THREAD

**Issue by LamboCreeper** [markdown-it/markdown-it#408]
Hi, I've been browsing the internet trying to find an hour for a while now and can't seem too.

Is it possible to embed HTML code within the rendered Markdown?  I have cut down a lot of the content that I am rendering below, but it gives an understanding of what I am trying to achieve.

```html
<script>
var md = window.markdownit({
	html: true,
	linkify: true,
	typographer: true
});
document.getElementById('article_content').innerHTML = md.render('You can see the data in this bar chart:\n\n<canvas id="bc_servers" width="400" height="400"></canvas>');
</script>
```

**Comment by puzrin** [comment]
1. There is online demo for experiments https://markdown-it.github.io/
2. Use http://spec.commonmark.org/ for any formatting details.
