### ISSUE TITLE
Markdown syntax one line below a html tag not converted

### ISSUE THREAD

**Issue by heyrict** [markdown-it/markdown-it#409]
```
<font size=4>
[link](about:blank)
</font>
```
With html enables, `link` in this example won't be converted to a clickable link, but both
```
<font size=4>[link](about:blank)
</font>
```
and
```
<font size=4>

[link](about:blank)
</font>
```
will work. 
It seems that the first example is marked as a "html_block" as a whole.

demo's [here](http://markdown-it.github.io/#md3=%7B%22source%22%3A%22%5Cn%3Cfont%20size%3D4%3E%5Cn%5Blink%5D%28about%3Ablank%29%5Cn%3C%2Ffont%3E%5Cn%5Cn%5Cn%3Cfont%20size%3D4%3E%5Blink%5D%28about%3Ablank%29%5Cn%3C%2Ffont%3E%5Cn%5Cn%5Cn%3Cfont%20size%3D4%3E%5Cn%5Cn%5Blink%5D%28about%3Ablank%29%5Cn%3C%2Ffont%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

**Comment by puzrin** [comment]
That's all according to spec, not a bug http://spec.commonmark.org/0.28/#html-blocks
