### ISSUE TITLE
Fwd: *emphasis* & **strong** markups not working with symbol chars at the inner closing end

### ISSUE THREAD

**Issue by Vdragon** [markdown-it/markdown-it#410]
(Forwarded from [\*emphasis\* & \*\*strong emphasis\*\* markup not working under certain circumstances · Issue \#459 · hackmdio/hackmd](https://github.com/hackmdio/hackmd/issues/459))

This issue can be reproduced when:
* A `symbol_character` is not at the end of the markup(`symbol_character` can either English or Chinese punctuation character, like colon:： and period.。)

AND

* Space character is not immediately after the markup

[demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%2A%2AWARNING%3A%2A%2ADON%27T%20TOUCH%20THE%20CHILD%20%23%20NOT%20WORKING%20%20%5Cn%2AWARNING%3A%2ADON%27T%20TOUCH%20THE%20CHILD%20%23%20NOT%20WORKING%5Cn%5Cn%2A%2AWARNING%3A%2A%2A%20DON%27T%20TOUCH%20THE%20CHILD%20%20%5Cn%2AWARNING%3A%2A%20DON%27T%20TOUCH%20THE%20CHILD%5Cn%5Cn%2A%2AWARNING%2A%2ADON%27T%20TOUCH%20THE%20CHILD%20%20%5Cn%2AWARNING%2ADON%27T%20TOUCH%20THE%20CHILD%20%23%20Somehow%20remove%20the%20colon%20in%20emphasis%20works%20as%20well%20%3A-%2F%5Cn%5Cn%2A%2A%E8%AD%A6%E5%91%8A%EF%BC%9A%2A%2A%E5%88%A5%E5%8B%95%E9%82%A3%E5%80%8B%E5%AD%A9%E5%AD%90%20%23NOT%20WORKING%20%20%5Cn%2A%E8%AD%A6%E5%91%8A%EF%BC%9A%2A%E5%88%A5%E5%8B%95%E9%82%A3%E5%80%8B%E5%AD%A9%E5%AD%90%20%23NOT%20WORKING%2C%20also%20for%20Chinese%20colon%200_o%3F%5Cn%5Cn%2A%2A%E8%AD%A6%E5%91%8A%2A%2A%E5%88%A5%E5%8B%95%E9%82%A3%E5%80%8B%E5%AD%A9%E5%AD%90%20%20%5Cn%2A%E8%AD%A6%E5%91%8A%2A%E5%88%A5%E5%8B%95%E9%82%A3%E5%80%8B%E5%AD%A9%E5%AD%90%5Cn%5Cn%2A%2A%E8%AD%A6%E5%91%8A%E3%80%82%2A%2A%E5%88%A5%E5%8B%95%E9%82%A3%E5%80%8B%E5%AD%A9%E5%AD%90%20%23NOT%20WORKING%20%20%5Cn%2A%E8%AD%A6%E5%91%8A%E3%80%82%2A%E5%88%A5%E5%8B%95%E9%82%A3%E5%80%8B%E5%AD%A9%E5%AD%90%20%23NOT%20WORKING%2C%20also%20for%20Chinese%20period%200_o%3F%5Cn%5Cn%2A%2A%E8%AD%A6%EF%BC%9A%E5%91%8A%2A%2A%E5%88%A5%E5%8B%95%E9%82%A3%E5%80%8B%E5%AD%A9%E5%AD%90%20%20%5Cn%2A%E8%AD%A6%EF%BC%9A%E5%91%8A%2A%E5%88%A5%E5%8B%95%E9%82%A3%E5%80%8B%E5%AD%A9%E5%AD%90%20%23%20Working%20when%20the%20punctuation%20character%20is%20not%20at%20the%20end%20of%20emphasis%20markup%5Cn%5Cn%2A%2A%EF%BC%9A%E8%AD%A6%E5%91%8A%2A%2A%E5%88%A5%E5%8B%95%E9%82%A3%E5%80%8B%E5%AD%A9%E5%AD%90%20%20%5Cn%2A%EF%BC%9A%E8%AD%A6%E5%91%8A%2A%E5%88%A5%E5%8B%95%E9%82%A3%E5%80%8B%E5%AD%A9%E5%AD%90%20%23%20Also%20work%20when%20the%20punctuation%20character%20in%20at%20the%20start%20of%20emphasis%20markup%5Cn%5Cn%2A%2AWARNI%3ANG%2A%2ADON%27T%20TOUCH%20THE%20CHILD%20%20%5Cn%2AWARN%3AING%2ADON%27T%20TOUCH%20THE%20CHILD%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Afalse%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

**Comment by puzrin** [comment]
That works exactly as defined in commonmark spec, see [reference implementation](http://spec.commonmark.org/dingus/?text=**WARNING%3A**DON%27T%20TOUCH%20THE%20CHILD%20%23%20NOT%20WORKING%20%20%0A*WARNING%3A*DON%27T%20TOUCH%20THE%20CHILD%20%23%20NOT%20WORKING%0A%0A**WARNING%3A**%20DON%27T%20TOUCH%20THE%20CHILD%20%20%0A*WARNING%3A*%20DON%27T%20TOUCH%20THE%20CHILD%0A%0A**WARNING**DON%27T%20TOUCH%20THE%20CHILD%20%20%0A*WARNING*DON%27T%20TOUCH%20THE%20CHILD%20%23%20Somehow%20remove%20the%20colon%20in%20emphasis%20works%20as%20well%20%3A-%2F%0A%0A**%E8%AD%A6%E5%91%8A%EF%BC%9A**%E5%88%A5%E5%8B%95%E9%82%A3%E5%80%8B%E5%AD%A9%E5%AD%90%20%23NOT%20WORKING%20%20%0A*%E8%AD%A6%E5%91%8A%EF%BC%9A*%E5%88%A5%E5%8B%95%E9%82%A3%E5%80%8B%E5%AD%A9%E5%AD%90%20%23NOT%20WORKING%2C%20also%20for%20Chinese%20colon%200_o%3F%0A%0A**%E8%AD%A6%E5%91%8A**%E5%88%A5%E5%8B%95%E9%82%A3%E5%80%8B%E5%AD%A9%E5%AD%90%20%20%0A*%E8%AD%A6%E5%91%8A*%E5%88%A5%E5%8B%95%E9%82%A3%E5%80%8B%E5%AD%A9%E5%AD%90%0A%0A**%E8%AD%A6%E5%91%8A%E3%80%82**%E5%88%A5%E5%8B%95%E9%82%A3%E5%80%8B%E5%AD%A9%E5%AD%90%20%23NOT%20WORKING%20%20%0A*%E8%AD%A6%E5%91%8A%E3%80%82*%E5%88%A5%E5%8B%95%E9%82%A3%E5%80%8B%E5%AD%A9%E5%AD%90%20%23NOT%20WORKING%2C%20also%20for%20Chinese%20period%200_o%3F%0A%0A**%E8%AD%A6%EF%BC%9A%E5%91%8A**%E5%88%A5%E5%8B%95%E9%82%A3%E5%80%8B%E5%AD%A9%E5%AD%90%20%20%0A*%E8%AD%A6%EF%BC%9A%E5%91%8A*%E5%88%A5%E5%8B%95%E9%82%A3%E5%80%8B%E5%AD%A9%E5%AD%90%20%23%20Working%20when%20the%20punctuation%20character%20is%20not%20at%20the%20end%20of%20emphasis%20markup%0A%0A**%EF%BC%9A%E8%AD%A6%E5%91%8A**%E5%88%A5%E5%8B%95%E9%82%A3%E5%80%8B%E5%AD%A9%E5%AD%90%20%20%0A*%EF%BC%9A%E8%AD%A6%E5%91%8A*%E5%88%A5%E5%8B%95%E9%82%A3%E5%80%8B%E5%AD%A9%E5%AD%90%20%23%20Also%20work%20when%20the%20punctuation%20character%20in%20at%20the%20start%20of%20emphasis%20markup%0A%0A**WARNI%3ANG**DON%27T%20TOUCH%20THE%20CHILD%20%20%0A*WARN%3AING*DON%27T%20TOUCH%20THE%20CHILD%0A).

That's not a bug of this package. It's better ask at commonmark forum about known issues with asian languages group and their plains. As soon as spec will be changed, we will update logic too. But we can not diverge from spec in advance.

**Comment by tats-u** [comment]
Tentative solution: https://www.npmjs.com/package/markdown-it-cjk-friendly
