### ISSUE TITLE
Where is the source code of the live-demo and how its javascript bundled?

### ISSUE THREAD

**Issue by madexuan** [markdown-it/markdown-it#411]
As the title, do you use the rollup.js to output a commonJs style `https://markdown-it.github.io/index.js`

**Comment by Martii** [comment]
> Where is the source code of the [live-demo](https://markdown-it.github.io/)

It's on a branch of this repo [here](https://github.com/markdown-it/markdown-it/tree/gh-pages).

**Comment by puzrin** [comment]
See https://github.com/markdown-it/markdown-it/blob/3353462142d519dfe5b613e4d9e79fa29601ff98/Makefile#L15

**Comment by madexuan** [comment]
Thx!!! @Martii @puzrin
