### ISSUE TITLE
How to add properties to inline tags?

### ISSUE THREAD

**Issue by hinesboy** [markdown-it/markdown-it#412]
I want `<a>` open in a new window,  need add `target="_block"` to it
I didn't find related information in the API *(maybe I'm not careful enough)* , so I replaced the whole method:
```javascript
markdown.inline.ruler.at('link',function (state) {
    // my link-rule method
})
```
I think it isn't good, I hope you can give some advice I will be very grateful

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer see all alternatives

**Comment by hinesboy** [comment]
Thank you very much! 
I have been reading source code, ignoring the docs 
![image](https://user-images.githubusercontent.com/26454305/33481077-edfa15a6-d6cd-11e7-8913-a59d72f9bfeb.png)
I tried to solve this way, but did not go first to add this method.
Thanks again!
