### ISSUE TITLE
Factoring out the core to support other markup languages?

### ISSUE THREAD

**Issue by alanctkc** [markdown-it/markdown-it#414]
So, this is probably very tangential to this project's goals, but just wanted to see if it's something you'd entertain.

I'm dipping into potentially creating a Javascript parser for [org files](http://orgmode.org/worg/dev/org-syntax.html). There are a couple of partial javascript implementations, but I wasn't totally happy building on their base, so I thought I'd look around to see if any solid Markdown implementation existed. Markdown is similar in that it's an ambiguous syntax and can't really be parsed using a grammar for one of the many parser generators.

Looking at your lib, it looks like a really strong foundation with good testing and a nice architecture. I was noticing that the way rules are structured and how pluggable they are, it may be possible to build parsers for other markup languages on the core of markdown-it.

What would your thoughts be about a little experiment to pull the core out into another js package and see if I can do some rudimentary org parsing with it? If successful, I could see that core lib becoming a dependency of markdown-it and maybe org, reStructuredTest, and other markup formats over time.

Totally understandable if long term vision would just be to keep it simple and markdown-focused. :) There just aren't a lot of base parser implementations out there that suit the markup use case in a more general way.

**Comment by puzrin** [comment]
1. Personally, i think that creating sublibs at early stage is like premature optimization - useless waste of time :). 
2. I see no profit to add dependencies to markdown-it on foreign libs - it will not become better (and may become more difficult to maintain). I can understand your interest in experiment. But you did not explained why this could be interesting for this project or it's authors. That's a collaboration principle - it should be interesting to all participants.
3. You can see in roadmap notes, this parser requires full rewrite to add support for sourcemaps (and, probably, AST).

I'd suggest to copy-paste everything you find useful and move forward.

**Comment by alanctkc** [comment]
All makes sense to me, thanks!
