### ISSUE TITLE
html block behavior different from common mark

### ISSUE THREAD

**Issue by episodeyang** [markdown-it/markdown-it#416]
### Source

```markdown
 <div>
  *hello*
         <foo><a>
  some test that is also
  
and *this* works?
  
  does this work
</div>

this rocks.
```

### Expected output (common mark)

note that the markdown is not parsed for the line in-between

```html
 <div>
  *hello*
         <foo><a>
  some test that is also
<p>and <em>this</em> works?</p>
<p>does this work</p>
</div>
<p>this rocks.</p>
```

### Markdown-it output

note that the markdown is actually parsed for the line in-between

```html
<p>&lt;div&gt;
<em>hello</em>
&lt;foo&gt;&lt;a&gt;
some test that is also</p>
<p>and <em>this</em> works?</p>
<p>does this work
&lt;/div&gt;</p>
<p>this rocks.</p>
```

## Using `<pre>` tag

(identical to the original otherwise)
```markdown
 <div>
  *hello*
         <foo><a>
  some test that is also
  
and *this* works?
  
  does this work
</div>

this rocks.
```

### Commonmark reference output

 <pre>
  *hello*
         <foo><a>
  some test that is also
  
and *this* works?
  
  does this work
</pre>
<p>this rocks.</p>

### Markdown-it output

note that the `*this*` is still parsed.

```html
htmlsourcedebug
<p>&lt;pre&gt;
<em>hello</em>
&lt;foo&gt;&lt;a&gt;
some test that is also</p>
<p>and <em>this</em> works?</p>
<p>does this work
&lt;/pre&gt;</p>
<p>this rocks.</p>
```

**Comment by puzrin** [comment]
- http://markdown-it.github.io/
- http://spec.commonmark.org/dingus/

Please provide your samples via permalinks. I guess, you do something wrong with options. This package pass all CM tests.

**Comment by episodeyang** [comment]
You are right! Thanks! I'm closing this.
