### ISSUE TITLE
How to use plugin in browser

### ISSUE THREAD

**Issue by mnlipp** [markdown-it/markdown-it#417]
I'm not using node.js, I have an old-fashioned server, but I would like to use markdown-it in the browser.

I have succeeded to use the core:
```
<script src="/markdown-it.js"></script>
...
<script>
    var md = window.markdownit(); // Can be found in https://markdown-it.github.io/markdown-it/ "Simple"
</script>
```

However, I fail to get the plugins running. From the documentation, It seems that the only way to get a plugin is "require", This, however, fails in the browser (`require` is node.js specific, right?).

Could please anybody give me a hint how to get the plugin-objects that I need as parameter for `md.use` without using `require`?

**Comment by Odyseus** [comment]
Hello, @mnlipp.

The `require` part that you mention is equivalent to the `window.markdownit()` initialization in browser. The plugin loading is the same in both (browser and node). Most of the plugin READMEs have examples on how to load them in browser.

[emoji plugin example](https://github.com/markdown-it/markdown-it-emoji#init) (Read *Differences in browser*):

```javascript
var md = window.markdownit().use(window.markdownitEmoji);
```

**Comment by mnlipp** [comment]
Okay, thanks. I didn't think of looking in the plugins' documentations (assuming that there should be some general explanation in the core documentation).

**Comment by mnlipp** [comment]
I'm sorry, but there must be a bit more to it. I now have:
```
<script src="/markdown-it.js"></script>
<script src="/markdown-it-abbr.js"></script>
...
<script>
    var md = window.markdownit(); // Fails now!
</script>
```
I.e. I have added the source for the abbr plugin (but haven't even tried to `use` it). This makes the core module fail. I get: `TypeError: window.markdownit is not a function`.

This clearly depends on including the plugin script. Removing it again fixes things. I took `markdown-it-abbr.js` directly from the [dist directory](https://github.com/markdown-it/markdown-it-abbr/tree/master/dist) ("Raw", of course).

**Comment by puzrin** [comment]
It's better to read `browserify` documentation. That's general things, not specific to this project.

**Comment by mnlipp** [comment]
@puzrin: Thanks, but having had a short look at it, I disagree. I don't need another build system in my project (and I *really* don't want to start developing with node.js), I just want to use this great library with its plugins on the client side (i.e. in the browser).

(And though I made a silly mistake in the beginning (deleted comment) and I'm not through with all the plugins yet, @Odyseus approach seems to work fine.)

**Comment by puzrin** [comment]
@mnlipp i mean we have some time constrains and avoid spending it for general programming questions. Browserify [is used here](https://github.com/markdown-it/markdown-it/blob/3353462142d519dfe5b613e4d9e79fa29601ff98/Makefile#L85) to build browser sources for markdown-it and plugins. It worth to learn principle once, and reuse this knowledge many times later :).
