### ISSUE TITLE
Showing HTML tags as output

### ISSUE THREAD

**Issue by exrishu** [markdown-it/markdown-it#420]
Hi, I am trying to transform YML file into the markdown through this custom code but in output am getting the HTML tags as here -:

`YOU ARE SMARTER THAN <strong>YOURSELF</strong>`

and in YML file it is like 

`YOU ARE SMARTER THAN **YOURSELF**`

here is the custom code:
```
const md = MarkdownIt({
html:true
})
```
when I checked the source code am getting `&lt;strong&gt; `  , Please help me to solve this issue. How to config my md.

**Comment by puzrin** [comment]
No idea how to do it. This question seems not related to this package.
