### ISSUE TITLE
Mathjax support with parsed markdown fails

### ISSUE THREAD

**Issue by auser** [markdown-it/markdown-it#421]
Hi markdown-it team,

I am having a bit of trouble with an edgecase working with mathjax. I have worked through every latex/katex/mathjax plugin I could find, but none of them seem to help with this particular issue.

I should note at the offset that markdown-it + markdown-it-mathjax plugin parses most equations properly, except when there is markdown syntax in the equation.

Currently, I have a markdown document with a latex formula that looks like this:

```math
\begin{equation}c_i = \begin{cases}
- \log{(\hat{y}_i)} & \text{for }y_i = 1 \\
- \log{(1 - \hat{y}_i)} & \text{for }y_i = 0
\end{cases}\end{equation}
```

Notice the `-` in the equation. Markdown it sees these `-` marks and parses them as `li` elements which breaks the latex rendering (as latex doesn't know what to do with `<ul><li>`. Is there a way to tell markdown-it to skip rendering anything inside of the `\begin{equation}` and `\end{equation}` syntax? Alternative suggestions work too... I'm kind of stuck on this issue.

Thanks!

**Comment by puzrin** [comment]
You should ask plugin's author, we have no relation to `markdown-it-mathjax`.

**Comment by auser** [comment]
Oh, I suppose I was asking more about how you would just tell markdown-it to ignore a section upon encountering a sequence. I'm blown away by how quickly you responded!

**Comment by puzrin** [comment]
There no way to let parcer magically ignore things you wish. You should create rule for new block type, and renderer for it.

I would start with [fenced block](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_block/fence.js), modify start/stop conditions and so on.

There are some [general recommendations](https://github.com/markdown-it/markdown-it/tree/master/docs) for plugin writers.

**Comment by auser** [comment]
@puzrin Sooo... I am _almost_ to the point where it's working, but I can't quite finish it up. The issue is that I can get the text to render, but I'm not sure it's working. I'm not entirely certain the rendering is working... when I do it like it is in the gist, it just renders the equation over and over, however if I break it up into multiple blocks, it renders the start and end markers.

Mind taking [a peek](https://gist.github.com/auser/1ee9f4294fce3035be5c5fa6f7fcf6b4#file-markdown-it-ignore-block-js-L15-L17)?
