### ISSUE TITLE
[question] How to write matcher for native unicode Emoji

### ISSUE THREAD

**Issue by ivawzh** [markdown-it/markdown-it#422]
Hi, I am not sure if this is a right place for this kind of question. I am happy to move this to Slack or a mail list if you give me a link.

I want to write a plugin to parse native Unicode emoji into HTML span. Is this possible?

If it's possible, I have tried matching Unicode Emoji with js regex like `\\u{1f4af}`, code here: https://github.com/ivawzh/markdown-it-emoji-mart/blob/78bf5ff0b47f4087e15b57a5227048001cbd28a4/lib/data/native_full.json#L2-L5.
However, code above does not work. Would you please give me some clues how the markdown-it matching mechanism works?

**Comment by puzrin** [comment]
Due time limits i can't help with debugging or discuss generic questions.

Simple approach is the same as in markdown-it-emoji you cloned - scan all text tokens, then search content via regexp and replace with new token types. And render later as you need.

Probably, you need to add tests for your generated regexps and make sure those are correct.

**Comment by puzrin** [comment]
Also see https://github.com/twitter/twemoji, it may give you some ideas.
