### ISSUE TITLE
Question about plugins. Making sections

### ISSUE THREAD

**Issue by brenwell** [markdown-it/markdown-it#423]
Good day everyone,

I would like to write a plugin which would allow me to have mark down such as the following...

```md
++++Section 1++++

# This is section 1
It will be separated from section 2

++++Section 2++++

# This is section 2

```

And would like the end result to be something like this...

```js
sections: [
    {
        name: "Section 1",
        content: "<h1>This is section 1</h1><p>It will be separated from section 2</p>"
    },
    {
        name: "Section 1",
        content:  "<h1>This is section 2</h1>"
    }
]
```

I have a few questions, 
First is this realistic?
Are you aware of a plugin doing this already (couldn't find it via npm)
And If there isn't one could you point me in the right direction. I have a quick read through the api and it seems like its a bit tricky where I should plugin to.

Any tips are greatly appreciated, thanks!

**Comment by puzrin** [comment]
Sorry, i don't see why your question can be related to this package.

**Comment by brenwell** [comment]
I would like to build a plugin to do the above and was hoping you get suggest where I should tie in. I don’t see how that is not relevant but whatever.

**Comment by puzrin** [comment]
@brenwell i don't see how this markup is related to markdown and how output data related to one produced by this package. Correct me, if i'm wrong. Also note, due time constrains i can not discuss too generic questions.
