### ISSUE TITLE
code block first line indentation not correct

### ISSUE THREAD

**Issue by ZhouHansen** [markdown-it/markdown-it#424]
some markdown like:
 \`\`\`js
const css = require('sheetify')
const html = require('bel')
css('tachyons')
\`\`\`

will generate:
```js
const css = require('sheetify')
  const html = require('bel')
  css('tachyons')
```

**Comment by puzrin** [comment]
[works as expected](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%60%60%60js%5Cn%20%20const%20css%20%3D%20require%28%27sheetify%27%29%5Cn%20%20const%20html%20%3D%20require%28%27bel%27%29%5Cn%20%20css%28%27tachyons%27%29%5Cn%60%60%60%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)
