### ISSUE TITLE
It seems there are some bugs when parse strong tag(**xxx**)

### ISSUE THREAD

**Issue by xiaodi0003** [markdown-it/markdown-it#425]
**“b”**
is parsed correctly

but
a**“b”**，c**“d”>“e”**
is parsed mistakenly

**Comment by puzrin** [comment]
Works according to spec, as [reference implementation](http://spec.commonmark.org/dingus/?text=a**%E2%80%9Cb%E2%80%9D**%EF%BC%8Cc**%E2%80%9Cd%E2%80%9D%3E%E2%80%9Ce%E2%80%9D**%0A%0A**%E2%80%9Cb%E2%80%9D**)

Not a bug.
