### ISSUE TITLE
Using markdown-it plugin with the `parse` function?

### ISSUE THREAD

**Issue by laurent22** [markdown-it/markdown-it#426]
I'm using the `parse()` function of markdown-it to do some custom rendering. My code is something like this:

````
const md = new MarkdownIt({
	breaks: true,
	linkify: true,
});

md.use(require('markdown-it-katex'));

const env = {};
const tokens = md.parse(body, env);

// Custom processing and rendering of tokens...
````

This works well in general, however I cannot get plugins to work with this. For regular rendering, the tokens will contain rendering information (html tags and attributes), which I can use and augment with my application code. For the above markdown-it-katex plugin however the token is like below, without the rendering the plugin would normally be doing.

![capture](https://user-images.githubusercontent.com/1285584/34788026-9ae161e0-f639-11e7-841b-4cb986a1f396.PNG)

So I'm wondering is there any way to get the plugin to apply its transformation when using the `parse()` function?

**Comment by puzrin** [comment]
You should contact plugin author with such request. Custom tokens format depends on plugin only.

Or you can scan tokens, extract desired part, manually run renderer on it and replace content in original as you need.
