### ISSUE TITLE
Security issue with input sanitation

### ISSUE THREAD

**Issue by Arve** [markdown-it/markdown-it#427]
The following snippet allows insertion of arbitrary event handlers into user-submitted data when executed in a client/browser:

    import mdIt from 'markdown-it'; // imports default export as "mdIt"

    var md = "<p onmousemove='alert(\"foo\")''>blablabla</p>";

    window.onload = function(){
        var t = mdIt({  html: true }).render(md);
        document.body.innerHTML += t;
    }

**Expected behavior:**

\<script\> tags and unknown/unvetted attributes get stripped by default.

**Actual behavior:**

Using ` html: true` when calling/parsing using markdown-it causes any mouse move over the paragraph containing "blablabla" to cause an alert in the web browser.  

**Suggested fix:**

While I realize that allowing inline HTML in markdown makes for a larger target surface, blanket trusting input with this attribute enabled is very much the wrong fix. 

The correct approach here is to parse the resulting document fragment and remove all tags and attributes that are not explicitly deemed safe by default - in other words, in a future-proof version, a whitelist approach must be used in favor of blacklisting properties and tags.

**Comment by puzrin** [comment]
That's out of this project scope. Output is safe by default. If you enable html, it's your responsibility to use external sanitizer when needed. This package is about markdown only.

**Comment by Arve** [comment]
Output is safe unless implementors has valid reasons for allowing html or other markup in it.   My argument here is that enabling HTML should _still_ be safe, and allowing unsafe HTML should be its own option - e.g. `unsafe_html: true`.

Doubly so, when this plugin prides itself on being "safe by default".  90% of people integrating this plugin are not going to read beyond "Safe by default", and assume common options, which allowing html is to be safe.

**Comment by puzrin** [comment]
There are 2 ways to make markdown output safe and keep users happy:

1. Allow html for everything unsupported and use complicated sanitizer
2. Disable html and allow user extend markup via plugins.

We selected a second way. That's all was considered/discussed many times and i see nothing new to talk about.
