### ISSUE TITLE
The url contains spaces, will be abnorma.

### ISSUE THREAD

**Issue by suxiaoxin** [markdown-it/markdown-it#428]
### Input
```
![](style/images/logo.png#a b)
```

### Ouput
```
<p>![](style/images/logo.png#a b)</p>
```
### Expect
```
<p><img src="style/images/logo.png#a b" alt=""></p>
```

**Comment by puzrin** [comment]
http://spec.commonmark.org/0.28/#links

Whitespaces should be escaped.

**Comment by wulmer** [comment]
Looks, like spaces in pointy brackets are now allowed since https://spec.commonmark.org/0.29/#links.
Any chance to get support for them?

**Comment by rlidwka** [comment]
@wulmer please provide an example of what is now allowed

I don't see any relevant changes in the spec

**Comment by rlidwka** [comment]
> Looks, like spaces in pointy brackets are now allowed since https://spec.commonmark.org/0.29/#links.

if you are talking about this, it's already supported:

```md
[link](</my uri>)
```

**Comment by wulmer** [comment]
Hi @rlidwka , close, I was talking of pure pointy bracket links like:
```
<https://my.server/my file.txt>
```

**Comment by rlidwka** [comment]
spaces are not accepted there, as you can verify on https://spec.commonmark.org/dingus/

**Comment by wulmer** [comment]
You are right, I am sorry, I somehow misread the specification. Thanks for clarifying!
