### ISSUE TITLE
Smartquotes bug with final quote before newline.

### ISSUE THREAD

**Issue by jgerigmeyer** [markdown-it/markdown-it#430]
If a quoted word (with either single- or double-quotes) is the final thing before a newline, it is not converted correctly into smartquotes. There also seems to be a related bug with a quoted word as the first word after a newline.

Test case: https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%27this%27%5Cnand%20%5C%22that%5C%22.%5Cn%5Cn%5C%22this%5C%22%5Cnand%20%5C%22that%5C%22.%5Cn%5Cn%5C%22this%5C%22%20and%5Cn%5C%22that%5C%22.%5Cn%5Cn%5C%22this%5C%22%20and%5Cn%5C%22that%5C%22.%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22lang-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D

**Comment by puzrin** [comment]
Thanks for clear report. Will be fixed in 2-3 weeks

**Comment by rlidwka** [comment]
fixed, thanks!
