### ISSUE TITLE
Detecting written language changes in parser/renderer?

### ISSUE THREAD

**Issue by matatk** [markdown-it/markdown-it#431]
Thank you for markdown-it :-). I was wondering, if one had the following markdown code containing some inline HTML...

```markdown
Here is some text <span lang="fr">en français</span>.
```

Is possible for the parser to pass the `lang` attribute to the token representing the text within the span? If not, would I need to change the existing parser rules (e.g. override some of [lib/rules_inline/html_inline.js](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/html_inline.js))?

The reason I ask is that I've written [a spell-checking plugin for markdown-it](https://github.com/matatk/markdown-it-spellcheck). The plugin uses renderer rules to extract the text (including image `alt` text and HTML code blocks).  I would like it to have the ability to spell-check words in their own language (or at least not count them as mis-spellings in the current language).

*I'd like to extend this in future to allow certain parts of the document to be ignored by the spellchecker, possibly using [the `spellcheck` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck), though some escape mechanism will be needed, particularly for fenced code blocks.*

*I am also working on a tool to extract the text from HTML blocks (taking into account attributes such as `alt` and `lang` there), so an alternative to modifying markdown-it to supply the `lang` attribute could be to take even *inline* HTML out and parse that with the other tool (rather than parsing it as inline HTML within markdown-it), but that would need some alterations to markdown-it's parser too.*

My questions are:
* Do you think that using the `lang` attribute on `<span>` or `<div>` tags is an appropriate way to indicate changing language within a markdown document?
* If markdown-it's parser doesn't pass `lang` attributes to contained tokens now, is it something you'd like me to add to core, or is it better in a plugin?

**Comment by puzrin** [comment]
See [demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22Here%20is%20some%20text%20%3Cspan%20lang%3D%5C%22fr%5C%22%3Een%20fran%C3%A7ais%3C%2Fspan%3E.%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22debug%22%7D%7D) with your text.

IMHO markdown markup is not supposed to understand html details. It can catch html tags as "raw text for output" but it does not understand content. If you wish, you can scan resulting tokens and try to extract more info, but this is out of scope to discuss here.

PS. everything is supposed to be added via plugins. Core acceptance policy is very conservative.
