### ISSUE TITLE
Can I access particular html tag from markdown file?

### ISSUE THREAD

**Issue by kalpeshsingh** [markdown-it/markdown-it#434]
**Use case**

I have used `<template>` tag in my markdown and I want to access it so that I can extract content from that tag and use it.

**Example**
```
<template>
    {
        "author": "Kalpesh Singh",
        "date": "24 January, 2017"
    }
</template>
```

If I have content from this template then I can use `JSON.parse()` to get content as JS object from this tag.

Is there any workaround or hack available to solve my issue?

**Comment by puzrin** [comment]
IMHO fenced block should be ok for such type of content. Please use commonmark forum for generic questions. This repo is only about specific implementation.
