### ISSUE TITLE
How to add [cut]?

### ISSUE THREAD

**Issue by iliakan** [markdown-it/markdown-it#435]
Hello,

I'm implementing `[cut]` functionality for the editor. 
It should "cut" the rest of the content before the rest of processing takes place.

Can I do it with a plugin or I should override `parse` or something else?

**Comment by puzrin** [comment]
IMHO cutting text is out of parser responsibility. I'd suggest to generate `<!-- CUT -->` in output at root level, then drop tail with regexp when needed. This can be done via plugin.

**Comment by iliakan** [comment]
How to instantiate such a plugin?

**Comment by iliakan** [comment]
Usually, I use something like `md.core.ruler.before('replacements', 'remove_cut', removeCut);`

**Comment by puzrin** [comment]
Since this should be at top level only, i would to it as block rule, from fenced one

**Comment by iliakan** [comment]
I did not touch the editor for a while, and not remember its structure.

What should I write instead of `md.core.ruler.before('replacements', 'remove_cut', removeCut);`? (where removeCut is the plugin)

Thank you.

**Comment by iliakan** [comment]
It should work even if inside a fenced block. For instance, this should work:
```
'''code
[cut]
'''
```

That's syntactically incorrect, but I guess the cut should happen.

**Comment by puzrin** [comment]
Just drop everything from `fenced` block rule, leaving only check for `<cut>` or any other marker you wish. + check that you are at top level. I suggested `fenced` rule because because it produces single token at block level.
