### ISSUE TITLE
Emphasis inside words

### ISSUE THREAD

**Issue by chadananda** [markdown-it/markdown-it#439]
I'm trying to add emphasis to individual letters or groups of letters inside a word. This does not seem to render correctly. It seems to require the entire word be surrounded by underscores. Is this a bug?

```
_super_    ->   <em>super<em>
su_per_    ->    su_per_ 
s_up_er    ->    s_up_er
```

**Comment by puzrin** [comment]
That's not a bug. Please, read commonmark spec http://spec.commonmark.org/
