### ISSUE TITLE
Should skip comment

### ISSUE THREAD

**Issue by taoqf** [markdown-it/markdown-it#440]

**Comment by taoqf** [comment]
Why this issue is closed?

**Comment by puzrin** [comment]
It looked like garbage at creation time (with empty body).

[Everything works needed](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3C!--%20comment%20--%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Afalse%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D). All details about html markup are described in commonmark spec.

**Comment by taoqf** [comment]
https://github.com/AlanWalk/markdown-toc
How could I use this plugin then?

**Comment by puzrin** [comment]
I don't know. That package is not related to this one.

**Comment by taoqf** [comment]
Thanks anyway

**Comment by jcubic** [comment]
I have similar question How to add comment to output html? I want to add TODO comment that should not be rendered in html.

**Comment by puzrin** [comment]
You should enable html, it's disabled by default.

**Comment by jcubic** [comment]
@puzrin thanks, it work perfectly.
