### ISSUE TITLE
can not stop escapeHTML

### ISSUE THREAD

**Issue by joe223** [markdown-it/markdown-it#442]
if input string like this,
```javascript
let str = `
<button @click="hello">hello</button>

# markdown content
`
console.log(md.render(str))
```
then, we got 
```
<p>&lt;button @click=&quot;hello&quot;&gt;hello&lt;/button&gt;</p>
<h1>content</h1>
```

set configure as show below:
```javascript
const md = require('markdown-it')({
  html: false
})
```

**Comment by puzrin** [comment]
[demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Cbutton%20click%3D%5C%22hello%5C%22%3Ehello%3C%2Fbutton%3E%5Cn%5Cn%3Cbutton%20%5C%22click%3D%5C%22hello%5C%22%3Ehello%3C%2Fbutton%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

Works as expected. `@click` is not valid attr name. The same in reference parcer http://spec.commonmark.org/dingus/

**Comment by joe223** [comment]
thanks so much，I should translate `@` into `__at__` or some text else.
