### ISSUE TITLE
plugin help: enable ?[x](y) as variant of [name](href)

### ISSUE THREAD

**Issue by networkimprov** [markdown-it/markdown-it#443]
Hi and thank you for this wonderful library!

I've written two rendering plugins for link_open and image which are simple and effective. I would like to extend my link_open plugin so that if `?` (but not `\?`) precedes `[name](href)` I can detect that in an env field. Is it possible to change the env from a .ruler function? If not how should I flag a `?` prior to link_open?

link_open rendering plugin so far (this works fine)
```
   mnm._mdi.renderer.rules.link_open = function(iTokens, iIdx, iOptions, iEnv, iSelf) {
      var aHref = iTokens[iIdx].attrs[iTokens[iIdx].attrIndex('href')];
      if (!sUrlStart.test(aHref[1])) {
         // special treatment for relative URL
         var aParam = aHref[1].replace(/^this_/, iEnv.msgId+'_');
         aHref[1] = '?an=' + encodeURIComponent(aParam);
      }
      return iSelf.renderToken(iTokens, iIdx, iOptions);
   };
```
The purpose of `?[x](y)` is to create a "mount" point in the HTML for a Vue form component.

Similarly, I'd like to make `!![alt](href)` represent a video object, implementing it in my .rules.image plugin.

**Comment by puzrin** [comment]
That should not be done via renderer hacks. You are expected to create new tokenizer rule, based on [link](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/link.js) or [image](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/image.js).

**Comment by networkimprov** [comment]
The check for `!` in [image](/markdown-it/markdown-it/blob/master/lib/rules_inline/image.js) is hardcoded, so it's not possible to re-use that function for `?[x](y)` or `!![alt](href)`. Would you accept a patch enabling an optional argument with alternate prefix (or flag to skip the check for `!`) so that function is re-usable?

**Comment by puzrin** [comment]
No, such patch will not be accepted. You should do your own copy.

**Comment by networkimprov** [comment]
Sorry to intrude again... I searched for an HTML attribute escape function and found many escape references, but nothing clearly labeled as encoding attributes, e.g.

`'<div id="' + attrEscape(uid) + '"></div>'`

Which is what my plugin for a Vue form would generate. Could you point out the correct function?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/42e388224b92c41208941093e15b5c0dc486464c/lib/renderer.js#L177
