### ISSUE TITLE
Proactive prevention of homograph attacks

### ISSUE THREAD

**Issue by julianlam** [markdown-it/markdown-it#444]
Hello there,

If a user tries to craft an url using punycode, markdown-it's linkifier seems to display the ASCII version in the `href`, and the unicode version in the link **text**, which seems backwards. Please see the following image:

![selection_315](https://user-images.githubusercontent.com/923011/37307118-3f0ce1ee-2610-11e8-85fb-2002922dbc49.png)

The following changeset by @rlidwka in 2015 shows the punycode library added to the linkifier to allow this behaviour.

https://github.com/markdown-it/markdown-it/commit/77e8b6cad03faccfd8441e955b3b955a6173faec#diff-6d186b954a58d5bb740f73d84fe39073

Now, major browsers will intercept these attacks and display the punycode variant to the end user in the browser address bar, etc... however is there a specific reason why markdown-it explicitly and wilfully shows the unicode version to the end user in the link text, potentially allowing a homograph attack to be carried out?

I should also point out that regardless of whether or not you paste the url in punycode or unicode, Markdown-it's linkifier will display the unicode variant:

![image](https://user-images.githubusercontent.com/923011/37307708-2cd8a88a-2612-11e8-9df2-c5791d7106ea.png)

One can argue that the end -user ought to be careful and check the address bar to ensure they're on the correct site, but additional protections only help prevent these sorts of vulnerabilities.

I'd argue that markdown-it might better serve its users by proactively displaying the ascii punycode if the punycode library detects a unicode string in the link text **or** href... but if not, I'd still appreciate some justification.

Thank you for your time :smile:

**Comment by julianlam** [comment]
For context, here's [the Chromium team's bit on IDN and homograph attacks](http://www.chromium.org/developers/design-documents/idn-in-google-chrome)

Of course, I'm not suggesting that markdown-it adopt Chromium's list of logic for determine which urls to punycode-ify and which to display as unicode... but again I'd argue that a heavy-handed approach to dealing with unicode urls is preferable until such time that a js variant of [IDNToUnicodeOneComponent](https://cs.chromium.org/chromium/src/components/url_formatter/url_formatter.cc?l=520&gs=cpp%253Aurl_formatter%253A%253A%253Canonymous-namespace%253E%253A%253AIDNToUnicodeOneComponent(const%2Bunsigned%2Bshort%2B*%252C%2Bunsigned%2Blong%252C%2Bstd%253A%253Abasic_string%253Cbase%253A%253Achar16%252C%2Bbase%253A%253Astring16_char_traits%253E%2B*)%2540chromium%252F..%252F..%252Fcomponents%252Furl_formatter%252Furl_formatter.cc%257Cdef&gsn=IDNToUnicodeOneComponent&ct=xref_usages) is created.

**Comment by puzrin** [comment]
That feature was to make text human-friendly. For example, when user copy-paste from browser address line. Since user can manually type ANY text for any link, this can not be considered as significant additional weakness. Also, you can change this behaviour if you wish.

I see nothing to discus/change.
