### ISSUE TITLE
strikethrough does not work with single tilde

### ISSUE THREAD

**Issue by artin-phares** [markdown-it/markdown-it#446]
By [GFM spec](https://github.github.com/gfm/#strikethrough-extension-) strikethrough is enabled by wrapping in pair of `~single tildes~`, but `markdown-it` requires at least `~~two tildes~~`.

**Comment by puzrin** [comment]
Hmm... i suspect it worked different when been implemented.

Problem is that existing GFM spec for strikethrough will conflict with [subscript extension](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22H~2~O%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D) of pandoc. Need acceptable resolution before change.

**Comment by puzrin** [comment]
This issue has no good resolution right now.

- If you need exact GFM behaviour, try https://github.com/npm/marky-markdown
- I've posted to github contacts about spec conflict, but no much hope...
- If anyone has time and patience, it worth to discuss possible solution on commonmark forum (because this repo is about implementation only).

**Comment by puzrin** [comment]
For tracking:

- https://github.com/github/cmark/issues/84#issuecomment-373125944
- https://github.com/github/cmark/issues/71#issuecomment-373125190
- https://talk.commonmark.org/t/why-there-is-no-syntax-for-subscript-and-supscript/586

I can keep this issues open. But resolution on spec level needed to move forward. If we change strikethrough behaviour to existing GFM spec, this will be ass pain for subscript.

**Comment by puzrin** [comment]
https://github.com/github/cmark/issues/99#issuecomment-405127309

They updated spec. I think issue can be closed now.
