### ISSUE TITLE
some image formats supplied as data URLs are not recognized

### ISSUE THREAD

**Issue by artin-phares** [markdown-it/markdown-it#447]
`markdown-it` does not recognize some images supplied as data URIs:  `bmp`, `svg+xml`, `tiff`.  

Since `gif`, `png`, `jpeg` and `webp` are [already supported](https://github.com/markdown-it/markdown-it/blob/c9199b582dbe80fbbed0a0bcb72b4080d864250c/lib/index.js#L33), can we extend that list?

**Comment by puzrin** [comment]
Works as expected. No plans to track all possible extensions. You can override validator for your needs.

**Comment by artin-phares** [comment]
> No plans to track all possible extensions.

Any reasoning behind that?

**Comment by puzrin** [comment]
Almost zero added value. That's an endless process, out of project scope. No goals to implement everything possible or everything users can imagine. Goal is to provide flexible API.

**Comment by artin-phares** [comment]
Yeah, but we can relax `/^data:image\/(gif|png|jpeg|webp);/` to `/^data:image\/.*;/` and avoid infinite requests to add new formats. What do you think?

**Comment by puzrin** [comment]
I think API allows you to be independent on my opinion, and requests to change defaults are subjective & not welcome. I prefer to see there minimal reasonable set of strict rules.

**Comment by artin-phares** [comment]
Hm, I doubt this is subjective request, but rather tend towards `CommonMark` spec this project based on. 
 And spec does not introduce any limits for images.  

Using custom configuration for this case every time is inconvenient.  

Although, I understand that changing defaults may cause some backward compat issues for existing users.  So, anyway..

**Comment by artin-phares** [comment]
I've ended up with

```js
const defaultValidateLink = md.validateLink;
md.validateLink = url => /^data:image\/.*?;/.test(url) || defaultValidateLink(url);
```
