### ISSUE TITLE
Use plugins when running from command line

### ISSUE THREAD

**Issue by dsbert** [markdown-it/markdown-it#448]
It would be helpful to pass in plugins when running `markdown-it` from the command line. Assumption is that these plugins will already be installed. To set options for the plugins, maybe pass in a file instead of a list of plugins.

`markdown-it --options .markdownrc somefile.md`

```
// .markdownrc
{
  "plugins": [
    { 
      "plugin": "markdown-it-anchor" ,
      "options": {}
    }
  ]
}
```

**Comment by puzrin** [comment]
Sorry, no plans to spend efforts to extend CLI features. I'd suggest to create your own wrapper. If it will be designed well, it may be considered to merge into upstream.
