### ISSUE TITLE
Line breaks inside the output

### ISSUE THREAD

**Issue by dhoko** [markdown-it/markdown-it#449]
Hey, 

I don't know if it's an issue, I didn't find a way to remove this :/
cf https://codesandbox.io/s/r0xmrk9wwn

Marked output vs markdown-it, why do you replace `\n` by `<br>` and keep the `\n` ?

**Comment by puzrin** [comment]
To make output look better. I would not recommend compare output with marked. This parser follows commonmark spec. If you suspect something goes wrong - correct actions are to read spec and compare  with reference implementation (commonmark.js).

**Comment by dhoko** [comment]
Ok let's try with commonmark -> https://codesandbox.io/s/4ql044p3l7

Same output as marked `<p>dew<br>dew<br>dew</p>`. 
It doesn't try to make it "look better" because it's an output. Adding an extra \n can create an issue.
Ex: you have a md input, you convert it to HTML via markdown-it, and you put the HTML inside a WYSIWYG editor :boom: you now have extra lines.

**Comment by puzrin** [comment]
See spec first :). http://spec.commonmark.org/0.28/#example-189 or search `<br` in text. All examples go with `\n`.

You can customize output renderer for your needs https://github.com/markdown-it/markdown-it/blob/6fa70c57e9e68170015ddcdf374bf7538d7a591b/lib/renderer.js#L104-L109. Everything is tuneable.

**Comment by dhoko** [comment]
Great thx :+1:
