### ISSUE TITLE
Link resolution plugin point

### ISSUE THREAD

**Issue by dwaite** [markdown-it/markdown-it#45]
I'm looking at making a plugin for the [wintersmith](http://wintersmith.io) static site generator to use markdown-it rather than marked.

One feature wintersmith has is the ability to link to pre-build content, and have the link be rewritten while building the static content to be a correct link to the final location. It adds this functionality by [patching](https://github.com/jnordberg/wintersmith/blob/master/src/plugins/markdown.coffee#L11-L41) marked.

Is this something that markdown-it would consider adding as a proper feature?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer

You can override existing renderer, this feature already exists.

**Comment by dwaite** [comment]
Is the proper way to do this to override link_open (and image) in the renderer with a version that resolves the url? 

It seems more appropriate to modify the token data at an earlier stage, so that any other custom rules will get resolved URLs.

**Comment by puzrin** [comment]
You can do it in `core` chain too. https://github.com/markdown-it/markdown-it-for-inline

It's up to you - depends on your need.

**Comment by dwaite** [comment]
I overrode link_open, but am only modifying the token and passing control on. I'll modify image after I refactor the code.

This should let other overrides work as long as the ordering is correct. 
https://github.com/dwaite/wintersmith-markdown-it/blob/master/index.coffee#L28-L55
