### ISSUE TITLE
Fine-grained control over disabling/enabling headings

### ISSUE THREAD

**Issue by MartinMuzatko** [markdown-it/markdown-it#453]
hey there!

I would love to be able to disable usage of H1.
Do I have to write a plugin to disable that? Afaik there is no rule (and also rules are not documented as stated here:  #289 )

Thanks!

**Comment by puzrin** [comment]
Yes. You do.

Probably, the most easy way is to override default renderer for Hx, and shift down output level or replace H1 with P.

**Comment by MartinMuzatko** [comment]
hm. I couldn't find a plugin that does. What do you think speaks against including this control in the rules?

**Comment by puzrin** [comment]
Sorry, customization requests are not accepted. Everything should be done on user side, via plugins or other way. That's a good place to start with https://github.com/markdown-it/markdown-it/tree/master/docs
