### ISSUE TITLE
Access to the render function from a custom highlight function

### ISSUE THREAD

**Issue by simondean** [markdown-it/markdown-it#456]
Hi.  I've trying to use `markdown-it` together with the https://www.npmjs.com/package/markdown-it-attrs extension.  

I'm passing a custom `highlight` function to `markdown-it` to generate custom code block HTML

```
var md = markdownIt({
        linkify: true, html: true,
        highlight: function (str, lang) {
            if (highlightJs.getLanguage(lang)) {
                try {
                    return '<pre class="highlight lang-' + lang + '"><code>' +
                        highlightJs.highlight(lang, str, true).value +
                        '</code></pre>';
                } catch (__) { }
            }

            return '<pre class="highlight"><code>' + md.utils.escapeHtml(str) + '</code></pre>';
        }
    })
    .use(markdownItAttrs);
```

The problem I'm facing is that there's no way to access `markdown-it`'s `slf.renderAttrs(token)` from within a custom `highlight` function.  Because I can't access `slf.renderAttrs(token)`, there's no way for to take advantage of the rendering that the https://www.npmjs.com/package/markdown-it-attrs extension provides.  

I can think of a couple of ways of solving this: 
* `markdown-it` passes the `slf` object as a new third argument when it calls a custom `highlight` function.  
* `markdown-it` makes either `slf` or `slf.renderAttrs(token)` available on `this` when it calls a custom `highlight` function.  

I've created some custom code for this issue here: 
* https://github.com/simondean/markdown-it-issues/blob/master/highlight-attrs/index.js

**Comment by puzrin** [comment]
IMHO this request is too specific. You can override fenced renderer as you wish if default features are not enougth.

**Comment by simondean** [comment]
Hi @puzrin.  The issue is that the `fence` function in https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.js#L77 has access to functionality that a custom `highlight` function does not.  The `fence` function can call the `slf.renderAttrs` function whereas a custom `highlight` function cannot.

**Comment by simondean** [comment]
Thanks for the feedback @puzrin.  I'll raise an issue on issue tracker for the extension https://github.com/arve0/markdown-it-attrs
