### ISSUE TITLE
Custom highlight function cannot access the attributes of the fence token

### ISSUE THREAD

**Issue by simondean** [markdown-it/markdown-it#457]
A custom `highlight` function cannot access the attributes of the fence token.  The built-in [`fence` function](https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.js#L39) can access the attributes of the token with the following code but a custom `highlight` function has no way to do this.  

```javascript
var token = tokens[idx]
...
tmpAttrs = token.attrs ? token.attrs.slice() : [];
```

This means that any custom attributes added to the current token by extensions (e.g. a custom class name added by an extension) are available to the `fence` function but not available to a custom `highlight` function.

**Comment by puzrin** [comment]
I see no reasons, why highlighter should get additional params. Do you have good examples. why this can be useful for all (not abstract concept, but real example)? In other case you'd better to override default fenced renderer with your own implementation.

**Comment by simondean** [comment]
Hi.  The real world example is https://www.npmjs.com/package/shins, which renders HTML for API documentation.  `shins` uses `markdown-it` and supports the https://github.com/arve0/markdown-it-attrs plugin for adding custom attributes to markdown elements.  

The `markdown-it-attrs` plugin is failing to add attributes to code fences, as `shins` passes a custom `highlight` function to `markdown-it`, which short-circuits `markdown-it`'s code for rendering a code fence token's attributes (including the attributes added by the `markdown-it-attrs` plugin.  

Thanks for the suggestion of overriding the default `fence` renderer.  I've taken that approach in PR https://github.com/Mermade/shins/pull/33

**Comment by puzrin** [comment]
Thanks. `markdown-it-attrs` syntax is not stable (not approved in spec yet) and i'd like to avoid API change "in advance". IMHO if you use specific hacks for highlighter, it would be more logical to hack fenced renderer too and keep things in one place (at your side).
