### ISSUE TITLE
Single smartquote bug

### ISSUE THREAD

**Issue by AleshaOleg** [markdown-it/markdown-it#460]
Seems like, smartquote not working properly if it stay single.

Here is an example - https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%5C%22%5Cn%5C%22%5C%22%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Atrue%2C%22langPrefix%22%3A%22%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D

Or it shouldn't work for this case? Expected result for me is:
```
<p>“<br>
“”</p>
```

**Comment by puzrin** [comment]
I see no problems. Smartquoter is for real wold, not for artificial cases.
