### ISSUE TITLE
md.render on japanese character set when no space is present

### ISSUE THREAD

**Issue by leom** [markdown-it/markdown-it#462]
In the JP characterset, when ** does not have a space after it the rendering fails.

Please see an example below.

```
const md = new MarkdownIt({ xhtmlOut: true, breaks: true });
console.log(md.render('**${MyString}** な')); //renders <p><strong>${MyString}</strong> な</p>
console.log(md.render('**${MyString}**な'));  //renders <p>**${MyString}**な</p>
process.exit(1);
```

**Comment by puzrin** [comment]
Works according to spec https://spec.commonmark.org/0.28/#emphasis-and-strong-emphasis. Not a bug of this package. Please discuss spec-related things at http://talk.commonmark.org. This package is just an implementation of standard.

**Comment by Phryxia** [comment]
I'm wondering why this is not a bug of this package.

I read the spec, but I don't understand that why discarding above case is bounded in spec.

Since second ** of `**${MyString}**な` is both left-flanking and right-flanking, so I think by rule 7, it can close the strong tag.

**Comment by tats-u** [comment]
Tentative solution: https://www.npmjs.com/package/markdown-it-cjk-friendly
