### ISSUE TITLE
Horizontal line markup error

### ISSUE THREAD

**Issue by Texxer** [markdown-it/markdown-it#463]
# Current behavior

[Screenshot](https://user-images.githubusercontent.com/14838850/40964782-f06d0b80-68e6-11e8-88ad-ead958fab819.png)
[Screenshot](https://puu.sh/AySo3/6d67deb2f2.png)

--- increases size and thickness of previous text

# Expected behavior

--- should create a horizontal line

**Comment by puzrin** [comment]
Please, use [markdown-it](http://markdown-it.github.io/#md3=%7B%22source%22%3A%22hoge%5Cn---%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D) demo next time and check official dingus first.

[Works as expected](https://spec.commonmark.org/dingus/?text=hoge%0A---%0A) (official implementation). See [commonmark spec](https://spec.commonmark.org/0.28/#setext-headings) for details
