### ISSUE TITLE
Need Help: Parser Rule For Email Obfuscation

### ISSUE THREAD

**Issue by ilyaigpetrov** [markdown-it/markdown-it#465]
I want to obfuscate autolinks that are emails, e.g. <homer.j.simpson@example.com>.
For obfuscation I plan to convert `a.href` and its text to html entities if href is an email.
I have some questions:
1) Inside `md.parser.renderer.rules.link_open` function may I consume and render 3 tokens (link_open, text, link_close) at once?
2) If 1) is not possible, then I guess I have to add parse rules and output special token. I guess it's done this way: `md.parser.core.ruler.push('MY_RULE', state => { ...for some reason all input is tokenized here already...  });`. I need more information about how to do it at this point or if I do it wrong. Why state has source tokenized already, how to work with it if I want to convert some tokens into a token of my type?

If this place is not appropriate for such questions -- let me know.
Thank you for your help,
Ilya.

**Comment by puzrin** [comment]
[dev docs](https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer) refer to [markdoan-it-for-inline](https://github.com/markdown-it/markdown-it-for-inline#use), it has example for link interation and modification.

You should modify array with tokens. That should happen before renderer. See [linkify](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_core/linkify.js) rule for example.

**Comment by ilyaigpetrov** [comment]
I have written [a version for autolinks](https://github.com/ilyaigpetrov/markdown-it-email-obfuscator).
Now I want to try writing obfuscator for all links, [here] is what I do (take a look on inputs).
My question: why in the first input `link_open` and `link_close` are on the same level, and for the second input they are on different levels (`link_open.level = 1`, `link_close.level = 0`)? How should I treat this inconsistency?

[here]: https://github.com/ilyaigpetrov/markdown-it-email-obfuscator/blob/master/._trash/linkify-like.js

**Comment by puzrin** [comment]
Hm... i would expect levels equal. Don't remember why those are not. Probably a bug.

You can sum `.nesting` value until result become 0 again, to find proper pair.

**Comment by ilyaigpetrov** [comment]
Please, let me know if you are going to fix it soon, because I'm going to continue writing my plugin for the fixed version dropping support for all the prior versions.
