### ISSUE TITLE
Differenciate `_ _` and `** **` with css class

### ISSUE THREAD

**Issue by linvi** [markdown-it/markdown-it#468]
Hello,

Currently both double underscore and double * are generating the same html `<strong></strong>`.
Could we add a class to allow to differentiate both of them :

** => `<strong class='star'></strong>`
_ _ => `<strong class='underscore'></strong>`

I guess same would go for *italics*.

This would allow me to style both of them differently and have more visual options for rendering.

Cheers,
Linvi

**Comment by puzrin** [comment]
`token.markup` contains info about markup been used.
