### ISSUE TITLE
Smart punctuation cannot be escaped in special cases

### ISSUE THREAD

**Issue by dwelle** [markdown-it/markdown-it#471]
By smart punctuation (what common-mark calls it in its dingus), I mean `typographer` option.

- `\"` does nothing (yields `"`, beautified)
- `\(c)` still yields ©.. same for `(tm)`
    - only when the escape char is used for the ending paren, it works: `(c\)`
- `\--` still yields en-dash (commonmark [yields two dashes](https://spec.commonmark.org/dingus/?text=%5C--&smart=1))
    - same as above, if escaping the 2nd dash, it works: `-\-`

There are probably other cases which don't come to mind.

**Comment by puzrin** [comment]
Yes, smart punctuation can not be escaped, only completely disabled. This has no easy fix (without serious parser rewrite).

**Comment by dwelle** [comment]
Pity. Is there a way to keep `typographer` but turn off `(c)`/`(tm)` (and similar)? Particularly the `(c)` is precarious, because users are much more likely to write `(c)` to mean a list item, rather than a copyright logo.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/rules_core/replacements.js

Replacements rules are separate from quotes fixer. You can disable that plugin, or replace with customized one.
