### ISSUE TITLE
Parse metadata from Markdown

### ISSUE THREAD

**Issue by wiktor-k** [markdown-it/markdown-it#473]
GitHub's extension to markdown allows specifying meta properties, they are located at the beginning of the doc and look like that:
```
---
TOCTitle: FAQ
ContentId: E02F97FD-842B-4D27-B461-37DD18B2582E
PageTitle: Visual Studio Code Frequently Asked Questions
DateApproved: 7/5/2018
MetaDescription: Our docs contain a Common Questions section. Here are items that don't fit in the other topics.
---
```

They are used to supply additional info to the document, used for example here: https://raw.githubusercontent.com/Microsoft/vscode-docs/master/docs/supporting/faq.md and here is how it looks like: https://github.com/Microsoft/vscode-docs/blob/master/docs/supporting/faq.md

It would be nice if markdown-it parsed this structure and returned it from `parse`, it doesn't need to be rendered to HTML but I'd like have access to it from the AST.

Currently this is rendered as a `<hr>` and a set of bold headings.

**Comment by puzrin** [comment]
That's not for this project. You need to create external wrapper, split input and process meta and content separately. May be, there can be ready solutions in npm.

**Comment by wiktor-k** [comment]
Okay, thanks for the info!
