### ISSUE TITLE
You don't acually use linkiy-it

### ISSUE THREAD

**Issue by rugk** [markdown-it/markdown-it#475]
https://github.com/markdown-it/markdown-it/blob/e6f19eab4204122e85e4a342e0c1c8486ff40c2d/lib/rules_core/linkify.js

This looks like code duplication :wink: 

Also it is bad for projects wanting to use both. (markdown and linkify plain text) :smile:

**Comment by puzrin** [comment]
Closed (looks as useless garbage).

**Comment by rugk** [comment]
Oh, wait… now I understand.


That whole logic in https://github.com/markdown-it/markdown-it/blob/e6f19eab4204122e85e4a342e0c1c8486ff40c2d/lib/rules_core/linkify.js is just for calling linkify-it and processing the results. I think, that's quite much…
