### ISSUE TITLE
Bug: must have new line after html tag parsing.

### ISSUE THREAD

**Issue by ayvaroff** [markdown-it/markdown-it#478]
There is a bug with markdown render after html tag. Strong text doesn't appear in this case:

`'<iframe width="560" height="315" src="https://www.youtube.com/embed/FlsCjmMhFmw" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>\n__here comes bold text__'`

But it work's if we insert one more new line:

`'<iframe width="560" height="315" src="https://www.youtube.com/embed/FlsCjmMhFmw" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>\n\n__here comes bold text__'`

It's a bug cause right now you have to insert a new line to render as it should be.

**Comment by puzrin** [comment]
Works as needed. Please read commonmark spec and test in official dingus prior to report bugs here.
