### ISSUE TITLE
Bug: strong block parse wrong when text contains _

### ISSUE THREAD

**Issue by ayvaroff** [markdown-it/markdown-it#479]
There is bug when using with markdown-it-attr plugin. Case with attribute target="_blank" for <a> tag. But library think that it's <em> block breaking the hole markdown.

`__Link to [link name](/link/href){target=_blank} must be strong.__ `

**Comment by puzrin** [comment]
Any CM spec things are NOT related to this project. It implements standard as is, without deviations. You can try to use `\_blank` for workaround, or `**` instead of `__`.
