### ISSUE TITLE
Setup an Issue template...

### ISSUE THREAD

**Issue by digitalmoksha** [markdown-it/markdown-it#480]
@puzrin you might consider setting up an issue template, as outlined here: https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

This might help inform developers what are valid bugs to submit, to check them on the CommonMark reference page first before submitting, etc.  It might help eliminate some noise...

**Comment by puzrin** [comment]
You are right. Need to write some polite instructions. Seems CONTRIBUTING.md no longer work for issues and it's content is outdated.

**Comment by puzrin** [comment]
Hope to be solved by https://github.com/markdown-it/markdown-it/commit/9bbefc1bc39fa02dd8cc5f9a10400b1cdbb5edf1.

Feel free to post fixes/improvements
