### ISSUE TITLE
Markdown interpreted in links

### ISSUE THREAD

**Issue by fwhcat** [markdown-it/markdown-it#482]
Hi. A link that has some markdown keywords would be interpreted and the output is wrong:

example:

`https://images-na.ssl-images-amazon.com/images/I/513CDH89HrL._UX679_.jpg`

https://images-na.ssl-images-amazon.com/images/I/513CDH89HrL._UX679_.jpg

will break and display UX679 in italic. The problem is that the generated link is cut.

Ofc, we can still use the format:

`[https://images-na.ssl-images-amazon.com/images/I/513CDH89HrL._UX679_.jpg](https://images-na.ssl-images-amazon.com/images/I/513CDH89HrL._UX679_.jpg)`

[https://images-na.ssl-images-amazon.com/images/I/513CDH89HrL._UX679_.jpg](https://images-na.ssl-images-amazon.com/images/I/513CDH89HrL._UX679_.jpg)

![image](https://user-images.githubusercontent.com/20411249/43061852-0ce73f8e-8e57-11e8-836b-d70e77bf9bb3.png)

**Comment by fwhcat** [comment]
PS: [GFM (GitHub Flavored Markdown) specification](https://github.github.com/gfm/) does not have this issue.
It seems only implementations respecting [CommonMark specification](http://spec.commonmark.org/) do have this issue.

**Comment by puzrin** [comment]
That's a known issue in linkifier, with known workaround. https://github.com/markdown-it/markdown-it/issues/38

Will not fix.
