### ISSUE TITLE
Add callback for `md.render`

### ISSUE THREAD

**Issue by colinfang** [markdown-it/markdown-it#483]
I am working on a markdown-it plugin that I hope to share states between each match of the custom rules in a `md.render`. However, I don't want the states to persist across each call of `md.render`.

Is there any simple way to achieve that?

**Comment by puzrin** [comment]
https://markdown-it.github.io/markdown-it/#MarkdownIt.render

See `env` param and how it's used in code. It's an independent sandbox for each call, used to share data between plugins.

**Comment by colinfang** [comment]
nice! It is a lot better than my current ` idx === 0` check.
