### ISSUE TITLE
normalizeLink would break certain URLs

### ISSUE THREAD

**Issue by opennota** [markdown-it/markdown-it#49]
``` js
var normalizeLink = require('./common/utils').normalizeLink;
console.log(normalizeLink('http://example.com/?q=%3f'));
```
Output: `http://example.com/?q=%253f`

``` js
var md = MarkdownIt();
console.log(md.render('[link](http://example.com/?q=%3f)'));
```

Output: `<p><a href="http://example.com/?q=%253f">link</a></p>`

**Comment by puzrin** [comment]
Result of  broken utf-8 sequence normalization is not significant on practice.

In general, this duplicates #29

**Comment by opennota** [comment]
@puzrin 
In the real world one can question Google "как зовут моего кота?" and copy the URL from the navigation bar to a forum post. In the default configuration Firefox would encode `?` as `%3F`, and `normalizeLink()` would corrupt that URL.

**Comment by puzrin** [comment]
Anyway, it's better to move this example to that ticket, IMHO. Current normalizer needs serious rewrite, and i think this bug will be resolved automatically.

**Comment by opennota** [comment]
@puzrin Done.
