### ISSUE TITLE
Inconsistent replacement

### ISSUE THREAD

**Issue by opennota** [markdown-it/markdown-it#492]
``` js
const md = markdownit({ typographer:true });
console.log(md.render('---|---'));
```

Output:

```
<p>—|---</p>
```

I'd expect both `---` replaced, because there is a symmetry.

**Comment by puzrin** [comment]
AFAIK long dash is allowed at phrase start, and not allowed at phrase end. Anyway, nobody prohibit you to write your own rule.

**Comment by opennota** [comment]
The same applies to en-dash, too: `console.log(md.render('--|--')); // Output: <p>–|--</p>`

**Comment by puzrin** [comment]
I think your samples are artificial (with single char between) and not related to grammar. This can not happen with regular text.
