### ISSUE TITLE
Typographer doesn't seem to work

### ISSUE THREAD

**Issue by vimtaai** [markdown-it/markdown-it#494]
Hi,
I'm creating my own Markdown flavor using `markdown-it` and I seem to be stuck with the following problem. I just can't figure out why typographer is not working.

My `markdown-it` config:

```js
import MarkdownIt from 'markdown-it'
import anchor from 'markdown-it-anchor'
import deflist from 'markdown-it-deflist'
import container from 'markdown-it-container'

import { config as anchorConfig } from './configs/anchor'
import { config as containerConfig } from './configs/container'

const parser = new MarkdownIt('commonmark')

parser
  .set({ typographer: true })
  .set({ linkify: true })
parser
  .enable('linkify')
  .enable('table')
  .enable('strikethrough')
parser
  .use(anchor, anchorConfig)
  .use(deflist)
  .use(container, '', containerConfig)

export const parse = parser.render.bind(parser)
```

My `.md` test:
```
## Typographic replacements

Enable typographer option to see result.

(c) (C) (r) (R) (tm) (TM) (p) (P) +-

test.. test... test..... test?..... test!....

!!!!!! ???? ,,  -- ---
```

HTML output: 
```html
<h2 id="typographic-replacements">Typographic replacements</h2>
<p>Enable typographer option to see result.</p>
<p>(c) (C) (r) (R) (tm) (TM) (p) (P) +-</p>
<p>test.. test... test..... test?..... test!....</p>
<p>!!!!!! ???? ,,  -- ---</p>
```

Any ideas?

**Comment by puzrin** [comment]
Can't help about es6 syntax. Probably, your selected preset (commonmark) does not include typographer rules https://github.com/markdown-it/markdown-it/blob/master/lib/presets/commonmark.js.

Try `.enable('replacements').enable('smartquotes')` 

https://github.com/markdown-it/markdown-it/tree/master/lib/rules_core

**Comment by puzrin** [comment]
I strongly recommend to look into docs/sources, to see how plugins work.

`.enables()` manage plugins. `.set()` manage params. Those are not related anyhow. Everything works right with default preset. If you use different ones - it's your responsibility how to configure things right.
