### ISSUE TITLE
How to "import" markdown-it?

### ISSUE THREAD

**Issue by oshihirii** [markdown-it/markdown-it#495]
In readme there are install instructions:

    npm install markdown-it --save

I am using on frontend, can i Include `markdown-it` in my `main.js` file with something like:

    import md from 'markdown-it'  

And then use like:

    var result = md.renderInline('__markdown-it__ rulezz!');

For reference, the following is working for me, it's just the rest of my imports use `import x from y`, so trying to be consistent.  

    npm install markdown-it --save
    npm install --save markdown-it-attrs
    
    var md = require('markdown-it')();
    var markdownItAttrs = require('markdown-it-attrs');
    md.use(markdownItAttrs);
    var new_value_rendered = md.renderInline(new_value);

**Comment by puzrin** [comment]
No ideas. I think, generic programming questions are not for this repo.

**Comment by dcolens** [comment]
For the record
```javascript
import MarkdownIt from 'markdown-it';
var md = new MarkdownIt();
...
```

**Comment by KoljaL** [comment]
> 
> 
> For the record
> 
> ```js
> import MarkdownIt from 'markdown-it';
> var md = new MarkdownIt();
> ...
> ```

How does it work with plugins for markdown-it?

**Comment by digitalgopnik** [comment]
> > For the record
> > ```js
> > import MarkdownIt from 'markdown-it';
> > var md = new MarkdownIt();
> > ...
> > ```
> 
> How does it work with plugins for markdown-it?

```
import MarkdownIt from 'markdown-it';
import markdown_it_strikethrough_plugin from './plugins/markdown-it-strikethrough';
const markdownIt = new MarkdownIt('commonmark').use(markdown_it_strikethrough_plugin);
```
