### ISSUE TITLE
When typographer is set to true... how I can escape one instance to see as it were set to false

### ISSUE THREAD

**Issue by ylulloa** [markdown-it/markdown-it#497]
Is there any workaround for the case where I need to use (c) as a symbol and in the same content use it literally "(c)" as a text?

**Comment by puzrin** [comment]
[escape & entity](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%28c%29%5Cn%5Cn%28c%5C%5C%29%5Cn%5Cn%28%26%23x63%3B%29%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D) may help, but this does not work when multiple entries in the same line for some reasons.

Replacements have simplified implementation. It may be more simple to disable those.
