### ISSUE TITLE
Markdown is not parsed correctly

### ISSUE THREAD

**Issue by Havunen** [markdown-it/markdown-it#502]
Hey!

I started building editor using markdown-it and its working pretty well. However I noticed parser returns incorrect syntax when italics and bolds are mixed. I tried using `_` to separate italics and `**` to separate bold but it didn't work.

However if in place of italic strikethrough is used, everything works as expected.

Here is the [link](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%23%20This%20is%20bug%20report%5Cn%5CnI%20want%20to%20style%20word%20emphasis%20so%20that%20first%203%20characters%20are%20bold%20and%20last%203%20characters%20are%20bold%5Cn%5CnThen%20from%20the%20second%20first%20character%20make%20italic%20until%20second%20last%20character%5Cn%5CnUsing%20%60_%60%20as%20italic%20separator%20it%20does%20not%20work%3A%5Cn%5Cn%2A%2AE_mp_%2A%2A_ha_%2A%2A_si_s%2A%2A%5Cn%5CnUsing%20%60%2A%60%20as%20italic%20separator%20it%20does%20not%20work%20either%3A%5Cn%28ha%29%20should%20not%20be%20bold%5Cn%5Cn%2A%2AE%2Amp%2A%2A%2A%2Aha%2A%2A%2A%2Asi%2As%2A%2A%5Cn%5CnWhen%20strikethrough%20is%20used%20in%20place%20of%20italic%20it%20works%20as%20expected%5Cn%5Cn%5Cn%2A%2AE~~mp~~%2A%2A~~ha~~%2A%2A~~si~~s%2A%2A%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Afalse%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D) to test case

**Comment by puzrin** [comment]
[official dingus](https://spec.commonmark.org/dingus/?text=%23%20This%20is%20bug%20report%0A%0AI%20want%20to%20style%20word%20emphasis%20so%20that%20first%203%20characters%20are%20bold%20and%20last%203%20characters%20are%20bold%0A%0AThen%20from%20the%20second%20first%20character%20make%20italic%20until%20second%20last%20character%0A%0AUsing%20%60_%60%20as%20italic%20separator%20it%20does%20not%20work%3A%0A%23%23%20**E_mp_**_ha_**_si_s**%0A%0AUsing%20%60*%60%20as%20italic%20separator%20it%20does%20not%20work%20either%3A%0A(ha)%20should%20not%20be%20bold%0A%23%23%20**E*mp****ha****si*s**%0A%0AWhen%20strikethrough%20is%20used%20in%20place%20of%20italic%20it%20works%20as%20expected%0A%0A%23%23%20**E~~mp~~**~~ha~~**~~si~~s**) shows the same result. You should read commonmark spec, why this happens. Also note, this package just follows spec as is, and we stay aside of discussing markup questions.
