### ISSUE TITLE
MAS 1.3.1: Form elements must have labels (.task-list-item-checkbox[type="checkbox"])

### ISSUE THREAD

**Issue by amitkumariiit** [markdown-it/markdown-it#505]
Markdown task list has the following accessibility issue that is reported on running the KerosForWeb tool to find the accessibility.

![checklistpng](https://user-images.githubusercontent.com/9694413/47085173-6e454a80-d233-11e8-8b05-672f9d8b03a8.png)
![checklist 2](https://user-images.githubusercontent.com/9694413/47085174-6edde100-d233-11e8-96ab-5568feda3fae.png)

Issue Details
Form elements must have labels
[label](https://dequeuniversity.com/rules/axe/3.1/label)

Element Path
.task-list-item:nth-child(1) > .task-list-item-checkbox[type="checkbox"]

Snippet
<input class="task-list-item-checkbox" disabled="" type="checkbox">

How to fix
Fix any of the following:
- aria-label attribute does not exist or is empty
- aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
- Form element does not have an implicit (wrapped) <label>
- Form element does not have an explicit <label>
- Element has no title attribute or the title attribute is empty

To reproduce
Use [K4W ](https://microsoft.sharepoint.com/teams/msenable/Pages/KerosForWeb.aspx)to investigate the issue details

Environment
Chrome version 69.0.3497.100

This accessibility issue was found using **Keros for Web**

**Comment by puzrin** [comment]
Close as not related to this project
