### ISSUE TITLE
Markdown parsing with not closing html tag

### ISSUE THREAD

**Issue by awpsawps12** [markdown-it/markdown-it#507]
The markdown content is:
```markdown
<div>
# 1
<section>
# 2
```

The html render result is:

```html
<div>
# 1
<section>
# 2
</section>
</div>
```

What I want the result is:
```html
<div></div>
# 1
<section></section>
# 2
```

Is there any simple way to achieve that?

**Comment by puzrin** [comment]
Please, see commonmark spec instead https://spec.commonmark.org/0.28/#html-blocks. Also note, this repo is just an implementation of CM spec, it's not for generic/markup questions.
