### ISSUE TITLE
Relative paths to included content

### ISSUE THREAD

**Issue by oravecz** [markdown-it/markdown-it#511]
I had noticed the [markdown-it-include](https://www.npmjs.com/package/markdown-it-include) plugin seems to support the inclusion of external files by use of relative paths. However, the path is not relative to the markdown file containing the plugin tag, it is relative to some configured root directory.

Obviously, in order to support pathing relative to the source markdown file, one will have to know the path to the markdown file being processed. Is there any thought (or some other approach) to supporting the accessing of resources at markdown time which are in a relative location to the source file?

**Comment by puzrin** [comment]
You can use `env` param  to add any kind of meta data, including current path. Or change cwd before call. But it's better to discuss such question with plugin author.
