### ISSUE TITLE
High CPU and memory usage in IE11 making the page unresponsive

### ISSUE THREAD

**Issue by chitra-c** [markdown-it/markdown-it#512]
I am using tui-editor in my application which uses markdown-it. It's working fine in chrome but when i open the application in IE11 ,the markdown-it.js causes high usage of cpu and memory resulting in making the page unresponsive. If i remove markdown-it.js then the application works fine.

**Comment by puzrin** [comment]
Sorry, can't debug tui-editor for you. If you are sure problem is in this package - create a separate repo with minimal code (only with markdown-it, without tui-editor and so on).

**Comment by chitra-c** [comment]
Is there a way to debug and check whether it's markdown-it that's causing the issue or is it tui-editor-Editor ,because if i comment out markdown-it then everything is working fine

**Comment by duane9** [comment]
@puzrin does markdown-it still support IE11?
