### ISSUE TITLE
How can I trigger highlight function for markdown code block with four whitespace 

### ISSUE THREAD

**Issue by wangzhenhui1992** [markdown-it/markdown-it#515]
Markdown text like below will not trigger highlight function.

    code with 4 whitespaces ahead

but code between ``` can trigger it
```
code between ```
```

**Comment by puzrin** [comment]
You should override code block renderer to make it behave similar to fenced block https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.js#L30.
