### ISSUE TITLE
 Into an infinite loop when parsing a string in a specific format

### ISSUE THREAD

**Issue by MANSOUL** [markdown-it/markdown-it#516]
Yesterday I accidentally wrote a string like the following, and then my program runs very slowly, seems to be stuck in an infinite loop, after checking it is caused by parsing some strings like the following format:

**Comment by puzrin** [comment]
I don't see your example.

**Comment by puzrin** [comment]
Also make sure your problem is reproducible in https://markdown-it.github.io/, or create a test repo with minimal possible code sample.

**Comment by MANSOUL** [comment]
I am very sorry, I just wrote a test example, but it seems that there is no error. I will look it up carefully. If there is an exception, I will tell you again, sorry.
