### ISSUE TITLE
a little question.

### ISSUE THREAD

**Issue by ms-typescript** [markdown-it/markdown-it#517]
my code is

```html
<!DOCTYPE html>
<html>
    <head>
        <title> </title>
    </head>
    <body>
      <script src="hello.js"></script>
    </body>
</html>
```
default render
![image](https://user-images.githubusercontent.com/41296175/49142117-0ce4c100-f333-11e8-9e92-6b802fbe4815.png)

i want this style. what should i do?

![image](https://user-images.githubusercontent.com/41296175/49142183-31409d80-f333-11e8-9e65-c3096a3631ea.png)

**Comment by ms-typescript** [comment]
my code is
![image](https://user-images.githubusercontent.com/41296175/49142250-4c131200-f333-11e8-87d2-87ae275a9baf.png)

**Comment by puzrin** [comment]
I don't understand you. If you need different highlight skin, that should be tuned in external highlighter options. [Here](https://github.com/markdown-it/markdown-it/blob/46bd681eadb2cf19e26ecdbf200d5d083ac2b8d4/lib/renderer.js#L39-L86) is code, calling it.

**Comment by ms-typescript** [comment]
I'm sorry, I didn't say clear.
I mean

my raw code is
![image](https://user-images.githubusercontent.com/41296175/49144640-d742d680-f338-11e8-8739-7080033a9902.png)

I want to keep

![image](https://user-images.githubusercontent.com/41296175/49144677-e75ab600-f338-11e8-892b-8958060be506.png)

”```html“ and "```" 

To make it easier to explain what language it is.

but  markdown-it remove ”```html“ and "```" 

    "markup": "```",
    "info": "html",

I don't know if I made myself clear.

**Comment by ms-typescript** [comment]
I don't want to remove 
![image](https://user-images.githubusercontent.com/41296175/49144861-6223d100-f339-11e8-8d64-a6dc622fe9bb.png)
and
![image](https://user-images.githubusercontent.com/41296175/49144879-6d76fc80-f339-11e8-8f42-f0694fdb248f.png)

i want to render all

**Comment by puzrin** [comment]
Wrap it with [more long pattern](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60html%5Cn%60%60%60html%5Cnbla-bla-bla%5Cn%60%60%60%5Cn%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

Also see [CommonMark spec](https://spec.commonmark.org/0.28/#fenced-code-blocks) for all questions about markup.

**Comment by ms-typescript** [comment]
thank you
