### ISSUE TITLE
Linkify terminating url - requires upgrade?

### ISSUE THREAD

**Issue by llamamoray** [markdown-it/markdown-it#518]
Hi,

When I have markdown:
`https://www.riotinto.com/documents/_Iron%20Ore/Port_Handbook_Final_-_July_2016(2).pdf`
markdown-it seems to terminate the link at `https://www.riotinto.com/documents/_`
See: [example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%5Bclick%20me%5D%28https%3A%2F%2Fwww.riotinto.com%2Fdocuments%2F_Iron%2520Ore%2FPort_Handbook_Final_-_July_2016%282%29.pdf%29%5Cn%5Cnhttps%3A%2F%2Fwww.riotinto.com%2Fdocuments%2F_Iron%2520Ore%2FPort_Handbook_Final_-_July_2016%282%29.pdf%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

![image](https://user-images.githubusercontent.com/2970147/49173339-5a652c00-f33b-11e8-982d-c3d105f6fdcc.png)

I've tried this in the the linkify-it playground and it [seems to work](http://markdown-it.github.io/linkify-it/#t1=https%3A%2F%2Fwww.riotinto.com%2Fdocuments%2F_Iron%20Ore%2FPort_Handbook_Final_-_July_2016(2).pdf) making me think that the latest release 2.1.0 of linkify-it has fixed the issue I'm seeing.

Would it be possible to upgrade and rebuild the markdown-it dependency?

**Comment by llamamoray** [comment]
Having tried upgrading linkify-it and writing a test for the broken url, I think the problem is actually in the parsing of the markdown.

I'm not familiar with the codebase, but by the time the tokenised markdown gets to [here](https://github.com/markdown-it/markdown-it/blob/46bd681eadb2cf19e26ecdbf200d5d083ac2b8d4/lib/rules_core/linkify.js#L62) it's already missing the end of the url.

As such I suspect that it's the underscore character terminating the url when it's being tokenised upstream.

**Comment by puzrin** [comment]
That's a known issue, when underscores are processed as italic. [Example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22https%3A%2F%2Fwww.riotinto.com%2Fdocuments%2F%5C%5C_Iron%2520Ore%2FPort_Handbook_Final_-_July_2016%282%29.pdf%5Cn%5Cnhttps%3A%2F%2Fwww.riotinto.com%2Fdocuments%2F_Iron%2520Ore%2FPort_Handbook_Final_-_July_2016%282%29.pdf%5Cn%5Cn%3Chttps%3A%2F%2Fwww.riotinto.com%2Fdocuments%2F_Iron%2520Ore%2FPort_Handbook_Final_-_July_2016%282%29.pdf%3E%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D). You can search previous tickets for details.

Workaround is to use `< >` brackets or add `\` escape to some `_`. Better possible, but not easy, and not planned.
