### ISSUE TITLE
doent recongnized html and image, can be ???

### ISSUE THREAD

**Issue by emazzu** [markdown-it/markdown-it#519]
hi, how are you !!! 

I send an email with the markdown-it, but the tag <p> appear as <p style="text-align: justify;"> and the image doest show !!!

could you help me ????

28/11/2018
<p style="text-align: justify;"> Agregamos en Base Map, el servicio para conocer la ubicación de los equipos de Pulling en Tiempo Real con un intervalo de actualización de 2 minutos (sin tocar nada). </p> <p style="text-align: justify;"> En forma predeterminada, el servicio no esta visible, para habilitarlo, hay que hacer clic en el siguiente widget, lo van a encontrar con el nombre COM RAS - GSJ Ras. De igual forma que el resto de los servicios, haciendo clic en un equipo, se pueden el nombre y las propiedades. </p>

An awesome example image

**Comment by puzrin** [comment]
Please, provide full details and make sure to read https://spec.commonmark.org/ before.
