### ISSUE TITLE
Easily add classes to all different tags

### ISSUE THREAD

**Issue by samselikoff** [markdown-it/markdown-it#520]
Hi there, thanks for this great library!

I'm trying to understand the easiest/most ergonomic way to modify the Renderer to add classes to different tags.

I came across the example with `paragraph_open`:

```js
md.renderer.rules.paragraph_open = () => `<p class="mb-3">`;
```

This is just what I'm looking for, but is there anywhere I can see a list of all the rule names? 

Also, is there a different way to add a rule just for `<h1>` tags? Right now I'm doing something like

```js
md.renderer.rules.heading_open = function(tokens, i) {
  let str;
  let token = tokens[i];
  
  if (token.tag === 'h1') {
    str = `<h1 class='mb-1'>`;
  } else {
    str = `<${token.tag}>`;
  }

  return str;
})
```

Thanks!

**Comment by puzrin** [comment]
> is there anywhere I can see a list of all the rule names?

No direct list for renderer, but those are easy to understand from parser rules:

- https://github.com/markdown-it/markdown-it/tree/master/lib/rules_inline
- https://github.com/markdown-it/markdown-it/tree/master/lib/rules_block

> Also, is there a different way to add a rule just for \<h1> tags? Right now I'm doing something like

I think your implementation is ok.
