### ISSUE TITLE
Modify markdown text without translating it to html

### ISSUE THREAD

**Issue by coreyxue** [markdown-it/markdown-it#522]
I'm trying to append some text to all links in my markdown text. Can I easily achieve this?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/tree/master/docs see basic docs and examples first.

**Comment by coreyxue** [comment]
@puzrin Let me clarify my question. What I wanna achieve is to leave my markdown text as it is and only to modify link markdown texts  from "[link text](https://mylink.com)" to "[link text](prefix+https://mylink.com)"

for example:
from "- some text\n\n[link text](https://mylink.com)"
to "- some text\n\n[link text](prefix+https://mylink.com)"
