### ISSUE TITLE
Question: bold question mark

### ISSUE THREAD

**Issue by tjoskar** [markdown-it/markdown-it#525]
Hi,

The following code returns `<p>Hell<strong>o</strong></p>` as one may expect:

```js
md.render('Hell**o**')
```

And this code: `md.render('Hello **?**')` returns `<p>Hello <strong>?</strong></p>` which seams correct. 

But the following code: `md.render('Hello**?**')` returns `<p>Hello**?**</p>` which I didn't expect.  

Is this a bug or by design? Or is it even in the spec? 

(it is the same thing for `!` and other special chars)

Ref: [https://jsbin.com/hunixuneji/edit?html,js,console](https://jsbin.com/hunixuneji/edit?html,js,console)

**Comment by puzrin** [comment]
That's in spec somewhere, not this package issue

https://spec.commonmark.org/0.28/#emphasis-and-strong-emphasis

**Comment by tjoskar** [comment]
Thanks @puzrin!
