### ISSUE TITLE
Losing attributes after markdown

### ISSUE THREAD

**Issue by bahmanian** [markdown-it/markdown-it#529]
I'm trying to render quill.js html data. but after markdown most of quill elements classes lost.

**Comment by puzrin** [comment]
I'm not sure your question is related to this repo. Please, add more details to reopen.

**Comment by bahmanian** [comment]
for example `<h1 class="something">Hello</h1>` will convert to # Hello

**Comment by puzrin** [comment]
I still don't understand what are you speaking about and why to you write this in this repo.

**Comment by bahmanian** [comment]
Sorry I'm talking about toMarkdown() method sir. Is this method related to this repo?

**Comment by puzrin** [comment]
No, this library has no method with such name.

**Comment by bahmanian** [comment]
Excuse me for this misunderstanding
