### ISSUE TITLE
Modify to use GFM-style newline

### ISSUE THREAD

**Issue by christianbundy** [markdown-it/markdown-it#530]
Hello!

I'm looking for a way to use GFM-style newlines where each newline creates a `<br>` without having to append two spaces to the line. Is there a simple way to do this with markdown-it? Thanks a lot!

## Desired

```md
a
b
c
```

> a
> b
> c

## Actual

```md
a
b
c
```

> a b c

**Comment by puzrin** [comment]
See option `{ breaks: true }`

**Comment by christianbundy** [comment]
Thank you!
