### ISSUE TITLE
How to replace linkify token output completely ?

### ISSUE THREAD

**Issue by dxwc** [markdown-it/markdown-it#534]
md.renderer.rules.link_open = function (tokens, idx, options, env, self)
    {
        if(tokens[0].attrs[0][1] === `https://github.com/`)
            return '<b>something else completely</b>';
        else
            return defaultLinkOpen(tokens, idx, options, env, self);
    }

    console.log(md.render('https://github.com/'));

outputs: `<p><b>something else completely</b>https://github.com/</a></p>`

How can I make it output `<p><b>something else completely</b></p>` only ?

**Comment by dxwc** [comment]
Got it work by checking in `...rules.link_open` if next text is matching, if so: return empty string else default, same with `.rules.link_close`. For `rules.text`, check if previous is a type `link_open` and if so return `<b>something else completely</b>` else it's default. Is this the correct way to accomplish this or are there any simpler/faster option here ?

**Comment by puzrin** [comment]
1. It's better to check if `token.markup === 'linkify'`;

https://github.com/markdown-it/markdown-it/blob/bda94b0521f206a02427ec58cb9a848d9c993ccb/lib/rules_core/linkify.js#L104

2. Renderer function should respond for single token only. If you need to modify/add/remove multiple tokens, then you should add your function to rules.core, scan all tokens and do appropriate changes.
