### ISSUE TITLE
markdown-it-hierarchy - plugin help

### ISSUE THREAD

**Issue by chmorgan** [markdown-it/markdown-it#537]
Hello.

I've put together a pretty nice pipeline here using markdown-it and a handful of plugins.

When I added markdown-it-hierarchy, https://github.com/shytikov/markdown-it-hierarchy/blob/master/index.js, the headers that this plugin is modifying have lost their anchors added by markdown-it-anchor.

Looking at the source it looks clear that the issue is that most of the token information is being dropped. I've looked briefly at the plugin docs but I'm not sure what the right fix is. I'd appreciate some help on the direction here. I've reported the issue to the author but haven't heard back yet, that plugin may not be maintained at the moment.

**Comment by puzrin** [comment]
Sorry, no resources for generic programming questions.

**Comment by chmorgan** [comment]
@puzrin, the plugin guide said I could post questions here. I’ve spent a few hours and have run into issues in two ways I’ve tried to fix the plugin that are due to my lack of full understanding of the processing pipeline in markdown-it, could I post specifics with code here?

One is that I’m not able to preserve the md.renderer.heading_open (typing on mobile without code here). I was looking to save that, modify the tag content and then call the default heading_open. Unfortunately it looks like that parameter isn’t valid when the plugin is loaded so it can’t be saved and used like defaultRender in the examples. I’m referencing the example plugin code that uses that approach to override images.

The other approach was modeled after the markdown-it-anchor plugin where during one of the core phases, can’t recall but code copied from that plugin, and I modify the content of the inner text token. This works but because I’m adding headings at that level it conflicts with the markdown-it-toc-done-right plugin that adds its own numbers and there are two sets of section numbers like 1.1 1.1 some section etc. Should I look for the toc plugin to avoid adding those numbers as a solution?

I almost prefer the modification of the content at the core phase as it doesn’t require overriding the header_open function like the plugin was doing before. Overriding this was losing the id attribute and breaking the anchors that markdown-it-anchor put in but I can imagine other plugins could add other fields and it seems wrong for the plugin to be modifying the output at the rendering phase.

I’m just looking for some direction here, I’m not sure where else to ask and I’ve done the work to understand quite a bit about the system but I’m not sure which approach to pursue.

**Comment by puzrin** [comment]
I can try to help with concrete questions, if small samples available. But can not analyze whole project. Try to harrow down your question.

**Comment by chmorgan** [comment]
@puzrin I appreciate that.

How do I get the original md.renderer.rules.heading_open? I'm trying to follow the model specified at https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#data-flow because I'd like to call the default rule to finish processing the token after I've adjusted its content.

Here is the plugin code:

```
let accumulator = {};
let last = '';

let read = function (accumulator, level) {
    let value = '';

    for (let header in accumulator) {
        value += `${accumulator[header]}.`;

        if (header == level) {
            return `${value} `;
        }
    }

    return `${value} `;
}

let hierarchy = function (md, opts) {
    var defaultRender = md.renderer.rules.heading_open // NOTE: This doesn't appear to be valid at this point...

    md.renderer.rules.heading_open = function (tokens, idx, options, env, self) {
      let level = tokens[idx].tag;

      console.log(tokens[idx])
      console.log(tokens[idx+1])

      if (last < level) {
          accumulator[level] = 1;
      } else {
          accumulator[level]++;
      }

      output = read(accumulator, level)
      console.log("output", output)

      tokens[idx].content = output + tokens[idx].content

      // pass token to default renderer.
      return defaultRender(tokens, idx, options, env, self);
    };
};

module.exports = hierarchy;
```

```
[13:34:37] TypeError: defaultRender is not a function
    at Object.md.renderer.rules.heading_open (/Users/cmorgan/projects/dlc-user-manual/node_modules/markdown-it-hierarchy/index.js:40:14)
    at Renderer.render (/Users/cmorgan/projects/dlc-user-manual/node_modules/markdown-it/lib/renderer.js:326:38)
    at MarkdownIt.render (/Users/cmorgan/projects/dlc-user-manual/node_modules/markdown-it/lib/index.js:543:24)
    at markdownToHtml (/Users/cmorgan/projects/dlc-user-manual/gulpfile.js:43:21)
    at DestroyableTransform.modifyFile [as _transform] (/Users/cmorgan/projects/dlc-user-manual/node_modules/gulp-tap/lib/tap.js:53:11)
    at DestroyableTransform.Transform._read (/Users/cmorgan/projects/dlc-user-manual/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/cmorgan/projects/dlc-user-manual/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/cmorgan/projects/dlc-user-manual/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/cmorgan/projects/dlc-user-manual/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/Users/cmorgan/projects/dlc-user-manual/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:334:11)
[13:34:37] 'build' errored after 61 ms
[cmorgan@CHRISTOPHERs-MacBook-Pro dlc-user-manual]$
```

**Comment by puzrin** [comment]
See this peace of code

https://github.com/markdown-it/markdown-it/blob/bda94b0521f206a02427ec58cb9a848d9c993ccb/lib/renderer.js#L323-L329

Seems header uses "default" renderer. For block rules, call `renderToken()` is named rule not exists.

**Comment by chmorgan** [comment]
@puzrin this helped a ton, thank you for the pointer there, I appreciate the help. I think I've been able to update the plugin to be less intrusive, use the previous rule if there was one in place and I'm working to get it pushed out as the next rev through the original author. Thanks for the help here, I know it can be a pain and that I'm not well versed with the terminology or design of markdown-it, I appreciate it!
