### ISSUE TITLE
Bundle size reductions?

### ISSUE THREAD

**Issue by robcresswell** [markdown-it/markdown-it#539]
Hi! Is there any way to reduce the size of `markdown-it` in some conditions? I know there are ways to disable plugins etc, but this only seems to prevent their runtime execution, not their inclusion. It's sort of a shame that the library is so monolithic (vs entities etc being a separate plugin?)

See https://bundlephobia.com/result?p=markdown-it@8.4.2 vs https://bundlephobia.com/result?p=marked@0.6.1

(I know marked is not an ideal example as it is half-dead, but markdown-it minified + gzip is 4x the size)

It would be great, long term, if we could do something like

```js
import { renderer, entities } from "markdown-it";

const markdownRenderer = renderer();

markdownRenderer.use(entities);
```

The idea being that the core minimal renderer logic can still be applied, and then other parts are pulled in conditionally. I don't suppose there is any roadmap or possibility for this type of composition?

**Comment by puzrin** [comment]
There are no good ways to reduce size without loosing important features.

**Comment by robcresswell** [comment]
Why would optionally reducing size lose features? Sorry, not sure I follow. It's sort of exactly what I'm suggesting; let consumers choose their feature coverage by manual inclusion, rather than bundling it all in one monolith.

**Comment by puzrin** [comment]
I'm very sceptical about suggestion to optimize something when no metrics provided. The same about imaginated ideal modular design. If you wish to spend your time to search such solution - no problem, but i can not participate.

**Comment by robcresswell** [comment]
Sure, it was more of an open ended question; the metrics were the bundle sizes above, which make this a troublesome library to use in the browser. There are a handful of similar issues that have been opened and subsequently closed as well, so I wondered if there were any plans.

If it doesn't interest you, then thats cool also, its your project, and I can look elsewhere. Thanks for your time :)

**Comment by puzrin** [comment]
> There are a handful of similar issues that have been opened and subsequently closed as well, so I wondered if there were any plans.

- There are no plans from my side to spend significant time for changes. Everything doable with small spends is already done.
- If someone decide to invest his own time - PR will be reviewed with care.
- All postponed ideas are recorded in issue 125.
