### ISSUE TITLE
[question] avoiding top-level <p> wrappers for <img>, <a>, etc?

### ISSUE THREAD

**Issue by leeoniya** [markdown-it/markdown-it#540]
Hi,

i know that the markdown spec wraps all top-level 'inline' elements in `<p>`, but is it possible to disable this behavior via an option or extension? it's exceedingly rare that top-level images or links are ever meant to be inline, in fact they are almost always floated, overridden to `block` or `flex` children.

i would like to simply use CSS to define all top-level elements to block display e.g. `article > * { display: block }` and skip any unnecessary block-ifying `<p>` wrappers. then utilize [markdown-it-attrs](https://www.npmjs.com/package/markdown-it-attrs) for further case-by-case floating or refinement.

if something like this is not available, it would be helpful if someone can point me in the direction of a simple extension example that can be gutted to support this.

i can probably strip any top-level `<p>` wrappers containing a single child element in a post-processing pass, but would prefer to avoid going this route.

thanks!

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/index.js#L574

The only possible option to avoid paragraph is use `.parseInline()` method. Then all input will be considered as single paragraph.

**Comment by leeoniya** [comment]
this isn't a great solution since i have to somehow split the entire document by either `\n` or `\n\n+`, and loop through those lines. but how to split is not clear becase in some cases `\n` is just a line separator and in other cases it can be block separator.

```
# header
paragraph1

paragraph2
paragraph2
```

there's no way to know how to split this easily to then be able to use `renderInline` or `parseInline`. unless there's a lot more machinery/boilerplate that needs to go into using those methods.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it#init-with-presets-and-options

Just use `break` option

**Comment by mcfriend99** [comment]
Did this ever work?? I tried with the break option and it doesn't work. Why is this issue closed?? This behavior makes MarkdownIt fail a lot of the commonmark specification test.
