### ISSUE TITLE
HR following whitespace is interpreted as empty H2 

### ISSUE THREAD

**Issue by lancedolan** [markdown-it/markdown-it#541]
### Demo
Review these two closely:
- [Succeeds](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22Paragraph%20before%20horizontal%20rule.%C2%A0%5Cn%20%5Cn----%5Cn%C2%A0%5CnParagraph%20after%20horizontal%20rule.%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Afalse%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)
- [Fails](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22Paragraph%20before%20horizontal%20rule%C2%A0%5Cn%C2%A0%5Cn----%5Cn%C2%A0%5CnParagraph%20after%20horizontal%20rule.%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Afalse%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

### Expected
`----` should be parsed as a horizontal rule
See [Example 62](https://spec.commonmark.org/0.24/#example-62) to confirm

### Observed
`Paragraph before horizontal rule` and subsequent whitespace(` `) and subsequent `----` are, together, parsed as an H2.

### Diagnosis
  - If the white space on the line above `---` is a U+0020 : SPACE [SP] character, then markdown-it handles the scenario correctly
  - If the white space on the line above `---` is a U+00A0 : NO-BREAK SPACE [NBSP] character, then markdown-it handles the scenario _incorrectly_  

You just need to handle that unicode whitespace character correctly I believe

**Comment by puzrin** [comment]
That's not a bug. NBSP is processed as regular character. Also, use https://spec.commonmark.org/dingus/ to check agains spec.

**Comment by lancedolan** [comment]
You're absolutely right:

https://github.com/commonmark/CommonMark/issues/366

I'm really surprised and logged an issue there instead.

**Comment by puzrin** [comment]
IMHO nbsp (not just unicode, but non breaking) is processed right. But if spec will be updated, this package will reflect it.

**Comment by lancedolan** [comment]
If you have the time, care to explain? There are enough people agreeing with your position that I'm thinking it must be me who is missing something important?

For me, the fact that non breaking space is _officially_ categorized as a "Unicode Whitespace" by spec agrees with my intuition that it is, in fact, whitespace, and is therefore surprising when not parsed as whitespace. Furthermore, the typical web user who doesn't even know what "spec" means should be confused if their unicode whitespace isn't parsed as whitespace.

The only valid reason I've seen for keeping the spec as-is, is that an ASCII-only definition of whitespace makes life easier for certain implementations (byte stream parsers as jgm put it). This appears, to me, a case of implementation determining specification rather than specification determining implementation. Tail wagging the dog.

Again, it's eerie to me how few voices agree with what seems obvious to me, so I'm very open to new reasons that could change my mind?

**Comment by puzrin** [comment]
IMHO you try to create artificial logical links. Idea of nbsp is that it's a "normal char, but displayed as whitespace". And that's why it's processed as char.

But that's only my personal opinion. It's better to discuss this things on CM forum. This package just implement spec and stay aside of theory.

**Comment by lancedolan** [comment]
I guess we see each other as creating artificial logical links 😛 
When asked whether NBSP is white space or not, and agree that it is  "normal char, but displayed as whitespace", we make different choices about which is more important: the fact that it is normal, or the fact that it is displayed as whitespace. :)
