### ISSUE TITLE
just 88.6217949% CommonMark support

### ISSUE THREAD

**Issue by Vanessa219** [markdown-it/markdown-it#542]
use https://spec.commonmark.org/0.28/spec.json to test markdown-it

```
  console.log __test__/markdown/parse.test.ts:20
    pass:553, error:71

(node:15181) UnhandledPromiseRejectionWarning: Error: expect(received).toBe(expected) // Object.is equality

Expected: "<table><tr><td>
<pre>
**Hello**,
<p><em>world</em>.
</pre></p>
</td></tr></table>
"
Received: "<p>&lt;table&gt;&lt;tr&gt;&lt;td&gt;
&lt;pre&gt;
<strong>Hello</strong>,</p>
<p><em>world</em>.
&lt;/pre&gt;
&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;</p>
"

... ref test.log
```
[test.log](https://github.com/markdown-it/markdown-it/files/2965915/test.log)

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/test/commonmark.js

This package has built-in test, and conform spec 0.28 100%.

**Comment by Vanessa219** [comment]
@puzrin So sorry, i'm not set `html: true`. 
but now, i config:
```
{
    xhtmlOut: true,
    html: true,
}
```
the md can not convert to commonmark  `<p><a href=\"/url\">foo</a></p>\n<blockquote>\n</blockquote>\n`, it's convert to `<p><a href=\"/url\">foo</a></p>\n<blockquote></blockquote>\n` can you tell me how to config it? thank you so mush

```
[foo]

> [foo]: /url

```

**Comment by puzrin** [comment]
Please, use online demo and official dingus to provide samples. I don't understand what you need.

**Comment by Vanessa219** [comment]
md：
```
[foo]

> [foo]: /url

```
result:
```
<p><a href=\"/url\">foo</a></p>\n<blockquote></blockquote>\n
```
commonmark expect：
```
<p><a href=\"/url\">foo</a></p>\n<blockquote>\n</blockquote>\n
```

**Comment by puzrin** [comment]
See https://github.com/markdown-it/markdown-it/blob/d533c27017dbb9663422019a08adcf15265cf9fb/test/commonmark.js#L9-L11

That's a known difference.
