### ISSUE TITLE
Replace arrows when typographer enabled

### ISSUE THREAD

**Issue by thybzi** [markdown-it/markdown-it#543]
Wouldn't it be nice also to replace arrows when in typographer mode?

Something like:
`->`→`→`
`=>`→`⇒`
etc.

**Comment by thybzi** [comment]
These replacements should be skipped inside code blocks, I suppose.

**Comment by puzrin** [comment]
All format extensions should be done via plugins. Existing features are frozen and updated only when commonmark spec changes.
