### ISSUE TITLE
Convert relative links to .md to links to the resulting .html files when redering

### ISSUE THREAD

**Issue by frederikheld** [markdown-it/markdown-it#548]
Hey everyone,

I was expecting markdown-it to convert relative links to .md files into relative links to the resulting .html file when rendering. Instead it keeps the .md extension which breaks the link in the rendered result.

You can find a very good description of the behaviour I would expect in this documentation of a different markdown renderer:

https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#link-to-a-file-using-relative-path

I couldn't find anything about this in the documentation or via Google search. Can you give me a hint on how I need to configure markdown-it or is this actually not possible?

Thanks in advance,
Frederik

**Comment by puzrin** [comment]
I would strongly recommend to read commonmark spec and dev docs prior to create issues.

https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer - here are samples of simple modifications.

**Comment by spl** [comment]
I'm brand new to `markdown-it` and out of practice with JavaScript, but this is what I hacked together using [markdown-it-replace-link](https://www.npmjs.com/package/markdown-it-replace-link) (in the context of configuring [Eleventy](https://www.11ty.dev/)):

```javascript
let markdownIt = require('markdown-it');
let markdownItReplaceLink = require('markdown-it-replace-link');
let markdownItOptions = {
  html: true,
  replaceLink: function (link, env) {
    // Convert links such as `./blah.md` to `.././blah/`.
    return link.replace(/^\./, '../.').replace(/.md$/, '/');
  }
};
let mdLibrary = markdownIt(markdownItOptions).use(markdownItReplaceLink);
```

I'm leaving it here in case others arrive here for similar reasons.

**Comment by edgarascom** [comment]
@spl thanks a lot for this! Do you know how I could also dynamically include an absolute folder path, based on which folder .md files is in? E.g. `/posts/` or `/articles/` or `/case/`?

**Comment by spl** [comment]
@edgarascom I'm not sure if I understand correctly, but could you try changing the first string substitution (`.replace(/^\./, '../.')`) to suit your needs?

**Comment by edgarascom** [comment]
@spl yes, I changed it to:

```
    replaceLink: function (link, env) {
      return "/posts/" + link;
    }
```

But this will only work with .md files that are in `posts` input folder. I need to reference input folders dynamically somehow.

**Comment by spl** [comment]
@edgarascom This is just a guess: can you inspect `link` to determine the folder?

**Comment by edgarascom** [comment]
@spl mmm you are right, I could actually, but not in case if link is without a folder path. For example, if I am "posts" input folder and I link from one post to the other I just use [My post](my-post.md) link. When html link is generated, that leads me to "current-post/my-post" which is not existing.

**Comment by spl** [comment]
@edgarascom It sounds like markdown-it-replace-link might not give you the flexibility you need to do what you want.

**Comment by edgarascom** [comment]
@spl I think it does. I just need a dynamic variable of current input folder the note is in. So during the build I can add that dynamic path to links that do not have a folder path. E.g.: if the link is [my-page](my-page.md) I would add dynamically "/posts/" path, because the file is in "posts" input folder. But if the link is has a folder path [my-article](articles/my-page.md) I would only add a "/" in front.
