### ISSUE TITLE
Formatting isn't applied if a line ends with exclamation mark, three asterisks and backslash

### ISSUE THREAD

**Issue by roythedev** [markdown-it/markdown-it#550]
### Issue

* When ending a formatted text line with  "!\*\*\*\\" the wanted bold and italic formatting isn't applied for backslash forced breaks.
* Escaping the exclamation mark doesn't help.
* Ending the line with two spaces instead of backslashes to add forced breaks or "!\*\\" (only italic),  "!\*\*\\" (only bold) works as expected.
* Issue is able to be replicated on https://markdown-it.github.io/ with the "CommonMark strict" box checked.

### Test case (copy to the dingus)

\*\*\*Failed to be bold and italic!\*\*\*\\
text

**Comment by puzrin** [comment]
https://spec.commonmark.org/dingus/?text=***Failed%20to%20be%20bold%20and%20italic!***%5C

Works exactly as official dingus. Please, read spec and check reference sandbox prior to report issue here.
