### ISSUE TITLE
Inline token rendered as "<>"

### ISSUE THREAD

**Issue by Nautigsam** [markdown-it/markdown-it#551]
I have the following code that detects parenthesis and replaces them with `<span>` tags:

```javascript
let token = state.push('stage_directions_open', 'span', 1)
token.markup = markerStart

let content = state.src
    .slice(pos, matchStart)
    .replace(/[ \n]+/g, ' ')
    .trim()
const childTokens = []
state.md.inline.parse(
    content,
    state.md,
    state.env,
    childTokens
);

token = state.push('inline', '', 0)
token.children = childTokens

token = state.push('stage_directions_close', 'span', -1)
token.markup = markerEnd
```

When parsing the simple input `(test)`, it creates the following tokens (note how the inline content is properly tokenized):

```json
[
    {
        "type": "stage_directions_open",
        "tag": "span",
        "attrs": null,
        "map": null,
        "nesting": 1,
        "level": 0,
        "children": null,
        "content": "",
        "markup": "(",
        "info": "",
        "meta": null,
        "block": false,
        "hidden": false
    },
    {
        "type": "inline",
        "tag": "",
        "attrs": null,
        "map": null,
        "nesting": 0,
        "level": 1,
        "children": [
            {
                "type": "text",
                "tag": "",
                "attrs": null,
                "map": null,
                "nesting": 0,
                "level": 0,
                "children": null,
                "content": "test",
                "markup": "",
                "info": "",
                "meta": null,
                "block": false,
                "hidden": false
            }
        ],
        "content": "",
        "markup": "",
        "info": "",
        "meta": null,
        "block": false,
        "hidden": false
    },
    {
        "type": "stage_directions_close",
        "tag": "span",
        "attrs": null,
        "map": null,
        "nesting": -1,
        "level": 0,
        "children": null,
        "content": "",
        "markup": ")",
        "info": "",
        "meta": null,
        "block": false,
        "hidden": false
    }
]
```

But the HTML which is produced does not render the inline content :

`<p><span><></span></p>`

I am sure I am doing something wrong, can you please help me?

**Comment by puzrin** [comment]
I can't understand logic of what you try to do. Could you describe exact initial task with example?

**Comment by Nautigsam** [comment]
I am writing a plug-in to extend the syntax. I want to replace the parenthesis by <span> tags and keep the text between the parenthesis.
I did not paste the whole code but basically this is a part of an Inline Parser rule which I add before the "text" rule.

**Comment by puzrin** [comment]
Please, provide examples of text: expected input and desired output.

**Comment by Nautigsam** [comment]
Input: `(test)`
Expected: `<p><span>test</span></p>`
Result: `<p><span><></span></p>`

**Comment by puzrin** [comment]
There are implementations for markup pairs - built in emphasis, [markdown-it-mark](https://github.com/markdown-it/markdown-it-mark) & [markdown-it-ins](https://github.com/markdown-it/markdown-it-ins). IMHO all you need is copy-paste with minimal changes. Is anything wrong with those?

**Comment by Nautigsam** [comment]
Thank you for your links. Finally I changed my markup for `--` instead of parenthesis so I could reuse your code. Closing this issue.
