### ISSUE TITLE
There is no support for Right-to-Left (RTL) languages

### ISSUE THREAD

**Issue by tri-go** [markdown-it/markdown-it#554]
When writing text in an RTL lanugage (for example, Hebrew, Arabic, etc.), writing **should** start from the **right** of the page and continue to the **left**. Most modern text editors support this.

However, in markdown-it demo (and consequently in applications that use markdown-it as a md renderer), when a line begins with Hebrew characters (For example), the line is still aligned to the **left** instead of the **right**.

I'm attaching two pictures to show how the text renders correctly in _Kate (text editor)_ and how it renders in _markdown-it_ demo. I'm also attaching the .md file that I used for testing. It will show several situations:

1. Starting a line with Hebrew characters vs. Latin characters.
2. Mixing Latin text and then Hebrew text vs. first mixing Hebrew text and then Latin text.
3. Starting a line with symbols and then Hebrew/Latin characters

This is how things work (correctly) in Kate (Latin text is aligned to the **left** while Hebrew text is aligned to the **right**):
![RTL-support-in-Kate-markdown](https://user-images.githubusercontent.com/49899269/56850417-163a7f80-690b-11e9-825b-f4091f82bfae.png)

This is how markdown-it demo shows the same text (everything is aligned to the **left** of the page):
![no-RTL-support-in-markdown-it](https://user-images.githubusercontent.com/49899269/56850496-577f5f00-690c-11e9-9d81-4523a424cc8f.png)

For more information about Right-to-Left language systems: https://en.wikipedia.org/wiki/Right-to-left
And for more information about Bi-directional text (mixing RTL languages with Left-to-Right languages): https://en.wikipedia.org/wiki/Bi-directional_text

I'm attaching the .md file that I used in my testing. Github doesn't allow uploading of .md files, so I just chaged the suffix to .txt instead of .md. You can download it and change it back to .md.
[A_note_about_right-to-left_support.txt](https://github.com/markdown-it/markdown-it/files/3123922/A_note_about_right-to-left_support.txt)

Do you think it's possible to fix this and enable RTL?
The wikipedia article about [Right-to-left#Computing_support](https://en.wikipedia.org/wiki/Right-to-left#Computing_support) says: "Right-to-left, top-to-bottom text is supported in common consumer software. Often this support must be **_explicitly enabled_**."
Maybe it just needs to be enabled somehow..

Thank you

**Comment by puzrin** [comment]
Demo is a simplified thing. Nobody plan to spend extra time for it, because that will not affect parser quality anyhow.

If anybody wish add RTL support there send a PR.

**Comment by tri-go** [comment]
I wasn't suggesting adding a RTL support for the demo. I was referring to markdown-it the original parser. The demo reference was just to show the incorrect rendering.

I arrived here after posting about a similar issue in [Vnote](https://github.com/tamlok/vnote) (A note-taking application that uses md and markdown-it to render MD to HTML). The creator of Vnote [said he uses markdown-it as parser, and that's why the editor has no RTL support when rendering md files](https://github.com/tamlok/vnote/issues/759#issuecomment-487244961). 
I thought that if this issue will be solved here, hopefully, it can improve md parsing in many other programs that use markdown-it.

**Comment by puzrin** [comment]
I'm not sure your issue is related to this package:

https://talk.commonmark.org/t/explicit-rtl-indication-in-pure-markdown/286/9

But if you insist, please provide minimal possible (reproducible) code sample, to 
show expected input, expected output and actual output.

**Comment by tri-go** [comment]
In my original post here, I did:
- Provide a minimal possible (reproducible) code sample - that's the text file called [A_note_about_right-to-left_support.txt](https://github.com/markdown-it/markdown-it/files/3123922/A_note_about_right-to-left_support.txt)

-  Showed expected output - that's the screenshot from Kate (text editor) that renders RTL correctly.
![RTL-support-in-Kate-markdown](https://user-images.githubusercontent.com/49899269/56852824-a1763e00-6928-11e9-94b6-1881522872f7.png)

- Showed the actual output using the markdown-it demo (I could've used Vnote's output that is based on markdown-it and showed the same output, but I figured it's best to use your original demo:
![no-RTL-support-in-markdown-it](https://user-images.githubusercontent.com/49899269/56852825-a5a25b80-6928-11e9-8ca3-46eb016d521b.png)

I hope this can help you fix this on markdown-it.
I will also look at commonmark.
Thank you

**Comment by puzrin** [comment]
This is general description, good to explain that problem exists, but not enougth to prove it's related to this package.

If you are sure, bug is related to this package, you are expected to provide smallest possible code sample, not text and screenshots. You could ask vNotes authors to post those. But i'm sure,  parser don't touch any unicode direction marks.

**Comment by tamlok** [comment]
@puzrin Hi! The screenshots given are not in VNote but in the official demo of md-it. BTW, do we need to add extra markup to denote the direction of the text manually in md-it?

Thanks!

**Comment by puzrin** [comment]
@tamlok as i said earlier, demo != parser. It's "quick and dirty", because we have no time to do it better. If you insert LRM/RLM/ARM chars, those should pass intact. I'm not familiar with other details.

**Comment by 3j9fkyahunqoxwqu** [comment]
Hello

I also came here because of [RTL issue](https://github.com/laurent22/joplin/issues/2047) in note taking app "[Joplin](https://github.com/laurent22/joplin/issues/2047)"

I understood that you confirm problem exists and also the demo is not a complete implementation of markdown-it package.

then what do you think about this problem?
what candidates may cause this problem?
may be markdown syntax itself?
or something else?

**Comment by puzrin** [comment]
markdown-it just implements CM spec and is agnostic to RTL. Any questions should be forwarded to commonmark forum or solved via CSS. That's out of this package scope.
