### ISSUE TITLE
How to ignore parsing React code?

### ISSUE THREAD

**Issue by sahibjotsaggu** [markdown-it/markdown-it#555]
I have a use case where I am using @mdx-js/mdx to parse .mdx files that have React code and markdown code in the files. I have another use case where I just need to parse the .mdx files as plaintext but would like to ideally ignore React code because I run into problems where the React code contains something like `arr.attr[something]` and the parser gets thrown off by the `[]`.

So is there a setting I can change to ignore parsing React code or is there an easy way to create a plugin to do that for me?

**Comment by puzrin** [comment]
Sorry, i don't use react, this question is out of project scope.

**Comment by sahibjotsaggu** [comment]
thanks for the help
