### ISSUE TITLE
When will the ruler be called?

### ISSUE THREAD

**Issue by guanpengchn** [markdown-it/markdown-it#556]
I debug `markdown-it-footnote`.

I find that `footnote_inline` function will be called when meet `^`, `[` or `]`.

I want to know where it is defined and how to modify it.

Thank you very much.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it-footnote

**Comment by guanpengchn** [comment]
I know and debug it.

https://github.com/markdown-it/markdown-it-footnote/blob/master/index.js#L179

When input `abc^[abcdefg]abc`, line 179 will only go in three times, where is the function called?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it-footnote/blob/master/index.js#L360-L363

See how those variables are used. Please, avoid general programming questions here.
