### ISSUE TITLE
Doesnt renders code after unordered list

### ISSUE THREAD

**Issue by MobeenAshraf** [markdown-it/markdown-it#558]
Markdown doesnt closes unordered list .   It  can render other markdown syntax correctly but doesnt seems to identify code blocks afterwards.
![image](https://user-images.githubusercontent.com/13708372/57691724-61b89180-765e-11e9-96ad-4e1f58de2bfc.png)
![image](https://user-images.githubusercontent.com/13708372/57691763-7b59d900-765e-11e9-9686-7d544cbdb440.png)

**Comment by puzrin** [comment]
Direct links:

- [markdown-it](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22-%20foo%5Cn-%20bar%5Cn%5Cn%5Cn%5Cn%20%20%20%20baz%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)
- [reference](https://spec.commonmark.org/dingus/?text=-%20foo%0A-%20bar%0A%0A%0A%0A%20%20%20%20baz)

Results are equal => not a bug. You should dig commonmark spec to find why this happens. I don't remember details.

**Comment by MobeenAshraf** [comment]
Is it the reason that code needs to be enclosed in ``` ?

My bad for not understanding?  I was previously using marked and had to move to an alternative solution that supports katex.

Is it possible (any config) that will allow markdown it to use 4 spaces for code blocks

**Comment by puzrin** [comment]
May be. I think, it worth start from this document https://spec.commonmark.org/

This package is only implementation of commonmark spec, with possibility to extend. We stay aside from markup questions.
