### ISSUE TITLE
No example for using the debug output

### ISSUE THREAD

**Issue by Hunchmun** [markdown-it/markdown-it#559]
Hi there,

I've initialized with `html: false` but it still gives me a html output, not the output like that of the debug tab in the demo, is this the intended behaviour or a bug or am I just doing it wrong?

Any help appreciated, thanks!

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/support/demo_template/index.js#L198

This is is demo-specific feature.

**Comment by Hunchmun** [comment]
Thanks!

Solved using `.parse()`
