### ISSUE TITLE
Strong and em combination at different position of word inconsistency. 

### ISSUE THREAD

**Issue by AlexanderSergan** [markdown-it/markdown-it#561]
Greetings!
 
I'd like to ask a question about correct and bugless `em` and `strong` composition. Le'ts assume we want to define `strong` and `em` marks at different parts of word:
`***example***` ->  ***example***
`ex***amp***le` -> ex***amp***le
`***exam***ple` -> ***exam***ple
`ex***ample***` -> ex***ample***

I created small demo with different combinations of `em` marks (`*` and `_`) in markdownIt demo:
[markdownIt demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%23%20Bold%2Fitalic%20word%20wrap%20issues%20demo%5Cn%5Cn%23%23%20Full%20word%20wrap%3A%5Cn%5Cn%2A%2A%2Aitalicbold%2A%2A%2A%20%20%60%3C--%20OK%60%5Cn%5Cn_%2A%2Aitalicbold%2A%2A_%20%20%60%3C--%20OK%60%5Cn%5Cn%2A%2A_italicbold_%2A%2A%20%20%60%3C--%20OK%60%5Cn%5Cn%23%23%20Inside%20word%20wrap%3A%5Cn%5Cnita%2A%2A%2Alicbo%2A%2A%2Ald%20%20%60%3C--%20NONE%60%5Cn%5Cnita_%2A%2Alicbo%2A%2A_ld%20%20%60%3C--%20bold%3A%20OK%2C%20italic%3A%20FAIL%60%5Cn%5Cnita%2A%2A_licbo_%2A%2Ald%20%20%60%3C--%20bold%3A%20FAIL%2C%20italic%3A%20OK%60%5Cn%5Cn%23%23%20At%20start%20of%20the%20word%3A%5Cn%5Cn%2A%2A%2Aitalic%2A%2A%2Abold%20%20%60%3C--%20NONE%60%5Cn%5Cn_%2A%2Aitalic%2A%2A_bold%20%20%60%3C--%20bold%3A%20OK%2C%20italic%3A%20FAIL%60%5Cn%5Cn%2A%2A_italic_%2A%2Abold%20%20%60%3C--%20bold%3A%20FAIL%2C%20italic%3A%20OK%60%5Cn%5Cn%23%23%20At%20end%20of%20the%20word%3A%5Cn%5Cnitalic%2A%2A%2Abold%2A%2A%2A%20%20%60%3C--%20NONE%60%5Cn%5Cnitalic_%2A%2Abold%2A%2A_%20%20%60%3C--%20bold%3A%20OK%2C%20italic%3A%20FAIL%60%5Cn%5Cnitalic%2A%2A_bold_%2A%2A%20%20%60%3C--%20bold%3A%20FAIL%2C%20italic%3A%20OK%60%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)
and [commonmark demo](https://spec.commonmark.org/dingus/?text=%23%23%20Full%20word%20wrap%3A%0A%0A***italicbold***%20%20%60%3C--%20OK%60%0A%0A_**italicbold**_%20%20%60%3C--%20OK%60%0A%0A**_italicbold_**%20%20%60%3C--%20OK%60%0A%0A%23%23%20Inside%20word%20wrap%3A%0A%0Aita***licbo***ld%20%20%60%3C--%20FAIL%20in%20MarkdownIt%2C%20OK%20here%60%0A%0Aita_**licbo**_ld%20%20%60%3C--%20bold%3A%20OK%2C%20italic%3A%20FAIL%60%0A%0Aita**_licbo_**ld%20%20%60%3C--%20bold%3A%20FAIL%2C%20italic%3A%20OK%60%0A%0A%23%23%20At%20start%20of%20the%20word%3A%0A%0A***italic***bold%20%20%60%3C--%20FAIL%20in%20MarkdownIt%2C%20OK%20here%60%0A%0A_**italic**_bold%20%20%60%3C--%20bold%3A%20OK%2C%20italic%3A%20FAIL%60%0A%0A**_italic_**bold%20%20%60%3C--%20bold%3A%20FAIL%2C%20italic%3A%20OK%60%0A%0A%23%23%20At%20end%20of%20the%20word%3A%0A%0Aitalic***bold***%20%20%60%3C--%20FAIL%20in%20MarkdownIt%2C%20OK%20here%60%0A%0Aitalic_**bold**_%20%20%60%3C--%20bold%3A%20OK%2C%20italic%3A%20FAIL%60%0A%0Aitalic**_bold_**%20%20%60%3C--%20bold%3A%20FAIL%2C%20italic%3A%20OK%60%0A)

Looking at fact, that compilation results has such diversity, I'm curious if there is a right way to define such styling constructions in markdownIt? 
Thanks for any clarification.

***
P.S.: 
### markdownIt demo page:
![markdownIt demo](https://user-images.githubusercontent.com/6415224/59036603-4fee9680-8878-11e9-854a-22f190646525.png)
### commonmark demo page: 
![image](https://user-images.githubusercontent.com/6415224/59037879-cab8b100-887a-11e9-8068-31a96bc4aeba.png)

**Comment by puzrin** [comment]
@AlexanderSergan 

By default reference (dingus) implementation has priority.

1. https://spec.commonmark.org/0.29/#emphasis-and-strong-emphasis - that's a right start point to read.
2. Since this repo is about implementation only, https://talk.commonmark.org/ is better place for questions about markup.

Of cause, divergence from reference implementation is not nice and should be fixed. I'd suggest you post your samples to spec repo, because it worth add those into official test cases.

**Comment by AlexanderSergan** [comment]
@puzrin thanks for such quick reply. Please check out PR #562 if they are correct. Im new to this repo and I'm not sure if they are in correct place. Thanks.

**Comment by rlidwka** [comment]
It was changed in commonmark 0.29 (see https://github.com/commonmark/commonmark-spec/commit/83ed53e12aa2e011b04474825bfb22a40682e4a0). Should work now after updating code up to spec.

**Comment by AlexanderSergan** [comment]
Thank you, @rlidwka for the commit. I confirm that this issue resolved with 9.0.0 release.
