### ISSUE TITLE
Easier development of plugins

### ISSUE THREAD

**Issue by fabiospampinato** [markdown-it/markdown-it#563]
Hi 👋 I'm the creator of [Notable](https://github.com/notable/notable) and I'm currently in the process of transitioning it from using [showdown](https://github.com/showdownjs/showdown) to using `markdown-it`.

I've written a few custom Markdown plugins for the app, and many more will be written for it once I open it up to third-party plugins. 

I'm looking for the best way to implement a plugin architecture on top of `markdown-it` which is fast, safe and provides a great developer experience, currently I see the following possible options for it:

### RegEx-based architecture

The current plugin architecture I have is regex-based, basically plugins can perform string substitutions on the raw Markdown and/or on the compiled HTML.

- It's not great for performance, since those regexes have to go through the whole document.
- It's not safe, since we can't really pretend to parse HTML with regexes, and often times we have to be careful that we aren't replacing strings inside attributes, codeblocks etc.
- It's relatively simple to understand for developers though, there isn't much of a learning curve.

### DOM-based architecture

An alternative could be to parse the compiled HTML, perhaps even wrapping it in jQuery, and having plugins manipulate that.

- It's not great for performance, since parsing that HTML can be relatively expensive, plus if we want to do the work in a web worker we would need to provide our own DOM implementation I think.
- It's safe, providing plugins traverse the DOM properly.
- It's simple to understand, many people are familiar with the DOM and/or jQuery.
- Maybe in some cases we need to edit the raw Markdown before it gets processed, in which case we would probably have to provide an alternative API for those plugins.

### Tokens-based architecture

I see "native" `markdown-it` plugins are implemented on top of the internal tokens representation.

- It's great for performance.
- It's safe.
- It allows us to manipulate the raw Markdown too.
- But IMHO it's not ergonomic, people would basically have to understand how the internals of `markdown-it` work and that seems kind of complicated to me, plus not super documented, for instance if I'm writing a plugin that deals with headings tokens it's not clear to me at all where I can learn that maybe I have to find tokens with their `type` property equal to `heading_open`.

Also just to give a more concrete example I see the [mark](https://github.com/markdown-it/markdown-it-mark/blob/master/index.js) plugin consists of ~120 lines of code, when we could get 99% there just with this oneliner:

```ts
markdown = markdown.replace ( /==(.*?)==/g, '<mark>$1</mark>' );
```

Now that would be slower and kind of broken under many circumstances, but it's so much easier to write. Perhaps there's a way to write a plugin architecture that would allow for just as safe and fast as tokens-based plugins to be implemented, without requiring hundreds lines of code for something relatively trivial.

### AST-based architecture

It's mentioned in the docs that an AST could be implemented on top of the currently provided tokens, maybe that would be much more ergonomic to manipulate while still allowing for great plugins to be developed.

### Something else

There are probably other alternative architectures I'm not seeing.

----

All that being said I come to my conclusion: I think lots of amazing third-party plugins will be developed on top of Notable, and I want to develop a plugin architecture for them of top of `markdown-it`.

What kind of architecture do you guys think I should implement? Considering that it should enable fast and safe plugins to be developed very ergonomically.

Would you guys be interested in integrating a more ergonomic plugin architecture on top of `markdown-it` itself? Or would you consider merging in one I could develop?

**Comment by puzrin** [comment]
We follow principle, that all feature extensions for current state of package should be implemented as external modules, if possible. If you wish AST, this can be done by manual call of: parse -> [ast build -> transforms -> tokens out] -> render.

If result become stable and beautiful, one day it can be applied into core.

> Would you guys be interested in integrating a more ergonomic plugin architecture on top of markdown-it itself? Or would you consider merging in one I could develop?

I can not give any promises about big changes. It's impossible to predict all details in advance. You may be interested to see #125 about possible vectors how to kick parser to next spin of awesomeness :). If you have a lot of time and energy to participate - we can discuss details.

**Comment by fabiospampinato** [comment]
Thank your for your answer @puzrin.

> If you wish AST

I'm not sure what the best architecture for my use case should be based upon. Ideally I want to be able to write fast and safe plugins ergonomically, plugins should be able to render almost arbitrary Markdown to arbitrary HTML and if possible the architecture shouldn't be too tied to `markdown-it`, or any other markdown processor, internals.

Do you think an AST would be the best option for me given these constraints?

> If you have a lot of time and energy to participate - we can discuss details.

I want to get Notable's plugin architecture right because I won't be able to significantly change it later on without breaking existing third-party plugins, so in the course of the following months I can dedicate quite some time on this, but I've never written a compiler or even just an AST in the past and I'm not very familiar with `markdown-it` internals, so any hints and tips you can provide would be very useful.

**Comment by puzrin** [comment]
Sorry, i can not give advices about external apps design. IMO your questions are too generic and a bit out of markdown-it scope (without clear resolution criteria).

**Comment by fabiospampinato** [comment]
> Sorry, i can not give advices about external apps design.

Fair enough, I thought it'd be useful to mention my specific use case anyway, even just to provide some more context.

> IMO your questions are too generic and a bit out of markdown-it scope (without clear resolution criteria).

Feel free to ignore the parts related to the app, the issue related to `markdown-it` is that making plugins for it isn't a great developer experience IMO, and I'd be personally interested in volunteering the time required for improving the situation, if it can serve my greater use case too.

I'm not sure if developing an AST would be the right answer or not.

If you have some ideas you'd like me to try for improving `markdown-it` plugin architecture, like I see there's an initial AST spec [here](https://github.com/markdown-it/markdown-ast-spec), I'd be happy to hear them, otherwise I'll just try to come up with a reasonable solution in the following months and share it back 👍

**Comment by puzrin** [comment]
> If you have some ideas you'd like me to try for improving `markdown-it` plugin architecture, like I see there's an initial AST spec [here](https://github.com/markdown-it/markdown-ast-spec), I'd be happy to hear them, otherwise I'll just try to come up with a reasonable solution in the following months and share it back +1

The most lacking feature, which require serious rewrite, is source maps. That requires AST design ans so on. In short - this feature is needed for correct syntax highlight and some markup transforms. From the other hand - none of alternate parsers support it :)

Everything else is not "fatal problem". You may find it easy or not, but it's useable enougth to solve most of your tasks (except highlighting). I'd say, at current level everything possible is already done.

I think, breaking changes should be done only if something important added. IMO, in this case it would be better to start develop lossless AST spec, but that requires significant time and experience in this area.

Let's close this to keep tracker clear, but feel free to continue talk and ask any questions.

**Comment by fabiospampinato** [comment]
> but that requires significant time and experience in this area.

Which I definitely lack 🤔. I'll do some experimentations and see what works best for me, I feel developing an AST would be the "right" choice here, maybe I'll try getting a reasonably good one to work.
