### ISSUE TITLE
Why does the inclusion of punctuation in the emphasis be rendered incorrectly?

### ISSUE THREAD

**Issue by LinFeng1997** [markdown-it/markdown-it#564]
Example：
![image](https://user-images.githubusercontent.com/16188742/59659008-c9bb4400-91d7-11e9-8284-79e799f79642.png)

**Comment by puzrin** [comment]
https://spec.commonmark.org/dingus/?text=**incorrectly%3A**result

Works as original implementation.

Probably, some combination of punctuation + missed space. Please, see commonmark spec for details. It's describes all possibilities.
