### ISSUE TITLE
Bad text of Benchmark in readme

### ISSUE THREAD

**Issue by higimo** [markdown-it/markdown-it#565]
> Sample: README.md (7774 bytes)
>  > commonmark-reference x 1,222 ops/sec ±0.96% (97 runs sampled)
>  > current x 743 ops/sec ±0.84% (97 runs sampled)
>  > current-commonmark x 1,568 ops/sec ±0.84% (98 runs sampled)
>  > marked x 1,587 ops/sec ±4.31% (93 runs sampled)

I read so:
markdown-it performs 743 operations. Worst of all. **Marked** is the **fastest**.

**Comment by puzrin** [comment]
Please send PR with improvement if you think this can be done better.
