### ISSUE TITLE
Broken indentation in ordered lists indented by 2 spaces

### ISSUE THREAD

**Issue by fabiospampinato** [markdown-it/markdown-it#568]
The following code:

```
- Foo
  - Bar
    - Baz
      - Qux

1. Foo
  1. Bar
    1. Baz
      1. Qux
```

Is rendered like so:

<img width="185" alt="Screen Shot 2019-07-07 at 21 17 31" src="https://user-images.githubusercontent.com/1812093/60772881-e541ac80-a0fc-11e9-8bb8-faaa69445a06.png">

IMHO if unordered lists indented with 2 spaces are supported than ordered lists indented with 2 spaces should be supported too.

**Comment by puzrin** [comment]
We implement commonmark spec and do not accept requests about how markup should look. That's out of project scope.

**Comment by fabiospampinato** [comment]
Fair enough, I've moved the issue here: https://github.com/commonmark/commonmark-spec/issues/594
