### ISSUE TITLE
Escape HTML in headers

### ISSUE THREAD

**Issue by iliakan** [markdown-it/markdown-it#571]
Generally, HTML is allowed in my articles.

But for headers like `## Tag <script>`, I'd like to escape HTML, as in headers there should be no markup.

What's the right way to implement that?

**Comment by puzrin** [comment]
I don't know right way. You could inject hook into `core` chain [between block & inline stages](https://github.com/markdown-it/markdown-it/blob/d08c7c38976f5dcdf8dfe9ea3fdf149905001d16/lib/parser_core.js#L15-L16), skan blocks and escape special chars of inline's content if it's between heading tokens. Dirty but simple.

**Comment by iliakan** [comment]
Maybe I can replace content of `html_inline` tokens?

**Comment by puzrin** [comment]
That should work too. Then put such sanitizer in the end of chain, to not care about `.level` of inner tokens, after you drop surrounding `html_inline`.

**Comment by iliakan** [comment]
Great to see you're continuing to work on this project, @puzrin !

**Comment by puzrin** [comment]
Close?
