### ISSUE TITLE
Support for "tel:" link

### ISSUE THREAD

**Issue by HellDevil** [markdown-it/markdown-it#572]
As per the object, it would be appropriate to add support for the "tel:" link type.

Very thanks

**Comment by puzrin** [comment]
We do not support such feature requests here. Please, use plugins for any custom needs.

**Comment by evo-sapio-admin** [comment]
This is not custom.  See<https://www.rfc-editor.org/rfc/rfc3966>

Please re-open!

**Comment by evo-sapio-admin** [comment]
What I expect is for 
```
<+1-23-456-7890>
```
to generate something like <a href="tel:+1-23-456-7890">+1-23-456-7890</a>
