### ISSUE TITLE
Improperly parsed image linking to "file://" url

### ISSUE THREAD

**Issue by fabiospampinato** [markdown-it/markdown-it#573]
The following Markdown:

```markdown
# Test Workbench

![](@attachment/icon_small.png)

![](file:///Users/fabio/Dropbox/Notes/Test/images/icon_small.png)
```

Is rendered like so by CommonMark's own [demo](https://spec.commonmark.org/dingus/?text=%23%20Test%20Workbench%0A%0A!%5B%5D(%40attachment%2Ficon_small.png)%0A%0A!%5B%5D(file%3A%2F%2F%2FUsers%2Ffabio%2FDropbox%2FNotes%2FTest%2Fimages%2Ficon_small.png)):

```html
<h1>Test Workbench</h1>
<p><img src="@attachment/icon_small.png" alt="" /></p>
<p><img src="file:///Users/fabio/Dropbox/Notes/Test/images/icon_small.png" alt="" /></p>
``` 

And like so by markdown-it's own [demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%23%20Test%20Workbench%5Cn%5Cn!%5B%5D%28%40attachment%2Ficon_small.png%29%5Cn%5Cn!%5B%5D%28file%3A%2F%2F%2FUsers%2Ffabio%2FDropbox%2FNotes%2FTest%2Fimages%2Ficon_small.png%29%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D):

```html
<h1>Test Workbench</h1>
<p><img src="@attachment/icon_small.png" alt=""></p>
<p>![](file:///Users/fabio/Dropbox/Notes/Test/images/icon_small.png)</p>
```

**Comment by puzrin** [comment]
That's due default security limits. See commnets there how to enable everything.

https://github.com/markdown-it/markdown-it/blob/master/lib/index.js#L307

**Comment by fabiospampinato** [comment]
@puzrin Shouldn't this be considered a bug given that enabling "CommonMark strict" still doesn't make markdown-it output the same exact html?

**Comment by fabiospampinato** [comment]
Also I don't believe this `validateLink` function is documented, it probably should be.
