### ISSUE TITLE
when using renderInline, highlight doesn't work.

### ISSUE THREAD

**Issue by supertiger1234** [markdown-it/markdown-it#576]
Im trying to use hightlight code thing, it seems to work fine with the render() function but not with renderInline(). any solution?

**Comment by puzrin** [comment]
Highlighting is for blocks only, because inlines do not allow to specify markup language.

You may override appropriate renderer function and add any magic you wish https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.js#L21-L27.

**Comment by supertiger1234** [comment]
Why would you close this and assume everything is fixed?

**Comment by puzrin** [comment]
Because there is nothing to fix, everything works as intended.
