### ISSUE TITLE
Broken html detection

### ISSUE THREAD

**Issue by fabiospampinato** [markdown-it/markdown-it#577]
The CommonMark spec [says](https://spec.commonmark.org/0.29/#html-blocks) that newlines are allowed inside `script`, `pre` and `style` tags, because their ending condition is only the presence of the their closed tag.

This is broken in `markdown-it` as the following:

```markdown
<script>
foo

bar
</script>

<style>
foo

bar
</style>

<pre>
foo

bar
</pre>
```

Is being rendered ([permalink](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Cscript%3E%5Cnfoo%5Cn%5Cnbar%5Cn%3C%2Fscript%3E%5Cn%5Cn%3Cstyle%3E%5Cnfoo%5Cn%5Cnbar%5Cn%3C%2Fstyle%3E%5Cn%5Cn%3Cpre%3E%5Cnfoo%5Cn%5Cnbar%5Cn%3C%2Fpre%3E%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D)) as such:

```markdown
<p>&lt;script&gt;
foo</p>
<p>bar
&lt;/script&gt;</p>
<p>&lt;style&gt;
foo</p>
<p>bar
&lt;/style&gt;</p>
<p>&lt;pre&gt;
foo</p>
<p>bar
&lt;/pre&gt;</p>
```

While CommonMark renders ([permalink](https://spec.commonmark.org/dingus/?text=%3Cscript%3E%0Afoo%0A%0Abar%0A%3C%2Fscript%3E%0A%0A%3Cstyle%3E%0Afoo%0A%0Abar%0A%3C%2Fstyle%3E%0A%0A%3Cpre%3E%0Afoo%0A%0Abar%0A%3C%2Fpre%3E)) it as:

```
<script>
foo

bar
</script>
<style>
foo

bar
</style>
<pre>
foo

bar
</pre>
```

**Comment by puzrin** [comment]
Mmmmm... can this be caused by disabled HTML in markdown-it permalink :) ?

[This](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Cscript%3E%5Cnfoo%5Cn%5Cnbar%5Cn%3C%2Fscript%3E%5Cn%5Cn%3Cstyle%3E%5Cnfoo%5Cn%5Cnbar%5Cn%3C%2Fstyle%3E%5Cn%5Cn%3Cpre%3E%5Cnfoo%5Cn%5Cnbar%5Cn%3C%2Fpre%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D) seems to work (see checkboxes on top).

HTML is disabled by default for security reasons.

**Comment by fabiospampinato** [comment]
That fixes it for the snippet I posted, but I actually have that option enabled already in my code and I'm still seeing this issue in some circumstances. For instance the following:

```markdown
<div>
  <script>
    Foo
    Bar
  </script>
</div>
```

Is being rendered ([permalink](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Cdiv%3E%5Cn%20%20%3Cscript%3E%5Cn%20%20%20%20Foo%5Cn%20%20%20%20Bar%5Cn%20%20%3C%2Fscript%3E%5Cn%3C%2Fdiv%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D)) as:

```html
<div>
  <script>
    Foo
    Bar
  </script>
</div>
```

While this:

```markdown
<div>
  <script>
    Foo
 
    Bar
  </script>
</div>
```

Is being rendered ([permalink](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Cdiv%3E%5Cn%20%20%3Cscript%3E%5Cn%20%20%20%20Foo%5Cn%20%5Cn%20%20%20%20Bar%5Cn%20%20%3C%2Fscript%3E%5Cn%3C%2Fdiv%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D)) as:

```html
<div>
  <script>
    Foo
<pre><code>Bar
</code></pre>
  </script>
</div>
```

I get the same output from CommonMark's own implementation too, so I guess both implementations are buggy in this particular regard? Unless I'm misunderstanding something the spec seems to say pretty clearly that those snippets should be recognized as HTML.

**Comment by puzrin** [comment]
> I get the same output from CommonMark's own implementation too, so I guess both implementations are buggy in this particular regard?

In this case, more high probability is that you misunderstood spec about block HTML tags (it's really a bit cryptic).

As far as i remember, each HTML block can not contain empty lines inside (empty line terminates it).

```
<div>
  <script>
    Foo
 
    Bar
  </script>
</div>
```

This is considered as

- 3 lines of html (line 4 empty => stop)
- `Bar` as markdown (4 spaces => code block)
- 2 lines of html (previous block terminated because indent too small)

See spec, it should have all this details and more examples.

**Comment by fabiospampinato** [comment]
It seems that you're correct, the issue here is that since the html starts with `<div>` it will end as soon as an empty line is found. By removing the wrapper `<div>` then the `script` tag will be parsed correctly.

I'm closing this as it seems to actually be spec-compliant.

But I'm going to open an issue in CommonMark's own repo as this make absolutely no sense to me.

**Comment by fabiospampinato** [comment]
Upstream issue: https://github.com/commonmark/commonmark-spec/issues/597

**Comment by puzrin** [comment]
I'd suggest to search forum first. Don't remember link, but current HTML rules were discussed very long time and very deep, with several iterations. It's current state is compromiss of hundreds edge cases.

In short - it's not possible to invent anything new, not known by spec authors :).

Probably, you may wish to use https://github.com/npm/marky-markdown instead. That's retuned markdown-it, to be more close to github (used to render readme-s on npm registry).

**Comment by fabiospampinato** [comment]
> In short - it's not possible to invent anything new, not known by spec authors :).

I don't agree this sentiment, if the spec were perfect there wouldn't have been multiple revisions to it in the first place.

I don't think the authors agree with that either, as for this specific issue one said:

> We could talk about specific ways to change it (but please, nothing that requires unlimited backtracking).

> Probably, you may wish to use npm/marky-markdown instead. That's retuned markdown-it, to be more close to github (used to render readme-s on npm registry).

That's interesting, I'll take a look at that, thanks!

I'd prefer to use something as portable as possible though, i.e. something that has a spec behind it. The minor issues I've found so far seem to arise because perhaps CommonMark was written focussing too much on machines rather than humans.
