### ISSUE TITLE
Reusing linkify-it instances

### ISSUE THREAD

**Issue by fabiospampinato** [markdown-it/markdown-it#579]
Instantiating `linkify-it` is relatively expensive, this becomes a bit of a performance issue when instantiating `markdown-it` itself multiple times, as a new instance of `linkify-it` is created for each.

This is what we want if we want to customize `linkify-it` for each `markdown-it` instance, but if we want it to always behave the same way it should be possible to reuse an existing `linkify-it` instance.

I propose to add support for passing a pre-instantiated `linkify-it` instance as the `linkify` option.

**Comment by puzrin** [comment]
This does not looks like sample from real wold, and i don't like polish code just for fun. Do you have example when this is really required and creating cache of some markdown-it instances is not enougth?

**Comment by fabiospampinato** [comment]
Kind of, in [notable](https://github.com/notable/notable) I have a `markdown-it` instance used for rendering notes, which has a set of plugins enabled, and another `markdown-it` instance which I use for actually stripping out HTML and Markdown markup, which has another set of plugins enabled.

In the second instance I don't really need `linkify-it` though, ensuring it doesn't get instantiated https://github.com/markdown-it/markdown-it/issues/578 would be a better option for my particular use case.

**Comment by puzrin** [comment]
That doesn't look as example of "really required". What will change if you app will be initialized 2ms faster?

**Comment by fabiospampinato** [comment]
> What will change if your app will be initialized 2ms faster?

I've answered this [here](https://github.com/markdown-it/markdown-it/issues/578#issuecomment-515797356), basically I think every millisecond matters, 2ms here and there add up to something significant.

**Comment by puzrin** [comment]
Closing in pair with #578. Let's return to this after several months, when you collect more data from real product, why this is critical chain.
