### ISSUE TITLE
only allow limited set of tags

### ISSUE THREAD

**Issue by KyleMit** [markdown-it/markdown-it#582]
I'd like to allow users to have a very limited set of markdown formatting options.  Can I specify an explicit set of whitelisted elements?

I'd only like to support, **bold**, *italics*, `code`, and [links](https://github.com/markdown-it/markdown-it/)

So I'd want to permit `<strong>`, `<em>`, `<code>`, and `<a>` and disallow any other types of elements.

It looks like the [`.enable()`](https://markdown-it.github.io/markdown-it/#MarkdownIt.enable) and [`.disable()`](https://markdown-it.github.io/markdown-it/#MarkdownIt.disable) options may provide a vehicle to doing this, but there doesn't seem to be a direct mapping to html tag names.

Also, there is some documentation on [Ruler](https://markdown-it.github.io/markdown-it/#Ruler), but I can't find a comprehensive list of rules or what they do.  I got a rough listing of rule names as follows:

```js
[ 'core', 'block', 'inline' ].flatMap(c => markdownit()[c].ruler.__rules__).map(r => r.name)
// normalize, block, inline, linkify, replacements, smartquotes, table, code, fence, blockquote, hr, list, reference, heading, lheading, html_block, paragraph, text, newline, escape, backticks, strikethrough, emphasis, link, image, autolink, html_inline, entity
```

But then, if I `.enable([emphasis])`, it doesn't seem to automatically disable all other rules so I'm not quite sure what the appropriate way to use this is.

**Comment by KyleMit** [comment]
Here's what I've come up with to limit to just the tags I want

```js
var text = `**Bold** __Bold__ *Italics* _Italics_ \`code\`

[markdown-it](https://github.com/markdown-it/markdown-it)

# Not Allowed

~strikethrough~
`

var disable = [ "replacements", "smartquotes", "table", "fence", "blockquote", "hr", "list", "reference", "heading", "lheading", "html_block", "escape", "strikethrough", "image", "html_inline", "entity"];
var enable = ["normalize", "block", "inline", "linkify", "autolink", 'link', 'backticks', 'emphasis', "paragraph", "text", "newline"]

var md = window.markdownit({linkify: true})
               .disable(disable)
               .enable(enable);

var result = md.render(text);

console.log(result)
```

And here's the example in [jsFiddle](https://jsfiddle.net/KyleMit/bqr0wysc/13/)

It took some fiddling and trial and error to get the enable / disable commands to let the right stuff through

**Comment by puzrin** [comment]
https://markdown-it.github.io/markdown-it/#MarkdownIt.new

You need "zero" preset
