### ISSUE TITLE
where is all the built-in rules?

### ISSUE THREAD

**Issue by zzzgit** [markdown-it/markdown-it#584]
Hi, I want to disable some of the built-in rules.

Where can find all the built-in rule names?
I failed to find it in the documentation.

**Comment by puzrin** [comment]
You need to look into sources:

- https://github.com/markdown-it/markdown-it/blob/master/lib/parser_inline.js
- https://github.com/markdown-it/markdown-it/blob/master/lib/parser_block.js
- https://github.com/markdown-it/markdown-it/blob/master/lib/parser_core.js

**Comment by DimaDK24** [comment]
I want to do the same. Perhaps it's worth mentioning at least links above somewhere in docs?

**Comment by puzrin** [comment]
That's opinion-based. You can suggest PR with improvements to discuss.
