### ISSUE TITLE
It's incompatible with chinese double quotes

### ISSUE THREAD

**Issue by jaune162** [markdown-it/markdown-it#585]
source
```
测试**“这是一段测试”**测试

测试**“这是一段测试”** 测试

**“这是一段测试”**测试

**“这是一段测试”** 测试

**“这是一段测试”**
```

parse result

```html
<p>测试**“这是一段测试”**测试</p>
<p>测试**“这是一段测试”** 测试</p>
<p>**“这是一段测试”**测试</p>
<p><strong>“这是一段测试”</strong> 测试</p>
<p><strong>“这是一段测试”</strong></p>
```

If the symbol of `**` is not start with the line, it‘s get the parsing error.

测试**“这是一段测试”**测试

测试**“这是一段测试”** 测试

**“这是一段测试”**测试

**“这是一段测试”** 测试

**“这是一段测试”**

Oh the github markdown editor is also has this bug!

**Comment by jaune162** [comment]
The [marked](https://github.com/markedjs/marked) is work fine.

**Comment by puzrin** [comment]
Please, read commonmark spec and check at Commonmark dingus, as said in bug issue template, prior to report. Such questions is spec-related and should be discussed at commonmark forum. We do not accept customization requests.
