### ISSUE TITLE
Parsing nested markdown in a plugin?

### ISSUE THREAD

**Issue by sdegutis** [markdown-it/markdown-it#587]
Hello. I have a question about plugin implementation. I've fully read through all the files in `docs` and the API page, and scanned several files in the source, and still can't figure out an answer. I'm not sure whether this question is considered "short enough" to be discussed on the gitter.im site or if this is the better place, so I apologize if I got it wrong.

I'm trying to write a plugin that correctly parses arbitrarily nested content. I'm actually migrating a plugin that I wrote last week for `remarkable` (see jonschlinkert/remarkable#361 for details), because I found out today that MarkdownIt is the real version and is more up-to-date. Kudos @puzrin and @rlidwka on very well designed architecture and great code.

In particular, my plugin parses JSX. I know that there are other plugins which parse JSX instead of HTML, but none of them do it the way I need to do it. And none of their implementations are helpful in answering my question either, because they don't push tokens the way I need to.

In my plugin, when I hit the `<` character, I'm able to use Babel's parser to get an AST that I can then traverse to find inner text nodes within the JSX expression. These should be parsed as markdown. Everything else should be passed as literal inline text.

Here's an example picture demonstrating what I mean. The highlighted text should be interpreted as Markdown, and the non-highlighted text should be emitted as literal text.

<img width="386" alt="Screen Shot 2019-08-19 at 5 24 25 PM" src="https://user-images.githubusercontent.com/4399718/63303703-328d6e00-c2a6-11e9-838a-8827939a9c5c.png">

What I have right now is an array of positions in the text representing the boundary points at each segment here. So in this highlighted sample code, I'd have `[0, 7, 14, 32, 40, ...]`. It starts with 0 and it ends  at the end of the JSX expression.

In my version of this plugin for `remarkable`, I was stored this array as state inside `state.env`, and resumed parsing after consuming each JSX (non-Markdown) node until the array was empty.

In other words, for each highlighted segment of code, I would emit that as `htmltag` (the old version of `html_inline`), and for each non-highlighted segment, I would just return from my rule and let the inline parser continue forward until it hits `<` again. Then I'd resume at the next spot in the array.

Does MarkdownIt's plugin system have a way to do this with proper nesting? More specifically, is there a way for an inline rule to emit a token that signals to MarkdownIt to parse that token as Markdown text again? Or better yet, is there a way to give control back to the inline parser *up to a certain character*, so that I can run through this array in a loop?

Or do I need to keep using my stateful strategy, returning from my inline rule at each non-highlighted segment's end?

Thanks for your time and am looking forward to your advice.

**Comment by puzrin** [comment]
Markdown plugin system if for extending markdown markup. But as far as i understand, your question is about outer wrapper, where you wish to call md parser from. So, short answer is - md architecture is not suitable for such needs.

CM spec considers html tags as raw injections, without any info about coupling and behaviour. Possibilities to extend those (with deterministic behaviour) are very limited.

You should decide first, what is on top level - html or markdown. That will define implementation and limits.

**Comment by sdegutis** [comment]
I probably explained it wrong. My plugin takes Markdown and finds JSX within it *instead of* HTML. JSX is a superset of HTML, it can do everything HTML can do, and even more.

My plugin is finished, I ported it over from Remarkable to MarkdownIt and it works great. (In fact, just moving to MarkdownIt has fixed at least one bug automatically.)

My question was about whether I can simplify my implementation, but as it is, it works very well right now. So I guess never mind.

That said, I do have another question: is token.map ever used? The source code doesn't seem to use it anywhere, I'm not sure what it's purpose is anymore, and it's just extra work to calculate it.

**Comment by puzrin** [comment]
Let's close this if it works.

.map is used in block tokens. For example: https://github.com/markdown-it/markdown-it/blob/master/lib/rules_block/fence.js#L95

**Comment by sdegutis** [comment]
That's where it's set, but I can't find a place that attribute is ever accessed and used, and I did a search for the string `map` throughout the whole project's source code.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/support/demo_template/index.js

**Comment by sdegutis** [comment]
Oh I see, it's there for plugins and user-land, not for internals. Makes sense. Thanks @puzrin.

**Comment by Embraser01** [comment]
Hi @sdegutis! It seems that you succeeded to write the plugin, congrats 🎉. Do you plan on making it available for everyone?
I may need something just like this 🙂

**Comment by puzrin** [comment]
@Embraser01 see https://github.com/markdown-it/markdown-it-container. You need to decide first, do you need to wrap inner markdown OR some magic with processing tokens. That's 2 completely different approaches.

**Comment by sdegutis** [comment]
@Embraser01 it's still pretty rough and buggy and may need a rewrite so probably not anytime soon :)
