### ISSUE TITLE
Linkify-it + mardown-it does incorrect url detection

### ISSUE THREAD

**Issue by jlanzarotti** [markdown-it/markdown-it#588]
Using linkify in combination with markdown-it generates incorrect url detection for the following case:

```
http://www.asdf.com/?4_--_88119_--_489_--_1
```

Linkify-it demo

<img width="976" alt="Screenshot 2019-08-21 at 16 33 20" src="https://user-images.githubusercontent.com/2772605/63411875-73fe5480-c431-11e9-81b2-b9b496a24724.png">

Markdown-it demo

<img width="927" alt="Screenshot 2019-08-21 at 16 32 22" src="https://user-images.githubusercontent.com/2772605/63411877-73fe5480-c431-11e9-993a-19e326fcce2e.png">

**Comment by jlanzarotti** [comment]
Not very familiar with the project structure, but this case is that the tokenization is adding an `em` block. Should it validate first if the string is a link first ?

**Comment by puzrin** [comment]
See #580. That's a known issue, with all details discussed. Not scheduled for fix, but anyone can do PR if interested.
