### ISSUE TITLE
Some commonmark syntax is not support?

### ISSUE THREAD

**Issue by jaune162** [markdown-it/markdown-it#589]
The link syntax
```
[Link][1]
⋮
[1]: http://b.org
```
The image syntax
```
![Image][1]
⋮
[1]: http://url/b.jpg
```
It is not supported in markdown-it, but is the common syntax in commonmark.

**Comment by puzrin** [comment]
[That works](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%5BLink%5D%5B1%5D%5Cn%5Cn%5B1%5D%3A%20http%3A%2F%2Fb.org%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D). Please use permalinks for online demos of markdown-it & CM dingus in your examples.

**Comment by jaune162** [comment]
Oh sorry, is my wrong.
It is need a blank line like this

```
[Link][1]

[1]: http://b.org
```
