### ISSUE TITLE
HTML In Markdown Parser Breaks It

### ISSUE THREAD

**Issue by anishanne** [markdown-it/markdown-it#592]
If I run the markdown parser on

```
# stuff
<h1> more stuff </h1>
```

It ends up rendering as
# stuff
&lt;h1&gt; more stuff &lt;/h1&gt;
And the actual HTML code doesn't render.

So if I need to support HTML & Markdown in my display, it won't work.

**Comment by puzrin** [comment]
[example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%23%20stuff%5Cn%3Ch1%3E%20more%20stuff%20%3C%2Fh1%3E%5Cn%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

You should enable html.
