### ISSUE TITLE
How destroy instance?

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [markdown-it/markdown-it#594]
Read comment.

**Comment by afwn90cj93201nixr2e1re** [comment]
Hi, im using markdown-it inside vue component, which placed inside modal, so, it's creating on each click new instance of component -> new instance of mardown-it.
https://hastebin.com/jifuxalagu.xml - component (read comment on destroyed event),
https://hastebin.com/opekicenux.js - additional link attributes.

So, the question is - how i should destroy markdown-it instance on destroyed event's?
I didn't found it inside prototypes.

Is `this.md = undefined` - enought?

@puzrin - ping

И нужно ли вообще здесь destroy, или gc думаете почистит потом это все? (Просто я не уверен с текущими имплементациями браузеров)

**Comment by puzrin** [comment]
JS uses gc, no destroy needed. That's a generic thing, not specific to this package.

**Comment by afwn90cj93201nixr2e1re** [comment]
;(
That's not nice.
Every package have destroy method. So, ok.
