### ISSUE TITLE
Changelog: document API changes for 9.x and 10.x

### ISSUE THREAD

**Issue by networkimprov** [markdown-it/markdown-it#597]
I use version 8.4.

Changelog at 9.0 doesn't mention any API changes. Could you document them?

Changelog at 10.0 says only:
>If you use external "pairs" extensions, you need sync those with "official ones".

I wrote custom extensions for `<a>` and `<img>`. Could you give an example of how to "sync those with official ones"?

**Comment by puzrin** [comment]
Pairs = emphasis-like. No need to change anything in your case. Details can be found in commit logs. Documentation of such level was never supported.

**Comment by networkimprov** [comment]
Thanks for the quick reply. So no API change for 9.x?

**Comment by puzrin** [comment]
yes
