### ISSUE TITLE
Consider reduce browser build size

### ISSUE THREAD

**Issue by puzrin** [markdown-it/markdown-it#6]
Canditades:

1. Decode entries via DOM, instead of havind big hash (saves ~8k gzipped).
2. Replace autolinker
3. Split rare features to external packages

Entity decode for browser:

```js
var ta;

function decodeEntities(input) {
  ta = ta || document.createElement('textarea');
  ta.innerHTML = input;
  return y.value;
}
```

__UPD__ . Please, note, this ticket is for memo, not for discussion. In teory, it's possible to reduse size from 30kb gzipped to 20kb gzipped, but this question has very low priority. Everyone who need to increase priority, should write something like this:

> I have site [link] with total assets XXXkb gzipped , and difference in 10kb is significant for me

Such info can make sense for priority. Everything else will not make sense.

**Comment by neonstalwart** [comment]
:+1:  marked is ~ 20k minified vs ~ 95k for minified markdown-it.  it's quite a substantial pill to swallow for running in the browser.

**Comment by puzrin** [comment]
You should compare gzipped sizes, not minified. Gzipped is ~30k

**Comment by neonstalwart** [comment]
yup - and marked is ~5.5k gzipped.

assuming i can also do some of the customizations i've been able to do with marked, i'd love to get the benefits of markdown-it but adding another 10% to the total gzipped size of my app is a tough call.

i see you already recognize that you need to reduce the size and i'm just agreeing with you rather than trying to be hostile about it.  something under 20k gzipped would be more palatable.

**Comment by puzrin** [comment]
Size is price for speed, safety (no ddos), flexibility & following specs. marked is from a bit different league :)

There is no need to discuss "is is good to reduce size or not". Sutiation is simple - it's possible to make reduction to ~20k gzipped, but this question has very low priority. This ticked is just for memo, if someone decide to do it.

Everyone who wish to change priority, should write something like:

> I have site [link] with total assets XXXkb gzipped , and difference in 10kb is significant for me

Such info can make sense. Everything else will not make sense.

**Comment by neonstalwart** [comment]
great! my app is ~300k gzipped and a difference in 25kb is significant for me.  admittedly i have custom fonts and images where each of those are larger than all my JS but i am actively working to remove unnecessary weight wherever possible.

links can be provided some time after a public launch currently scheduled for early May 2015 if someone wants to remind me :)

**Comment by puzrin** [comment]
Where will no be difference of 25kb gzipped after optimization hacks. Only 10kb in very optimistic case.

**Comment by c-spencer** [comment]
You don't need to do a full split to get some size benefits if you use webpack/browserify to do the build. If you shift the responsibility of loading rules files to the presets themselves, and add a small layer of indirection in the default index.js to keep the same API, then a slightly different API can be used for a fully modular include, example:

```
var ModularMarkdown = require('markdown-it/lib/modular');
var markdown = new ModularMarkdown(require('markdown-it/lib/presets/commonmark'), { ... });
```

Disadvantage is you'll only be able to enable those modules specified in the preset. Could have each built-in preset include all modules to keep the same behaviour as now, and leave partial setups to advanced users, or include a few extra presets.

I have a basic implementation at https://github.com/sysdea-libs/remarkable/commit/dde784887dc2e1a6266990984cb02225ac830549 (didn't spot markdown-it being rather more active than remarkable before doing).

**Comment by zachmullen** [comment]
Hi @puzrin , I am in the same boat here, trying to choose between this and marked for purely in-browser content rendering, but the 6x size difference between the two libraries is a compelling factor. Not being extremely familiar with the structure of the code in markdown-it, I have no idea how hard it would be to build a browser-only js module... do you think it would be possible? Which source files would need to be included in such a module? (I can download the npm package and use uglify locally to build it if it is just a subset of the source tree.)

**Comment by puzrin** [comment]
Wontfix

**Comment by wifiextender** [comment]
Thanks for the highlights guys, will use another markdown parser instead. The whole conversation reminds me to the following video - https://www.youtube.com/watch?v=okk0BGV9oY0 by @HenrikJoreteg

**Comment by zachmullen** [comment]
@wifiextender I recommend remarkable

**Comment by puzrin** [comment]
@zachmullen strange recommendation - remarkable is in general a very old version of this parcer, with a lot of unresolved issues. You can check commits history and changelog.
