### ISSUE TITLE
package.json missing "bin" value

### ISSUE THREAD

**Issue by mmocny** [markdown-it/markdown-it#60]
Seems you have a cli, but its not added to my PATH automatically after doing `npm install -g markdown-it` because your `package.json` is missing a [`"bin"`](https://docs.npmjs.com/files/package.json#bin), I think.

**Comment by mmocny** [comment]
Seems this may be by design (as per #9), but I think you should re-think it!

**Comment by puzrin** [comment]
If you need CLI, i think it's better to create another issue, with direct CLI request and desired options.

I've moved existing script to another location to avoid confusion.
