### ISSUE TITLE
HTML In Markdown Parser Breaks It IF HTML tag comes first.

### ISSUE THREAD

**Issue by ryan0122** [markdown-it/markdown-it#602]
If I run the markdown parser on

```
<h1> more stuff </h1>
# stuff
```

It ends up rendering as

<h1>more stuff</h1>
`#stuff`

And the actual MARKDOWN code doesn't render.

[example](https://markdown-it.github.io/#md3=%7B"source"%3A"<h1>%20more%20stuff%20<%2Fh1>%5Cn%23%20stuff%5Cn%5Cn"%2C"defaults"%3A%7B"html"%3Atrue%2C"xhtmlOut"%3Afalse%2C"breaks"%3Afalse%2C"langPrefix"%3A"language-"%2C"linkify"%3Atrue%2C"typographer"%3Atrue%2C"_highlight"%3Atrue%2C"_strict"%3Afalse%2C"_view"%3A"html"%7D%7D)

**Comment by puzrin** [comment]
https://spec.commonmark.org/dingus/?text=%3Ch1%3E%20more%20stuff%20%3C%2Fh1%3E%0A%23%20stuff%0A

Works as expected. Read commonmarl spec how html tags work.
