### ISSUE TITLE
Is escaped backtick not supported within backtick's inline code notation ?

### ISSUE THREAD

**Issue by tmori3y2** [markdown-it/markdown-it#604]
- Open https://markdown-it.github.io/
- Input the following markdown

~~~md
`example 1: escape of \``

`a =\`A\``

*example 2-1: escape of \**

_example 2-2: escape of \__

**example 3-1: escape of \*\***

__example 3-2: escape of \_\___

~~example 4: escape of \~\~~~
~~~

`example 1: escape of \``

`a =\`A\``

*example 2-1: escape of \**

_example 2-2: escape of \__

**example 3-1: escape of \*\***

__example 3-2: escape of \_\___

~~example 4: escape of \~\~~~

**Comment by puzrin** [comment]
https://spec.commonmark.org/0.29/#example-329

Please read commonmark spec for generic markup description.

**Comment by tmori3y2** [comment]
I understand it.

~~~md
``example 1: escape of ` within inline code``

``a =`A` ``
~~~

``example 1: escape of ` within inline code``

``a =`A` ``

Thank you !!
