### ISSUE TITLE
Two consecutive periods replaced with ellipsis

### ISSUE THREAD

**Issue by csMACnz** [markdown-it/markdown-it#606]
This has already been raised before with a workaround, but I believe this is still a bug in the implementation: https://github.com/markdown-it/markdown-it/issues/454

When typography is turned on, it is replacing two dots (`..`) with an ellipsis. This should not be the case with 2, but instead 3 dots is what should make an ellipsis (`…`)

I have checked this against commonmark and can confirm it correctly leaves two dots alone, but transforms 3 when smart-punctuaction is used.

[demonstrating the issue in mardown-it](https://markdown-it.github.io/#md3=%7B%22source%22%3A%222019-01..2020-10%5Cn%5Cn2019-01...2020-10%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

[working example in commonmark](https://spec.commonmark.org/dingus/?text=2019-01..2020-10%0A%0A2019-01...2020-10&smart=1)

**Comment by csMACnz** [comment]
It looks like a candidate fix for this has been proposed and rejected. https://github.com/markdown-it/markdown-it/pull/605

It would be great to get this bug fixed, as it affects other applications using this library.

**Comment by csMACnz** [comment]
It looks like this issue is also related, and was also shot down. https://github.com/markdown-it/markdown-it/issues/590

This is certainly a bug that needs fixing, and does not match what other markdown parsers do.

**Comment by puzrin** [comment]
1. This is not related to commonmark anyhow. This is custom extension, disabled by default. The same for dingus. And those are completely different.
2. This is covered with tests.
3. You can disable replacer rule or overwrite with your own, if you don't like it.

You could read CM spec & see test cases first, prior to create issue about not existing "bug".
