### ISSUE TITLE
Zero-width-character-escaped double-asterisk sequence is not ignored, whereas zero-width-character-escaped single asterisk is

### ISSUE THREAD

**Issue by haqer1** [markdown-it/markdown-it#607]
**Reproduction code**:
<pre>var s110="***Essai** 57* :\n Ligne 2.\n2 ​* 3 ​* 4 = 24\nSome langs treat this as equivalent of ^: 2 "
 + String.fromCharCode(8203)+ '*' + String.fromCharCode(8203)+ "*" + " 3 " + String.fromCharCode(8203)+ "*" 
   + String.fromCharCode(8203)+ "* 4 = 4096\nUne ***chose* *très* importante**.";
var md = window.markdownit();
md.render(s110);
</pre>

**Result**:
<pre>
<p><em><strong>Essai</strong> 57</em> :
Ligne 2.
2 ​* 3 ​* 4 = 24
Some langs treat this as equivalent of ^: 2 ​<em>​</em> 3 ​<em>​</em> 4 = 4096
Une <strong><em>chose</em> <em>très</em> importante</strong>.</p>
</pre>

**Expected**: IMHO, (either) 2 ** 3 ** 4 should be there (or for consistency 2 3 4 instead of 2 * 3 * 4).

P.S.
It works if using backslash for escaping double asterisk.

**Comment by puzrin** [comment]
I guess, you misunderstood how asterisks work. Those conditions are a bit cryptic and described in details in CM spec. While backslash is official escape, with zero-width character you change meaning of neighbour, and that's completely different thing. If that helped you in some cases, that doesn't mean it should help everywhere.

I'd suggest to check that with https://github.com/commonmark/commonmark.js first and report here only if result is different.

Or, of i missed moment when ZW character become escape - give me please direct link to spec example.

**Comment by puzrin** [comment]
Close - not a bug (we just follow spec). If you manage to update spec, this package will be updated accordingly, but this should be done not via this repo.
