### ISSUE TITLE
The purpose of line breaks in rendered HTML tags

### ISSUE THREAD

**Issue by tranvuetnghia** [markdown-it/markdown-it#611]
Hi everyone,

I just found out that the rendered HTML included a lot of line breaks (\n). Why do you add it in every single HTML tag?
Example:
```<ul>\n<li>test</li>\n<li>test</li>\n</ul>\n<blockquote>\n<p>test</p>\n</blockquote>\n```

We can replace all ">\n<" by "><" as a workaround solution. Are there any other options to remove it from the result?

Cheers,
Nghia.

**Comment by puzrin** [comment]
Such question is opinion based and can not have right answer. Currently output is the same as from reference implementation. You cam replace renderers if need different result.
