### ISSUE TITLE
Linkify not working if initialized with commonmark and overriding

### ISSUE THREAD

**Issue by altbdoor** [markdown-it/markdown-it#612]
After creating an instance with `commonmark`, it seems that we are unable to override the `linkify` option effectively.

```js
const md = window.markdownit('commonmark')
md.set({ html: false, linkify: true }) // either via set

// or via the presetname and options combo
const md = window.markdownit('commonmark', { html: false, linkify: true })
```

With the configuration above, rendering the markdown content will not linkify the URLs. Strangely enough, the override for `html` works.

Tested with markdown-it v10.0.0 from jsDelivr.

**Sample:** https://jsfiddle.net/2tbuxs3j/

**Question:** Is this the intended behavior? It feels odd that we could override the `html` option, but not the `linkify` option.

**Comment by puzrin** [comment]
That's intended, because only commonmark-related rules are enabled explicit in that preset. If you need additional features, you should enable missed rules back first.

**Comment by puzrin** [comment]
@vast https://github.com/markdown-it/markdown-it/blob/master/lib/parser_core.js#L17

**Comment by altbdoor** [comment]
@vast in case it was not clear, the idea is to enable the `linkify` feature. This is what I've done to make it work.

```js
// initialize markdown-it
const md = new MarkdownIt('commonmark', { html: false, linkify: true });

// enable linkify feature
md.enable(['linkify']);
```

https://jsfiddle.net/w8gejrdb/

Hope this helps.
