### ISSUE TITLE
Custom highlight need more than a customized highlight function to be activated ?

### ISSUE THREAD

**Issue by flesage-000** [markdown-it/markdown-it#614]
Hello,

I try to customize highlighting to add language option because by default it HTML render 

```html
<code>css&lt;br&gt;Code block&lt;br&gt;but multiline and stylized&lt;br&gt;</code>
```

but I need to add language class.

I used both code below :
```javascript
highlight: function (str, lang) {
    if (lang && hljs.getLanguage(lang)) {
        try {
            return '<pre class="hljs"><code>' +
            hljs.highlight(lang, str, true).value +
        '</code></pre>';
    } catch (__) {}
}
// or
highlight: function (str, lang) {
    console.log('plop highlight', lang);
    if (lang && hljs.getLanguage(lang)) {
        console.log('plop IF', lang);
        try {
        return '<pre class="hljs"><code class="' + lang + '">' +
                hljs.highlight(lang, str, true).value +
                '</code></pre>';
        } catch (__) {}
    }

    return '<pre class="hljs"><code>' + md.utils.escapeHtml(str) + '</code></pre>';
}
```

But HTML rendering is always te same.

Note:
- I use "render()" to render multiline blocks
- i pluged highlight-js

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/support/demo_template/index.js#L81 take a look how demo works. You probably also need to register markup languages.

**Comment by flesage-000** [comment]
ok, but why the `console.log` is never shown in console?? It seems that the script totally ignore this part... I change 'HTML' option to false and i am able to see change directly.

**Comment by puzrin** [comment]
I can't debug your code. Can only suggest you to investigate working example.
