### ISSUE TITLE
renderInline doesn't render reference links

### ISSUE THREAD

**Issue by jackdouglas** [markdown-it/markdown-it#615]
var m = window.markdownit('zero').enable(['reference','link']);
m.render('[mylink][1]\n\n[1]: https://dbfiddle.uk');
~~~
"<p><a href=\"https://dbfiddle.uk\">mylink</a></p>
"
~~~
m.renderInline('[mylink][1]\n\n[1]: https://dbfiddle.uk');
~~~
"[mylink][1]

[1]: https://dbfiddle.uk"
~~~

**Comment by puzrin** [comment]
References are not inline. So, works as expected.
