### ISSUE TITLE
Cannot build latest release with webpack

### ISSUE THREAD

**Issue by acao** [markdown-it/markdown-it#616]
thanks for all you do and a great library!

![Screen Shot 2019-11-27 at 9 08 09 AM](https://user-images.githubusercontent.com/1368727/69730096-77227400-10f5-11ea-8851-c7c9add3945a.png)

looks like [the last commit](https://github.com/markdown-it/markdown-it/commit/3d24bda4045f8166ae1932a0be38fbf8b4ba7d19#diff-c3b955ce7acfaa4b102fbafe5132b9b6L6) you made for the 10.0.0 release broke this file path, @puzrin?

**Comment by puzrin** [comment]
I can not comment build process of your project. Probably, old dependencies used somewhere inside. Referred commit reflects changes of `entities` package and is correct -  `markdown-it` has browserified builds and they pass without errors.
