### ISSUE TITLE
Block-before-inline prevents using markdown-it-attrs with markdown-it-toc-done-right

### ISSUE THREAD

**Issue by rauschma** [markdown-it/markdown-it#618]
[According to the author of markdown-it-toc-done-right](https://github.com/nagaozen/markdown-it-toc-done-right/issues/25):

> According to Markdown-it architecture, block rules are always processed before inline rules. Because one of our reasons to exist was exactly to be a block parser and also because markdown-it-attrs is an inline rule, I don't believe this is achievable without bringing that plugin logic into this one (as we did with the markdown-it-anchor).

Is there any way around this limitation? It’d be great to have a TOC that includes IDs as changed via markdown-it-attrs.

**Comment by puzrin** [comment]
Question sounds too wide. I can't investigate third-party plugins code. It's better to ask plugin authors.
