### ISSUE TITLE
Allow "safe" html tags (markdown-it tag whitelisting)

### ISSUE THREAD

**Issue by nmaro** [markdown-it/markdown-it#620]
Creating the issue as a placeholder. I've been searching the web for a plugin or config that does this but wasn't able to find it.
Would it be easy to implement this as a plugin?
I'd like to be able to define a whitelist of allowed html tags (e.g. <iframe>).

**Comment by puzrin** [comment]
That's technically impossible, because "html" in scope of markdown are raw injections. Correct solution is to use sanitizer with output.

I'd suggest to investigate https://github.com/npm/marky-markdown/blob/master/package.json#L70. That package is used to render github's readme in npm registry.

**Comment by nmaro** [comment]
thanks!
