### ISSUE TITLE
Parser for telegram html_mode

### ISSUE THREAD

**Issue by Serfi7** [markdown-it/markdown-it#621]
Hello

I have issue with [markdown_mode](https://core.telegram.org/bots/api#markdown-style) for telegram: telegram markdown parser couldn't parse link like https://github.com/some_repo because parser try parse `_` as italic and couldn't do it. I report this bug to telegram, but they say nothing.
I would like to use markdown-it for telegram and follow [telegram html roles](https://core.telegram.org/bots/api#html-style). 
I have next hardship:
parsed html must not have wrapper like \<p>. Once block element is `pre`. How I can parse `pre` as block, but another message parse inline (without wrapper)? Example: 

input:
> my code:
>  \`\`\`console.log('Hello world');\`\`\`

output:

> my code\<pre>console.log('Hello world');\<pre>

**Comment by puzrin** [comment]
`_` (emphasis) can conflict with linkifier (autolinking), that's a known issue, discussed in previous tickets, not scheduled for fix.

To parse inline content only, without `<p>`, see `.parseInline` / `.renderInline` methods.

**Comment by Serfi7** [comment]
If I use `.renderInline`, \`\`\` will be parsed as \<code>, not \<pre>.

**Comment by puzrin** [comment]
You can override that tag renderer different, as you wish. Everything is tuneable.
