### ISSUE TITLE
langPrefix how to use

### ISSUE THREAD

**Issue by MoonCheung** [markdown-it/markdown-it#622]
Markdown-it configuration inside `langPrefix: 'md-'`, then from the Vue page inside the local style as follows:
```scss
md-javascript: {
  background-color: #fff
}
```
After writing the local SCSS style, it still doesn't show white, I wonder what I did wrong, do I understand wrong

There's another way that markdown-it parses this HTML page without `md-javascript`
![image](https://user-images.githubusercontent.com/19801190/71539511-ed75f880-2977-11ea-911c-30c060f183c5.png)

**Comment by puzrin** [comment]
Questions about vue & css writing are out of project scope.

`langPrefix` is suffix of class name, added to `pre` container in default renderer. Because commonmark spec requires `language-`, but others may prefer `lang-`. This can be overridden by custom renderer.
