### ISSUE TITLE
Can you help to manage this project?

### ISSUE THREAD

**Issue by TroyTae** [markdown-it/markdown-it#623]
Issue from: https://github.com/craigdmckenna/markdown-it-front-matter/issues/4#issuecomment-571437455

Hello, thank you for your maintaining.
For fixing an issue, I created a PR in [markdown-it-front-matter](https://github.com/craigdmckenna/markdown-it-front-matter).
But owner replied like this: "Are either of you interested in taking ownership of this repo and the associated npm package? It's just not in my wheelhouse anymore."
For preventing like this situation, I think it would be better to manage this repo in organization (not individually).
And I think this organization related with markdown-it-front-matter.
Can you help to manage this project?
Thank you :)

**Comment by puzrin** [comment]
Sorry, different priorities. Here are already enough packages to maintain.

**Comment by TroyTae** [comment]
@puzrin 
I understand, thank you for your answer!
