### ISSUE TITLE
double dash not always converted

### ISSUE THREAD

**Issue by nineteentrees** [markdown-it/markdown-it#624]
Double dashes are not always converted, e.g. the following line of markdown

```
2--4--0
```

gets converted to this:

```
2–4--0
```

**Comment by puzrin** [comment]
Is that example fro real world of from fuzzy noise tester? Is that really needs to be fixed?

**Comment by nineteentrees** [comment]
It's real world. It's called Whyte Notation, see https://en.wikipedia.org/wiki/Whyte_notation

It is used for classifying steam locomotives.

**Comment by puzrin** [comment]
Wow, interesting.

https://github.com/markdown-it/markdown-it/blob/master/lib/rules_core/replacements.js#L73-L74 - i see why this happens, but don't know how to fix in nice way (exept repeat replace). Anyway, that's a bug then.

**Comment by nineteentrees** [comment]
I think a look-ahead group in the regex will fix it. I just did a quick test and replaced line 74 with the following one and it seemed okay. Might be good to use look-aheads in the other regex too.

```js
          .replace(/(^|[^-\s])--(?=[^-\s]|$)/mg, '$1\u2013');
```

**Comment by rriegs** [comment]
I'm seeing this with with triple dash, too:
```
we---I---you
```
gives
```
we—I---you
```

**Comment by rriegs** [comment]
I've noticed yet another possibly related issue as shown [here](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22a--%20b%5Cn%5Cna%20--b%5Cn%5Cna--b%5Cn%5Cna%20--%20b%5Cn%5Cna%20b--%5Cn%5Cn--a%20b%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D):
```
a-- b

a --b
```
fail to convert double dashes with white space on one side and non-space on the other, while
```
a--b

a -- b

--a b

a b--
```
all work as intended.  Conversely, em dash works correctly in all of these circumstances.

**Comment by rlidwka** [comment]
@rriegs I'm looking at this:

https://github.com/markdown-it/markdown-it/blob/master/lib/rules_core/replacements.js#L73-L74

```js
          .replace(/(^|\s)--(\s|$)/mg, '$1\u2013$2')
          .replace(/(^|[^-\s])--([^-\s]|$)/mg, '$1\u2013$2');
```

looks to me like it's intended behavior that you have to either put spaces on both sides of dash or neither

**Comment by rlidwka** [comment]
although that's different from commonmark behavior:

```sh
$ ./commonmark/bin/commonmark --smart
a-- b --c
<p>a– b –c</p>

$ ~/markdown-it/bin/markdown-it.js -t
a-- b --c
<p>a-- b --c</p>
```

**Comment by rlidwka** [comment]
fixed, thanks for reporting

> I think a look-ahead group in the regex will fix it.

yeah, look-aheads and look-behinds are extremely useful in these situations

can't use look-behinds for now for compatibility reasons, but worth mentioning that those are coming  (already in node.js btw)
