### ISSUE TITLE
Can I use flow chart in markdown-it?

### ISSUE THREAD

**Issue by luckymore** [markdown-it/markdown-it#625]
`flowchart.js` based `dom`，so make it usable with `markdown-it` is difficult

Please Support flow chart ~

**Comment by puzrin** [comment]
We do not accept such requests here. You should create your own plugin for this need.

**Comment by Mister-Hope** [comment]
emmm you can actually, see this file, hope it can give you some inspiration.

https://github.com/Mister-Hope/vuepress-theme-hope/blob/master/packages/md-enhance/src/markdown-it/flowchart.ts

It is a plugin to support flowchart for markdown files in vupress. 

Official docs: https://vuepress-md-enhance.mrhope.site/guide/tex.html

**Comment by avimehenwal** [comment]
1. [vuepress-plugin-flowchart](https://github.com/ulivz/vuepress-plugin-flowchart) and
2. [vuepress-plugin-mermaidjs](https://www.npmjs.com/package/vuepress-plugin-mermaidjs)

are excellent existing solutions to render flowchars from markdown. Once plugins are installed its as easy as writing following code in markdown

```md
 ```mermaid
 graph TD
   A --> B
 '''
