### ISSUE TITLE
Pass additional context to highlight option from fence renderer

### ISSUE THREAD

**Issue by KyleMit** [markdown-it/markdown-it#626]
This is similar to #456 (Access to the render function from a custom highlight function) but much  more limited in scope. 

In some markdown flavors like [python][0], you can pass additional parameters at the head of a fenced code block like this:

     ```python hl_lines="1"
     # This line is emphasized
     # This line isn't
     ```

Currently, the `options.highlight` callback passes two parameters:

```
options.highlight(token.content, langName)
```

Where `langName` is created by taking all the info available at the head of the fenced code block  and splitting on the first whitespace character

```js
var info = unescapeAll(token.info).trim()  // python hl_lines="1"
var langName = info.split(/\s+/g)[0]       // python
```

The only requested delta is to leave the first two parameters exactly as they are and just pass in the rest of the available context as a third so the highlight function can make use of it:

```diff
if (options.highlight) {
-    highlighted = options.highlight(token.content, langName);
+    highlighted = options.highlight(token.content, langName, info);
```

### Possible workarounds

The same workaround to #456 is available here to override the [`default_rules.fence`][1] implementation, but that leaves a lot of work in the client's flow

Another available workaround is to delimit by a non-space character when shoving extra info to fenced code blocks like this `python,hl_lines="1"`, and then splitting out the language definition inside the highlight function, but this breaks the language detection for other engines where the raw md might live, like in your editor or github.

[0]: https://python-markdown.github.io/extensions/fenced_code_blocks/
[1]: https://github.com/markdown-it/markdown-it/blob/10.0.0/lib/renderer.js#L39

**Comment by puzrin** [comment]
Suggestion sounds reasonable, but i'm very conservative about api changes. I see no strong reasons to decline immediately, but i don't like to make this change too :).

I'd stay this open for a while.

**Comment by KyleMit** [comment]
Seems reasonable - i was able to [locally override the fence handler](https://github.com/VermontDepartmentOfHealth/docs/commit/37abb5da#diff-64bbf3709cc6a42c12f4c84016d29a36) in my own project, so that workaround handles my own workflow.  Only needs to be pulled into core if it helps other folks too.  Thanks

**Comment by rlidwka** [comment]
Fixed, remainder of fence params is now passed through to highlighter as 3rd option.

**Comment by danieleades** [comment]
@rlidwka will this fix only work if the additional attributes are whitespace-delimited, or will it also work if they're comma-separated?

As in-

````
```rust,no_run
fn foo(bar: &Bar) {
    // ...
}
```
````

**Comment by puzrin** [comment]
This is not allowed by CM spec,
