### ISSUE TITLE
query params in img src should not be escaped

### ISSUE THREAD

**Issue by elixiao** [markdown-it/markdown-it#627]
```js
const md = require('markdown-it')()
const str = '![alt](http://image-url-with-query-params.com?width=200&height=100)'
console.log(md.render(str))
```

output:

```html
<p><img src="http://image-url-with-query-params.com?width=200&amp;height=100" alt="alt"></p>
```

`&` is escaped, how could I get the following output?

```html
<p><img src="http://image-url-with-query-params.com?width=200&height=100" alt="alt"></p>
```

**Comment by puzrin** [comment]
Escaping is mandatory, issue header does not look valid.

If you need different behaviour for some reasons, you can try to override image tag renderer https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.js#L89
