### ISSUE TITLE
Q: Rendering back to markdown?

### ISSUE THREAD

**Issue by MaxMotovilov** [markdown-it/markdown-it#628]
How easy would it be to implement the following pipeline with markdown-it:
- Parse to AST
- Transform AST (specific application in mind is automatic translation)
- Save back to Markdown

I have already established that an AST-like representation exists and can be obtained via an API call. It appears that AST transformation can either be done externally or as part of the pipeline via custom plugin(s). What I don't find is a renderer back into Markdown syntax. Does one exist, or is this something that will also have to be implemented?

**Comment by puzrin** [comment]
Markdown-it has no AST. It uses lower level tokens stream. Here is call of parser and renderer https://github.com/markdown-it/markdown-it/blob/master/lib/index.js#L543

**Comment by MaxMotovilov** [comment]
Um - isn't this the HTML renderer? I was asking about the existence of a Markdown renderer. 

Token stream should be as good as the AST for my purposes, perhaps better (simpler to process).

**Comment by puzrin** [comment]
That's not html renderer. I'm not sure you question is related to this package.

**Comment by MaxMotovilov** [comment]
[...Render markdown string into html. It does all magic for you :) ...](https://markdown-it.github.io/markdown-it/#MarkdownIt.render)

This renderer, right? `this.parse(src, env)` produces a token stream and `this.renderer.render(...)` produces HTML text from it? What I'm asking is if there's an out-of-the-box way to produce Markdown text instead.

**Comment by puzrin** [comment]
> What I'm asking is if there's an out-of-the-box way to produce Markdown text instead.

I don't know. That's out of this package scope.

**Comment by MaxMotovilov** [comment]
No worries - I was just asking, not starting a flame :)  Has impact on the scope of what I am looking to achieve.

Thanks!
