### ISSUE TITLE
hightlight dont work in code block

### ISSUE THREAD

**Issue by GouJieShinee** [markdown-it/markdown-it#629]
my markdown string is : ```bash npm install highlight.js ```
but dont`t highlight this bash code

my code is:
import markdown from 'markdown-it'
import hljs from 'highlight.js/lib/highlight';
const markdownParser = markdown('default',{
    html: true,
    highlight: (str, lang) => {
        if (lang && hljs.getLanguage(lang)) {
            if (lang && hljs.getLanguage(lang)) {
                return hljs.highlight(lang, str, true).value;
            }
        }
        return '';
    },
});

hope somebody can tell me what error in code

**Comment by GouJieShinee** [comment]
up

**Comment by pavittarx** [comment]
add a `.css` file for styles you want to apply. `Markdown-It` just converts your markdown to HTML, all the styles you see are browser rendered. So, you won't see any colors or styles unless you add some.

**Comment by puzrin** [comment]
[Works as expected](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%60%60%60sh%5Cnbash%20install%20highlight.js%5Cn%60%60%60%5Cn%5Cn%60%60%60sh%5Cn%24npm%20install%20highlight.js%5Cn%60%60%60%5Cn%5Cn%60%60%60c%5Cnint%20c%3B%5Cn%60%60%60%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)
