### ISSUE TITLE
Gist embeding

### ISSUE THREAD

**Issue by dan-online** [markdown-it/markdown-it#630]
Is there a way to embed a gist into markdown that markdown-it could render? 

Example gist embed tag: <script src="https://gist.github.com/dan-online/5d9d75db54ff2720a8cee6c59f622551.js"></script>

Thanks in advance for any comments :)

**Comment by puzrin** [comment]
You could create plugin, scan tokens and replace paragraphs with single gist link for raw html tags. There are too many ways to reach desired result. Your question is too wide and a bit out of scope.
