### ISSUE TITLE
How to modify the regex of an existing tag?

### ISSUE THREAD

**Issue by iMrDJAi** [markdown-it/markdown-it#632]
Hello, the question is clear: **How to modify the regex of an existing markdown tag?**

## Backgrounds:

I was trying to add a support for the spoiler tags `>!spoiler!<`, this standard is used on Reddit, and because I'm working on a custom Reddit app using Electron I have to setup some extra tags on **markdown-it**.

I tried to start working so the first thing that I did is reading docs, but tbh I didn't understand anything there (I feel dumb).

So I searched a lot about about a simple way, then I found a module called [markdown-it-regexp](https://www.npmjs.com/package/markdown-it-regexp), and it was a perfect solution, it will help me to add the rest of the markdown tags on Reddit.

Now I made it using a simple function:

```js
var plugin = require('markdown-it-regexp'); //I will find a way to use this module on browser too, but it's ok for now because I'm working on Electron
var markdownitspoiler = plugin(
    /\>\!([\s\S]+?)\!\</,
    function(match, utils) {
      return '<span class="spoiler">' + utils.escape(match[1]) + '</span>';
    }
  )
var md = window.markdownit({/*...*/}).use(markdownitspoiler);
```
As you can see, this is so simple, now let's check what we got:

![image](https://user-images.githubusercontent.com/42304709/72814531-7c1f2200-3c65-11ea-8d08-6ec57d67498f.png)

1- What you see on Reddit.
2- The text without rendering.
3- The text with markdown-it rendering.

Now you can guess, the blockquote tag is overriding my custom tag, this will lead me to ask:

> **How to modify the regex of an the blockquote markdown tag?**

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/rules_block/blockquote.js

You could clone blockquote's rule source, add check that `>` is not followed by `!` and replace original one with your modified.

**Comment by iMrDJAi** [comment]
#I checked that and not I have some questions:

1- What's exactly the name of the name of the variable that I have to check? I have to fully analyse the code to find it myself, this will be hard to me.

2- Since I prefer to use the browser version and not the node module, how to include there changes on `markdown-it.js`?

**Comment by puzrin** [comment]
Sorry, i have no possibility to help with generic programming questions.

**Comment by digitalmoksha** [comment]
@iMrDJAi can you customize the spoiler plugin to use the syntax you need?  

https://www.npmjs.com/package/markdown-it-spoiler

**Comment by iMrDJAi** [comment]
I just would say that it's done, by adding this:
```js
  // check if it's not a spoiler tag 'Change by ${Mr.DJA}'
  if (state.src.charCodeAt(pos++) === 0x21/* ! */) { return false; }
  pos--
```
After the line number 2489 on the file `markdown-it.js`:

![image](https://user-images.githubusercontent.com/42304709/73066645-dfe45d80-3ea6-11ea-81a3-3dc4779d6325.png)

I think I'm gonna make a pull request to add this, since it will help people who wanna use the spoiler tag and it will not gonna affect the blockquote tag at all.

**Comment by iMrDJAi** [comment]
@digitalmoksha Actually no, I don't really know how to deal with plugins, I used [markdown-it-regexp](https://www.npmjs.com/package/markdown-it-regexp) for that.

**Comment by iMrDJAi** [comment]
> 
> 
> @iMrDJAi can you customize the spoiler plugin to use the syntax you need?
> 
> https://www.npmjs.com/package/markdown-it-spoiler

@digitalmoksha I made a library to add spoilers like those on Reddit: https://github.com/iMrDJAi/markdown-it-reddit-spoiler
