### ISSUE TITLE
A question about reference-style links rendering.

### ISSUE THREAD

**Issue by iMrDJAi** [markdown-it/markdown-it#636]
So I was working on some custom markdown tags using **markdown-it-regex** package, and I used another rendering functions to convert the text inside these tags, and it works perfectly.
My question is not about custom tags, or plugins development, but it's about reference-style links.
So since the extra rendering functions converts only the text inside the custom tags, using reference-style will not gonna work since the syntex is not inside the rendered text and its located in another part of the document.
I wanna know more about reference-style links rendering, I know that a links map will be stored somewhere while rendering, so how to get this object for external use?

**Comment by puzrin** [comment]
Those are stored in `env`, last param of parser call. Please, inspect sources before create such issues.

**Comment by iMrDJAi** [comment]
Hmmm sorry, I opened this issue using mobile, that's why I didn't give more details.
So `env` will store it, thanks for the info.

**Comment by iMrDJAi** [comment]
@puzrin Excuse me, I think I didn't really understand you.
So after some tries I ended with this:
```js
var ref = window.markdownit('zero').enable('refernece');
console.log(ref.parse(text, {}));
```
On the output I can only see the the tokens of the rendered text, but nothing about references, I don't really know what I supposed to do since I still trying to understand the renderer system.
