### ISSUE TITLE
[Question] I need some help with the MarkdownIt.parse method

### ISSUE THREAD

**Issue by salahmak** [markdown-it/markdown-it#638]
Hi, I recently discovered the `MarkdownIt.parse` method, and I see it very helpful for creating some custom tags by dealing directly with tokens instead of the rendered output according to the [docs](https://markdown-it.github.io/markdown-it/#MarkdownIt.parse).
I have 2 questions about it:
* I see on the docs `MarkdownIt.parse(src, env)`, `src` is the input string and that's clear, but I'm wondering about `env` (environment sandbox) since I can't find something about the object data itself on the docs, so what should I include inside it? Is there any good examples for that?
* The docs has been mentioned **references** many times and I already have seen a scenario that I have to deal with the `MarkdownIt.renderInline` method to include some of them.
    * First of all how to extract their tokens from a string using MarkdownIt.parse method? I tried `markdownit().parseInline(str, {})` and I can only see the links/imgs tokens but not references, I know that they will be removed during the process so what's the right way to get an object with the references links? 
   * Does passing that object directly into `env` will work?

That's all, I hope that I will get the needed answer, and thanks

**Comment by puzrin** [comment]
As far as i remember, references are processed at block level https://github.com/markdown-it/markdown-it/blob/master/lib/parser_block.js#L21. If you use inline percer only, there will be no info to create objects. I'd suggest to inspect list of plugins in each parser. That will give you direction how to quickly find desired part.

Common method to pick internal structs is to pass env object by ref:

```js
let env = {};

let tokens = md.parse(src, env);

console.log(env);
```
