### ISSUE TITLE
`Token.hidden` doesn't work for `Renderer.prototype.renderInline`

### ISSUE THREAD

**Issue by duduluu** [markdown-it/markdown-it#639]
I try to hide some contents in output via setting the property `hidden` as `true` of tokens.
But it only hide tags, the inline contents still be output.

My code:
```js
const md = MarkdownIt();

md.core.ruler.push('hide-title', ({ tokens }) => {
  for (let i = 0; i < tokens.length; i++) {
    const token = tokens[i];
    if (token.type === 'heading_open' && token.tag === 'h1') {
      // hide h1 open tag
      token.hidden = true;

      // hide h1 inline content
      tokens[i + 1].hidden = true;
      tokens[i + 1].children.forEach(c => (c.hidden = true));

      // hide h1 close tag
      tokens[i + 2].hidden = true;
    }
  }
});
```

Input:
```md
# This is title
This is the first paragraph.
```
Output:
```html
This is title
<p>This is the first paragraph.</p>
```

I check out the source code and find `Renderer.prototype.renderInline` doesn't detect `hidden` property, but `Renderer.prototype.renderToken` does detect.

**Comment by puzrin** [comment]
That's an internal hack to render tight lists (without paragraph). You should not use it.
