### ISSUE TITLE
Tidier way of allowing nested blocks than doing src changes in core?

### ISSUE THREAD

**Issue by pragdave** [markdown-it/markdown-it#640]
I'd like to do something like _markdown-it-container_, but supporting nested containers:

~~~
::: slide
# Here's a diagram
::: mydiagram
code for the diagram
:::
See, it's easy...
:::
~~~

(So in this example, the first ::: would close the _diagram_ block, and the second the _slide_ block)

I tried seeing if I could go recursive in the block processing, but I couldn't work out any way to make it work.

I can obviously do it in core, but that feels like I'm bypassing a bunch of your architectural goodness. Am I missing a trick?

Cheers

Dave

**Comment by puzrin** [comment]
Nested containers are supported in `markdown-it-container`. You just need increase (or decrease?) amount of `:` in each nesting.

**Comment by pragdave** [comment]
Sorry, I'm dumb....
