### ISSUE TITLE
Windows Paths in Image Tags

### ISSUE THREAD

**Issue by BrekiTomasson** [markdown-it/markdown-it#642]
I'm building a system that auto-generates PDF versions of Markdown files based on various templates, custom commands, etc. So far, everything is going well, except when it comes to images on Windows computers.

I've already got the system parsing the correct path, so a user entering ![](image.jpg) will have the file field rewritten to the full absolute path. However, on Windows that path might be C:\temp\image.jpg, so the final image tag in the HTML becomes:

<img src="c:%5Ctemp%5Cimage.jpg" alt="" />

Now, this works when I replace the file paths with "normal" slashes instead of backslashes, but I can't just do a simple "replace-all" in my Markdown as this would kill my current escaping of characters that need escaping. Is there any reason to assume that markdown-it can be made to handle backslashes in paths better?

**Comment by puzrin** [comment]
There MUST be valid URL, that's not the same as windows file path. See commonmark spec. You can not just put there anything you wish.
