### ISSUE TITLE
Typographer converts quotes incorrectly between punctuation

### ISSUE THREAD

**Issue by rriegs** [markdown-it/markdown-it#643]
Typographer incorrectly renders input including quotes between other punctuation (including other quotes), such as
```
The dog---"'man's' best friend"
```
which incorrectly yields
```
The dog—&quot;‘man’s’ best friend&quot;
```
without converting the straight quotes to double quotes.  Single quotes are also converted incorrectly in similar circumstances, for instance the UK version of the above:
```
The dog---'"man's" best friend'
```
yields
```
The dog—’“man’s” best friend’
```
where the leading single quote faces the wrong way.  (Almost invisible in GitHub's font, unfortunately.)

Adding a space between the leading punctuation mark and the quote fixes the problem, but this (a) affects the output and (b) can itself interfere with typographer if the leading punctuation is also a quote, i.e. `"'"foo"'"` cannot be 'fixed' with `" '"foo"'"`.

While correct behavior is clear for the example shown, namely
```
The dog—“‘man’s’ best friend”
```
it's not immediately obvious how to decide correct behavior for all input.  Em dashes in particular are space-*like,* and so perhaps could be treated as such unless there is actual white space on the other side of the quotation mark.  This still doesn't address quotes between other quotes; for that, it may be necessary to look ahead and behind past all adjacent punctuation to determine if the nearest non-punctuation character is white space or otherwise.

**Comment by puzrin** [comment]
Seems issue contains too much. First, keep in mind, built-in typographer is simple/basic, and there are no plans to make it full-featured. This should be done via plugins, and discussions about euristics should be kept aside.

But we could try to fix obvious bugs. Could you narrow down your example and express it via online demo? Something like [this](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22Not%20works%3A%5Cn%5Cn-%20dog---%5C%22%27man%27s%27%20best%20friend%5C%22%5Cn%5CnWorks%20%28but%20syntax%20is%20bad%2C%20space%20should%20not%20be%20added%29%3A%5Cn%5Cn-%20dog---%20%5C%22%27man%27s%27%20best%20friend%5C%22%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D). If it's the only "obvious bug" - then just confirm.

**Comment by rriegs** [comment]
Thanks for the response, and the demo link you give exactly expresses the behavior I'm having trouble with.  The quickest fix seems to be treating em dash the same as white space for the purpose of quotation marks and not worrying about the other behavior I mention.

**Comment by rlidwka** [comment]
Fixed by allowing opening quote to be inside of punctuation sequence. It wasn't allowed before, don't remember why, probably just didn't find any useful cases until now.
