### ISSUE TITLE
How can I run only a custom markdown-it plugin rule (no built in markdown rules)

### ISSUE THREAD

**Issue by seanblue** [markdown-it/markdown-it#645]
I have a custom plugin for markdown-it and for reasons not worth going into, I want to run text through markdown-it and have it *only* change text based on the plugin's rules and no other markdown-it rules. For example, let's say my plugin's rule is to replace "abc" with "123".

Given the following text:
```
Today **is**

an abc

kind of day
<br/>
needed breaks for some reason
```

I would want to get back:
```
Today **is**

an 123

kind of day
<br/>
needed breaks for some reason
```

I don't want to convert `**` to `strong`, or add `p` tags around anything, or escape the `<`/`>` from the `br` tag (or escape any other characters), or make any other changes I'm not considering.

I managed to avoid converting `**` (and similar markdown) by using the "zero" preset. And I managed to avoid the `p` tags and keep the `\n` line breaks instead using `renderInline` instead of `render`. However, `<br/>` gets converted to `&lt;br/&gt;` which is not desirable.

Is there a way to simply run my custom rule directly to avoid all these considerations? Or if not, is there a way to stop markdown-it from escaping characters?

I appreciate the help!

**Comment by puzrin** [comment]
`<br/>` is escaped because raw html is disabled by default. See 'html' option. Also, if you use zero preset, you need to enable appropriate html rules back, those are responsible for passing html tags as is.

**Comment by seanblue** [comment]
@puzrin Replacing `markdownit('zero')` with `markdownit('zero', {'html': true})` doesn't fix the issue. How do I allow specific tags through?

And should I take this to mean that there is no way to run just a specific plugin's rules?

**Comment by puzrin** [comment]
See https://github.com/markdown-it/markdown-it#manage-rules

Probably `.enable([ 'html_inline', 'newline' ])`. Inspect lists of rules by references at link above. That will give you idea what can be enabled or disabled.

> How do I allow specific tags through?

If you ask about specific html tags - only if you replace default "html_*" rules with your custom ones.

**Comment by seanblue** [comment]
@puzrin Thank you, that did fix the issue with `<br/>`. The last issue I'm having is that some characters like `>` or `"` are being escaped. I looked through the link you suggested and tried enabling `escape` and `text`, but neither of those helped. Any suggestions for that?

**Comment by puzrin** [comment]
That's a markdown, it MUST provide valid output with properly escaped characters. Exclusion is html tags (and that's why it's disabled by default). If you need unescaped chars, probably you use this package in wrong way.

You can overwrite text tokens renderer https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.js#L112, but i strongly recommend too avoid such things.
