### ISSUE TITLE
How to change a plugin to work with renderInline

### ISSUE THREAD

**Issue by jackdouglas** [markdown-it/markdown-it#650]
I have a generic 'object' plugin that I've based off an existing plugin:

https://topanswers.xyz/lib/markdown-it-object.js

How do I make the plugin render with renderInline? I'm just looking for pointers to get started, not asking more than that.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/index.js#L240

I should be assigned to `md.inline.ruler` chain, not to block one.
