### ISSUE TITLE
Types problem: Ruler

### ISSUE THREAD

**Issue by Mister-Hope** [markdown-it/markdown-it#651]
```ts
import MarkdownIt = require(".");
import State = require("./rules_core/state_core");

export = Ruler;

declare class Ruler<S extends State = State> {
    after(afterName: string, ruleName: string, rule: MarkdownIt.Rule<S>, options?: any): void;
    at(name: string, rule: MarkdownIt.Rule<S>, options?: any): void;
    before(beforeName: string, ruleName: string, rule: MarkdownIt.Rule<S>, options?: any): void;
    ...
    push(ruleName: string, rule: MarkdownIt.Rule<S>, options?: any): void;
}
```

There are issue with the type defination `rule: MarkdownIt.Rule<S>`.

```ts
    interface Rule<S extends State = State> {
        (state: S, silent?: boolean): boolean | void;
    }
```

It fits the `parser_inline` at [here](https://github.com/markdown-it/markdown-it/blob/master/lib/parser_inline.js#L91)

For `parser_core` [at line 51](https://github.com/markdown-it/markdown-it/blob/master/lib/parser_core.js#L51) should be 

```ts
    interface Rule<S extends State = State> {
        (state: S): boolean | void;
    }
```
and the types fits, at least.

But `parser_block` at [here](https://github.com/markdown-it/markdown-it/blob/master/lib/parser_block.js#L79) will throw a type error,

because it expext the rule to be

```ts
    interface Rule<S extends State = State> {
        (state: S, line:number, endline: number, silent?: boolean): boolean | void;
    }
```

I hope you can fix it by changing the rule type in Ruler to a union type.

**Comment by Mister-Hope** [comment]
Besides, I don't think it's a hard work to ship the whole project to ts, which will give the developer and the user greater experience.

Would you consider it?

**Comment by puzrin** [comment]
We do not support ts and have no plans to rewrite "just for fun". Those .ts file was commited by volunteers. If you wish to change it - do PR please.

**Comment by Mister-Hope** [comment]
> We do not support ts and have no plans to rewrite "just for fun". That .ts file was commited by volunteers. If you wish to change it - do PR please.

From other issues, I figured out you are not familar and also not rate it. But more and more repos are mirigating typescript. I just throw a advice, but "just for fun" words, really offense people. Wish you have no fun in the future.

**Comment by puzrin** [comment]
@Mister-Hope under "just-for fun" i mean nothing offensive, only lack of arguments/motivation. I have a lot of parallel projects for development/support. Spending time for rewrite with zero added value is not rationale (because much better alternatives available).

**Comment by Mister-Hope** [comment]
> @Mister-Hope under "just-for fun" i mean nothing offensive, only lack of arguments/motivation. I have a lot of parallel projects for development/support. Spending time for rewrite with zero added value is not rationale (because much better alternatives available).

I got it, I may behave unduly. I am not an English speaker, and "just for fun" is not a good word in my home language.

**Comment by Mister-Hope** [comment]
BTW, would you accept the PR if someone migrate it to Typescript?

**Comment by puzrin** [comment]
Then i will have to learn ts to be able to maintain rewritten package. Alternative to do nothing still looks more attractive :).
