### ISSUE TITLE
Markdown it is not considering successive line breaks ?

### ISSUE THREAD

**Issue by MuhammadMattiullah** [markdown-it/markdown-it#654]
I am using a package https://github.com/iamacup/react-native-markdown-display to convert my content to markdown and this package is using markdown it to handle markdown but when i am used successive line breaks in content. It does not consider it and combine the spaces into one.
Can you please tell how can use multiple linebreaks in markdown ?
Example string provided below:

**Hello**

_This is me_

Regards

When i am rendering this string it ignores all the breaks and combine all the lines together like
Output
**Hello**_This is me_Regards
@puzrin i need your input. Please guide
Thanks in advance

**Comment by puzrin** [comment]
I can not provide help for third party packages.

This package has option [`breaks`](https://github.com/markdown-it/markdown-it#init-with-presets-and-options). Here is an [example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%221%5Cn2%5Cn3%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Atrue%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D).

**Comment by MuhammadMattiullah** [comment]
@puzrin might be i cant explain the question well.
I just provided you the reference of package which is using markdown-it. I am asking about the conversion of markdown-it that how does it handle the multiple linebreaks.

**Comment by puzrin** [comment]
Sorry, due lack of time, no possibility to help with software developed by other people. You'd better ask authors of that package.

**Comment by braintapper** [comment]
I'm having the same issue as @MuhammadMattiullah's, and the `breaks = true` option doesn't solve it. 

This markdown:

```
# heading 1

  

  

  

  

  

some blank lines above this text

  

  

  

  

multiple blank lines above this text
```

Renders as this [example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%23%20heading%201%5Cn%5Cn%20%20%5Cn%5Cn%20%20%5Cn%5Cn%20%20%5Cn%5Cn%20%20%5Cn%5Cn%20%20%5Cn%5Cnsome%20blank%20lines%20above%20this%20text%5Cn%5Cn%20%20%5Cn%5Cn%20%20%5Cn%5Cn%20%20%5Cn%5Cn%20%20%5Cn%5Cnmultiple%20blank%20lines%20above%20this%20text%5Cn%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Atrue%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D):

```
<h1># heading 1</h1>
<p>some blank lines above this text</p>
<p>multiple blank lines above this text</p>
```

I expected to see a few `<br>`s in there when `breaks = true`, but that's not happening.

While I understand that the Markdown spec strips away extraneous whitespace, it would be nice if there was an option to convert blocks of empty lines as `<br>` tags.

**Comment by MuhammadMattiullah** [comment]
@braintapper multiple line breaks are not supported by Markdown. Markdown's syntax doesn't support multiple line breaks and if there are successive line breaks then it considers it as a single line break only.
But still if u wish to add line breaks then you could do some tweak with your body content like this:
```export const MarkdownText = ({ body, onLinkPress }) => {
  const linked = linkify(body);
  const markdownChildren = body.split('\n').map(row => {
    if(!row?.length) return (<Text> {' '} </Text>);    
    return(
      <Markdown
        onLinkPress={(url) => onLinkPress(url)}
        style={{ link: { color: '#007BC7' } }}
        rules={rules}>
        {linked}
      </Markdown>
    );
  });
  return markdownChildren; 
};
```
So what i did in the above code. I just iterated over the body and based on the line-breaks i m getting from the content i just created the desired response in which the line breaks will be considered as it is.

**Comment by braintapper** [comment]
@MuhammadMattiullah  Thanks for the response. 

Originally I was planning on storing my rich text editor's content in my db by using `turndown` to convert the editor's html data into markdown and then  converting it back to html using `markdown-it` (in case I decided to switch editors, as different editors produce slightly different html).  

As part of the round trip, the html never came back the same as it went in because of the extra blank lines, although it was easy to address using a method like yours.

In the end, I found a rich editor that I could use long term (quill), and then opted not to store the content as markdown in my db.

**Comment by adelriosantiago** [comment]
This can also be solve by replacing two line breaks (in Regex `/\n\n$/`) with a line break and an invisible character (`\n `). Note that the character after `\n` is an Alt+0160 or an invisible character.

Here is a sample code and result:

```text
1

2


3


4




5
```

processing with `md.render(string.data.replace(/\n\n$/gm, "\n "))` becomes in markdown-it rendered text:

![image](https://user-images.githubusercontent.com/5462382/108613137-c61c8f00-73b4-11eb-8b3d-3e949fc584be.png)

**Comment by quaos** [comment]
> This can also be solved by replacing two line breaks (in Regex `/\n\n$/`) with a line break and an invisible character (`\n `). Note that the character after `\n` is an Alt+0160 or an invisible character.
> 
> Here is a sample code and result:
> 
> ```
> 1
> 
> 2
> 
> 
> 3
> 
> 
> 4
> 
> 
> 
> 
> 5
> ```
> 
> Rendered with `md.render(string.data.replace(/\n\n$/gm, "\n "))` becomes:
> 
> ![image](https://user-images.githubusercontent.com/5462382/108613137-c61c8f00-73b4-11eb-8b3d-3e949fc584be.png)

Thanks! I inserted `'&#0160;'` before `\n` in my code and it worked like a charm!
