### ISSUE TITLE
Redeploy https://markdown-it.github.io/ (gh-pages branch) to incorporate new fixes

### ISSUE THREAD

**Issue by roryokane** [markdown-it/markdown-it#655]
I noticed that the website https://markdown-it.github.io/ still doesn’t incorporate my fix https://github.com/markdown-it/markdown-it/pull/600 made on 2019-10-02. This is because the [`gh-pages` branch](https://github.com/markdown-it/markdown-it/tree/gh-pages) was last deployed on 2019-09-10.

Can you please **run `make gh-doc`** ([this Makefile target](https://github.com/markdown-it/markdown-it/blob/f798bea9623277bbf89b9621cf7fb283c693fcab/Makefile#L59-L67)) to update the `gh-pages` branch, which will redeploy the website?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/releases

It's updated when release happens to be in sync.
