### ISSUE TITLE
Possibility to render html in code block

### ISSUE THREAD

**Issue by chenbin11200** [markdown-it/markdown-it#657]
I would like to mark some codes in the code block by using HTML inline style, e.g. define background color for a piece of code.
```html
<span style="background-color:#FFFF00">codes I want to emphasise.</span>
```
This is normally supported, even in quote block it works, but not in code block. In order to achieve that, I could use:
```java
<pre>
<code>This is my <span style="background-color:#FFFF00">code.</span>
</code>
</pre>
```
Well, you can not see the "correct" result in github, but I believe you understand what is expected result. But in this way, it will overwrite the code highlight feature in code block.
I understand that, the codes in the code block will/should be escaped, because there exists some programming languages, such as HTML.
How about define a second parameter for the code block? For example, if I define a code block by ` ```java renderHTML`, then the HTML code will not be escaped in the code block, and will be rendered correctly as HTML code, then one can take advantage of hundreds HTML/CSS styling features in code block?

This feature might be discussed before, but I didn't really find a good solution. If there is a way, would you mind tell me how to achieve this feature?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.js#L39 you can override default renderer, and process infostring / content as you wish.
