### ISSUE TITLE
How to modify headers generated code

### ISSUE THREAD

**Issue by jcubic** [markdown-it/markdown-it#659]
I can't find this information in docs. I would like to add something like https://github.com/npm/marky-markdown where you have links with anchors before the header (SVG image like on GitHub) and add id with normalized title.

```
<a href="#some-title"><svg>...</svg></a>
<h1 id="some-title">Some Title</h1>
```

next step would be to generate TOC, this would not be that hard because I can extend the library with my `{{TOC}}` token, but without headers that have id, this useless because I can't add in page links.

I don't need to publish it as plugin (need this for my project), but it can be used as example if this is possible to do.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.js#L325 add named rule to override default renderer.

`heading_open` - https://github.com/markdown-it/markdown-it/blob/master/lib/rules_block/heading.js#L42.
