### ISSUE TITLE
linkify is conflicting with typographer

### ISSUE THREAD

**Issue by Leonya** [markdown-it/markdown-it#66]
Try "http://somelink.com/(c)" or "http://somelink.com/..." with both linkify and typographer enabled. The resulting link would then include typographic enhancements which breaks it, obviously.

Version 3.1.0

**Comment by Leonya** [comment]
It's not fixed:

```
http://www.hostname.com/123...123/
```

is converted to

```
<p><a href="http://www.hostname.com/123">http://www.hostname.com/123</a>…123/</p>
```

**Comment by puzrin** [comment]
Your report was about typorgapher, that it replaced data in href. It's fixed, because typografer do not breaks href anymore. New example is about `likify-it`, and not related to this package at all.

**Comment by Leonya** [comment]
Now both the href and the text are wrong - "...123" should have been part of the href.

**Comment by puzrin** [comment]
May be. But that's another issue, not related to this one anyhow. Linkifier has it's own tracker. In markdown you can always use autolink `<anything>` to force url.

**Comment by Leonya** [comment]
Reported to the correct tracker. Always a pleasure dealing with you.
