### ISSUE TITLE
how can I add non-symatric token

### ISSUE THREAD

**Issue by neouyghur** [markdown-it/markdown-it#662]
Hi, I am trying to add a new token, which is like that `(*aaa*)=>AAA`.  I checked many plugins where others use tokens composed of the same character tokens. How can I add this type of token?

**Comment by neouyghur** [comment]
Hi, after reading lots of issues and source code. I have figured it out. My code is like this:
```
var converter = require('./converter');

module.exports = function uyghurArabicScript_plugin(md) {
  md.core.ruler.after('normalize', 'UyghurArabicScript', (state) => {
    function replacer(match) {
        return match=converter.convert(match.slice(2, match.length-2), 'ULA', 'UAA');
      }

    var regex = /(\(\*)([^\?]+?)(\*\))/gm;
    state.src = state.src.replace(regex, replacer);
  });
};
```

The converter will update the matched script. 

I am quite new to the javascript world. However, I am working on a plugin that will convert markdown notes written with Latin characters to HTML with Uyghur Arabic Script. 

Hope someone can give some suggestion on my implementation. Thanks.

**Comment by puzrin** [comment]
[1](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/entity.js), [2](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/html_inline.js) there are single-token rules. Just use any as base and replace matcher with your one. Then add renderer for your custom token if needed.
