### ISSUE TITLE
is their any option to convert TOKENs into MD format?

### ISSUE THREAD

**Issue by ayanb1991** [markdown-it/markdown-it#663]
I have a kind of requirement where the TOKENs needed to be converted back into MD format. I was wondering if there is any option to achieve it. If Markdown-it does not have that kind of solution for now, it will be great if you can give me a direction to achieve the same.

**Comment by puzrin** [comment]
No ideas, sorry. That's out of his package scope.

**Comment by rayfoss** [comment]
@ayanb1991 What did you end up doing? I'm in the same boat. I've used custom rules to modify tokens and I'd like to reverse the process and get markdown with the modified attributes.

I'm thinking of making a md renderer... I think that was mentioned in passing in the dev docs.

**Comment by ayanb1991** [comment]
Yup! I thought about making a custom renderer using tokens and custom rules. But it seems like I needed some knowledge for compiler design. So I stalled the idea till now. I am mostly in the same line with you. @rayfoss
