### ISSUE TITLE
How to add elements to symbols

### ISSUE THREAD

**Issue by Mr-Tenglin** [markdown-it/markdown-it#664]
If there is a [danger] tag after the> symbol, how to change the conversion output < blockquote class = "danger" > < / blockquote>
`>[danger] markdown-it` = `<blockquote class="danger">markdown-it</blockquote>`

**Comment by puzrin** [comment]
You can replace existing blockquoterule, adding your tag matcher instead of simple `>`. And add `class` atr to token when tag exists.

**Comment by Mr-Tenglin** [comment]
hello, may I ask the few lines in the `markdown-it.js` file, I did not find it, it is best to give the code.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/rules_block/blockquote.js#L37

Please, try to avoid basic programming questions in tracker.
