### ISSUE TITLE
Replace blank lines with line break <br />

### ISSUE THREAD

**Issue by slinto** [markdown-it/markdown-it#668]
Hi,

is it possible to replace blank lines eg:

```
text
text

text

* item 1
* item 2

test
```

with <br/> html tags?
```
<p>text</p>
<p>text</p>
<br/>
<p>text</p>
....
```

Thank you.

**Comment by puzrin** [comment]
The only available option is `breaks: false`,inside paragraphs. Other things are out of CommonMark spec.
