### ISSUE TITLE
Consider explicitly documenting the fact that commonmark allows HTML

### ISSUE THREAD

**Issue by vpzomtrrfrt** [markdown-it/markdown-it#669]
Just got bit by this. Using the "commonmark" preset enables raw HTML tags, which seems to be technically correct, but unsafe. Could there be a warning somewhere about this behaviour?

**Comment by puzrin** [comment]
Commonmark preset is for compatibility only, expected to be used only by people who understand what they do. I don't see reasons to duplicate anything about spec.

But you can suggest PR if you wish (although i can not guarantee merge)
