### ISSUE TITLE
How do I stop linkify from parsing anything ending with .info as a link?

### ISSUE THREAD

**Issue by Turbotailz** [markdown-it/markdown-it#674]
I have some pieces of text that end with `.info` and they are being parsed as links when they aren't actually links. I need `linkify` for other parts of the app but just want to be able to stop it from parsing these .info strings of text. Is that possible to do?

Screenshot for example, green lines are the "links":

![image](https://user-images.githubusercontent.com/10846855/82445430-214ce880-9ae8-11ea-8a02-24fad8fcf0cf.png)

**Comment by puzrin** [comment]
Disable fuzzy option back, it's too fragile and off by default. Or use separate-configured markdown instances for different kinds of blocks.
