### ISSUE TITLE
Is there an easy way to determine if a list if tight or loose

### ISSUE THREAD

**Issue by jeromesimeon** [markdown-it/markdown-it#678]
I'm working on building an AST from the token stream returned by the markdown-it parser. Everything has been very smooth, but I couldn't find an easy way to determine from the tokens whether a list is tight or loose.

(For comparison, the commonmark.js AST provides that information on the list nodes).

Did I miss it or is it not available? Is there anyway to identify that information from the result of parsing at all?

Thanks!

**Comment by puzrin** [comment]
See tokens https://markdown-it.github.io/#md3=%7B%22source%22%3A%22-%20tight%5Cn%5Cnloose%5Cn%5Cn-%20foo%5Cn%5Cn-%20bar%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22debug%22%7D%7D.

You can check in `li` if `p` has property `hidden` true or false.

**Comment by jeromesimeon** [comment]
> See tokens https://markdown-it.github.io/#md3=%7B%22source%22%3A%22-%20tight%5Cn%5Cnloose%5Cn%5Cn-%20foo%5Cn%5Cn-%20bar%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22debug%22%7D%7D.
> 
> You can check in `li` if `p` has property `hidden` true or false.

Thanks @puzrin.

I'm unclear how that relates to the question (although possibly the rendering in HTML is identical?).

For instance:
```
- > quote1
- > quote2
```

is a `tight` list according to the commonmark spec (and commonmark.js AST):
https://spec.commonmark.org/dingus/?text=-%20%3E%20quote1%0A-%20%3E%20quote2

but the `p` property is false in all `markdown-it` tokens:
https://markdown-it.github.io/#md3=%7B%22source%22%3A%22-%20%3E%20quote1%5Cn-%20%3E%20quote2%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22debug%22%7D%7D

**Comment by puzrin** [comment]
Probably i misunderstand your question. AFAIK, the only difference between tight/loose lists is dropping `<p>` tag for one-liner content. I told you how to check with tokens if `<p>` should be dropped or not - via "hidden" property. May be now ideal, but there are no more differences in data. Direct attr on list parent is not available.

If you need something different - could you reword?

**Comment by jeromesimeon** [comment]
> Probably i misunderstand your question. AFAIK, the only difference between tight/loose lists is dropping `<p>` tag for one-liner content. I told you how to check with tokens if `<p>` should be dropped or not - via "hidden" property. May be now ideal, but there are no more differences in data. Direct attr on list parent is not available.
> 
> If you need something different - could you reword?

Thanks for the follow up. Sorry if my question wasn't so well formulated. I'm still wrapping my head around this distinction between tight and loose lists in commonmark. But reading the spec:

https://spec.commonmark.org/0.29/#lists
> A list is loose if any of its constituent list items are separated by blank lines, or if any of its constituent list items directly contain two block-level elements with a blank line between them. Otherwise a list is tight. (The difference in HTML output is that paragraphs in a loose list are wrapped in <p> tags, while paragraphs in a tight list are not.)

It seems to me that the distinction is not simply about one-liner content.

For the example I gave above:
```
- > quote1
- > quote2
```
The commonmark AST gives you a `tight="true"` attribute 
```
<document xmlns="http://commonmark.org/xml/1.0">
  <list type="bullet" tight="true">
    <item>
      <block_quote>
        <paragraph>
          <text>quote1</text>
        </paragraph>
      </block_quote>
    </item>
    <item>
      <block_quote>
        <paragraph>
          <text>quote2</text>
        </paragraph>
      </block_quote>
    </item>
  </list>
</document>
```

While the following example:
```
- > quote1

- > quote2
```

Result in an AST with `tight="false"`
```
<document xmlns="http://commonmark.org/xml/1.0">
  <list type="bullet" tight="false">
    <item>
      <block_quote>
        <paragraph>
          <text>quote1</text>
        </paragraph>
      </block_quote>
    </item>
    <item>
      <block_quote>
        <paragraph>
          <text>quote2</text>
        </paragraph>
      </block_quote>
    </item>
  </list>
</document>
```

The application could then decide to render those differently (or distinguish when transforming to another format).

As far as I can tell, the token stream is identical in those two examples, so I was looking for a way to recover that tight/loose distinction in some way.

**Comment by puzrin** [comment]
You can do more deep abalyzis, if you wish, but that's a bit out of this project scope. Difference in data was described in first answer - fake paragraph tokens.

**Comment by jeromesimeon** [comment]
> You can do more deep abalyzis, if you wish, but that's a bit out of this project scope. Difference in data was described in first answer - fake paragraph tokens.

That won't work if the token stream is identical in both cases, but understanding if you consider this out of scope.

Summary for anyone else bumping into this:
- `markdown-it` does not expose information about `tight` v `loose` lists in parse tokens
- this distinction can sometimes be inferred from the `hidden` attribute in tokens within the list, but not always (see above examples)
- this is out of scope for the project

**Comment by puzrin** [comment]
Note, reference parser does NOT provides AST. Because columns info missed in tokens. It provides tree-like data. That's not enough for exact reverse transform.
