### ISSUE TITLE
Does markdown-it have not support parsing md tags with spaces using method parseInline?

### ISSUE THREAD

**Issue by justwink** [markdown-it/markdown-it#679]
Does markdown-it have not support parsing md tags with spaces using method parseInline?

like:  **THISISASTRONGTAG  ** 
This STRONG label can not be recognized because there is a space after it.

**Comment by puzrin** [comment]
I guess no. Markdown-it works according to CommonMark spec. Please read it and try  commonmark forum for any questions about formatting.
