### ISSUE TITLE
line and character positions for syntax highlighting...

### ISSUE THREAD

**Issue by digitalmoksha** [markdown-it/markdown-it#68]
I need to perform syntax highlighting of the markdown source. It would be very helpful to have the character positions in the token stream (you already have the lines in there).

I know it's probably possible to generate those numbers by re-traversing the entire token stream.  However, since you're already building the stream (and the line numbers), it seems like it would be best to have it done at that level (even if it had to be turned on with an option).

Then, given a range of the source that needs highlighting, I should be able to quickly get the various tokens and proper character ranges easily.

Is this something you've considered adding (I think they are already doing it in the reference implementations of CM).

Cheers,
Brett

**Comment by puzrin** [comment]
Exact positioning was declined at planning phases as too expensive in implementation. AFAIK ref parser also does not provide it.

**Comment by digitalmoksha** [comment]
No problem.  However, both the Javascript reference implementation (for example line 688 in lib/blocks.js) and the C reference implementation (for example line 55 in src/node.h) - both support it at the parsing stage.  The renderers are then able to use the information if they wish.  And both of those are pretty fast.

Anyway, prefer the expandability your markdown-it, so was hoping this would get implemented...

**Comment by puzrin** [comment]
Look at the CM dingus AST tab. Columns mapping exists only for block nodes, not for inlines. That's the same as "useless" :)

**Comment by digitalmoksha** [comment]
yep you're right, inlines are not implemented...

**Comment by sbruchmann** [comment]
@digitalmoksha FYI: There’s [mdast](https://github.com/wooorm/mdast) by @wooorm, which has positional information about the nodes in the abstract syntax tree. You also might want to check out [mdast-range](https://github.com/wooorm/mdast-range).

**Comment by wooorm** [comment]
Thanks for the shout-out @sbruchmann. @digitalmoksha, mdast’s focus is especially on the AST, and not so much on rendering to HTML, so I think it might just be what you want if you’re going to highlight markdown. Let me know if you have questions (raise an issue on mdast, or e-mail me).

**Comment by puzrin** [comment]
@woorm it's really cool that someone decided to move markdown forward with new features!

Does you parser allow plugins on syntax parse level or on ast only?

**Comment by wooorm** [comment]
@puzrin First of all, sorry to start advertising my parser on your page, hope you don’t mind :)

Of course, there are like a million markdown parsers, but what I was missing was some tool which did not focus on compiling to HTML, rather, focus on the markdown itself: I see markdown used more and more “raw”, without the need to compile to HTML or other formats.

To answer your question, it does, but it isn’t documented very well. [mdast-github](https://github.com/wooorm/mdast-github) is an example, which parses text tokens, when not in links, into more text and links like @mention’s, SHA references, &c.

I started mdast based off of marked, so it’s still depending on regular expressions, unlike markdown-it. I’d like to change it, but it’s a big step to take so maybe somewhere in the far future 😄

mdast plugin’s have two phases: first, they receive the mdast instance and options, so they can modify the parser and stringifier. Second, they receive the parsed document, as an abstract syntax tree, and a virtual file format (useful for plug-ins which modify the format, such as outputting HTML, so they can decide to change the extension to `.html`). I guess that that’s mdast in one paragraph 👌!

**Comment by puzrin** [comment]
@wooorm no need to excuse. I know how difficult is to create markdown parser, when 100% commonmark compatibility required. You did a great work, and your experience with sourcemap generation is useful for me too.

Under syntax plugin i meaned plugins for tokenizer process (not ast transforms). Because some extensions should work BEFORE tokens were created for 100% correct result. For example https://github.com/markdown-it/markdown-it-container

**Comment by digitalmoksha** [comment]
@sbruchmann  @wooorm  oh cool, this may be exactly what I need. I don't have time right now but will try to check it out this week, and let you know if I have any questions.

**Comment by wooorm** [comment]
@puzrin, it was lots of work but it really enables some powerful things: I’m almost done with `mdast-lint` which enables powerful style violation detection. Let me know if you need help!

Re hooking into the parser, we’re talking about the same thing I think! I could’ve implemented mdast-github through AST transformations too, but chose for hooking into the parser (which is faster).
I haven't created the container syntax plug-in yet, but it seems really useful.

@digitalmoksha Alright, no rush, interested in your questions!
