### ISSUE TITLE
Two formattings inside word cause wrong output

### ISSUE THREAD

**Issue by mwasilewski** [markdown-it/markdown-it#680]
In case of applying two formattings inside word output is wrong.
 
eg.
```
ab*~~cd~~*ef
```
 
[permalink to example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22test%2A~~test~~%2Atest%5Cn%5Cntest%20%2A~~test~~%2A%20test%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

**Comment by puzrin** [comment]
Not sure if this can be fixed fast, but at first glance really may be error.

**Comment by rlidwka** [comment]
This is intended, add spaces like this: `ab *~~cd~~* ef` if you want two formattings.

Reason is: as per spec, `*` cannot open a tag if it is preceded by a letter (`b`) and succeeded by a punctuation (`~`).

Commonmark standard (the one we follow) doesn't define strikethrough, but if you replace it with `__`, you get similar results:

https://spec.commonmark.org/dingus/?text=ab*__cd__*ef%0A
