### ISSUE TITLE
How to disable code inline?  (or how to only enable bullet and numbered list?)

### ISSUE THREAD

**Issue by kopax** [markdown-it/markdown-it#681]
Hi and thanks for sharing. This is by far the most stable react-native + react-native-web markdown processor available. 

For my use case, I am using `disable`:

```js
const disable = [
    'strikethrough',
    'emphasis',
    'link',
    'image',
    'autolink',
    'html_inline',
    'entity',
    'smartquotes',
    'blockquote',
//    'inline',
    'reference',
    'heading',
    'lheading',
    'html_block',
    'table',
    'code',
    'fence',
    'hr',
  ]
```

-I only want to have bullet list and numbered list , I feel this is quite long, how can I improve it?
- Also, I didn't find any way to disable inline code, if I enable the commented line, then all the text disappear, how can I disable the inline code?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it#init-with-presets-and-options

You could start with `zero` preset and enable what you need.

**Comment by rodbs** [comment]
@kopax  Could you explain how you integrate `markdown-it` into react-native and react-native-web? If you could share any code I'd highly appreciate it! Thx
