### ISSUE TITLE
Q: Is plugin already loaded 

### ISSUE THREAD

**Issue by goessner** [markdown-it/markdown-it#683]
Is it possible per API to query a `markdown-it` instance, if a certain plugin is already loaded ?

This is important for VSCode markdown extension developing, when two separate extensions use the same  `markdown-it` plugin.

thanks

**Comment by puzrin** [comment]
You could override `.use()` to track what you wish. But there are no official description of what plugin is, and no guarantees. I'd recommend to use different instances for different things. That's how this package is expected to be used.
