### ISSUE TITLE
Disable the parsing between certain delimiters (regex matchings)?

### ISSUE THREAD

**Issue by kpym** [markdown-it/markdown-it#685]
In the situation where another parser is going to process the code produced by `markdown-it` is it possible to disable parsing between certain delimiters?

For example: 
- If you use `mustache.js` or `vue.js` you should have `[click here]({{editanswer}})` translated to `<a href="{{editanswer}}">click here</a>` and not to the actual `<a href="%7B%7Beditanswer%7D%7D">click here</a>` _(this is just one example)_. So disabling parsing between `{{...}}` can be useful.
- If we use `mathjax.js` it will be useful not to interpret what lies between `\(...\)`, `\[...\]` or `$$...$$`.

Maybe having a list of regex rules that disable `markdown-it` for the matching parts would be helpful?

**So my question is: do such configurable rules to disable the parsing already exist?**

**Comment by puzrin** [comment]
- I doubt this task has possible generalized solution at all (without syntax conflicts).
- If you look inside, we avoid regex for performance reasons.
- For perf reasons, in inline mode we quick-skip (as plain text) all chars except limited set https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/text.js (delimiters should start with those chars).

According to your description, i'd suggest to use [fence](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_block/fence.js) and [backticks](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/backticks.js) as base for our own. Regex are ok for your local solution, but not ok for "officially maintained".

**Comment by kpym** [comment]
Thanks for your answer @puzrin.  Sorry but i'm not familiar with the `markdown-it` code and do not understand what should I do concretely to disable parser between delimiters ?

The regex rules were just a suggestion, but I understand that this is not a good solution. Anyway another general solution (fast and without regex) is probably possible for disable parsing between delimiters ?

**Comment by puzrin** [comment]
> what should I do concretely to disable parser between delimiters ?

1. https://github.com/markdown-it/markdown-it/tree/master/docs - start with reading recommendations for developpers.
2. You need 2 completely different rules - for block markup & for inline markup. Use code of `fence` and `backtick` to create custom plugin. They behave similar to what you described. If you replace there delimider conditions & renderer function - you will get what your need.

> Anyway another general solution (fast and without regex) is probably possible for disable parsing between delimiters ?

- From spec's point of view - not possible due high probability of syntax conflicts.
- Technically - possible, if you know what you do.

**Comment by kpym** [comment]
Thanks @puzrin for your answer. I'll check the suggested links.
