### ISSUE TITLE
Smartquotes with standard <q> tag

### ISSUE THREAD

**Issue by kpym** [markdown-it/markdown-it#686]
> Double + single quotes replacement pairs, when typographer enabled,
> and smartquotes on. Could be either a String or an Array.
> 
> For example, you can use '«»„“' for Russian, '„“‚‘' for German,
> and ['«\xA0', '\xA0»', '‹\xA0', '\xA0›'] for French (including nbsp). 

Can we have option to replace quotes by the standard html tag `<q>`.
For example something like:
```js
quotes: '<q>'
```

The advantage is that in this way the quotations are displayed regarding the corresponding `lang` attributes or guessed by the browser. And configuration through `css` is also possible.

And a more sophisticated parameterization could be:
```js
quotes: '<q[lang=fr]>'
```
Which should translate `"test"` to `<q lang="fr">test</q>`.

**Comment by puzrin** [comment]
There are 2 problems:

- Current quotes matcher is simplified (does not analyse language).
- Cheating with html markup can introduce security problems.

So, answer is: embedded smartquoter is trade-off between features, simplicity, safety and size for browser. If you need more - you should replace it with custom one.

**Comment by kpym** [comment]
Sorry, I think I was not clear. What I meant was that you don't need to worry about the language because the browser does it for you.

In the meantime I realized that what I was asking for was already possible with a slightly longer syntax : 
```js
quotes: [ '<q>','</q>','<q>','</q>']
```
or even : 
```js
quotes: [ '<q lang="fr">','</q>','<q lang="fr">','</q>']
```
Thanks for your consideration.

**Comment by puzrin** [comment]
If you do direct replace to `<q>`, those will be escaped in output. Current beautifier works at text level.

**Comment by kpym** [comment]
> those will be escaped in output

If HTML tags are not enabled, I suppose.

**Comment by puzrin** [comment]
I feel you need to read dev docs & inspect sources a bit, because real code works not as imaginated one in your head :). This package is easy for direct use, but things are not so simple if you need advanced modifications.

"html tags" feature is not related to discussed one anyhow.

**Comment by kpym** [comment]
I see, `&lt;q&gt;` will be used in place of `<q>`... this is a bad news for me. Thanks for answering my questions.
