### ISSUE TITLE
show link of page that dosen't exist with red color

### ISSUE THREAD

**Issue by ahmadhamzavi** [markdown-it/markdown-it#687]
how to change color of link to Red when the page (internal link) doesn't exist.

[this iamge](https://i.stack.imgur.com/2wyFm.png)
[StackOverflow](https://stackoverflow.com/questions/62485250/show-page-dosent-exist-by-markdown-it-js)

**Comment by puzrin** [comment]
This question is no related to this package. I does not check links, only render markdown.
