### ISSUE TITLE
How to add a custom class to images rendered?

### ISSUE THREAD

**Issue by dessalines** [markdown-it/markdown-it#688]
Is there any way to add a custom class to all of the images rendered? Related to #536

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer approaches are described in dev docs. Please read those first.

**Comment by dessalines** [comment]
Turns out you can just do stuff like

```
.md-div img {
  max-height: 90vh;
  max-width: 100%;
  height: auto;
}
```
