### ISSUE TITLE
Table layout could be disrupted.

### ISSUE THREAD

**Issue by ataihei** [markdown-it/markdown-it#689]
When using table syntax, if you use even one `` ` `` after surrounding a `` ` `` with a ``` `` ```, the table layout may be corrupted.

Example:
```markdown
|a|b|
|--|--|
|`` ` ``| `c` |
|`` ` ``| `d |
| `e` | `` ` `` |
|`` ` ``| f |
```
Result:
![image](https://user-images.githubusercontent.com/10428970/87619130-68590200-c756-11ea-81b7-2abcef51de61.png)

Thank you for your response.

**Comment by rlidwka** [comment]
Fixed, should be the same as on github now.
