### ISSUE TITLE
markup field in token stream seems incorrect for em_close and strong_close...

### ISSUE THREAD

**Issue by digitalmoksha** [markdown-it/markdown-it#69]
If I put `this is **a** paragraph.` in the demo, the markup field shows `*` for the `strong_close` token, while the `strong_open` token has `**` for the markup field.  I think they should both show `**`

There is a similar issue with the `em_close` token using this sample text `this is _a_ paragraph.`:  the `em_close` markup field shows `__`, while the `em_open` correctly shows `_`

I noticed this issue while parsing through the token stream returned from `parse`

Using 4.0.1

**Comment by puzrin** [comment]
If it's not urgent, i will do release later.

**Comment by digitalmoksha** [comment]
No problem.  Thank you for fixing it...
