### ISSUE TITLE
Writing Plugin that hooks into MarkdownIt().parse(markdown)

### ISSUE THREAD

**Issue by bharney0** [markdown-it/markdown-it#691]
First, thank you for building such an excellent library. Markdown-it has helped in so many wonderful ways with parsing markdown. My question is regarding markdown-it's [parse function](https://github.com/markdown-it/markdown-it/blob/5789a3fe9693aa3ef6aa882b0f57e0ea61efafc0/lib/index.js#L516). I have used [markdown-it-container plugin](https://github.com/markdown-it/markdown-it-container#readme) which helps tremendously with rendering custom html when using 
```
var md = require('markdown-it')()
            .use(require('markdown-it-container'), name [, options]);
md.render(markdown);
```
and being able to hook into the `validate` and `render` methods. But my recent requirement has been to hook into the parse function. We would like to be able to write a custom plugin that updates properties in the AST. Do you have guidance for writing a function similar to container_plugin that expose hooks like [render](https://github.com/markdown-it/markdown-it/blob/5789a3fe9693aa3ef6aa882b0f57e0ea61efafc0/lib/index.js#L540). But for the parse function? It looks like I can still use the container_plugin to add to types to the AST, but is it possible to edit the Object properties like content and attrs?

The code we are using does not use the render method, but instead uses parse.
```
const md = new MarkdownIt()
             .use(require('markdown-it-container'), 'image', options);
const tokenStream = md.parse(markdown,{});
```
I've looked online, but I only found 1 issue about plugins for the parse function [here](https://github.com/markdown-it/markdown-it/issues/426).

**Comment by puzrin** [comment]
I don't understand your question:

1. If you need to override `.parse()` - that's basic JS programming, not specific for this package.
2. If you need to modify data,  "after" `.parse()` - you could sit on [`core`](https://github.com/markdown-it/markdown-it/blob/master/lib/parser_core.js#L13-L20) chain.

Could you clarify what are you asking about?

**Comment by bharney0** [comment]
My question is regarding updating the AST properties like content and attrs. From my experience, I havent been able to update those properties using the container plugin. But I will try overriding parse, or modify the data after parse using core. Thank you for the advice.
