### ISSUE TITLE
href missing on h1, h2, h3, h4, h5 elements

### ISSUE THREAD

**Issue by oze4** [markdown-it/markdown-it#692]
How to add href to h1-h5 like GitHub does within README files?

I tried enabling `linkify`, etc..

```javascript
const md = new MarkdownIt({
  html: true,
  linkify: true,
  typographer: true,
});
```

**Comment by puzrin** [comment]
https://github.com/npm/marky-markdown - see how it's done here. Also please, read dev docs prior to ask programming questions.

**Comment by oze4** [comment]
@puzrin thanks! I'll check that out. Unfortunately, I spent about 20 minutes searching the docs - even searched issues on this repo before asking this question.. (searched explicitly for 'href' even, as searching for 'link' was not giving me proper results)

Unfortunately, nothing showed up in my searches or manually browsing docs/issues/readme.. Perhaps, it should stand out more in the readme at least?

**Comment by puzrin** [comment]
Statement about missed hrefs looks like asking wrong questions in wrong place. This is extendable commonmark parser. All extra features are added via third-party plugins. You need to search suitable plugin (it can exist with high probability) or write your own. If you have concrete proposals about readme - you can create PR with your suggestions.
