### ISSUE TITLE
Shrug emoticon removing backslash ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by dalipkumar703** [markdown-it/markdown-it#693]
markdown-it removing backslash. 
![image](https://user-images.githubusercontent.com/11908216/88515085-c0222380-d008-11ea-8438-3e72a6274acc.png)

It work with double backslash.

**Comment by puzrin** [comment]
Works according to spec. Please read before create issues.

**Comment by dalipkumar703** [comment]
@puzrin Do you know reason for escaping backslash in case of backslash with ascii? But not with character.

**Comment by puzrin** [comment]
No idea. We stay aside from any questions about spec. Commonmark forum is more appropriate place for such kind of questions.
