### ISSUE TITLE
CommonMark blockquote example 221 fails

### ISSUE THREAD

**Issue by zq1997** [markdown-it/markdown-it#696]
According to [`commonmark spec`](https://spec.commonmark.org/0.29/#example-220)

> It is a consequence of the Laziness rule that any number of initial >s may be omitted on a continuation line of a nested block quote:

```
>>> foo
> bar
>>> baz
```

should be render to (By [spec.commonmark.org](https://spec.commonmark.org/dingus/?text=%3E%3E%3E%20foo%0A%3E%20bar%0A%3E%3E%3E%20baz) and github comment system)
```html
<blockquote>
<blockquote>
<blockquote>
<p>foo
bar
baz</p>
</blockquote>
</blockquote>
</blockquote>
```

but current implemention gives:
```html
<blockquote>
<blockquote>
<blockquote>
<p>foo
bar</p>
</blockquote>
<blockquote>
<p>baz</p>
</blockquote>
</blockquote>
</blockquote>
```

**Comment by puzrin** [comment]
Thank you for report. We test CM spec automatically. Need to check why this sample was missed.

**Comment by ocavue** [comment]
The example in the origin issue is not the example 221 in CM.

The [example 221](https://spec.commonmark.org/0.29/#example-221) is:

```
>>> foo
> bar
>>baz
```

Notice that there is not space before `baz`. `markdown-it` works fine with example 221.

**Comment by zq1997** [comment]
Yeah, example 221 use two `>`, but I test it with three, that's why autotest didn't report this issue.

**Comment by rlidwka** [comment]
Fixed, thanks for reporting.
