### ISSUE TITLE
Improve linkify-it pretest range when breaks are enabled

### ISSUE THREAD

**Issue by fabiospampinato** [markdown-it/markdown-it#699]
Given the following sample Markdown string:

```markdown
https://github.io
https://a.b
https://a.com
```

`linkify-it`'s `pretest` function is being passed the entire string in any case.

I think it would be better to split the passed string by newlines and call `pretest` with each line, that way a more granular pretesting logic could be implemented. 

Essentially I'm arguing for this change for the same reason `pretest` don't receive the entire string all the time but each inline block.

**Comment by puzrin** [comment]
Any proposal should have clear added value. What is added value of this proposal?

**Comment by fabiospampinato** [comment]
> Any proposal should have clear added value. What is added value of this proposal?

👇 

> Essentially I'm arguing for this change for the same reason pretest don't receive the entire string all the time but each inline block.

Basically by chunking the input string more granularly less computation can be performed by letting `pretest` potentially discard a higher percentage of it. I mean it's the same principle behind not passing the entire thing to `pretest`.

**Comment by puzrin** [comment]
Please, understand me right, from my experience, talks about performance without benchmarks are waste of time. I can't participate in changes "just or fun". Let's return to this proposal when arguments become more prepared.

**Comment by fabiospampinato** [comment]
Sure, I understand.

What kind of dataset would you like me to potentially benchmark this against? And what kind of performance numbers would you need to see to be convinced to implement this?

**Comment by puzrin** [comment]
I can not answer about dataset without been involved. Building benchmarks "close to real world" is a separate state of art.

---

About perf gain. My personal opinion:

- 5x..10x total (not local) gain - reasonable minimum to discuss seriously.
- < 2x gain - usually not worth to discuss at all.

But that's only my personal opinion, because i have another projects and can't polish each endless without significant reasons.

So, keep in mind, i think everything in this place is "good as is". Probability to convince me do that instead of another projects is about zero. But i can be convinced to accept PR at least (default policy for stable projects is "reject everything"). That's not specific for your proposal. There are still too much of things to do https://hackaday.io/projects/hacker/440909 :)

**Comment by fabiospampinato** [comment]
> Building benchmarks "close to real world" is a separate state of art.

Yeah that's why I was asking, because maybe I could come up with a fictional benchmark where this suggested optimization performs really well, but then you may rightfully say that the benchmark isn't really relevant to how humans usually write Markdown.

> 5x..10x total (not local) gain - reasonable minimum to discuss seriously.

I feel almost certain in saying that a 10x speedup on average in general without any form of caching is impossible to achieve, maybe the same is true for a 5x speedup too.

In some circumstances this kind of improvement could be achieved though, for example when editing a Markdown with the editor on one side and the rendered thing on the other side, like in markdown-it.github.io, re-rendering the entire thing naively is at least 10x slower than what it could be by partially compiling it, but that's tricky to do as some times if one block changes other blocks should be re-rendered too, hacking this on top of markdown-it in a way that works perfectly might not be really doable. Is this the kind of optimization you might be interested in?

**Comment by puzrin** [comment]
Problem become real when someone reported, until that happened, it's "imaginated problem" :). Solving imaginaed problem about performance is "premature optimisation".

Personally, that still looks as changes "just for fun" in my eyes.

**Comment by fabiospampinato** [comment]
Well, let me report the issue with more details then.

I'm using markdown-it in a note-taking [app](https://github.com/notable/notable) where I need to debounce re-renders otherwise the app would feel janky while editing regularly-sized notes. 

Debouncing re-renders still makes renders feel janky as a consequence, plus even just debouncing on its own as a workaround for this issue is problematic because picking the perfect debounce delay that gives the best user experience is impossible (would the user type something else right when a render starts? how long will the _next_ render take? etc.)

When editing very large notes without any further optimizations the app would just become unusable. Currently for very large notes I'm implementing a poor man's version of what I'm proposing here, I'm basically only tokenizing the document and then rendering dynamically only the block tokens that would actually be visible in the app to HTML, that showed at least a 10x improvement right there, without partially tokenizing the document too.

All this happens in my above-average laptop, I don't have a build of the app for smartphones yet but I'd imagine the average smartphone may be at least 5x~10x slower than my machine, making the problem much worse.

I could put the Markdown compilation in another process to kind of decouple its performance from the editing part of the app, but at the end of the day if everything has to be rendered from scratch each time the app just can't update the rendered document fast enough to provide a great user experience, or even a decent one for very large documents.

I understand that there might be a lot of work involved with implementing this in markdown-it perfectly, and there just aren't enough man-hours available to get this done, but are you at least more convinced now that maybe this matters?

**Comment by puzrin** [comment]
I can't understand how this can be related to current issue about linkifier. Talks about performance without benchmarks can be endless. I'd suggest create benchmark, to continue with something more concrete.

**Comment by fabiospampinato** [comment]
It isn't related to the current issue, but since you continued the discussion on my previous post I just continued it here too. 

I can open a separate issue about this, with some actual numbers and a way to reproduce my findings, but do you want me to do that or would I be wasting my time? I think actually there was an issue about this already, [here](https://github.com/markdown-it/markdown-it/issues/258), which got closed for some reason.

**Comment by puzrin** [comment]
1. No, all my posting were in scope of initial issue context.
2. If similar issue already exists, it's better to avoid duplication, and continue previous.

**Comment by fabiospampinato** [comment]
> No, all my posting were in scope of initial issue context.

My bad then, for the sake of clarity I thought your `Personally, that still looks as changes "just for fun" in my eyes.` was in response to my `Is this the kind of optimization you might be interested in?` which came right after suggesting implementing partial compilation and was my only question in that post, I think I misunderstood what you were referring to via "it".

> If similar issue already exists, it's better to avoid duplication, and continue previous.

👍
