### ISSUE TITLE
question about the 'markup' field in the token stream...

### ISSUE THREAD

**Issue by digitalmoksha** [markdown-it/markdown-it#70]
I'm a little confused how the `markup` field is supposed to be used in an open and close token.

For example, `em_open.markup` is `_`, and `em_close.markup` is `_` - this makes sense because markup surrounds the text.

But `list_item_open.markup` is `*`, and `list_item_close.markup` is also `*` - but for a list item, there is no closing markup.

I'm trying to use consistent rules to walk the token tree without a bunch of special cases.

Same issue with `bullet_list_open` and `bullet_list_close`, both fill in the markup field.  In fact, I would have assumed that neither markup fields would be filled in (just like for a paragraph) since the markup is encapsulated in the list item.

**Comment by puzrin** [comment]
Markup is not for traverse, and not expected for regular use. You need `.level` property to find matching pairs and `.nesting` to detect token type (paired/single). See src of rules in core chain, how those seek tokens.

**Comment by digitalmoksha** [comment]
In order to calculate position ranges (for use in syntax highlighting), i need to know the markup characters (some are one character, some are two, some are 3, etc) - level and nesting won't give me that information.  If the markup fields are correct, then it makes it easier to do the calculations, without special cases, and (it would seem) without having to know all the different plugins that are installed and account for them.

It would also help make the token stream more "round trip" - you could reconstitute the original markdown text if needed...

**Comment by puzrin** [comment]
Markup field is filled somehow to keep original markup characters, but there are no clear quides and content depends on token type. I can't suggest anything better than see rules sources, to know exact value for each.
