### ISSUE TITLE
How to disable buttons?

### ISSUE THREAD

**Issue by guledali** [markdown-it/markdown-it#702]

**Comment by puzrin** [comment]
This is not related to this package.

**Comment by guledali** [comment]
@puzrin  It's related to that package

For some reason you can disable images but not buttons why

```javascript
const md = MD({ html: true, typographer: true, breaks: true, linkify: true }).disable([
  "image"
]);
```

**Comment by puzrin** [comment]
What BUTTONS are you speaking about? Please provide example via online demo.

**Comment by guledali** [comment]
@puzrin Here is an image 
<img width="1029" alt="Screenshot 2020-08-18 at 10 25 10" src="https://user-images.githubusercontent.com/20647282/90489103-22b89c00-e13d-11ea-9a6b-9c9acda5228e.png">

**Comment by puzrin** [comment]
All enable/disable are about markdown components only. If you enabled raw hml - it's only your responsibility how to sanitize output.
