### ISSUE TITLE
Update Image URL

### ISSUE THREAD

**Issue by Ramon404** [markdown-it/markdown-it#704]
I'm currently pulling my data from Strapi. I get markdown from Strapi, and using markdown-it to render the content. The images in the markdown have a relative URL, how can I update the markdown-it configuration to modify the image URL so that it's an absolute URL and not relative?

**Example:**
Current image URL =  /uploads/test.png
Image URL I want = http://localhost:1337/uploads/test.png

**Comment by puzrin** [comment]
You can override renderer https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer, or update link tokens https://github.com/markdown-it/markdown-it-for-inline. Take a look at dev docs.

**Comment by vladfaust** [comment]
Excuse me, a quick question: is it possible to modify tokens, and then render back to Markdown (not HTML)?

**Comment by rlidwka** [comment]
> Excuse me, a quick question: is it possible to modify tokens, and then render back to Markdown (not HTML)?

Not out of the box in this library.

Look for 3rd party libraries/plugins, there's a good chance that there's a plugin for that.

Or you can try to write a convertor yourself.
