### ISSUE TITLE
Keep track of line maps for "tr_open" tokens inside tbodys

### ISSUE THREAD

**Issue by fabiospampinato** [markdown-it/markdown-it#705]
It looks like "tr_open" tokens have their "map" property populated only if they are inside the "thead" of a table, while "tr_open" tokens inside the "tbody" section of the table don't have their "map" property populated.

It would be useful if all "tr_open" tokens got their "map" properties populated so that scroll synchronization solutions that are built on top of that could reliably map table rows too.

**Comment by fabiospampinato** [comment]
Same for `image` tokens, should I open a separate issue about that?

**Comment by puzrin** [comment]
Mapping [rows, but without columns] is for blocks only (images are inline).

`tr_open` seems possible to extend https://github.com/markdown-it/markdown-it/blob/master/lib/rules_block/table.js#L175 with `token.map = [ nextLine, nextLine + 1 ];`

**Comment by fabiospampinato** [comment]
> Mapping [rows, but without columns] is for blocks only (images are inline).

Right, especially since images can have arbitrary heights it would still be useful to be able to map them back to the source line when more than one image is found within the same paragraph. Otherwise I'd image synchronized scrolling would become somewhat unreliable under those scenarios.

> tr_open seems possible to extend https://github.com/markdown-it/markdown-it/blob/master/lib/rules_block/table.js#L175 with token.map = [ nextLine, nextLine + 1 ];

Yeah that should be trivial. Would you like me to submit a PR for that?

**Comment by puzrin** [comment]
> Otherwise I'd imagine synchronized scrolling would become somewhat unreliable under those scenarios.

Since big images are usually inside separate paragraph, result is good enougth. Anyway, sourcemapping of inlines is different level of complexity and not planned.

> Yeah that should be trivial. Would you like me to submit a PR for that?

As you wish. I hope, we will solve all pending issues at once next week.

**Comment by rlidwka** [comment]
Fixed, looks like these were missed by accident.

**Comment by fabiospampinato** [comment]
@rlidwka Actually line mapping have been added to `td_open` tokens, not `tr_open` tokens, was that intentional? Shouldn't `tr_open` tokens have line mapping provided for too?

**Comment by rlidwka** [comment]
> not `tr_open` tokens, was that intentional

Not intentional, fixed in https://github.com/markdown-it/markdown-it/commit/9fe835bc1267a1c0c82bcca4e30396236e113417.

**Comment by fabiospampinato** [comment]
Awesome, thank you!
