### ISSUE TITLE
Bug recognizing underline-style h1 and h2 when title has list syntax

### ISSUE THREAD

**Issue by wolftune** [markdown-it/markdown-it#708]
These two are two variants of CommonMark that should both give the same result (an h2 with the full "1. Hello" text as the title).

`## 1. Hello`

vs

```
1. Hello
----------
```

However, markdown-it seems to turn the latter into an ordered-list with a horizontal rule after it.

Also, the markdown for horizontal rule is for blank lines both above and below, so the hr shouldn't be generated in this case.

**Comment by puzrin** [comment]
- [markdown-it](https://markdown-it.github.io/#md3=%7B%22source%22%3A%221.%20Hello%5Cn---------%5Cn%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)
- [reference](https://spec.commonmark.org/dingus/?text=1.%20Hello%0A---------)

Result looks he same with reference parser. Please, read description of issue template, it has details about preliminary checks & how to provide examples.
