### ISSUE TITLE
When I use MathJax with markdown ("{" - MathJax is not rendering)

### ISSUE THREAD

**Issue by varunraghu3112** [markdown-it/markdown-it#709]
While I'm using markdown with MathJax script, \Bigg{ it is not rendered as "{" it's showing the same MathJax string, but the other markdowns are rendered properly, any known thing to solve the issue ?

Thanks in advance

**Comment by rlidwka** [comment]
Please show the code that reproduces this issue (both using "other markdowns" that works, and with this implementation that doesn't).

This module wasn't written with mathjax in mind, but I'm curious why it'd behave differently with other implementations if it does.

**Comment by puzrin** [comment]
Will reopen when more info provided, why this is related to this package.
