### ISSUE TITLE
HTML multiline comment with empty lines.

### ISSUE THREAD

**Issue by mauvm** [markdown-it/markdown-it#71]
Empty lines (or a double newline) in a comment does not work as expected:

```markdown
foo <!-- this is a comment

with empty lines

-->
```

becomes

```html
<p>foo &lt;!-- this is a comment</p>
<p>with empty lines</p>
<p>--&gt;</p>
```

While if I remove the empty lines, it works as expected. I couldn't find anything regarding this issue in the CommonMark spec/forum.

**Comment by puzrin** [comment]
Commonmark does not allow blocks with empty lines in inline content. All pending spec-related cases about comments are already collected in #51 .
