### ISSUE TITLE
better plugin documentation

### ISSUE THREAD

**Issue by kaisershahid** [markdown-it/markdown-it#711]
can you put together more examples and explanations of how to write plugins? the existing documentation doesn't provide enough context

**Comment by puzrin** [comment]
Sorry, no time to write advanced docs.

**Comment by binyamin** [comment]
@puzrin The beauty of open-source is that people work on open issues. How will you get contributors if you close issues you can't work on?

**Comment by puzrin** [comment]
I don't like to to keep endless issues in tracker, just because you believe somebody can do it. Sorry, but that's realistic estimate, IMO. Also, this issues has no concrete criteria, when it can be considered as done.

If someone really decides to improve docs - status of issue will not stop him.

**Comment by airtonix** [comment]
@puzrin lol you're charming.
