### ISSUE TITLE
potential bug: `parse` does not fill `env` var, only `render` does

### ISSUE THREAD

**Issue by pke** [markdown-it/markdown-it#716]
Not sure this is correct place to report a potential bug I discovered when using the https://github.com/GerHobbelt/markdown-it-title#usage plugin

It seeems the `env` is only filled out when `render` and not during `parse`?

That works:

```ts
const env = {}
md.render('# Hello, *`world`!(c)*', env)
env.title === 'Hello, world!©'
```

But using `parse` the `env` is not filled:

````ts
const env = {}
md.parse('# Hello, *`world`!(c)*', env)
env.title !== 'Hello, world!©'
```

**Comment by puzrin** [comment]
`env` is filled by parser when there is something to fill with. For example, refereneces data. It's up to plugins how to use it.

You can inspect sources to see how and where env used. I can not comment third party plugins.

**Comment by pke** [comment]
You right it seems the plugin only performs as render plugin.
