### ISSUE TITLE
Running test suite under Windows fails because of line breaks

### ISSUE THREAD

**Issue by c3er** [markdown-it/markdown-it#719]
I just cloned markdown-it under Windows and executed the test suite. It failed because of "wrong" line breaks in all files. The option "autocrlf" in my Git config is set tot true. The error message that comes several hundred times is

```
Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
```

I fixed this locally by removing following line from `.eslintrc.yml`:

```yml
linebreak-style:        2
```

My suggestions:

Remove the above mentioned line from `.eslintrc.yml`.

Or, if you want to enforce Unix line breaks on all development machines, add a `.gitattributes` file with e.g. following content:

```
* text eol=lf
```

**Comment by puzrin** [comment]
Thanks for details.

There is editor config https://github.com/markdown-it/markdown-it/blob/master/.editorconfig, and it was enough for many years. I would not like to add extra configs, if possible.

May be you know many popular js projects, using .gitattribues? I'm open to new things, if those became mainstream.

**Comment by c3er** [comment]
I don't know, how mainstream `.gitattributes` is, but it is supported by Git for ages. The problem with `.editorconfig` and `.eslintrc.yml` is that Git does not care about them at the clone process, while the rules in `.gitattributes` are regarded while cloning.

I use `.gitattributes` mainly for files that are generated and/or manipulated by some tools, e.g. `package.json`.

**Comment by puzrin** [comment]
Please, understand me right, here is stable process, working for many years. Personal opinion of single human is not enough to change it. To move forward, i need not feature description, but usage samples/stats in real projects.

**Comment by c3er** [comment]
Here is a list `.gitattributes` files after a quick search:

- [Angular](https://github.com/angular/angular/blob/master/.gitattributes)
- [Atom](https://github.com/atom/atom/blob/master/.gitattributes)
- [Bootstrap](https://github.com/twbs/bootstrap/blob/main/.gitattributes)
- [Electron React Boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/.gitattributes)
- [Electron](https://github.com/electron/electron/blob/master/.gitattributes)
- [React](https://github.com/facebook/react/blob/master/.gitattributes)
- [VS Code](https://github.com/microsoft/vscode/blob/master/.gitattributes)
- [Webpack](https://github.com/webpack/webpack/blob/master/.gitattributes)

My personal project: [MDView](https://github.com/c3er/mdview/blob/master/.gitattributes)

**Comment by puzrin** [comment]
Thank you for info. Looks reasonable.

Take a look, is it ok now?

**Comment by c3er** [comment]
Tests passed without need for any modification after a fresh clone. I checked some files manually and they have Unix line ending.

Thanks!
