### ISSUE TITLE
Broken image due to URL

### ISSUE THREAD

**Issue by danielgtaylor** [markdown-it/markdown-it#72]
I have a bug report in danielgtaylor/aglio#93 where a user has an image link in the Markdown that used to work with `marked` but now renders out badly with `markdown-it`. Please see the original issue for details.

It seems that the following works:

```md
![Alt text](http://yuml.me/diagram/scruffy/class/[Administrator]-^[Person],%20[Person]-^[Party])
```

Any chance that `markdown-it` can support the original use case without URL-encoding?

**Comment by puzrin** [comment]
[Place url to `< >`](https://markdown-it.github.io/#md64=eyJzb3VyY2UiOiIhW0FsdCB0ZXh0XShodHRwOi8veXVtbC5tZS9kaWFncmFtL3NjcnVmZnkvY2xhc3MvW0FkbWluaXN0cmF0b3JdLV5bUGVyc29uXSwgW1BlcnNvbl0tXltQYXJ0eV0pXG5cbiFbQWx0IHRleHRdKDxodHRwOi8veXVtbC5tZS9kaWFncmFtL3NjcnVmZnkvY2xhc3MvW0FkbWluaXN0cmF0b3JdLV5bUGVyc29uXSwgW1BlcnNvbl0tXltQYXJ0eV0+KSIsImRlZmF1bHRzIjp7Imh0bWwiOmZhbHNlLCJ4aHRtbE91dCI6ZmFsc2UsImJyZWFrcyI6ZmFsc2UsImxhbmdQcmVmaXgiOiJsYW5ndWFnZS0iLCJsaW5raWZ5Ijp0cnVlLCJ0eXBvZ3JhcGhlciI6dHJ1ZSwiX2hpZ2hsaWdodCI6dHJ1ZSwiX3N0cmljdCI6ZmFsc2UsIl92aWV3IjoiaHRtbCJ9fQ==), if you need spaces and other strange chars there. That's described in [commonmark spec](http://spec.commonmark.org/0.18/#link-destination).
