### ISSUE TITLE
normalizeLinkText mangles links containing %25

### ISSUE THREAD

**Issue by sophiebits-humu** [markdown-it/markdown-it#720]
If you normalize a URL that has something that looks like a double-escaped character, normalizeLinkText changes the meaning:

```js
new MarkdownIt().normalizeLinkText('https://www.google.com/search?q=hello%252Fhello');
// https://www.google.com/search?q=hello%2Fhello
```

Note that the input is a Google search for the term `hello%2Fhello`; the second is `hello/hello`, so normalizeLinkText has changed the meaning.

(It's uncommon to do this but it is needed sometimes – what if you did want to search for `hello%2Fhello`?)

Compare this to a similar example with %26:

```js
new MarkdownIt().normalizeLinkText('https://www.google.com/search?q=hello%26hello');
// 'https://www.google.com/search?q=hello%26hello'
```

Here, normalization knows not to convert this to `?q=hello&hello` because `&` has special meaning in a URL. The same treatment that applies to `%26` should apply to `%25` as well because `%` has special meaning in a URL too.

Tested with 11.0.1.

**Comment by puzrin** [comment]
https://markdown-it.github.io/#md3=%7B%22source%22%3A%22https%3A%2F%2Fwww.google.com%2Fsearch%3Fq%3Dhello%25252Fhello%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D

Please, clarify: URL stays correct, but text corruped? Right?

**Comment by sophiebits-humu** [comment]
Correct. (I happened upon this via Atlassian's AtlasKit project's rich text editor, which calls normalizeLinkText directly.)

**Comment by rlidwka** [comment]
Added `%` to exception list, I hope it solves this.

**Comment by sophiebits-humu** [comment]
Thank you.
