### ISSUE TITLE
Tables indented by double tabs do not render properly

### ISSUE THREAD

**Issue by barro350** [markdown-it/markdown-it#721]
Version: Markdown-it v12.0.0

## Description

Consider the following Markdown source: a table inside a nested list. Each line of the table is indented by two consecutive tabs.

```markdown
- Level 1

	- Level 2

		| Column 1 | Column 2 |
		| -------- | -------- |
		| abcdefgh | ijklmnop |
```

## What is expected (Github's implementation)

- Level 1

	- Level 2

		| Column 1 | Column 2 |
		| -------- | -------- |
		| abcdefgh | ijklmnop |

## What actually happens

It seems that the first 4 characters of each line after the tabs (`| Co`, `| ab`) is removed.

[Demonstration of the bug @ https://markdown-it.github.io/](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22-%20Level%201%5Cn%5Cn%5Ct-%20Level%202%5Cn%5Cn%5Ct%5Ct%7C%20Column%201%20%7C%20Column%202%20%7C%5Cn%5Ct%5Ct%7C%20--------%20%7C%20--------%20%7C%5Cn%5Ct%5Ct%7C%20abcdefgh%20%7C%20ijklmnop%20%7C%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

## Discussions

[According to the GFM spec](https://github.github.com/gfm/#tabs), "in contexts where whitespace helps to define block structure, tabs behave as if they were replaced by spaces with a tab stop of 4 characters."

If every tab is replaced with 4 whitespaces, [Markdown-it correctly renders the table](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22-%20Level%201%5Cn%5Cn%5Ct-%20Level%202%5Cn%5Cn%20%20%20%20%20%20%20%20%7C%20Column%201%20%7C%20Column%202%20%7C%5Cn%20%20%20%20%20%20%20%20%7C%20--------%20%7C%20--------%20%7C%5Cn%20%20%20%20%20%20%20%20%7C%20abcdefgh%20%7C%20ijklmnop%20%7C%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D).

**Comment by rlidwka** [comment]
Fixed, thanks for reporting.
