### ISSUE TITLE
Tables with markdown-it-attrs break in v12

### ISSUE THREAD

**Issue by valtlai** [markdown-it/markdown-it#723]
After the rewrite of tables in v12, the `markdown-it-attrs` plugin works incorrectly: see arve0/markdown-it-attrs#113.

I’m not sure if the plugin should be updated or if the refactor introduced a bug in `markdown-it` itself.

<details>
<summary>Sample code</summary>

Input:

```md
| Foo   | Baz   |
| ----- | ----- |
| sin   | cos   |
{.lorem}
```

Current output:

```html
<table>
<thead>
<tr>
<th>Foo</th>
<th>Baz</th>
</tr>
</thead>
<tbody>
<tr>
<td>sin</td>
<td>cos</td>
</tr>
<tr>
<td class="lorem"></td>
<td></td>
</tr>
</tbody>
</table>
```

Expected output:

```html
<table class="lorem">
<thead>
<tr>
<th>Foo</th>
<th>Baz</th>
</tr>
</thead>
<tbody>
<tr>
<td>sin</td>
<td>cos</td>
</tr>
</tbody>
</table>
```
</details>

**Comment by puzrin** [comment]
I think, issue in original repo is enough. Markdown-it has tests and nothing was broken there.
