### ISSUE TITLE
Sequence of pipe characters and newlines interpreted as a table

### ISSUE THREAD

**Issue by fabiospampinato** [markdown-it/markdown-it#724]
As of markdown-it v12.0.1 the following is interpreted as a table ([Permalink](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%7C%5Cn%7C%5Cn%7C%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)):

```markdown
|
|
|
```

It is not interpreted as a table when commonmark-strict is enabled, obviously ([Permalink](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%7C%5Cn%7C%5Cn%7C%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Atrue%2C%22_view%22%3A%22html%22%7D%7D)).

And GitHub itself doesn't interpret that as a table either:

|
|
|

Is this a bug with markdown-it? Or is maybe GitHub not following the latest version of their spec?

**Comment by rlidwka** [comment]
If a table doesn't have any columns in it, is it still a table?..

Yeah definitely a bug. Spec probably doesn't define this case specifically, but the chance of user ever wanting this to be a table seems to be quite slim.

Fixed, thanks for reporting.
