### ISSUE TITLE
How to mutate markdown source during tokenisation

### ISSUE THREAD

**Issue by jackdouglas** [markdown-it/markdown-it#726]
My block plugin is similar to `markdown-it-container`, but it morphs the contents of the container — and I want the new contents to be parsed as if they were the original markdown.

e.g.

```
::: onebox
ae3e83e2fab3a7d8683d8eefabd1e74d
743b5f019d80e012a08dc6b598b18141
:::
```

is transformed to:

````
::: onebox
```
boo
```
```
hoo
```
:::
````

I don't think there is an easy way of doing this, is there? Is my only option to recursively call `render` on the transformed contents and inject the result, or can I safely change `state.src` on the fly?

**Comment by puzrin** [comment]
> Is my only option to recursively call render on the transformed contents and inject the result, or can I safely change state.src on the fly?

I'd suggest to recursively call parse for nested content, and then replace container token with parsed result.
