### ISSUE TITLE
Why are the dom nodes rendered in the list inconsistent

### ISSUE THREAD

**Issue by chenmy0917** [markdown-it/markdown-it#728]
**text 1:**
```
* Merge pull request #1 in ~ZHOUDANDAN10/fe-test-pr from feature/test to master

* commit '95ff3056c162972130a88b4a83b1f10d90d4d505':
 conflict
 de1 r
 dev1;
* tst;
* test;
* conflict
```
**render dom:**
![image](https://user-images.githubusercontent.com/22138217/98533972-b6be7d80-22be-11eb-843f-0bbddc8a30f3.png)

**text 2:**
```
* Merge pull request #1 in ~ZHOUDANDAN10/fe-test-pr from feature/test to master
* commit '95ff3056c162972130a88b4a83b1f10d90d4d505':
 conflict
 de1 r
 dev1;
* tst;
* test;
* conflict
```
**render dom:**
![image](https://user-images.githubusercontent.com/22138217/98534083-ebcad000-22be-11eb-8f6b-53967c292451.png)

**The difference between text 1 and text 2 is a blank line, the effect of rendering on the web page is shown in the figure below:**
![image](https://user-images.githubusercontent.com/22138217/98534321-419f7800-22bf-11eb-90ca-615c09778f7f.png)
![image](https://user-images.githubusercontent.com/22138217/98534283-32b8c580-22bf-11eb-8428-a2d70471a8ec.png)

**Comment by puzrin** [comment]
Please, use online demo to play & read CM spec ("tight list").

Everything works as expected. Empty lines between list items cause wrapping content to paragraph.
