### ISSUE TITLE
feature request: by-character sourcemap

### ISSUE THREAD

**Issue by carljm** [markdown-it/markdown-it#73]
Hi! I'm using Markdown-it on a project where I have an upcoming need for high-fidelity (to the individual character) source-map info. I will likely need to do the work to implement that in Markdown-it regardless; I'm filing this ticket to ask in advance whether that work might be accepted into mainline if I file it as a pull request. Do you have any in-principle objection to tracking by-character sourcemap info?

Thanks!

**Comment by puzrin** [comment]
IMHO, such work will be valuable independing on my agreement or disagreement to accept PR. I don't object against this feature in general, but not sure it's possible to implement without significant speed loss and architecture refactoring. If it will be possible to keep & maintain 2 builds at once (fast + sourcmap) - no problem.

Idea of this project was to get new quality level of markdown parsers - with pluggable "everything" and still with high speed. I'm fine with current result, but if someone wish to continue - i'll be happy to help with everything i can.

**Comment by carljm** [comment]
Ok. I'll update once I see what it looks like in practice, and what the speed impact is.

**Comment by puzrin** [comment]
I predict full rewrite, seriously :) . Current shared DFA design reached it's limit for offsets tracking.

**Comment by puzrin** [comment]
Can i close it?

**Comment by puzrin** [comment]
Closing to keep tracker clear. We have no plans to implement this feature, but if you have any questions or need any kind of help - contact me.
