### ISSUE TITLE
What does `typographer` actually do? How do I just get smart quotes, without any other stuff?

### ISSUE THREAD

**Issue by jameshfisher** [markdown-it/markdown-it#730]
In the course of converting my site from Jekyll to 11ty, I've enabled `typographer:true`, in order to get smart quotes. However, I then found some random other stuff was converted, like `(c)` was converted to `&copy;`. The docs just say "Enable some language-neutral replacement + quotes beautification", but don't say what all the other replacements are. I find this unnerving, as I don't know what other undesirable substitutions it's making. I really just want to explicitly opt-in to any non-standard replacements like smart quotes.

So, Q1: what does `typographer:true` actually do?

And Q2: if I want to just get smart quotes, and none of the other stuff, how can I do that? Can I do it just with `markdown-it`, or would I have to post-process with a separate library?

**Comment by jameshfisher** [comment]
OK, I managed to answer Q1, in this PR: https://github.com/markdown-it/markdown-it/pull/731

**Comment by jameshfisher** [comment]
From looking at the source, I _think_ the answer to Q2 is that, unfortunately, there's no way to just get smart quotes. The two separate features are enabled by a single flag `typographer`. Could someone confirm this?

**Comment by puzrin** [comment]
use .enable()/.disable() for concrete hook

**Comment by jameshfisher** [comment]
Thanks @puzrin, though I've had no luck with that:

```
> require('markdown-it')('zero').enable('smartquotes').render('Jim\'s "smart quotes"')
"<p>Jim's &quot;smart quotes&quot;</p>\n"
"<p>Jim’s “smart quotes”</p>\n"  // my expected output
```

Am I using it wrongly?

**Comment by jameshfisher** [comment]
Ah, hm, so, this works:

```
> require('markdown-it')({typographer:true}).disable('replacements').render('Jim\'s "smart quotes" (c)')
'<p>Jim’s “smart quotes” (c)</p>\n'
```

It seems that even if you explicitly `enable('smartquotes')`, it still hits this line https://github.com/markdown-it/markdown-it/blob/master/lib/rules_core/smartquotes.js#L190 and then gives up. So the only way is to explicitly disable everything you don't want.

A better API IMO would be for `typographer:true` to mean `.enable('replacements').enable('smartquotes')`, which could then be individually enabled or disabled.

Either way - thanks for your help @puzrin; I think I can live with `.disable('replacements')`. Hopefully `typographer:true` doesn't introduce any other transforms in future versions, so I can trust that this just enables smart quotes.

**Comment by puzrin** [comment]
> So the only way is to explicitly disable everything you don't want.

You can use `zero` preset, and enable what you need. Just be careul, some features like lists use several rules.
