### ISSUE TITLE
How to add target="_blank" and rel="noopener noreferrer" to external links?

### ISSUE THREAD

**Issue by devquestionz** [markdown-it/markdown-it#738]
Is it possible to add `target="_blank" rel="noopener noreferrer"` to links?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer dev docs has example.

**Comment by devquestionz** [comment]
@puzrin that will add that to all links what about external links? is there any method that can check if link is not one of the internal site links then add target blank?

**Comment by puzrin** [comment]
Markdown does not know anyhing about about inernal/extrnal. It's user responsibility to add more conditions to link updater.
