### ISSUE TITLE
Quoteblocks turn to &gt; text instead of normal quoteblock

### ISSUE THREAD

**Issue by IdkGoodName** [markdown-it/markdown-it#739]
If you do
```md
> A
```
in Markdown-it, it apparently outputs
```html
&gt; A
```
instead of
> A

**Comment by puzrin** [comment]
https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3E%20A%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

Works as needed.

**Comment by IdkGoodName** [comment]
![Untitled](https://user-images.githubusercontent.com/31628630/100661448-2672d600-335c-11eb-97ce-c4e4de4d5a03.png)

**Comment by IdkGoodName** [comment]
Ok, seems like other library replaced all > to &gt;.
