### ISSUE TITLE
Raw HTML header tags get rendered in a paragraph tag...

### ISSUE THREAD

**Issue by digitalmoksha** [markdown-it/markdown-it#74]
If I put a raw header tag in the markdown, it gets rendered inside a paragraph.  For example,

    <h1>Markdown</h1>

gets rendered as

    <p><h1>Markdown</h1></p>

I would expect it to be rendered like this:

    <h1>Markdown</h1>

I've tried other html block tags (not exhaustively), and they don't seem to have this problem.

**Comment by cristiano-belloni** [comment]
This is still happening with "markdown-it": "^8.4.1",

**Comment by s-a** [comment]
@puzrin why you closed this issue? 
@cristiano-belloni did found a workaround?

**Comment by s-a** [comment]
I also figured out that it converts `''` to '<pre><code></code></pre>\n' which seems random 😨
