### ISSUE TITLE
Issues with custom (Github-style) task lists

### ISSUE THREAD

**Issue by aronpammer** [markdown-it/markdown-it#740]
Github has the following style for its lists:
```
- [ ] unchecked list
- [x] checked list
```

I know there are several plugins for this already, for example this one used by thousands of users: 
https://github.com/revin/markdown-it-task-lists

However, this one checks the inline part of the string: https://github.com/revin/markdown-it-task-lists/blob/master/index.js#L17

`md.core.ruler.after('inline', 'github-task-lists', function(state) {`

The issue with this is the following:
```
- [ ] This works fine

- [ ] > In block mode -- this won't work

- [ ] # Heading -- this won't work either
```

Clearly, they won't work, because at first they will be converted into a bulletlist, then into a todo by the inline formatter plugin I mentioned above, and then it will ignore all the rest of the modifiers and treat them as plaintext.
I understand why, that's not my question, and I figured I'll just take a look at the list parser here:
https://github.com/markdown-it/markdown-it/blob/master/lib/rules_block/list.js
and extend this with my own list style. (the todo list style)

And I did:
```
function skipTodoListMarker(state, startLine) {
    var marker, startPos, pos, max, ch;
  
    pos = state.bMarks[startLine] + state.tShift[startLine];
    max = state.eMarks[startLine];
    
    var todoMarkers = [
        "- [ ] ",
        "- [X] ",
        "- [x] "
    ];

    for (let index = 0; todoMarkers.length > 0 && index < todoMarkers[0].length; index++, pos++) {
        if (pos >= max) {
            todoMarkers = [];
            break;
        }

        let newTodoMarkers = [];
        for (const todoMarker of todoMarkers) {
            const todoMarkerCode = todoMarker.charCodeAt(index);
            marker = state.src.charCodeAt(pos);

            if (marker === todoMarkerCode) {
                newTodoMarkers.push(todoMarker);
            }
        }
        todoMarkers = newTodoMarkers;
    }

    if (todoMarkers.length === 0) {
        return [-1, undefined];
    }

    // pos - 1 because we shouldn't count the last space
    return [pos - 1, todoMarkers[0].toLowerCase().includes("x")];
}
```

I also added a new element type `token       = state.push('todo_list_open', 'ul', 1);` when I detected this. All good so far.

This worked for the simplest cases.
```
- [ ] This worked
- [x] This worked as well
```

My problem is, however, is when I tried to do indentation.
```
- [ ] This works
   - [ ] This won't work
```
The second part just wouldn't work. So I started debugging why, and found out that the `state.blkIndent` is set to the end of the list marker, which in my case is the space before the first letter. So in this case the blkIndent for the first line is 5. Then I went further, and saw that in order for this list to work properly, I would have to indent the next line at least by 6.

```
- [ ] This works
      - [ ] This works now, yay
```

This is where I'm stuck. I want this to work even when the indentation is not 6, but 3, just like with normal lists. I tried changing the blkIndent parameter in a hacky way, but then I'd get a todo list, but with this text: `[ ] Todo text`, so the `[ ]` will not be removed. 

How could I make this work?

Sidenote: this same thing happens when the ordered list counter is too long
```
123456. First element
   1. second element -- this won't work
```
Which according to this: 

https://spec.commonmark.org/dingus/?text=123456.%20First%20element%0A%20%20%20%20%20%20%20%201.%20second%20element

is the expected behaviour, so I'm not saying this is an issue with this library, but other markdown text editors would treat this as a normal indented list.

Thank you!

**Comment by puzrin** [comment]
> - [ ] This works
>       - [ ] This works now, yay

1. Since you increased marker length, offset of second level increased. You need to rewrite level offset calculation logic too.
2. I can no comment CM spec. The have forum for that.

**Comment by aronpammer** [comment]
@puzrin Thanks a lot, I kind of knew this already. I'm looking for some guidance here, though. Can you please point me in the right direction? Or what would be the best platform for asking questions like this?

**Comment by puzrin** [comment]
Sorry, busy with another projects.

**Comment by aronpammer** [comment]
I understand. Good luck with your projects.
