### ISSUE TITLE
Add base URL option for links and images (and other?)

### ISSUE THREAD

**Issue by sdegutis** [markdown-it/markdown-it#741]
If I pass `baseUrl: 'https://google.com/'` and then render `[foo](foo.html)` it should render `<a href="https://google.com/foo.html">foo</a>`. The `marked` library has this option, and it's useful. Your library might benefit from it too.

**Comment by puzrin** [comment]
We do not add options, doable via plugins to keep api clean. See dev docs for examples how to implement such things.

**Comment by yuttie** [comment]
@sdegutis I had the same goal and ended up with something like the following code:
```javascript
md.core.ruler.push('baseurl', (state: any): any => {
  const baseUrl = 'https://example.com/';
  function rewrite(tokens: any[]) {
    for (const token of tokens) {
      if (token.type === 'image') {
        for (const attr of token.attrs) {
          if (attr[0] === 'src') {
            attr[1] = baseUrl + attr[1];
          }
        }
      }
      // Process recursively
      if (token.children !== null) {
        rewrite(token.children);
      }
    }
  }
  rewrite(state.tokens);
});
```

**Comment by sdegutis** [comment]
Thanks.

**Comment by Isti115** [comment]
I think that I have a but cleaner solution, but correct me if I'm missing something:
```js
const defaultImageRenderer = md.renderer.rules.image
md.renderer.rules.image = (tokens, idx, options, env, self) => {
  const src = tokens[idx].attrGet('src')
  if (src.startsWith('/')) {
    tokens[idx].attrSet('src', `https://your.base.url${src}`)
  }

  return defaultImageRenderer(tokens, idx, options, env, self)
};
```
This only prepends the base URL to links starting with `/`, so that absolute URLs are not affected. It's not a comprehensive check at all, so feel free to override the condition if you need something more fine grained.

**Comment by rlidwka** [comment]
> It's not a comprehensive check at all

Your approach is correct, however better idea would look like this (no need to do `src.startsWith`):

```js
tokens[idx].attrSet('src', url.resolve(src, 'https://your.base.url'))
```

Or use newer URL api (`new URL(src, 'https://your.base.url').toString()`) and handle the fact that it can throw exceptions.
