### ISSUE TITLE
The first line of space in the code block is not displayed

### ISSUE THREAD

**Issue by imcloudfloating** [markdown-it/markdown-it#743]
When the content is:

```
    1
2       3
```

The code block rendered as:

```
<pre><code class="hljs">1
2      3</code></pre>
```

Finally it shows:

```
1
2       3
```

**Comment by puzrin** [comment]
- https://spec.commonmark.org/dingus/?text=%20%20%20%201%0A2%20%20%20%20%20%20%203%0A%0A%60%60%60%0A%20%20%20%201%0A2%20%20%20%20%20%20%203%0A%60%60%60
- https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%20%20%20%201%5Cn2%20%20%20%20%20%20%203%5Cn%5Cn%60%60%60%5Cn%20%20%20%201%5Cn2%20%20%20%20%20%20%203%5Cn%60%60%60%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

Result is exacly as in reference parser. I'm not sure your question is related to this package.
