### ISSUE TITLE
HTML code disables Markdown formatting on the next line

### ISSUE THREAD

**Issue by laurent22** [markdown-it/markdown-it#746]
I've noticed that Markdown code that immediately follows some HTML tags will appear as unformatted.

For example:

```markdown
<div>Text below is not formatted:</div>
**test**

<div>But this one is:</div>

**test**
```

![image](https://user-images.githubusercontent.com/1285584/103321913-d1e27980-4a33-11eb-9d50-0a73ae7d9164.png)

Is that a bug? And if not, is there any option that can be used to make it render this part of the Markdown?

**Comment by puzrin** [comment]
Please, read commonmark spec for details.

**Comment by laurent22** [comment]
If someone comes across this post, this is the relevant section: https://spec.commonmark.org/0.28/#example-133 Definitely not the most intuitive part of the spec.
