### ISSUE TITLE
Does not seem to handle empty block quote in same way as CM...

### ISSUE THREAD

**Issue by digitalmoksha** [markdown-it/markdown-it#75]
It seems that the CM test at line 2381 "A block quote can be empty", fails because the blockquote tags are not separated by \n.

    > 

renders as

    <blockquote></blockquote>

instead of

```
<blockquote>
</blockquote>
```

per the spec.

This issue causes 3 tests in the CM spec to fail: 2058, 2381, and 2388

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/test/commonmark.js#L10

That's intentional, not a bug. I don't agree how CM does blockquotes and there are no requirement in HTML spec to add line break in empty tag.

**Comment by digitalmoksha** [comment]
Thank you for pointing out the normalize function in the test, I had overlooked that.

I don't know for sure, but my guess as to why they do it that way is consistency and ease in rendering.  For that type of tag, no matter what needs to be rendered inside, you can throw the opening and closing on their own line.
