### ISSUE TITLE
Network Url's (\\testserver.testlocation.com\\testfolder\\test.docx) are not supported with markdown

### ISSUE THREAD

**Issue by atishayv** [markdown-it/markdown-it#751]
If i try to use markdown with network type url's, its not rendering properly. Ex :
```[my link](\\testserver.testlocation.com\\testfolder\\test.docx)```

The output html when doing markdown.render with above text is : 
```<p><a href="%5Ctestserver.testlocation.com%5Ctestfolder%5Ctest.docx">my link</a></p>```

However it should be :
```<p><a href="\\testserver.testlocation.com\testfolder\test.docx">my link</a></p>```

Can you please help me with the same ?

**Comment by puzrin** [comment]
I'm no sure your links are valid. We implement commonmark spec. It describes escaping in details. You could override nomaliser https://github.com/markdown-it/markdown-it/blob/master/lib/index.js#L47 as you wish, but is is out of package scope.
