### ISSUE TITLE
Renders OL when value ends with a dot

### ISSUE THREAD

**Issue by Tosters** [markdown-it/markdown-it#752]
Hi!
Been working with botframework-webchat and it uses markdown-it@11.0.0 at the moment. This can be reproduced in markdown-it@latest also.
Is MarkdownIt render function supposed to be working like this:

Render for value "123." (note the "." at the end) is returning `<ol start="123"> <li></li> </ol>`
Render for value "1234567890." is returning `<p>1234567890.</p>`

Here is a [Demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22123.%5Cn123123214.%5Cn44313213.%5Cn123123123.%5Cn123123123123123.%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

**Comment by r0the** [comment]
According to CommonMark, an [ordered list marker](https://spec.commonmark.org/0.29/#ordered-list-marker) has nine or less digits. So `1234567890.` is not a list marker and is rendered correctly as a paragraph.

**Comment by puzrin** [comment]
https://spec.commonmark.org/dingus/?text=123.%0A123123214.%0A44313213.%0A123123123.%0A123123123123123.

Works exactly as reference parser. Please read commonmark spec prior to ask any questions.
