### ISSUE TITLE
Add a minimal default style for tables

### ISSUE THREAD

**Issue by jrichardsz** [markdown-it/markdown-it#753]
### Expected behaviour
 Markdown tables must have a minimal default style

### Current behaviour
If I use this table markdown
```
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| **col 3 is**  | right-aligned | $1600 |
| col 2 is      | *centered*    |   $12 |
| zebra stripes | ~~are neat~~  |    $1 |
```

The result is:

![https://i.ibb.co/LSfwB4G/2021-02-04-18-12.png](https://i.ibb.co/LSfwB4G/2021-02-04-18-12.png)

Inspecting the web, I can see that table does not have any class or style

![https://i.ibb.co/Y0MSN1C/2021-02-04-18-19.png](https://i.ibb.co/Y0MSN1C/2021-02-04-18-19.png)

But in demo https://markdown-it.github.io/ , the table looks pretty due to this class:

    class="table table-striped"

And the **bootstrap.css**

![https://i.ibb.co/HTrG4N4/2021-02-04-18-15.png](https://i.ibb.co/HTrG4N4/2021-02-04-18-15.png)

### Workaround 1

Add the **bootstrap.css**, not everyone can use it

### Workaround 2

Add class to all <table> using regex:

      var html = markdownConverter.render(markdownString);
      html = html.replace(/<table>/g, '<table class="styled-table">');

and load this css file
```
.styled-table {
  font-size: 100%;
  color: #222;
  ...etc
}  
```

### Propose

Maybe a possibility to add the table class or has a default inlined style for tables

Thanks for your awesome library!

**Comment by puzrin** [comment]
That's intended. We thinked a lot about that before implementation. And found impossible to provide universal solution out of box. So, we did minimal possible intrusion, to let users play with renderer rules as they wish.

https://github.com/markdown-it/markdown-it/blob/7b8969ce5cb2edc54f2c1aa39a85a3a08076337d/support/demo_template/index.js#L157-L159
