### ISSUE TITLE
Way to disable automatic escaping of characters?

### ISSUE THREAD

**Issue by jonpalmisc** [markdown-it/markdown-it#754]
Hi, I am wondering if there is a way to disable character escaping by default. I often use markdown-it to process Markdown that includes LaTeX, and this breaks align environments, because `\\` is turned into `\`. You can see an example of this (and the related issue) [here](https://github.com/jonpalmisc/pmt/issues/19).

I know it is possible to simply write `\\\\`, which will be converted to `\\`, but a method that doesn't require modifying existing Markdown documents would be better.

Furthermore, if this isn't a supported feature, I would be happy to submit a PR if you can point me where to start.

**Comment by puzrin** [comment]
Your question looks like misunderstanding how things work. It has no good answer. I'd recommend to read commonmark spec & investigate ready plugins in npm.

From reference, sample looks block-like. Then you need something like fenced block + customrenderer.
