### ISSUE TITLE
Add rendering rules 'table_close'

### ISSUE THREAD

**Issue by kaharman** [markdown-it/markdown-it#755]
Hello,

I have problem with Markdown table in mobile device browser. If I have big column table then the display is overflowed, the page width will follow the table width. So I want to add ```<div>``` tag as parent of table. I can use rule ```table_open``` to open DIV tag but I need also rule ```table_close```. Can we have it?

Thanks,
Kaharman

**Comment by puzrin** [comment]
It already exists.
