### ISSUE TITLE
how to make sourceMap work after transforming `markdown` 

### ISSUE THREAD

**Issue by HomyeeKing** [markdown-it/markdown-it#757]
for example, write a plugin to transform `markdown` to `vue`,
the source and the generated are mapped well,

but the `generated vue` will be sourceMapped again by `vue inner plugin` , so  how to make this connect

**in brief** :
1.  the `generated vue`  is mapped  manually to `source markdown` ,
2.  but the `inner vue plugin` will also do the sourceMap with `generated vue`, 

so is anything I should do with this or  just need to  foucus on step `1` and don't care about `2`

**Comment by puzrin** [comment]
This package does not support sourcemap. It supports only string number mappings for blocks. See previous issues, this was explained somewhere.
