### ISSUE TITLE
Does the order of use() calls matter?

### ISSUE THREAD

**Issue by valtlai** [markdown-it/markdown-it#759]
When loading markdown-it plugins, does the order of the `use()` calls matter?

So, if I have the following:

```js
const md = require('markdown-it')()
   .use(plugin1)
   .use(plugin2, opts, ...)
   .use(plugin3);
```

Is the behavior always same if I change the order, for example, to:

```js
const md = require('markdown-it')()
   .use(plugin2, opts, ...)
   .use(plugin1)
   .use(plugin3);
```

**Comment by puzrin** [comment]
If plugins install handlers on the same hook - order will be different, they may interfere somehow.

It's not possible to give one universal answer. Order CAN matter, but usually not.
