### ISSUE TITLE
Ignore specified HTML blocks in markdown-it?

### ISSUE THREAD

**Issue by yuis-ice** [markdown-it/markdown-it#760]
For example, let's say I have following markdown: 

```
> Acronis True Image does not allow to clone a single partition; only cloning of an entire disk is possible
> [Acronis True Image: how to clone a disk | Knowledge Base](https://kb.acronis.com/content/56634)

But you can use <a href="https://px.a8.net/svt/ejp?a8mat=3H7MDC+20NGN6+49QG+5YJRM" rel="nofollow">this</a><img border="0" width="1" height="1" src="https://www11.a8.net/0.gif?a8mat=3H7MDC+20NGN6+49QG+5YJRM" alt="">. 
```

markdown-it renders the one to like this: 

```
<blockquote>
<p>Acronis True Image does not allow to clone a single partition; only cloning of an entire disk is possible    
<a href="https://kb.acronis.com/content/56634">Acronis True Image: how to clone a disk | Knowledge Base</a></p> 
</blockquote>
<p>But you can use &lt;a href=&quot;https://px.a8.net/svt/ejp?a8mat=3H7MDC+20NGN6+49QG+5YJRM&quot; rel=&quot;nofollow&quot;&gt;this&lt;/a&gt;&lt;img border=&quot;0&quot; width=&quot;1&quot; height=&quot;1&quot; src=&quot;https://www11.a8.net/0.gif?a8mat=3H7MDC+20NGN6+49QG+5YJRM&quot; alt=&quot;&quot;&gt;.</p>
```

But actually I want to render the one to something like this:

```
<blockquote>
<p>Acronis True Image does not allow to clone a single partition; only cloning of an entire disk is possible    
<a href="https://kb.acronis.com/content/56634">Acronis True Image: how to clone a disk | Knowledge Base</a></p> 
</blockquote>
<p>But you can use <a href="https://px.a8.net/svt/ejp?a8mat=3H7MDC+20NGN6+49QG+5YJRM" rel="nofollow">this</a><img border="0" width="1" height="1" src="https://www11.a8.net/0.gif?a8mat=3H7MDC+20NGN6+49QG+5YJRM" alt="">.</p>
```

Is a feature something like this already implemented to markdown-it?

**Comment by puzrin** [comment]
`{ html: true }`

https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3E%20Acronis%20True%20Image%20does%20not%20allow%20to%20clone%20a%20single%20partition%3B%20only%20cloning%20of%20an%20entire%20disk%20is%20possible%5Cn%3E%20%5BAcronis%20True%20Image%3A%20how%20to%20clone%20a%20disk%20%7C%20Knowledge%20Base%5D%28https%3A%2F%2Fkb.acronis.com%2Fcontent%2F56634%29%5Cn%5CnBut%20you%20can%20use%20%3Ca%20href%3D%5C%22https%3A%2F%2Fpx.a8.net%2Fsvt%2Fejp%3Fa8mat%3D3H7MDC%2B20NGN6%2B49QG%2B5YJRM%5C%22%20rel%3D%5C%22nofollow%5C%22%3Ethis%3C%2Fa%3E%3Cimg%20border%3D%5C%220%5C%22%20width%3D%5C%221%5C%22%20height%3D%5C%221%5C%22%20src%3D%5C%22https%3A%2F%2Fwww11.a8.net%2F0.gif%3Fa8mat%3D3H7MDC%2B20NGN6%2B49QG%2B5YJRM%5C%22%20alt%3D%5C%22%5C%22%3E.%20%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D
