### ISSUE TITLE
Double space at the end of a line should be <br>

### ISSUE THREAD

**Issue by SephReed** [markdown-it/markdown-it#764]
One of the specifications I've seen for markdown is that any line that ends in two or more spaces should be a line break.

This doesn't happen in Markdown-it, and I'm having a hard time making it happen myself.

**Comment by SephReed** [comment]
Alright, so it happens on lines with text, but lines without.  That's the issue I'm running into.

**Comment by puzrin** [comment]
Please provide examples via online demo and cm dingus.

**Comment by SephReed** [comment]
Thanks for the quick response.

I think that it's user error.  Empty lines with 2+ spaces are not considered line breaks, only 2+ spaces at the end of a line with text.
