### ISSUE TITLE
Autolinks set `Token.info`

### ISSUE THREAD

**Issue by hukkinj1** [markdown-it/markdown-it#765]
The comment for `Token.info` states the attribute is for storing a [fence infostring](https://github.com/markdown-it/markdown-it/blob/7b8969ce5cb2edc54f2c1aa39a85a3a08076337d/lib/token.js#L87).

Besides fences the attribute is, however, also used by autolinks and linkify-autolinks (both set the value `"auto"`).

Maybe the comment should be made more accurate? Or perhaps autolinks should not set this attribute? If the intention is to differentiate from a non-autolink links, then `Token.markup` already achieves that.

**Comment by puzrin** [comment]
Do PR with comment clarification if you wish.
