### ISSUE TITLE
markdown-it with phantomjs: replacements only working in every second run

### ISSUE THREAD

**Issue by svbergerem** [markdown-it/markdown-it#77]
We are running markdown-it with phantomjs for our jasmine testsuite on TravisCI. Some replacements (`(c)`, `(p)`, `(r)`, `(tm)`) are only working in every second run. I uploaded a script to test this to https://gist.github.com/svbergerem/3d24e87443045ee7a4e0. That script has to be in the parent directory of the markdown-it dir. The expected output would be that `(r)`, `(p)` and `+-` are replaced everytime. For `(r)` and `(p)` that only happens every second time like you can see in the output file in the gist.

I tested this with phantomjs 1.9.8.0. https://github.com/markdown-it/markdown-it/commit/9ae876b0fe57973392db7a6735d838a78326930e introduced this issue. With builds from the parent commit https://github.com/markdown-it/markdown-it/commit/00117cb2e7052e578b376144cf1bfd8143371ba3 everything works as expected.

**Comment by puzrin** [comment]
Look at fix please. AFAIK `regex.test()` should not depend on index position when `/g` flag used. Is it phantomjs bug or my one?

PS. `make browserify` to rebuild browser files.

**Comment by puzrin** [comment]
https://www.google.ru/search?q=v8+regex+%2Fg+test+bug

As far as i see, different trackers have answer, that "odd behavior" is not a bug, but real life is different. In FF / Cromium ubunty that's not reproduceable - only in phantomjs. I've checked for sure all other places - they have separate REs for `.test()`

Try new version, just released all today fixes.

**Comment by svbergerem** [comment]
> PS. `make browserify` to rebuild browser files.

I know. :) This is exactly how I tested the different versions. I can confirm that 4.0.3 fixed the phantomjs problem. Thanks a lot.
