### ISSUE TITLE
Escaping user input

### ISSUE THREAD

**Issue by evert** [markdown-it/markdown-it#771]
Our API renders markdown responses, but part of this markdown contains user-supplied data from a database.

Roughly this might look like this:

```
ctx.response.body = `

# Hello world!

Welcome ${user.name}
`;
```

What can I do to make sure that if `user.name` contains any special characters (html, or markdown) for those to always be interpreted emitted literally?

**Comment by puzrin** [comment]
https://www.npmjs.com/package/markdown-escape - see source code

**Comment by evert** [comment]
Thank you!

**Comment by evert** [comment]
@puzrin 

Would you be open to a contribution that integrates `markdown-escape` into `markdown-it`? I would like to add both the escaping function and add support for template literals as, so it can be used this way:

```javascript

const md = markdown`
# Hello world

Hi ${username}
`;
```

I feel it would be a useful addition to markdown-it, and I'm willing to put in the work for both the feature, docs and tests

**Comment by puzrin** [comment]
Let's keep api as is.
