### ISSUE TITLE
inline comment incorrectly parsed as header

### ISSUE THREAD

**Issue by lkho** [markdown-it/markdown-it#772]
when an inline comment contains a `==` on a new line, and there is no blank lines between the starting tag `<!--` and `==`, the inline comment is treated as header.

test:
```markdown
<!--
==
-->
okay
```

expected:
https://spec.commonmark.org/dingus/?text=%3C!--%0A%3D%3D%0A--%3E%0Aokay%0A

markdown-it output:
http://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3C!--%5Cn%3D%3D%5Cn--%3E%5Cnokay%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Afalse%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Atrue%2C%22_view%22%3A%22html%22%7D%7D

**Comment by rlidwka** [comment]
Fixed, thanks for reporting.

**Comment by markNZed** [comment]
This also happens with header two level e.g.
```
<!--
-
-->
okay
```
Tested at https://markdown-it.github.io/
