### ISSUE TITLE
CodeMirror + Markdown-it = Not expected result

### ISSUE THREAD

**Issue by buinguyenhoangtho** [markdown-it/markdown-it#773]
Hi guys. Sorry for noob question. I'm using Markdown-it with CodeMirror to make my own markdown simple text. Everything is work fine. I got my preview things like below images. I'm using markdown-it to render from Markdown to HTML and somehow it give me default html tag. Can anyone teach me how to deal with it. Thanks you
I want to add style like Github

![Imgur](https://imgur.com/4F2YuRh.jpg)
My code: https://pastebin.com/gBZG8a93

**Comment by puzrin** [comment]
Sorry, can't help with generic programming questions. Only if you narrow down problem to be this package specific.
