### ISSUE TITLE
Option for classes of table cells

### ISSUE THREAD

**Issue by PaperStrike** [markdown-it/markdown-it#774]
There's a related but different #753.

Currently, markdown-it will use inline style `text-align` to align texts in table cells. It requires CSP rule `unsafe-inline` to be set, and is intrusive as an `!important` is required to override that.

Using `renderer.rules.table_open` can configure the class attribute of `<table>`, as mentioned in the related issue:

https://github.com/markdown-it/markdown-it/blob/7b8969ce5cb2edc54f2c1aa39a85a3a08076337d/support/demo_template/index.js#L157-L159

I wonder if there's a similar API for us to configure the align-requiring cells, making it possible for us to use classes like `.align-right` to style them.

Thanks.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/rules_block/table.js

See token names and use is as rule name to override default behaviour of `th_open` & `td_open` (see condition like [this](https://github.com/markdown-it/markdown-it/blob/3740146fc9c92ea15fdc6a358137ec7b68f05f4b/lib/renderer.js#L329)). For example, you could check if `style` attribute exists and replace it with `class` attribute on the fly.

**Comment by PaperStrike** [comment]
@puzrin I noticed some discussions made in https://github.com/markedjs/marked/issues/1211. I think it's the same case to markdown-it, so would you consider using `align` attribute instead of inline style? If not, why?
