### ISSUE TITLE
Markdown between non-CommonMark tags doesn't render

### ISSUE THREAD

**Issue by AbhijeetKrishnan** [markdown-it/markdown-it#776]
Markdown present between tags enabled by syntax extensions (e.g. [subscript](https://github.com/markdown-it/markdown-it-sub), [superscript](https://github.com/markdown-it/markdown-it-sup) and others) doesn't render. This affects the ability to chain plugins that provide this type of "fenced" syntax extension.

## MWE ([permalink](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%5E%2At%2A%5E%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D))

```
^*t*^
```

## Expected output

```html
<p><sup><em>t</em></sup></p>
```

## Actual output

```html
<p><sup>*t*</sup></p>
```

**Comment by puzrin** [comment]
1. That's not related to this repo.
2. That's done such way intended, to simplify things.
