### ISSUE TITLE
Parsing of table with inline code with vertical bar

### ISSUE THREAD

**Issue by usernamehw** [markdown-it/markdown-it#777]
```
| 1     | 2     |
| ----- | ----- |
| `||3` | `4||` |
```

| 1     | 2     |
| ----- | ----- |
| `||3` | `4||` |

[markdown-it demo](https://markdown-it.github.io/#md3=%7B%22source%22:%22%7C%201%20%20%20%20%20%7C%202%20%20%20%20%20%7C%5Cn%7C%20-----%20%7C%20-----%20%7C%5Cn%7C%20%60%7C%7C3%60%20%7C%20%604%7C%7C%60%20%7C%22,%22defaults%22:%7B%22html%22:false,%22xhtmlOut%22:false,%22breaks%22:false,%22langPrefix%22:%22language-%22,%22linkify%22:true,%22typographer%22:true,%22_highlight%22:true,%22_strict%22:false,%22_view%22:%22html%22%7D%7D)

**Comment by r0the** [comment]
https://docs.github.com/en/github/writing-on-github/organizing-information-with-tables:

> To include a pipe | as content within your cell, use a \ before the pipe:

```
| 1       | 2       |
| ------- | ------- |
| `\|\|3` | `4\|\|` |
```

**Comment by usernamehw** [comment]
Thanks, I though that would render the `\` symbol.
