### ISSUE TITLE
Incorrectly added attributes to the closing tag

### ISSUE THREAD

**Issue by Yubiao-Li** [markdown-it/markdown-it#778]
when I use `new Markdown().render(html)`, it will generate code like this 
![image](https://user-images.githubusercontent.com/39786286/115508146-918f5b80-a2af-11eb-8f9e-5f2140133947.png)
which has incorrectly added attributes to the closing tag

**Comment by puzrin** [comment]
This is NOT output by pure markdown-it. Your question should be addressed to app, using it with plugins.

**Comment by Yubiao-Li** [comment]
yes, it is caused by my plugin, thanks
