### ISSUE TITLE
Enhancement: a form syntax module

### ISSUE THREAD

**Issue by dumblob** [markdown-it/markdown-it#78]
I was searching for a simple way how to create forms in Markdown/CommonMark and found out, that there are number of different ideas how to approach this problem:

1. https://github.com/rbnvrw/markdown-forms
2. https://github.com/bradgessler/formdown
3. https://github.com/maleldil/wmd

Which of these would you prefer and why (in terms of consistency, extensibility, usability...)?

**Comment by puzrin** [comment]
I don't know - never had such need. It's better to duscuss commonmark extensions proposals at http://talk.commonmark.org/ - guys there are more experienced in such questions.

**Comment by dumblob** [comment]
I've tried to sign in using my github account, but they want me to register instead of logging me in. Do you have an account there already? If so, could you please ask the question there and refer to this github issue?

**Comment by puzrin** [comment]
Sorry, cant provide such kind of assistense. This issue is out of this repo subject.
