### ISSUE TITLE
Use it with vitepress

### ISSUE THREAD

**Issue by deleonio** [markdown-it/markdown-it#780]
Use-Case: https://vitepress.vuejs.org/guide/markdown.html#advanced-configuration

**.vitepress/config.js**
```js
...
  markdown: {
    config: (md) => {
      // use more markdown-it plugins!
      md.use(require('mermaid-it'));
    },
  },
...
```

**doc.md**
```md
### Graph
```mermaid
graph TD;
  test-accessibility-nav --> test-link
  style test-accessibility-nav fill:#f9f,stroke:#333,stroke-width:4px
```

![image](https://user-images.githubusercontent.com/6279703/116179775-34186600-a718-11eb-86ad-0a82a4724e49.png)

**Comment by puzrin** [comment]
Sorry, we can not help with third party packages.

**Comment by emersonbottero** [comment]
https://emersonbottero.github.io/vitepress-plugin-mermaid/
