### ISSUE TITLE
Add Mermaid support

### ISSUE THREAD

**Issue by cadavre** [markdown-it/markdown-it#781]
Mermaid is a well-known extension to any Markdown-like editors:

https://mermaid-js.github.io/mermaid/#/

It allows to create various diagrams: class, gantt, state, entity relationship...

It is purely text-based so no additional elements in editor is required. Rendering is made with dedicated JS+CSS.

**Comment by puzrin** [comment]
Sorry, we do not accept customization requests. All extensions are expected to be done by volunteers via plugins.

**Comment by CarsonSlovoka** [comment]
Hi @cadavre 

You can try

```html
<div data-com="markdown-it">
  <div class="mermaid">
    flowchart TD
    A[Start] --> B{Is it?}
    B -->|Yes| C[OK]
    C --> D[Rethink]
    D --> B
    B ---->|No| E[End]
  </div>
</div>
<script>
  mermaid.initialize({
    theme: 'forest', // forest dark, base, default
    logLevel: "fatal", // debug, fatal
    securityLevel: 'loose', // strict, loose, antiscript, sandbox // https://github.com/mermaid-js/mermaid/blob/b141f24068e9c5f6979706383a29db6380ffdf31/docs/usage.md?plain=1#L114-L117
    flowchart: {curve: 'basis'},
  })
  window.onload = () => {
    document.querySelectorAll(`[data-com="markdown-it"]`).forEach(elem => {
      if (elem.dataset.com === undefined) {
        return
      }
      const md = window.markdownit({
        html: true,
        linkify: true,
        typographer: true
      })
      elem.outerHTML = md.render(elem.innerHTML)
    })
  }
</script>
```

[see example and output](https://gist.github.com/CarsonSlovoka/3c3bbf1e4d3e8bc9655c555c40ae8a69?permalink_comment_id=4085411#gistcomment-4085411)
