### ISSUE TITLE
Question: Why is `int` char code used instead of a char?

### ISSUE THREAD

**Issue by hukkinj1** [markdown-it/markdown-it#782]
Hey @puzrin thanks for an excellent parser!

[I've been trying to understand ](https://github.com/executablebooks/mdit-py-plugins/pull/17#discussion_r619785465)why we use integer character codes instead of characters of type `String` in the code.

For example [this line](https://github.com/markdown-it/markdown-it/blob/df4607f1d4d4be7fdc32e71c04109aea8cc373fa/lib/rules_block/blockquote.js#L37):
```js
if (state.src.charCodeAt(pos++) !== 0x3E/* > */) { return false; }
```

wouldn't it be more concise and readable to compare the character directly, i.e.
```js
if (state.src[pos++] !== '>') { return false; }
```
I'm sure there's a good reason, just couldn't understand what it is by myself. Would be great if you could shed some light on this.

Thanks in advance!

**Comment by puzrin** [comment]
That's for speed optimizations. I'd suggest to read https://mrale.ph/ first. Because how js jit works is completely different from what you can imagine :).
