### ISSUE TITLE
Babelmark results are broken or outdated

### ISSUE THREAD

**Issue by vassudanagunta** [markdown-it/markdown-it#784]
This is just a heads up:

On [Babelmark 2](https://johnmacfarlane.net/babelmark2): `markdown-it failed to return a valid response: error Internal Server Error`

On [Babelmark 3](https://babelmark.github.io), the results are from `markdown-it 8.4.0` which differs a lot from current behavior.

**Comment by puzrin** [comment]
Please, contact babelmark author, i'm not responsible for what happens there. The only thing i provide is http responder, it's auto-deployed to heroku on each master commit.

**Comment by vassudanagunta** [comment]
I figured you'd want Babelmark to reflect accurately how Markdown-it behaves -- i.e. I was trying to be helpful. I already know so this isn't important to me.

**Comment by puzrin** [comment]
No problem. Babelmark was important for investigations, but now, when CM spec exists and markdown-it follows it - i don't care what happens in babelmark.
