### ISSUE TITLE
Images cannot be resized

### ISSUE THREAD

**Issue by sindhus** [markdown-it/markdown-it#79]
I can use markdown-it to display images in my app but cannot show re-sized images like this:
`![](pic1s.png =250x)`
`![](./pic/pic1s.png =100x100)`

Can you add support for this please? Thanks!

**Comment by puzrin** [comment]
This package implements [commonmakr spec](http://commonmark.org/) and doesn't accept custom requests in core. Try to search available plugins (see readme). Probably, someone already implemented this feature.
