### ISSUE TITLE
Image not rendered if src is prefixed by `file://`

### ISSUE THREAD

**Issue by ChristophNiehoff** [markdown-it/markdown-it#793]
Image tags are not rendered to HTML if the source is prefixed by `file://`.
Example:
```
![image](file:///home/user/image.jpg)
```
is rendered to 
```
<p>![image](file:///home/user/image.jpg)</p>
```

For other prefixes it is rendered correctly to an `<img>` tag.

Used version: 12.0.6
Demonstration:  [on the demo playground](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22These%20work%20as%20expected%3A%5Cn%5Cn!%5Bimage%5D%28https%3A%2F%2Fexample.org%2Fimage.jpg%29%5Cn!%5Bimage%5D%28%2Fhome%2Fuser%2Fimage.jpg%29%5Cn!%5Bimage%5D%28C%3A%5C%5C%5C%5Cusers%5C%5C%5C%5Cimage.jpg%29%5Cn!%5Bimage%5D%28foobar%3A%2F%2F%2Fhome%2Fuser%2Fimage.jpg%29%5Cn!%5Bimage%5D%28ThisIsACoolString%29%5Cn!%5Bimage%5D%28filex%3A%2F%2F%2Fhome%2Fuser%2Fimage.jpg%29%5Cn%5CnThis%20is%20strange%3A%5Cn%5Cn!%5Bimage%5D%28file%3A%2F%2F%2Fhome%2Fuser%2Fimage.jpg%29%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D)

commonmark handles this correctly: [see demonstration](https://spec.commonmark.org/dingus/?text=These%20work%20as%20expected%3A%0A%0A!%5Bimage%5D(https%3A%2F%2Fexample.org%2Fimage.jpg)%0A!%5Bimage%5D(%2Fhome%2Fuser%2Fimage.jpg)%0A!%5Bimage%5D(C%3A%5C%5Cusers%5C%5Cimage.jpg)%0A!%5Bimage%5D(foobar%3A%2F%2F%2Fhome%2Fuser%2Fimage.jpg)%0A!%5Bimage%5D(ThisIsACoolString)%0A!%5Bimage%5D(filex%3A%2F%2F%2Fhome%2Fuser%2Fimage.jpg)%0A%0AThis%20is%20strange%3A%0A%0A!%5Bimage%5D(file%3A%2F%2F%2Fhome%2Fuser%2Fimage.jpg))

**Comment by ChristophNiehoff** [comment]
The same is also true for `<a>` tags.

**Comment by puzrin** [comment]
1. https://github.com/markdown-it/markdown-it/blob/master/lib/index.js#L32-L40 override default validator as you wish
2. enable html (disabled by default)

By default markdown-it output is "secure", but you can relax this if you know what you do.

**Comment by ChristophNiehoff** [comment]
Ok, that makes sense.

Thanks, @puzrin , for your help!
