### ISSUE TITLE
How to  Parsing  <adc>?

### ISSUE THREAD

**Issue by tangjuncheng1986** [markdown-it/markdown-it#794]
Hi :
    If I add <hello> in md file, the content cannot show .But If I add <add我的> ,the content can be show.
![image](https://user-images.githubusercontent.com/19219876/123943073-59eb1100-d9ce-11eb-8617-7880c42a2fb0.png)

**Comment by puzrin** [comment]
I guess, only latin letters allowed in custom tags

https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Cadd%E6%88%91%E7%9A%84%3E%5Cn%5Cn%3Cadd%3E%5Cn%5Cn%3Chello%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D
