### ISSUE TITLE
[Bug Report] can't recognize self-closing html inline elements correctly

### ISSUE THREAD

**Issue by meteorlxy** [markdown-it/markdown-it#796]
Sorry for creating a duplicate issue, but the previous one #795 was closed by @puzrin without a reasonable anwser.

As the markdown spec, inline html elements should be force-wrapped by paragraph.

However, `<img>` element won't be wrapped correctly.

The reason might be that, self-closing html tags are always recognized as block elements:

![image](https://user-images.githubusercontent.com/18205362/124457482-70bea880-ddbe-11eb-8651-06db9d6ef7ac.png)

https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Cimg%20src%3D%5C%22foo%5C%22%3E%3C%2Fimg%3E%5Cn%5Cn%3Cimg%20src%3D%5C%22foo%5C%22%3E%5Cn%5Cn%3Cb%3Efoo%3C%2Fb%3E%5Cn%5Cn%3Cb%2F%3E%5Cn%5Cn%3Cspan%3Efoo%3C%2Fspan%3E%5Cn%5Cn%3Cspan%2F%3E%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

**Comment by puzrin** [comment]
Please, stop create duplicated issue.

**Comment by rlidwka** [comment]
> As the markdown spec, inline html elements should be force-wrapped by paragraph.

As per commonmark spec version 0.30, section 4.6, condition 7, `<img src="foo">` on its own line followed by a blank line is a block element, https://github.com/markdown-it/markdown-it/issues/795
