### ISSUE TITLE
Image style support (plugin?)

### ISSUE THREAD

**Issue by jeffmcneill** [markdown-it/markdown-it#80]
I have a need for image style support, usually just width="100%" but sometimes other stuff (alt, title, other size parameters). What would be the best approach to extending markdown-it with this kind of syntax?

**Comment by vyp** [comment]
Not sure about the answer to your question but fyi seems similar to #79.

Therefore, for the moment at least, [this](https://github.com/tatsy/markdown-it-imsize) might be what you're looking for?

**Comment by jeffmcneill** [comment]
I've added an issue over there to see if the support is present: https://github.com/tatsy/markdown-it-imsize/issues/4

**Comment by puzrin** [comment]
> What would be the best approach to extending markdown-it with this kind of syntax?

Only via plugins, because core should follow spec, instead of reinventing one more custom markdown dialect. Search in [plugins](https://www.npmjs.org/browse/keyword/markdown-it-plugin) first, because even if something not exists, you can find similar one and rewrite for your needs.

If you need to discuss syntax itself, the best place is http://talk.commonmark.org

**Comment by caub** [comment]
Updated and simplified plugin with latest markdown-it, I think I'll publish to npm soon with tests

https://runkit.com/caub/629b37d2a0045d00080b08b5

```js
function markdownItImageSize(md, { lazy = true, caption = true } = {}) {
  md.renderer.rules.image = function (tokens, idx, options, env, slf) {
    const token = tokens[idx];

    // "alt" attr MUST be set, even if empty. Because it's mandatory and
    // should be placed on proper position for tests.
    //
    // Replace content with actual value

    token.attrs[token.attrIndex('alt')][1] =
      slf.renderInlineAsText(token.children, options, env);

    if (lazy && token.attrIndex('loading') === -1) { // add loading="lazy" attribute
      token.attrs.push(['loading', 'lazy']);
    }

    // process optional ={width}x{height} title
    const titleIndex = token.attrIndex('title');
    if (titleIndex >= 0) {
      const [title, size] = token.attrs[titleIndex][1].split('=');
      const [width, height] = size ? size.split('x').map(v => v.trim()).filter(Boolean) : [];
      if (title) {
        token.attrs.splice(titleIndex, 1,
          ...typeof caption !== 'boolean' && title ? [['title', title]] : [],
        );
      }
      if (width) {
        token.attrs.push(
          ['width', width],
          ...height ? [['height', height]] : [],
        );
      }

      if (caption && title) return `<figure>${slf.renderToken(tokens, idx, options)}<figcaption>${title}</figcaption></figure>`;
    }

    return slf.renderToken(tokens, idx, options);
  };
}
```
