### ISSUE TITLE
Markdown using code blocks not indented text for element numbers with three digits or more

### ISSUE THREAD

**Issue by Syntactical01** [markdown-it/markdown-it#800]
Sorry if this is the wrong spot to put this. I originally filed this bug with VS Code but it appears it was upstream of them so I decided to see if this is the right spot base on the feedback I got from them. If this is the wrong spot please let me know.

My original Issue
https://github.com/microsoft/vscode/issues/129305
Issue Type: <b>Bug</b>

Create over 100 elements in a numbered list in markdown. Indenting the text under the number sections will cause the indented text in the markdown preview to be considered a code block not just indented text. This is fine for 1-99 items but items numbered 100+ have the issue:

```Markdown
100. My item.

    This text should be indented not a code block, which it is for item 1-99 but 100+ its turned into a code block in VSCode.
```

Note that it works fine if I do the numbers like:
```Markdown
1. Element one
1. Element two
1. Element three
```
but the second I start using a three digit number it has the issue.

Screenshot for context:
![image](https://user-images.githubusercontent.com/46199814/126877984-5a3a67ad-e364-4e46-9aff-b0aa8132d8d3.png)

The response I got:
> This is consistent [with how CommonMark renders that example](https://spec.commonmark.org/dingus/?text=100.%20My%20item.%0A%0A%20%20%20%20This%20text%20should%20be%20indented%20not%20a%20code%20block%2C%20which%20it%20is%20for%20item%201-99%20but%20100%2B%20its%20turned%20into%20a%20code%20block%20in%20VSCode.) and [how markdown-it renders it too](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22100.%20My%20item.%5Cn%5Cn%20%20%20%20This%20text%20should%20be%20indented%20not%20a%20code%20block%2C%20which%20it%20is%20for%20item%201-99%20but%20100%2B%20its%20turned%20into%20a%20code%20block%20in%20VSCode.%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)
> 
> If you believe this is an issue, please file an issue against markdown-it to start. I believe the markdown spec [should allow up to nine digits for ordered lists](https://spec.commonmark.org/0.30/#ordered-list-marker) (although maybe there's some exception I'm overlooking here)

**Comment by yume-chan** [comment]
Related to commonmark/commonmark-spec#594, looks like this is compliant with the spec.

**Comment by rlidwka** [comment]
You should vertically align "My item." and "This text" for it to be considered a list item.

This works:

```
100. My item.

     This text
```

This doesn't:

```
100. My item.

    This text
```

Since string "100." is larger than "99.", all items in it should be prefixed by 1 space more (at least 5 spaces as opposed to at least 4).

Not a bug, this is very much intentional I believe.

**Comment by Syntactical01** [comment]
@rlidwka  I always thought indentation was 4 spaces (same the required indentation for code blocks if ``` wasn't used. Note that 4 spaces works properly on: https://markdownlivepreview.com/

I can indent one more but I do not believe this was the design intention (I could be wrong as it seems different previewers are inconsistent) but the 4 spaces makes more sense then aligning with the number since 4 spaces is what indentations normally do in IDEs.

**Comment by rlidwka** [comment]
Please read this fragment of CommonMark spec that describes exactly this issue:
https://github.com/commonmark/commonmark-spec/blob/499ebbad90163881f51498c4c620652d0c66fb2e/spec.txt#L103-L117

Long story short, all parsers following CommonMark spec will require same indentation as the first paragraph in the list item.

Original Markdown.pl and most other implementations will require 4 space indentation, but it varies between parsers.
