### ISSUE TITLE
Can I load/save a MD file from/to an arbitrary GIT repository?

### ISSUE THREAD

**Issue by RufusJWB** [markdown-it/markdown-it#802]
I would like to load (`pull`) a markdown file from an arbitrary GIT repository, edit it with `markdown-it` and then save(`commit` and `push`) it back. Do you support such a mechanism? I was looking for a way to plug this in, but I couldn't find a reference / starting point to do so.

**Comment by puzrin** [comment]
This question is out o project scope.

**Comment by RufusJWB** [comment]
Thank you for the feedback @puzrin - I finally understood that you are doing 'only' the rendering but not the 'editing' of markdown. Sorry for stealing your time ;-)

But while I'm already stealing your time, I have one more question: can you recommend a web control for editing markdown files online which uses your rendering engine?

**Comment by puzrin** [comment]
I used only CodeMirror. It's better to google for full list.

**Comment by RufusJWB** [comment]
Thank you!
