### ISSUE TITLE
I turned on HTML parsing，I got the correct HTML on PC, but I didn't get the correct HTML on my phone

### ISSUE THREAD

**Issue by websunny** [markdown-it/markdown-it#803]
in pc 

![image](https://user-images.githubusercontent.com/37695257/128192125-be7b1223-3c7f-4dbe-b7a4-2c927a3e3581.png)
in phone

 ![image](https://user-images.githubusercontent.com/37695257/128192007-0fe06608-9b3e-48c8-93b0-6768e4f0c7cd.png)

**Comment by puzrin** [comment]
Your question does not seems to be related to this package.
