### ISSUE TITLE
How to get raw text, without Markdown tokens?

### ISSUE THREAD

**Issue by saneef** [markdown-it/markdown-it#804]
I have a use case where I need to get the raw text, markdown tokens removed? I need to achieve what `markdown-it` is doing to [`alt` attributes in `<img>` tags](https://github.com/markdown-it/markdown-it/blob/eed156e9cd8f9db123e7fb227d40fff052dffac2/test/fixtures/markdown-it/commonmark_extras.txt#L15).

What is the write way to do with `markdown-it`?

**Comment by puzrin** [comment]
https://markdown-it.github.io/#md3=%7B%22source%22%3A%22!%5B%2Astrip%2A%20%5Bmarkdown%20__in__%20alt%5D%28%23%29%5D%28%23%29%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22debug%22%7D%7D

Raw alt src already exists in token

**Comment by saneef** [comment]
Sorry, I failed to explain my use case.

I use static site generator to build my website. I want to use Markdown on titles. Here is an example:
```yml
---
# Front matter
title: A title with _italics_
---

...content follows...
```

And in the generated HTML I want to achive:
```html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>A title with italics</title> <!-- 👈 Raw text from `title` here -->
</head>
<body>
	<article>
                <h1>A title with <em>italics</em></h1> <!-- 👈 HTML from `title` here, for which I can use `renderInline()` -->
               ...content follows...
        </article>
</body>
</html>
```

I can see `renderInlineAsText` in the API docs, but _it is internal._ Is there any way to get what `renderInlineAsText` provides internally?

**Comment by puzrin** [comment]
IMO your question is not related to this project. You could split input and process metadata before markdown call.
