### ISSUE TITLE
How to pass special characters as nordic languages letters as æ,å,ø

### ISSUE THREAD

**Issue by Jakub41** [markdown-it/markdown-it#806]
Hello,

I have a requirement in my project to add special characters to a PDF like:
æ,ø,å and else.

I'm using your package to make the data to HTML but when data comes with nordic languages special characters that are not shown in the HTML and seem to me that the MD is escaping those.

How can avoid that and include the special characters into the HTML than PDF? 

Hope you can help me with my issue.

Thank you for your time.

**Comment by puzrin** [comment]
https://markdown-it.github.io/ please use online demo for checks and examples. Everything should work.
