### ISSUE TITLE
Pipes in backticks inside tables break rendering

### ISSUE THREAD

**Issue by rauschma** [markdown-it/markdown-it#808]
This used to work in v8.4.2, but doesn’t seem to work in the latest version.

Example:

```md
| Operator | Description |
|----------|-------------|
| `|`      | Bitwise Or  |
| `&`      | Bitwise And |
| `^`      | Bitwise Xor |
```

Output:

```html
<table>
<thead>
<tr>
<th>Operator</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td>`</td>
<td>`</td>
</tr>
<tr>
<td><code>&amp;</code></td>
<td>Bitwise And</td>
</tr>
<tr>
<td><code>^</code></td>
<td>Bitwise Xor</td>
</tr>
</tbody>
</table>
```

https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%7C%20Operator%20%7C%20Description%20%7C%5Cn%7C----------%7C-------------%7C%5Cn%7C%20%60%7C%60%20%20%20%20%20%20%7C%20Bitwise%20Or%20%20%7C%5Cn%7C%20%60%26%60%20%20%20%20%20%20%7C%20Bitwise%20And%20%7C%5Cn%7C%20%60%5E%60%20%20%20%20%20%20%7C%20Bitwise%20Xor%20%7C%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

**Comment by puzrin** [comment]
Not a bug, works exactly as on github. You need to escape `|`

https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%7C%20Operator%20%7C%20Description%20%7C%5Cn%7C----------%7C-------------%7C%5Cn%7C%20%60%5C%5C%7C%60%20%20%20%20%20%20%7C%20Bitwise%20Or%20%20%7C%5Cn%7C%20%60%26%60%20%20%20%20%20%20%7C%20Bitwise%20And%20%7C%5Cn%7C%20%60%5E%60%20%20%20%20%20%20%7C%20Bitwise%20Xor%20%7C%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

**Comment by rauschma** [comment]
The point of backticks is precisely that pipes do not have to be escaped (other special characters such as the asterisk don’t have to be escaped either).

* GitHub handles this correctly: In the initial example, I did not have to escape the pipe.
* Same: Pandoc

**Comment by puzrin** [comment]
Sorry, but discussing spec is out of scope. This is software implementation, not spec development area.

If you don't like default table behaviour, you can replace it with your custom plugin.

**Comment by rauschma** [comment]
It’s obviously your call! Thanks for taking the time to answer.

As an aside: Spec-wise, things seem clear to me: `` `\|` `` is normally rendered as a backslash followed by a pipe: `\|`
CommonMark: https://spec.commonmark.org/dingus/?text=%60%5C%7C%60

Tables are the only exception in GitHub-flavored Markdown and markdown-it (but not in Pandoc).

**Comment by puzrin** [comment]
Please, don't try to involve me into holywars "what spec is better". Since CM does not define tables, we follow GFM spec for those. You may like or not like this choice, but it's not subject to discuss. If you need changes in this repo - ask github guys to update GFM spec.

Or you can just create you own plugin for tables instead.

**Comment by rauschma** [comment]
It’s indeed in their spec: https://github.github.com/gfm/#example-200

I wasn’t aware of that and thought this was only how they happened to implement it. But it’s a deliberate decision.
