### ISSUE TITLE
The bolded result is incorrect

### ISSUE THREAD

**Issue by usecodelee** [markdown-it/markdown-it#809]
> **111:**222222

The result of parsing is:
![image](https://user-images.githubusercontent.com/32923083/130384598-f443c7bb-3b68-4aec-bb94-e57ff97fcf85.png)

And not like this:
![image](https://user-images.githubusercontent.com/32923083/130384832-5390aee1-88d1-4822-adf9-4101c5611edf.png)

I'm guessing here it should be[:*] hit on emoji

**Comment by puzrin** [comment]
https://spec.commonmark.org/dingus/?text=**111%3A**222222%0A it works exactly as reference parser.

See spec for markup details

**Comment by tats-u** [comment]
You live in China, so this plugin may help you: https://www.npmjs.com/package/markdown-it-cjk-friendly (the suggested case is not covered, but many Chinese text will be covered)
