### ISSUE TITLE
Would it be possible for a markdown-it plugin to implement attribute lists, meta data extension?

### ISSUE THREAD

**Issue by jeffbski** [markdown-it/markdown-it#81]
Would it be possible for a markdown-it plugin to implement the Maruku meta data extensions (inline attribute lists and attribute list definitions)? 

These are really useful for being able to set a few key attributes like id and class without having to switch into full html. They are also real useful for setting attributes on links and images, so you can make some links nofollow or set the target. Very useful. I have used these with Maruku in the past on Ruby and loved them, I am really wishing that one of these parsers would implement so I can use them now with javascript.

See: http://maruku.rubyforge.org/proposal.html

A few details from the proposal page:

This proposal describes two additions to the Markdown syntax:

inline attribute lists (IAL)
```markdown
## Header ##       {: key=val .class #id ref_id}
```

attribute lists definitions (ALD)
```markdown
{:ref_id: key=val .class #id}
```

Every span-level or block-level element can be followed by an IAL:
```markdown
### Header ###     {: #header1 class=c1}

Paragraph *with emphasis*{: class=c1}
second line of paragraph
{: class=c1}
```

In this example, the three IALs refer to the header, the emphasis span, and the entire paragraph, respectively.

IALs can reference ALDs. The result of the following example is the same as the previous one:

```markdown
### Header ###  {: #header1 c1}

Paragraph *with emphasis*{:c1}
second line of paragraph
{:c1}

{:c1: class=c1}
```

**Comment by puzrin** [comment]
https://github.com/andrey-p/markdown-it-classy

There are no way to implement it __correct__ via plugin (i don't count all rules rewrite), because definition has problems with consistency. We postponed all related work on this kind of extension, until it's done in commonmark spec. That will happen sometime, but no deadlines known. Until that happens, you can try hack from link above.

**Comment by jeffbski** [comment]
@puzrin Thanks for letting me know. I'm glad there is discussion about this to standardize and improve the spec. It's great stuff. Thanks for pointing me to classy plugin, that could help for some things.

**Comment by andrey-p** [comment]
@puzrin @jeffbski Probably worth mentioning that I haven't yet managed to port `markdown-it-classy` to work with `markdown-it` version 4 and above - it's on my todo list for this week.

**Comment by puzrin** [comment]
@andrey-p  thanks for info. If you need help - let me know.

**Comment by jeffbski** [comment]
@andrey-p thanks for the heads up.
