### ISSUE TITLE
Add a default rules list for original package.

### ISSUE THREAD

**Issue by AkiraVoid** [markdown-it/markdown-it#810]
I'm using this package to add markdown support for my web app. But some functions like `table` should be disabled for users. I know I can find all rules' names in the lib, but I just don't understand what they actually are(like `lheading`). I am wondering if there can be a list of default rules which show their names and describe them.

**Comment by puzrin** [comment]
The only thing i can suggest - read spec first https://spec.commonmark.org/0.30/ for markup elements names. Usually rule names are the same or very similar. Or you can ask concrete question about concrete name.
