### ISSUE TITLE
Render hangs when paragraph rule is disabled

### ISSUE THREAD

**Issue by NOtherDev** [markdown-it/markdown-it#811]
```
var MarkdownIt = require("markdown-it")
const md = new MarkdownIt()
md.disable('paragraph').render(`--`)
```

Version 12.2.0.

Rendering of this code never finishes, see [RunKit](https://runkit.com/embed/qdumcuikmax0).

**Comment by puzrin** [comment]
You should NOT disable paragraph rule. It's mandatory.

**Comment by NOtherDev** [comment]
OK then, maybe I'll present my issue broader. I'm parsing user-provided markdown and I'd like to get the horizontal line here:

```
md.render('hey\n---\nho')
```

I'm getting `hey` as heading though. Is there a way to disable [this heading](https://spec.commonmark.org/0.30/#setext-heading)? `disable('heading')` doesn't seem to do the trick.

**Comment by NOtherDev** [comment]
It's `disable('lheading')` it seems! Thanks 🙂

**Comment by puzrin** [comment]
I'd recommend to add empty lines before/after `---` to follow spec. When you disable rule like `lheading`, you may reinvent "one more markup standard" :).

**Comment by NOtherDev** [comment]
Right... Well, if only I control what I get from the users... :) Thanks anyway!

**Comment by duncte123** [comment]
> You should NOT disable paragraph rule. It's mandatory.
> 
> Probably you need `.renderInline()` method.

I feel like this should be documented over at https://markdown-it.github.io/markdown-it/#MarkdownIt.disable 
(might pr if I have time)

**Comment by rlidwka** [comment]
I've changed it, so markdown parser now throws an error instead of going into infinite loop:

https://github.com/markdown-it/markdown-it/commit/1529ff4944329eb8080a8558dab85164b6c212cd

but the patch wasn't released yet
