### ISSUE TITLE
[Bug] Markdown links display incorrectly when used with backticks

### ISSUE THREAD

**Issue by wenfangdu** [markdown-it/markdown-it#814]
Steps to Reproduce:

1. Paste the following code into [the editor](https://markdown-it.github.io/):

```
[`code`](https://example.com)
```

2. Displays as code, can't tell it's a link:

   ![image](https://user-images.githubusercontent.com/28700378/131200493-a0a70797-548e-4d79-ab91-9ca4af68052d.png)

**Comment by puzrin** [comment]
https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%5B%60code%60%5D%28https%3A%2F%2Fexample.com%29%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D

Works as expected, link exists.

**Comment by wenfangdu** [comment]
@puzrin They look the same unless hovering over each of them:

![image](https://user-images.githubusercontent.com/28700378/131210401-14d96962-3c19-48c4-9add-43616a9599ca.png)

![image](https://user-images.githubusercontent.com/28700378/131210440-1aa11546-aa85-44ab-a3e0-3ae8e639a55c.png)

The following is what's expected:

[`Clickable Code`](https://example.com) `Just Code`.

**Comment by puzrin** [comment]
That's not this package problem. This package generates html only. You can style it as you wish with css
