### ISSUE TITLE
How to get existing rules to extend then using `at`-function?

### ISSUE THREAD

**Issue by katerlouis** [markdown-it/markdown-it#824]
[EDIT: I know about https://www.npmjs.com/package/markdown-it-attrs – but since I'm aiming for even more customization than explained here and learning to extend markdown-it in general, I'd like to add the mentioned functionality myself]

Bit of background:
I wanna enable my colleagues to add [ScrollTriggers](https://greensock.com/scrolltrigger/) to call specific functions when the user has scrolled there. I'd like to extend existing rules rules for that. What I need is all block rules accepting an optional (kebab-case) string parameter, that then gets added as a `data-`-attribute to the html (or ideally initializes the scrolltrigger directly, but I guess that's not possible, because I need a DOM element for that and markdown-it only produces strings, right?)

When I do `md.block.ruler.at('heading', function()...` I need a the original render (?) function. 

All the examples I found in the issues so far include `md.renderer.rules.<rule-to-overwrite>`, but neither `heading` nor `paragraph` nor any other block rules are present there. 

Only other way I can think of getting the function is by filtering through `md.block.ruler.__rules__` array, which doesn't seem right. 

So, here are my specific questions
1) How would you suggest to enhance all block rules with that functionality?
2) What syntax would you suggest to add optional string parameter to block rules (mainly headings/paragraphs)?

Thanks a lot :)

**Comment by rlidwka** [comment]
> Only other way I can think of getting the function is by filtering through md.block.ruler.__rules__

If you need existing functions, there probably isn't a better option. *Accessing existing functions for the purpose of overriding is such a rare case, so there just isn't any API for it.*

> (or ideally initializes the scrolltrigger directly, but I guess that's not possible, because I need a DOM element for that and markdown-it only produces strings, right?)

Browser will see these strings as DOM elements. You can write initialization code inside `<script>` right after that element's closing tag, and I think that would *probably maybe* work.

> How would you suggest to enhance all block rules with that functionality?
> What syntax would you suggest to add optional string parameter to block rules (mainly headings/paragraphs)?

There is a more foolproof solution for this:

https://github.com/markdown-it/markdown-it-container

You can make a syntax like:

```
~~~~~ Any ScrollTriggers Arguments Here
## heading
~~~~~
```

So you don't override heading itself, but instead nest it inside another markdown token. Then merge such tokens in one in a separate `rule_core` rule as post-processing.
