### ISSUE TITLE
Tables not being parsed?

### ISSUE THREAD

**Issue by RamonBalthazar** [markdown-it/markdown-it#825]
Hello, it seems that tables are being parsed incorrectly.

I'm using [this markdown file](https://github.com/mui-org/material-ui/blob/39dcf9bbf6c7877ef384e325ed82402ac5f3e6d8/SECURITY.md) to test. And this is what I get when I render to HTML:

> ![image](https://user-images.githubusercontent.com/4910678/142901908-42c57d87-68e6-4047-95c8-3fbc117cfa1a.png)

Is this expected?

-----

The code I'm using:

```javascript
import MarkdownIt from 'markdown-it';

...

const markdownItInstance = new MarkdownIt('commonmark', { html: true });
const htmlString = markdownItInstance.render(markdownString);
```

Using `markdown-it@12.2.0`

-----

**Update:** I "fixed" this by explicitly using the `markdown-it-table` plugin. But I'm not sure this is a fix since `markdown-it`'s readme says that table parsing is already embedded.

**Comment by puzrin** [comment]
https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%23%20Security%20Policy%5Cn%5Cn%23%23%20Supported%20Versions%5Cn%5CnThe%20versions%20of%20the%20project%20that%20are%20currently%20supported%20with%20security%20updates.%5Cn%5Cn%7C%20Version%20%7C%20Supported%20%20%20%20%20%20%20%20%20%20%7C%5Cn%7C%20-------%20%7C%20------------------%20%7C%5Cn%7C%205.x%20%20%20%20%20%7C%20%3Awhite_check_mark%3A%20%7C%5Cn%7C%204.x%20%20%20%20%20%7C%20%3Awhite_check_mark%3A%20%7C%5Cn%7C%20%3C%204.0%20%20%20%7C%20%3Ax%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%5Cn%5Cn%23%23%20Reporting%20a%20Vulnerability%5Cn%5CnYou%20can%20report%20a%20vulnerability%20by%20contacting%20us%20via%20email%20at%20%5Bsecurity%40mui.com%5D%28mailto%3Asecurity%40mui.com%29.%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

Please use online demo to provide examples. I see nothing wrong.

**Comment by RamonBalthazar** [comment]
Rude and unhelpful, but thanks.

**Comment by puzrin** [comment]
If you have default permission to post here, that does not mean any kind of your posts are welcome.

**Comment by sawhney17** [comment]
@RamonBalthazar, i read that used the markdown-tables-plugin. How did you do this? I believe you are doing this in a web environment due to using an import statement but I can't figure out how to import a plugin using `import` rather than a `require`

**Comment by ddrpa** [comment]
Having a glance at [commonmark spec](https://spec.commonmark.org/0.30/), I don't think it support table-extensions. You can check it in `node_modules/markdown-it/lib/presets/commonmark.js` or try it on [markdown-it demo](https://markdown-it.github.io/) with _CommonMark strict_ checked.

Use `presetName: 'default'` instead.
