### ISSUE TITLE
Wrong render for kind of this string like 'ssssss.se'.

### ISSUE THREAD

**Issue by ricenoddle** [markdown-it/markdown-it#826]
Demo link:
https://markdown-it.github.io/ 

Error Screenshot:
![image](https://user-images.githubusercontent.com/13479751/143677451-099d10bd-1b14-4fd0-8289-12f7da5280f2.png)

Description:
So in this situation, this string 'ssssss.se' should be rendered as a normal <p>sssss.se</p>, but it turns out <p><a href="sssss.se">sssss.se</a></p>

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/index.js#L291 change linkifier options as you need (disable fuzzy links)
