### ISSUE TITLE
How to wrap output in container?

### ISSUE THREAD

**Issue by SNDST00M** [markdown-it/markdown-it#827]
I want to write a plugin that will wrap all `markdown-it` output in a custom container.
The use case is for https://github.com/mjbvz/vscode-github-markdown-preview-style/pull/70.

e.g.

```js
const md = require('markdown-it')();
let result = md.render('# markdown-it rulezz!');
```

Before:
```html
<h2>markdown-it rulezz!</h2>
```

After:
```html
<div class="dark-theme">
<h2>markdown-it rulezz!</h2>
</div>
```

**Comment by puzrin** [comment]
```js
const md = require('markdown-it')();
let result = '<div class="dark-theme">' + md.render('# markdown-it rulezz!') + '</div>';
```

I'm not sure you need plugin for that.

**Comment by SNDST00M** [comment]
I do because it's the `vscode` repo and they refuse to add any kind of modification like this.

**Comment by puzrin** [comment]
Hm... then 2 alternatives:

1. Create plugin to override `.render()` https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.js#L321 to add html before/after result.
2. Create plugin to stay on the end of `core` chain, and inject raw `html block` tokens with content you need https://github.com/markdown-it/markdown-it/blob/master/lib/rules_block/html_block.js.

Basics about plugins are in doc folder https://github.com/markdown-it/markdown-it/tree/master/docs

**Comment by SilvaQ** [comment]
@SNDST00M 
Below is the code I used in vscode plugin, hope to help you：

```javascript
function somePlugin(md){
  md.renderer.backuprender = md.renderer.render;
    md.renderer.render = function (tokens, options, env) {
      const result = md.renderer.backuprender(tokens, options, env);
      return `<div class="shirkhan-markdown-body">${result}</div>`;
    };
    return md;
  }
```

**Comment by SNDST00M** [comment]
I discovered `contributes['markdown.previewScripts']` in vscode API which allows for script injection.

 Don't need to do this but y'know:

```typescript
md.core.ruler.push('bierner-container', function(state) {
    const tokens = state.tokens;
    const containerOpen = new state.Token('block', 'div', 1);
    containerOpen.attrSet('class', 'bierner-content bierner-dark');
    containerOpen.attrSet('itemprop', 'text');
    tokens.unshift(containerOpen);
    const containerClose = new state.Token('block', 'div', -1);
    tokens.push(containerClose);
});
```

**Comment by puzrin** [comment]
Do you still need my help & this issue open?

**Comment by SNDST00M** [comment]
I've solved my problem but will other users be able to comment if it's closed?

**Comment by puzrin** [comment]
Yes, they will. This work different. Tracker is for concrete issues, with realistic deadlines, and about this package only. Open issue ~ "someone of core team should spend personal time [for free]" :).
