### ISSUE TITLE
Strip markdown for html title tag

### ISSUE THREAD

**Issue by ghisleouf** [markdown-it/markdown-it#828]
Hi there !

Got a question for a specific use case.
Let's say that our CMS contributor can edit a page title with Markdown, for example :
` My super title with CO~2~`

Since we are using your super library (and extensions installed), it works fine into HTML page body and my title is super clean, rendered with HTML.

Now, I want to re-use my contributor work and print it into `<html> <head><title>My super title with CO~2~</title>` 

Currently, if i render it inline, I have `My super title with CO<sub>2</sub>` printed out into my browser tab, or if I don't use renderInline method I have `My super title with CO~2~` printed out.

Is there a way to render it properly or ... striping markdown from this title to have, at least,  `My super title with CO2` rendered ?

Thanks a lot for your help and your amazing work !

**Comment by rlidwka** [comment]
You want to transform `My super title with CO~2~` into `My super title with CO~2~`? Unless I don't understand something, you don't need any markdown renderer for that, you could just copy input to the output.

As for stripping markdown characters, one can write a plugin that removes all tokens except `inline`, and all tokens except `text` inside `inline.children`. It's relatively easy to do, I can explain how, but I don't know why it can be useful.

**Comment by ghisleouf** [comment]
Sorry,

Maybe my explanation is not clear.

My database is storing `CO~2–` 
I want to display it properly into my <title> tag : CO<sub>2</sub>

Using render() method, it transform into this escaped string `CO<sub>2</sub>`  and this is what the visitor can see into its browser tab.

I would like to display it properly for the visitors (eg CO<sub>2</sub>) or striping markdown caracters  to display at least `CO2`

Hope it's a little bit clearer !

Thanks for your answer.

**Comment by ghisleouf** [comment]
Hi @puzrin ,

Quite complicated to provide a full working example it's also related to  your browser and the <title> tag of your web page.
I already using markdown-it-sub which works super fine but, i'm going to try to explain again:

Let suppose I retrieve this string from my database : `This is CO~2~`

If I use  `md.renderInline('This is CO~2~');` , I perfectly retrieve `This is CO<sub>2</sub>`which is perfect to inject in my page body :

![image](https://user-images.githubusercontent.com/1439092/145887765-dcfc39d5-ae45-4099-8e60-b14a8b323586.png)

But now, let's move to `<title>` tag into head of the page.  This tag should not contain child node and here is the escaped result :

![image](https://user-images.githubusercontent.com/1439092/145888679-8a04b60f-da14-4b3d-848e-eb951829df5d.png)

As you can see, it's not correct and my question is ... "Do you think that I can handle this use-case ?"

**Comment by puzrin** [comment]
@ghisleouf IMO your question is not about this package. If you wish to restrict HTML (drop some tags from `<title>`-s inner) - there are lot of sanitizers available, or you can create your one with [cheerio](https://github.com/cheeriojs/cheerio) and so on.

**Comment by ghisleouf** [comment]
Anyway, I think it is not related to sanitizying with but a specific use case here where markdon rendering does not work.
I will try to create an example if I have some time because doing something like `$md.renderInline(text).replace(/(<([^>]+)>)/gi, "")`which strips html tags introduces another issue that you can see in my previous screenshot ... the `&amp;` html entities rendered.
