### ISSUE TITLE
GFM

### ISSUE THREAD

**Issue by ivan-kleshnin** [markdown-it/markdown-it#83]
The most idiotic design decision in markdown is treating offsets (tabs, spaces) as code block markers. It makes markdown basically incompatible with HTML (where offsets are, hmm, more than common). I'm not aware of any markdown parser that would support markdown syntax inside nested HTML tags. This is a breaker.

Github coined better syntax **\`\`\`language ... \`\`\`** which serves greatly for inlining PL snippets.
But than offset-based syntax should be disabled by some flag at least.

Thats' only one fundamental thing which https://github.com/chjj/marked lacks but that's enough to turn me off Marked. Refer to https://github.com/chjj/marked/issues/488

What do you guys think about it?

**Comment by jeffmcneill** [comment]
Spaces are also used for indenting ordered lists and unordered lists. This is a key part of the plain text visual representation when editing markdown (it appears "like" indented lists). I think this usage is important to maintain, though I see your point as four spaces don't mean anything in HTML and are generally stripped to a single space. This is more of a weakness in HTML, though.

**Comment by puzrin** [comment]
Syntax issues should be discussed at commonmark forum. This repo is about implementation. Any separate syntax part can be disabled or replaced. I see no point to discuss here.

**Comment by vyp** [comment]
Not the right place as puzrin says, here is the link he is referring to: http://talk.commonmark.org/

**Comment by ivan-kleshnin** [comment]
Not sure I want to argue about such things. I'm getting scared of people who use Markdown in it's current broken state and never complain... Perpahs it's easier to just fork **Marked** and remove indentation handling as I need this for personal project.

**Comment by vyp** [comment]
Note that anyone can just come there and open a new topic on anything. I would be extremely surprised if emojis officially become part of the spec, because it just misses the *point* of markdown entirely, in my opinion.

Either way, this is an issue tracker for markdown-it, not CommonMark, so any further discussion here would be spam. Open a topic there (assuming you want CommonMark to consider this), because otherwise the only other option you have is to scratch your own 'itch' or possibly communicate to the marked project about this.

**Comment by rlidwka** [comment]
> But than offset-based syntax should be disabled by some flag at least.

Well you can disable it already:

```js
var mdit = require('markdown-it')()
console.log(mdit.render("\n      this is a code block\n"))

mdit.disable('code')
console.log(mdit.render("\n      this isn't anymore\n"))

// Outputs:
//
// <pre><code>  this is a code block
// </code></pre>
//
// <p>this isn't anymore</p>
```

**Comment by ivan-kleshnin** [comment]
@rlidwka thank you! This really somehow disables offset code yntax but keeps GFM code syntax. Strange, but that's what I wanted. Can you point me to documentation where this `code` rules is mentioned. I can't find it.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it#manage-rules

In readme & api docs.

**Comment by ivan-kleshnin** [comment]
@puzrin I see there's everythin except `code`. I may be blind but Chrome search fails to find `code` too ;)

**Comment by puzrin** [comment]
Full list of rules available at source code only. That's not for novices, and not included into existing doc to keep it simple.

**Comment by mattbrunetti** [comment]
@vyp emojis are in line with the point of Markdown, since emojis often have precise semantic meaning. (assuming we both agree the point of Markdown is to take style/presentation out of the format and focus on content/meaning) food for thought

**Comment by vyp** [comment]
@mattbrunetti yeah past me was weird. I don't see anything wrong with emojis or how it even relates to markdown, and I completely agree with you. (For example [a comment](https://github.com/NixOS/nix/issues/779#issuecomment-326860803) of mine a few days ago.) Maybe I meant the GFM `:` syntax for inserting emojis though. (But then on GitHub that doesn't even insert emojis, it just inserts pictures representing emojis or something. 🤷)
