### ISSUE TITLE
Inconsistent list rendering

### ISSUE THREAD

**Issue by fabiospampinato** [markdown-it/markdown-it#830]
The following Markdown:

```markdown
1. asd
   1. asd

---

1. asd
	1. asd

---

1. asd
   2. asd

---

1. asd
	2. asd
```

Generates [this](https://markdown-it.github.io/#md3=%7B%22source%22%3A%221.%20asd%5Cn%20%20%201.%20asd%5Cn%5Cn---%5Cn%5Cn1.%20asd%5Cn%5Ct1.%20asd%5Cn%5Cn---%5Cn%5Cn1.%20asd%5Cn%20%20%202.%20asd%5Cn%5Cn---%5Cn%5Cn1.%20asd%5Cn%5Ct2.%20asd%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Atrue%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Atrue%2C%22_view%22%3A%22html%22%7D%7D) in markdown-it, in commonmark-strict mode:

<img width="216" alt="Screen Shot 2021-12-15 at 23 13 08" src="https://user-images.githubusercontent.com/1812093/146273123-45069941-be57-4b69-b65e-c651ce5e6050.png">

While commonmark.js generates [this](https://spec.commonmark.org/dingus/?text=%0A1.%20asd%0A%20%20%201.%20asd%0A%0A---%0A%0A1.%20asd%0A%091.%20asd%0A%0A---%0A%0A1.%20asd%0A%20%20%202.%20asd%0A%0A---%0A%0A1.%20asd%0A%092.%20asd%0A):

<img width="173" alt="Screen Shot 2021-12-15 at 23 13 54" src="https://user-images.githubusercontent.com/1812093/146273196-52907917-e67a-4f56-b8ab-8145e4dcbfe0.png">

So there seems to be some slightly differences there.

**Comment by puzrin** [comment]
Difference is certainly not nice. But in this case i can't say immediately, is this bug of markdown-it or of reference commonmark implementation (not sure what spec says).

If you have time, could you ask @jgm in commonmark tracker, how your last case is expected to work (according to spec)? Anyway, i think they can wish to add this case into spec. We test all spec samples and fix any deviations ASAP. Also we track pathological tests of `commonmark.js`.

**Comment by jgm** [comment]
See section 5.3 of the spec:

> In order to solve [the problem of] of unwanted lists in paragraphs with hard-wrapped numerals, we allow only lists starting with 1 to interrupt paragraphs.

This means that you can't have a sublist beginning with `2.` unless you leave a blank line.  (markdown-it is therefore not in compliance with this rule in the fourth case.)

**Comment by rlidwka** [comment]
Fixed, thanks for reporting (parser incorrectly calculated tab width for that particular case).
