### ISSUE TITLE
Avoiding using Token.prototype.* methods internally

### ISSUE THREAD

**Issue by fabiospampinato** [markdown-it/markdown-it#831]
There are some convenience methods attached to `Token.prototype`, which can be problematic if they are used by markdown-it itself. For my use case I'm passing tokens back and forth from a worker, since I'm trying to move markdown-it to a worker for performance, but the problem is that whenever tokens cross the boundaries of the thread they got created in they are cloned as plain objects basically, their `Token.prototype` is lost, so then when markdown-it assumes those methods are there and tries to use them it throws.

Currently it seems only `Token.prototype.attrIndex` is used internally, and only twice, the minimal fix for this would be to replace `token.attrIndex` with something like `Token.prototype.attrIndex.call ( token`. It looks weird, but that doesn't have this problem.

**Comment by puzrin** [comment]
IMO for data transfer you need serialize/unserialise methods. Or, you could re-pin prototype back.

I can understand your problem, but i don't like suggestion. Could you provide sample of your code (how do you intend to use WW)? May be, we could invent something better.

**Comment by fabiospampinato** [comment]
Those prototypes can't really be serialized and reattaching the prototype back inside the worker for each token is expensive, changing the prototype at runtime for an object is already a performance cliff in some cases I think.

I can't provide snippets of code as there's nothing I can cleanly extract from the files I'm using markdown-it in, but basically I'm doing the following: markdown string input -> send it to worker for parsing -> send parsed tokens back to main thread -> use parsed tokens for various things -> send tokens to worker for rendering -> send rendered html back to main thread.

The problematic uses of `Token.prototype.*` methods are all in code related to rendering, so potentially I could send the main thread the parsed token _and_ the serialized string in one go, but my setup is kind of complicated, I'm doing incremental tokenization in some cases, so the main thread often asks the worker thread to parse only a few edited lines, it then tried to patch the previous tokens to account for the new tokens of the edited lines, it then sends the patched tokens back to the worker thread. Moving the code that does the patching to the worker too would be troublesome as I'm using various dependencies for that, currently the web worker contains almost only markdown-it and a few plugins and I'd like to keep it that way.

Another option may be to define all the `Token.prototype.*` methods as standalone functions, and then calling those functions from the prototype methods and calling the functions directly in the rest of the codebase.

Personally I just patched my fork of markdown-it with the previous suggestion I made, since I'm already running a fork anyway.

I can't think of a less ugly solution, and admittedly most people using markdown-it aren't probably running into this problem because they are either not using workers at all or they don't need the complicated back and forth that I need. 

Still it is a problem in some cases, I don't know if it's worth fixing here though, your call.

**Comment by fabiospampinato** [comment]
I've taken a closer look at the performance implications of this and just sending all the tokens back and forth for a big document is about 100x slower than performing the actual incremental tokenization 🥲 So moving markdown-it to a worker, or at least sending tokens out of the current thread, just makes performance worse overall. Perhaps if tokens were encoded as array buffers or something, somehow, then it could be worth it, or perhaps this is still worth it if I can move all the code that needs the raw tokens to the same worker too, in any case if tokens don't leave the worker than this is no longer an issue.

I'm closing as I'm no longer interested in this, unfortunately.

**Comment by fabiospampinato** [comment]
Potentially the code doing the rendering could be moved to the main thread, removing the need for my use case to send tokens back to the worker, but cloning tokens and generating them in the first place seem to take about the same amount of time, so there probably isn't any point in offloading the parsing to a worker when you're going to pay the same price just to receive the tokens from the worker.

**Comment by puzrin** [comment]
The most obvious would be to send txt to worker and receive html back keeping all package internals in the same context/thread.
