### ISSUE TITLE
Indent markdown code snippet

### ISSUE THREAD

**Issue by asifkabani** [markdown-it/markdown-it#836]
Currently if I add some code block as such:

```
<html>
<body>
<h1 className="city"><span style="background-color: red;">Hello World</span></h1>
</body>
</html>
```
it does not format the indentions. Is there a way to do this or any idea on how to achieve this?
Wanting the result to be something like this:

```
<html>
  <body>
    <h1 className="city">
      <span style="background-color: red;">Hello World</span>
    </h1>
  </body>
</html>
```

**Comment by puzrin** [comment]
You could indent your code before insert. This does not seems to be related to this package anyhow.
