### ISSUE TITLE
Tables, backquotes and code is not rendering in my nuxt project

### ISSUE THREAD

**Issue by km2442** [markdown-it/markdown-it#837]
Hello, I'm trying to implement default example markdown from `markdown-it` in my nuxt project with vuetify, and `table`, `backquotes` and `code` is not rendering entirely

my markdown plugin:
``` js
let emoji = require('markdown-it-emoji');

let md = require('markdown-it')({
  linkify: true,
  breaks: true,
  typographer: true,
  html: false,
})
  .use(emoji);

export default function ({}, inject) {
  inject('md', md);
} 
```
I'm rendering my markdown through:
```
<v-card-text>
  <div v-html="$md.render(config.donateText)"></div>
</v-card-text>
```

and i'm getting such html
![screencapture-localhost-3000-donate-2021-12-31-15_36_39](https://user-images.githubusercontent.com/20816660/147828891-8bed6213-a678-4398-bdba-2f21ae1b2380.png)

is there any way how can I debug and fix it? I cant find anything related in internet...
Thank you

**Comment by puzrin** [comment]
Sorry, that's not related to this package, can't help with generic programming questions.
