### ISSUE TITLE
Multiple plugins syntax, sorry, a bounce from gitter

### ISSUE THREAD

**Issue by alanfluff** [markdown-it/markdown-it#838]
Hi,

Sorry, this is a bounce from a [gitter](https://gitter.im/markdown-it/markdown-it?at=61c4a0d72a210c38c194bd8b) question.

I'm sure the correct place to have asked that was Gitter, and I should wait longer for an answer there, but I just found another plugin I would like to "chain in" (previously abbr and now footnote too) to Markdown-it.

I hope my Gitter question is self-explanatory and thank you in advance if you know what syntax I need to use; per that Gitter question, in pseudo code I want to do this:

```
var md = window.markdownit({
html:         true,
xhtmlOut:     true,
linkify:      true
}).use(classy).alsoUse(abbr).alsoUse(footnote)
```
Thanks in advance for any help.

Cheers

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it#plugins-load

`.use()` is already chain-able.

**Comment by alanfluff** [comment]
dOH o_O  sorry @puzrin, I'm sorry I missed that. Thank you.
