### ISSUE TITLE
What is `pos` and `posMax` in state?

### ISSUE THREAD

**Issue by julianlam** [markdown-it/markdown-it#84]
Trying to add a new rule into the parser where inline links are converted to a video player element.

I added a new rule by calling `parser.inline.ruler.before('link', 'myRule', function() { ... });`, and also added a new rule to the renderer.

What I am confused with is the inline rule, which is passed `state`. What is `pos` and `posMax`? From context, it seems like it is the current position of the parser, but I don't know how its values are derived, and what I should set it to at the end.

For example, given the raw input `www.youtube.com/watch?v=vHZLCahai4Q`, `pos` is 23, and `posMax` is 35. I want to replace the entire link with the video player element, but so far, if I do not modify `pos` or `posMax` at all, then the video player element just gets dropped in between `v` and `=`.

I'm sure it's just a matter of figuring out what the number is supposed to be, but right now I can't seem to grok it...

Any light you can shed on this would be helpful :smile:

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/state_inline.js#L14-L15

pos is current cursor position, posmax - total string length. Each rule increase pos on sucess (except "validation mode").

I'm not sure that understand what you are doing. The most simple solution would be to leave inline parser intact and replace tokens later in core chain.

**Comment by julianlam** [comment]
Hi @puzrin -- thanks for the reply.

> Each rule increase pos on sucess

So the rules work on a character by character basis?

If so, I do not understand why after adding my Ruler, when I `console.log(state);`, `pos` is 23 and `posMax` is 35. I do not understand the calculation behind these numbers, so I cannot predict what they should be set to once I am done my transformation.

> I'm not sure that understand what you are doing. The most simple solution would be to leave inline parser intact and replace tokens later in core chain.

To put it simply: Turn a link into an iframe. If I were to replace the tokens later in the core chain, I can listen for `link_open` and replace the HTML accordingly, yes, but I do not know how to deal with the two tokens immediately succeeding the matched token: `text` and `link_close`. But you are right, that would be easier for me to work with.

Because I did not know how to deal with the trio of tokens (link_open, text, link_close), I chose to try introducing my own Ruler object, which worked alright (the `iframe` element gets added), but I cannot control where it gets added.

**Comment by puzrin** [comment]
@julianlam , it's very difficult to explain how parser works in couple of words, and reply about code that i don't see. In general - try to investigate existing rules, and ask question if you don't understand something.

> but I do not know how to deal with the two tokens immediately succeeding the matched token: text and link_close

That's just elements of array. You can combine new array, and reassign it to core.state. See sources of linkify https://github.com/markdown-it/markdown-it/tree/master/lib/rules_core, it does something similar (insert new elements).

If you know `token_open`, you can seek `token close` by moving forward and checking until `token.level` became the same.

**Comment by digitalmoksha** [comment]
@julianlam  you might also check out the [markdown-it-video plugin](https://github.com/brianjgeiger/markdown-it-video).  It might do exactly what you need, or at least give you some ideas along the same path.

There is a list of several of these types of plugins at https://www.npmjs.com/browse/keyword/markdown-it-plugin
