### ISSUE TITLE
Postpone escape info drop

### ISSUE THREAD

**Issue by puzrin** [markdown-it/markdown-it#840]
**Problem:**

We loose escaping info in parser too early.

- Most of plugins really needs unescaped result for easy text processing (we should NOT pass escape info to renderer input).
- Some plugins like https://github.com/markdown-it/markdown-it-emoji still needs escaping info.

**Possible solution**

1. Push `EscapedChar` OR [`Text` with "escaped start" flag] tokens into stream
2. Add one more stage, "collapse escapes" AFTER `text_collapse` handler.

In theory, this should provide both "unescaped" and "escaped" states for any plugin requirements. Also, this should keep good compatibility with existing plugins (i can't imagine who may wish to sit exactly after "text-collapse", instead end of chain).

But this is very preliminary, need more investigation.

**Comment by puzrin** [comment]
UPD.

https://data.stackexchange.com/ - can be used for SQL search of links, ending with `-/+/_/~`.

**Comment by moki** [comment]
@puzrin Hello, Vitaliy.

Is it possible to disable escaping entirely?

**Comment by puzrin** [comment]
https://meta.discourse.org/t/links-with-multiple-dots-aren-t-linking-right/220781 one more test case to check

**Comment by puzrin** [comment]
Done in upcoming v13
