### ISSUE TITLE
Vulnerability while using links in markdown

### ISSUE THREAD

**Issue by SoulNinja-dev** [markdown-it/markdown-it#841]
`![image](https://grabify.link/CENSORED)`

for the above markdown the generated HTML by markdown-it looks like this
```html
<p><img src="https://grabify.link/CENSORED" alt="image"></p>
```
this loads automatically, logging the IP in grabify.

I think there should some regex to remove these type of links in the parser.

**Comment by puzrin** [comment]
I think, it's more appropriate to report you problem to w3c and suggest to drop images support from html spec.
