### ISSUE TITLE
How to enable HTML tags in source?

### ISSUE THREAD

**Issue by sujalgoel** [markdown-it/markdown-it#842]
I want to know, how can I enable HTML tags in Markdown in browsers in HTML5 and JavaScript.

**Comment by NaincyKumariKnoldus** [comment]
Hello @sujalgoel Can I do this?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it#init-with-presets-and-options

Please read docs.

**Comment by sujalgoel** [comment]
but that's for NodeJS, isn't it?
