### ISSUE TITLE
Bad escaping with incorrect HTML.

### ISSUE THREAD

**Issue by TazmanianDI** [markdown-it/markdown-it#846]
We just starting using this library and we immediately had a customer report that their HTML links are no longer rendering correctly. It turns out that they have `target` attribute on their HTML but they are missing spaces before them. I believe that is technically not allowed by the spec but browsers render the link just fine anyway. Unfortunately markdown-it seems to be parsing it pretty poorly and escaping part of the tags resulting in HTML that really does not render correctly.

Input:
```
<a href="x"target="_blank">Click</a>
```

Output:
```
<p>&lt;a href=&quot;x&quot;target=&quot;_blank&quot;&gt;Click</a></p>
```

As you can see, it escaped the `<a>` part but not the `</a>` part and has pretty much mangled the link.

Instead of 
![image](https://user-images.githubusercontent.com/25828402/150569873-5e3edf9a-0635-429d-bfda-9ceb98c60ddc.png)
You get
![image](https://user-images.githubusercontent.com/25828402/150570030-dba6e881-e816-4ee9-96ea-4921d72a2060.png)

This is arguably not a bug with this library since the input HTML is not spec compliant. It does however render fine it browsers and ideally this library would just leave the HTML alone and not modify or escape it.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it#init-with-presets-and-options html tags disabled by default for security reasons.

**Comment by TazmanianDI** [comment]
@puzrin Sorry if I wasn't clear but I we have HTML tags enabled. The issue isn't that HTML tags don't work and are getting escaped but that only this this specific case where there is a missing space before an attribute does it render incorrectly and it's not completely escape. I've updated the description with some additional details.

**Comment by puzrin** [comment]
https://spec.commonmark.org/dingus/?text=%3Ca%20href%3D%22x%22target%3D%22_blank%22%3EClick%3C%2Fa%3E%0A%0A%3Ca%20href%3D%22x%22%20target%3D%22_blank%22%3EClick%3C%2Fa%3E%0A

Result is exactly as in reference parser. If you wish to change behaviour, i'd suggest to ask questions in CM trackers first. IMHO it's not good idea to diverge behavior without real need.

**Comment by TazmanianDI** [comment]
Alright, thanks for the followup and the extra details!
