### ISSUE TITLE
Facing issues with plugin development

### ISSUE THREAD

**Issue by iMrDJAi** [markdown-it/markdown-it#847]
Hello, I'm currently porting my plugins to char code scan instead of regex ([markdown-it-regexp](https://github.com/rlidwka/markdown-it-regexp)) to improve performance.

While my custom markdown tag works fine, I'm facing an odd issue, other tags that come after it won't render (except for inline code), emphasis tags cause infinite loops that freeze the browser!

![image](https://user-images.githubusercontent.com/42304709/151618313-7305b7ce-f577-4575-9fcf-6e4617761d81.png)

Nested markup is working fine btw:

![image](https://user-images.githubusercontent.com/42304709/151619311-31d231bc-0078-4fc0-956c-a75140721a03.png)

Not sure what I did wrong, I followed the source code of many rules/plugins and I was able to make it work, but couldn't find out what causes this issue. Here is my code anyway:

```js
function spoiler(md) {
    const exMark = 0x21 /* ! */
    const gtSign = 0x3E /* > */
    const ltSign = 0x3C /* < */

    md.inline.ruler.after('emphasis', 'spoiler', (state, silent) => {
        if (silent) return false
        let start = state.pos,
            end = state.posMax - 1,
            found = false
    
        // Check for >!
        if (
            state.src.charCodeAt(start) !== gtSign ||
            state.src.charCodeAt(start + 1) !== exMark
        ) {
            return false
        }
    
        // Find !<
        state.pos = end - 1
        while (state.pos > start + 1) {
            if (
                state.src.charCodeAt(state.pos) === exMark &&
                state.src.charCodeAt(state.pos + 1) === ltSign
            ) {
                found = true
                break
            }
            state.pos -= 1
        }
        
        if (!found) {
            state.pos = start
            return false
        }
    
        state.posMax = state.pos
        state.pos = start + 2
    
        let token = state.push('spoiler_open', 'span', 1)
        token.attrs = [
            ['class', 'md-spoiler']
        ]
        token.markup = '>!'

        // Parse nested markup
        state.md.inline.tokenize(state)
    
        token = state.push('spoiler_close', 'span', -1)
        token.markup = '!<'

        state.pos += 2

        return true
    })
}
```

**Comment by puzrin** [comment]
Sorry, that's too much about low level programming. I can't debug your code. General recommendation is to take plugin with similar markup/nesting behavior and modify start/stop markers rules for your needs.

- https://github.com/markdown-it/markdown-it-mark - that's an example of inline pair-like markup extension (inline + begin/end + allow markup inside).
- https://github.com/markdown-it/markdown-it-container - blocks with nested content.

**Comment by iMrDJAi** [comment]
@puzrin I already checked markdown-it-mark. Just to let you know, this one is based on the emphasis rule, a lot of unnecessary/unclear logic there.

Also, I couldn't find any example where the open/close markers have different characters, the emphasis code is simply not designed to handle this case.

Another rule to look at was the backticks but it doesn't support nested markup, so I had to create my own plugin from scratch, I guess I'll be stuck for some time until I find a solution for this. ¯\\\_(ツ)_/¯

**Comment by puzrin** [comment]
Inline rules with nesting are the most cryptic part. I'd suggest you to start form the root - provide exact description of your tag and how it is expected to work (markup, intersection with other tags and so on). Then, probably, i'll be able to suggest something more concrete.

AFAIK, discourse guys implemented inline bbcodes support. You can take a look there. Or search in npm for bbcode plugins.

**Comment by iMrDJAi** [comment]
@puzrin I finally got it working! My previous code had logic issues, I totally messed it up, I was giving `state.pos` and `state.posMax` wrong values. 🤦‍♂️

However, I started fresh again, this time I used the [link](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/link.js) rule as an entry point, it was easier to understand, I cleaned up all unnecessary logic, then I wrote my own rule on top of it, and this is the result:

```js
function spoiler (md) {
    const exMark = 0x21 /* ! */
    const gtSign = 0x3E /* > */
    const ltSign = 0x3C /* < */

    md.inline.ruler.push('spoiler', (state, silent) => {
        let start,
            end,
            pos = state.pos,
            max = state.posMax,
            tagLen = 2 // Closing tag length
        
        // Check for >!
        if (state.src.charCodeAt(pos) !== gtSign) return false
        pos += 1
        if (state.src.charCodeAt(pos) !== exMark) return false
        pos += 1
        start = pos

        // Find the very last !<
        pos = max - tagLen
        while (pos > start) {
            if (
                state.src.charCodeAt(pos) === exMark &&
                state.src.charCodeAt(pos + 1) === ltSign
            ) {
                end = pos
                break
            }
            pos -= 1
        }
        if (!end) return false

        // Skip the closing tag
        pos = end + tagLen

        // Don't insert any tokens in validation mode
        if (!silent) {
            state.pos = start
            state.posMax = end
            let token = state.push('spoiler_open', 'span', 1)
            token.attrs = [
                ['class', 'md-spoiler']
            ]
            token.markup = '>!'
            state.md.inline.tokenize(state)
            token = state.push('spoiler_close', 'span', -1)
            token.markup = '!<'
        }
      
        state.pos = pos
        state.posMax = max
        return true
    })
}
```
My advice to plugins developers is to avoid assigning values to `state.pos` and `state.posMax` as much as possible, except before tokenizing nested markup, and at the end before `return true`. Always have a separate variable for the cursor, this way you can avoid issues like this.

> provide exact description of your tag and how it is expected to work (markup, intersection with other tags and so on).

I'm copying the spoiler tag from Reddit, the one they use on their redesign <www.reddit.com> since it's rendered differently on the old website <old.reddit.com>, I'm thinking about writing a detailed spec before publishing the plugin.  
And yeah, it has an intersection with the blockquote rule, I already fixed that anyway.

Thank's a lot for your advice!
