### ISSUE TITLE
Leave out javascript blocks unparsed

### ISSUE THREAD

**Issue by vallettea** [markdown-it/markdown-it#85]
Hello,

thanks for this awesome module.
Just one question, how can I say to markdown-it not to parse such a block of my markdown:

```
<div id="tree"></div>
<style>
#tree{
  position: relative;
  left: -300px;

} 
.node circle {
  fill: #fff;
  stroke: #585858;
  stroke-width: 2px;
}

.node text {
  font: 12px sans-serif;
}

</style>
<script>
d3.json("./rapport/tree.json", function(error, treeData) {

 ....
```

**Comment by puzrin** [comment]
http://spec.commonmark.org/0.18/#html-blocks

Remove empty lines in such blocks or use separate wrapper for markdown content

**Comment by vallettea** [comment]
thx
