### ISSUE TITLE
Add option to disable indented code blocks

### ISSUE THREAD

**Issue by xplosionmind** [markdown-it/markdown-it#851]
I have been looking around for quite some time now, and I read a lot of debates but I see no conclusion.

I believe that, if not by disabling it by default, users should be given the choice of **disabling code blocks generated from indentation**. Does markdown-it give a choice? If yes, how?

Thank you very much!

**Comment by puzrin** [comment]
`md.disable('fence')` https://github.com/markdown-it/markdown-it/blob/master/lib/parser_block.js#L17

**Comment by xplosionmind** [comment]
Thank you very very much, @puzrin!

**Comment by xplosionmind** [comment]
Thanks a a lot, again, @puzrin! The problem is that by using `md.disable('fence')`, fenced code blocks are disabled, I would like to disable indented ones, instead!

**Comment by puzrin** [comment]
`md.disable('code')` https://github.com/markdown-it/markdown-it/blob/master/lib/parser_block.js#L16

**Comment by idontknowjava** [comment]
@xplosionmind could you please how were you able to use `md.disable('code')`, am I doing anything wrong here:

```js
var md = require("markdown-it")({
  linkify: true,
  break: true
}).disable(["code", "fence"]);

const str = "`Some text`";
var result = md.render(str);
console.log(result);
```

Current output is `<p><code>Some text</code></p>`
But expected output is `<p>Some text</p>`.

**Comment by xplosionmind** [comment]
I set this up a long time ago by testing some different options, and now it works. I do not remember at all. I suggest you to tweak some stuff and see what comes out of it.

**Comment by jackusay** [comment]
> @xplosionmind could you please how were you able to use `md.disable('code')`, am I doing anything wrong here:
> 
> ```js
> var md = require("markdown-it")({
>   linkify: true,
>   break: true
> }).disable(["code", "fence"]);
> 
> const str = "`Some text`";
> var result = md.render(str);
> console.log(result);
> ```
> 
> Current output is `<p><code>Some text</code></p>` But expected output is `<p>Some text</p>`.

I have same problem...

**Comment by rlidwka** [comment]
`.disable(["code"])` works only for code **blocks**. If you want to disable inline code, it would be `.disable(["backticks"])`.
