### ISSUE TITLE
esm output

### ISSUE THREAD

**Issue by jimmywarting** [markdown-it/markdown-it#852]
would be nice to be able to import the package.
this link isn't really working: https://cdn.jsdelivr.net/npm/markdown-it@12.3.2/index.min.js

**Comment by jimaek** [comment]
Have you tried our ESM mode? https://cdn.jsdelivr.net/npm/markdown-it@12.3.2/+esm

**Comment by paulirwin** [comment]
@jimaek I'm not seeing the ESM build in the npm package, am I missing something? 

When using the following import in an Angular app:

```typescript
import markdownit from 'markdown-it/lib';
```

I get the following warning:
```
Warning: [redacted_file_path] depends on 'markdown-it/lib'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

**Comment by MartinKolarik** [comment]
@paulirwin the ESM build is available at the jsDelivr URL linked above since the original question was about a CDN usage. It is not part of the npm package so if you try to import it locally, that won't work.

**Comment by paulirwin** [comment]
@MartinKolarik Thanks, but I don't use jsDelivr, markdown-it is a transitive dependency through npm for me via prosemirror-markdown. I'll submit a separate issue for ESM output in the npm package.
