### ISSUE TITLE
The strikethrough syntax doesn't follow the GFM spec

### ISSUE THREAD

**Issue by iMrDJAi** [markdown-it/markdown-it#854]
After running the test script against the GFM spec, I found out that markdown-it parses strikethrough tags differently:

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src line: 7716

.
~~Hi~~ Hello, world!
.
<p><del>Hi</del> Hello, world!</p>
.

error:

<p><s>Hi</s> Hello, world!</p>
```

As you can see, markdown-it parses them as `<s>`. However, [GFM](https://github.com/github/cmark-gfm/blob/0.29.0.gfm.3/test/spec.txt#L7710) suggests that they should be parsed as `<del>`.

It is worth noting that tables are also getting parsed differently:

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src line: 3352

.
| abc | defghi |
:-: | -----------:
bar | baz
.
<table>
<thead>
<tr>
<th align="center">abc</th>
<th align="right">defghi</th>
</tr>
</thead>
<tbody>
<tr>
<td align="center">bar</td>
<td align="right">baz</td>
</tr>
</tbody>
</table>
.

error:

<table>
<thead>
<tr>
<th style="text-align:center">abc</th>
<th style="text-align:right">defghi</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center">bar</td>
<td style="text-align:right">baz</td>
</tr>
</tbody>
</table>
```

[GFM](https://github.com/github/cmark-gfm/blob/0.29.0.gfm.3/test/spec.txt#L3309) suggests that table cells alignment should be done by the `align` attribute, markdown-it uses inline style instead. However, the `align` attribute is obsolete and there is some talk about replacing it by inline style (https://github.com/github/cmark-gfm/pull/86).

If you're okay with that, I'll open a pull request to fix the strikethroughs issue.

**Comment by puzrin** [comment]
IMO if anyone wish exact GFM support, https://github.com/npm/marky-markdown will be more suitable.

Strike and table extensions were taken from GFM at the moment of creation (as de-facto standard), and syntax should be the same (while output layon differs by reasons above). But this package is focused on CM + flexibility, not on blind following of every new GFM feature. So, core rules stays intact, and all mods are injected via plugins.

If you wish some concrete actions from our side, please be more specific.

**Comment by iMrDJAi** [comment]
> Strike and table extensions were taken from GFM at the moment of creation

@puzrin If this is the case then, I think it's better to leave it as is, until the GFM spec becomes stable enough (since it's clearly not currently).

> If you wish some concrete actions from our side, please be more specific.

Well, GFM is the second most common flavor of markdown, is very reasonable to request official support for it, but since markdown-it is so flexible, this won't be a big deal for developers.

**Comment by rlidwka** [comment]
a preset like this:

```js
require('markdown-it')('cmark-gfm')
```

would be easy to implement and wouldn't be too out of place imho

**Comment by puzrin** [comment]
@iMrDJAi thank you for understanding. Let's close this issue. But feel free to add new details, issue can be reopened anytime when more reason appears. Or create  a new one.
