### ISSUE TITLE
Doing some modernization?

### ISSUE THREAD

**Issue by jimmywarting** [markdown-it/markdown-it#855]
Would you be open if i created some PR that refactor some things into es6 classes and using some const/let?

**Comment by puzrin** [comment]
It's not a problem to refactor, but everything should have concrete reasons. Could you explain your ones?

**Comment by jimmywarting** [comment]
Just want to learn the in and outs of this package of how it works and starting to contribute to new features eventually.

by using classes instead of prototyping vs code will be able to better understand and give better IDE auto suggestion as well...

**Comment by puzrin** [comment]
Please, understand me right. I don't like to change development process without strong reasons. Things are unified across many repos, and i don't like to spend extra efforts for maintenance without big added value.

**Comment by jimmywarting** [comment]
Ok... no worries.
just thought since you are testing node v12 that it would be fine...

https://github.com/markdown-it/markdown-it/blob/6da01033aa6ea2892e16a44672431fad3aff37b2/.github/workflows/ci.yml#L16

May I ask what targeted browser/node do you support?

if such things as this isn't alright, then i guess it isn't fine to even try to introduce classes, async/await or even function generators that could be part of a streaming approche to even try and introduce some form of `async highlight() { ... }` functionality...

**Comment by puzrin** [comment]
All with es5 support should be ok.
