### ISSUE TITLE
How to enable xhtmlOut from the console?

### ISSUE THREAD

**Issue by ngcdev** [markdown-it/markdown-it#865]
Hello!

First of all, thank you for this great tool! I'm using it to publish MD to HTML that is later uploaded to Confluence.

However, Confluence requires XHTML in their API. For the most part it's fine, but from time to time a file will fail. I examined the code and I noticed that you do have an option (internally) to output XHMTL (xhtmlOut):
```
  md = require('..')({
    html: !options.no_html,
    xhtmlOut: false,
    typographer: options.typographer,
    linkify: options.linkify
  });
```
Since I'm running it from the console ( `$ markdown-it SOME.MD > output.html`) I have not been able to figure out how to pass that parameter. I see that other options are taken from the "options" parameter, which are parsed from the console arguments, but there doesn't seem to be an option for the xhtmlOut.

An I missing something? How can I pass a parameter to output xhtml? I read that the require('..') can be used to load a file, but not sure if that will work here (to create my own js options file) (Sorry, not a node developer)

Thanks for your attention!

**Comment by rlidwka** [comment]
`markdown-it` binary is created mostly for testing purposes and doesn't cover all possible options (presets, plugins, highlighter, etc.)

I would suggest to write custom wrapper and enable exactly what you need.

Something like this would do:

```js
#!/usr/bin/env node

const fs = require('fs')

let md = require('markdown-it')({
  html: false,
  xhtmlOut: true,
  typographer: true,
  linkify: true,
  breaks: false,
  langPrefix: 'lang-',
  // etc.
})

let source = fs.readFileSync('input.txt')
let output = md.render(source.toString())
fs.writeFileSync('output.txt', output)
```

Proposals to add all possible features (something like babel-cli does) are welcome.
