### ISSUE TITLE
`https://` becomes `https:///` and `http://` becomes `/ttp://` when linkify is enabled

### ISSUE THREAD

**Issue by sapphi-red** [markdown-it/markdown-it#868]
```markdown
https://
```
becomes
```html
<p><a href="http://">http://</a>/</p>
```

---

```markdown
http://
```
becomes
```html
<p><a href="/">/</a>ttp://</p>
```

I tested with https://markdown-it.github.io/.

**Comment by puzrin** [comment]
https://markdown-it.github.io/#md3=%7B%22source%22%3A%22https%3A%2F%2F%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

/cc @rlidwka

**Comment by rlidwka** [comment]
Fixed in https://github.com/markdown-it/linkify-it/commit/d03a760854741fec7e14b3507bd2d7d07766f1e3, will be published soon.
