### ISSUE TITLE
Feature to demote headers

### ISSUE THREAD

**Issue by nneil** [markdown-it/markdown-it#871]
I would like headers that use "#" to be treated as if they used "##". I use eleventy to statically generate pages and add a H1 element using the page title. I'd like the rest of the headers to be H2 or below without having to type extra characters.

**Comment by puzrin** [comment]
You can override default renderer for `heading_open` / `heading_close` tokens, with shifted levels.

**Comment by harrislapiroff** [comment]
@puzrin Is it possible to give an example of what this would look like? Or point to some documentation/code to look at? I've done some amount of overriding rules, but I'm struggling to read the code for this particular one. Thank you!

**Comment by xXNickznXx** [comment]
I achieved it by doing so:
```javascript
const md = new MarkdownIt();
const proxy = (tokens, idx, options, env, self) => self.renderToken(tokens, idx, options);
const defaultHeadingOpenRenderer = md.renderer.rules['heading_open'] || proxy;
const defaultHeadingCloseRenderer = md.renderer.rules['heading_close'] || proxy;
const increase = (tokens, idx) => {
  // dont go smaller than 'h6'
  if (parseInt(tokens[idx].tag[1]) < 6) {
    tokens[idx].tag = tokens[idx].tag[0] + (parseInt(tokens[idx].tag[1]) + 1);
  }
};
md.renderer.rules['heading_open'] = function (tokens, idx, options, env, self) {
  increase(tokens, idx);
  return defaultHeadingOpenRenderer(tokens, idx, options, env, self);
};
md.renderer.rules['heading_close'] = function (tokens, idx, options, env, self) {
  increase(tokens, idx);
  return defaultHeadingCloseRenderer(tokens, idx, options, env, self);
};
console.log(md.render('# h1 \n ## h2 \n ### h3 \n #### h4 \n ##### h5 \n ###### h6'));
```

**Comment by mrleblanc101** [comment]
How would I do something similar, but instead completely remove the FIRST `<h1>`.
I use [@mdit-vue/plugin-headers](https://www.npmjs.com/package/@mdit-vue/plugin-headers) to extract the first `<h1>` and render it somewhere else in a custom html page header.
Currently this lead to having two `<h1>` !
