### ISSUE TITLE
Moving from markdown-it 12.x to 13.x is escaping underscores in text urls

### ISSUE THREAD

**Issue by rj-david** [markdown-it/markdown-it#872]
This URL: https://www.youtube.com/watch?v=_wfHcgwejng

is being transformed to https://www.youtube.com/watch?v=\_wfHcgwejng

I cannot replicate it in
- https://markdown-it.github.io/ - online demo of `markdown-it`

But I just upgraded from version 12.x to 13.x, and when looking at the changelog, seems like the issue that I am encountering is related to items fixed here:
```
Smartquotes, typographic replacements and plain text links can now be escaped with backslash (e.g. \(c) or google\.com are no longer replaced).
Fixed collision of emphasis and linkifier (so http://example.org/foo._bar_-_baz is now a single link, not emphasized). Emails and fuzzy links are not affected by this.
```
Can someone help guide me on where to look in this case?

**Comment by puzrin** [comment]
Sorry, can not help with debugging your software. As been noted, a minimal example works as expected:

https://markdown-it.github.io/#md3=%7B%22source%22%3A%22link%20https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D_wfHcgwejng.%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

To spend time for investigations, we need minimal narrowed example, to prove problem is in this package, not outside. Usually online demo is the most optimal way.

If you manage to create required example, let us know.
