### ISSUE TITLE
TextContent does not render properly with HTML options

### ISSUE THREAD

**Issue by MarketingPip** [markdown-it/markdown-it#873]
I have attached a demo of this issue in a Github Page example - first section inserted with a string of text (displays properly) - the second is with textContent < and does not render properly. 

Example of issue here - https://marketingpip.github.io/Markdown/

**Comment by puzrin** [comment]
Please, provide a minimal example via online demo https://markdown-it.github.io/ or test repo. I can not debug your app.

**Comment by MarketingPip** [comment]
@puzrin -

I think it's literally only possible to show my example via a HTML page! Tho the code for the GitHub Page / link I just gave you is here

https://github.com/MarketingPip/Markdown/


https://github.com/MarketingPip/Markdown/blob/main/bug-test.js < as said text in string displays fine!  But when using textContent - it does not! 

Please note as of writing this post - all content under the HTML page is NOT working correctly due to waiting for JSDeliver cache to update...


Thank you as well for the more than fast reply!

**Comment by puzrin** [comment]
This repo is about markdown parser, it accepts strings on input. IMO question about textContent is a bit out of scope. If you insist on problem in this package, you are expected to provide some proof (minimal example with no outer code)

**Comment by MarketingPip** [comment]
Create a HTML document with this 

```
<main></main>


<article><p align="center">
  <img height="400" src="https://imgur.com/oQgTNF3.png" />
</p>

</article>
```



Use this for the Javascript
```


const md = window.markdownit();
md.options.html = true;

document.querySelector('main').innerHTML = md.render(`# This works fine

 
<p align="center">
  <img height="400" src="https://imgur.com/oQgTNF3.png" />
</p>
);

/* ERROR OCCURS HERE */

document.querySelector('article').innerHTML = md.render(article.textContent);


```


And again this same bug is displayed here -  https://marketingpip.github.io/Markdown/

**Comment by puzrin** [comment]
I can not help with generic programming questions, sorry.

**Comment by MarketingPip** [comment]
@puzrin - literally thank you for that answer hahah! :heart:  

Sorry late night here! Can marked this as closed! :)
