### ISSUE TITLE
Are horizontal rules broken?

### ISSUE THREAD

**Issue by MaxterBattle** [markdown-it/markdown-it#874]
I'm looking at your online sample at https://markdown-it.github.io/.  Under the heading __Horizontal Rules__ I see examples in the markdown text that make sense, things like `---`, but these don't seem to be generating the horizontal rules in the output.

**Comment by MaxterBattle** [comment]
Learning more, it looks like the <hr> elements are in the HTML, just not visible when rendered by the browser.

**Comment by puzrin** [comment]
https://markdown-it.github.io/#md3=%7B%22source%22%3A%22foo%5Cn%5Cn---%5Cn%5Cnbar%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

Everything works as expected.
