### ISSUE TITLE
Random comma at end of every md file

### ISSUE THREAD

**Issue by peepopoggers** [markdown-it/markdown-it#876]
When using svelte, in the below snippet, with any file I pass, even empty, I see a comma appended to the end of the markdown element.

Reference:
```html
<script>
    import MarkdownIt from "markdown-it";
    import "highlight.js/styles/an-old-hope.css";

    import highlight from "highlight.js";
    export let markdown = "";

    const md = new MarkdownIt({
    	highlight: function (str, lang) {
    		if (lang && highlight.getLanguage(lang)) {
    			try {
    				return highlight.highlight(lang, str).value;
    			} catch (e) {
    				console.error("Failed to highlight string");
    			}
    		}
    		return "";
    	}
    });

    const rendered = md.render(markdown);
</script>

<div>
  {@html rendered}
</div>
```

I have checked and it is inside the p element that the markdown element has created.

Any help would be appreciated.

**Comment by puzrin** [comment]
Sorry, can not help with generic programming questions, only with specific to markdown-it.

**Comment by peepopoggers** [comment]
This is not a generic programming question. The comma is within the rendered element. How would this even be possible?

**Comment by puzrin** [comment]
This repo is about markdown, not about svelte. It has demo with highlighter, where everything works as expected.
