### ISSUE TITLE
How To Implement Plugin for Indent/Outdent

### ISSUE THREAD

**Issue by volomike** [markdown-it/markdown-it#877]
I noticed that when I do numbered or bullet lists, and I have a paragraph break and type more content below it, sometimes I have a specific need to indent that content to match the indent under a numbered or bulleted list.

How would I go about creating a plugin for that? It's sort of like the `>` for a blockquote, but without the fancy formatting. So for instance, I could put some character sequence before and after the paragraph and it would indent it. And if I repeat that character sequence more than once, it would indent it by that number of character sequence matches. Meanwhile, it would need to ignore this in code blocks because they already look at tabs.

For instance, if a paragraph is not inside a code block, and begins with `:]`, then it gets indented all the way up until the next `\n`. And if it has `::]` that begins the paragraph, it indents twice, and so on.

**Comment by rlidwka** [comment]
Can you provide examples of both markdown input and expected output?

I didn't quite understand what kind of indent is being talked about.

**Comment by puzrin** [comment]
Closing as timed out.
