### ISSUE TITLE
`### attrs.name` is rendered as a link

### ISSUE THREAD

**Issue by Mini-ghost** [markdown-it/markdown-it#878]
I use VitePress to build document, and I have a section title is `### attrs.name` It will be rendered as a link, like bellow:

https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%23%23%23%20attrs.name%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

Any way to resolve this issue?

**Comment by puzrin** [comment]
- You can just disable linkifier
- or disable fuzzy mode only
- or disable `.name` domains linkification in fuzzy mode.

See docs/sources for options.

**Comment by Mini-ghost** [comment]
@puzrin Thank 💚
