### ISSUE TITLE
Bold not rendering correctly in some cases

### ISSUE THREAD

**Issue by rxliuli** [markdown-it/markdown-it#880]
For example, the following text cannot be rendered correctly using markdown-it, but can be rendered using marked. I would like to know how to make it render correctly. Currently, I add a space to each **, but for Chinese, this is very difficult. Hate is also weird.

```md
**真没想到我这么快就要死了，**她有些自暴自弃地想着。
```
github also doesn't render correctly

**真没想到我这么快就要死了，**她有些自暴自弃地想着。

marked can render correctly, refer to:
<https://marked.js.org/demo/?text=**%E7%9C%9F%E6%B2%A1%E6%83%B3%E5%88%B0%E6%88%91%E8%BF%99%E4%B9%88%E5%BF%AB%E5%B0%B1%E8%A6%81%E6%AD%BB%E4%BA%86%EF%BC%8C**%E5%A5%B9%E6%9C%89%E4%BA%9B%E8%87%AA%E6%9A%B4%E8%87%AA%E5%BC%83%E5%9C%B0%E6%83%B3%E7%9D%80%E3%80%82>

**Comment by rxliuli** [comment]
> Please, use CM spec & forum for such questions https://commonmark.org/. This repo is about implementation of CM spec, not about spec discuss.

I've observed that the issue seems to have been discussed with no results. Is it possible for me to handle this via markdown-it plugin?

**Comment by puzrin** [comment]
In theory, you can replace emphasis rule with your custom one. But designing new concept and checking all side effects is not trivial thing.

**Comment by rxliuli** [comment]
Yes, the workaround is to replace `**真没想到我这么快就要死了，**她有些自暴自弃地想着` with `**真没想到我这么快就要死了**，她有些自暴自弃地想着`.  But this is not always possible, e.g. with ?  or !  ending

**Comment by puzrin** [comment]
Please, ask such kind of questions at CM forum https://talk.commonmark.org/. This repo is about spec implementation, not about spec content.

**Comment by rxliuli** [comment]
Another way of thinking, wouldn't it be simpler to remove the space to the right of the `</strong>` closing tag when rendering?

**Comment by rxliuli** [comment]
> Another way of thinking, would it be simpler to implement a plugin that removes the space on the right of `\</strong\>` when rendering?

仅仅作为记录，我实现了 markdown-it 插件来清理

```ts
import MarkdownIt from 'markdown-it'
import Token from 'markdown-it/lib/token'

/**
 * 清理粗体之后的空格
 */
function clearStrongAfterSpace(ends: string[]): MarkdownIt.PluginSimple {
  return (md) => {
    const renderInline = md.renderer.renderInline.bind(md.renderer)
    md.renderer.renderInline = (tokens, options, env) => {
      const checkTokenIndexs = tokens
        .map((token, i) => {
          return {
            p:
              token.type === 'strong_close' &&
              ends.some((end) => tokens[i - 1].content.endsWith(end)) &&
              i + 1 < tokens.length &&
              tokens[i + 1].type === 'text',
            i: i + 1,
          }
        })
        .filter((item) => item.p)
        .map((item) => item.i)
      const newTokens: Token[] = tokens.map((token, i) => {
        if (!checkTokenIndexs.includes(i)) {
          return token
        }
        return {
          ...token,
          content: token.content.trimStart(),
        } as Token
      })
      return renderInline(newTokens, options, env)
    }
  }
}

const md = new MarkdownIt()
md.use(clearStrongAfterSpace(['！', '？', '，']))
console.log(md.render('**真没想到我这么快就要死了** ，她有些自暴自弃地想着'))
console.log(md.render('**我们不需要战术，** 外星人好像是在这么说'))
```

**Comment by luckymore** [comment]
@rxliuli Actually Only very old markedjs versions can parse it
<img width="1021" alt="image" src="https://github.com/markdown-it/markdown-it/assets/5390013/0c369856-ba96-42e4-9dff-9eab988c3735">

I had the same problem and was able to solve it with `<b></b>`

**Comment by tats-u** [comment]
Hotfix plugin has been released: https://www.npmjs.com/package/markdown-it-cjk-friendly
