### ISSUE TITLE
Default empty alt tag on images causes browsers to not show broken image icon

### ISSUE THREAD

**Issue by mjbvz** [markdown-it/markdown-it#885]
## Setup

1. Create a reference to an image that does not exist: `![](nosuch)`

## Bug

When this image is rendered in browsers, they show nothing instead of the typical broken image icon

This is caused by the image having an empty `alt` attribute. `[](nosuch)` is rendered as `<img src="nosuch" alt=""`

[This demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22Bad%20!%5B%5D%28nosuch%29%5Cn%5CnGood%20!%5Balt%5D%28nosuch%29%5Cn%5CnGood%20%3Cimg%20src%3D%5C%22nosuch%5C%22%3E%5Cn%5CnBad%20%3Cimg%20alt%20src%3D%5C%22nosuch%5C%22%3E%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D) demonstrates the problem:

```
Bad ![](nosuch)

Good ![alt](nosuch)

Good <img src="nosuch">

Bad <img alt src="nosuch">
```

Renders as:

![Screen Shot 2022-08-04 at 12 02 43 PM](https://user-images.githubusercontent.com/12821956/182932559-86b12067-4388-457b-8874-376b34c3cb6a.png)

[According to mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img):

> Setting this attribute to an empty string (alt="") indicates that this image is not a key part of the content (it's decoration or a tracking pixel), and that non-visual browsers may omit it from rendering.

I believe it's more likely the user did mean to include the image and simply forgot the `alt`

**Comment by mjbvz** [comment]
I haven't been able to work around this either unless I fully replace the default image renderer

It does also happen [on the common mark dingus](https://spec.commonmark.org/dingus/?text=Bad%20!%5B%5D(nosuch)%0A%0AGood%20!%5Balt%5D(nosuch)%0A%0AGood%20%3Cimg%20src%3D%22nosuch%22%3E%0A%0ABad%20%3Cimg%20alt%20src%3D%22nosuch%22%3E) but I can't find where in the common mark spec is says that the `alt` tag should always be added

---

My proposal is to omit the `alt` tag when no alt text is provided. However that does mean that there'd be no way to create an image using `alt=""` in markdown syntax if that's what you really want to do

**Comment by rlidwka** [comment]
> but I can't find where in the common mark spec is says that the alt tag should always be added

there are tests for it, e.g. spec example 580:
https://spec.commonmark.org/0.30/#example-580

I suggest to reopen this issue there:
https://github.com/commonmark/commonmark-spec

*it's not feasible to change the output of markdown-it specifically for this particular case, making those tests fail, and then try to figure out how to make them pass again*

**Comment by mjbvz** [comment]
Thanks! I opened https://github.com/commonmark/commonmark-spec/issues/718 to continue the discussion
