### ISSUE TITLE
How to access token list and render without parsing twice?

### ISSUE THREAD

**Issue by flaviotordini** [markdown-it/markdown-it#886]
I need to access the token list to get a list of headings, the markdown title and maybe other things in the future. I also want to render to HTML. Currently I have to parse and then render (which parses again). Is there a way to first parse and then use the parsed tokens to render?

**Comment by rlidwka** [comment]
```js
md.renderer.render(tokens, md.options, {});
```

**Comment by flaviotordini** [comment]
Thanks! It didn't occur to me to look in the Renderer class.
