### ISSUE TITLE
Code captions and labels

### ISSUE THREAD

**Issue by tonqa** [markdown-it/markdown-it#890]
I have a lot of fenced code blocks on my website. I need to add captions and labels for these fenced code blocks. Though I know there could be a plugin, I rather think this should be a core feature to add captions and labels like this:

    ```c,caption=My first C program,label=cprogram
    LOC
    ```

Or like that:

    ```c {caption: "My first C program", label: "cprogram"}
    LOC
    ```

In Pandoc you can do it like this:

    ~~~ { .bash caption="A git commit"}
    git commit file1.txt --message="A commit message"
    ~~~

Please see, that a lot of people need this not only for figures but also for Code blocks. I hope you see this as well.

**Comment by rlidwka** [comment]
There is a popular plugin for this, that's been in development for years:
https://www.npmjs.com/package/markdown-it-attrs

> I rather think this should be a core feature

Core feature of markdown-it is an ability for you to write plugins like this *(including everything in the main package is rather impractical, as every user will have to download all of it)*.

**Comment by tonqa** [comment]
Thanks @rlidwka for pointing that out. I missed that one.

Though it's interesting that it's not part of the core features and markdown does not develop further. I guess a proper markup is only complete with such syntactic elements as it should provide enough means of expression.

I close this one.
