### ISSUE TITLE
How to support strikethrough syntax in commonmark mode

### ISSUE THREAD

**Issue by duhaime** [markdown-it/markdown-it#892]
Hello and thanks for this great library. We are using `markdown-it` to render commonmark documents, and just recently noticed that strikethrough syntax is not transformed properly:

```
import MarkdownIt from "markdown-it";

var a = new MarkdownIt();
var b = new MarkdownIt("commonmark");

var s = "~~okay~~";

document.write(a.render(s));
document.write(b.render(s));
```

The first has the strikethrough, the second doesn't [[fiddle](https://codesandbox.io/s/trusting-violet-y31we5?file=/src/index.js:0-182)]. How can we support the strikethrough syntax in commonmark mode? Any pointers would be appreciated!

**Comment by puzrin** [comment]
strikethrough is NOT part of commonmark. But you can enable/disable any combination of rules you wish.

`.enable('strikethrough')`

**Comment by duhaime** [comment]
Ah spectacular, thank you!
