### ISSUE TITLE
Added pipe (|) to terminator characters

### ISSUE THREAD

**Issue by Luffyyy** [markdown-it/markdown-it#893]
https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/text.js

It seems like the [comment ](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/text.js#L10) above the defined characters implies the existence or intent of adding the pipe character to the terminator characters, it would be useful to add that character or any of the character defined there if that was the intent, thanks.

**Comment by puzrin** [comment]
We do not add changes "just for fun". Do you have a concrete example, where lack of `|` is a problem?

**Comment by Luffyyy** [comment]
Trying to implement a Discord-style spoiler block. Not being able to even extend said list is unfortunate. I was mostly just wondering why the character was on the comment despite not being in the list itself.

**Comment by puzrin** [comment]
> I was mostly just wondering why the character was on the comment despite not being in the list itself.

I don't remember, if it was placed in comment by mistake or missed in code.

Right now you can replace `text` rule by your custom one. Then, when your plugin ready, just kick me and I will add the desired char into mainstream.
