### ISSUE TITLE
Enable config for code/fence block to 

### ISSUE THREAD

**Issue by codingstar** [markdown-it/markdown-it#894]
Currently, if markdown text is '\`\`\`\nabc\n\`\`\`'，it will be transformed to

```
<pre><code>abc\n</code></pre>
```

Is there any way to config whether to save the trailing `\n`? 

Like the [option](https://github.com/showdownjs/showdown/tree/a9f38b6f057284460d6447371f3dc5dea999c0a6#valid-options) in showdown: `omitExtraWLInCodeBlocks`

**Comment by rlidwka** [comment]
Override renderer using custom function:

```
md.renderer.rules.fence = function () {...}
```

This is how it's defined:

https://github.com/markdown-it/markdown-it/blob/08444a5c1c84440f0c03a23c26d5cf57175e7575/lib/renderer.js#L39-L90

This is an example how to do it:

```
let md = require('./')()

let default_fence_rule = md.renderer.rules.fence
md.renderer.rules.fence = (...args) => {
  return default_fence_rule(...args).replace(/\n$/, '')
}

console.log(md.render(`
~~~
abc
~~~
`))
```
