### ISSUE TITLE
I want to enable only admonition plugin, but I need to disable everything, including paragraph. But `renderInline` doesn't parse admonition syntax

### ISSUE THREAD

**Issue by gusbemacbe** [markdown-it/markdown-it#895]
Since @gpoore's VSCode's Codebraid Preview extension does not support `markdown-it` and `markdown-it` plugins, that are supported only by Microsoft's VSCode's native Markdown Preview, and Atlassian's corporative version of Confluence doesn't allow the usage of JavaScript code of admonition, developed by @ianfun, I'll use Gulp to export from `markdown-it` with the inclusion of @sesispla's [`markdown-it-admonition`](https://github.com/docarys/markdown-it-admonition) plugin to the same Markdown file before exporting from Codebraid to HTML. My Gulp file is based on @caraya's code.

My Gulp file code is totally similar to `markdown-it` simple example of usage.

I want to enable only admonition and disable everything, including paragraph. I saw the question https://github.com/markdown-it/markdown-it/issues/12, posted by @rpominov. @puzrin suggested the usage of `renderInline` if we wanted to suppress the paragraphs.

But this ruler did not parse admonition syntax. It is important to observe that admonition syntax uses paragraph for admonition title. 

There are two alternatives `markdown-it` codes that I attempted:

1st alternative:

```js
const markdownIt = require('markdown-it')
const admonition = require("markdown-it-admonition");
const options = 
{
  breaks: false,
  html: true,
  linkify: false,
  preset: "zero",
  typographer: false,
  xhtmlOut: false,
};

const md = new markdownIt(options)
md.block.ruler.enableOnly([]);
md.disable('code');
md.disable('emphasis');
md.use(admonition);

function markdownToHtml(file) 
{
  const result = md.renderInline(file.contents.toString());
  file.contents = new Buffer.from(result);
  file.path = replaceExt(file.path, '.md');
  return;
}

function markdown() 
{
  return gulp
  .src('tests/formatting/*.md')
  .pipe(tap(markdownToHtml))
  .pipe(gulp.dest('tests/formatting/output/'));
}
```

2nd alternative:

```js
const markdownIt = require('markdown-it')
const admonition = require("markdown-it-admonition");
const options = 
{
  breaks: false,
  html: true,
  linkify: false,
  preset: "zero",
  typographer: false,
  xhtmlOut: false,
};

const md = new markdownIt(options)
md.configure(
{
  components: 
  {
    core: 
    {
      rules: 
      [
        'block',
        'inline',
        'linkify',
      ]
    },
    block: 
    {
      rules: 
      [
        'paragraph',
      ]
    },
    inline: 
    {
      rules: 
      [
        'newline',
      ]
    }
  }
});
md.use(admonition);

function markdownToHtml(file) 
{
  const result = md.renderInline(file.contents.toString());
  file.contents = new Buffer.from(result);
  file.path = replaceExt(file.path, '.md');
  return;
}

function markdown() 
{
  return gulp
  .src('tests/formatting/*.md')
  .pipe(tap(markdownToHtml))
  .pipe(gulp.dest('tests/formatting/output/'));
}
```

**Comment by rlidwka** [comment]
Can you override paragraph rendering, so it doesn't include `<p>...</p>` in them? Would it solve your problem?

Block parser must have some kind of a default rule that always works on any text. It is a paragraph rule. If you remove it, you have to write some kind of replacement.

**Comment by 0xTomDaniel** [comment]
@rlidwka Could you point me in the right direction to override paragraph rendering? I'm also trying to completely eliminate `<p></p>` tags for Telegram compatibility, but need block rendering for blockquotes.

**Comment by rlidwka** [comment]
@0xTomDaniel , something like `md.renderer.rules.paragraph_open = function () { return '' }`

There are a couple of built-in rules here, and you would be overriding those:
https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.mjs#L21
