### ISSUE TITLE
Order list sub items does not follow common procedure

### ISSUE THREAD

**Issue by devPaulRS** [markdown-it/markdown-it#899]
The following does not display accurately as expected as like github and other markdown does, please make a patch update.

1. This is the main item
a. This is a sub item of the main item
b. This is a second sub item of the main item
2. This is the second main item
a. This is the first sub item of the second main item
3. This is the third main item

A workaround is to add double space at the end of each line, but this isn't feasible it should be automatic.

Markdown link: https://markdown-it.github.io/#md3=%7B%22source%22%3A%22Problem%3A%5Cn1.%20This%20is%20the%20main%20item%5Cna.%20This%20is%20a%20sub%20item%20of%20the%20main%20item%5Cnb.%20This%20is%20a%20second%20sub%20item%20of%20the%20main%20item%5Cn2.%20This%20is%20the%20second%20main%20item%5Cna.%20This%20is%20the%20first%20sub%20item%20of%20the%20second%20main%20item%5Cn3.%20This%20is%20the%20third%20main%20item%5Cn%5CnExpectation%3A%5CnThis%20is%20adding%20double%20spaces%20at%20the%20end%20of%20each%20line.%5Cn%5Cn1.%20This%20is%20the%20main%20item%20%20%5Cna.%20This%20is%20a%20sub%20item%20of%20the%20main%20item%20%20%5Cnb.%20This%20is%20a%20second%20sub%20item%20of%20the%20main%20item%20%20%5Cn2.%20This%20is%20the%20second%20main%20item%20%20%5Cna.%20This%20is%20the%20first%20sub%20item%20of%20the%20second%20main%20item%20%20%5Cn3.%20This%20is%20the%20third%20main%20item%20%20%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

**Comment by puzrin** [comment]
Works exactly as [reference parser](https://spec.commonmark.org/dingus/?text=1.%20This%20is%20the%20main%20item%0Aa.%20This%20is%20a%20sub%20item%20of%20the%20main%20item%0Ab.%20This%20is%20a%20second%20sub%20item%20of%20the%20main%20item%0A2.%20This%20is%20the%20second%20main%20item%0Aa.%20This%20is%20the%20first%20sub%20item%20of%20the%20second%20main%20item%0A3.%20This%20is%20the%20third%20main%20item%0A%0AExpectation%3A%0AThis%20is%20adding%20double%20spaces%20at%20the%20end%20of%20each%20line.%0A%0A1.%20This%20is%20the%20main%20item%20%20%0Aa.%20This%20is%20a%20sub%20item%20of%20the%20main%20item%20%20%0Ab.%20This%20is%20a%20second%20sub%20item%20of%20the%20main%20item%20%20%0A2.%20This%20is%20the%20second%20main%20item%20%20%0Aa.%20This%20is%20the%20first%20sub%20item%20of%20the%20second%20main%20item%20%20%0A3.%20This%20is%20the%20third%20main%20item%20%20%0A). I'd suggest to read CM spec for details.

**Comment by devPaulRS** [comment]
@puzrin it's also incorrect they also need to update.

**Comment by puzrin** [comment]
Try to explain your position at CM forum. This repo implements spec exactly as is.

**Comment by vassudanagunta** [comment]
See https://github.com/commonmark/commonmark.js/issues/266.
