### ISSUE TITLE
Unable to block code rule

### ISSUE THREAD

**Issue by idontknowjava** [markdown-it/markdown-it#902]
[Manage rules](https://github.com/markdown-it/markdown-it#manage-rules) section mentions that any rule could be blocked. I don't want any string written in `code` syntax to render as `code`. Using the following implementation. How can I block `code` rule?
 
```js
var md = require("markdown-it")({
  linkify: true,
  break: true
}).disable(["code", "fence"]);

const str = "`Some text`";
var result = md.render(str);
console.log(result);
```

Current output: `<p><code>Some text</code></p>`
Expected output: `<p>Some text</p>`

**Comment by rlidwka** [comment]
If a rule is disabled, you'll have `` <p>`Some text`</p> `` as an output.

If you don't want it to be rendered as code, maybe the best approach is to change CSS so it doesn't?

If you want to omit `<code>` tag, you can override renderers for `code_inline`, `code_block` and `fence` like this:

```js
let md = require('markdown-it')()

md.renderer.rules.code_inline = tokens => (
  tokens.map(t => t.content).join('')
)

console.log(md.render("`Some text`"))
```
