### ISSUE TITLE
Unexplained dashes in tables test

### ISSUE THREAD

**Issue by black-puppydog** [markdown-it/markdown-it#905]
This came up while cleaning up some things in [markdown-it.rs](https://github.com/rlidwka/markdown-it.rs). Re-generating the tests over there led to this test failing.

The `---` dash in line 751 is what makes this fail, but I don't understand what that dash is doing there in the first place. It was imported from this repository and references example 203 of the GFM spec, yet I don't see it there: https://github.github.com/gfm/#example-203

https://github.com/markdown-it/markdown-it/blob/2b6cac25823af011ff3bc7628bc9b06e483c5a08/test/fixtures/markdown-it/tables.txt#L744-L753

**Comment by rlidwka** [comment]
Sorry for delay in answering.

markdown-it.js tests work with all features enabled, and this is just a typographer side-effect ("---" transformed into "—").
