### ISSUE TITLE
Brackets not working when used in parse() function

### ISSUE THREAD

**Issue by RensTillmann** [markdown-it/markdown-it#907]
Version used: 13.0.1

Content being parsed:

```
# FAQ

This [shortcodes] is not working.

```

Below the output I get:

```
$ node scrape-github.js
C:\project\node_modules\markdown-it\lib\rules_inline\link.js:99
    if (typeof state.env.references === 'undefined') { return false; }
                         ^

TypeError: Cannot read property 'references' of undefined
```

When I change the content of the markdown file to the below it works without problems. Not sure what to do here, can't find any information about it online. Setting different options didn't seem to help like html: true/false.

```
# FAQ

This shortcodes is working.

```

Code to reproduce:

```
const md = require('markdown-it')({
  html: true // Enable HTML tags in source
});
const html = `
# FAQ

Stupid [shortcodes] not working.

`;
const ast = md.parse(html);
```

**Comment by RensTillmann** [comment]
Please note that I can't edit the contents so the markdown file stays the same. The only option I have is to tweak it with a regex before parsing it.

If I would mess with replacing open/close brackets to replace or surround it with a backtick (which does seem to parse fine in those cases) it would also do this for any links in the document. Or I would need to first convert any links to a different format, and then do the replacement on any shortcodes. And then revert back. It's all possible but I find this a bit of a strange "issue"?

Another problem here is that I can't get any information on where the parser is encountering the problem.
It just gives that generic error.

```
`[shortcode]`
```

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/index.js#L517 seems, missed second mandatory param in manual  `.parse()` call. See docs & how it's used from `.render()`
