### ISSUE TITLE
Could not import MarkdownIt in Ember CLI

### ISSUE THREAD

**Issue by changeweb** [markdown-it/markdown-it#91]
I've installed markdown-it via both bower and npm and trying to import it in my Ember app. But Could not import it.

I'm trying to use [Markdown-it][1] in Ember Helper. First I installed it with **Bower** and tried to import it. In `Brocfile.js`

    app.import('bower_components/markdown-it/dist/markdown-it.js');
In helper:

    import MarkdownIt from "markdown-it";
This is showing error `Could not find module: markdown-it`. Then I tried to use [Ember-browserify][2] and install `Markdown-it` via npm. I tried to import it in helper

    import MarkdownIt from "npm:markdown-it";
 
    export default Ember.Handlebars.makeBoundHelper(function(input){
        var result = MarkdownIt.render(input);
        return new Ember.Handlebars.SafeString(result);
    });
This is showing error `TypeError: a.default.render is not a function`.

I also tried using `/* global MarkdownIt */`. Nothing is working.

  [1]: https://github.com/markdown-it/markdown-it
  [2]: https://github.com/ef4/ember-browserify

**Comment by puzrin** [comment]
No ideas. I'm not familiar with tools you use. Not sure this question is related to this repo.

**Comment by changeweb** [comment]
Ok, I'm closing it for now.

**Comment by svyatogor** [comment]
I am experiencing the same problem. With all due respect are you sure its is a good idea to close the ticket as irrelevant? EmberJS is one of the most popular MVC's out there.
