### ISSUE TITLE
Link with apostrophe character not clickable

### ISSUE THREAD

**Issue by swati693** [markdown-it/markdown-it#910]
If there is a tooltip text on a link with apostrophe character, the link is not clickable..
 Ex :
Not Clickable - [ Customer's Hello Doc ](https://hellodoc.html 'Customer's Hello Doc')

Clickable - [ Customers Hello Doc ] (https://hellodoc.html 'Customers Hello Doc')
With correct tooltip - Customers Hello Doc

**Comment by puzrin** [comment]
https://spec.commonmark.org/dingus/?text=Not%20Clickable%20-%20%5BCustomer%27s%20Hello%20Doc%5D(https%3A%2F%2Fhellodoc.html%20%27Customer%27s%20Hello%20Doc%27)%0A%0AClickable%20-%20%5BCustomers%20Hello%20Doc%5D(https%3A%2F%2Fhellodoc.html%20%27Customers%20Hello%20Doc%27)%0A%0AEscaped%20-%20%5BCustomer%27s%20Hello%20Doc%5D(https%3A%2F%2Fhellodoc.html%20%27Customer%5C%27s%20Hello%20Doc%27)%0A

Works as expected, apostrophe should be escaped.
