### ISSUE TITLE
XHTML output improperly self-closing DIV from markdown-it-task-checkbox plugin

### ISSUE THREAD

**Issue by richardtallent-erm** [markdown-it/markdown-it#911]
When using the `xhtmlOut` flag and the `markdown-it-task-list` plugin with the wrapper div option, the wrapper div is self-closed by markdown-it, so it no longer wraps the input and label, but the div's end tag is left as well, so the markup is invalid XHTML:

```js
import MarkdownIt from "markdown-it"
import MarkdownItTaskCheckbox from "markdown-it-task-checkbox"

const xhtmlParser = MarkdownIt({
	html: true,
	xhtmlOut: true,
}).use(MarkdownItTaskCheckbox , { divWrap: true });
var html = xhtmlParser.render("- [ ] unchecked item 1");
console.log(html);
```

```html
<ul class="task-list">
  <li class="task-list-item">
    <div class="checkbox" />
    <input type="checkbox" id="cbx_0" disabled="true" />
    <label for="cbx_0"> unchecked item 1</label>
    </div>
  </li>
</ul>
```

I don't know if this is an issue specific to the plugin or an edge case in MarkdownIt that could happen in other situations as well. I looked at the plugin's code, but didn't see any obvious issues (I haven't developed a MarkdownIt plugin, so the API is fairly opaque to me):

https://github.com/linsir/markdown-it-task-checkbox/blob/6c684bb3f02aa097fe33ca7d9fe05e19857c910d/index.js#L69

**Comment by puzrin** [comment]
That's a third-party plugin, I can't comment on it. Please get in touch with the author.
