### ISSUE TITLE
Zero config + Breaks

### ISSUE THREAD

**Issue by dliebner** [markdown-it/markdown-it#914]
Trying to figure out how to use zero config with breaks. Also not quite sure why `code` isn't disabled by default:

```js
var md = require("markdown-it")('zero', { breaks: true });

md.set({
  breaks: true
});

md.disable(['code']);

let text = `
  Line 1
  Line 2
`;

console.log( md.render(text) );
/** <p>Line 1
  Line 2</p>
*/
```

**Comment by rlidwka** [comment]
> Trying to figure out how to use zero config with breaks.

You need to enable newline rule, as it is the rule that generates tokens to be turned into breaks:

```js
var md = require("markdown-it")('zero', { breaks: true });
md.enable(['newline']);
let text = `
Line 1
Line 2
`;
```

> Also not quite sure why code isn't disabled by default:

Code **is** disabled by default, which you can check by turning it on and off in the following snippet:

```js
var md = require("markdown-it")('zero', { breaks: true });
md.enable(['code']);
let text = `
    Line 1
    Line 2
`;
```
