### ISSUE TITLE
How can I preserve &nbsp; used in markdown files?

### ISSUE THREAD

**Issue by epoberezkin** [markdown-it/markdown-it#915]
Currently it is replaced with `\xA0`

**Comment by puzrin** [comment]
Use escaping with `\`: `\&nbsp;` => \&nbsp;

**Comment by epoberezkin** [comment]
The problem with this approach is that they are then incorrectly rendered in markdown files on GitHub - it shows `&nbsp;` text instead of inserting spaces.

Markdown files should support html entities as is, they should not be replaced with some other characters when converted into HTML - it would be good to have some option to control this behavior...

**Comment by puzrin** [comment]
I don't understand, how your questions are related to this concrete package.

**Comment by epoberezkin** [comment]
> I don't understand, how your questions are related to this concrete package.

Well, we can't just arbitrarily change markdown files to fit a package expectations, as they are used as pages on GitHub or any other code hosting platform - so the package should accept them as is...

> If you wish to keep entities intact, you can .disable('entity')

Thank you - will try that!
