### ISSUE TITLE
Module not found: Error: Package path ./lib/maps/entities.json is not exported from package 

### ISSUE THREAD

**Issue by niemyjski** [markdown-it/markdown-it#916]
I was curious what the outcome of the following issue is https://github.com/fb55/entities/issues/783

I'm running into this with the latest version of webpack as well as latest version of this library. 
```
Module not found: Error: Package path ./lib/maps/entities.json is not exported from package /Users/blakeniemyjski/code/abc/node_modules/entities (see exports field in /Users/blakeniemyjski/code/abc/entities/package.json)
 @ ./node_modules/markdown-it/lib/common/utils.js 80:15-36
 ```

**Comment by niemyjski** [comment]
Pinning the entities dep to `3.0.1` resolves this but the default seems to resolve it to 4.x

**Comment by nathanaelphilip** [comment]
@niemyjski how were you able to pin this? I’ve tried the `overrides` method, but that doesn’t seem to work.

**Comment by niemyjski** [comment]
"Markdown-dep-that-is-broken": "3.0.1"

**Comment by pyhedgehog** [comment]
I hope #901 will fix this too.
