### ISSUE TITLE
Solis Scan issue: Information Disclosure - Suspicious Comments

### ISSUE THREAD

**Issue by prakhar-tiwari** [markdown-it/markdown-it#917]
Solis scan gave following result
`Endpoint: https://<domain>/markdown-it/markdown-it.min.js?3d26806b53e4dc005566`

The response appears to contain suspicious comments which may help an attacker. Note: Matches made within script blocks or files are against the entire content not only comments.

Suggested solution:
Remove all comments that return information that may help an attacker and fix any underlying problems they refer to.

**Comment by puzrin** [comment]
Not a bug
