### ISSUE TITLE
custom css / latex

### ISSUE THREAD

**Issue by servermeta** [markdown-it/markdown-it#92]
Hi! great project!

I'm trying to write an open source online editor for academic writing, built on top of markdown + latex.

It seems like yours is one of the most interesting implementation of markdown in JS. I have two questions:

1) Does markdown-it generate any CSS at all? Can I customize it? 

2) I've looked at the documentation of markdown-it for writing extension, and to implement LateX I would either need coaching in helping to understand how to do it, or someone else would need to help me write it. 

I think that a math extension would really help spreading the use of markdown, at least among the academic community, which really needs it. 

We already have a very excellent starting point, made by @runarberg  

https://github.com/runarberg/markdown-it-math

But we could do much better.

**Comment by vyp** [comment]
> 1) Does markdown-it generate any CSS at all? Can I customize it?

Do not think so. Though I might be wrong.

---

Implementing LaTeX parsing in javascript would be extremely difficult. If you just want the math part, have you seen [MathJax](http://www.mathjax.org/)? I assume it would be trivial to integrate markdown-it with mathjax (client side, that is. Afaik, mathjax doesn't run on Node or other server side javascript platforms). There is also [texlive.js](http://manuels.github.io/texlive.js/#open_pdf), but that *creates pdfs* with javascript, rather than display html/in-browser editor display version of LaTeX.

To be honest, I think it might actually be easier to just  use the [Pandoc](http://pandoc.org/README.html) haskell library for your backend, meaning no need for markdown-it.

**Comment by puzrin** [comment]
- Markdown generates content to insert into "body". You need to wrap it with the rest.
- For LaTeX blocks you can overrite fenced blocks renderer or clone it if you need another syntax with similar features.

Sorry, but can't help with generic programming and anything else _not specific for this package_. We are focused only on implementing configurable CommoMarc parser only. Everything else, like syntax should be discussed in different places. For example, on http://talk.commonmark.org/

**Comment by servermeta** [comment]
@vyp obviously I dont want to reinvent the wheel :smile: I plan to use mathjax and I've already built a demo with pandoc https://groups.google.com/forum/#!topic/pandoc-discuss/WTq_L2RSHDk

anyhow pandoc is written in haskell, which I dont know. And having a full javascript stack would allow it to run fully in the client, allow me to offer the app for free to everybody.

@puzrin A math extension has already been proposed, and the idea have been approved 

http://talk.commonmark.org/t/mathjax-extension-for-latex-equations/698

we could be bleeding edge by implementing this suggestion before it's formalized :+1: 

jokes aside I've already looked that way, as it seemed the smartest to me. Anyhow I'm a total noob, so I would like to make you some dumb questions that could help improve the documentation for beginners like me.

**Comment by servermeta** [comment]
example:

let's say I want a fast way to create a specific style for equations. Let's call this FancyEq.

Such equations should be:

1) Centered
2) Numbered
3) Rendered from latex with mathjax
4) Placed in a light red rectangular box, to highlight them

I would use a selection of multiple packages: 

https://www.npmjs.com/package/markdown-it-classy
https://github.com/markdown-it/markdown-it-container

1) The editor would propose a set of CSS styles to pick from
2) The user pick a style 
3) the user type:

::: FancyEquation
$$Bad Ass Latex$$
::: {OptionalClass}

markdown-it-container would provide the container. Can I add multiple class to it, to combine multiple styles?

Otherwise I should use Classy to add additional classes?

Can I create a container option that automatically detect that it contains latex, thus not requiring $$ $$?

**Comment by puzrin** [comment]
@servermeta i will try to help if questions are related to this project, but more generic talks should be left aside. There are better places for such thing.

Current tokens allow to add custom attributes like class, but content is just a string. If you need multiple classes, you have to care about proper join those with space into single string. That's done intentionally, because different attributes can have different join chars.

**Comment by servermeta** [comment]
@puzrin thank you for your help!

1) Does markdown-it support custom IDs too?

2) Does markdown-it-container support this or should I implement it?

Something like:

::: FancyEquation FancyClass
$$Bad Ass Latex$$
:::

**Comment by puzrin** [comment]
@servermeta Writing complete tutorial from zero is very big task, and i have no resources for it. You really need to dig source code of existing plugins and rules. Current minimal entry level requires it, to create new ones.

`id` is attribute, as `class` is. Tokens allow any attributes, and don't make difference between those. `markdown-it-container` does not care about classes at all. You can rewrite rendering rule as you wish or modify attrs.

**Comment by servermeta** [comment]
@puzrin Now I get everything better. I can create html from markdown, using classes, and styles with CSS/Less, and put them together client side or with metalsmith to be published as HTML/PDF/EPub

I'm not speaking of a full tutorial. Just blogging about some extensions would be really helpful. I'm playing with different paths (pandoc server side, markdown-it client side, others), but if I will pick markdown-it I will write one myself.

One of the coolest thing of markdown is that you can extend it. Taking care of making the plugin system easy to use is a sure way to boost this project reach.

It's sad this project has so little recognition, it has some amazing ideas. Markdown is really fragmented, but I feel like markdown-it could replace all other extensions, if it were as easy as showdown to extend.

**Comment by runarberg** [comment]
@servermeta markdown-it-math is my attempt for native rendering of mathematics. It will render math delimited text into MathML using whatever renderer you pick. Currently MathML is only available in Firefox and Safari, with no plans to be included in Explorer or Chrome.

You can easily auto-number block level equations using [CSS counters](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Counters) but how you would reference those in your text you probably need to do programmatically.

Regarding your project, perhaps you should take a look at [ScholarlyMarkdown](http://scholarlymarkdown.com/), it's a Pandoc fork aimed at the academic community, perhaps you can get some inspiration there.

**Comment by servermeta** [comment]
@runarberg my only question is: why you didn't use MathJax as default?

It has better browser support, and I think that the generated output looks better.

Scholarly Markdown is definitely a project I have in mind. They implement most of what I want to do, so I'm using them as a reference. 

As I said before of pandoc:

"anyhow pandoc is written in haskell, which I dont know. And having a full javascript stack would allow the app to run fully in the client, allowing me to offer it for free to everybody (almost zero hosting cost)."

Having a fully client side app is a big plus for me. CSS has progressed a lot since Pandoc was born, and lot of stuff can be done now that couldn't be done before.

Using a CSS preprocessor, and a static site generator (like metalsmith, or something fully client side) you can take care of numbering, of positioning the number (via CSS you can say to place the numeration after each element), and you can reference them via IDs.

**Comment by servermeta** [comment]
@runarberg anyhow I have a pandoc implementation that requires a server, and works:

1) Offline App for linux, windows and mac
2) Online App for browser Android, Windows phone and iOS 

and with:

3) Collaborative editing in real time via operational transforms and reactivity
4) Auto completion
5) (in progress) Real time preview 

switching to javascript make the app available offline also for mobile, and allow me to ditch nw.js, which weights 200+ mb. 

If you are willing to help me customize a bit markdown-it, we could deliver an open source implementation in 2/3 weeks. 

At the moment I'm banging my head behind virtual dom implementation, for really fast preview (a limit of the scholarly demo), and some mathematical stuff (levenstein distance for fast generation).

**Comment by runarberg** [comment]
@servermeta You don't need a plugin to use MathJax, MathJax both parses and renders TeX equations, AsciiMath or MathML. If you don't care about native support (and speed) you can just leave the math delimiters in your HTML documents, and then let MathJax render and parse them. Markdown-it-math parses and translates your math into MathML while markdown-it is working, and let's your browser (if it supports it) do the rendering. If you use MathJax along side markdown-it-math, it should only be a polyfill.

**Comment by servermeta** [comment]
@runarberg now I get it. If you stay in the browser you are right, it's the same. 

But sicne I need to print as PDF or EPub, I prefer a javascript free output, so I could process input directly into HTML+CSS with mathjax, do you agree?

**Comment by runarberg** [comment]
MathML has accessibility advantages (screen-readers, CAS, etc.), so if the intended platform supports MathML it is a superior option. However, as noted, implementation is currently poor. An optimal solution might be to fall back on HTML+CSS rendering with MathJax in case of an non-supportive client.

**Comment by mgeier** [comment]
There is another extension that might be relevant for this discussion: https://github.com/classeur/markdown-it-mathjax
