### ISSUE TITLE
Special char emphasis rendering

### ISSUE THREAD

**Issue by ferllings** [markdown-it/markdown-it#920]
Hello,

I've noticed a rendering problem:
some special chars (%, !, ?, ...) are not correctly applying emphasis, if the char is the first char of the emphasis group and if the emphasis group is preceded by a letter

`**%**`
produce **%**

`100**%**`
produce 100**%**

Is it a desired behavior or a known problem?

**Comment by rlidwka** [comment]
> Is it a desired behavior or a known problem?

That is a desired behavior.

```
100**%**
   ^^--- these are interpreted as closing emphasis, not opening
```

Roughly speaking, there are 3 classes of characters to determine whether emphasis pairs are openers or closers:
 - alphanumeric characters
 - punctuation characters
 - whitespace characters

And `**` attaches to the ones with most priority. In your case, `**` would rather attach to preceding `0` than succeeding `%`.
