### ISSUE TITLE
parser should get live rules from ruler for each iteration

### ISSUE THREAD

**Issue by wisammechano** [markdown-it/markdown-it#922]
I have a use case where I need to disable certain blocks inside a list, like preventing a blockquote and headings inside a list item.

How I am approaching it is putting a rule at the beginning of the block chain that checks if the current parent in the state is `list`, it would disable `heading` and `blockquote` rules. Otherwise, it enables them. However, because in the loop, the rules have been acquired, disabling them won't have an effect.

Currently i believe the solution to this would be to remove these tokens on render, or to hack the rules to return false.

**Comment by puzrin** [comment]
Sorry, we can not redesign parser for your needs. Rules are static and configured before use.

**Comment by wisammechano** [comment]
Thank you for your response. However, I find it weird given that it is a feature request backed by a statement in the developer docs:

> Each chain (core / block / inline) uses an independent state object when parsing data, so that each parsing operation is independent and _can be disabled_ on the fly.
[Source](https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md)

As it currently stands, disabling it on the fly can't happen. I can only disable it before the chain starts parsing, which wouldn't serve my purpose in this case.

Or maybe I am using it incorrectly. Please correct me if I am wrong.

**Comment by rlidwka** [comment]
> I have a use case where I need to disable certain blocks inside a list, like preventing a blockquote and headings inside a list item.

You can copy-paste blockquote/headings code (write your own plugin based on the existing rules). Then on top of the rules check if they are called from inside a list. All tools are there.

> so that each parsing operation is independent and can be disabled on the fly.

That was perhaps referring to operation of parsing a whole document. I.e. you would be able to disable rules for next document.

> How I am approaching it is putting a rule at the beginning of the block chain that checks if the current parent in the state is list, it would disable heading and blockquote rules. Otherwise, it enables them. 

You can't change a global state of the parser based on user input in one particular document. That's just wrong for many reasons.

Dynamically changing parser rules for current document only is a cool idea, however it would run into performance issues with the current approach.
