### ISSUE TITLE
Concern on licensing compatibility with argparse

### ISSUE THREAD

**Issue by eta-orionis** [markdown-it/markdown-it#926]
Can anyone provide an authoritative source on whether this package's MIT license is compatible with the "Python-2.0" license from its `argparse` dependency? In particular: are there implications of using `markdown-it` in commercial projects and being forced to accept the `argparse` license as a result?

There is very little information on the Python-2.0 license, apart from Wikipedia saying that some versions _might not_ be GPL-compatible [1] -- which means other versions _are_ GPL-compatible. GNU says the incompatibility is due to the governing law: Python-2.0 requires Virginia law, which the GPL does not allow [2]. But if that is the only problem, it would sound like the Python-2.0 license is more similar to GPL than to MIT.

[1] https://en.wikipedia.org/wiki/Python_License
[2] https://www.gnu.org/licenses/license-list.html#PythonOld

**Comment by eta-orionis** [comment]
Apparently I'm not the only one noticing the problem. This has also been reported at argparse's own repository [1],[2],[3], but the issues have been closed without a solution or authoritative answer beyond. Furthermore, it seems that the SPDX identifier for argparse's license does not match the actual text of the license (Source: the links above). Wordpress itself is having problems with the license, but they are able to circumvent it as they are only using argparse during development, not in the released code.

[1] https://github.com/nodeca/argparse/issues/159
[2] https://github.com/nodeca/argparse/issues/160
[3] https://github.com/nodeca/argparse/issues/161

**Comment by m-gallesio** [comment]
I have checked how `argparse` is used here, and it seems to be only a dependency of the command line part. This means **it does not get included in bundles** (or at least it should not), so *it does not seem* any licensing problems affect browser distributions and bundling.

**Comment by puzrin** [comment]
1. As far as i remember, argparse license is confusing but correct. Also, it was updated to better one.
2. In any case, it's used only for CLI helper and should not be an issue.
