### ISSUE TITLE
Renderer.fence: Don't wrap markdown containing one ore more `<pre>` tags

### ISSUE THREAD

**Issue by hirasso** [markdown-it/markdown-it#928]
I am making use of the plugin [markdown-it-shiki](https://github.com/antfu/markdown-it-shiki) for highlighting fenced code blocks. The plugin renders two `<pre>` tags for [light/dark mode](https://github.com/antfu/markdown-it-shiki#dark-mode). It wraps these two `<pre>` tags in a div for greater control over the outcome (css effects, additional UI).

Since markdown-it only skips wrapping fenced code blocks that *start* with a `<pre>` tag, it will output invalid HTML in the case that the result of the highlighter in use starts it's output with a `<div>` or any other element.

I have created a PR that would solve this issue, where I also have posted more information: #927 (sorry for creating the PR before opening an issue 😅)

Would someone from the maintainers be willing to have a look at that PR? I would very much like to understand the concerns with my proposed feature, if there are any 🙏

**Comment by puzrin** [comment]
See https://github.com/markdown-it/markdown-it/pull/927#issuecomment-1817525222. I'd prefer to leave any customisations for users.

**Comment by hirasso** [comment]
Ok. Thanks for your consideration.
