### ISSUE TITLE
Allow `\` as a stopping char for plugins

### ISSUE THREAD

**Issue by runarberg** [markdown-it/markdown-it#93]
I am the author of [markdown-it-math](https://github.com/runarberg/markdown-it-math) and I am trying to resolve [this issue](https://github.com/runarberg/markdown-it-math/issues/4). I'm having issue [getting my inline rule to pass](https://github.com/markdown-it/markdown-it/blob/master/docs/development.md#why-my-inline-rule-is-not-executed). Since many authors use `\(`...`\)` to delimit inline math, it would be nice if I could allow the users of my plugin to do the same.

**Comment by puzrin** [comment]
Could you explain details, what's a problem with it? This char already exists in list of possible terminators https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/text.js#L31 , but you need to inject your plugin before [escaping rule](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/escape.js), or this rule will eat it.

**Comment by puzrin** [comment]
Inline math is ~ the same as inline code block. So, you rule should be like [backticks](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/backticks.js), but with slightly different start-end check (and with different renderer, of cause). That's doable, and not require any changes in mainstream.

**Comment by runarberg** [comment]
Thanks. I didn't know about the escaping rule. It worked like a charmed when inserted before it.
