### ISSUE TITLE
Custom rule pushed as last in the chain is not being executed

### ISSUE THREAD

**Issue by GhostOrder28** [markdown-it/markdown-it#930]
Hello I'm writing a plugin for markdown-it in which I need to rearrange the block token chain, because of this I need my rule to be the last in the chain so I can modify the tokens array, but when I `push` it or add it `after` the paragraph rule (which is the default last one) then my rule is not executed at all.

```
md.use((md, opts) => {
  md.block.ruler.push('my_custom_rule', function customRule () {
    console.log('executing custom rule...') // this is never executed
  })
})
```
However it works if I add my rule before the last rule in the chain:
```
md.use((md, opts) => {
  md.block.ruler.before('paragraph', 'my_custom_rule', function customRule () {
    console.log('executing custom rule...') // this works
  })
})
```
What I'm missing here?

**Comment by rlidwka** [comment]
> Hello I'm writing a plugin for markdown-it in which I need to rearrange the block token chain, because of this I need my rule to be the last in the chain so I can modify the tokens array

`md.block` chain is a tokenizer. It is meant for rules that **create** tokens, not modify them or rearrange them.

I believe you want your plugin to be added to core chain instead (and then traverse all block tokens from there).

> but when I push it or add it after the paragraph rule (which is the default last one) then my rule is not executed at all

All rules in block and inline chains are executed until any rule returns true. `paragraph` is a catch-all rule that always stops the chain, thus nothing can ever be executed after it in a block chain.

**Comment by GhostOrder28** [comment]
> I believe you want your plugin to be added to core chain instead (and then traverse all block tokens from there).

Yep, that's what I ended up doing

> All rules in block and inline chains are executed until any rule returns true. paragraph is a catch-all rule that always stops the chain, thus nothing can ever be executed after it in a block chain.

Gotcha, that's why the `paragraph` rule is at the end of the chain, thank you for the clarifications.
