### ISSUE TITLE
Open links in new tab

### ISSUE THREAD

**Issue by ahm750** [markdown-it/markdown-it#934]
Hi,

Does the package offer an option for links to open in a new tag? Meaning that the link tags will contain target="_blank" attribute.

Thanks.

**Comment by rlidwka** [comment]
yes, see an example in https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer

**Comment by samiahmedsiddiqui** [comment]
@ahm750 Try this package: https://www.npmjs.com/package/markdown-it-external-link
