### ISSUE TITLE
Incorrect conversion of numeric character references 

### ISSUE THREAD

**Issue by chrisjsewell** [markdown-it/markdown-it#935]
e.g. `[](&#X22z;) [](&#35z;)` is incorrectly converted to `<p><a href="%22"></a> <a href="#"></a></p>`, as opposed to `<p><a href="&amp;#X22z;"></a> <a href="&amp;#35z;"></a></p>`

- https://spec.commonmark.org/dingus/?text=%5B%5D(%26%23X22z%3B)%20%5B%5D(%26%2335z%3B)%0A%0A%0A%0A
- https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%5B%5D%28%26%23X22z%3B%29%20%5B%5D%28%26%2335z%3B%29%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Afalse%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Atrue%2C%22_view%22%3A%22src%22%7D%7D

It feels like the addition of `$` (in https://github.com/markdown-it/markdown-it/commit/6325878f9fa7dba17c8af1c5f190a455191495aa) to https://github.com/markdown-it/markdown-it/blob/2b6cac25823af011ff3bc7628bc9b06e483c5a08/lib/common/utils.js#L78
should have fixed this, but that does not appear to be the case in the demo

**Comment by chrisjsewell** [comment]
Ah, actually I guess this has not been released yet?

**Comment by rlidwka** [comment]
> Ah, actually I guess this has not been released yet?

Yeah, and demo wasn't rebuilt since then.

I added `$` to regexp in commit above to make regexp more specific. But I didn't know this was an actual bug, thus it wasn't documented, tested and released.

**Comment by chrisjsewell** [comment]
Yeh the behaviour of `parseInt` is a bit weird, in that it essentially ignores any "tail" characters that are not parseable

**Comment by rlidwka** [comment]
This should be fixed now in released 13.0.2 version.
