### ISSUE TITLE
Emphasis not working with embedded links.

### ISSUE THREAD

**Issue by cliss** [markdown-it/markdown-it#94]
I'm seeing a bug wherein a link within an emphasis/bold block is not showing as `strong`.

Example:

```
> md.render('This is a __[test of a link in bold](http://www.github.com/)__.')
'<p>This is a __<a href="http://www.github.com/">test of a link in bold</a>__.</p>\n'
```

I would have expected:

```
'<p>This is a <strong><a href="http://www.github.com/">test of a link in bold</a></strong>.</p>'
```

You'll note that this works as expected when the link is not included:

```
> md.render('This is a __test of bold__.')
'<p>This is a <strong>test of bold</strong>.</p>\n'
```

This seems to work as I expected on the [Commonmark Dingus](http://spec.commonmark.org/dingus/?text=This%20is%20a%20__%5Btest%20of%20a%20link%5D(http%3A%2F%2Fwww.github.com)%20in%20bold__.%0A%0AThis%20is%20a%20__test%20of%20bold__.).

If this user error, my utmost apologies; please let me know what I'm doing wrong!

**Comment by rlidwka** [comment]
> This seems to work as I expected on the Commonmark Dingus.

No, [it doesn't](http://spec.commonmark.org/dingus/?text=This%20is%20a%20__%5Btest%20of%20a%20link%5D(http%3A%2F%2Fwww.github.com)%20in%20bold__.%0A%0AThis%20is%20a%20__%5Btest%20of%20a%20link%5D(http%3A%2F%2Fwww.github.com%20in%20bold)__.%0A%0AThis%20is%20a%20__test%20of%20bold__.). It's the dot after closing `__` that confuses the algorithm.

Maybe re-open it in [jgm/CommonMark](https://github.com/jgm/CommonMark) repo?

**Comment by cliss** [comment]
Shoot, you're totally right. My apologies. I'll open the same issue there.

**Comment by puzrin** [comment]
@rlidwka you already did patch for oirdinary text. I seems logical to make it work with links. We will have to do it anyway.
