### ISSUE TITLE
Problems with single and triple backtick formatting

### ISSUE THREAD

**Issue by sunwooz** [markdown-it/markdown-it#943]
Hello, I've been trying to figure out a problem for a few days that has to do with backtick code and code highlighting.

I'm currently using ChatGPT to generate text, which then gets run through markdown-it + highlightjs to fence triple back ticks(\`\`\`), and create inline code highlights for single backticks(\`)

I have two main problems.

When I run the resulting text through markdown-it, the \`\`\`ruby code \`\`\` ouputs as `ruby code` without getting rid of the 'ruby'.

<img width="1218" alt="Screen Shot 2023-06-27 at 12 38 36 PM" src="https://github.com/markdown-it/markdown-it/assets/1232414/1c25516a-b591-4fe3-b586-bddafb32334b">

This is how I have markdown-it and highlightjs configured

```
var md = require('markdown-it')({
  highlight: function (str, lang) {
    if (lang && hljs.getLanguage(lang)) {
      try {
        return '<pre class="hljs"><code>' +
               hljs.highlight(str, { language: lang, ignoreIllegals: true }).value +
               '</code></pre>';
      } catch (__) {}
    }

    return '<pre class="hljs"><code>' + md.utils.escapeHtml(str) + '</code></pre>';
  },
  linkify: true,
  typographer: true,
  html: true,
  breaks: true,
  langPrefix: 'language-',
  backticks: true,
  fence: true,
}).use(require('markdown-it-highlightjs'), {
    auto: true,
    inline: true,
    hljs: hljs,
    code: false,
});
```

The other problem is that I would like to differentiate inline vs blocked code(single vs triple backticks), but can't seem to figure out how to do that. I've tried enabling and disabling the different options to no avail.

Thanks in advance.

**Comment by rlidwka** [comment]
> When I run the resulting text through markdown-it, the \`\`\`ruby code \`\`\` ouputs as ruby code without getting rid of the 'ruby'.

That's an inline code snippet, which doesn't support highlighting, and doesn't support info strings.

You can check it up with reference parser:
https://spec.commonmark.org/dingus/?text=%60%60%60ruby%20code%20%60%60%60

Or even here on github.

If you want it to work differently, I think you have to write your own plugin.

> The other problem is that I would like to differentiate inline vs blocked code(single vs triple backticks), but can't seem to figure out how to do that. I've tried enabling and disabling the different options to no avail.

Inline code is single line. This is inline code: `````` `````code````` ``````.

Block code is 3+ lines. This is block code:

``````
`````info
code
`````
``````

The amount of backticks does not matter (except for inline it can be 1 or more, for blocks - 3 or more). As an example, I used 5 backticks above for both.
