### ISSUE TITLE
Rules with duplicate names is an issue

### ISSUE THREAD

**Issue by ThePlenkov** [markdown-it/markdown-it#944]
HI! I'm debugging currently the [module ](https://www.npmjs.com/package/@atlaskit/editor-markdown-transformer?activeTab=code) from Atlassian where they parse markdown. 
In one of plugins they require `markdown-it-table` which creates table rule.

Unfortunately right after this it's not possible to disable that newly added rule, because current code - will be always finding the first rule (standard one) and is not possible to disable the new one:
`tokenizer.block.ruler.disable('table')`;

probably `disableAll()` could be the solution or may be even something like this - `getRules('table')[1].disable()`

**Comment by puzrin** [comment]
Rule names MUST be unique. Please, write to plugin devs OR probably you can remove default one and re-add under different name.
