### ISSUE TITLE
Support for Function Plotting in Markdown

### ISSUE THREAD

**Issue by NowLoadY** [markdown-it/markdown-it#947]
## Feature Description:
I would like to kindly request support for function plotting in Markdown. It would be greatly appreciated if users could conveniently include function plots directly in Markdown documents, thereby enhancing the convenience and expressive capability of the format.

## Feature Requirements:
I kindly ask for support in directly embedding code or syntax in Markdown to plot functions, similar to \begin{tikzpicture} in LaTeX or using the matplotlib library in Python.

It would be greatly appreciated if the basic functionality could include plotting common types of functions, such as straight lines, quadratic curves, trigonometric functions, etc.

Furthermore, I kindly request the ability to adjust parameters like image size, style, colors, etc., in order to cater to different needs.

## Use Cases:
The function plotting feature would be extremely useful in various domains such as mathematics education, technical documentation, data analysis, and more. By allowing users to plot functions directly in Markdown, it becomes easier to visualize mathematical formulas, data trends, and other related content.

## Additional Information:
If there are any existing similar functionalities, extensions, or plugins available for reference, I would be sincerely grateful for any relevant resources and links.

**Comment by puzrin** [comment]
Sorry, the core project implements commonmark-only markup and does not accept extension requests. Any customizations should be done via plugins. Try to search in npm (links at the top of readme), probably someone implemented that.
