### ISSUE TITLE
`` symbol is not correctly parsed?

### ISSUE THREAD

**Issue by chenJJ-88** [markdown-it/markdown-it#955]
![image](https://github.com/markdown-it/markdown-it/assets/118970817/3aedfc51-f033-4685-bffc-e667d835f170)
The following is returned by the interface.
![image](https://github.com/markdown-it/markdown-it/assets/118970817/79e34d13-7af5-4c0e-a2a6-12494ef17dc3)
Is there anything else you need to configure?
![image](https://github.com/markdown-it/markdown-it/assets/118970817/dc8f213c-9762-443d-abcc-0526b35c3eb2)
This is the actual effect.

Thank you very much.

**Comment by rlidwka** [comment]
No idea what you're talking about. Can you provide a code snippet instead of a screenshot?
