### ISSUE TITLE
[Feature request] Provide a "unuse" function?

### ISSUE THREAD

**Issue by songispm** [markdown-it/markdown-it#956]
Can markdown-it provide a "unuse" function?

I found that I can enable a plugin with "use" function, but I can't disable the plugin manually.

Unless create another new instance.

**Comment by rlidwka** [comment]
Why not create a new instance?

If I remember correctly, markdown-it needs to recompile/reevaluate all rules (their ordering) when configuration is changed. So enabling and disabling plugin at runtime is not cheap.

And as far as I remember about how we use it in production, it is reasonable to have every plugin configuration with its own instance (using memoize to select the one you need).

**Comment by puzrin** [comment]
The package is not intended to be reconfigured on the fly. Please, create another instance.
