### ISSUE TITLE
Unable to resolve "entities/lib/maps/entities.json" from "../../node_modules/markdown-it/lib/common/entities.js"

### ISSUE THREAD

**Issue by alicesteban** [markdown-it/markdown-it#958]
iOS Bundling failed 1640ms
Unable to resolve "entities/lib/maps/entities.json" from "../../node_modules/markdown-it/lib/common/entities.js"

<img width="394" alt="Screenshot 2023-09-20 at 2 22 25 PM" src="https://github.com/markdown-it/markdown-it/assets/109953285/80c7b68e-af95-458b-af0a-f932dda62125">

"expo": "~48.0.18",
"react": "18.2.0",
"react-native": "0.71.8",

markdown-it version 10

**Comment by Armster15** [comment]
If it helps, installing the `entities` package with the version `3.0.1` fixed it for me
