### ISSUE TITLE
Line break in table cells

### ISSUE THREAD

**Issue by Redwaza** [markdown-it/markdown-it#961]
Are line breaks in table cells supported? I have tried all kinds of characters that come to mind for line breaks but nothing seems to work (.e.g. \n, <br />, <br>, \) Any help is highly appreciated.

**Comment by rlidwka** [comment]
Line breaks in table cells are not supported by this library.

Maybe you can look around for a plugin that does this, but I can't suggest any.

**Comment by Redwaza** [comment]
Ok, thanks a lot! I appreciate your quick response!

**Comment by puzrin** [comment]
Known workaround is enable html and use `<br>`. But in general, multiline content not supported in current table implementation (it should be equal to github)

**Comment by AndrewKvalheim** [comment]
Duplicate of #308
