### ISSUE TITLE
Using whitespace as a closing delimiter

### ISSUE THREAD

**Issue by Acumane** [markdown-it/markdown-it#962]
Having unique open and close delimiters are possible; if I replace `0x20` with `0x21` and the last `token.markup` to `"!"`, then `x^n!` works as expected: x<sup>n</sup>
```js
  ...
  
  while (state.pos < max) { // find closing whitespace
    if (state.src.charCodeAt(state.pos) === 0x20) {
      found = true; break
    }

    state.md.inline.skipToken(state)
  }

  ...

  // found!
  content = state.src.slice(start + 1, state.pos)

  state.posMax = state.pos
  state.pos = start + 1

  token         = state.push('sup_open', 'sup', 1)
  token.markup  = '^'

  token         = state.push('text', '', 0)
  token.content = content

  token         = state.push('sup_close', 'sup', -1)
  token.markup  = " "

  state.pos = state.posMax + 1
  state.posMax = max
  return true
  
  ...
```

But as per the snippet above, I cannot simply do the same with a space (`x^n `)

Does `token.markup` not accept whitespace? Is there something else I'm doing wrong?

**Comment by rlidwka** [comment]
`token.markup` is completely irrelevant

Possible issue is that skipToken will skip over spaces, because they are part of text token.

Maybe instead of skipToken, you'd just use `state.pos++`?

**Comment by Acumane** [comment]
Thank you! Closer now... if I use `state.pos++` *and* set `token.markup` empty (`''`), then I can get `x^n     a` to be x<sup>n</sup> a, but some non-whitespace character is required after


Also, I was able to get `x^[n + m]` = x<sup>n + m</sup>, but I cannot get `x^(n + m)` to work. Might this be a conflict with an existing rule? I'm currently using `md.inline.ruler.before('emphasis', ...`

**Comment by Acumane** [comment]
Barebones plugin example:
```js
module.exports = function sup_plugin(md) {
  md.inline.ruler.before('text', 'sup', (state, silent) => {
    let max = state.posMax, 
        start = state.pos

    if (state.src.charCodeAt(start) !== 0x3A /* : */) return false

    console.log(state.src) // want to see this printed

    while (state.pos < max) {
      // ...
      state.pos++
    }

    return true
  })
}
```

A character like the colon (`0x3A`) works fine. Switch it with, say, a zero (`0x30`), and it's only recognized if it appears at the beginning of a state string (`0test` but not `tes0t`); try a forward slash (`0x2F`), and it won't work anywhere.

**Comment by rlidwka** [comment]
Yes, [text rule](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/text.js) skips over these, because they are not expected to be tokens. This is intentional, and done for performance reasons.

> A character like the colon (0x3A) works fine.

But in your case the starting character of the rule is `^`, is it not?

**Comment by Acumane** [comment]
> But in your case the starting character of the rule is `^`, is it not?

In my first code snippet, yes. My last example doesn't look for any common delimiters.
That's a shame! How would you get around this?

**Comment by rlidwka** [comment]
Is it a public package, or your own project?

if it's inside your own project:
- disable text rule (this has performance penalties)
- or replace with a custom text rule

if you're writing a package that's used by others:
- explain in full detail what plugin you're writing, maybe we can include that character in text rule (but its very unlikely at this point due to stability concerns)
- maybe you can find other people that have similar issue, or already solved this

**Comment by Acumane** [comment]
Several public packages under one monorepo. Slightly dated, but spec ideas are [listed here](https://github.com/Acumane/jotdoc#readme)—open to feedback, ofc ^_^

A case without common tokens would be simple fractions, e.g. 1/2 → `<sup>1</sup>⁄<sub>2</sub>` → <sup>1</sup>⁄<sub>2</sub>

**Comment by puzrin** [comment]
Close - possible resolutions explained.
