### ISSUE TITLE
A proper plugin documentation for Markdown-it

### ISSUE THREAD

**Issue by ByPikod** [markdown-it/markdown-it#963]
Markdown-it is a very useful library, but its developer(s) provide the worst answer to the question of "how to create a plugin."

While looking into this, I found an older discussion where things got really unpleasant between developers and users, with a lot of arguing. I want to make it clear that I'm not bringing this up to start another argument.

The main point I want to emphasize is that I believe Markdown-It truly needs proper plugin documentation. As mentioned at the beginning of my writing, the documentation for example plugins, as described in the issue, is very weak. Therefore, it is quite challenging to read the code.

I am confident that senior developers like Markdown-It's developers will have no difficulty in understanding this code. However, the absence of documentation is a severe issue for junior developers.

If Markdown-it starts answering the question "How to create a plugin?" the community can produce more extensions, and support for more markdown syntax can be expanded.

The purpose of creating this issue, as I stated initially, is not to bring up an already discussed topic. Markdown-It has a deficiency, and I am aware of it. I cannot do anything to address this deficiency. I'm sure there are many developers like me. If no one insists on implementing this feature, **developers may think that this feature is not essential**. That's precisely why I'm opening this issue.

**Comment by puzrin** [comment]
IMHO this is not right place to encourage maintainers. Support is provided according to existing possibilities, "as is".

**Comment by RealAlphabet** [comment]
> IMHO this is not right place to encourage maintainers. Support is provided according to existing possibilities, "as is".

Where is the right place to do it?

**Comment by puzrin** [comment]
> Where is the right place to do it?

May be on generic programming forums. We can't keep "endless" issues without clear resolution criteria and without plans to resolve.
