### ISSUE TITLE
Reconstruct Markdown document from the tokens?

### ISSUE THREAD

**Issue by laurent22** [markdown-it/markdown-it#965]
I'm trying to parse a large number of Markdown documents - in each I need to make a few tweaks so that they match a certain spec. For example, all `<br>` tags must be closed as `<br/>`, certain HTML entities must be encoded, etc.

I got that working by creating a custom plugin and processing the tokens. But now I would like to rebuild the Markdown document but can't quite figure out how to do that. Is there an existing method that can be used to rebuild the document from the tokens? Otherwise what would be the method to do so?

I tried to loop through them and do something different depending on the token type, but that's tedious since each type must be handled separately with all kind of special treatments, and even when doing this newlines and white spaces tend to be messed up.

Any idea what would be the right approach?

**Comment by moki** [comment]
@laurent22 as far as i am aware markdown-it deliberately doesn't support markdown as a generator target.

I similarly faced the need to render markdown back to markdown after arbitrary token transformations in my projects.

*sorry for the shameless plug*

So i ended up implementing markdown renderer: [markdown-it-markdown-renderer](https://github.com/diplodoc-platform/markdown-it-markdown-renderer)

you can use it as markdown-it plugin(really minimal example in the README)

more in depth examples - (custom + md) renderer: [one](https://github.com/diplodoc-platform/markdown-translation/blob/main/src/skeleton/renderer.ts) [two](https://github.com/diplodoc-platform/markdown-translation/blob/main/src/markdown/renderer.ts), custom renderer: [one](https://github.com/diplodoc-platform/markdown-translation/blob/main/src/xlf/renderer.ts)

it is based on my other project [markdown-it-custom-renderer](https://github.com/diplodoc-platform/markdown-it-custom-renderer)

which allows you to attach to different "life cycles": before/after render, before/after inline render, before rendering specific rule(like text, image, or w/e) etc.

**Comment by moki** [comment]
@laurent22 actually it is production ready and in cases of not having zero diff it has semantic zero diff.

may i ask you to please open issues in the project itself if you really have cases of it breaking markdown syntax in the way that it breaks final html render?

because as far as i am aware thats not the case and library has commonmark test suit.

**Comment by laurent22** [comment]
This:

```
<img src="https://example.com/img.png"/>

# Image and header
```

will be rendered as this:

```
<img src="https://example.com/img.png"/>
# Image and header
```

which doesn't render to the same HTML, at least not in GitHub, StackOverflow or any other renderer I tried.

**Comment by moki** [comment]
@laurent22 thanks for the good catch.

unfortunately html doesn't get enough love from me since we are not big on mixing it with the markdown.

opened an issue to fix it: https://github.com/diplodoc-platform/markdown-it-markdown-renderer/issues/83

**Comment by puzrin** [comment]
Unfortunately, current design has no AST with full source info and not suitable well for source restore. Tokens have some info about initial source, and some project tries to use it. But this is on your own risk only.
