### ISSUE TITLE
Linkify breaks simple italics syntax

### ISSUE THREAD

**Issue by simov** [markdown-it/markdown-it#966]
Hi,

I found that when linkify is enabled (which is the default) a simple italics markup does not work:

```md
_Linkify breaks italics: https://github.com/markdown-it/markdown-it_
```

It is a bit hard to compare commonmark with markdown-it since the first does not implement rendering of raw URLs, but same thing gets rendered correctly with marked, remark, here on GitHub and in Sublime Text.

> _Linkify breaks italics: https://github.com/markdown-it/markdown-it_

- commonmark - https://spec.commonmark.org/dingus/?text=_Linkify%20breaks%20italics%3A%20https%3A%2F%2Fgithub.com%2Fmarkdown-it%2Fmarkdown-it_
- markdown-it - https://markdown-it.github.io/#md3=%7B%22source%22%3A%22_Linkify%20breaks%20italics%3A%20https%3A%2F%2Fgithub.com%2Fmarkdown-it%2Fmarkdown-it_%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

**Comment by puzrin** [comment]
This is a known trade-off for rare case, because it's impossible to determine end of link 100% right for all possible uses. Discussed somewhere in previous issues.

Workaround is to use explicit link makup `< >`
