### ISSUE TITLE
Replace Node's deprecated punycode

### ISSUE THREAD

**Issue by bcomnes** [markdown-it/markdown-it#967]
Importing `markdown-it` into Node.js triggers a warning now:

```console
node:11893) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
```

Looks like anything relying on Node.js's punycode implementation should switch to a userland implementation. 

https://github.com/markdown-it/markdown-it/blob/e476f78bc3ea3576beb61bdc94322d0a6b2d85cc/lib/index.js#L14

Let me know if you want a PR.

**Comment by philoserf** [comment]
see also: https://github.com/DavidAnson/markdownlint-cli2/issues/234 and https://github.com/igorshubovych/markdownlint-cli/issues/437 and https://github.com/DavidAnson/markdownlint/issues/1032

**Comment by philoserf** [comment]
Thank you. Most downstream users will not get an update until we tag/release.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/pull/863#issuecomment-1837022282 in progress.

**Comment by ljharb** [comment]
@puzrin any chance this could be backported to v13? I'm stuck on a dep chain that requires markdown-it unfortunately pinned at 13.0.1, via markdownlint@"~0.29.0" - but if markdown-it v13 avoids this deprecation warning, then i can try to ask markdown-lint to backport it to v0.29.

**Comment by rlidwka** [comment]
@ljharb I don't think we do any backports usually. :(

Latest `markdownlint@0.34.0` does depend on `markdown-it@0.14.1`, can you check if you can use that instead?

Alternatively, you can temporarily backport the change yourself until the dep chain situation is resolved. I'm not familiar with this, but surely there must be *some* tools that allow patching transitive dependencies in npm ecosystem (similar to rust cargo's `[patch]` section).

**Comment by ljharb** [comment]
@rlidwka i might, but i'm pinned to markdownlint on v0.29.0 for a reason I can't recall right now.

Patching deps is certainly doable but it's a very bad idea; i'd rather just ignore the deprecation warning for the time being.

Backports aren't difficult; I'm happy to do it if you're willing :-) in this case it's just changing `'punycode'` to `'punycode/'` and adding the package dep.
