### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'references')

### ISSUE THREAD

**Issue by TinyWisp** [markdown-it/markdown-it#968]
I tried to use the `MarkdownIt.parse`  method to parse markdown documents, and I found some texts, that are rendered well, could lead to the error below.

![image](https://github.com/markdown-it/markdown-it/assets/15992102/0766db08-ccf2-4209-b4ec-14a1b6e0735b)

if I followed the first link in the error above, it would bring me here

![image](https://github.com/markdown-it/markdown-it/assets/15992102/d8fb4ca0-2aa4-41d1-a833-e158ccdbd323)
 

the texts that lead to the error
```
![Alt text][id]

With a reference later in the document defining the URL location:

[id]: https://octodex.github.com/images/dojocat.jpg  "The Dojocat"
```

```
### [Footnotes](https://github.com/markdown-it/markdown-it-footnote)

Footnote 1 link[^first].

Footnote 2 link[^second].

Inline footnote^[Text of inline footnote] definition.

Duplicated footnote reference[^second].

[^first]: Footnote **can have markup**

    and multiple paragraphs.

[^second]: Footnote text.
```

version: 13.0.2

**Comment by puzrin** [comment]
You probably missed mandatory `env` param

https://github.com/markdown-it/markdown-it/blob/8470eb6706bda0d8fa79c4d54d115260de305d59/lib/index.js#L544
