### ISSUE TITLE
Run ./benchmark/benchmark.js does not work

### ISSUE THREAD

**Issue by kliu57** [markdown-it/markdown-it#970]
**Bug**: The step `Run ./benchmark/benchmark.js` in [CONTRIBUTING.md](https://github.com/markdown-it/markdown-it/blob/e476f78bc3ea3576beb61bdc94322d0a6b2d85cc/CONTRIBUTING.md) does not work.

**Screenshot of error**:
![error screenshot](https://github.com/markdown-it/markdown-it/assets/98062538/c0444cf8-ce41-482b-a404-97af80027ea0)

**Reasons for Error**:

- In three places in the project files there are references to `../../extra/lib/node_modules` however this directory does not exist. The directory that has `node_modules` is actually `../../../node_modules`

![problematic code screenshot](https://github.com/markdown-it/markdown-it/assets/98062538/35658d9e-2268-4974-8b54-f58ce0e9a31d)

- Some modules need to be installed with `npm` prior to running `./benchmark/benchmark.js`. This includes `benchmark`, `commonmark`, `marked`.

**Proposed Fix**:

- Fix the project files in those three places mentioned above to have the correct path to node_modules
- Add instructions to [CONTRIBUTING.md](https://github.com/markdown-it/markdown-it/blob/e476f78bc3ea3576beb61bdc94322d0a6b2d85cc/CONTRIBUTING.md) to tell contributors to do `npm install` on above mentioned modules prior to running ./benchmark/benchmark.js.

Screenshot of `./benchmark/benchmark.js` successfully running after the proposed fix:

![image](https://github.com/markdown-it/markdown-it/assets/98062538/18ad3923-52a8-43ad-a955-e1c29857ae88)

Please assign this fix to me if these changes look ok.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/pull/971#issuecomment-1817528030
