### ISSUE TITLE
Pause animated gifs

### ISSUE THREAD

**Issue by aigan** [markdown-it/markdown-it#975]
Animated gifs can be fairly distracting for people with certain cognitive disabilities such as autism. For quite a few people, animations are so distracting, it is essentially impossible for them to read the text. 

VS Code has ignored the accessibility request for being able to stop animated gifs inside Electron.
As also stated in https://github.com/microsoft/vscode/issues/134514

**Comment by rlidwka** [comment]
What are you suggesting exactly, and what does it have to do with markdown-it?

**Comment by puzrin** [comment]
Probably posted in wrong repo. This issue is about presentation, that's customized at user side.
