### ISSUE TITLE
value of alt attribute in image token is empty

### ISSUE THREAD

**Issue by kilgarenone** [markdown-it/markdown-it#976]
* [Sample](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22!%5Balt%5D%28https%3A%2F%2Fwww.hostinger.com%2Ftutorials%2Fwp-content%2Fuploads%2Fsites%2F2%2F2021%2F10%2Fwhat-is-a-permalink.webp%29%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22debug%22%7D%7D)

```js
    "nesting": 0,
    "level": 1,
    "children": [
      {
        "type": "image",
        "tag": "img",
        "attrs": [
          [
            "src",
            "https://www.hostinger.com/tutorials/wp-content/uploads/sites/2/2021/10/what-is-a-permalink.webp"
          ],
          [
            "alt",
            "" // should it be 'alt' string here?
          ]
        ],
...
```

**Comment by puzrin** [comment]
By CM spec, `alt` can have markup inside (i know, that's very strange). So, it can't be stored in attr value (those are for plain values). I don't remember full details, but you can dig in image renderer/rule.

**Comment by rlidwka** [comment]
By CM spec, images are the same as links. This is an example from cmark:

```md
[markup](link "title")
![markup](image "title")
```

```html
<link destination="link" title="title">
  <text>markup</text>
</link>
<image destination="image" title="title">
  <text>markup</text>
</image>
```

Then markup gets folded into string at render time. "alt" you see is just a placeholder for where that markup will end up.
