### ISSUE TITLE
Add GFM comments

### ISSUE THREAD

**Issue by emilioplatzer** [markdown-it/markdown-it#98]
In github HTML comments are invisible. 

Is there a way to do the same in markdown-it? 

Can I pass some option to render or to the object to get the same GFM behavior? 

Can you include It?

```
# markdown example

<!-- comment -->

here
```

**Comment by puzrin** [comment]
You should enable [html](https://markdown-it.github.io/#md3={%22source%22%3A%22%23%20markdown%20example\n\n%3C!--%20comment%20--%3E\n\nhere\n%22%2C%22defaults%22%3A{%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22}}), that is off by default for security reasons.
