### ISSUE TITLE
Vue Error with new version Can't import the named export 'P' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by erdidoqan** [markdown-it/markdown-it#980]
After the new update came, I started not being able to use markdownit. I show the error message with the screenshot below. I'd be very happy if someone could help.

<img width="842" alt="Ekran Resmi 2023-12-09 23 46 09" src="https://github.com/markdown-it/markdown-it/assets/6223609/94b38d3d-278f-45ae-aae4-7fff9fd3f6b0">

**Comment by puzrin** [comment]
No ideas about third-party tools, that's a bit out of scope. Try to use old style CJS `require()` or create a minimal possible test repo to reproduce.

**Comment by nbutmickey** [comment]
i have same questions in Taro 
<img width="1290" alt="image" src="https://github.com/markdown-it/markdown-it/assets/30484035/5354fbe0-acaa-4fda-9d27-18787ef05eec">

**Comment by puzrin** [comment]
As a workaround, you can try to use pre-build `dist/markdownit.js`. Then, could you write to the authors of your bundler, about why they do not support named exports in ESM modules?

**Comment by nbutmickey** [comment]
> As a workaround, you can try to use pre-build `dist/markdownit.js`. Then, could you write to the authors of your bundler, about why they do not support named exports in ESM modules?

wo solved it, thanks

**Comment by zy-zhiyuan** [comment]
@nbutmickey 请问怎么处理的？我这边也遇到了同样问题，十分感谢
