### ISSUE TITLE
Add Alerts

### ISSUE THREAD

**Issue by electriquo** [markdown-it/markdown-it#982]
[VSCode utilizes markdown-it and GitHub is moving toward the CommonMark specification](https://code.visualstudio.com/Docs/languages/markdown#_does-vs-code-support-github-flavored-markdown).

[GitHub added extension for Alerts](https://github.blog/changelog/2023-12-14-new-markdown-extension-alerts-provide-distinctive-styling-for-significant-content/), here is an example :)

```markdown
> [!NOTE]
> Useful information that users should know, even when skimming content.

> [!TIP]
> Helpful advice for doing things better or more easily.

> [!IMPORTANT]
> Key information users need to know to achieve their goal.

> [!WARNING]
> Urgent info that needs immediate user attention to avoid problems.

> [!CAUTION]
> Advises about risks or negative outcomes of certain actions.
```

> [!NOTE]
> Useful information that users should know, even when skimming content.

> [!TIP]
> Helpful advice for doing things better or more easily.

> [!IMPORTANT]
> Key information users need to know to achieve their goal.

> [!WARNING]
> Urgent info that needs immediate user attention to avoid problems.

> [!CAUTION]
> Advises about risks or negative outcomes of certain actions.

But Alerts it is yet available within VSCode (markdown preview/validation).

I hope that if this request will be accepted, all of us will be able to enjoy it when VSCode renders the markdown.

**Comment by puzrin** [comment]
We do not add non-CM syntax to core anymore. All extensions are expected to be implemented via plugins. I'd suggest to search existing plugins first. For example, there is https://github.com/ByPikod/markdown-it-github-alert (but I don't know how good is it)
