### ISSUE TITLE
Allow tree-shaking of unused rules and dependencies

### ISSUE THREAD

**Issue by memcorrupt** [markdown-it/markdown-it#983]
Since 14.0.0, this package is now an ESM module and should be much simpler to restructure to allow tree shaking to lower its contribution to the total bundle size. Because of the current internal architecture of this package, it is not possible for treeshaking to occur since all rules are imported even if they are not used.

Currently, the only way to receive a size benefit on unneeded rules is to patch the package to remove references to unneeded modules. Creating a seperate constructor/entrypoint to this library to allow granular addition of rules can allow more lightweight uses of this library.

**Comment by puzrin** [comment]
Sorry, no plans to change api/internals. This is commonmark parser first. Excluding some of default rules is a specific case, and will not add enough value for big changes.
