### ISSUE TITLE
Unsupported engine WARN EBADENGINE   current: { node: 'v16.20.1', npm: '8.19.4' }

### ISSUE THREAD

**Issue by arunkumar413** [markdown-it/markdown-it#984]
Hi Team,

I'm trying to install markdon-it but getting the below error:

```
arun@tuxnest:~/projects/doczilla$ npm install markdown-it
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'marked@11.1.0',
npm WARN EBADENGINE   required: { node: '>= 18' },
npm WARN EBADENGINE   current: { node: 'v16.20.1', npm: '8.19.4' }
npm WARN EBADENGINE }

```

**Comment by JeffJassky** [comment]
Having the same issue. it seems like one of the dependencies is the "tinyspawn" package. Not sure where it's being required but it can't run on node 16 in the meantime.

**Comment by puzrin** [comment]
This can be somewhere in dev deps. Those are not installed when you install package not directly but as project dependency. 

Just ignore those warnings. Also, node v16 should be EOL, worth to upgrade.
