### ISSUE TITLE
 Have you ever encountered the problem of going from <p> to <h1> during parsing?

### ISSUE THREAD

**Issue by ainightfool** [markdown-it/markdown-it#986]
I am working on a project similar to gpt.I use sse to gradually get the data, and then splice the latest data each time, and parse it through markdown-it. I will enter a string in p tag, but it will suddenly change to h1 tag, and finally restore to p tag.I confirm that the data returned to me by the backend does not have '#'.
<img width="574" alt="image" src="https://github.com/markdown-it/markdown-it/assets/12795601/0415994c-c5e4-417c-8eb0-6b279df3dd0f">
<img width="773" alt="image" src="https://github.com/markdown-it/markdown-it/assets/12795601/7d5682cf-f71b-4864-96d4-32c0ed548c16">

**Comment by puzrin** [comment]
`H1` can be caused also by `===` underline.

https://markdown-it.github.io/ - you can use sandbox to play with syntax and provide links to examples.
