### ISSUE TITLE
@types/markdown-it for ^14

### ISSUE THREAD

**Issue by deleonio** [markdown-it/markdown-it#992]
https://www.npmjs.com/package/@types/markdown-it?activeTab=versions

**Comment by puzrin** [comment]
Please, as in types repo, we do not maintain that package.

**Comment by deleonio** [comment]
Sorry, your package has no type definition within.

https://github.com/markdown-it/markdown-it/blob/master/package.json

It would only be in their interest to provide or update these for typescript.

**Comment by kintz09** [comment]
@deleonio Did you find a solution for types for this package? I need them as well. Looks like the latest version of `@types/markdown-it` is still version [13.0.7](https://www.npmjs.com/package/@types/markdown-it/v/13.0.7). How do we get these types updated?

**Comment by deleonio** [comment]
@puzrin @kintz09 they should reopen the issue.
