### ISSUE TITLE
Inserting a link in markdown with underscore

### ISSUE THREAD

**Issue by ElenaLevkova** [markdown-it/markdown-it#997]
We have local files in folders whose names begin with an underscore "C:\S3\\__test". 
When we try to paste this link into markdown, we get the wrong view: "C:\S3__test". 
The character combination "\_" is accepted by Markdown as escaping for "_", but should not be used in links. 

The expected behavior is that when copying and pasting links of this type, we will immediately receive the correct link "C:\S3\\__test" without making any changes to it.

**Comment by rlidwka** [comment]
That is not a link, it's a file path.

If you want to link to that file (and e.g. open it in the browser), it would look like this: `file:///C:/S3/__test`.

If you want to copy-paste arbitrary text (which may include escape sequences), this is exactly what code blocks are for:

```md
`C:\S3\__test`
```
